### ISSUE TITLE
Responsive Docs navbar

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1022]
The navbar for docs is not responsive on small/mobile screens. We should make it collapsible like this [example](https://getbootstrap.com/docs/3.3/examples/navbar/)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-297)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-297

**Comment by denis-yuen** [comment]
Obsolete due to drop-down
