### ISSUE TITLE
Support for Private Docker Images in Workflows

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1040]
We should add support for private docker images in workflows; today there is only support in it for tools.

See https://docs.dockstore.org/docs/publisher-tutorials/public-and-private-tools/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-5)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-5
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@coverbeck  This is more of a placeholder for your Firecloud integration work. 
We also need to make a design decision here (i.e. this is approaching the sound of one hand clapping stuff)

**Comment by coverbeck** [comment]
@agduncan94, @denis-yuen Thinking of closing this one and using #1384 . Or I can close that one and keep this one open....

Or do we also want to support sharing private workflows like we do with tools today, with the Request Access button (in addition to the FC integration work going on)?

**Comment by denis-yuen** [comment]
This is pretty non-specific. 
Does this mean private as in "hosted workflows that cannot be seen except via sharing" or private as in "workflows that are synced from private github repos"?

I think the latter is out of scope for this release.

**Comment by agduncan94** [comment]
I believe this was referring to the older concept of private workflows (https://docs.dockstore.org/docs/publisher-tutorials/public-and-private-tools/). Not sure exactly how this concept would be ported over to workflows.
