### ISSUE TITLE
Make Dockstore compatible with SevenBridges JSONified CWL

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1060]
### Desired behaviour

Looks like this is an example https://github.com/stevetsa/Metaphlan-SBCGC
It sounds like cwltool simply handles draft-2 workflows (specifically, `sbg:draft-2`), so we might not have to do much more than just trivially convert from JSON to YAML before feeding it through the rest of our code. 

Also reach out to seven bridges to get some more complete examples with parameter files.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-300)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-300
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
https://github.com/KnowEnG/KnowEnG_CWL might be promising since I believe they're in GA4GH-DREAM, but can probably also just look through https://github.com/search?utf8=%E2%9C%93&q=%22sbg%3Adraft-2%22&type=Code

**Comment by mr-c** [comment]
Good news JSON is a subset of YAML so no JSON→YAML conversion should be needed.

Bad news: we dropped support for `draft-2` in `cwltool` a while ago, so you'll either need to do your own upgrading or extend the standalone `cwl-upgrader`: https://github.com/common-workflow-language/cwl-upgrader

**Comment by mr-c** [comment]
FYI: https://github.com/sbg/sevenbridges-cwl-draft2-upgrader
