### ISSUE TITLE
Clarity/Request of 'Verified' flag

### ISSUE THREAD

**Issue by keiranmraine** [dockstore/dockstore#1065]
## Feature Request 

At present some tools have a 'verified' flag set which is seen in the search results but there is no clear indication of the criteria to get this 'badge' or anywhere for someone outside of the Dockstore admins to set it.

### Desired behaviour

Add the ability for someone to raise a "ticket" from the tool/workflow info pages.  It should indicate what verified means and what information is required for approval.

e.g.

You are independent from the team creating the tool and have successfully used it producing expected results.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-301)
┆Epic: Runtime Metrics
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-301
┆Sprint: 113 - Liao
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Currently, a user can click on a verified checkmark to get to https://dockstore.org/docs/faq#what-is-a-verified-tool-or-workflow- which explains it.  The ability to raise a request/ticket to get verified on non-verified tools, maybe by automatically creating a discourse or github issues thread would be a good idea

**Comment by keiranmraine** [comment]
Ah so you have to click on it or mouse over to see what it is.  Could a button be added in the tool details when a tool has not been verified, say, 'Verify this tool', or "works for me+" (if logged in).  That would make it more clear that a user can influence this by raising an issue or discourse thread.

**Comment by denis-yuen** [comment]
Yeah, I think that both would be pretty useful.

**Comment by denis-yuen** [comment]
@coverbeck can delegate, but would be a good nicety 
(e.g. tracking who "vouches" for particular workflows)
