### ISSUE TITLE
Slightly Confusing Labeling on Versions Tab

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1079]
On My Tools, there is a Tab named `Versions`, and in the table there is a column named `Version`. To create a new row, you click `Add Tag`, but `tag` is not mentioned anywhere else in the page. The Add Tag dialog does have a `Version Tag` label, but overall I find this mildly confusing.

Should the `Add Tag` button be renamed to `Add Version`, or should the `Versions` tab and `Version` column header be renamed to Tag(s)?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-302)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-302

**Comment by denis-yuen** [comment]
I think Version would be better than Tag

**Comment by coverbeck** [comment]
Also see #1050 -- you can get an `invalid tag` error with the dockstore tool. And responses from the API have a `tags` property.

Even though we may change the message in #1050, I'm thinking we should consider the wording in a larger sense, and not based with just what is on this page.

**Comment by denis-yuen** [comment]
I think I'm ok with either really, I agree that it would be nice to be consistent, but I think we basically inherited the inconsistency.

```
Image[:tag]
While not strictly a means of identifying a container, you can specify a version of an image you’d like to run the container with by adding image[:tag] to the command. For example, docker run ubuntu:14.04.
```
https://docs.docker.com/engine/reference/run/#pid-equivalent

**Comment by denis-yuen** [comment]
Still a thing

**Comment by Ldcabansay** [comment]
#2274 also related
