### ISSUE TITLE
Ignore null properties during serialization

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1092]
## Feature Request 

Currently we have swagger models in Java that when serialized by the current object mapper, returns a JSON that may potentially have null values.  Protobuf straight up discourages null types.  Our current swagger.yaml for TRSV does not have nullable types (although it was previously injected via a script) which means the webservice will fail validation if TRSV encounters a null value anywhere.  

There's an option to globally skip over properties with null values and simply not include those in serialization.  See https://github.com/ga4gh/dockstore/blob/feature/trsv_changes/dockstore-webservice/src/main/java/io/dockstore/webservice/DockstoreWebserviceApplication.java#L222 for how to do it.  This would require a bit of testing.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-303)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-303

**Comment by coverbeck** [comment]
@garyluu Is this still relevant now that protobuf has been removed from TRS? Charles & Denis

**Comment by garyluu** [comment]
Swagger 2.0 still discourages null but there are still ways to represent that the type is nullable.  OpenAPI 3.0 allows nullable.  So...up to us whether to keep it or not.
