### ISSUE TITLE
UI2 docs.component.spec.ts tests disconnects chrome

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1102]
## Bug Report
When UI2 is being tested on Travis, sometimes Chrome(headless) is disconnected.

Here is an overview of the issue with links to some ways to mitigate it:
https://gitlab.com/gitlab-org/gitlab-ce/issues/33784

From what I gather, here's some options that might help:
- ~Run headless chrome~
- Use async in tests
- Update Jasmine-core
- Increase timeout

Updating Jasmine might be the best solution:
https://github.com/angular/angular/issues/17543

### Expected behaviour
Karma test on UI2 runs on Travis deterministically without being disconnected.

### Actual behaviour
Actual Karma test on UI2 runs on Travis but sometimes disconnects.

### Steps to reproduce the behaviour 
Run UI2 on Travis multiple times

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-304)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-304

**Comment by garyluu** [comment]
On second thought, this might be a legitimate bug from dockstore-ui2 because locally it directs to the doc page.

**Comment by garyluu** [comment]
It appears docs.component.spec.ts is the problem.  It redirects to the docs.dockstore.org site which causes tests to fail

**Comment by denis-yuen** [comment]
test is not present
would be better to be present, but not worth keeping this open really
