### ISSUE TITLE
Unify 'tool' and 'workflow' entries in terms of UI and user interaction with them

### ISSUE THREAD

**Issue by junjun-zhang** [dockstore/dockstore#1103]
## Feature Request 
From a user's perspective, the similarity between `tool` and `workflow` is overwhelming, particularly the way to run them is identical. A `tool` can be thought as a special case of a `workflow`, it's a workflow with one tool. A general workflow consists of one or more tools.

### Desired behaviour
- no need to search them separately
- no need to render a Dockstore entry differently depending on it's a tool or workflow, using the current workflow page, a tool should be able to fit in.
- no need to register tool and workflow differently

Note: this maybe ambitious, but harmonizing handling tool and workflow could yield long lasting benefits for Dockstore app and users. Additionally, it could be in line with GA4GH TRS specification which does not seem to differentiate tool and workflow. They are all just `tool`, although personally I prefer using `workflow`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-305)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-305
┆Epic: Entity Consistency

**Comment by cricketsloan** [comment]
Possibly a duplicate to DOCK‌-309

**Comment by melainalegaspi** [comment]
reopen if needed
