### ISSUE TITLE
Add dockstore registration configuration file (.dockstore.yaml) in workflow/tool GitHub source repo

### ISSUE THREAD

**Issue by junjun-zhang** [dockstore/dockstore#1105]
## Feature Request 
It would be nice to introduce the concept of dockstore configuration file. Similar to how `.travis.yml` file is used for Travis CI.

In the `.dockstore.yaml` file, authors can put the information needed in order to have the tool/workflow registered in Dockstore. For example, entry point CWL file, path, preferred name, intended version tags to be registered, documentation, labels, test parameter jsons etc etc. It also opens possibility to expand in the future.

Note the `.yml` is not officially recommended extension for YAML file, `.yaml` is. https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml/21059164

### Desired behaviour
With this `.dockstore.yaml` file available in the tool/workflow's GitHub source code, it's very easy to automatically register it into Dockstore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-306)
┆Issue Type: Story
┆Issue Number: DOCK-306

**Comment by denis-yuen** [comment]
See also ##1127
