### ISSUE TITLE
Misleading Error Message When Refreshing Workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1116]
## Bug Report

If there is an error refreshing workflows because your GitHub token doesn't have the correct scope, the error message says it failed `trying to create/modify`, which could be read as Dockstore was trying to modify something in your GitHub account.

### Expected behaviour

If refreshing workflows fails due to an authorization issue, the error message should not say it was trying to create or modify anything.

### Actual behaviour

It says it was trying to `create/modify`.

### Steps to reproduce the behaviour 

To reproduce this, you have to be in a state where your GitHub token is missing a scope. I don't know how you into that state, but once you are:

1. Go to `My workflows`
2. Click on `Refresh All Workflows`

See following error screen:

<img width="1210" alt="screen shot 2018-01-17 at 4 15 38 pm" src="https://user-images.githubusercontent.com/1049340/35117280-0fe83d1a-fc43-11e7-99e8-dba907a233d3.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-202)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-202

**Comment by denis-yuen** [comment]
Reproduction: you'll want to reverse https://github.com/dockstore/dockstore-ui2/pull/160 to login with an older token

**Comment by cricketsloan** [comment]
Why is this not syncing

**Comment by coverbeck** [comment]
If Angular had [this feature](https://github.com/angular/angular/issues/25577) implemented, we could do more context aware alert messages in alert-service, e.g., if the request were a GET, then we would there was no attempt to modify anything.

**Comment by denis-yuen** [comment]
Punting to next version since this is in backlog

**Comment by NatalieEO** [comment]
For a simple fix, how about just getting rid "create/modify" entirely for all error messages. I don't think it's helpful or relevant often times. Also getting rid of the http status codes?

**Comment by denis-yuen** [comment]
I think getting rid of create/modify is fine, its usually not useful. 
I do like keeping the http status codes, makes bug reports (user or other-wise) more helpful.
