### ISSUE TITLE
Consistent property names between tools and workflows

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1125]
Currently in tools, we have the idea of path and tool_path, representing the tool path without and with the toolname.

In workflows, we have the same concepts, however we already use the term workflow_path to represent the default descriptor path. For now I'll have workflow.path == tool.path and workflow.full_workflow_path == tool.tool_path.

We will need to rename workflow.full_workflow_path to workflow.workflow_path and find a new name for the existing workflow.workflow_path.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-231)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-231
┆Epic: Entity Consistency

**Comment by denis-yuen** [comment]
Oh, this is in the web service, not the ui2.
That might make things tricker because we have to consider backwards compatibility

**Comment by melainalegaspi** [comment]
reopen if needed
