### ISSUE TITLE
Flatten search tools and workflows into one

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1130]
For the average person using search, who is probably looking for a tool or workflow to run, whether it is a tool or workflow does not really matter. In fact, it may confuse new users. In reality, they just see it as a piece of software they can use, and not a tool or workflow.

We could flatten the two lists into one, and add a column for type. That way for people who care, like workflow/tool developers, they can see the difference in the search. They can also still filter by tool or workflow.

Removing the tools and workflows top level pages themselves would also go well with this, removing any confusion of what is a tool vs a workflow when people first navigate to the site (since lots of people seem to have this). These two pages would just be replaced some sort of listening of both tools and workflows, perhaps popular, perhaps featured.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-309)
┆Issue Type: Story
┆Issue Number: DOCK-309

**Comment by denis-yuen** [comment]
I agree, I think the distinction for tools and workflows is more significant for workflow developers. 
It is not as significant for search.

**Comment by garyluu** [comment]
Kind of similar to https://github.com/ga4gh/dockstore/issues/1103

**Comment by denis-yuen** [comment]
Probably depends on the definition of user

**Comment by denis-yuen** [comment]
Duplicates #1103
