### ISSUE TITLE
Comprehensive solution for $include, and $import

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1155]
### Desired behaviour

Follow-up for #1150 

As of 1.3.4, we'll have partial support for `$mixin`, `$import`, and `$include`. This works for launching, refreshing to pick up secondary files, and for harvesting descriptions.

A more comprehensive implementation will need to be done in 1.4.0 to make sure it works in other situations like authorship.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-312)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-312
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
See also #953

**Comment by agduncan94** [comment]
Also consider https://github.com/ga4gh/dockstore/blob/1.4.0/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/CWLHandler.java#L271 DAG handling will need to consider this

**Comment by denis-yuen** [comment]
No more mixin in CWL 1.1 apparently
https://gitter.im/common-workflow-language/common-workflow-language?at=5d812a6362bfc95112069e1a

**Comment by coverbeck** [comment]
@svonworl FYI
