### ISSUE TITLE
Checker workflow DB and migration

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1166]
### Desired behaviour

- New DB structure and migration
- migrations.test.xml should also get a couple workflows based on the examples for testing

**Comment by agduncan94** [comment]
Note to self. Migrations for structure done, need to add migrations with sample workflows.

**Comment by agduncan94** [comment]
Ended up using actual endpoint calls instead of storing the workflows in migrations. Refresh is never called on all tools, only a specific tool so the impact on rate limit should be negligible.

**Comment by agduncan94** [comment]
The next steps for this ticket is to create example an example WDL workflow with a checker workflow (probably md5sum again).

**Comment by agduncan94** [comment]
Done in https://github.com/ga4gh/dockstore/pull/1247
