### ISSUE TITLE
Figure out if it is possible to not mock database objects in Cypress testing

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1184]
Currently for testing we have some mocks (such as for the mytools Amazon ECR test) which need to be updated as the JPA model changes. It would be nice if there were some way to have these stored in the database so that they aren't broken by changes to the JPA.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-315)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-315

**Comment by melainalegaspi** [comment]
reopen if needed
