### ISSUE TITLE
Dockstore Tool Publish Message Unintuitive

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1216]
## Feature Request 
Make the publish command more intuitive

### Desired behaviour
The current output of the help command is:
```
See https://www.dockstore.org for more information

Usage: dockstore tool publish --help
       dockstore tool publish
       dockstore tool publish [parameters]
       dockstore tool publish --unpub [parameters]

Description:
  Publish/unpublish a registered Tool.
  No arguments will list the current and potential Tools to share.
Required Parameters:
  --entry <entry>             Complete Tool path in the Dockstore (ex. quay.io/collaboratory/seqware-bwa-workflow)
  --entryname <Toolname>      Toolname of new entry

---------------------------------------------
```
1. The required parameters show `--entryname` as required but https://github.com/ga4gh/dockstore/blob/develop/dockstore-integration-testing/src/test/java/io/dockstore/client/cli/GeneralIT.java#L402 indicate it works without it
2. The publish description doesn't quite explain what the --entryname parameter is used for.  Says "Toolname of new entry", but the user's intention was probably to just publish/unpulish their current tool.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-203)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6.x
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-203

**Comment by denis-yuen** [comment]
`dockstore tool list` and `dockstore tool search` both probably need some reworking. 
Should they match public listings or take advantage of your token? (Or be parameterizable)
Maybe merge into `dockstore list` and `dockstore search`

**Comment by denis-yuen** [comment]
Can also check out whether other changes might be more intuitive

**Comment by cricketsloan** [comment]
Why is this not syncing?

**Comment by Ldcabansay** [comment]
for tools:
`--entryname` registers a new tool based off `--entry` with a new name ex:
```
dockstore tool publish --entry quay.io/ldcabansay/toolpotato --entryname foopotato
```

for workflows:
`--entryname` currently doesn't work like it does for tools, but has the same help message which is misleading and needs to be changed. For example, when running: 
```
dockstore workflow publish --entry dockstore.org/geezlooueez/granularPotato --entryname delme
```
the following error message is given:
```
16:58:14.258 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Unable to publish delme
16:58:14.260 [main] ERROR io.dockstore.client.cli.ArgumentUtility - io.swagger.client.ApiException: Missing the required parameter 'workflowRegistry' when calling manualRegister
	at io.swagger.client.api.WorkflowsApi.manualRegister(WorkflowsApi.java:1005)
	at io.dockstore.client.cli.nested.WorkflowClient.handlePublishUnpublish(WorkflowClient.java:660)
	at io.dockstore.client.cli.nested.AbstractEntryClient.publish(AbstractEntryClient.java:454)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:242)
	at io.dockstore.client.cli.Client.run(Client.java:709)
	at io.dockstore.client.cli.Client.main(Client.java:611)
```

**Comment by denis-yuen** [comment]
Not to self: this is underway in Ferry

**Comment by Ldcabansay** [comment]
For workflows the following command doesn't work because it is a hosted workflow and dockstore is not a valid 'workflowRegistry'. 

```
dockstore workflow publish --entry dockstore.org/geezlooueez/granularPotato --entryname delme
```

**Comment by Ldcabansay** [comment]
Workflow bug logged in #2309

**Comment by denis-yuen** [comment]
@Ldcabansay issue still alive?

**Comment by Ldcabansay** [comment]
> @Ldcabansay issue still alive?

@denis-yuen I made the PR, but going by the date I assume this was in 1.6.0. Issue should've closed during the verification process.
