### ISSUE TITLE
Cromwell Resolve Relative Path of Files

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1260]
### Expected behaviour
Relative paths defined in the WDL .json parameter file should be relative to the .json file, similar to cwltool behaves and how dockstore cwl launchers behave.

### Actual behaviour
Relative paths defined in the .json parameter file are relative to the user's current working directory

### Steps to reproduce the behaviour 
- `git clone git@github.com:ENCODE-DCC/pipeline-container.git`
- `cd pipeline-containers`
- `dockstore workflow launch --local-entry local-workflows/encode_mapping_workflow.wdl --json local-workflows/encode_mapping_workflow.wdl.json --script`
Resolves the file to `pipeline-container/input_data/ENCFF000VOL.fastq.gz` instead of `local-workflows/pipeline-container/input_data/ENCFF000VOL.fastq.gz`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-322)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-322

**Comment by melainalegaspi** [comment]
This may be a complicated review ticket

**Comment by melainalegaspi** [comment]
@garyluu Please review this work and add more info to description
