### ISSUE TITLE
Make better use of loading indicators

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1302]
I noticed that while the UI is waiting for data, whether it be my tools, my workflows, or search, instead of showing a loading indicator/icon we don't show anything. For example for my tools when you load the page you see white and then a seemingly randomly placed 'Add Tool' button. It would make sense to just have a loading indicator and not even show the 'Add Tool' button until the my tools have been retrieved.

Another example is with the tools page. When datatable is loading the tools, you see the table header but then the rest is just blank. A loading icon here would be good.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-324)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-324

**Comment by denis-yuen** [comment]
Duplicates #893

**Comment by denis-yuen** [comment]
Interesting reading https://developers.google.com/speed/pagespeed

**Comment by denis-yuen** [comment]
Loading indicators are present now
