### ISSUE TITLE
Better message when trying to register a tool as a workflow (or vice versa)

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1319]
### Desired behaviour

Right now, it just silently adds no files to a workflow.
We should probably have a better warning message with the caveat that we don't want to break refresh by org or refresh all.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-329)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-329

**Comment by denis-yuen** [comment]
Should use the new validation framework

**Comment by agduncan94** [comment]
Confirmed that this works as of 1.9.0-alpha.3 and 2.5.1-rc.1
