### ISSUE TITLE
Confidential test migration tracking

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1361]
So it seems like we can't add a tracked file to a gitignore and expect it to not track the changes. The workaround might be with the maven resources plugin (https://maven.apache.org/plugins/maven-resources-plugin/examples/include-exclude.html).

The gist of what to do is to
a) Ignore the confidential files in the git ignore
b) Have the stub confidential files exist, however with different names (ex. migration.test.confidential1.stub.xml)
c) Remove or exclude the confidential files from the copying of resources to target so that they aren't packaged, and copy the stubs into the correct location. This is done with the maven resources plugin.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-334)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-334

**Comment by denis-yuen** [comment]
Elaborating on requirements:
1) The confidential migrations should not show up in `git status` or `git diff` but can be used locally when running tests 
2) The confidential migrations should survive branch changes and checkouts
3) They should not make it into the resulting jar
