### ISSUE TITLE
Improve DOS File Provisioner (DRS API)

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1373]
## Feature Request 
Similar to the s3 plugin, add a file provisioner that can resolve and provision [DOS URIs](https://github.com/ga4gh/data-object-service-schemas).

An example DOS URI is `dos://dos-dss.ucsc-cgp-dev.org/fff5a29f-d184-4e3b-9c5b-6f44aea7f527?version=2018-02-28T033124.129027Z`

cc: @rjbautis

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-1)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1
┆Sprint: Backlog
┆Issue Type: Epic

**Comment by coverbeck** [comment]
Plugin should use https://commons.apache.org/proper/commons-vfs/filesystems.html or other file provisioning plugins as appropriate to fetch the underlying URLs.

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

This has the student working on this Ryan
