### ISSUE TITLE
Update TRS API to search by Labels

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1385]
## Feature Request 

```
GUIDs for tools from KC2
Look to see if labels are searchable
Alias instead of labels?
Add to search
Get some examples
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-336)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-336

**Comment by melainalegaspi** [comment]
reopen if requested
