### ISSUE TITLE
Versions box non-existent on mobile

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1393]
If you are on mobile looking at a public entry, the only way to change the version is by going to the versions tab. Maybe for smaller screens we should use the same dropdown we have on my tools/my workflows.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-341)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-341

**Comment by melainalegaspi** [comment]
reopen if significant mobile traffic
