### ISSUE TITLE
Can't get git reference for quay tool tags that have since been deleted

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1412]
https://quay.io/repository/agduncan94/checker-md5sum?tab=tags
There are 4 tags on quay - latest, master, develop and feature_file-cleanup

https://github.com/dockstore-testing/md5sum-checker
Only 2 branches exist on Github - master and develop

What happened was I deleted the feature/file-cleanup branch on Github, which is the branch pointed to by quay tag feature_file-cleanup. So when we try to find if the git reference feature_file-cleanup is a branch or not, we can't find the reference on Github so the referenceType stays as UNSET.

A possible solution for this is to record the commit id too.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-346)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-346
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
Thinking about this, this may be an issue for workflows too if feature branches are created and deleted.
We may want to record commit ids across the board both for this issue and to indicate which version of the documents we currently store (this may be unclear if someone is rapidly iterating a workflow while working in a branch)

**Comment by denis-yuen** [comment]
This can also be an optimization in some ways
(i.e. don't refresh tags or branches if the commit id has not changed since last time)

**Comment by agduncan94** [comment]
I think for workflows what would happen is we would just deleted the version on dockstore if it has no matching remote branch.

**Comment by denis-yuen** [comment]
Yes, but I could imagine that could still be frustrating if a user has encountered a workflow, found a version of it, but couldn't figure where it came from because the workflow author has since deleted it from GitHub (but not removed it from Dockstore yet). 
A commit id would help prevent this problem because while branches get deleted, commit ids usually are not (barring some rebase trickiness)

**Comment by agduncan94** [comment]
This is probably a good to bring up during our next refresh simplification discussion.

**Comment by denis-yuen** [comment]
Commit id is now implemented and stored in the DB. 
Needs to be followed up with for this specific refresh issue
