### ISSUE TITLE
Investigate open API yaml generation 

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1444]
## Bug Report

In a browser, if you go to [Dockstore Swagger](https://dockstore.org:8443/static/swagger-ui/index.html#/), there is a link labeled [Error](https://online.swagger.io/validator/debug?url=https://dockstore.org:8443/swagger.json) at the very bottom of the page.

Clicking the link takes you to a JSON file that shows various schema validation messages.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-350)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-350
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10212/Screen+Shot+2020-03-26+at+8.12.46+AM.png">Screen Shot 2020-03-26 at 8.12.46 AM.png</a>

**Comment by denis-yuen** [comment]
Sounds like its related to a deprecated annotation  http://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiOperation.html#position()

**Comment by denis-yuen** [comment]
This might be done already

**Comment by denis-yuen** [comment]
From linked issue, seems like it has gotten worse 
```
Swagger-UI does say in the bottom right corner that the swagger is invalid
Seems it doesn't handle the redirect to /api
```

**Comment by garyluu** [comment]
Essentially...the swagger yaml requires too many breaking changes to fix (so abandoning that).  The OpenAPI, however, should be valid
