### ISSUE TITLE
Implement something  for WDL 1.0 metadata

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1445]
### Desired behaviour

Take a look at using womtool for parsing wdl metadata

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-351)
┆Issue Type: Story
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-351

**Comment by cricketsloan** [comment]
maybe of womtool/wdl4s

**Comment by agduncan94** [comment]
Is this simply seeing if we can extra authorship/description/email from .wdl files using womtool/wdl4s/whatever?

**Comment by denis-yuen** [comment]
Hmmm, seeing parse errors with some previously working verified tools.
https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0?tab=files and  https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:2.1.0?tab=files (have to click on WDL tabs while in "My Workflows"
stack traces look like the following, but don't seem to abort the whole refresh
```
14:33:56
INFO [2019-08-20 14:33:56,887] io.dockstore.webservice.helpers.AbstractImageRegistry: quay.io/pancancer/pcawg-bwa-mem-workflow ICGC-TCGA-PanCancer : Parsing WDL...
INFO [2019-08-20 14:33:56,887] io.dockstore.webservice.helpers.AbstractImageRegistry: quay.io/pancancer/pcawg-bwa-mem-workflow ICGC-TCGA-PanCancer : Parsing WDL...

14:33:56
ERROR [2019-08-20 14:33:56,894] io.dockstore.webservice.languages.WDLHandler: Unable to parse WDL file /Dockstore.wdl

14:33:56
! wdl.draft3.parser.WdlParser$SyntaxError: ERROR: Sibling nodes have conflicting names:

14:33:56
!

14:33:56
! WdlTask defined here (line 1, col 6):

14:33:56
!

14:33:56
! task Seqware_BWA_Workflow {

14:33:56
! ^

14:33:56
!

14:33:56
! WdlWorkflow statement defined here (line 43, col 10):

14:33:56
!

14:33:56
! workflow Seqware_BWA_Workflow {

14:33:56
! ^

14:33:56
!

14:33:56
! at io.dockstore.common.WdlBridge.getBundleFromContent(WdlBridge.scala:322)

14:33:56
! at io.dockstore.common.WdlBridge.getMetadata(WdlBridge.scala:100)
```

**Comment by denis-yuen** [comment]
I think I'm satisfied that basic WDL 1.0 parsing is functional based on some test with current WDL repos such as 
https://github.com/dockstore-personal-testing-phoenix/topmed-workflows   /variant-caller/variant-caller-wdl/topmed_freeze3_calling.wdl 
and 
https://github.com/denis-yuen/dockstore-whalesay-wdl-only

Splitting out issue to more specific ticket
