### ISSUE TITLE
Remove #workflow

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1451]
### Desired behaviour
Now that workflow paths and tool paths are pretty much distinct at this point (maybe not for hosted workflows and tools), explore the idea of removing `#workflow` from the ids in the GA4GH endpoint.  
Although it shouldn't matter when purely using TRS endpoints, it's easier when someone looks at Dockstore.org to instantly figure out what the TRS tool id should be.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-353)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-353

**Comment by garyluu** [comment]
Additionally, if `#workflow` can't be removed, display it prominently in the ui2 somewhere

**Comment by melainalegaspi** [comment]
Done already
