### ISSUE TITLE
Suggestions/Ideas for Accounts Page

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1460]
This is for code currently on develop branch, and related mainly to the Google account integration that is not yet in production.

1. The help text for both GitHub and Google logins says both are required. Only one of them is required, and even then that's only if you want to login. It is slightly confusing.
2. It is probably of limited value to optionally display the Google access token -- they expire after an hour or so. Not unless you want to display a refreshed access token that is up to date.
3. ~On the other hand, I found it would be useful to display my Google email address (and something similar for the other integrations, if available). Users often have both personal and work mail accounts that they might use separately into different repositories, and it would be nice to see at a glance which account(s) you have linked.~

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-355)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-355

**Comment by agduncan94** [comment]
1. Looks like this has been dealt with.
2. Should we just remove this?
3. The email address is shown as the username of the google account. Perhaps we can make this stand out more. It is also visible on the profiles tab.

**Comment by david4096** [comment]
@coverbeck can we close?

**Comment by coverbeck** [comment]
Hmmm...

We haven't changed 2.

I think number 3 is now good, although we might have to revisit as part of #2490

**Comment by cricketsloan** [comment]
@NatalieEO Check this ticket out when you are in the code adding ORCid
