### ISSUE TITLE
We should be case insensitive in the webservice for enums and such

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1466]
Values like DOCKSTORE_WDL should be case insensitive.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-357)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-357

**Comment by denis-yuen** [comment]
might be done already

**Comment by denis-yuen** [comment]
Done with https://github.com/dockstore/dockstore/commit/3aba2384e00e504ba4b486762d19861933554f71#diff-14c028d4be3b9eed37f6aae0f854624fR215

Can now be all like

/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FCCDG_aligner_functional_equivalent_wdl/versions/1.1.0/WdL/descriptor

/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FCCDG_aligner_functional_equivalent_wdl/versions/1.1.0/WDL/descriptor

/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FCCDG_aligner_functional_equivalent_wdl/versions/1.1.0/wdl/descriptor
