### ISSUE TITLE
DOS File Provisioning Plugin Should Handle Uploads

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1481]
## Feature Request 

The first iteration of the DOS File Provisioning plugin is download only; it should handle uploads as well.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-13)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-13
┆Epic: Improve DRS File Provisioner

**Comment by melainalegaspi** [comment]
reopen if specification allows
