### ISSUE TITLE
Redesign select default version and select current viewable version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1531]
### Desired behaviour
Redesign the way to select default version and  viewed version.  The table contents will be reserved for hyperlinks to external locations (git reference goes to github/tree, file link directs to source file...etc) so there needs a new way of selecting default version and  viewed version.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-362)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-362
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
1. set as default button next to version drop down
2. rule of thumb: one action per box
3. click on text, not the background
