### ISSUE TITLE
Refresh cannot be performed by workflow non-owner after changing Git repo

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#1584]
## Feature Request 
Provide way for Workflow or Tool to update in Dockstore when public Git repo is changed by a person other than the Dockstore Workflow or Tool owner 

### Desired behaviour
Perhaps Dockstore could be notified of changes to the Git repository and refresh automatically?

### Steps to reproduce the behaviour 
Developer A creates a workflow in Dockstore that points to the workflow code in a public Git repository
Developer B makes a change to workflow code in the public Git repository that should be reflected in the workflow in Dockstore
Developer B cannot click on 'Refresh Workflow' because he does not own the workflow in Dockstore
Developer A must be notified to go to Dockstore and 'refresh' the workflow so that the changes to the workflow code in the public Git repository can be seen in Dockstore

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-369)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-369
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
I was discussing this with Walt, and we're going to research this some more tomorrow with Developer B, who may remember some more details of exactly what happened.

**Comment by coverbeck** [comment]
We looked at with Michael (Developer B), and what happened is that he had joined the org before the workflow repo had been created, so the workflow in question wasn't showing up in his My Workflows.

It wasn't obvious to them that they needed to click the refresh button for the org; we just did that and the workflow now shows up.

**Comment by denis-yuen** [comment]
Might be a documentation or interface improvement then
