### ISSUE TITLE
Extend Workflow Sharing to non-hosted Workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1593]
## Feature Request 

The upcoming first iteration of workflow sharing is being restricted to hosted workflows. At some point after we are comfortable with the feature working correctly, we should extend the feature to all workflows.

On the webservice side, see TODO in io.dockstore.webservice.resources.WorkflowResource#addWorkflowPermission.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-371)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-371
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Can't find specific ticket, but in conversation, it seems that SAM is ready to tackle sharing for users that have a Google Account but are not specifically users of FireCloud (although process of registering makes them known to FireCloud)
