### ISSUE TITLE
Identify ways to improve lighthouse audit score

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1600]
### Desired behaviour

Some simple steps identified via https://developers.google.com/web/tools/lighthouse/
Let's try to reach a score of at least 50 performance by using some of their suggestions like re-compressing/shrinking/lazy loading certain images, etc,

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-372)
┆Issue Type: Story
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-372

**Comment by denis-yuen** [comment]
For tentative goals, I'd propose over simulated 3G and mobile
1) Performance: 50
2) Progressive Web App: 50
3) Accessibility: 50
4) Best Practices: 100
5) SEO: 100

**Comment by garyluu** [comment]
My manifest.json for easy PWA score doesn't appear to be working, should fix it.

**Comment by cricketsloan** [comment]
➤ Natalie Perez commented:

Done can be defining the subtasks

**Comment by denis-yuen** [comment]
Replaced by #2482
