### ISSUE TITLE
Add tag missing notifications

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1604]
### Desired behaviour
Add tag appears to be missing loading display (progress bar or alert).  Add tag success missing success notification, add tag error is missing error notification.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-373)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-373

**Comment by denis-yuen** [comment]
Looks a bit funny (the text clears and the validation fails quickly before the request actually succeeds. But these is a indeterminate progress bar now and a "Adding tag succeeded message" )
