### ISSUE TITLE
Too much twitter, covfefe

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1630]
## Bug Report

Why are there Twitter callbacks when I'm nowhere near the homepage timeline (seen on "My Workflows"). 

![screenshot from 2018-07-20 16-46-00](https://user-images.githubusercontent.com/1730679/43024434-7092d358-8c3c-11e8-9dee-0bbd506e75fc.png)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-378)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-378

**Comment by garyluu** [comment]
eek, every time the homepage is visited, the twitter script is added 

![image](https://user-images.githubusercontent.com/24548904/43608377-f55ef1f2-966e-11e8-80a3-5f4401233f2b.png)

**Comment by denis-yuen** [comment]
I'm going to bump up the priority of this

**Comment by garyluu** [comment]
2nd issue supposedly fixed, 1st issue remains (at a much lower frequency of requests)

**Comment by denis-yuen** [comment]
@garyluu  This seems to be acting odd. 
Browsing from the homepage to Tools and back leads to a blank twitter listing until a manual refresh

**Comment by garyluu** [comment]
uhoh

**Comment by denis-yuen** [comment]
Still alive

**Comment by garyluu** [comment]
Uhoh, might still not be fixed

**Comment by denis-yuen** [comment]
Looks better on 
API - 1.8.0-beta.6 
UI - 2.5.0-beta.1
