### ISSUE TITLE
Redesign export as zip button

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1642]
## Feature Request 

~1. If you're looking at a hosted workflow, the info tab has a row that says `Dockstore.org: The source code for this workflow is stored on Dockstore.org`. The label value seems odd to me in this context. The label changes based on the Source Control, e.g., it will say `GitHub` and then have a GitHub url if you have registered a GitHub workflow. Perhaps the label should be static, like `Source code` and not vary per source control system.~
2. The `Export as Zip` button is sort of buried/hidden; it doesn't stick out. Maybe add color to it, or don't have inline with the other label-value pairs?
~3. Presumably, this is being worked on, but the Export as Zip button doesn't download the zip file.~

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-379)
┆Epic: Usability
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-379
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
1) :+1: 
2) open to ideas
3) might be #1636

**Comment by coverbeck** [comment]
3. I see the Ajax call being made in Chrome Dev Tools, and I see that it returns content. It just doesn't go anywhere, i.e., I'm not prompted to save it.

**Comment by agduncan94** [comment]
Regarding the export as zip, we couldn’t think of a great place to put it so we kind of just dumped it into the info tab. We are open to ideas for other places we could put it.

**Comment by coverbeck** [comment]
I think the Info tab is the right place, it just looks sort of buried/hidden where it is now within the tab, particularly with the button style/colors as they are.

I'm not 100% in love with it, but maybe you could do something like we do in Boardwalk, with the bottom button:

![screen shot 2018-07-30 at 2 59 42 pm](https://user-images.githubusercontent.com/1049340/43426037-4f65ba04-9409-11e8-91de-da10122dad60.png)

**Comment by denis-yuen** [comment]
Check on 3 which might be a bug, the label is a documentation issue. 
2 should be punted to 1.8.0

**Comment by agduncan94** [comment]
Spit balling ideas.

Currently we have a few buttons on the top right of a tool/workflow. Publish, view public, refresh. We should condense these into two dropdowns. One for version related actions, one for tool/wf related.

Tool Actions
* Publish/unpublish
* Refresh
* View public

Version actions
* Make snapshot
* Make DOI
* Download as zip

**Comment by garyluu** [comment]
Though it's a large change, I prefer the entry information and version info to have different elevations/layers.  So the entry information will be on the bottom layer and the version information to be on a layer above that with higher elevation.  These buttons should then be placed on the appropriate layer.

**Comment by agduncan94** [comment]
@garyluu Could you make a mockup?

**Comment by coverbeck** [comment]
I think we also have a ticket or epic, or at least a storytime to revisit the versions table in general. Plus there is the idea of publishing versions. It potentially all ties together, for better or worse.

**Comment by denis-yuen** [comment]
Assessed, think it still makes sense, but updated description
