### ISSUE TITLE
Standardize on Descriptor Type

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1649]
### Desired behaviour
Standardize on descriptor type in Dockstore, currently there's too many different representations for the same thing.  See https://docs.google.com/spreadsheets/d/1DcDkjwzpd4Rd5Bl8S1duH4q2-hRBa-kKhlO1IYHWWu0/edit#gid=0

Decision was to change the DescriptorLanguageBean to return the shorter friendly name and possibly the extensions too.  For almost all code, use the ones in TRS (CWL, WDL, NFL).  For display, mostly use the short friendly name (CWL, WDL, Nextflow).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-380)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-380

**Comment by agduncan94** [comment]
I've done some work on this, so no nextflow is nfl. However now there is the difference between nfl and NFL for example. We should choose a case and stick to it.

**Comment by garyluu** [comment]
There's still a bunch of places that need to be changed.

**Comment by denis-yuen** [comment]
Ok, I'll punt this out to 1.6.0

**Comment by garyluu** [comment]
Having second thoughts above what the descriptor types should be:

https://github.com/ga4gh/tool-registry-service-schemas/pull/78

**Comment by denis-yuen** [comment]
@garyluu is this relevant anymore, not entirely clear to me

**Comment by garyluu** [comment]
probably not, but there is still a bug with the stub workflows missing a descriptor type in the UI and possibly other defects that are not immediately obvious

**Comment by denis-yuen** [comment]
@garyluu ok, could you create narrower tickets for those? thanks
