### ISSUE TITLE
Show link for "view checker workflow" button

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1668]
### Desired behaviour
View Parent Entry and View Checker Workflow buttons should work with middle click and show link at bottom.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-384)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-384

**Comment by melainalegaspi** [comment]
Done already
