### ISSUE TITLE
Lazy-load images

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1728]
### Desired behaviour
UI2 should lazy load images: https://theinfogrid.com/tech/developers/angular/lazy-loading-images-angular-6/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-391)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-391

**Comment by cricketsloan** [comment]
➤ Natalie Perez commented:

See whether we’re doing it or not
