### ISSUE TITLE
Evaluate heterodon to substitute for schema-salad for using cwlavro on the web service

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1734]
### Desired behaviour

While the Dockstore client uses cwlavro, the web service also works with CWL and is much less sophisticated treating CWL as simple yaml. Try out heterodon as a substitute for the schema-salad/cwltool portion of cwlavro so that we can work with CWL on the web service like we do with cwlavro on the client without dropping out of the JVM. 

See https://github.com/broadinstitute/heterodon
https://github.com/broadinstitute/cromwell/pull/4018

(Potential?) Thanks to @geoffjentry

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-168)
┆fixVersions: Open-ended research tasks
┆friendlyId: DOCK-168
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
https://github.com/broadinstitute/cromwell/blob/develop/cwl/src/main/scala/cwl/CwltoolRunner.scala#L45

**Comment by denis-yuen** [comment]
Functional but seems to have weird ... hiccups. 
Considering alternative architecture for integration

**Comment by geoffjentry** [comment]
@denis-yuen for our own purposes can you give more details? (cc @kshakir)

**Comment by denis-yuen** [comment]
@geoffjentry @kshakir

Ah, I was being imprecise. We might have to look at an alternative way of integrating heterodon as opposed to an alternative to heterodon. 

But specifically for the hiccups, I'll definitely be gathering more data, but likely after Basel. As a first impression, it was very simple to integrate but I noticed odd pauses with our tests running on Travis where the tests using heterodon would seem to run quickly at some times, timing out at other times. 

The problem could entirely be on our end or something to do with Travis-CI on the day I was running tests, so take the anecdote with a grain of salt.
