### ISSUE TITLE
RSS articles are toooooooo loooooooooooooooooooooooooong

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [dockstore/dockstore#1741]
## Feature Request 

Truncate RSS articles that are too long.

### Desired behaviour

Some articles are very long, and are hard to read in an RSS reader. They should be truncated, with a link to the main content.

Example: see the RSS item titled "images.sbgenomics.com/nikola_tesic/quagmir" dated 2018-08-08 08:42 AM

Also, it might be a good idea to strip out markdown/HTML from RSS articles.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-396)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-396

**Comment by denis-yuen** [comment]
In addition, I think the current code has the following flaws
1) Doesn't take into account age, I suspect that the RSS standard has some best practice for how long to leave old entries up. Do that
2) Doesn't include versions, the current code republishes a new entry when a new version is created but doesn't communicate what that new version is

**Comment by melainalegaspi** [comment]
description has been truncated to 200 characters
