### ISSUE TITLE
Dockstore in FAIRShake?

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#1755]
Should we get Dockstore registered in FAIRshake?

Denis Yuen, Avi Maayan, Hsinyi Tsang
https://fairshake.cloud/project/ 
Use FAIRshake to perform automated assessments on the registered Dockstore tools and workflows, especially given the presence of the `GA4GH Tool Registry API` for tool

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/SEAB-158)
┆Issue Type: Epic
┆Issue Number: SEAB-158

**Comment by denis-yuen** [comment]
https://fairshakejam.cloud/ perhaps this

**Comment by cricketsloan** [comment]
[~accountid:5c47ac5281ec9e450cead350] having worked with these people, anythoughts?

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

I think FAIRshake is a good set of metrics to consider as we plan for future changes to Dockstore (especially state stuff). We should definitely take the metrics into account during our discussions for things like DOI, archiving entries, etc.

The relevant set of metrics are https://fairshake.cloud/rubric/25/
