### ISSUE TITLE
Refresh all vs refresh by org for tools

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1780]
Failing for refresh all, but not refresh by org.
Workaround is refresh by org after adding a tool in that org (make sure to use toolname).

Issue could be related to adding a new org when you have existing orgs, as once the above workaround is done, refresh all will work.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-401)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-401

**Comment by denis-yuen** [comment]
@agduncan94  probably will need to grab more information, it doesn't seem to be a systematic issue with refresh to add an organization

**Comment by melainalegaspi** [comment]
will revisit in light of GitHub apps
