### ISSUE TITLE
Only open important facets by default on search page

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1814]
Currently we have a lot of facets, and each is open by default. We should only open the ones that are important by default.

One problem with having all facets opened is that the clear facets button is very low not visible on normal screen sizes unless you scroll far down.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-409)
┆Epic: Fix Facets 
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-409
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Parallel is https://dcc.icgc.org/search with primary site, project, study, and gender open but the rest are closed. We can pick some initial facets but also change them based on user popularity after #1203 #1811

**Comment by denis-yuen** [comment]
See also #2062
