### ISSUE TITLE
RSS feed and discourse version interaction

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1816]
### Expected behaviour

RSS clients see new articles when there is a new version of a workflow. Discuss doesn't create a new thread when there are new versions of workflows. 

### Actual behaviour

RSS clients see new articles when there is a new version of a workflow. Discuss creates a new thread for each new version of a workflow. (or at least they are named that way, needs a closer look)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-410)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6.x
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-410

**Comment by denis-yuen** [comment]
Additional issue. 
RSS feed is creating new articles when a workflow is refreshed as opposed to when they actually get new versions

**Comment by denis-yuen** [comment]
fyi @agduncan94

**Comment by agduncan94** [comment]
Based on discussion:
The only way to embed a discourse topic and not auto create it is to link by topicID. Unfortunately the Discourse API does not let you search by topic ID.

Possible Solution:
Disable both RSS topic creation and embed creation. Topics created automatically by a cron job and will store the topic ID in the database.

When a tool/workflow page is loaded, the object will have the topicID if it exists and will display the comments without creating. If not topicID exists, will just display a message along the lines of "topic is in queue to be generated"

**Comment by agduncan94** [comment]
More notes:
Another idea was somehow blocking Dockstore.org from creating topics, and only let the RSS feed create the topics.

The reason we do not use the auto topic generation on its own and require the RSS is because discourse is not able to properly load the site (JS?) so the title of each page is always set to Dockstore. This was confirmed by the new changes which set the title to be things like 'Dockstore | Organizations', as the topics auto generated still used the base 'Dockstore' title.

**Comment by agduncan94** [comment]
@denis-yuen I think this can be removed from 1.6.0. I will be looking at it very soon but I think it makes sense to exist outside the releases, or at least 1.6.0.

**Comment by agduncan94** [comment]
Asked on the discourse discourse and this is the response
https://meta.discourse.org/t/embed-discourse-topic-but-do-not-automatically-create/111705

In summary, there doesn't seem to be a built in way to do this. I think likely the only solution is https://github.com/ga4gh/dockstore/issues/1816#issuecomment-473979200

**Comment by denis-yuen** [comment]
I like that idea actually.

**Comment by agduncan94** [comment]
Just summarizing what I'm doing:
* Update entry.java to have topicId field
* UI should display using topic ID, and not autogenerate a topic for new tools/workflows on page visit
* Create a swagger client for Discourse (subset of calls)
* Create a dockstore-discourse module
* Create a class that can be called by AWS lambda that will create a discourse topic for the first returned tool/workflow that does not have a topicId associated with it

And once done, stop RSS from creating topics.

One question, what is calling the AWS lambda function to be run? Just a simple script run periodically on the dockstore server?

**Comment by denis-yuen** [comment]
Sounds roughly right. 
Initially, we could try a AWS lambda cron (i.e. run every 5 minutes), later we can be more sophisticated and just trigger the lambda when new entities are created on Dockstore (i.e. copy some of the webhook code we'll have later)

**Comment by agduncan94** [comment]
Ok thanks. So the jar (dockstore-discourse) would simply do the following:
* Call dockstore API to get first entry without a topicId
* If entry found, call to discourse API to create a topic
* Update the entry (psql) with the topicId returned by the create topic call

**Comment by denis-yuen** [comment]
> * Update the entry (psql) with the topicId returned by the create topic call

This should probably be done through the pre-existing PUT to update an existing tool/workflow since the lambda won't have access to postgres directly

**Comment by agduncan94** [comment]
Oops I just put that there meaning it was writing to the database, but yeah will use the dockstore webservice for that.

**Comment by agduncan94** [comment]
What ended up being done is the following:
* entries now have a topic ID column
* on publish, if no topic ID is set, try to create a topic on discourse and link it to the entry (failure to do so will not cause the publishing to fail)
* endpoint for curators that allow them to manually create and link a discourse topic to an entry

What is left to do:
* UI should not auto generate a topic, but instead display a topic if the entry has an associated ID
* migrations

Follow-up ticket for migrations
https://github.com/ga4gh/dockstore/issues/2422

**Comment by denis-yuen** [comment]
@melainalegaspi  unito going a bit nuts?
