### ISSUE TITLE
getMyself and getMyOrgs in sourcecoderepo is possibly redundant

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1821]
There seems to be some overlap in the repos returned, could possibly make this more efficient.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-411)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-411

**Comment by melainalegaspi** [comment]
close in favor of optimizing through GitHub apps
