### ISSUE TITLE
Instead of only refresh, option to fetch new workflows/tools or update existing

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1828]
Sometimes we may not want to update all workflows, we just want to fetch new ones. This should be an option.

Perhaps something like this.
https://v4-alpha.getbootstrap.com/components/dropdowns/#split-button-dropdowns

Clicking the left button will do the typical refresh, but clicking the arrow will give two options. Fetch new workflows or refresh existing workflows.
![screenshot from 2018-09-14 09-58-53](https://user-images.githubusercontent.com/6331159/45554591-cfc56400-b804-11e8-988d-2e82d0936cdc.png)

Note that this probably requires some cleanup of the refresh code in the webservice. Will need to separate so that a normal refresh happens in two steps.

1) Fetch new workflows
2) Refresh workflows existing workflows

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-414)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-414

**Comment by denis-yuen** [comment]
Revisit after #2400
