### ISSUE TITLE
Make a standard toolkit for adding launch with options

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#1852]
We have special methods for each of the DNAstack/DNANexus/Firecloud.  We would like to see a toolkit for adding buttons that we could provide for external collaborators.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-94)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-94
┆Epic: Launch-with Support

**Comment by denis-yuen** [comment]
Toolkit should include recommendations for API endpoints to hit as well depending on when this is done

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

This is mainly done, although need to tidy up to handle non-WDL partners.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Also, mention /metadata/config.json endpoint (DOCK-839)

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Was merged and is present (not really user facing)
