### ISSUE TITLE
Sidebar selection before ready

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1855]
### Desired behaviour
Currently the sidebar expansion panels are shown and can be interacted with immediately.  Afterwards, there is panel expansion logic that is executed afterwards.  Between these two, a user can potentially expand a different panel and then have their action overridden by the panel expansion logic.  Ideally, this should not happen

Possible solutions:
- Make the sidebar not interact-able until the panel expansion logic has been executed.
- Do the panel expansion logic first before showing the sidebar.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-423)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-423

**Comment by denis-yuen** [comment]
Check if still a thing, otherwise punt

**Comment by garyluu** [comment]
Not sure why, but it's less of an issue now.  Still possible I think but doesn't seem humanly possible to do so

**Comment by denis-yuen** [comment]
Ok, closed
