### ISSUE TITLE
Wrap nextflow in Dockstore CLI

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1856]
Currently the Dockstore CLI does not support Nextflow. Users must run nextflow CLI directly, either by passing the associated git reference as an argument or by using local files that they downloaded.

This is fine for now, as the nextflow CLI supports many options for file provisioning. However, for consistencies sake, along with some other benefits, we should allow users to run nextflow workflows the same way they run CWL and WDL workflows.

Some benefits off the top of my head:
- users who do not care about NFL vs CWL vs WDL and just want to run something would like to do so in a consistent way
- for hosted entries, users won't have to download the descriptor files themselves, and can instead rely on the Dockstore CLI to do that (1 step vs at least 2)
- users can reference a entry on dockstore using a path, and not have to reference either the git repo or download the files directly (referencing git url for tools might confuse people)
- users will be able to run both hosted workflows and remote workflows in the same way, unlike what happens now

Also, we should have the option to pass extra user specified parameters. I know we do this for cwltool by having users specify in their config, but maybe it makes more sense to pass as an argument when doing `dockstore launch ...`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-424)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-424

**Comment by agduncan94** [comment]
It looks like there is already a Nextflow client, need to investigate exactly how much is implemented.

**Comment by melainalegaspi** [comment]
reopen if requested
