### ISSUE TITLE
Entry Verification

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1863]
### Desired behaviour
Would be nice if the Entry object has a verified property that's populated in the webservice.  This would let the UI be able to quickly determine if the object is verified once received.  Another advantage is that it saves an elasticsearch query or two because the current implementation does some hacky workaround in order to filter verified and not verified.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-427)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-427

**Comment by garyluu** [comment]
If giving the entry object an on-the-fly computed verified property is too intensive, then one solution is to only compute the verified property only during elasticsearch indexing.

**Comment by denis-yuen** [comment]
Duplicates #2384

**Comment by denis-yuen** [comment]
Actually https://github.com/dockstore/dockstore-ui2/pull/760
