### ISSUE TITLE
DAG sometimes does not figure out the type properly

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1870]
See https://dockstore.org/workflows/github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/pcawg-oxog-full-workflow:master?tab=dag

Some nodes have type dockstore_, meaning their type was not figured out.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-132)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-132

**Comment by agduncan94** [comment]
Looking at the example, it seems that the node that doesn't work is due to a Git submodule. However, I still think we should change the default to be something else, so for now I'll make it 'n/a'.

**Comment by NatalieEO** [comment]
The type for node does now show as n/a on staging API - 1.7.0-beta.1  UI - 2.4.0-beta.1
