### ISSUE TITLE
Node Version Should Be Enforced in package.json

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1911]
The package.json has a [engines](https://docs.npmjs.com/files/package.json#engines) section -- the UI should specify the node version in there.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-433)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-433

**Comment by garyluu** [comment]
node version is already specified in .nvmrc  which is actually used for something.  https://github.com/nvm-sh/nvm/issues/651 .  Specifiying it in package.json has no benefit.

**Comment by coverbeck** [comment]
> Filing a motion to dismiss.

I guess so; I certainly don't like the duplication.  And if engine doesn't actually enforce anything, then it's worthless. Still, I used to use node without nvm and maybe because I'm old-school I'm used to looking in the package.json to know what version of node to use.

But ultimately no objection.

**Comment by denis-yuen** [comment]
Considering this closed
