### ISSUE TITLE
Improve UX for Hidden Versions

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1940]
## Feature Request 

It is not easy at a glance to determine what versions of workflow are hidden or not. You need to click the Edit button for each version and see if the Hidden checkbox is selected.

On top of that, it wasn't immediately obvious to me that is where you should hide/unhide a version.

Finally, if I hadn't been looking for the feature, it's not clear to me what `hidden` means in this context -- it's not immediately obvious that it means hide in the Published view.

It would be nice if Dockstore at least showed what versions are hidden or not directly in the table.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-441)
┆epic: Deletion-Archiving Policies
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-441
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Sounds good, can link to a FAQ entry like with verified or private entries. 
A column or other way of indicating to tool/workflow others that a version is hidden (maybe graying it out?) would be worth trying out too.

**Comment by agduncan94** [comment]
I can't seem to hide workflow versions. It does work for tool versions though.

**Comment by coverbeck** [comment]
Hmm, I thought I tried this and it worked for me. When you say it doesn't work, do you mean you can't get to/click the hidden checkbox, or that you are able to, but it still shows up?

**Comment by agduncan94** [comment]
Sorry I should've explained more. So for workflow versions when I click on edit the checkbox is greyed out and I can't click on it.

**Comment by agduncan94** [comment]
Looking at the code it looks like the variable canWrite is not set.

**Comment by denis-yuen** [comment]
Maybe you're trying different versions?

**Comment by coverbeck** [comment]
There is now a hidden column in the versions table, rejecting pending any more requests in this area.
