### ISSUE TITLE
Information in info tab should come from the selected version

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1943]
## Feature Request 

The description and other information in the info tab comes from the default version.

I think it should come from the selected version. You might be working on a branch in GitHub, where for example, you update the description and see what it looks like in Dockstore.

Alternatively, if the feeling is that it should display information from the default version, then it should be more clearly denoted.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-295)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-295

**Comment by denis-yuen** [comment]
Worth a discussion I think

**Comment by agduncan94** [comment]
Some thoughts on reorganising the info tab.
Idea is to split up the info tab into entry level fields and version.
The entry section includes the following:
* remote resource links
* TRS links
* Default file paths
* Checker workflow
* Build mode
* Last updated/modified

The version section includes the following:
* Author
* Email
* Description

The version section is based on the selected version, and not the default.

**Comment by denis-yuen** [comment]
Do we show any default information in this version or does it only control the version you see if you link to a workflow or browse to a workflow via search?

**Comment by agduncan94** [comment]
It will only control the version you see if you link to a workflow/find in search. It may be that we just remove the concept of default all together and find an automatic way to select a default version.
