### ISSUE TITLE
QuickStart Wizard change

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1950]
### Desired behaviour
Part 1 Step 3 appears to be an alternative to Step 2 but nothing to do with Step 1.  Perhaps Step 3 should be combined with Step 2.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-292)
┆Issue Type: Story
┆Issue Number: DOCK-292

**Comment by denis-yuen** [comment]
meh
