### ISSUE TITLE
Verifiedsource null for some verified workflow version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1951]
### Expected behaviour
Verifying a sourcefile with `/api/ga4gh/v2/extended/{id}/versions/{version_id}/{type}/tests/{relative_path}`
Annotate test JSON with information on whether it ran successfully on particular platforms plus metadata  should result in a workflow version or tag to be verified with a non-null verifiedsource

### Actual behaviour
Verifiedsource is null, 1.5.1 /tools endpoint runs into error

### Steps to reproduce the behaviour 
Verify the tool or version using:
```
response = client.extendedGA4GH.toolsIdVersionsVersionIdTypeTestsPost(type="WDL",
                                                                      id="#workflow/github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline",
                                                                      version_id="1.29.0",
                                                                      relative_path="u_of_michigan_aligner.json",
                                                                      platform="Cromwell",
                                                                      metadata="TOPMed, HCA via Broad", verified=False).response().result
```
Try to hit the /tools endpoint

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-291)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-291

**Comment by garyluu** [comment]
`select * from workflowversion where verified='true' and verifiedsource is null;` reveals many more problematic versions but it doesn't seem to trigger unless there's multiple of them in the same entry.  All these versions happen to be verified using the new endpoint so likely the problem lies there.

Regardless, verifiedsource should not be null for verified files (and their versions).  After fixing the null verified source, additional options may include:

- adding a constraint for non-null verified source when verified is true
- removing verified altogether, a non-null verified source implies verified

**Comment by denis-yuen** [comment]
@garyluu please link and then swap this to 1.7.x

**Comment by garyluu** [comment]
So I think this issue was from a really long time ago.  verified and verified source no longer exists in the workflow table.  The merged ticket above should remedy whatever inconsistencies that arise.

Example (we need to run this in production):
```
curl -X POST "http://10.11.8.92:8080/workflows/2327/verify/8893" -H "accept: application/json" -H "Authorization: Bearer thing"
```

**Comment by garyluu** [comment]
The endpoint was somewhat recently modified with my PR. It's better to wait and avoid more potential sync issues with the current endpoint

**Comment by Ldcabansay** [comment]
Outdated issue, see #2376, more relevant and updated fixes.
