### ISSUE TITLE
python 3 cwltool installation instructions

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1952]
### Expected behaviour
pip installation instructions with python 3 should probably say pip3 to be explicit.  
should mention that cwltool may not work unless you log out and log back in (similar to docker)

### Actual behaviour
Doesn't say the above

### Environment (Browser or OS and Dockstore version)

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-290)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-290

**Comment by denis-yuen** [comment]
Should switch to Python 3 for cwltool for 1.7.0 
Update tutorials and Travis-CI in-time for https://changelog.travis-ci.com/upcoming-python-default-version-update-96873

**Comment by garyluu** [comment]
Funny: https://pythonclock.org/

**Comment by denis-yuen** [comment]
Also tooltester

**Comment by garyluu** [comment]
1. Check that everything runs fine on tooltester
2. If it works, remove Python 3 requirements.txt
3. Change tests to not test deps 2 command

**Comment by garyluu** [comment]
Step 1 has failed before even using Python 3.

Blocked by:
#2727
#2725

**Comment by denis-yuen** [comment]
@garyluu re-assess, think fixes are available for both
