### ISSUE TITLE
Workflow launch help message does not match code in explanation of parameters json, yaml

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#1971]
### Expected behaviour
wdl and nextflow currently only launch with json, while cwl can launch with either json, or yaml. The help message for `dockstore workflow help` should reflect this. 

### Actual behaviour
Help message states that '--json', '--yaml', '--tsv' are optional parameters when at least one is required to run workflow.
Also [Source code](https://github.com/ga4gh/dockstore/blob/3fd37afed57121ab66cebacc93a42e4e79c77cd9/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java#L437) shows that to launch a workflow only cwl has yaml support, but help message for `dockstore workflow launch` implies otherwise. Tsv parameter is correctly identified as cwl only.

### Environment (Browser or OS and Dockstore version)
MacOS, Dockstore 1.5.1

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-282)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-282

**Comment by garyluu** [comment]
CLI exception aside, we should check whether WDL workflows can be launch with YAML

**Comment by coverbeck** [comment]
If you use `--local-entry`, it does pass on [the yaml](https://github.com/ga4gh/dockstore/blob/3fd37afed57121ab66cebacc93a42e4e79c77cd9/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java#L490)
