### ISSUE TITLE
Create some components for smaller repetitive html

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1983]
This will require some investigation into what units are repeated. Some good examples is the display of alerts and also the display of validation messages.

This would be a good task for a new person, as it will get them familiar with Angular and the codebase.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-279)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-279

**Comment by agduncan94** [comment]
@garyluu I think for alerts the goal would be that you could use something like <ds-alert message='...' canClose='false' type='warning'></ds-alert> instead of writing the HTML for the alerts each time. Less room for error, more consistent display, etc.

**Comment by denis-yuen** [comment]
Re-open for specific proposed components
