### ISSUE TITLE
AlertService my-workflows displays error as success

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1985]
## Bug Report
Fetching workflows in my-workflows is incorrect.

### Expected behaviour
Should properly handle:
- when 1 of the 2 GET endpoints (sharedWorkflows, regular workflows) fail
- when both endpoints fail
- when none fail

### Actual behaviour
Currently when either endpoints (sharedWorkflows, regular workflows) fail, it will display the error and still say success

### Steps to reproduce the behaviour 
Block URL on GET shared workflows

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-278)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-278

**Comment by denis-yuen** [comment]
Seems functional on staging, use Chrome to block, not firefox (seems to hang in some kind of debug mode)
