### ISSUE TITLE
Sidebar covers expanded DAG

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#1993]
### Expected behaviour
Fullscreen DAG covers all except for DAG tooltips

### Actual behaviour
Sidebars covers it.  Material Tabs seem to have changed the stacking context of the DAG.  Even though fullscreen DAG has a maxed out z-index, it doesn't matter if the parent's stacking context is underneath the sidebar.  Sidebar has a z-index of 2, .mat-tab-body-wrapper appears to have a z-index of 1.  A quick fix option is to change .mat-tab-body-wrapper z-index to 2 but need to figure out the consequences of doing so.  Another option is the change the fullscreen DAG into a fullscreen dialog.

Note: Add integration test to make sure it's not covered by sidebar.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-275)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-275

**Comment by denis-yuen** [comment]
Seems functional on staging.dockstore.org with 2.4.0-beta.5
