### ISSUE TITLE
Galaxy Workflows

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#1994]
We are exploring the addition of Galaxy Workflows into the Dockstore eco-system.   

* What do we need to know about ?
  * Does Galaxy have a concept 
* What would an interface class look like?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-181)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-181
┆Epic: Galaxy-Dockstore Integration

**Comment by coverbeck** [comment]
Discussion with @jmchilton

Define an interface for interacting with workflow languages. Interface will live in main Dockstore repo.

Create a new repo in Dockstore for Galaxy support with a skeleton implementation for testing for James to contribute.

Notes from meeting:

```
Galaxy has the concept of default parameters
- how is input data treated
- checker workflows can be a pass 2 since it involves/supports testing across platforms sharing a language
- Dataflow
- walk through https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java
- data items
- author
- parameter files (working example of parameters user would use to launch workflows)
- examples of CLI commands used to launch workflow (applicable?)
- description
- DAG(?) - not currently
- list of Docker containers (biocontainers)/images a workflow uses
- their Dockerfiles if applicable
- may involve work
- validity
- list of descriptors and their imports
- URLs to go to primary storage of descriptors and docker image
- where would Dockstore talk to in order to get list of a user's workflows/Dockerfiles
```

**Comment by cricketsloan** [comment]
➤ Melaina Legaspi commented:

[~accountid:5ad7afeb1db05e2a66fa947b] remember to remind Seabright/Dockstore to create more specific followup tickets for this issue
