### ISSUE TITLE
Workflow and Tool Versions Should be Immutable

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#1995]
## Feature Request 

Workflow and tool versions should be immutable. While they currently are for hosted entries, they are not for entries that come from GitHub and other source control systems -- Dockstore versions are sourced from from GitHub tags, and GitHub tags can be moved, deleted, etc. When you refresh a workflow, if the GitHub tag was moved, the Dockstore version will reflect the new tag.

It would also be nice to be aware of Docker containers, e.g., a workflow refers to a Docker image and the Docker image changes (in that case we could issue a warning).

The motivation for this is so that papers/experiments can refer to a specific version of a Dockstore workflow/tool with confidence that the workflow/tool does not change.

A lot of details need to ironed out on how to implement this.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-274)
┆Issue Type: Epic
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-274

**Comment by agduncan94** [comment]
Perhaps we could label any tags/versions that no longer have remote counterparts as no longer on GitHub/Bitbucket/GitLab.

**Comment by denis-yuen** [comment]
The bigger problem this seeks to guard against (and we need to think about it) is actually hostile mutation rather than disappearing

**Comment by denis-yuen** [comment]
Think about a curator being able to delete
Users also have a grace period or can delete before a workflow is published, will only be able to archive otherwise
See #624

**Comment by david4096** [comment]
Recommended approach, implement version freezing as a separate feature and leave the existing synchronization features largely in place.

To close this, 

1. Extend the existing Tools and Workflow versions to include a new metadata field. This field will denote the `read-only` status of the version.
1. Add guards which disallow these `read-only` marked items from being overwritten during refresh (or delete).
1. Demonstrate that snapshotted remote tools and workflow versions can be registered and not overwritten using webservice tests.

This does not affect Hosted entries, which are already more or less immutable. This approach allows the existing endpoints to be mostly left intact (although some guarantees will have to be made that mutation is not possible at the `workflowVersions` endpoint).

**Comment by denis-yuen** [comment]
Compromise was to create the new #2700 snapshot functionality
Should follow-up with #2391
