### ISSUE TITLE
Integration tests for file provisioning plugins

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2028]
Add integration tests for the S3 and GS file provisioning plugins that literally exercise uploading and downloading files from Amazon S3 and Google Cloud Storage
These tests should also exercise error conditions, e.g. when an invalid bucket name is specified.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-177)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-177
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Might be useful, we used localstack once upon a time to simulate AWS SQS, I think it works for S3 as well. 
Not sure if there's a GS equivalent.

**Comment by denis-yuen** [comment]
@wshands punting, think this can be done off-cycle from Dockstore releases
