### ISSUE TITLE
Improve Dockstore CLI WES implementation after testing

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2031]
Based on testing and feedback from Dockstore engineers potentially refactor and enhance the Dockstore CLI WES implementation
Is authorization handled properly?
Is it general enough for the endpoints used in testing?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-195)
┆Epic: WES API support
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-195
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Note: some of this work is essentially feedback to the GA4GH WES repo
