### ISSUE TITLE
Figure out how to deal with nested lazy loading

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2043]
See getAllOrganizations, which loads a subset of organizations along with memberships. The issue is that memberships include org and user, which ends up in an infinite calls to load their sub collections. For example the org in the membership would then again load the memberships, and you end up in a loop. Hibernate initialize does a deep initialisation, we want a shallow one.

https://github.com/ga4gh/dockstore/blob/88c5704e063d1500b86061ca46a42d2cbb974368/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganisationResource.java#L212

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-206)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-206

**Comment by denis-yuen** [comment]
Not specific enough on what is needed here, re-open if we remember
