### ISSUE TITLE
Improve selecting facet values in search page for facets with many values

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2062]
If there is a large number of values for a facet, it is difficult to select a particular value. For example, there are currently more than 90 authors on the search page at Dockstore.org. If you're looking for a particular author, you need to expand the list of authors, which expands to a very long list where you have to manually select. This will not scale.

It would be nice if there was a search with autocomplete box so the user can select authors by typing the names.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-215)
┆epic: Fix Facets 
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-215
┆sprint: Sprint 46- Unicorn Fish
┆taskType: Story

**Comment by cricketsloan** [comment]
➤ Natalie Perez commented:

This and the whole search page should be brought up as a story time before working on it.

**Comment by denis-yuen** [comment]
> It would be nice if there was a search with autocomplete box so the user can select authors by typing the names. 
came up as a good idea in storytime

**Comment by denis-yuen** [comment]
After #1085 , this implementation should be generalised to facets with many values

**Comment by GFJHogue** [comment]
**Review**:
This looks incomplete to me.
Only `Author` has a search box with autocomplete.
What about the other facets with many values?
- `Tool: Namespace` (65)
- `Workflow: Organization` (93)
- `Labels` (134)

**Comment by coverbeck** [comment]
Proposing for 1.12 milestone. For workflows, there are more organizations and labels than there are authors
