### ISSUE TITLE
Take a look at DRIP for Cromwell and Nextflow

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2067]
### Desired behaviour

Take a look at  DRIP, investigate to see if this helps us https://github.com/ninjudd/drip

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-260)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-260

**Comment by melainalegaspi** [comment]
closed in favor of AWS lambda approach
