### ISSUE TITLE
UI should redirect if you have an invalid token

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2105]
## Feature Request 

If the UI has an invalid token, and you go to to My Workflows, My Tools, or My Account, the pages come up, but without the important content, e.g., no workflows, no tools, no profile info, etc.

Also the button at the top right is in a funny state; it has blank text.

The UI should instead redirect to you to the sign in page if you go to one of those pages, and button at the top right should say `Login/Register`.

This is fix would mainly be a local dev nicety, as when I reinitialize my local database, my previously issued token becomes invalid. But if we revoke a token, it would become an issue there as well.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-247)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-247
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
Can simulate when restoring a different database

**Comment by denis-yuen** [comment]
Could use same mechanism as https://github.com/dockstore/dockstore-ui2/pull/740

**Comment by coverbeck** [comment]
Relates to #3361, perhaps.

**Comment by david4096** [comment]
You can manually "invalidate" your token by logging in, changing your token's value in your browser's LocalStorage, and then refreshing.

**Comment by coverbeck** [comment]
Confirmed it logs me out with an invalid token on dev.

[Webservice](https://github.com/dockstore/dockstore/commits/5390433) - 5390433

[UI](https://github.com/dockstore/dockstore-ui2/commits/14afbd25) - 2.8.5-131-g14afbd25

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/b72dba0) - 1.11.2.1-125-gb72dba0

galaxyParsingLambdaVersion: 0.0.6
