### ISSUE TITLE
Bug fixes for DNAnexus integration

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2106]
Recorded issues:

1. On the main import screen need a "New project” option in addition to importing into an already existing project.
1. Need to support spaces in folder name.  APPARENTLY DONE 07/16/2018, MUST TEST
1. Change the green popup that announces a successful import even in the event of an error.
1. Automate population of the properties and labels of the imported workflows. Capture URL imported from, timestamp, version, whether the workflow was manually edited on DNAnexus’ side post-import. Reflect edits in the name by adding “modified” to the name.
1. Test WDLs with file path imports, get http imports support added.  APPARENTLY DONE 07/13/2018, MUST TEST (see below)
1. Add the staging instance of Dockstore to the whitelist at DNAnexus to enable button testing on the staging instance of Dockstore.
1. One other item, which is not part of the SOW, but a very strong nice-to-have, is to organize marketing communications and support for the newly added features.

Sincerely,

Vladimir Makarov

UPDATE:

From: Ola Zalcman <azalcman@dnanexus.com>
Sent: Monday, July 16, 2018 10:20 AM
To: Vladimir Makarov
Cc: Christopher Meyer; Geet Duggal; Brian O'Connor; Nihar Sheth; Teresa Barsanti
Subject: Re: DNAnexus Dockstore Milestone review

Morning Vladimir,

I forgot to add that folder names with spaces are also accepted in this new version.

Best,
Ola

From: Ola Zalcman <azalcman@dnanexus.com>
Sent: Friday, July 13, 2018 3:20 PM
To: Christopher Meyer
Cc: Geet Duggal; Brian O'Connor; Nihar Sheth; Vladimir Makarov; Teresa Barsanti
Subject: Re: DNAnexus Dockstore Milestone review

Hello,

Yes, as Geet mentioned, I released a new workflow importer version (0.0.10), which works with workflows that use URL import. An example of such workflow I found on dockstore is:
https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FTopMed_Variant_Caller_wdl_checker/versions/1.16.0

Best,
Ola

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-39)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-39
┆Epic: Test DNANexus

**Comment by cricketsloan** [comment]
Walt, can you see how this combines with your other tickets

**Comment by melainalegaspi** [comment]
reopen when we look at DNANexus next
