### ISSUE TITLE
Unexpected failure of workflow import from Dockstore to DNAnexus

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2107]
These workflows fail to import:

https://platform.dnanexus.com/panx/tools/import-workflow?source=https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FFunctional_Equivalence/versions/1.17.0

https://platform.dnanexus.com/panx/tools/import-workflow?source=https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FCRAM_no_header_md5sum/versions/1.19.0

DNAnexus team is informed.
Need to independently test the import once DNAnexus reports that the bug is resolved.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-124)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-124
┆Epic: Test DNANexus

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Both workflows now successfully export to DNANexus.

**Comment by cricketsloan** [comment]
I used the Dockstore.org ( http://Dockstore.org ) site and tried to export the U of Michigan aligner checker github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline_wdl_checker:1.31.0 ( http://github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline_wdl_checker:1.31.0 ) to DNANexus but received an error from DNANexus:

[33mEmpty output section, no outputs will be generated

Runtime attribute preemptible for task PreAlign is unknown

Runtime attribute maxRetries for task PreAlign is unknown

Runtime attribute zones for task PreAlign is unknown

Runtime attribute preemptible for task Align is unknown

Runtime attribute maxRetries for task Align is unknown

Runtime attribute zones for task Align is unknown

Runtime attribute preemptible for task PostAlign is unknown

Runtime attribute maxRetries for task PostAlign is unknown

Runtime attribute zones for task PostAlign is unknown[0m
[31mjava.lang.Exception: if is followed by parentheses, but is not a WDL standard library function
	at dxWDL.compiler.VarAnalysis.isIdentifer(VarAnalysis.scala:105)
	at dxWDL.compiler.VarAnalysis.$anonfun$split$2(VarAnalysis.scala:142)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)https://platform.dnanexus.com/projects/FQ0gB1j0‌‌bqgGbF054994z93B/data/ ( https://platform.dnanexus.com/projects/FQ0gB1j0bqgGbF054994z93B/data/ )

**Comment by melainalegaspi** [comment]
reopen when we look at DNANexus next
