### ISSUE TITLE
Test DNANexus

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2108]
We likely need another round of testing the  DNANexus connection

https://docs.google.com/document/d/1MvCHDFRcefS55fXYK8Iv8Qzodr6PyNNYv9YEbTwkZh0/edit

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-123)
┆Issue Type: Epic
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-123

**Comment by cricketsloan** [comment]
We would like to run the following on DNANexus

  * the checker workflow for the topmed alignment
  * the checker workflow for the variant caller
  * the alignment workflow on the 5 downsampled
  * possibly the alignment workflow on the 7 non downsampled

This involves the following tasks:

  * ✅ Getting a DNANexus credential for Walt
  * ✅ Getting a DNANexus payment account (Vladimir is working on this)
  * ❌ Importing Dockstore workflows into DNANexus using their url method (Consult Charles) No longer necessary since export works from Dockstore.org
  * ✅ Importing the data and the references
  * ❌ Running the workflows
  * ✅ Confirm that two bugs reported earlier are resolved (1. Option to create a new project upon import and 2. Automatic population of properties feature)
  * ( ) Reporting the results on time and cost

**Comment by melainalegaspi** [comment]
reopen when we look at DNANexus next
