### ISSUE TITLE
New DRS Plugin Release

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2113]
1. Need to do a GitHub release
2. Need to update plugins.json in Dockstore codebase to use new release.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-174)
┆Issue Type: Story
┆Issue Number: DOCK-174
┆Epic: Improve DOS File Provisioner

**Comment by coverbeck** [comment]
No work on this for now, closing
