### ISSUE TITLE
Fix facets

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2115]
https://dockstore.org/search?labels.value.keyword=topmed&searchMode=files

* the entry type is redundant 
* author and anything that is really long needs an autocomplete search to find
* the tool registry and workflow source control should only show up in its appropriate page: example- choose something that says tools to pop through to tools or don't have facet show up when workflow shows up
* tool namespace and workflow organization: has to be rethought to how it will fit with organization/organisation 
* labels: has to be handled like author 

there are a few more things....

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-216)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-216
┆Sprint: Backlog
┆Issue Type: Epic

**Comment by Ldcabansay** [comment]
#2062 #1814 also relate to facet improvements

**Comment by Ldcabansay** [comment]
Searching usability could be improved if facets also had 'include' functionality, whereas now it is just functions to filter the text query. How we handle search with include vs exclude by label will also be relevant to aliases.

For example to search for all entries belonging to a label the user has to leave the actual text search field empty and use only the label facet on the search page. From the facet drop down, the user would then select only the desired label out of the list of all possible labels in dockstore. This is not an intuitive process. 

Alternatively, if the user selects a label from an entry's landing page, it will navigate to the same search result described above which is an easier if roundabout way of getting all results for a label.

**Note:** This could also fall under advanced search, but currently advance search doesn't let you search by facets, only files and descriptions.

**Comment by denis-yuen** [comment]
Ensure that ticket is discussed in a storytime
