### ISSUE TITLE
Implement v2 final of TRS tools endpoint efficiently

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2125]
## Feature Request 

The [TRS implementation to fetch tools](https://github.com/ga4gh/dockstore/blob/bc44978b33bc8511e8f734e411e8b64453e71c1d/dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsApiServiceImpl.java#L272):

1. Fetches all published workflows and tools
2. Filters them in the Java code based on criteria
3. Returns up to a user-specified limit (1,000 if not explicitly specified) as the response.

This doesn't matter too much today, given that we have less than 1,000 published tools + workflows, but as the number of published tools + workflows increases (I have ~3,500 in my local setup), a lot of tools and workflows are being unnecessarily fetched server-side, java objects created, only to be discarded.

Ideally this could all be done with SQL, specifying the criteria as parameters and specifying a limit.

The complication is that there are currently two queries, one for tools and one for workflows, but we sort the results of the queries together. If that behavior is required, then we would need to limit each query to the same value, which could mean returning up to 2x more to the server than what the client will get.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-522)
┆epic: Performance improvements 
┆fixVersions: Dockstore 1.12,Dockstore 1.11.X
┆friendlyId: DOCK-522
┆sprint: Seabright Sprint 10 Jet Ski
┆taskType: Story

**Comment by denis-yuen** [comment]
Sitemap might be a simpler place to start, from staging.dockstore.org performance testing
```Only the sitemap and TRS endpoints really slow down ... ```

**Comment by denis-yuen** [comment]
Punting optimization to 1.8.0 if not started

**Comment by denis-yuen** [comment]
See also #1834

**Comment by denis-yuen** [comment]
This seems mislabeled given that we haven't implemented v2 final yet

**Comment by coverbeck** [comment]
> This seems mislabeled given that we haven't implemented v2 final yet

I vaguely remember this being discussed at a storytime or backlog grooming. The ticket was originally written up to improve the performance of the TRS tools endpoint. At the meeting it was suggested that when we implement TRS v2, we implement this endpoint efficiently as part of that work, and this was the suggested title by somebody.

That said, I feel like it's probably worth separating TRS v2 and this.

**Comment by denis-yuen** [comment]
Also see comment at https://github.com/dockstore/dockstore/pull/3221#discussion_r377455410

**Comment by coverbeck** [comment]
Going to put this on hold for now. Have one PR, #3661 , which has major performance improvements and is maybe 80% complete, but uses "hand-crafted" DTOs that can be difficult to maintain.

The other approach is to make all Entry associations lazy, then use EntityGraphs to load everything in one or very few SQL statements. We're working our ways towards that. Once we are able to try that, we can compare that approach with the #3661 approach and see if performance is comparable.

**Comment by coverbeck** [comment]
Verification instructions: Fetch all tools from dev and compare results with the following; it should be faster:

```
gtime curl "https://dev.dockstore.net/api/ga4gh/trs/v2/tools" | jq 'length'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5729k    0 5729k    0     0   107k      0 --:--:--  0:00:53 --:--:-- 1307k
0.06user 0.10system 0:53.11elapsed 0%CPU (0avgtext+0avgdata 6200maxresident)k
0inputs+0outputs (13major+1735minor)pagefaults 0swaps
678
```

1. `time` instead of `gtime` if on Linux; you may need to install gtime if on a Mac.
2. `jq` is optional, although it helps confirm you are comparing with a similar number for published entries.
2. 678 is the number of published tools and workflows; the number should be similar or else it's not a fair test.
3. If the response only takes a few seconds, it probably means you're getting a cached response and it's not a valid comparison. Try adding a limit query param so the cache is not used, e.g., `curl "https://dev.dockstore.net/api/ga4gh/trs/v2/tools?limit=800" | jq 'length'
4. Expecting about a 4x improvement, so hopefully response time should around ~13s, but the deployment is different in dev vs. local, so we'll have to see.

**Comment by coverbeck** [comment]
Ran this myself because I was curious:

```
gtime curl "https://dev.dockstore.net/api/ga4gh/trs/v2/tools" | jq 'length'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6543k    0 6543k    0     0   344k      0 --:--:--  0:00:19 --:--:-- 1438k
0.06user 0.11system 0:19.03elapsed 0%CPU (0avgtext+0avgdata 6224maxresident)k
0inputs+0outputs (8major+1742minor)pagefaults 0swaps
767
```

A 2.7x improvement, but with a larger dataset coming back.

**Comment by denis-yuen** [comment]
Current change verified, putting back into in-progress/backlog for further changes relating to either lazy loading or DTO objects

**Comment by coverbeck** [comment]
Played with it quite a bit on staging; with requests rates much higher than our current usage, heap usage never exceeded 20%.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.12) - 1.11.12

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.5) - 2.8.5

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2.1) - 1.11.2.1
