### ISSUE TITLE
Look at prettier (typescript code style)

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2130]
### Desired behaviour

Investigate use of https://github.com/prettier/prettier
See also #1174 #1573

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-524)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-524

**Comment by garyluu** [comment]
For vscode: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
and
```
  "[typescript]": {
        "editor.formatOnSave": true
    },
```
in settings.json

**Comment by garyluu** [comment]
Use husky + git secrets to automatically set it up https://prettier.io/docs/en/precommit.html
