### ISSUE TITLE
--script carried between tests

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2135]
### Expected behaviour
When there's multiple tests each running Client.main(...) with `--script` and no `--script`, I expect no `--script` to be honored.

### Actual behaviour
The first test that has `--script`, the following tests with have `--script`

### Steps to reproduce the behaviour 
Run the WorkflowInDirectoryTestIT and output the SCRIPT variable

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-529)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-529

**Comment by denis-yuen** [comment]
note to implementer, this is strictly a bug with the tests

**Comment by denis-yuen** [comment]
@agduncan94  punting, this is more of a like to have

**Comment by agduncan94** [comment]
I'm a bit confused about the issue. Is it that if I run multiple tests, once one test runs with --script, the following will also have --script even if they have script set to false? If that is the issue then I don't see it on develop.
