### ISSUE TITLE
Fix flaky cypress test

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2145]
## Bug Report
In the file `group1/checkerWorkflowFromTools.ts` from the UI, there is a test that does not pass consistently on travisci and locally. Once it fails, it tends to keep failing repeatedly. Unsure of which test it is.

### Steps to reproduce the behaviour 
Not sure how to reproduce. Seems to just happen randomly.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-537)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-537

**Comment by garyluu** [comment]
If this happens to already be fixed, you can try fixing the postgres resetDb.sql timeout problem instead which is even more flakey

**Comment by denis-yuen** [comment]
Punt
