### ISSUE TITLE
UI should show new .dockstore.yml filetype.

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2157]
## Feature Request 

As part of the implementation for #2148 , a new SourceFile type was added for the `.dockstore.yml`. See [DOCKSTORE_YML](https://github.com/ga4gh/dockstore/blob/137f86c21b61520cc690599e05896e309af1cfca/dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceFile.java#L68) in SourceFile.java.

The UI should display this file when looking at a hosted entry with a `.dockstore.yml`.

Ideally, possible, this change should be done such that if/when new file types are added in the future, changes to the UI are not required.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-543)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 14 Nordland
┆Issue Number: DOCK-543
┆Epic: Publish Workflows via Zip

**Comment by denis-yuen** [comment]
Working with https://staging.dockstore.org/services/github.com/denis-yuen/app-support-prototype:2.0?tab=info
