### ISSUE TITLE
Create GUI for creating aliases

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2161]
### Desired behaviour

Follows https://github.com/dockstore/dockstore-ui2/pull/552

Create user interface for generating aliases (ex: uuids) and sharing them as in the organizations wireframe (sharing button)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-546)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-546
┆Epic: Dockstore in FAIRShake

**Comment by agduncan94** [comment]
Webservice does not currently return aliases for org/collection (lazy loaded)
