### ISSUE TITLE
"Launch With" integration with SevenBridges

### ISSUE THREAD

**Issue by briandoconnor** [dockstore/dockstore#217]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-442)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-442
┆Epic: Launch-with Support

**Comment by denis-yuen** [comment]
Woo!
:fireworks: :champagne: 
https://github.com/dockstore/dockstore-ui2/pull/766
