### ISSUE TITLE
Investigate new WDL 1.0 Java Parser

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2171]
Currently we use WDL4S, though it is deprecated.

Should investigate if the new parser works. Pros - in java and a single file
https://github.com/openwdl/wdl/tree/master/versions/1.0/parsers/java/java8

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-555)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 9 Ice Boat
┆Issue Number: DOCK-555

**Comment by davidbenjamin** [comment]
@garyluu In the meantime, does this mean that every script written with WDL 1.0 will not work in dockstore, or will some WDL 1.0 features parse correctly?  In particular, I'm eager to be able to use the `parameter_meta` blocks for optional localization.

**Comment by garyluu** [comment]
In the meantime, we've relaxed on the WDL 1.0 validation.  How well parsing works will depend on a case to case basis depending on the specific WDL descriptor.  You can let us know which specific workflow it is and we'll see if there's something that can be done before we get a real WDL 1.0 parsing implemented.

**Comment by davidbenjamin** [comment]
Thanks!  I will see how it goes and report back.

**Comment by agduncan94** [comment]
womtool investigation/impressions
* simply download JAR and use
* doesn't seem to work with pre WDL 1.0 (at least the most recent release) -> looks like support for draft-3 was dropped in v35

Features include:
* validate
* generate inputs
* parse (create AST)
* graph (create a DOT graph, another visualisation option)

**Comment by davidbenjamin** [comment]
@garyluu I was able to import a simple WDL 1.0 script with a few structs into Dockstore.  It complained about unrecognized syntax but let me do it.  My goal here was to get around Firecloud's WDL validation (Firecloud uses a Cromwell version that supports WDL 1.0 and theoretically the only obstacle is its version of womtool.  It was speculated that Firecloud might not validate a WDL from Dockstore).  This workaround did not succeed, so I won't have any requests from Dockstore for now.

**Comment by agduncan94** [comment]
Based on discussion with Jeff Gentry and others, WOMtool seems like the best bet.
There are individual parsers that WOMtool calls out to that we could use ourselves, however we would need to write code to determine the version of the WDL file and call out to the proper parser. Adam Nichols recommends that we use WOMtool because it automatically chooses the correct parser to user.

WOMtool is available at https://broadinstitute.jfrog.io/broadinstitute/libs-release/org/broadinstitute/womtool_2.12/
