### ISSUE TITLE
Search page should remember items per page

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2175]
## Feature Request 

Similar to #1621, the Search page should remember the user's selection of items per page rather than falling back to the default every time the user visits the page.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-556)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-556

**Comment by denis-yuen** [comment]
FYI, going to put this in 1.6.0, but I'd consider it lower priority than outstanding bugs

**Comment by coverbeck** [comment]
Agreed; I was actually thinking it would go into 1.7.0 when I wrote it. :)

**Comment by denis-yuen** [comment]
Verified on staging.dockstore.org
