### ISSUE TITLE
Create organization request notification of accept/reject

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2177]
### Desired behaviour
The user who submitted a create organization request should get an accounts page notification and/or email notification to update them when their request has been accepted/rejected.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-558)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-558
┆Epic: Organization Improvements

**Comment by Ldcabansay** [comment]
see related #1646 #910

**Comment by Ldcabansay** [comment]
Should also show on requests page that a pending organization request was rejected. Currently when an organization is rejected it just disappears from the pending requests lists. The name of the rejected organization also can't be re-used.

**Comment by denis-yuen** [comment]
Use same mechanism as #2328 and/or #1646

**Comment by cricketsloan** [comment]
➤ Natalie Perez commented:

duplicate of https://ucsc-cgl.atlassian.net/browse/DOCK-807?atlOrigin=eyJpIjoiYjBjNDc0YzQ4NzlmNGY2ZThjMTNlOTU1MWJhOTlkZDQiLCJwIjoiaiJ9 ( https://ucsc-cgl.atlassian.net/browse/DOCK-807?atlOrigin=eyJpIjoiYjBjNDc0YzQ4NzlmNGY2ZThjMTNlOTU1MWJhOTlkZDQiLCJwIjoiaiJ9|smart-link )
