### ISSUE TITLE
Add flag to view stubbed workflows from CLI

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2184]
## Feature Request 

Add a flag to the CLI bindings to display stubbed (and unstubbed) entries.

### Desired behaviour

Following https://github.com/ga4gh/dockstore/issues/1773 , stubbed workflows no longer appear in the CLI output. The workflows are still made available by the web service. Providing an optional flag would let CLI clients manage both stubbed and unstubbed workflows.

### Expected behaviour

A flag like `--show-stubs` in the CLI.

### Actual behaviour

No flag, stubs are filtered out

### Steps to reproduce the behaviour 

`dockstore workflow publish` will list workflows regardless of their publicity.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-564)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-564

**Comment by melainalegaspi** [comment]
discouraging stub creation in favor of whitelist wizard
