### ISSUE TITLE
Collection does not belong to organization

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2192]
## Bug Report
Discovered during https://github.com/ga4gh/dockstore/issues/2190

### Expected behaviour
If you're an admin (maybe a curator too), 
https://staging.dockstore.org/api/static/swagger-ui/index.html#/organizations/getCollectionById
The organization ID should matter.  Trying to get a collection that does not belong to the organization should result in an empty response or error.

### Actual behaviour
The organization ID in the endpoint does not matter at all.  If the collection ID is there and is valid, you can grab every collection.

### Steps to reproduce the behaviour 
In the swagger, set organization ID as 1.  Cycle through all the collection IDs that exist.

### Environment (Browser or OS and Dockstore version)

DockstoreAPI - 1.6.0-beta.0

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-567)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-567

**Comment by denis-yuen** [comment]
* Was able to reproduce as an admin
* Users without credentials cannot see collections that they otherwise would not have access to

Punting for now
