### ISSUE TITLE
Speed up builds

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2215]
### Desired behaviour
We have too many things running on Travis CI, move some to Circle CI

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-579)
┆Issue Type: Epic
┆Fix Versions: Open-ended research tasks
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-579

**Comment by denis-yuen** [comment]
Idea 1:

Move coverage tests to CircleCI
- pros
   - would effectively cut build time in half
- cons
   - need to store confidential tokens twice
 
Idea 2: 
Move tests that don't require confidential tests to Circle CI
- pros
   - would speed up build
- cons
   - the bulk of testing would still remain on Travis

**Comment by denis-yuen** [comment]
In discussion with @garyluu 
Can give a shot to moving ui2 builds to CircleCI to avoid incoming webservice builds

**Comment by denis-yuen** [comment]
forkmode
worth a shot 
https://news.ycombinator.com/item?id=19763814

**Comment by denis-yuen** [comment]
Thought I typed this somewhere, but we should also look at https://aws.amazon.com/codebuild/pricing/?nc=sn&loc=3 and https://cloud.google.com/cloud-build/

With our historical data on Travis-CI we should be able to get together a cost estimate for how much it would cost to move builds for either the webservice or UI onto them. (And whether it would be more cost effective than simply paying for Travis-CI or Circle CI for increased build capacity)

One partial advantage for AWS, moving around encrypted bundles would be easier and could avoid bot users and/or integrate with other AWS services.  Scuttlebutt is that CloudBuild might be easier to use/is superior

**Comment by denis-yuen** [comment]
Alternatively, split up our build? 
We have two large components, the CLI and the webservice. Maybe they could be split into different repositories. That will make testing a bit trickier since they both share some language parsing code, but not a whole lot.

**Comment by garyluu** [comment]
- Are units tests ran on both CircleCI and Travis?
- For the UI in CircleCI, we can build the UI once and then copy that to the multiple jobs and run integration tests on it.  For the webservice, can we do the same (not mvn clean install)?

**Comment by denis-yuen** [comment]
>     * Are units tests ran on both CircleCI and Travis?

Yup, I think in both cases we use unit tests to act as a smoke test (i.e. don't run integration tests if unit tests fail, don't run deploys to cloudfront, check for database consistency, etc.)

>     * For the UI in CircleCI, we can build the UI once and then copy that to the multiple jobs and run integration tests on it.  For the webservice, can we do the same (not mvn clean install)?

Yes, I think we'd have to rig up our own storage for this though https://docs.travis-ci.com/user/build-stages/#data-persistence-between-stages-and-jobs

**Comment by coverbeck** [comment]
May delegate to Andy and/or Emily
