### ISSUE TITLE
Use should before click in cypress testing

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2225]
https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/#Try-and-try-again

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/DOCK-592)
┆Issue Type: Task
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-592

**Comment by denis-yuen** [comment]
@garyluu mentioned this is probably best practice, but doesn't quite solve test failures
can add to style doc for cypress testing
