### ISSUE TITLE
Alert state should be cleared before a new page is loaded

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2230]
## Feature Request 
Right now, the alert state is only cleared when a new page containing a component using the alert service (`alertService.start()`) is loaded. So, if a page doesn't use the alert service, the state will not get cleared and can cause bugs like ga4gh/dockstore#2124 .  The responsibility of clearing the state should be on the component that caused it to get set in the first place, not on the new page.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-590)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-590

**Comment by denis-yuen** [comment]
How widespread is this?

**Comment by NatalieEO** [comment]
ga4gh/dockstore#2124 more widespread than I initially thought.

**Comment by coverbeck** [comment]
@NatalieEO @garyluu I think we can close this one with the other fix, right?

**Comment by denis-yuen** [comment]
@garyluu investigate if done, or this might be just review of the PR

**Comment by garyluu** [comment]
State changed on page clear, should be fine.
