### ISSUE TITLE
Handle empty link

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2240]
### Expected behaviour
If empty string was passed in as an organization website link, webservice should handle it by assuming it's null.

### Actual behaviour
Webservice believes the link was what the user wants and throws invalid link error.

### Steps to reproduce the behaviour 
Edit organization, put link, remove link, update organization button.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-585)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-585

**Comment by denis-yuen** [comment]
Hmmm, I think I'd prefer the organization link to be mandatory

**Comment by denis-yuen** [comment]
Now mandatory https://github.com/dockstore/dockstore/blob/3fc0698e2d52345ce1687ba15fbad7459eb815e7/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java#L534
