### ISSUE TITLE
Serve UI from S3/CloudFront

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2247]
## Feature Request 

Currently the dockstore.model.ts has to be changed for each environment that the UI is run on. If instead the information were retrieved via an API:

* The same UI build would be running in staging and production
* The UI could be built in advance. Today it is part of the deploy process, and sometimes fails.
* The UI build could be copied to and served from s3 (or from a CDN -- see #2242 ).
* The UI could be deployed separately from the webservice.
* Doing a UI release would be as simple as having nginx/router point to an s3 URI.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-596)
┆Issue Type: Epic
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-596

**Comment by garyluu** [comment]
Likely going to have to use CloudFront to deal with all the routing problems for s3

**Comment by denis-yuen** [comment]
Make it so (in like a month)

**Comment by garyluu** [comment]
May also have to find and replace `src="../assets` with `src="/assets`

**Comment by garyluu** [comment]
Speak of the devil: https://firstclassjs.com/deploy-angular-application-to-aws-s3-and-cloudfront/

**Comment by cricketsloan** [comment]
This was a poor title for an epic: Don't have hard-coded dockstore.model.ts
