### ISSUE TITLE
Separate Elasticsearch Tests

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2254]
### Expected behaviour
SearchResourceIT and ElasticManagerIT should have their own elasticsearch running.  Once they're done with their tests (successfully or not), it should shut down its elasticsearch.

### Actual behaviour
SearchResourceIT and ElasticManagerIT do not have their own elasticsearch running.  If something is wrong in SearchResourceIT (not handle no index properly), it will still run fine because ElasticManagerIT will have previously create the index for SearchResourceIT.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-599)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-599

**Comment by denis-yuen** [comment]
Check-in with @david4096 might be redundant

**Comment by david4096** [comment]
I can confirm that the docker container will be restarted during integration tests.

https://github.com/dockstore/dockstore/pull/3025/files#diff-a54258b10da6687aef2c99cbf70a7d81R70
