### ISSUE TITLE
When posting a zip, see if contents already exist

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2259]
## Feature Request 
When posting a zip to create a new revision of a hosted workflow, we should check if the contents match the previous version's, and if so, not create a new revision.

See [this commit](https://github.com/ga4gh/dockstore/pull/2208/files#diff-0fe8aa76f8e46d26e28c81901f941045R218), where the check is already done if creating a new revision via the PATCH endpoint.

Note that the tests in [this PR](https://github.com/ga4gh/dockstore/pull/2256) will need to be modified as part of this fix, as the test relies on a new revision being created every POST, even with the same content.

This should be applicable to uploading as a JSON or uploading as a .zip, if it looks like the implementation for zip upload is independent from JSON upload, then do it only for JSON and ignore the zip endpoint. Also deprecate zip endpoint.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-603)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-603
┆Epic: Publish Workflows via Zip

**Comment by NatalieEO** [comment]
Endpoint is deprecated
API - 1.9.0-alpha.4-SNAPSHOT
