### ISSUE TITLE
Slow downloads using GS file provisioning plugin

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2268]
### Expected behaviour
The gs file provisioning plugin allows downloads from google buckets specified using `gs://` paths. The download speed from a bucket shouldn't differ when specified as `gs://` or `https://`. 

### Actual behaviour
Downloading the input files from `gs://` paths is significantly slower(~2-3x) than using the  `https://` paths.
### Steps to reproduce the behaviour
Download and unzip attached jsons and run the example workflow. (note: this workflow downloads large files and is selected to demonstrate speed, you don't need to let workflow complete to reproduce behavior) 

Note: you need to run this on 1.6.0+ with gs plugin support, easiest way to do this is to run dockstore CLI on the latest unstable version (rather than production) to do so: ```dockstore --upgrade-unstable```

Run with gs download:
[gsInput.json.zip](https://github.com/ga4gh/dockstore/files/2993958/gsInput.json.zip)

```
dockstore workflow launch --entry github.com/vgteam/vg_wdl/vg-pipeline-workingexample:master --json gsInput.json
```

Run with https download:
[httpInput.json.zip](https://github.com/ga4gh/dockstore/files/2993959/httpInput.json.zip)
```
dockstore workflow launch --entry github.com/vgteam/vg_wdl/vg-pipeline-workingexample:master --json httpInput.json
```

### Environment (Browser or OS and Dockstore version)
Dockstore version 1.6.0-beta.4

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-609)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6.x
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-609

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Fix if it's easy.

**Comment by NatalieEO** [comment]
Using Dockstore CLI version 1.6.0 vs 1.7.0-rc.0 the timing difference launching the same tool is 
real	3m55.377s
user	2m42.931s
sys	0m52.779s

real	0m34.498s
user	0m17.950s
sys	0m4.574s

Much faster
