### ISSUE TITLE
Dockstore CLI JAR should be smaller

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2270]
## Feature Request 

It seems like the CLI JAR could be smaller. I took a quick look at its contents, and noticed, for example, that it currently includes, which I don't think would ever be used by the CLI (?):

* Postgres driver and Apache DB connection pooling classes
* Findbugs

The JAR is 3M smaller in 1.6 than 1.5, but it is still 47M. I discovered this when wondering why it took relatively long to display the CLI's help.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-610)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-610

**Comment by denis-yuen** [comment]
Webservice Jar could probably use some work too

**Comment by denis-yuen** [comment]
Noticed some aws jars in Dockstore webservice, but this likely has moved out to https://github.com/dockstore/s3-plugin

**Comment by denis-yuen** [comment]
> Noticed some aws jars in Dockstore webservice, but this likely has moved out to https://github.com/dockstore/s3-plugin

AWS stuff is actually for SQS integration

**Comment by denis-yuen** [comment]
Re-open in other tickets  for more specific suggestions
