### ISSUE TITLE
Update to compatible node + global @angular/cli version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2279]
### Expected behaviour
compose_setup and dockstore-ui2 should be using compatible node and @angular/cli versions which at the time of writing is 10.13.0 and 7.0.4 respectively

revert https://github.com/dockstore/dockstore-ui2/commit/be3c0478800dafbc0fb7a074d329338cc4bf240a and the travis wait in the compose_setup

_Modify to not use a global @angular/cli version at all_

### Actual behaviour
It is using node ~8 and 6.0.2 respectively

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-612)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-612

**Comment by denis-yuen** [comment]
Will soon be made obsolete with cloudfront deployment
