### ISSUE TITLE
Default DAG visualization has larger font

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2281]
## Bug Report

In staging (1.6), the DAG for this particular WDL is not "spread out as well" as it is in production (1.5). Things overwrite each other, at least for this particular workflow. More easily described with screenshots:

### Production

https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=dag
![Screen Shot 2019-03-25 at 1 33 43 PM](https://user-images.githubusercontent.com/1049340/54952587-8b2d2a80-4f03-11e9-81a8-23d1734dcc9f.png)

### Staging

https://staging.dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=dag

![Screen Shot 2019-03-25 at 1 40 56 PM](https://user-images.githubusercontent.com/1049340/54952618-a730cc00-4f03-11e9-8a35-4d571d78eb90.png)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-615)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-615

**Comment by denis-yuen** [comment]
Seems completely broken
500 error on the underlying dag request, maybe related to WDL 1.0 work

**Comment by denis-yuen** [comment]
Looks fixed, probably by https://github.com/dockstore/dockstore/pull/2807
On staging at 1.7.0-rc.0
