### ISSUE TITLE
Cannot search organization or collection by display name

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2282]
Go to staging.dockstore.org
Click on Organizations
Note that 'Ontario Institute for Cancer Research' is an organization
Enter 'Ontario Institute for Cancer Research' in the search box at the top of the page
See message "No organizations found"
Enter 'oicr5'
See 'Ontario Institute for Cancer Research' 

The UI and swagger API does not support searching on a display name, only 'name' and 'alias'
This is also true for searching collections.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-614)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 14 Nordland
┆Issue Number: DOCK-614

**Comment by denis-yuen** [comment]
![Screenshot from 2019-07-05 15-06-58](https://user-images.githubusercontent.com/1730679/60741221-94805700-9f36-11e9-87e1-9a1124efeeaa.png)

**Comment by garyluu** [comment]
Search collections of an organization are going to be too network-intensive for the user without elasticsearch.  I don't recommend it.

**Comment by Ldcabansay** [comment]
Verified on Dockstore 1.7.0-beta.2
