### ISSUE TITLE
Terra to launch TRSv2 workflows incl. 'file includes'

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2288]
Work with the Broad to establish: Ability to launch TRS v2 workflows including those that have 'file includes'.  SmartSeq2 workflow is an example of a workflow that Terra should be friendly to.

https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SEAB-126)
┆Issue Type: Story
┆Issue Number: SEAB-126
┆Epic: Objective 3: Demo HuBMAP relevant workflows in Terra

**Comment by denis-yuen** [comment]
that's odd ...

**Comment by cricketsloan** [comment]
I am not sure why there are two tickets here.  I think that Michael B and Lighthouse would be advising on CAL-334

**Comment by cricketsloan** [comment]
➤ Stefan Kuhn commented:

@Cricket - I think you’re right. Rejecting accordingly. This ticket came out of the HuBMAP plan.
