### ISSUE TITLE
dockstore-ui2 build index.html

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2290]
### Desired behaviour
dockstore-ui2 should know how to build its own index.html file (either using npm config, environment var, etc) and not require compose_setup to do it.  This is so that changes in the index.html doesn't need to be duplicated in the compose_setup repo.

https://github.com/angular/angular-cli/issues/8759

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-620)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-620

**Comment by denis-yuen** [comment]
@garyluu seems like you're on the case already

**Comment by garyluu** [comment]
Trying...

**Comment by denis-yuen** [comment]
Going to call this done since https://github.com/dockstore/compose_setup/blob/1.6.0/templates/index.html.template is no longer with us
