### ISSUE TITLE
Pass through login errors

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2291]
### Expected behaviour

Alert should not be blank

### Actual behaviour

Used an incognito window with the dockstoretestuser, google login
You get a blank alert as a user.
But expanding the actual call in dev tools I see "Login failed, you may need to register an account". Meaning, I need to click right for registration.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-622)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-622

**Comment by coverbeck** [comment]
Confirmed that I do see a big red box on staging with the message "Login failed, you may need to register an account" when logging in with a non-registered Google account.

I think we need a better UI for displaying such messages, but that's beyond the scope of this ticket.

API - 1.7.0-beta.5
UI - 2.4.0-beta.4
