### ISSUE TITLE
Consistent alignment of buttons

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2292]
### Expected behaviour

Consistent alignment

### Actual behaviour

The "Add tag" button and "close" are left aligned in assets/images/docs/tageditor_modal.png now whereas the button is on the right for "Register Tool", "Register Workflow", "Create Organization Request", etc.?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-621)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-621

**Comment by garyluu** [comment]
See style guide for how to do that.
