### ISSUE TITLE
Link to docs should open in new tab

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2295]
## Feature Request 
It'd be nice if the link to the docs opened in a new tab. Sometimes while I'm on staging, I accidentally click the docs and forget that the links there don't go back to staging.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-624)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 22 Whaleboat
┆Issue Number: DOCK-624

**Comment by Ldcabansay** [comment]
LGTM, 
API - 1.8.0-alpha.2
UI - 2.5.0-alpha.0
