### ISSUE TITLE
Improve efficiency of refresh calls (refresh all vs org)

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2311]
Currently, for GitHub workflows at least, when you refresh all or refresh an organisation, we grab every single repository, sometimes more than once, regardless of if it makes sense (ex. grab all workflows related to a user, when only refreshing a certain organisation).

Really we should grab all if doing a refresh all, or just from a specific organisation if refreshing that organisation. Should add some speedup.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-634)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-634

**Comment by denis-yuen** [comment]
Hopefully obsolete (or less important) due to #2400

**Comment by coverbeck** [comment]
| we grab every single repository, sometimes more than once

Running into this with Sync services, not sure if we should consider reopening:

1. We fetch all of the user's repos [here](https://github.com/dockstore/dockstore/blob/06622c2dfe440557a7e0aacc0bd85ec5b4dc097a/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitHubSourceCodeRepo.java#L221) with one (paginated) call.
2. We then fetch each repo one-by-one [here](https://github.com/dockstore/dockstore/blob/06622c2dfe440557a7e0aacc0bd85ec5b4dc097a/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitHubSourceCodeRepo.java#L260), which is invoked from [here](https://github.com/dockstore/dockstore/blob/06622c2dfe440557a7e0aacc0bd85ec5b4dc097a/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/SourceCodeRepoInterface.java#L185), to get information that was already fetched in step 1.

**Comment by denis-yuen** [comment]
@coverbeck simply making the call twice might not be actually retrieving the data twice due to 
conditional requests https://github.com/dockstore/dockstore/pull/1330

The multi-threaded ticket https://github.com/dockstore/dockstore/issues/2668 makes sense

**Comment by coverbeck** [comment]
Ah cool, did know about that. Took a quick glance at the PR, and I think my comments *might* still apply the first time a user does a refresh, as points 1 and 2 from my previous comment are for different endpoints.
