### ISSUE TITLE
Tag Cloud and Search Field Not Clearing

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2314]
### Expected behaviour
Tag Cloud and search field should work together

### Actual behaviour
They don't

### Steps to reproduce the behaviour 
1. Go to https://staging.dockstore.org/search?searchMode=files
2. Click a word
It will put the word in the search field and then do the search properly
3. Erase the term in the search field
The search is not performed
The url does not change
If the above behavior isn't observed, click the same word and erase it again.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-636)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6.x
┆Issue Number: DOCK-636

**Comment by garyluu** [comment]
Also check that clear filters work

**Comment by denis-yuen** [comment]
Looks functional on staging.dockstore.org
