### ISSUE TITLE
Warning about resetting github token for new orgs

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2316]
If you join an org on github after you've created the github token, you'll need to unlink and link again to be able to retrieve tools/workflows from that org. We should add a warning/note about this on the accounts page.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-637)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-637

**Comment by denis-yuen** [comment]
@agduncan94 this is weird and should not be the case. Is it possible the scope changed (i.e. the old token had the wrong scope)

**Comment by agduncan94** [comment]
This does not seem to be the case. It was likely due to the following issue https://docs.dockstore.org/faq/#why-are-my-workflows-from-an-organization-i-belong-to-not-visible

> Organizations have the ability to restrict access to the API for third party applications. GitHub provides a tutorial on how to add these restrictions to your organizations.
> 
> In order for Dockstore to gain access to organizations of this type, you will need to grant access to the Dockstore application. Dockstore will only be reading information on workflows in your organization and who has access to them in order to mirror these restrictions on Dockstore itself. GitHub provides a tutorial for approving third party apps access to your organization.

I think a possible solution would be on the my workflow page to have some sort of note saying
"Don't see an organization here? Make sure that the organization does not restrict third-party application access."

**Comment by david4096** [comment]
I can confirm this message appears in staging.dockstore.org.

API - 1.7.0-rc.0
UI - 2.4.0-rc.0
