### ISSUE TITLE
Update to postgres 11

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2321]
### Desired behaviour

Update to postgres 11 to match AWS RDS and gain some parallelism performance enhancements
https://aws.amazon.com/rds/postgresql/why-postgresql-11/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-641)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-641

**Comment by garyluu** [comment]
I see it updated in compose_setup, dockstore, and dockstore-ui2.  Primer still says 10 though but maybe self-explanatory enough
