### ISSUE TITLE
Changing default workflow version alert

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2322]
### Expected behaviour
Successfully changing the default workflow version should result in a success message after everything is done

Alternatively, just have one endpoint that changes the default version and also refreshes (if specified in query param).

### Actual behaviour
The default version changes fast and the success message appears, but the workflow is still refreshing right after (with a progress bar).  The user doesn't know what is going on since it already said success.

### Steps to reproduce the behaviour 
Change the default version of a workflow on a reasonably slower network connection.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-640)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-640

**Comment by coverbeck** [comment]
@garyluu Is this still applicable? Do we still refresh the version when setting the default?

**Comment by garyluu** [comment]
Hmm...I think the reason was because we needed the entry level metadata to update.  Probably not anymore.

**Comment by denis-yuen** [comment]
Doesn't look like it does a refresh on staging either
