### ISSUE TITLE
Workflow tool info 500

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2323]
### Expected behaviour
If the workflow cannot get the tool table info, return a proper response code instead of 500

### Actual behaviour
Getting 500 errors https://staging.dockstore.org/api/workflows/8682/tools/19758

### Steps to reproduce the behaviour 
Visiting a bunch of workflows and change versions.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-639)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-639

**Comment by melainalegaspi** [comment]
reopen with more details if needed
