### ISSUE TITLE
Tooltester Launch Entry

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2324]
### Desired behaviour
Tooltester currently only tests:
- the Dockstore CLI
- the TRS API

And launches via --local-entry (after cloning git repo), it should be changed to --entry to extend testing to test more of the webservice too.  It can also be changed to --local-entry but with zip.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-642)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-642

**Comment by denis-yuen** [comment]
Update tooltester to run checker workflows currently
Other work to properly use zip download is longer term

**Comment by garyluu** [comment]
quay.io/pancancer/pcawg-sanger-cgp-workflow  2.0.6
- [x] Manual test locally 
- [x] Verify on staging
  - curl -X POST "https://staging.dockstore.org/api/api/ga4gh/v2/extended/quay.io%2Fpancancer%2Fpcawg-sanger-cgp-workflow/versions/2.0.6/CWL/tests/test1.json?platform=Dockstore&platform_version=1.6.0-rc.0&verified=false&metadata=Dockstore%20team" -H  "accept: application/json" -H  "Authorization: Bearer <token>"
- [ ] Run on tooltester
- [ ] Verify on production

quay.io/pancancer/pcawg-dkfz-workflow 2.1.0
- [ ] Manual test locally
  - can't run successfully
- [ ] Verify on staging
- [ ] Run on tooltester
- [ ] Verify on production

quay.io/pancancer/pcawg_delly_workflow 2.1.0
- [x] Manual test locally
- [x] Verify on staging
- [ ] Run on tooltester
- [ ] Verify on production

quay.io/pancancer/pcawg-bwa-mem-workflow unknown version
- [ ] Wait for PR to be reviewed and merged.
- [ ] Manual test locally
- [ ] Verify on staging
- [ ] Run on tooltester
- [ ] Verify on production

github.com/dockstore-testing/md5sum-checker/_cwl_checker:develop
- [x] Manual test locally
- [ ] Verify staging
- [ ] Run on tooltester
- [ ] Verify on production

**Comment by garyluu** [comment]
This was done at 1.6.0
