### ISSUE TITLE
Tools table cut off

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2325]
## Bug Report
Two bugs:

### Expected behaviour
1. The tools tab's table to not clip (word-wrap, horizontal scroll, highlight, etc).  
2. The docker images to be pull-able

### Actual behaviour
1. The tools table is cut off when the docker value is too large
2. The docker image no longer exists (or is publicly visible)

### Steps to reproduce the behaviour 
https://staging.dockstore.org/workflows/github.com/NCI-GDC/gdc-dnaseq-cwl/GDC_DNASeq:master?tab=tools

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-643)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6.x
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-643

**Comment by garyluu** [comment]
Only the first part is solved

**Comment by denis-yuen** [comment]
Sufficient on staging.dockstore.org
