### ISSUE TITLE
Filter common terms out of tag cloud

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2326]
I think we already filter common English words like 'a', 'and', 'of', etc.

There are some Dockstore specific tags I think are not necessary, like 'tool', 'workflow', 'dockstore', etc.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-645)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-645
┆Sprint: 115 - Niagara
┆Issue Type: Story

**Comment by coverbeck** [comment]
Unassigned and reassigned @y-ng to see if it triggers some Unito action.
