### ISSUE TITLE
Design for site-wide notification bar

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2328]
For when we have important news or want to link to release information, we should have a notification bar at the top of the site. Something like the following where the user can close it and we will not show it again until it has been updated.
<img width="722" alt="Screen Shot 2019-04-01 at 10 42 48 AM" src="https://user-images.githubusercontent.com/6331159/55336441-eb275200-546a-11e9-8397-5b2574203937.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-646)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 19 Tanker
┆Issue Number: DOCK-646
┆Epic: Site-wide Notification Bar

**Comment by coverbeck** [comment]
Could you also use this or something like this for pending requests as well? If you don't know to look for it by going to the accounts page, you'll never notice that you have pending requests (e.g., a request to join an org).

**Comment by agduncan94** [comment]
@coverbeck I agree, the requests are kind of hidden. The only place we link to them is at the top of the org/collection page when they are not approved/rejected. I was thinking that once we have the homepage/user profile page this will be more obvious.

I don't think we should use this for pending requests. I would be supportive of having a notification icon in the top right account dropdown or something like that. This bar was more so for site-wide alerts that are important for everyone, and not just a specific person.

**Comment by coverbeck** [comment]
May give/delegate to Andy and/or Emily
