### ISSUE TITLE
/organizations/{alias}/aliases not found

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2329]
### Expected behaviour
If alias is not found, a 404 should be returned from endpoint. 

### Actual behaviour
500 is returned

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-647)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-647
┆Epic: Organization Improvements

**Comment by coverbeck** [comment]
Because [this](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java#L797)

**Comment by denis-yuen** [comment]
Ok with aliases only working with approved orgs. 
Re-open if misinterpreted
