### ISSUE TITLE
Entry's checker link doesn't work

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2330]
### Expected behaviour
When clicking the view checker workflow link of https://staging.dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap/cgpmap-bamCsiOut:3.0.3?tab=info , the link should direct to the checker workflow

### Actual behaviour
There's a 400 entry not found in devtools when clicked and no error appears (no indication to the user).

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-648)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-648

**Comment by denis-yuen** [comment]
Gary has done ui, but there is a webservice component to this

**Comment by agduncan94** [comment]
Looks like the tool is published, but the associated checker workflow is not.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

I clicked the view checker workflow link of +https://staging.dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap/cgpmap-bamCsiOut:3.0.3?tab=info+ ( https://staging.dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap/cgpmap-bamCsiOut:3.0.3?tab=info )  and the link redirected to the checker workflow successfully
