### ISSUE TITLE
UI build itself

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2332]
### Desired behaviour
Currently the compose_setup is too dependent on certain UI versions.  The current compose_setup specifies which node version and global angular cli to install.  It also runs the prebuild step.  All these steps may not be applicable to past/future UI builds.

The UI should know how to install and build itself with simpler commands

```
npm ci
npm run build
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-650)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-650

**Comment by denis-yuen** [comment]
While at this, it would be nice if the production build didn't include testing dependencies like cypress

**Comment by denis-yuen** [comment]
Might also be worth investigating 
```
found 13 vulnerabilities (3 low, 7 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
