### ISSUE TITLE
Misc CollectionResource comments

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2342]
1. ~[Should say](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L88)"Collection to modify", not "Entry to modify".~
1.~This should be split out into its own ticket if there is agreement, but I don't think we should have paths like `/organizations/collections/{collectionId}/aliases` and `/organizations/collections/{alias}/aliases`. Normally the organization id should follow `/organizations`, and it does in many cases. Not sure what the answer is, but maybe we should have a top level aliases endpoint? Plus the second example has `{alias}/aliases` rather than the common collection/item pattern, e.g., `..../aliases/{alias}`, which really feels wrong.~ Follow-up ticket, too disruptive for 1.7
1. ~The organizationId [here](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L106) parameter is never used. If it's not used, it shouldn't be there. But see previous item. :)~ Out of date, is used now
1. ~Two places, [here](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L223) and [here](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L189), fetch the organization, but don't check if it's null. The only place the organization is used is for the event (not sure if the null org will cause an issue or not), and there is no enforcement that the collection belongs to the organization, i.e., it is possible to create an event for an org that a collection is not associated with. This sort of overlaps with the previous two items.~ Out of date, now checked with `getAndCheckCollection`
1. ~[This](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L181) will return a 404 if the entry id does not exist. The entry id is a query parameter, which I don't think is considered the resource, which if true, means it should return a 400. I think.~
1. ~The [include query param](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L293) should be preceded with an `@APIParam` documenting it.~
1. There is a call to [findAllByOrg](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L312), even though there was another one 6 lines above. Maybe that's necessitated by the calls in between, but I don't think it's necessary.
1. Error says [collection not found for org](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L429), but there was actually no check that the collection belonged to the org; the check was for whether the user had permissions on the collection.
1. Why are there separate endpoints for the collection's description? There is already an endpoint for updating the collection as a whole. Not saying we shouldn't, but we don't seem to have this pattern elsewhere.
1. ~[Swagger annotation](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java#L373) says only name and description can be updated, but code also updates topic and display name.~

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-655)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-655

**Comment by agduncan94** [comment]
7. Looks like the include isn't actually working, since it is using the sql query that selects all.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

We should review services paths as well, which came in after I did this review.

**Comment by denis-yuen** [comment]
@coverbeck 
> We should review services paths as well, which came in after I did this review.

Legitimately, a different ticket I think
