### ISSUE TITLE
Sitemap should include organizations

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2343]
## Feature Request 

The sitemap endpoint response should include approved organizations. And probably the collections of those approved organizations as well.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-656)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-656

**Comment by denis-yuen** [comment]
Verified in staging.dockstore.org
