### ISSUE TITLE
Resource classes review

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2344]
A list of miscellaneous issues seen when going through Resource classes. Should probably be broken up if there is agreement.

1. Is there any reason [this method](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java#L284) eagerly loads the users? There is a comment in there that it is doing it on purpose, but I see no use of it in the UI.
1. Is [the lack of a valid Git url](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java#L242) an error condition? Just wondering if this should be failing silently vs. returning an error.
1. [Comment](https://github.com/ga4gh/dockstore/blob/b3b1a71400a0ad0f7a15d3c0a0692034a0b77628/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java#L397) refers to workflow instead of container (ridiculously trivial). :)
1. In DockerRepoResource, several of the Swagger annotations say, for example, "Get the corresponding Dockerfile on Github.". Messages should not be GitHub specific, given other version control systems Dockstore supports.
1. The [findToolByIdAndCheckToolAndUser](https://github.com/ga4gh/dockstore/blob/75755883d4bd3b7debe24ca5f6cc2d5f0a3a1221/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java#L264) method will throw a SC_FORBIDDEN error, but some methods that call it should be returning a 404 instead, e.g., [here](https://github.com/ga4gh/dockstore/blob/75755883d4bd3b7debe24ca5f6cc2d5f0a3a1221/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java#L88)
1. The word [users](https://github.com/ga4gh/dockstore/blob/75755883d4bd3b7debe24ca5f6cc2d5f0a3a1221/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java#L152) needs an apostrophe.
1. In UserResource, there are several references in the Swagger annotations to "logged-in" user. Should probably reword, as logging in is more of a UI concept, and the API works with tokens. Not sure what to say though.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-657)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-657

**Comment by denis-yuen** [comment]
> Is the lack of a valid Git url an error condition? Just wondering if this should be failing silently vs. returning an error. 

This might be a tricky one, IIRC, it would be nice to return an error if this was a single tool. 
But this code might be re-used for batch refreshes and we don't want to abort the refreshing the whole (say, 20 tools in an org) because one tool couldn't refresh.
A superior solution now that we have validation messages might be to report refresh issues that way

**Comment by denis-yuen** [comment]
> Is there any reason this method eagerly loads the users? There is a comment in there that it is doing it on purpose, but I see no use of it in the UI.

@garyluu  might recall, it was introduced with https://github.com/ga4gh/dockstore/commit/5fb31336b608713655ce725fcf08a4db23153ad3

**Comment by garyluu** [comment]
Originally all users were eagerly loaded.  I then made all of them lazy loaded.  Then I decided if any tools were going to return the users, it should be when we grabbed a single tool...otherwise we might as well jsonignore the entire thing.

**Comment by denis-yuen** [comment]
The question is if anything uses users though, I can see pulling down starred users to populate the number of stars a tool has and/or the stargazers page. 
I see less value in the users that own a workflow though, it might be worth taking it out and seeing what breaks
