### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2347]
### Expected behaviour
When clicking on any link, it should always work (go to that page)

### Actual behaviour
Sometimes clicking on the link does nothing even though the link looks correct

### Steps to reproduce the behaviour 
Hard to reproduce.  Not exactly sure how.
Go to search page and click on a tool.  The link looks correct but doesn't actually go there.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-659)
┆Issue Type: Bug
┆Issue Number: DOCK-659

**Comment by denis-yuen** [comment]
Can't reproduce, maybe this is browser specific or account specific?
