### ISSUE TITLE
Tooltester Logs Publicly Available

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2348]
### Desired behaviour
Make tooltester logs publicly available.  Some ideas:

Use Jenkins s3 plugin to upload logs to s3 bucket and then have the dockstore webservice point to the logs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-660)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 9 Ice Boat
┆Issue Number: DOCK-660

**Comment by denis-yuen** [comment]
Also clean up OICR collab jenkins instances

**Comment by denis-yuen** [comment]
* I'd like to see one log per version of workflow kept (last success, don't care too much about failures)
* should include checker workflows 
* bucket structure can probably look like s3://dockstore.tooltester.backup/runner/#workflow/foo_org/foo_tool/<version>/output.log

* webservice should have a new config key for a s3 bucket
* if enabled, webservice can look at bucket and return via a new endpoint logs for a version of a workflow
* user can in the GUI click through the UI and link a snippet of the log that is useful for click through to the full log ala. travis

**Comment by denis-yuen** [comment]
- [x] Also clean up OICR collab jenkins instances
- [x] I'd like to see at least one log per version of workflow kept (last success, don't care too much about failures)
- [ ] should include checker workflows (not sure if not run, or not visible)
- [x]  bucket structure looks good

the rest look good, will just create new issue
