### ISSUE TITLE
Dockstore CLI should optionally still launch if it can't parse descriptors

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2349]
## Feature Request 

If the Dockstore CLI can't parse the WDL descriptors, it won't launch the WDL.

This is a currently an issue on staging with running 1.0 WDL workflows, because Dockstore cannot parse WDL 1.0. Even after Dockstore supports 1.0, this issue can possibly crop up again as newer versions of WDL are introduced.

Ideally, or at least optionally,  the Dockstore CLI should continue to launch and let the WDL fail/pass on the execution platform.

The reason Dockstore is parsing the descriptors is in order to determine which inputs should actually be provisioned, e.g., if the WDL is expecting inputs A and B, but the input JSON for some reason specifies A, B, and C, only A and B will get provisioned.

See [this code](https://github.com/ga4gh/dockstore/blob/be1f537a79769f9a6e9599e7789bb2ce570a9497/dockstore-client/src/main/java/io/github/collaboratory/wdl/WDLClient.java#L120).

```
dockstore workflow launch --entry github.com/DataBiosphere/topmed-workflows/checker_UM_variant_caller_wdl:1.32.0 --json ~/Downloads/topmed_freeze3_calling_checker.json
```

I don't know if this is an issue for other languages as well -- implementor of this should check when addressing this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-661)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-661

**Comment by wshands** [comment]
There doesn't seem to be an easy way around updating the WDL parser. The parser finds variable inputs of type File in the WDL so that those variables can be distinguished in the input JSON and then those files can be provisioned. There is nothing in the input JSON file that says whether the input is a file path or not; e.g. some are Docker paths and not file paths.

**Comment by denis-yuen** [comment]
Is this relevant anymore after WDL 1.0 updates?

**Comment by coverbeck** [comment]
I think we can close this. When I wrote the ticket I didn't understand how the code worked, and that it needs to be able to parse the workflow.
