### ISSUE TITLE
File Not Showing

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2354]
### Expected behaviour
File to appear

### Actual behaviour
1. Go to https://staging.dockstore.org/workflows/github.com/Barski-lab/ga4gh_challenge:v0.0.3?tab=files
2. Click test parameter files
3. Change to a different version from the recent versions menu (master)
4. Click descriptor files again
The file does not appear

### Steps to reproduce the behaviour 
See above

DockstoreAPI - 1.6.0-rc.4
DockstoreUI - 2.3.0-rc.4

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-664)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-664

**Comment by garyluu** [comment]
Quick fix is to lazy load the dockerfile tab (of tools) and the descriptor tab (of workflows)

**Comment by denis-yuen** [comment]
Seems still broken on staging.dockstore.org

**Comment by denis-yuen** [comment]
Completed on staging.dockstore.org with 2.4.0-beta.5
