### ISSUE TITLE
The /toolclasses endpoints should not have UnitOfWork annotation

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2375]
## Feature Request 

The v1 and v2 endpoints do not do database access, but have the UnitOfWork annotations.

V1 annotation is [here](https://github.com/ga4gh/dockstore/blob/96a36302904a759973f928135fdc1d3a3f6774fb/dockstore-webservice/src/main/java/io/swagger/api/ToolClassesApiV1.java#L42).

V2 is in generated file, ToolClassesApi.java:

```
 @GET
    @UnitOfWork
    
    
    @Produces({ "application/json", "text/plain" })
    @io.swagger.annotations.ApiOperation(value = "List all tool types", notes = "This endpoint returns all tool-classes available ", response = ToolClass.class, responseContainer = "List", tags={ "GA4GH", })
    @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "A list of potential tool classes.", response = ToolClass.class, responseContainer = "List") })
    public Response toolClassesGet(@Context SecurityContext securityContext, @Context ContainerRequestContext containerContext, @ApiParam(hidden = true) @Auth Optional<User> user)
    throws NotFoundException {
        return delegate.toolClassesGet(securityContext, containerContext, user);
    }
```

This second one was mentioned in a [PR comment](https://github.com/ga4gh/dockstore/pull/2345#pullrequestreview-222939916) -- would be worth verifying there are no other generated endpoints that don't need this.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-672)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-672
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
This one might be trickier than it is worth currently. At generation-time it doesn't look like swagger has any current way to determine which endpoints have database access (or for us to tell it).

**Comment by denis-yuen** [comment]
Probably too difficult to be worth it
