### ISSUE TITLE
Collections without a description should just not show description

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2379]
## Feature Request 

When viewing a public collection, I think it would look better to simply not display anything if there is no description, rather than displaying the message "This collection does not have a description".

If viewing as an admin/maintainer, I can see how it might be useful, so that you'll know to add it, but for the public facing view, it doesn't seem like it should be there.

Same for organization.

1. Go to [HCA collection](https://dockstore.org/organizations/HCA/collections/skylab)

![Screen Shot 2019-04-11 at 9 52 55 AM](https://user-images.githubusercontent.com/1049340/55976417-fc2d4b80-5c40-11e9-94da-882c911fd6bd.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-674)
┆Issue Type: Story
┆Issue Number: DOCK-674

**Comment by denis-yuen** [comment]
I view it as a bit of a nudge to "add a description already."

**Comment by garyluu** [comment]
Maybe only show it when the user has the ability to edit that collection?

**Comment by coverbeck** [comment]
> Maybe only show it when the user has the ability to edit that collection?

Yes, that's what I was thinking. I have no rights to modify the HCA collection in this example, so it doesn't really help me to read that there is no description. It just makes the page not look as nice, IMHO.

**Comment by denis-yuen** [comment]
I mean, that's kind of the intent. 

Like the report card specification. People like achievements because other people can see them. Similarly, discouraging default avatars on Twitter
```
The change from the colorful eggs to the blander silhouette is an intentional one by Twitter, which noted that the new image is specifically meant to be less interesting and feel more like a placeholder, in an effort to encourage users to customize their profiles to a more unique image. 
```
