### ISSUE TITLE
Handle Removed Verified Test Parameter Files

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2384]
### Expected behaviour
When a test parameter file that was previously verified is removed, the version should no longer be verified

### Actual behaviour
https://dockstore.org/workflows/github.com/Barski-lab/ga4gh_challenge:master?tab=versions
Shows the master version is still verified.  Clicking the "View" button shows the table with no data.

Quick partial fix is to hide table when no data.

### Steps to reproduce the behaviour 
See above

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-677)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-677

**Comment by denis-yuen** [comment]
question: when we we remove a verified test parameter file, should it be verified at all? Should this be a web service fix?

**Comment by denis-yuen** [comment]
Alternatively, should users be allowed to remove the last test parameter file for a verified workflow?

**Comment by denis-yuen** [comment]
Long term: verified workflows should be immutable for the verified versions of it?
Short term: open to ideas

**Comment by denis-yuen** [comment]
Short term: if v0.0.3  works, remove verification from master. 
Otherwise, maybe we can find json somewhere

**Comment by garyluu** [comment]
My suggestion:

1. A test parameter file is verified if somebody (tooltester or others) successful runs it alongside the descriptor at the time (weird if mutable?).  This is saved in the DB in the source file table.  If the source file is removed, so should the verification information.  This would cascade all the way to the entry.

2. A version is verified if any source files of that version are verified.  This is computed on the fly so we don't have to keep it in sync in the DB.  If the version is removed, presumably the source files are removed which should remove the source file verification information and should cascade up to the entry.

3. An entry is verified if any version of it is verified. This is computed on the fly so we don't have to keep it in sync in the DB.

**Comment by garyluu** [comment]
The original issue seems to have been fixed though.  There's no empty table anymore.

**Comment by denis-yuen** [comment]
For the suggestion, can you break down what the current situation is, what would be realistic options be for 1.7.0, and what did you have in mind for 1.8.0?

**Comment by garyluu** [comment]
Currently:
1. the extended GA4GH endpoint is where we verify/unverify a single test parameter file
2. the workflowVersion's verification status is updated only when that endpoint is used. Anything outside of this endpoint does not change the workflowVersion's verification status.  Which means deleting the file, modifying the file, etc will not change workflowVersion verification status.  
3. The entry's verification status does not exist in the webservice.  The entry's verification is calculated on the fly in the frontend.  

For 1.7.0, of the 3 points listed, only the 2nd point needs to be done.  Just need to calculate workflow version verification on the fly from the webservice (the UI would need to get the source files which may be too many requests in the /workflow page).

For 1.8.0.  I think we should:
1. Verify the source files in pairs (1 test parameter, 1 descriptor).  Probably need a new data structure
2. Modify the workflow version verification calculation to that change

**Comment by garyluu** [comment]
To fix the verification for that one workflow version:

curl -X POST "http://10.11.8.92:8080/workflows/2327/verify/8893" -H "accept: application/json" -H "Authorization: Bearer thing"

**Comment by denis-yuen** [comment]
@garyluu  Confirm, its a POST request with no body?

**Comment by garyluu** [comment]
Yes

**Comment by garyluu** [comment]
If I recall correctly, the verification status wasn't updated until the refresh (after removing the test parameter file).  It should be removed when the test parameter file is removed.

**Comment by garyluu** [comment]
New issue created
