### ISSUE TITLE
Expose dockstore.model.ts info in webservice API

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2385]
## Feature Request 

As a first step for the implementation of #2247, expose all the info in dockstore.model.ts in a web service API.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-678)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-678
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
Running for quite some time in staging.dockstore.org, considered verified
