### ISSUE TITLE
UI should consume new webservice config API

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2386]
## Feature Request 

UI should consume API that will be introduced in #2385. Doing so will entail the following changes:

* Change Dockstore Ajax calls to be relative to the domain, not absolute.
* Call the new API and store results, most likely in a new Akita store
* Change UI code to get data from new store instead of dockstore.model.ts
* Make local development of UI work, given the relative to the domain API calls, probably using Angular proxy
* Update compose_setup to no longer modify dockstore.model.ts and instead update webservice config file.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-679)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-679
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
Running for quite some time in staging.dockstore.org, considered verified
