### ISSUE TITLE
UI Fixes for Starring/Organizations

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2392]
During the demo for starring orgs, a few UI things were pointed out to fix. Creating this as a separate ticket for more incremental PR's

The Starred page has redundant titles
On the starred page, the info that's grabbed for organizations should be checked to see if it exists before displaying something like "email:   "
Organization Stargazers should be visually consistent with the tool/workflow stargazers.
The stargazers window can become quite large. Rethink/resize how users are displayed?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-683)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-683
┆Epic: Serve UI from s3/CloudFront

**Comment by david4096** [comment]
Can confirm that the organizations without emails don't show empty placeholders for Starred Organizations and that the stargazers for Tools and Orgs appear consistent.

1.7.0-beta.2
UI - 2.4.0-beta.2

staging.dockstore.org
