### ISSUE TITLE
Starring endpoints for organizations should be more RESTful

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2395]
## Feature Request 
The endpoints
`/{organizationId}/star`, `/{organizationId}/unstar`
`/{workflowId}/star`, `/{workflowId}/unstar`
`/{containerId}/star`, `/{containerId}/unstar`
are not really following RESTful practices. Star/unstar appear to be verbs and the StarRequest request is not actually being used.
Maybe the unstar endpoints should be removed and the StarRequest body should determine what the /star endpoint should do.

Sidenote to change to ApiParam value on `/{workflowId}/star`lo to `workflow to star` from `tool to star`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-684)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-684

**Comment by david4096** [comment]
This is handled by the CLI here https://github.com/dockstore/dockstore-cli/blob/6da3d535c54b92191d4f563f8ae5f3aa87530d43/dockstore-client/src/main/java/io/dockstore/client/cli/nested/ToolClient.java#L364

Another ticket was made to remove unstar endpoints https://github.com/dockstore/dockstore/issues/3657
