### ISSUE TITLE
Replace ngx-md with ngx-markdown

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2396]
### Desired behaviour
Explore the idea of replacing ngx-md with ngx-markdown (it's more popular, uses a newer version of marked, updated more frequently)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-688)
┆Issue Type: Story
┆Issue Number: DOCK-688

**Comment by agduncan94** [comment]
I think this can be closed.
