### ISSUE TITLE
Is workflow-service spamming us?

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2404]
### Desired behaviour

Investigate https://github.com/common-workflow-language/workflow-service and see if it is flooding us with requests of the form `/api/ga4gh/v1/tools/%2Fopt%2Fplatform%2Fworkflow%2Fworkflow-service%2Fworkflows%2Fchenchao%2Ff163c7b0500f49119001d2a676ae9070.cwl/versions/latest/plain-CWL/descriptor` (probably looking for something in their /opt directory locally).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-691)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-691

**Comment by denis-yuen** [comment]
Let's get a few examples and numbers of requests. 
In particular, Illumina would like 

Date/Time,
URL,
User-Agent and other identifying information captured by your logs
Remote IP-Address.

**Comment by melainalegaspi** [comment]
Will investigate if issue comes up again
