### ISSUE TITLE
Upgrade Cypress to 3.2.0

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2411]
Maybe it's only on Mac, but Cypress doesn't work with Chrome anymore. We have to switch to Electron to use, but it offers less functionality. But when I update to 3.2.0, seems to work with Chrome again.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-693)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-693
┆Epic: Dockstore 1.7 dependency updates

**Comment by garyluu** [comment]
It already is 3.2.0
