### ISSUE TITLE
Versions are ordered alphabetically while being numeric

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2415]
### Desired behaviour

When multiple versions of a workflow are available, the most recent or highest number should be at the top.

### Actual behaviour

Currently versions, while numeric when automatically generated, are sorted alphabetically so end up counting: "1, 10, 11, 12... 2, 21" and so on.

### Steps to reproduce the behaviour 

Create more than 9 versions of a workflow and click the versions pulldown.

![Screenshot_2019-04-19_15-05-19](https://user-images.githubusercontent.com/3795586/56446038-3045e380-62b5-11e9-9d51-bd3edc4086d5.png)

### Environment (Browser or OS and Dockstore version)

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website) 

Firefox 66.0.3 (64-bit)
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-695)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 23 Xebec
┆Issue Number: DOCK-695

**Comment by denis-yuen** [comment]
Can't find the commit, but this sounds like a regression

**Comment by denis-yuen** [comment]
This might be hard, versions might be semantically versioned. Or they might be garbage.

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Can consider sorting by date if dates are reliable

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Sorting should be webservice, but may be occurring in the UI

**Comment by agduncan94** [comment]
The UI isn't doing any sorting in this case, it is based off of the webservice. Will update the webservice to sort the versions ahead of time.

**Comment by agduncan94** [comment]
Perhaps sorting by date would be the better approach.

**Comment by david4096** [comment]
Taking a quick look at this it seems like since refresh updates all the versions the last modified might not work to sort these as expected? For this test I created tag z1 after a1 and expected it to appear higher in the list. It seems like they may be resorting to alpha-ordering still.

![image](https://user-images.githubusercontent.com/3795586/70960683-85005080-2034-11ea-87dd-e8749087906a.png)

![image](https://user-images.githubusercontent.com/3795586/70960707-977a8a00-2034-11ea-97d5-ae00cb92b4e3.png)

**Comment by agduncan94** [comment]
@david4096 For hosted workflows this should be fine, since you cannot refresh. For non-hosted workflows, it should behave similarly to before. Since refresh sets them all to the same last updated, then the name will be used to sort (which is what is used previously).

Not that this is the ideal case. It should probably grab the last updated time from GitHub to know the order to display.

**Comment by david4096** [comment]
In that case I can confirm this is the expected behavior and will make an issue for getting the updated times from github!

https://github.com/dockstore/dockstore/issues/3132
