### ISSUE TITLE
Create Slack notification for organization requests

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2417]
### Desired behaviour

Using either logging.dockstore.org (or AWS CloudWatch for that matter), create a Slack alert for new requests for organizations

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-696)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 20 Umiak
┆Issue Number: DOCK-696
┆Epic: Organization Improvements

**Comment by denis-yuen** [comment]
Tested and working

**Comment by NatalieEO** [comment]
Not sure if this is working. I just approved an org request that was sitting there for 3 days.

**Comment by denis-yuen** [comment]
I've seen false positive alerts too, so its definitely buggy

**Comment by denis-yuen** [comment]
Still bugged

**Comment by agduncan94** [comment]
Seems to be creating a notification in the dockstore-testing slack channel. Is this what is expected @denis-yuen ?

**Comment by garyluu** [comment]
Assuming staging is working correctly. There is a possibility I made the fix for staging but not for production.

**Comment by denis-yuen** [comment]
It's tricky. I mean I would expect a request made to staging to go to #dockstore-testing
A request to prod should go to alerts. 

What was the fix?

**Comment by garyluu** [comment]
I think I changed a character or something like that. Dang, I should've written it down

**Comment by agduncan94** [comment]
Looks like the prod one goes to dockstore-testing channel as well.

**Comment by agduncan94** [comment]
Need to figure out how to move this to dockstore-alerts channel.

**Comment by garyluu** [comment]
So it looks like the fix is in for both staging and production.  It was literally adding an extra space after "POST /api/organizations" so "POST /api/organizations "

**Comment by agduncan94** [comment]
@denis-yuen do you know how to switch the slack channel?

**Comment by agduncan94** [comment]
I have changed the slack channel for prod to be the alerts channel.
