### ISSUE TITLE
Test migration to new discourse system

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2422]
Requires https://github.com/ga4gh/dockstore/pull/2420.

This must be done during 1.7.0 release time. It includes the following steps:
* Delete all existing topics with no comments
* Manually connect topics with comments to the database (do not simply delete and copy comments)
* Write script to auto populate remaining empty topic IDs for published entries
* Disable RSS topic generation

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-698)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-698

**Comment by agduncan94** [comment]
Also should use cloud watch to monitor for any errors caused by the discourse integration with publish.

**Comment by denis-yuen** [comment]
Remaining tasks:
* test can use script to create topics for those that need them
* a few topics can be updated by SQL

Reviewer: go through discourse see whether entries make sense. Add a new workflow, tool, service and see whether a new topic exists

**Comment by agduncan94** [comment]
The test script has been created and tested on staging.
