### ISSUE TITLE
Location overflows on organization page

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2432]
The location of an organization appears to overflow the frame on the organizations page.

![Screenshot_2019-04-24_14-10-45](https://user-images.githubusercontent.com/3795586/56694147-ee44e500-669a-11e9-9b3c-d6f89d8439db.png)

It expect it to overflow to a new line if the text exceeds the max line length, or be hidden when it flows outside the inner div.

Firefox 66.0.3 (64-bit) Xubuntu 18.04

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-702)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-702
┆Epic: Organization Improvements

**Comment by agduncan94** [comment]
Any opinions on not having these in columns but instead as rows?
![smaller-screen-orgs](https://user-images.githubusercontent.com/6331159/72100995-b72e6680-32f1-11ea-805a-9368f396677e.png)

**Comment by NatalieEO** [comment]
Location does not overflow now the info is in columns
API - 1.8.0-beta.8 
UI - 2.5.0-beta.2
