### ISSUE TITLE
Update compose_setup for UI config changes

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2433]
## Feature Request 

With upcoming changes where UI will get its config information from web service (#2385 and #2386), update compose_setup to:

* No longer have a dockstore.model.ts.template
* Update web.yml.template with new uiconfig section, with appropriate parameterized values

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-701)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-701
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
This is now the case for staging.dockstore.org
