### ISSUE TITLE
Call to /config.json should be cached

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2443]
## Feature Request 

After #2386 is merged, we should cache the results of the call to get /config.json with in the sevice worker that was updated in dockstore/dockstore-ui2#633

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-707)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-707
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
Can live with this later

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

This was going to depend on the service worker that Ryan was working on, which we have so far decided not to use due to Cypress integration issues, so rejecting for now.

**Comment by garyluu** [comment]
> ➤ Charles Overbeck commented:
> 
> This was going to depend on the service worker that Ryan was working on, which we have so far decided not to use due to Cypress integration issues, so rejecting for now.

:cry:
