### ISSUE TITLE
CI to Build UI and upload to s3

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2446]
We need a CI job that builds the UI in prod mode and uploads the build to an s3 bucket. Or maybe buckets, see next section.

At least two versions of the generated index.html need uploaded; one for staging and one for production -- they have different Google Tag Manager ids.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-710)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-710
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
![Screenshot from 2019-07-31 13-13-53](https://user-images.githubusercontent.com/1730679/62232826-2001d200-b395-11e9-9b47-18418cee0e12.png)

Note the UI version, but this is on cloud.dockstore.org which should be deploying versions from develop. The version should probably be a short SHA1 or similar when deploying non-tags

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

When verifying that UI builds are on the S3 bucket; I see 2.4.0-alpha.6-1bfe812, 2.4.0-alpha.7-64cde99, 2.4.0-alpha.8-1119565, develop and other builds there.
