### ISSUE TITLE
Implement Serving UI from s3 on staging

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2447]
After other tickets are implemented to upload UI builds to s3, actually serve UI from s3, probably via CloudFront.

May need to terminate certificate here.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-709)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-709
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
> May need to terminate certificate here.

Probably, yes

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Closing as duplicate of DOCK-862
