### ISSUE TITLE
Remove UI from compose_setup

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2448]
Once UI is being served from s3, remove all references to UI from compose_setup. We should no longer build the UI, nginx shouldn't serve it, etc.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-711)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-711
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
Pending more testing of cloudfront in staging.dockstore.org as opposed to cloud.dockstore.org in our month of testing

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Keep UI in container for now, as a backup, but pull it from s3 instead of building it on the fly.

**Comment by denis-yuen** [comment]
Working on in https://github.com/dockstore/compose_setup/pull/98
