### ISSUE TITLE
Services UI

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2450]
Implement UI for Services. This will probably be broken down as the definition becomes clearer.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-713)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-713
┆Epic: Dockstore  My Services

**Comment by denis-yuen** [comment]
This should be broken out, but we need
1) https://dockstore.org/sitemap (services added here)
2) https://dockstore.org/services (for debugging, should re-use as much code as possible)
3) https://dockstore.org/search?_type=services&searchMode=files

**Comment by garyluu** [comment]
So...for the sitemap, there is the somewhat hidden/deprecated `/tools` page that `tools` links to.  For services, should it just link to https://dockstore.org/search?_type=services&searchMode=files ?

**Comment by denis-yuen** [comment]
I like the hidden page (using the old table) for debugging things actually (like if elastic search had an issue). Let's get that working for services

**Comment by denis-yuen** [comment]
1) Done
2) Done
3) Punted

**Comment by denis-yuen** [comment]
#2576 follows
