### ISSUE TITLE
Phase out Firecloud button

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2456]
By our next release, Firecloud will be no more.  We will need to phase out that button.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-714)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 11 Kayak
┆Issue Number: DOCK-714
┆Epic: Launch-with Support

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

We have until August 2019.

**Comment by denis-yuen** [comment]
Phased out on staging.dockstore.org
