### ISSUE TITLE
Organizations members should be visible

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2458]
### Expected behaviour
Organization members should be visible to the public (similar to github). Or at least if we want to keep membership views limited to logged in users, then the organization's events tab should similarly hide member related updates when a user is not logged in.

### Actual behaviour
Organization members are only visible if the user is logged in, but events tab still shows member's activity regarding organization. 

### Steps to reproduce the behaviour 
While logged out navigate to an organization's page and select the member's tab. No members show up if user is not logged in.

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0
DockstoreUI - 2.3.0
Chrome 73

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-716)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-716
┆Epic: Organization Improvements

**Comment by garyluu** [comment]
At least part of the reason is due to null check (might actually be solved with https://github.com/dockstore/dockstore/issues/1793)

**Comment by denis-yuen** [comment]
@agduncan94 any idea why this auto-closed?

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

[~accountid:5c118bd3e91d16692a3a3ae8] I moved it to done since it has been merged.
