### ISSUE TITLE
Prod Optimization Issue with pipeline-builder

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2461]
### Expected behaviour
ng build --prod and then serving the dist through angular-http-server or similar and then going to a public workflow page should work

### Actual behaviour
Nothing appears to happen when trying to click on a link to a workflow page (from the home page)

### Steps to reproduce the behaviour 
```
ng build --prod
npm i angular-http-server --no-save
bash -i -c 'npx angular-http-server --path ./dist -p 4200'
```
- have a running webservice with some workflows in it
- go to localhost:4200
- click on 'Browse Workflows' tab
- click on any workflow

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)
Any UI2 with 0.3.10-dev.308

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-717)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Issue Number: DOCK-717

**Comment by coverbeck** [comment]
What does optimization do? Tree shaking? Is it possible that some pipeline-builder files are getting shaken out?

**Comment by garyluu** [comment]
I think it changes the javascript too.

**Comment by coverbeck** [comment]
@garyluu Is this still relevant? I don't think we're using angular-http-server any more.

**Comment by garyluu** [comment]
Nothing special about angular-http-server.  It causes an issue for anything that serves the prod bundle

**Comment by garyluu** [comment]
Oh, and in the weird event that there isn't a prod issue.  Update to the latest pipeline-builder because of ...reasons

**Comment by garyluu** [comment]
Doesn't appear to be an issue, but lodash in the pipeline-builder should be updated for...reasons.

**Comment by melainalegaspi** [comment]
@garyluu create new issue for lodash if still relevant
