### ISSUE TITLE
Add Google Analytics to the dockstore docs

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2463]
Read the docs has built in support, so should be straightforward.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-719)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-719

**Comment by denis-yuen** [comment]
Might already be done, please confirm

**Comment by denis-yuen** [comment]
Functional, but need to remember to turn off "do not track" when testing
