### ISSUE TITLE
Discourse url setting duplicated in dockstore.yml

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2464]
## Bug Report

I added the discourseUrl for the UI config and Andrew added it for other discourse work, so now the setting is duplicated in the dockstore.yml.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-718)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-718

**Comment by denis-yuen** [comment]
Verified not present in develop
