### ISSUE TITLE
Add the following text to the grant page

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2465]
“This work was funded by the Government of Canada through Genome Canada and the Ontario Genomics Institute (OGI-168)”

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-720)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6.x
┆Sprint: Seabright Sprint 10 Jet Ski
┆Issue Number: DOCK-720

**Comment by denis-yuen** [comment]
Complete on staging.dockstore.org
