### ISSUE TITLE
Implement WOMtool to parse WDL 1.0 files

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2474]
After the investigation from https://github.com/dockstore/dockstore/issues/2171, it looks like WOMtool makes the most sense for our use case. We should try implementing it. The artifact is available at https://broadinstitute.jfrog.io/broadinstitute/libs-release/org/broadinstitute/womtool_2.12/.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-725)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-725

**Comment by denis-yuen** [comment]
Some more motivation
