### ISSUE TITLE
CircleCI PR merge test

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2475]
### Desired behaviour
CircleCI does not merge target branch before running tests.  I would be nice if it behaves like Travis which has two builds (one for the branch alone, one for the branch merged with the target branch)

https://circleci.com/ideas/?idea=CCI-I-926

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-726)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Sprint 20 Umiak
┆Issue Number: DOCK-726

**Comment by denis-yuen** [comment]
@agduncan94  Alternatively, we need to ensure that a merge from develop is one of the last commits to the branch?

**Comment by denis-yuen** [comment]
Can workaround for now

**Comment by garyluu** [comment]
Made a PR to develop, SSH'd into running job.  Not a single environment variable mentions "develop" :cry:
