### ISSUE TITLE
Improve lighthouse audit score

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2482]
### Desired behaviour
Some simple steps identified via https://developers.google.com/web/tools/lighthouse/
Let's try to reach a score of at least 50 performance by using some of their suggestions like re-compressing/shrinking/lazy loading certain images, etc,

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-732)
┆Issue Type: Epic
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-732

**Comment by coverbeck** [comment]
@emlys Let's talk about this one; avoid PWA, and you may need to create new tickets.

**Comment by denis-yuen** [comment]
@denis-yuen create stories under this
