### ISSUE TITLE
Remove legacy registry provider code

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2488]
Change the JSON property back to `registry_provider`. We should guarantee there are no clients still running the 1.3.6 version. Remove related dead code.

https://github.com/dockstore/dockstore/blob/db7890a5b46234612fbf6c8ff40e06a7c1f3e397/dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tool.java#L321

https://github.com/dockstore/dockstore/blob/5fb31336b608713655ce725fcf08a4db23153ad3/dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tool.java#L342

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-736)
┆Issue Number: DOCK-736
┆Sprint: Sprint 57- Frilled shark
┆Issue Type: Story

**Comment by garyluu** [comment]
To me, it seems like changing it back to registry_provider right now would break 1.7.0

**Comment by garyluu** [comment]
Current behaviour summary (mostly for myself):

Registry is stored as a string in the DB (ex. "quay.io")
It's returned as:
- enum (ex. QUAY_IO) from the "registry" property
- string (ex. quay.io) from the "registry_string" property

**Comment by coverbeck** [comment]
Confirmed that `DockstoreTool` appears in the OpenAPI -- verifies what the PR does, not the ticket description.

[Webservice](https://github.com/dockstore/dockstore/commits/580a271) - 580a271

[UI](https://github.com/dockstore/dockstore-ui2/commits/d167ef76) - 2.7.3-72-gd167ef76

[Compose Setup](https://github.com/dockstore/compose_setup/commits/36c8ddc) - 36c8ddc

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/da5d5ab) - 1.10-56-gda5d5ab
