### ISSUE TITLE
Investigate GitHub App deployments

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2489]
GitHub has the concept of deployments/environments which you can connect to versions/tags (see dockstore/dockstore environments tab). There would be a button beside each release that will take you to the corresponding version on Dockstore.

https://github.com/dockstore/dockstore/deployments

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-737)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-737

**Comment by melainalegaspi** [comment]
Will reopen if needed in future
