### ISSUE TITLE
Obfuscate user information

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2490]
Currently we collect profile information about users when they create an account like email and name. The email is used to verify the identity of the log in attempt when we receive the authentication callback. The name is used to display personal information on the profile page.

If, instead, we performed a one-way hash on the email and stored that during account creation or linking, Dockstore would continue functioning as expected for the Dockstore User but the Database would no longer contain their personal information.

Once this is in place we can either run a migration to create the expected fingerprint for each User, or it could be overwritten during their next login, and their email removed.

The full name is used on the profile, however, to avoid storing these data the dockstore-ui could store the profile information in its session data as gathered from the auth provider. Then using an session store present the name where it currently shows.

1) Implement an email-free auth checking flow by adding a new `identityToken` member variable and a `identityTokenSource` field so that we know which field of he auth callback has been hashed. Add a salt that is provided by the environment so we could export the production database with some guarantees that you couldn't use it to identify a Dockstore User, even if you separately had their email.

1) Remove the name member variable from Users. Implement UI based display customizations over requesting from the webservice.

1) Implement migrations or code that (all at once or eventually) remove existing emails and names from the DB.

This raises the possibility of removing the responsibility of holding some user data, especially since user's and workflow authors are separable. If we have to change the salt for some reason, Users may be required to relink their accounts.

This raises the possibility of obfuscating the tokens as well, but requires more thought. I believe it is possible to encrypt their github or google token without much effort following this. If we encrypt the tokens we keep using a key based on a user's generated ID token and the salt again, we should be able to provide some guarantees that even with those tables dumped an attacker couldn't assume their identities. When the webservice needs to use the token on their behalf, it regenerates the passphrase from the User's info and the salt (from the environment) and decrypts it, only ever storing the whole token in memory.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-738)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-738
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
For Google tokens, I think, although it needs to be tested, that we could just use [the user id](https://developers.google.com/resources/api-libraries/documentation/oauth2/v2/java/latest/com/google/api/services/oauth2/model/Userinfoplus.html#getId--). Then we wouldn't even have to hash the email; we could just use the id directly.

**Comment by denis-yuen** [comment]
Is that an improvement? It seems to me that the user id uniquely identifies a user as much as an email address would anyway (depending on what they mean by obfuscate and if that makes user ids non unique)

**Comment by coverbeck** [comment]
I don't think you can do anything with the id -- i.e.,  there's no API where I can look up a Google user by id, AFAIK. Whereas if I got an email, I could at least email the person. But we would need to confirm this, otherwise it really wouldn't be an improvement.

**Comment by david4096** [comment]
I believe this is a privacy requirement we don't have to meet. Closing
