### ISSUE TITLE
Implement aliases for tools and workflows

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2495]
There is documentation for linking to Organizations and Collections using aliases [https://docs.dockstore.org/docs/publisher-tutorials/guid-alias/\#organizations-and-collections](https://docs.dockstore.org/docs/publisher-tutorials/guid-alias/#organizations-and-collections) but not for Tools and Workflows [https://docs.dockstore.org/docs/publisher-tutorials/guid-alias/\#tools-and-workflows](https://docs.dockstore.org/docs/publisher-tutorials/guid-alias/#tools-and-workflows).

The implementation for aliases links has only been done for Organizations and Collections. I needs to be done for tools and workflows so that when we create DOIs for a tool or workflow we can provide an immutable link back to the tool or workflow. Right now an alias to a tool or workflow can be created using /entries/\{id\}/aliases; but there is no link that can be used such as for [https://dockstore.org/aliases/organizations/MyOrganization](https://dockstore.org/aliases/organizations/MyOrganization) for an organization alias ‘MyOrganization’

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-740)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-740
┆Epic: Create DOIs

**Comment by agduncan94** [comment]
I have added this feature, however the docs have not been updated yet.

**Comment by agduncan94** [comment]
Closing this, since I created an issue to update docs.
https://github.com/dockstore/dockstore/issues/2551
