### ISSUE TITLE
Bring up TOS on the Registration Flow

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2499]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-742)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 14 Nordland
┆Issue Number: DOCK-742
┆Epic: Terms of Service

**Comment by denis-yuen** [comment]
Passive message is definitely there. 
Columns 
```
privacypolicyversion               | PRIVACY_POLICY_VERSION_2_5
tosversion                         | TOS_VERSION_1
privacypolicyversionacceptancedate | 2019-07-30 17:20:14.914
tosversionacceptancedate           | 2019-07-30 17:20:14.914
```
being populated
