### ISSUE TITLE
Replace ga4gh github URLs with dockstore

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2516]
There are a number of places in comments and scripts where the old github.com/ga4gh/dockstore URL is present.

To close this, replace with the new URL.

https://github.com/dockstore/dockstore/blob/5fb31336b608713655ce725fcf08a4db23153ad3/dockstore-integration-testing/src/test/resources/testArrayHttpInputLocalOutput.json#L4

https://github.com/dockstore/dockstore/blob/b96bec5d7dc575261cc4dd56d03bca8c5ae016de/dockstore-webservice/src/main/templates/io/dockstore/webservice/resources/Description.java#L50

https://github.com/dockstore/dockstore/blob/5fb31336b608713655ce725fcf08a4db23153ad3/.github/CONTRIBUTING.md#L5

=== code ===

https://github.com/dockstore/dockstore/blob/8f4a0cf40214021fbc063e252dde36257b0bcc67/dockstore-client/bin/dockstore#L173

@Ldcabansay uncovered this while debugging the CLI.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-746)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6.x
┆Issue Number: DOCK-746

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

https://github.com/dockstore/dockstore/commit/3f896c8a6db8211aa48a90aa986d558ef898c161 ( https://github.com/dockstore/dockstore/commit/3f896c8a6db8211aa48a90aa986d558ef898c161|smart-link )

**Comment by garyluu** [comment]
Can't find "ga4gh/d" in webservice anymore
