### ISSUE TITLE
Linking does not work in develop branch

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2517]
## Bug Report

Linking to an external account is broken on develop branch.

This was introduced by the implementation for #2386 -- in links.model.ts, the properties are compiled with the values of dockstore.model.ts before it has been updated by calling `/metadata/config.json`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-747)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-747

**Comment by denis-yuen** [comment]
quay, github seem to link properly on staging.dockstore.org
