### ISSUE TITLE
When registration fails, there is no clear error message

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2519]
## Bug Report

If there is an error registering, there is no clear error message; the toaster pops up on the bottom, but there is no (visible) text.

This is basically the same as #2291, which fixed it for login errors, but not registration.

1. Register, if not already registered, with Github
2. Login
3. Logout
4. Try to register again, which will legitimately cause an error -- it's not clear what's going on.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-748)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-748

**Comment by denis-yuen** [comment]
Seems to work
