### ISSUE TITLE
Make it easier to run ui integration tests locally

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2522]
Had to setup a number of different things in order to get cypress tests to run
Can be frustrating and hopefully can be simplified

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-751)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-751
┆Epic: Dockstore Dev Operations

**Comment by melainalegaspi** [comment]
largely mitigated with CircleCI
