### ISSUE TITLE
Implement Recommendations for Dates/Timestamps

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2524]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-753)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-753
┆Epic: Dates

**Comment by NatalieEO** [comment]
replaced by #2598 #2597 #2570
