### ISSUE TITLE
Get Dockstore WebService Running Locally

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2526]
For Natalie

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-754)
┆Issue Type: Story
┆Sprint: Lighthouse Sprint47 University
┆Issue Number: DOCK-754

**Comment by cricketsloan** [comment]
[~lcabansa] Can you provide links for Emily here?

**Comment by denis-yuen** [comment]
Not enough info, but this one should be in SEAB and not GitHub

**Comment by denis-yuen** [comment]
@melainalegaspi 
this one should be SEAB only (not on GitHub)
