### ISSUE TITLE
Back button weird when navigating back from entry to a collection

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2537]
If you are on a collection page and click on an entry, then once on the entry click the back button, it will take you to the dockstore homepage. Clicking the back button again will take you back to the collection.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-760)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-760

**Comment by denis-yuen** [comment]
Still present 2.4.0-beta.5

**Comment by denis-yuen** [comment]
Seems fixed on staging 
```
API - 1.7.0-rc.0
UI - 2.4.0-rc.0
```
