### ISSUE TITLE
Add documentation to webservice for Entry dates/timestamps

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2549]
related to dockstore/dockstore#514 and dockstore/dockstore#2524

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-771)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-771

**Comment by david4096** [comment]
Can confirm https://github.com/dockstore/dockstore/pull/2533 improves the webservice docs.
