### ISSUE TITLE
Organisation starring is not showing properly

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2550]
When you view stargazers for and org, you should see them on a separate page.

<img width="1440" alt="Screen Shot 2019-06-07 at 1 53 33 PM" src="https://user-images.githubusercontent.com/6331159/59123653-c13b5180-892b-11e9-8d32-7117680c42d6.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-777)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-777

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

May be fixed already?

**Comment by NatalieEO** [comment]
Already fixed on develop
![image](https://user-images.githubusercontent.com/16004905/59225287-2938a480-8b85-11e9-8c51-7be605a0e6a1.png)

**Comment by denis-yuen** [comment]
Working on staging.dockstore.org as expected
