### ISSUE TITLE
Feedback for services

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2554]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-773)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 14 Nordland
┆Issue Number: DOCK-773

**Comment by garyluu** [comment]
TODO: 

- [ ] For the redirect, will need to know what parameters mean aside from state
- [ ] Need to find out relationship with organizations where you might have membership, collaboration, etc.
- [ ] Possible weird routing issues with my-workflows and my-services
- [ ] Search TBD
- [ ] Need to workout integration with TRS, particularly #service and #workflow
- [ ] My-tools has fetching workflows alert sometimes.  my-workflows and my-services does not

**Comment by denis-yuen** [comment]
Well underway, replaced by #2544 and #2543
