### ISSUE TITLE
Implement TopMed variant caller freeze8 WDL

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2555]
Write WDL wrapper for TopMed variant caller freeze8 utilizing the WDL freeze3 wrapper

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-772)
┆Issue Type: Story
┆Sprint: Lighthouse Sprint47 University
┆Issue Number: DOCK-772
┆Epic: Epic 1.3.WP2: Workflows and App Onboarding

**Comment by denis-yuen** [comment]
@wshands @cricketsloan should this be a seab ticket?

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

WDL wrapper is here: https://github.com/DataBiosphere/topmed-workflows/blob/feature/freeze8-wdl/variant-caller/variant-caller-wdl/topmed_freeze8_caller.wdl ( https://github.com/DataBiosphere/topmed-workflows/blob/feature/freeze8-wdl/variant-caller/variant-caller-wdl/topmed_freeze8_caller.wdl|smart-link ) 

It needs optimization and more testing
