### ISSUE TITLE
Hosted entry version can be mutated

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2558]
## Bug Report

A hosted entry version can be mutated with the following set of steps:

### Steps to reproduce

Using UI:

1. Create a hosted workflow
2. Create a new version, which will be version 1
3. Delete the version
4. Create a new version -- it will also be version 1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-778)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 15 Outrigger
┆Issue Number: DOCK-778
┆Epic: Version Immutability

**Comment by denis-yuen** [comment]
Requirements: 
* should deal with scenario, create version 1, issue DOI for version 1, delete version 1, and then create a new version. The DOI should not point at the incorrrect version (note, it could be pointing at a deleted version, which is not great, but can follow-up later ... i.e. create new ticket, delete DOI? when deleting? Disallow deletion when DOI has been issued?
* implementation should be compatible with TRS

**Comment by denis-yuen** [comment]
@garyluu  please check on ui2 counterpart and assign reviewer aftewards

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified on staging that if I follow the steps from the description, a new version is created, instead of the previous version getting recreated.

API - 1.7.0-beta.5
UI - 2.4.0-beta.4
