### ISSUE TITLE
Cache NPM node_modules in CI

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2561]
Cache NPM node_modules to speed up installation.  Saves roughly 25 seconds in total

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-781)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-781
┆Epic: Speed up Builds

**Comment by agduncan94** [comment]
Might be of use https://docs.cypress.io/guides/guides/continuous-integration.html#Example-circle-yml-v2-config-file

**Comment by agduncan94** [comment]
Circle CI is restoring and saving the cache when necessary.
