### ISSUE TITLE
Handle variation for email, author and description in WDL metadata

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2564]
The WDL meta field can store key value pairs. Currently we look for email, author, and description as keys, but one could imagine using other words for the same meaning.

It doesn't seem like WDL has recommended keys for authorship, it just says to include authorship.

email -> emails, e-mail, email address
author -> authors, creator
description -> about, summary

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-783)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-783

**Comment by melainalegaspi** [comment]
Stick with current recommendations for now
