### ISSUE TITLE
Implement snapshots for remote entries

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2569]
Recommended approach, implement version freezing as a separate feature and leave the existing synchronization features largely in place.

Currently, remote entries can be mutated during a refresh. If a named branch has its commit tag changed (like when a release is modified), Dockstore will accept these changes. 

We would like to provide guarantees that a given version of a remote entry has not been modified.

To close this, make the following minimal additions to the webservice.

1. Extend the existing Tools and Workflow versions to include a new metadata field. This field will denote the `read-only` status of the version.
1. Add guards which disallow these `read-only` marked items from being overwritten during refresh (or delete).
1. Demonstrate that snapshotted remote tools and workflow versions can be registered and not overwritten using webservice tests.

This does not affect Hosted entries, which are already more or less immutable. This approach allows the existing endpoints to be mostly left intact (although some guarantees will have to be made that mutation is not possible at the `workflowVersions` endpoint).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-786)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 14 Nordland
┆Issue Number: DOCK-786

**Comment by denis-yuen** [comment]
Going to do a bit of this

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Working on mutable metadata….

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

Tested on staging and it seems to be working as expected.
