### ISSUE TITLE
Add minimal "Snapshot" UI affordances

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2571]
UI for https://github.com/dockstore/dockstore/issues/2569

To implement in the UI, consider the following approach:

1. The existing "versions" table has edit and delete actions by version, add a "snapshot" or "build" action button that will start the snapshot wizard.
1. Implement a dialog that allows the Dockstore User to choose to issue a DOI (and change the version being snapshotted).
1. Display snapshots with a lock icon in the versions table or pulldown to denote a snapshotted version.

![image](https://user-images.githubusercontent.com/3795586/59635334-d53e3a80-9105-11e9-86fc-f9788f3f5964.png)

There are other features that snapshotting clears the way for, like including packing dependencies and digitally signing workflows and images.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-787)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-787

**Comment by denis-yuen** [comment]
Link the PR

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore-ui2/pull/736 too

**Comment by denis-yuen** [comment]
snapshot UI is completed and present on staging.dockstore.org
Found new issue that warrants a new ticket https://github.com/dockstore/dockstore/issues/2762
