### ISSUE TITLE
GitHub App Variable

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2575]
### Desired behaviour
Github App (in the UI) should be made into a variable to differentiate between staging, production, development.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-793)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-793

**Comment by denis-yuen** [comment]
exists in https://github.com/dockstore/compose_setup/blob/develop/install_bootstrap
