### ISSUE TITLE
Search Services (UI)

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2577]
### Desired behaviour
After https://github.com/dockstore/dockstore/issues/2576  .  UI's search page should handle services

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-791)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-791
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Can wait
