### ISSUE TITLE
Investigate how to use GitHub App integrations locally

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2578]
Need to investigate some options for running local instances of Dockstore that support GitHub Apps.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-790)
┆Issue Type: Story
┆Fix Versions: Open-ended research tasks
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-790

**Comment by agduncan94** [comment]
Made some notes on the wiki article, but in summary I think we need to maintain the endpoints "sync" and "refresh one entry" that can be used locally in place of the github app integrations.

**Comment by denis-yuen** [comment]
looks like localstack now claims to handle lambda https://github.com/localstack/localstack#overview
with local and docker executors for lambda

could use to debug/simulate lambda locally 

also has SQS and API Gateway, don't know how fleshed out they are

**Comment by denis-yuen** [comment]
@agduncan94  is there anything to review here? 
I don't see a corresponding wiki entry and I don't see a specific commit on develop

**Comment by agduncan94** [comment]
No I don't think so.
