### ISSUE TITLE
UI  prebuild should clearly indicate the web service build

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2579]
## Feature Request 

The other day a developer hadn't built in a while, pulled the UI, did a `npm run prebuild`, and it failed. It turned out she had a `~/.npmrc` file (from running `npm config set dockstore-ui2:webservice_version`) which was pointing to a really old version of the webservice. It took us a while to figure out what was going on, although once we did it was  obvious.

Ideally `npm run prebuild` would display a message saying what webservice version it is building against.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-789)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-789
┆Epic: Retro tickets

**Comment by denis-yuen** [comment]
Present
