### ISSUE TITLE
UI should also show actual web service version

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2590]
## Feature Request 

From a discussion in dockstore/dockstore-ui2#685 -- the web service version that the UI displays in the web service version that the UI was built against, that it generated client libraries for.

This should ideally also always be the web service the UI is running against. But there might be cases where it isn't, even if it's only in dev environments.

I would be nice if the UI also displayed the version of the web service it is making requests against.

I don't know if there is an API that returns the web service version already, may need to update it. If so, `/metadata/config.json` might be a good place.

**Comment by garyluu** [comment]
https://dockstore.org/api/static/swagger-ui/index.html#/GA4GH/metadataGet

**Comment by coverbeck** [comment]
Turns out we are displaying the actual web service version.
