### ISSUE TITLE
Logged-In Lower Banner

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2604]
Create the lower banner for logged-in homepage, see spec for details

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-808)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 15 Outrigger
┆Issue Number: DOCK-808
┆Epic: Home Page Changes

**Comment by Ldcabansay** [comment]
PR: https://github.com/dockstore/dockstore-ui2/pull/708
Will need to revisit in 1.8.0
