### ISSUE TITLE
Logged-In Side-Bar Notifications for organization requests

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2605]
Dedicated box at top of sidebar of logged-in homepage
For phase1 limit to notifying if user has a pending # of requests
Pending request notification should show until request is no longer pending
Don’t need to show details of request, but clicking message should link to requests tab of accounts page (need to be able to navigate this tab via url, see linked issue)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-807)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-807
┆Epic: Home Page Changes

**Comment by denis-yuen** [comment]
Seems to exist, cannot review News and Updates at this time
