### ISSUE TITLE
Logged-In Accordion Workflows and Tools

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2607]
Phase1: On the sidebar accordion create a section each for workflows and tools (if necessary separate to different tickets). 
When the sections are the active view they should list the users _published_ workflows/tools. Display the 'short name' of the tool/workflow aka the  one thats on the sidebar of the 'My Workflows/Tools' page. Fix the height of each section, use scroll bar if # of entries exceeds height. Stretch goal: able to search through entries within accordion.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-809)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-809
┆Epic: Home Page Changes

**Comment by NatalieEO** [comment]
@agduncan94 The search is kind of buggy for this. Not sure how to reproduce consistently, but sometimes the same search query will list different matches.
![Screen Shot 2019-12-10 at 9 05 43 AM](https://user-images.githubusercontent.com/16004905/70551477-709bef80-1b2c-11ea-8f9e-8be8ce3e306e.png)
![Screen Shot 2019-12-10 at 9 05 59 AM](https://user-images.githubusercontent.com/16004905/70551480-7265b300-1b2c-11ea-97ff-0ca6303b37bc.png)

**Comment by agduncan94** [comment]
@NatalieEO that is strange, shouldn't be happening. I think I can just make the changes on this ticket.
* case insensitive search
* fix incorrect response

**Comment by denis-yuen** [comment]
Find is very slow, but seems functional
