### ISSUE TITLE
Logged-In Side-Bar Accordion Organizations

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2608]
Create the accordion section for Organization. Similar specs to the accordion section for tools/workflows

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-810)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-810
┆Epic: Home Page Changes

**Comment by NatalieEO** [comment]
@agduncan94 I think this works as expected, but the search is case sensitive like the tools and workflows accordion

**Comment by agduncan94** [comment]
@NatalieEO So if I have a workflow FOOBAR and I search foo then the FOOBAR won't show up?

**Comment by NatalieEO** [comment]
Yeah, it won't show up. Noticed while searching for 'human' and wouldn't bring up 'Human'

**Comment by agduncan94** [comment]
Ok cool, this should be easily fixed if we do equalIgnoreCase.

**Comment by denis-yuen** [comment]
Works as expected in 
API - 1.8.0-beta.6 
UI - 2.5.0-beta.1
More specific tickets can follow if applicable
