### ISSUE TITLE
Handle users who stay logged in for TOS acceptance

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2609]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-811)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-811
┆Epic: Terms of Service

**Comment by cricketsloan** [comment]
➤ Natalie Perez commented:

Investigate what to do about this. Look into state where you’re half logged in as possible idea. 

See if there is simple solution

**Comment by agduncan94** [comment]
Confirmed working on 2.4.0 and 1.7.0
