### ISSUE TITLE
Investigate removing position parameters from Dockstore

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2610]
### Desired behaviour

Currently, the Dockstore swagger description outputs positions http://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/Api.html#position() in the swagger.yaml. 
This is supposed to be deprecated, but shouldn't make things invalid ... except the validator complains and apparently this breaks https://github.com/Yelp/bravado as well  (found by @geoffjentry) 

The only reason we use position is because it was the only way to ensure that our swagger-codegen generated clients don't randomly change the order of parameters for methods. 
See issues like https://github.com/sdaschner/jaxrs-analyzer/issues/56 or https://github.com/swagger-api/swagger-core/issues/1050

There may be a better solution with updates to either swagger-codegen (or more painfully, the update to OpenAPI3 across the board).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-812)
┆Issue Type: Story
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-812

**Comment by denis-yuen** [comment]
Update: there's a setting for validation of the swagger in Bravado which works as a workaround

**Comment by christianlorenzhmmh** [comment]
Hi, 
our generated client uses method-caching (together with a redis distributed cache). The keys look like 

"servicea-service:v0:answer-resources:123:false"

(a prefix, a version, cache name for the method to be cached, parameter-values "123" and "false". The parameter-Values are attached to the key in the order of the method-signature (the method which is cached).

our service does the cache-puts after processing an answer. the client just performs the cache-gets (bevor asking the service via network).

Problem: if the service does not user alphabetical order, but the generated client does, then the cache-keys are different. Caching would not work.

That´s a problem.

Solution? Maybe...
Somehow take over control of the cache-key-generation e.g. in the KeyGenerator org.springframework.cache.interceptor.CacheOperationMetadata . The KeyGenerator is final though..... well.... maybe i can get around that.....

**Comment by denis-yuen** [comment]
```As it turned out there's a simple config setting to not validate the swagger and at least for dockstore the generated client seems to work AOK w/o it```
