### ISSUE TITLE
Support CWL version v1.1

### ISSUE THREAD

**Issue by mr-c** [dockstore/dockstore#2612]
Requires updating `cwltool` version. Let me know how I can assist!

Related is https://github.com/dockstore/dockstore/issues/2371 but this issue can track CWL v1.1 separately

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-813)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-813

**Comment by denis-yuen** [comment]
Thanks for the reminder. 
Our plan is to re-test with a new cwltool version before the next release for local execution. 

For the web service, we probably also have to look at https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/CWLHandler.java to see if there are any assumptions we made about 1.0 that don't carry across to 1.1 or need to be improved.

At a quick glance, I do see `Any doc field may be an array of strings in addition to the previously allowed single string.` may affect parsing of descriptions for example.

**Comment by denis-yuen** [comment]
I'm satisfied that 1.7.0 will have CWL 1.1 support in general. 

Adjusting for `doc`, other new cwl fields don't seem to break anything as way as the webservice is concerned. Will open more specific tickets if we encounter issues testing new CWL 1.1 workflows/tools.
