### ISSUE TITLE
After navigating to a non-WDL workflow, UI tries to fetch WDL

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2613]
## Bug Report

If you navigate to a non-WDL workflow, you will see in the console that the UI tries to fetch WDL for the workflow, even though it's not a WDL workflow. This also happens with CWL workflows.

This seems to have no ill effect on the UI, and you wouldn't even notice it unless you have developer tools open. But it is an unnecessary call, so we should ideally not do it.

### Steps to reproduce the behaviour 

1. Open Developer Tools in your browser
2. Navigate to https://dockstore.org/workflows/github.com/nf-core/rnaseq:1.2?tab=info
3. In the tool's console, you will see the message `ERROR Object { headers: {…}, status: 400, statusText: "Bad Request", url: "https://dockstore.org/api/workflows/6934/wdl?tag=1.2", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://dockstore.org/api/workflows/6934/wdl?tag=1.2: 400 Bad Request", error: "No descriptor found" }`

### Screenshot
![Screen Shot 2019-07-08 at 11 00 28 AM](https://user-images.githubusercontent.com/1049340/60837448-0ba72c80-a17d-11e9-9c9e-230bc96fb64a.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-814)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-814

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Can confirm that on staging this error does not appear.

  * API  ( https://staging.dockstore.org/api/static/swagger-ui/index.html# )- 1.7.0-beta.4 ( https://github.com/dockstore/dockstore/releases/tag/1.7.0-beta.4 )

thumbnail ( https://img.shields.io/uptimerobot/status/m779655940-a297af07d1cac2d6ad40c491.svg )

  * UI - 2.4.0-beta.3-13-gde12d62c ( https://github.com/dockstore/dockstore-ui2/releases/tag/2.4.0-beta.3-13-gde12d62c )
