### ISSUE TITLE
Update cromwell for 1.7.0

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2620]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-818)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-818
┆Epic: Update cwltool/cromwell 1.7.0

**Comment by denis-yuen** [comment]
https://github.com/broadinstitute/cromwell/issues/5085

**Comment by denis-yuen** [comment]
Can confirm functional with a few wdl workflows for Can confirm with 1.7.0-rc.0
Proceed to specific issues for potential bugs
