### ISSUE TITLE
Update cwltool for 1.7.0

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2621]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-817)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-817
┆Epic: Update cwltool/cromwell 1.7.0

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore/pull/2690
