### ISSUE TITLE
Apply checkstyle to tests

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2632]
### Desired behaviour
Checkstyle should be applied to tests too

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-819)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 19 Tanker
┆Issue Number: DOCK-819

**Comment by denis-yuen** [comment]
Took a brief look at this, will need to wait til 1.8.0. 
Will want the pom files changes from https://github.com/dockstore/dockstore/tree/feature/checkstyle_expand_to_tests when we get to it

**Comment by denis-yuen** [comment]
Merged, doesn't really need review
