### ISSUE TITLE
Research capturing author at version level

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2634]
## Feature Request 

Dockstore currently sets the workflow's author based on information from a workflow version.

Because the author can vary from version to version (although probably not often in practice), Dockstore should capture the author for each version.

Wrote this in a rush, so more research that should be done:

* This probably applies to tools as well
* This probably applies to other metadata as well.
* Should understand how the code sets the workflow's author from (which?) version.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-820)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-820

**Comment by denis-yuen** [comment]
Set 1.7.0 for someone to document how it currently works here

**Comment by cricketsloan** [comment]
➤ Louise Cabansay commented:

check database structure to see if it can store author at version level. See if it can go into 1.7.0, but might have to punt into 1.8.0

**Comment by Ldcabansay** [comment]
**Summary:** Database as of 1.7.0-beta.6 does not store author or metadata* at the version level for workflows or at the tag level for tools, or even at the Entry level. 

_For clarification, base level = overall tool, workflow, or entry_

**Metadata**: Fields captured at base level: 
- Author
- Description
- Email
- Alias (Entry)
- Label (Entry)

***Caveat**: 
We capture some metadata at the version level for workflows. We could probably move some base level metadata to this existing table, but would need to create corresponding for tools. This is currently limited to the following fields:
- DOI status
- DOI  url
- Frozen

**Non-metadata**: We have other things we capture at the version/tag levels that are technically metadata, but not of interest for these purposes such as:
- Valid
- Hidden
- Verified
- Reference
- Path
- etc

**Some things to consider:**
Some things such as checker and collection are saved at the base level (workflow, tool, or entry), which links to the user specified default version of that base entry. It might be worth talking about this in the future. 

- For example, a user might want to add a specific version of an entry to a collection (one that is frozen with a doi etc), not just the latest or default version. Right now only the current default version (ex: 1.2.0) is added to the collection. The collection will always link to this version (1.2.0), even if the default version of the entry changes (ex 1.3.0).
