### ISSUE TITLE
Move Zenodo DOI code to a new class

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2635]
There is now a lot of Zenodo-specific code in WorkflowResource. I would recommend moving it into a new class, perhaps io.dockstore.webservice.helpers.ZenodoHelper, to follow the existing patterns.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-822)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-822
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ZenodoHelper.java is a thing
Should be linked to https://github.com/dockstore/dockstore/pull/2732
