### ISSUE TITLE
Refresh Zenodo token in DOI web service

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2636]
The code to refresh the Zenodo token in the web service DOI needs to be implemented

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-821)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 15 Outrigger
┆Issue Number: DOCK-821
┆Epic: Create DOIs

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Hmm, I’m not sure this is working. I linked my account in staging. I came back an hour and a half later, and it no longer shows up as linked.

I had not published anything after first registering.

If I link the account again, it doesn’t show up as linked. Maybe it wasn’t linked the first time though, and I hadn’t paid close attention. In any case, I’m not able to link.

[~accountid:5c118bd3e91d16692a3a3ae8] I know you linked your account; does it still show up as linked on your Accounts page?

**Comment by denis-yuen** [comment]
![Screenshot from 2019-08-09 10-07-33](https://user-images.githubusercontent.com/1730679/62784966-9d140200-ba8d-11e9-977d-169d825d6ba3.png)

Yep, the `Username:` is blank though, which I recall hearing about but should be cleaned up and/or replaced with something we can get, like an ID perhaps?

**Comment by coverbeck** [comment]
I wonder if it ever worked for me. The authorization page comes up, but when it comes back to the accounts page, it still shows the Link account button (as opposed to unlink). I wonder if the first time I tried that I didn't pay close attention. 

I just tried linking again and noticed a 500 with a duplicate key violation:

```
{"code":500,"message":"could not execute statement ERROR: duplicate key value violates unique constraint \"one_token_link_per_identify\"\n  Detail: Key (username, tokensource)=(, zenodo.org) already exists. "}
```

And in pasting the above message I see the problem: the constraint is on `username, tokensource` but as you noted, username is always empty. Looks like we can only allow one user to link to Zenodo.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Linked my account Zenodo on staging this morning. Waited several hours, then successfully created a DOI via the UI. Since access tokens expire after one hour, this means refresh logic worked.

API - 1.7.0-beta.4
UI - 2.4.0-beta.3
