### ISSUE TITLE
SharedWorkflow connection leak

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2638]
### Desired behaviour
get SharedWorkflows endpoint is using a temporary solution to avoid the connection leak.  Should investigate why the more optimized `.filter(workflow -> !workflow.getUsers().contains(user))` causes a leak

[~nperez9] use performance testing framework

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-824)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-824

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore/pull/2629#discussion_r304652725 is worth a try 
it does look suspicious to me

**Comment by denis-yuen** [comment]
@coverbeck for review, maybe this can be hooked up to the performance tester. 
Feel free to delegate

**Comment by NatalieEO** [comment]
Ran curl for sharedworkflow endpoint 1000 times, staging seems to be fine
API - 1.7.0-rc.0 
UI - 2.4.0-rc.0
