### ISSUE TITLE
Store the date and time someone creates an immutable workflow.

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2641]
Store date and time someone creates an immutable workflow so we can use that as the creation/publish date for a workflow in a Zenodo entry. Include this a part of the workflow attributes so it can be accessed something like workflowVersion.getImmutableCreationTime

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-825)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-825

**Comment by denis-yuen** [comment]
Might be redundant, when the frozen variable is set. That should be last time the version is able to be modified, meaning the column with
https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/annotations/UpdateTimestamp.html  will trigger and store that final time.

Please confirm @NatalieEO
