### ISSUE TITLE
418 errors should display error message (Services webservice grab bag)

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2643]
1. 418 errors should display error message (statusMessage currently null)
1. ~~~workflows and services with the same path should not clash (Charles)~~
1. ~~~basic validation for dockstore.yml (Andrew)~~~
1. ~~~add versions with dockstore.yml even if invalid (Andrew)~~~
1. ~~sync account should add user to any existing services they have access too, and pull any new ones that the app is installed on but aren't on Dockstore (Charles)~~

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-826)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-826
┆Epic: Dockstore  My Services

**Comment by agduncan94** [comment]
It seems like the issue is due to us returning a TEXT-PLAIN message for error response instead of the JSON object that WebApplicationException would usually create. The logging probably expects the response to be in the latter form.

Current CustomWebApplicationException response:
```
A service already exists for GitHub repository agduncan94/test-service
```


Typical WebApplicationException response:
```
{
  "code": 418,
  "message": "A service already exists for GitHub repository agduncan94/test-service"
}
```

**Comment by agduncan94** [comment]
The solution was to use the message body as the error message for 418 errors only. This was done in the lambda.

**Comment by cricketsloan** [comment]
➤ Gary Luu commented:

Everything seems to work.  Sync all takes a fairly lengthy amount of time though.
