### ISSUE TITLE
Services UI grab bag

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2644]
### Desired behaviour
- [x] Refresh individual service
- [x] Sync organization services
- [x] Add back plus button
- [x] Get rid of shared services
- [x] Modal for register services
- [x] Add sync next to manage github
- [x] Services description version
- [x] Change Register service to managed on GitHub
- [x] Change refresh button (single service) to sync
- [x] Load entry-specific action buttons at same time (Publish, View Public, Refresh, etc)
- [x] Hide share with me
- [ ] ~Change to GitHub icon for desktop, dropdown for mobile~
- [ ] Investigate validation per file
- [ ] ~Need a better message for missing version description~
- [ ] Weird tooltip when there's no services "Requires source control token" overlaps with the button tooltips

Possibly going to split some of these out

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-828)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 15 Outrigger
┆Issue Number: DOCK-828
┆Epic: Dockstore  My Services

**Comment by NatalieEO** [comment]
Sync button is added, but non-functional. However, Charles ticket to hook it up to the UI will have it's own review so I think this can be considered done.

Issues that are checkmarked working on staging API - 1.7.0-beta.1 
UI - 2.4.0-beta.1. 

Created another ticket for the other two #2707
