### ISSUE TITLE
Better icon for admin, curator, user, services

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2645]
### Desired behaviour
Investigate better icons for the dropdown main (admin, curator, and user).  Currently, it's using (lock, edit, and account_circle)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-827)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10410/Screen+Shot+2021-05-06+at+14.21.47+.png">Screen Shot 2021-05-06 at 14.21.47 .png</a>
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-827
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Also services

**Comment by agduncan94** [comment]
I think we should just replace all icons at once.

**Comment by denis-yuen** [comment]
Might be done already
