### ISSUE TITLE
Move DOI UI code into the service and add null checks

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2646]
Throw majority of the code into the service and add some null checks for this.workflow and this.selectedVersion

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-830)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-830
┆Epic: Create DOIs

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Version component service

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Guard against issuing DOI for mutable version

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Edit dialog disable controls for frozen workflow

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Opened a draft PR here https://github.com/dockstore/dockstore-ui2/pull/736 ( https://github.com/dockstore/dockstore-ui2/pull/736|smart-link )

**Comment by denis-yuen** [comment]
Draft PR closed, not really the kind of thing that is reviewable on staging
