### ISSUE TITLE
Use as a stream, map, and collect to List in DOI web service code

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2648]
Use as a stream, map, and collect to List in DOI web service code for adding labels code insetMetadataRelatedIdentifiers and in getAnExistingDOIForWorkflow in WorkflowResource.java

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-831)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-831
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
Done in #2712
