### ISSUE TITLE
Workflow/tool Date fields are numbers not Dates

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2650]
The `dbCreateDate` and `lastUpdated` fields on Workflows and DockstoreTools have type Date but are returned as numbers from the webservice. In date.service.ts, 
```
getISO8601Format(timestamp: Date | number): string | null {
    if (timestamp) {
      return new Date(timestamp).toISOString();
    } else {
      return null;
    }
  }
```
It should not be necessary to make a new Date() from `timestamp` when it is already a Date.
 See conversation here: https://github.com/dockstore/dockstore-ui2/pull/667

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-832)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Sprint: Backlog
┆Issue Number: DOCK-832
┆Epic: Dates

**Comment by garyluu** [comment]
Closing in favor of https://github.com/dockstore/dockstore/issues/3127
