### ISSUE TITLE
Only allow user to create DOIs for immutable workflow versions

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2653]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-834)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-834
┆Epic: Create DOIs

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Webservice needs to guard against DOI issuance for mutable versions

**Comment by NatalieEO** [comment]
Confirm that I can't create DOIs for versions that aren't frozen.
API - 1.7.0-beta.5 
UI - 2.4.0-beta.4
