### ISSUE TITLE
Update Documentation on Adding a Launch With Button

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2659]
## Feature Request 

The documentation for adding a Launch with Button needs to be updated to account for the new way configuration information is supplied to the UI, via the `/metadata/config.json` endpoint.

The [current documentation](https://github.com/dockstore/dockstore-ui2/blob/0574e06e36fb1d60e4f995e61776e8375859aca1/src/app/workflow/launch-third-party/launch-third-party.component.ts#L20) is in the UI code.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-839)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-839

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Folded this in to DOCK-839
