### ISSUE TITLE
Display modified hosted version immediately

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2661]
### Desired behaviour
After modifying a hosted version, the new version should immediately be displayed.

Example, if you're on version 1 (the only version).  Modify the version somehow (edit, remove, add), and then click "Save as New Version".  This new version (2) should now be selected and the title bar of the tool/workflow should be my-entry-name:2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-841)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-841

**Comment by denis-yuen** [comment]
@garyluu check on ui2 PR and assign reviewer when merge is confirmed

**Comment by Ldcabansay** [comment]
Verified on  Dockstore - 1.7.0-beta.5 and UI - 2.4.0-beta.4
