### ISSUE TITLE
Refreshing another user's workflows as an admin refreshes the admin's workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2664]
## Bug Report

The endpoints to refresh a user's workflows, `/users/{userId}/workflows/refresh` and `/users/{userId}/workflows/{organization}/refresh` allow an admin to call the endpoint on the user's behalf. But they then update the admin's workflows, not `{userId}`'s workflows.

The call to `checkUser` [here](https://github.com/dockstore/dockstore/blob/8916d3eee89b15090d3e0e4aa0ab5c012b071fe9/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java#L478) allows the method to proceed if the auth user is an admin, or if the auth user matches the `userId`.

However [the code](https://github.com/dockstore/dockstore/blob/8916d3eee89b15090d3e0e4aa0ab5c012b071fe9/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java#L481l) to refresh the workflows always uses the auth user, which means if `userId` is not authUser, authUser's workflows will be refreshed instead of userId's.

Note: Did not actually test this, noticed only from reading the code, which means I could be wrong.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-843)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-843
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
worth investigating

**Comment by coverbeck** [comment]
@denis-yuen , no, this has not been done. Looks like I referenced the wrong GitHub issue in my commit message.

**Comment by melainalegaspi** [comment]
@denis-yuen "We can just disable it."

**Comment by NatalieEO** [comment]
Confirmed on dev that admins can't refresh another user's workflow.

[Webservice](https://github.com/dockstore/dockstore/commits/055b7d4) - 055b7d4

[UI](https://github.com/dockstore/dockstore-ui2/commits/0e19bb8d) - 2.7.3-75-g0e19bb8d

[Compose Setup](https://github.com/dockstore/compose_setup/commits/36c8ddc) - 36c8ddc

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/4659624) - 1.10-60-g4659624
