### ISSUE TITLE
Refreshing a workflow that has become invalid does not update workflow

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2665]
### Expected behaviour
When a workflow is changed to something invalid and then manually refreshed, I would expect it to get updated with verification problems displayed in the files tab.  Another option is for an error message to display. 

### Actual behaviour
Refresh said successful, but nothing changed.

### Steps to reproduce the behaviour 
- Have a valid workflow with master/develop branch  in my-workflows
- Modify it to say `class: CommandLineTool` in GitHub
- Refresh workflow
Notice the absence of any error indicators

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-844)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-844

**Comment by denis-yuen** [comment]
Looks like a couple of related GUI issues. 
1) I needed to go a hard refresh to see the new content `lass: CommandLineTool`
2) The validation messages are not showing up ala https://github.com/dockstore/dockstore-ui2/pull/513 although I see them in the JSON response from calls like
`x:8080/workflows/3749?include=validations`

**Comment by denis-yuen** [comment]
FYI, in discussion with @garyluu looks like you're working on this already

**Comment by NatalieEO** [comment]
@garyluu @denis-yuen Hm, I'm not able to reproduce this? I see the workflow get updated and validation warning in the files tab without needing to refresh the page.

**Comment by denis-yuen** [comment]
@NatalieEO that's good news
I would try a few more scenarios (i.e. a valid workflow that becomes a malformed workflow in my-workflows, ditto for a malformed tool in my-tools, ditto for a malformed service in my-services) and if it all looks good. This can be closed

**Comment by garyluu** [comment]
this is the repository I used https://github.com/garyluu/Metaphlan-ISBCGC , see the last commit

**Comment by garyluu** [comment]
Ok, I think it was just a caching delay or something.
