### ISSUE TITLE
UI should force user to confirm creation of Zenodo DOI

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2666]
Issuing a DOI is a significant event. A user shouldn't be able to easily create one accidentally by unintentionally clicking the DOI button; there should be a dialog that requires the user to confirm.

Note: We also require a similar dialog for creating a frozen/snapshot version. And we have been speaking about a dialog that lets you create a Zenodo DOI from an unfrozen version, i.e., it will do the freezing for you.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-845)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-845
┆Epic: Create DOIs

**Comment by coverbeck** [comment]
@david4096 -- please see description of this. Your code for snapshot confirmation could perhaps be reused here. Or may be overkill, depending on how it's implemented.

**Comment by denis-yuen** [comment]
In progress at https://github.com/dockstore/dockstore-ui2/pull/736

**Comment by denis-yuen** [comment]
Confirmation dialogue live on staging 
```
API - 1.7.0-rc.0
UI - 2.4.0-rc.0
```
