### ISSUE TITLE
Create DOI button probably not in right place

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2667]
## Bug Report

The Create DOI button is next to Publish/Unpublish button, whose scope is the whole workflow.

The Create DOI button creates a button for a workflow **version**. Perhaps it should be located on the versions tab. OTOH, that will tend to hide its prominence.

Also, the Create DOI button is appearing on the My Services page, which we probably don't want at this point.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-846)
┆Issue Type: Story
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-846

**Comment by denis-yuen** [comment]
> The Create DOI button creates a button for a workflow **version**. Perhaps it should be located on the versions tab. OTOH, that will tend to hide its prominence.

:+1: 

> Also, the Create DOI button is appearing on the My Services page, which we probably don't want at this point.

Yes, it should probably be hidden given bandwidth.

**Comment by denis-yuen** [comment]
In progress at https://github.com/dockstore/dockstore-ui2/pull/736

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Covered by DOCK-830.
