### ISSUE TITLE
Get GitHub organization (and personal) id from webservice

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2671]
### Desired behaviour
UI currently gets all the GitHub organizations and figures out the ID in order to create a GitHub Apps installation URL for the specific organization/user (dockstore, garyluu, dockstore-testing, etc).  Webservice should do it instead.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-849)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-849
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@garyluu chat tomorrow, need to refresh

**Comment by denis-yuen** [comment]
Think this is still relevant or we have some dead code. 
https://github.com/dockstore/dockstore-ui2/blob/60b2027364ef2040fad22031b5e37b3709f2fb14/src/app/shared/state/token.service.ts#L82

**Comment by garyluu** [comment]
I see it called in the network tab in my-workflows

**Comment by denis-yuen** [comment]
Yeah, that works
