### ISSUE TITLE
Cannot view all descriptor and test parameter files for workflow

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#2675]
## Bug Report
Only one descriptor file and test input file are displayed (e.g. WDL, JSON files) for selected Version

### Expected behaviour
All of the files (e.g. WDL and test input) should be available to view

### Actual behaviour
Only one file (e.g. WDL and test input) are available for viewing

### Steps to reproduce the behaviour 
Go to:
https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:feature/freeze8-wdl?tab=files
(or a branch that is different from the 'default')

Only topmed_freeze3_calling.wdl is available for viewing, even though topmed_freeze8_calling.wdl is present in the GitHub repo. 

### Environment (Browser or OS and Dockstore version)
Chrome
DockstoreAPI - 1.6.0
DockstoreUI - 2.3.0

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website) 
Mac OS

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-850)
┆Issue Type: Story
┆Issue Number: DOCK-850

**Comment by garyluu** [comment]
I believe there's only 1 primary descriptor for each workflow and its defined by whatever is set on 'workflow path'

**Comment by denis-yuen** [comment]
Yes, I don't believe that we follow and parse http imports, but its worth double-checking

**Comment by wshands** [comment]
OK thanks I was thinking the wrong way about this
