### ISSUE TITLE
Logged in home page broken links

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2677]
### Expected behaviour
The three buttons in the banner should link to something

### Actual behaviour
None of the buttons works.  Adding RouterModule to the home-page module should fix the bottom two buttons.  The /about still doesn't work.

### Steps to reproduce the behaviour 
Log to the logged-in home page and click on the three buttons

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-851)
┆Issue Type: Story
┆Issue Number: DOCK-851

**Comment by denis-yuen** [comment]
Link a PR

**Comment by NatalieEO** [comment]
going to https://staging.dockstore.org/beta-homepage, the three buttons do link out correctly.
API - 1.7.0-beta.4 
UI - 2.4.0-beta.3-13-gde12d62c
