### ISSUE TITLE
Search from homepage doesn't always work

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2679]
### Expected behaviour
Search from homepage should filter by name

### Actual behaviour
Sometimes the filter is not applied, seems like a timing issue.

### Steps to reproduce the behaviour 
Go to homepage, type 'asdf' and press enter.  Keep repeating this and eventually, it will actually return all tools/workflows.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-852)
┆Issue Type: Story
┆Issue Number: DOCK-852

**Comment by denis-yuen** [comment]
Looks good on staging.dockstore.org
