### ISSUE TITLE
Workflows and tooltester logs

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2680]
### Desired behaviour

Checker workflows that can run successfully should have tool tester logs
Not sure if not run or not visible

Follows #2348

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-853)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Sprint 21 Viking vessel
┆Issue Number: DOCK-853

**Comment by denis-yuen** [comment]
1) Run checker workflows for verified workflows, period
2) Let's get a breakdown of checker workflows and why they're blacklisted
3) Are there any in https://github.com/dockstore/dockstore-support/blob/develop/tooltester/src/main/java/io/dockstore/tooltester/blacklist/BlackList.java here that have no versions that are successful

**Comment by denis-yuen** [comment]
Reviewer should check that remaining verified workflows with checker workflows have logs
@garyluu to fix checker workflows, at least hello world and md5sum so that at least one version of the checker workflow has logs (ideally, not a branch)

**Comment by garyluu** [comment]
2 and 3:
#workflow/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl: 
- [x] find latest version https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=files
- [x] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl:
- [ ] find latest version can't find it anymore
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/DataBiosphere/topmed-workflows/UM_aligner_cwl: 
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
quay.io/pancancer/pcawg-sanger-cgp-workflow
- [ ] find latest version 2.0.6
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
quay.io/pancancer/pcawg-dkfz-workflow:  I can never run this
- [ ] find latest version 2.0.6
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/KnowEnG/cwl-gene-prioritization
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/NCI-GDC/gdc-dnaseq-cwl/GDC_DNASeq
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/bcbio/bcbio_validation_workflows
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/dockstore-testing/md5sum-checker
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/dockstore-testing/md5sum-checker/wdl
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production
#workflow/github.com/dockstore/hello_world
- [ ] find latest version
- [ ] Manually run it
- [ ] Verify on staging
- [ ] Verify on production

**Comment by garyluu** [comment]
TODO List:

- [ ] Make changes for https://docs.dockstore.org/docs/publisher-tutorials/checker-workflows/ and mention logs
- [ ] Verify all checker workflows that were ran
- [ ] Do something for bcbio_validation_workflow
- [ ] Make a real hello_world checker workflow, make new release, rerun.
