### ISSUE TITLE
Change search to use Material Tab

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2684]
### Desired behaviour
ngx-bootstrap should be phased out eventually.  
Change the search page tabs to use Material tabs instead.

Or just get rid of the whole tabs thing in search entirely

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-856)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-856

**Comment by denis-yuen** [comment]
Duplicates #2747
