### ISSUE TITLE
My Workflows -- show numbers of repos

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2686]
## Feature Request 

It would be nice if there were a count of the visible number of repos in each org, using something like [Material badges](https://material.angular.io/components/badge/overview).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-858)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-858
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Idea is more to use this as an opportunity to think about how to search/filter my-workflows
