### ISSUE TITLE
Add comment about DOI upload file deletion

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2694]
WorkflowResource.java
This could use a comment... looking at code It seems odd that you have to wait for line 1317 to finish executing before you can delete the file, even though you don't pass the file to that method. As you explained to me some part of the deposition has a reference to the file so it can't be deleted, but if I saw this code 1 year from now I would be tempted to refactor it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-860)
┆Issue Type: Story
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-860
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
This seems a bit overkill as a discrete ticket?

**Comment by denis-yuen** [comment]
This was https://github.com/dockstore/dockstore/pull/2674#discussion_r309931484
