### ISSUE TITLE
Limit information provided in CustomWebApplication exception message

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2695]
WorkflowResource.java line 1129
Other files in Dockstore
Regarding my comments on the error messages -- to my knowledge we don't have a standard defined, so this is just my opinion. But I feel that we shouldn't be passing back internal error details to the client. Somebody tries to create a DOI and sees an error message mentioning an outputstream or that it's trying to create a temp directory (where?) -- I think it's a potentially confusing experience.

In case you don't know, the CustomWebApplication messages are typically (always?) displayed in the browser, so keep that in mind.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-861)
┆Issue Type: Story
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-861
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore/issues/2694#issuecomment-517727444

**Comment by denis-yuen** [comment]
Still a thing as of f8be15a956078c8f21b424f93ca8e3f2c081b248
