### ISSUE TITLE
Migrate and write up procedure for staging.dockstore.org migration to cloudfront

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2696]
### Desired behaviour

Come up with a plan to migrate staging.dockstore.org
Record length of / minimize outage 
Write up docs to use as a model for a similar migration for dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-862)
┆Issue Type: Story
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-862
┆Epic: Serve UI from s3/CloudFront

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

https://wiki.oicr.on.ca/display/DOC/Cloudfront ( https://wiki.oicr.on.ca/display/DOC/Cloudfront ) will need updates due to our latest approach 

(i.e. no edge lambda, no cname)

Should also clean up old cloudfront distro, lambda, etc. if confirmed
