### ISSUE TITLE
Pram Ticket Review-Andrew

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2699]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-866)
┆Issue Type: Story
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-866

**Comment by denis-yuen** [comment]
@melainalegaspi FYI
@agduncan94 closing since this should not be on github
