### ISSUE TITLE
Align DOI UI and Snapshot UI Flow

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2700]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-865)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-865
┆Epic: Version Immutability

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Edit dialog disable controls for frozen workflow

Guard against issuing DOI for mutable version

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Include version information in snapshot dialog

**Comment by denis-yuen** [comment]
Duplicates #2846
