### ISSUE TITLE
Add DOI swagger README with comment about where swagger originated

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2702]
coverbeck 3 days ago  Member
I guess you can't put it in here, but it would be nice to know, maybe in a commit comment, or maybe in the module's README.md, where this swagger came from.

I thought you said the Zenodo didn't have Swagger doc that you could find? Was this manually created? What if the update our API? How will we know how to update this doc?

Zenodo does not have a Swagger doc; it was in Denis' Zenodo prototype code, but we are not sure where it came from. Not a great situation but it works. When I asked Zenodo about it they replied "Thank you for contacting us. Unfortunately, we don't have swagger. You can find a list of the Zenodo REST API at this endpoint: https://zenodo.org/api/
And here you can find the REST API's documentation: http://developers.zenodo.org/"

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-870)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-870
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
Looking at the blame, I think I actually wrote this myself 
https://github.com/dockstore/zenodo-client/blame/master/swagger.yaml
