### ISSUE TITLE
Set DOI publication date to immutable version creation date

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2703]
Set DOI publication date to immutable version creation date in setMetadataPublicationDate when the immutable version creation date is available

Also from Charles: Probably doesn't matter, but going to mention it anyway`ZoneId.systemDefault` -- that will be using the timezone of the server. If Dockstore ever becomes popular enough that it requires being deployed in two or more regions, then the the results of this may depend on which server gets hit.

OTOH, you're only narrowing down to the day, not to time, and I may have this wrong about the behavior.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-869)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-869
┆Epic: Create DOIs

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

The publication date on Zenodo is set to workflowVersion.getLastModified(); is this appropriate?

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

We agreed to use the date that the DOI is created as the publication date.

**Comment by denis-yuen** [comment]
```
Publication date:
    August 15, 2019
```
Seems functional
