### ISSUE TITLE
2 Leftovers from services grab bag

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2707]
Investigate/add validation per file for services (also somewhat related to #2665 )

Weird tooltip when there's no services "Requires source control token" overlaps with the button tooltips

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-873)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-873
┆Epic: Dockstore  My Services

**Comment by denis-yuen** [comment]
Validation messages for services seem to display properly. 
Validation messages for workflows seem intact

```
API - 1.7.0-rc.2 
UI - 2.4.0-rc.2
```
