### ISSUE TITLE
Make template available to users in documentation of dockstore.yml

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2709]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-876)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-876

**Comment by denis-yuen** [comment]
this is for services

**Comment by cricketsloan** [comment]
➤ Gary Luu commented:

It’s linked to the develop .dockstore.yml  . Not sure if that’s intended.

**Comment by NatalieEO** [comment]
@garyluu I didn't give the link much thought. Does something else make more sense?

**Comment by garyluu** [comment]
Just point to the doc in the current branch I think?

**Comment by NatalieEO** [comment]
redid link https://github.com/dockstore/dockstore-documentation/pull/22

**Comment by denis-yuen** [comment]
:+1:
