### ISSUE TITLE
Info parsing

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2710]
Get author, email, description to populate. 

* Get this info from .dockstore.yml

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-875)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-875
┆Epic: Dockstore  My Services

**Comment by denis-yuen** [comment]
This was https://github.com/dockstore/dockstore/pull/2769 which means

**Comment by denis-yuen** [comment]
Working on staging.dockstore.org
https://staging.dockstore.org/services/github.com/dockstore-personal-testing-phoenix/app-support-prototype-awesome:12.0?tab=info
