### ISSUE TITLE
Adding gitlab as a docker registry

### ISSUE THREAD

**Issue by philloooo** [dockstore/dockstore#272]
as per title, we are using gitlab for one of our projects, it's nice that it has docker integration so we don't need to host dockers and code in separate places. It would be great if dockstore can support this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-443)
┆Issue Type: Story
┆Issue Number: DOCK-443

**Comment by denis-yuen** [comment]
Hi, 
I think so. To clarify, browsing through their website, I think supporting the instance of gitlab hosted at gitlab.com would be pretty straightforward.  

However, if your institution has a private instance of GitLab CE or EE running on-site, that would be more difficult and would require more drastic changes.

**Comment by philloooo** [comment]
yeah I was only talking about the one gitlab itself hosted

**Comment by denis-yuen** [comment]
@agduncan94 
Investigate and document this in a wiki document
1) How extensive is the API for GitLab (automated builds, listing a users repos, organizations they might be in, docker repos)
2) Does it support something akin to third-party OAuth and scoped access (read-only)
3) How easy is it to work with their API?

**Comment by denis-yuen** [comment]
Source code implemented in 1.1
Docker images to be implemented in following release

**Comment by melainalegaspi** [comment]
already implemented
