### ISSUE TITLE
io/netty/util/Timer error with github.com/DataBiosphere/topmed-workflows/checker_UM_aligner_wdl:1.32.0

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2725]
### Expected behaviour
Dockstore 1.7.0-beta.2 should be able to run the following commands and not have error
`gluu@ODL-GARYLUU:~/test/topmed-workflows/aligner/u_of_michigan_aligner-checker$ ./dockstore workflow launch --local-entry u_of_michigan_aligner_checker.wdl --json u_of_michigan_aligner_checker.json --script`

### Actual behaviour
```
gluu@ODL-GARYLUU:~/test/topmed-workflows/aligner/u_of_michigan_aligner-checker$ ./dockstore workflow launch --local-entry u_of_michigan_aligner_checker.wdl --json u_of_michigan_aligner_checker.json --script
Created temporary working directory at '/tmp/1565213299047-0'
Using local file 'u_of_michigan_aligner_checker.wdl' as primary descriptor
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/Timer
```

### Steps to reproduce the behaviour 
- git clone the repo from https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/checker_UM_aligner_wdl:1.32.0?tab=info 
- get the dockstore 1.7.0-beta.2 script
- checkout version 1.32.0
- run dockstore workflow launch --local-entry u_of_michigan_aligner_checker.wdl --json u_of_michigan_aligner_checker.json --script

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-882)
┆Issue Type: Story
┆Issue Number: DOCK-882

**Comment by denis-yuen** [comment]
@garyluu ditto, all workflows, all WDL workflows, or this specific version of the workflow?

**Comment by garyluu** [comment]
ditto, investigate

**Comment by garyluu** [comment]
this specific workflow and its version
