### ISSUE TITLE
Only one user can link to Zenodo

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2735]
## Bug Report

See [comment](https://github.com/dockstore/dockstore/issues/2636#issuecomment-519977588) -- there is a constraint on username, token_source, but username is always empty for Zenodo, so once the first user links his/her account, no further users can link.

Side note: when the linking fails, there is no obvious indication to the user. It appears to work, unless you notice that the link button is not enabled.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-886)
┆Issue Type: Story
┆Issue Number: DOCK-886
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
Seems to work staging.dockstore.org
