### ISSUE TITLE
Let's encrypt renewal cron not quite working

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2737]
### Desired behaviour

Seems like the cron command works according to the log and actually running it yourself. 
However, when checking the actual certificate, it seems like the new certificate is failing to be saved leaving to emails/potential HTTPs expiry.

Likely a permissions issue/some difference between running Docker as a cron/vs as the login user.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-887)
┆Issue Type: Story
┆Issue Number: DOCK-887

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Fixed

**Comment by denis-yuen** [comment]
Was different ways of install AWS (use apt)
