### ISSUE TITLE
CLI should warn about port 8443

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2739]
## Feature Request 

Due to CloudFront limitations, in Dockstore 1.7, we may no longer expose port 8443, requiring all https to go through the standard 443 port.

It's possible there might be some Dockstore config files that are still pointing to port 8443. The CLI could print a warning message if it detects the non-standard port so that users will know to update the config file.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-888)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-888

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Exists and works with staging.dockstore.org ( http://staging.dockstore.org ) CLI
