### ISSUE TITLE
Hide snapshot button on public page for services and workflows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2742]
## Bug Report
It fails and gives an error, but the snapshot button should be hidden on the public page.

### Steps to reproduce the behaviour 
Go to any workflow or service's public page and click on the versions tab.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-892)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-892

**Comment by NatalieEO** [comment]
Wasn't reviewing this specifically, but this is actually viewable again 
https://staging.dockstore.org/workflows/github.com/gatk-workflows/gatk4-somatic-snvs-indels/Mutect2:2.4.0?tab=versions

**Comment by denis-yuen** [comment]
Fixed in
```
API - 1.7.0-rc.1 
UI - 2.4.0-rc.1
```
