### ISSUE TITLE
Default metadata for DOI

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2744]
## Feature Request 

If you create a Zenodo DOI through Dockstore, the default author and description are "unknown creator" and "no description", respectively.

1. I don't like "unknown creator". How about "Author not specified"? Or at least "author" instead of "creator" -- the Zenodo UI refers to it as author.
2. How about "No description specified"?

Whatever we come up with, I think the first letter should be capitalized.

I know the user can edit the Zenodo afterwards, so it's not a huge deal, but at least with my one test case, it looks a little odd in Zenodo by default.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-894)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-894

**Comment by NatalieEO** [comment]
if no author/description then 
```
Author not specified
No description specified
```
are the defaults.
API - 1.7.0-rc.0 
UI - 2.4.0-rc.0
