### ISSUE TITLE
Remove ngx-bootstrap

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2747]
### Desired behaviour
"Only use one UI library in your Angular app

Even with tree shakeable ES6 imports, having eg. Material, Bootstrap, and Covalent in the same Angular app will crank up your main bundle size a lot. Also, it might make up for a weird design with mixing all of these UI libraries. Pick one and get rid of the others. An exception to this can be if you need a specific part from another ES6 loadable library, then sure import it, but if it is not shown on the initial load, lazyload it."

We should remove ngx-bootstrap and just stick to Material

Change the search page tabs to use Material tabs instead.
Or just get rid of the whole tabs thing in search entirely

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-897)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-897
┆Epic: Remove ngx-bootstrap

**Comment by denis-yuen** [comment]
Should probably come before #1899

**Comment by garyluu** [comment]
Can confirm search table has been swapped, still plenty of other ngx-bootstrap to remove though. Some were split out into different issues but not sure if it's exhaustive.

**Comment by ByteMap** [comment]
#3364
