### ISSUE TITLE
Investigate customized index.html for CloudFront

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2748]
## Feature Request 

Instead of using 100% CloudFront, where CloudFront directly serves up all the UI and proxies calls to the API, instead have the Docker VM serve up an index.html that has links to UI bits in CloudFront locations.

With this approach, the bulk of the UI will still be loaded via CloudFront. We will be able to phase in full CloudFront usage in future releases after we have sorted out some other issues.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-899)
┆Issue Type: Story
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-899
┆Epic: Serve UI from s3/CloudFront

**Comment by denis-yuen** [comment]
This is now functional in staging.dockstore.org
