### ISSUE TITLE
Create Tests for Zendo DOI Generation

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2749]
"There are two different code paths for adding a Zenodo DOI; one when no Zenodo DOI exists at all for any workflow version of a workflow, and another when there is at least one workflow version that already has a DOI. So we need a test for both of these cases if possible.

Other cases where DOI creation will fail:

If there are no descriptor or test input files associated with a workflow version (Zenodo must be able to upload files associated with a workflow version)
( also If a DOI already exists for a workflow version; but in this case the UI should disable the Create DOI button.)"

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-898)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Sprint 20 Umiak
┆Issue Number: DOCK-898
┆Epic: Create DOIs

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

I was able to create a DOI for my own Github repo test workflow on the production Zenodo site at https://zenodo.org/record/3386583#.XXBTj5NKh-U ( https://zenodo.org/record/3386583#.XXBTj5NKh-U ) via my local Dockstore instance.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Starting to look at tests written by Charles that  can be used as a template to mock calls to Zenodo https://github.com/dockstore/dockstore/commit/d25cc6558d4a31f4f601e193538ce3ff81674df1 ( https://github.com/dockstore/dockstore/commit/d25cc6558d4a31f4f601e193538ce3ff81674df1|smart-link )

**Comment by denis-yuen** [comment]
From storytime, need to ensure that final DOI is live on Datacite

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

The DOI not being published to DataCite turned out to be a Zenodo problem. Response from Zenodo support:

Dear Walter,

Thanks for having contacted us.

Our DOI providers had an issue on September 5th that made this problem occurred. This has now been fixed on their side and we just reprocessed your DOI which is now resolving.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Fixing an issue that prevents Hoverfly from mocking the Zenodo endpoints. It is due to using apache http client. See https://docs.hoverfly.io/projects/hoverfly-java/en/latest/pages/misc/misc.html ( https://docs.hoverfly.io/projects/hoverfly-java/en/latest/pages/misc/misc.html )

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Tried various potential solutions to get Hoverfly to intercept calls to Zenodo but none worked.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Created a manual test located here: https://github.com/dockstore/dockstore-ui2/blob/feature/cypress-zenodo/cypress/integration/manualTests/zenodo.ts ( https://github.com/dockstore/dockstore-ui2/blob/feature/cypress-zenodo/cypress/integration/manualTests/zenodo.ts|smart-link )

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

https://github.com/dockstore/dockstore-ui2/pull/805 ( https://github.com/dockstore/dockstore-ui2/pull/805|smart-link )
