### ISSUE TITLE
Existing entry aliases overwritten when new alias added

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2752]
**Needs to be verified when deployment of Dockstore 1.8 to staging occurs.**

## Bug Report
Aliases are overwritten for each entry when a new alias is added. A put request is sent when adding an alias to a workflow, this put request will override all existing aliases. Current work around is submitting a put containing all current aliases along with new additional aliases.

### Expected behaviour
Updating aliases should add new aliases to existing list. Might want to add the ability for curators and/or admins to remove aliases

### Steps to reproduce the behaviour 
1. Add an alias to an entry using the /entries/{id}/aliases endpoint
1. Confirm the new alias by fetching the workflow by ID (pending #2654, otherwise check database)
1. Add another alias to the entry
1. Confirm that the most recent added alias is there, but the first added alias is not

### Environment
Bug observed on Dockstore-1.7.0-beta.4

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-902)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Sprint 20 Umiak
┆Issue Number: DOCK-902

**Comment by denis-yuen** [comment]
A couple ideas @coverbeck @Ldcabansay 
a) never allow deletion of aliases (seems appropriate in DOI land, but may be not appropriate later)
b) use hosted workflow version syntax (https://dockstore.org/static/swagger-ui/index.html#/hosted/editHostedTool  "Set of updated sourcefiles, add files by adding new files with unknown paths, delete files by including them with emptied content"), meaning that it is easy to add aliases but you need an explicit json construct to delete them, the user cannot accidentally delete an alias by simply not including them  (a pro here is there might be some code that can be copied)

**Comment by coverbeck** [comment]
1. Another idea, although I don't know if I like it -- modify the existing PUT endpoint to return a 400 if the request doesn't at least include all existing aliases.
2. If using PATCH as with the hosted workflows example, because there are no files with/without content, there would be no way to delete via this method (unless you do something like [this article](https://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/) (see about 2/3 way down).  Which I think would be OK if we're never going to allow deletion of aliases, but would be a problem if we ever decided to allow it. Although we could add a new DELETE endpoint.

I tend to think we should allow deletion of aliases at some point, but that could certainly wait.

**Comment by denis-yuen** [comment]
I prefer the latter. 
That said, come to think of it, is this a 1.7.0 issue ? The zenodo code is creating aliases inside the webservice. Its not like the UI code is creating zenodo entries and PUT/PATCHing new DOIs to tthe webservice. 

Is it possible a fix/if needed should be to the zenodo code in the webservice erasing old aliases as opposed to an endpoint?

**Comment by coverbeck** [comment]
I don't think it's a 1.7.0 issue. The Zenodo integration code just looks for any aliases that are already set, but doesn't prompt for or set them. Only people directly accessing the API run the risk of running into this.

**Comment by denis-yuen** [comment]
Recommend punting to a 1.7.X then, creating

**Comment by denis-yuen** [comment]
Discussion, we may need to do some end-to-end testing, creating multiple zenodo deposits, verify that aliases created are not overwritten

**Comment by denis-yuen** [comment]
Checking in on alias creation via DOIs, it does looks like the old aliases for a workflow aren't overwritten when creating new DOIs (via the Issue DOI option)

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Reconfirmed that previous alias is not overwritten when issuing a second DOI for a different version of the same workflow, and that both aliases work.

I’m going to leave this ticket open, as it’s written up against the API and should be addressed separately, but the concern that our own internal usage of the API would run into this is not a problem.

**Comment by denis-yuen** [comment]
Resurrecting ticket to ensure that our endpoint is functioning as expected (i.e. not overwriting existing aliases unless intended)

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

The code is here: io.dockstore.webservice.resources.AliasableResourceInterface#updateAliases. The code removes existing aliases that are different from the aliases to be added via a PUT. The question is should I change this to be a POST and remove the code that removes existing aliases? However if aliases are deletable then I should add a DELETE endpoint for aliases also?

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

The docs +https://docs.dockstore.org/en/develop/advanced-topics/guid-alias.html+ ( https://docs.dockstore.org/en/develop/advanced-topics/guid-alias.html ) say An alias cannot be removed

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

/Users/waltershands/Documents/UCSC/gitroot/dockstore/dockstore-webservice/src/main/resources/openapi.yaml:2646

swagger.yaml:2420

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

https://github.com/dockstore/dockstore/pull/2948/files ( https://github.com/dockstore/dockstore/pull/2948/files|smart-link )

**Comment by coverbeck** [comment]
Verified on staging API that creating a second alias for an entry does not overwrite the previous alias.

API - 1.8.0-beta.0
