### ISSUE TITLE
Disable Sync with Github button while sync is happening

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2753]
## Bug Report
You can keep requesting to sync with github while a sync is already happening. This button should be disabled like the sync with organization button.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-901)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-901

**Comment by garyluu** [comment]
Is this fixed?

**Comment by denis-yuen** [comment]
@garyluu add a review label if you think #744 fixed it

**Comment by denis-yuen** [comment]
Seems disabled properly on 
API - 1.8.0-beta.0 
UI - 2.5.0-beta.0
