### ISSUE TITLE
Angular training

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2757]
Will preferably be done after 1.7 release. Individuals should have access to training guidelines/tutorials/self-contained projects with the goal of having a complete understanding Angular.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SEAB-386)
┆Issue Type: Story
┆Issue Number: SEAB-386
┆Epic: Retro tickets

**Comment by denis-yuen** [comment]
@melainalegaspi FYI, should be in SEAB

**Comment by cricketsloan** [comment]
➤ On 2019-08-15, Denis Yuen commented:

[~accountid:5ad7afeb1db05e2a66fa947b] 

Please re-open as SEAB (this ticket has no interest for outside users really)
