### ISSUE TITLE
Navigating to a JSON file causes error in console

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2759]
## Bug Report

If you navigate to a JSON file you'll see an error in the browser's console:

```
Loading script from “https://dockstore.org/worker-json.js” with importScripts() was blocked because of a disallowed MIME type (“text/html”).
```

This happens on both production and staging.

I think the ACE editor is making this request. See [this issue](https://github.com/ajaxorg/ace-builds/issues/113)

### Steps to Reproduce

1. Open browser tools
1. Navigate to https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow:2.2.0?tab=files
1. See error in console

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-906)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-906

**Comment by denis-yuen** [comment]
@coverbeck if I understand correctly, there are no ill side-effects aside from the error message?

**Comment by coverbeck** [comment]
> @coverbeck if I understand correctly, there are no ill side-effects aside from the error message?

I see nothing obvious, but it's possible there is some feature/functionality missing that I'm unaware of.

**Comment by garyluu** [comment]
Doesn't happen locally, likely CDN-related issue. `Refused to execute script from 'https://staging.dockstore.org/worker-json.js' because its MIME type ('text/html') is not executable.` because the link is supposed to be https://gui.dockstore.org/2.4.0-rc.0-4930df6/worker-json.js instead

**Comment by denis-yuen** [comment]
Doesn't seem present on staging 
```
API - 1.7.0-rc.1 
UI - 2.4.0-rc.1
```
