### ISSUE TITLE
Document Tool Build Modes

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2760]
### Desired behaviour
1. Update the document on how the tool build modes work.  
2. Change how the tool build modes work so that it's more intuitive.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-907)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-907

**Comment by agduncan94** [comment]
Relevant documentation https://beta.docs.dockstore.org/en/develop/getting-started/dockstore-tools.html?highlight=automated#additional-information-on-build-modes
