### ISSUE TITLE
Fix null aliases in API responses

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2761]
### Desired behaviour
Spun out of #2654 
Currently the response value of aliases is null in requests for a workflow, tool, organization, etc. However, querying directly by alias still returns the corresponding object. So aliases are correctly stores, but improperly displayed in API responses. This is primarily due to lazy loading and will become an issue when we hook up aliases to the UI. Fix should include solution for all object types with aliases.

### Steps to reproduce the behaviour
1. Give an object (ex workflow) an alias via API
2. Query for that alias, response should correctly contain object (workflow)
3. Query directly for that object (by id, path, etc), the value of alias will incorrectly show as null.

### Environment
Persists as of dockstore-webservice-1.7.0-beta.5

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-908)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-908

**Comment by denis-yuen** [comment]
Review pending solution for migration issue (cannot public to create new snapshots)

**Comment by denis-yuen** [comment]
Does not quite seem to work as expected. 
For example 
https://staging.dockstore.org/api/workflows/2327?include=validations%2Caliases
returns an empty aliases object for versions of the workflow

But https://staging.dockstore.org/api/aliases/workflow-versions/foo
gets
```
{
  "fullWorkflowPath": "github.com/Barski-lab/ga4gh_challenge",
  "tagName": "v0.0.2"
}
```

**Comment by garyluu** [comment]
WorkflowVersion aliases weren't a thing until way after this issue was merged

**Comment by denis-yuen** [comment]
Ok, I'll assign to @wshands  to replicate

**Comment by denis-yuen** [comment]
Needs new review as of https://github.com/dockstore/dockstore/pull/3145

**Comment by garyluu** [comment]
1. Gave 'potatoes' alias to workflow 2996
2. Did GET ​/workflows​/{workflowId} with no aliases 
| Test  | Result  |
|---|---|
|  GET ​/workflows​/{workflowId} with nothing  | Aliases show up  |
|  GET ​/workflows​/{workflowId} with 'aliases' | Aliases show up  |
|  GET
​/workflows​/path​/workflow​/{repository} with nothing | Aliases show up  |
|  GET
​/workflows​/path​/workflow​/{repository} with 'aliases' | Aliases show up  |
| GET /workflows/path/workflow/{repository}/published with nothing | Aliases show up |
| GET /workflows/path/workflow/{repository}/published with 'aliases' | Aliases show up |
| GET
​/workflows​/published​/{workflowId} with nothing | Aliases show up | 
| GET ​/workflows​/published​/{workflowId} with 'aliases' | Aliases show up | 

Didn't test tools, aliases option not shown in swagger

**Comment by garyluu** [comment]
Workflows for the 4 workflow endpoints (published/unpublished + path/id)

Also works for getting individual organization

Tools endpoints do not have the option though.

**Comment by garyluu** [comment]
Assuming tool version aliases were not implemented yet.
