### ISSUE TITLE
WDL parsing check for recursive imports catches cases that are not recursive

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2766]
See https://github.com/gevro/gatk4-exome-analysis-pipeline-flat

If you try and register it with the new dockstore WDL 1.0 parsing code, it will say there might be recursive imports. I checked the import structure and this is not true, it is a flaw with our code.

Our current WDL parsing code cannot parse these 1.0 files either, so users cannot publish their valid 1.0 workflows.

From
https://discuss.dockstore.org/t/unable-to-get-publish-button-to-become-active/1972

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-911)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-911

**Comment by denis-yuen** [comment]
@agduncan94 taking a look, let me know if you have code for this already

**Comment by agduncan94** [comment]
@denis-yuen I have the code, it is in https://github.com/dockstore/dockstore/tree/feature/2766/recursive-imports

I still have to write tests, was going to use the one from the discourse discussion.

**Comment by denis-yuen** [comment]
Ah, too late

**Comment by garyluu** [comment]
I can now register https://raw.githubusercontent.com/gevro/gatk4-exome-analysis-pipeline-flat/master/ExomeGermlineSingleSample.wdl
