### ISSUE TITLE
Published workflow has no valid versions

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2767]
Somehow the following workflow is published even though it is considered invalid by Dockstore (it isn't actually invalid).
https://dockstore.org/workflows/github.com/gatk-workflows/gatk4-exome-analysis-pipeline/ExomeGermlineSingleSample:1.1.0?tab=info

I'm wondering if on a refresh a previously valid version became invalid (due to change in parsing code?).

From
https://discuss.dockstore.org/t/unable-to-get-publish-button-to-become-active/1972

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-913)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-913

**Comment by denis-yuen** [comment]
One step forward, was able to use parts of a previous PR to get the workflow to validate. 
However, parsing metadata crashes, investigating

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

A bit confused on how to test this. Should I try forking it and registering on staging to see if it is now valid? Or would I migrate off production and try and refresh it locally to see if it is now fixed?

**Comment by denis-yuen** [comment]
It should be ok to test on staging. 
One idea would be to try a mix of valid/invalid WDL workflows, forked from that workflow. 
Basically if you encounter a situation where we consider something valid but cannot parse metadata (that is present) then that would mean an incomplete fix.
