### ISSUE TITLE
Services appearing in search under workflows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2771]
### Expected behaviour
Since services are in beta, I would expect them to not appear at all. 
Or if we do want them there, they shouldn't be listed under workflows at least. 
### Actual behaviour
They appear on the search page and service is an option on the language facet. And the links are broken anyway
### Steps to reproduce the behaviour 
1. Go to https://staging.dockstore.org/search
2. Can find a service easily by clicking 'service' option in the `Language` facet
(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-914)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-914

**Comment by denis-yuen** [comment]
Services should not be inserted into elastic search at this time
(or ideally should be a different type of object ala tools)

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

‘service’ no longer appears in the Language facet.
