### ISSUE TITLE
Investigate WDL parsing fails to parse some previously verified workflows from draft-2

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2773]
### Expected behaviour
TBD

### Actual behaviour

Hmmm, seeing parse errors with some previously working verified tools.
https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0?tab=files and  https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:2.1.0?tab=files (have to click on WDL tabs while in "My Workflows"
stack traces look like the following, but don't seem to abort the whole refresh (it is still 200 status code)
```
14:33:56
INFO [2019-08-20 14:33:56,887] io.dockstore.webservice.helpers.AbstractImageRegistry: quay.io/pancancer/pcawg-bwa-mem-workflow ICGC-TCGA-PanCancer : Parsing WDL...
INFO [2019-08-20 14:33:56,887] io.dockstore.webservice.helpers.AbstractImageRegistry: quay.io/pancancer/pcawg-bwa-mem-workflow ICGC-TCGA-PanCancer : Parsing WDL...

14:33:56
ERROR [2019-08-20 14:33:56,894] io.dockstore.webservice.languages.WDLHandler: Unable to parse WDL file /Dockstore.wdl

14:33:56
! wdl.draft3.parser.WdlParser$SyntaxError: ERROR: Sibling nodes have conflicting names:

14:33:56
!

14:33:56
! WdlTask defined here (line 1, col 6):

14:33:56
!

14:33:56
! task Seqware_BWA_Workflow {

14:33:56
! ^

14:33:56
!

14:33:56
! WdlWorkflow statement defined here (line 43, col 10):

14:33:56
!

14:33:56
! workflow Seqware_BWA_Workflow {

14:33:56
! ^

14:33:56
!

14:33:56
! at io.dockstore.common.WdlBridge.getBundleFromContent(WdlBridge.scala:322)

14:33:56
! at io.dockstore.common.WdlBridge.getMetadata(WdlBridge.scala:100)
```

Probably need to see if these are legitimate draft-2 WDL only and to mark them as such if need be.

### Environment (Browser or OS and Dockstore version)

API - 1.7.0-beta.5
UI - 2.4.0-beta.4

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-916)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-916
┆Epic: Update cwltool/cromwell 1.7.0

**Comment by denis-yuen** [comment]
Follows https://github.com/dockstore/dockstore/issues/1445

**Comment by denis-yuen** [comment]
womtool-45.jar parses successfully, doesn't validate

**Comment by denis-yuen** [comment]
Interesting, for tools with both CWL and WDL, it is valid as long as one of the two languages is valid
:thinking:

**Comment by denis-yuen** [comment]
https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#versioning

is useful, in particular `Any WDL files which do not have a version field must be treated as draft-2. All WDL files used by a workflow must have the same version.`

**Comment by agduncan94** [comment]
> Interesting, for tools with both CWL and WDL, it is valid as long as one of the two languages is valid
> 🤔

That should be the case, though I thought the UI code would hide the invalid language.

**Comment by cricketsloan** [comment]
➤ Louise Cabansay commented:

Note: come up with strategy to address this problem generally as well (fix might be after 1.7.0, but a help message would be helpful before then)

**Comment by denis-yuen** [comment]
Strategy may need to improve what validation means
Can validate on specific dates, with specific micro service builds, do we fix the specific pcawg workflows for people?

**Comment by denis-yuen** [comment]
@agduncan94 to verify that draft-2 workflows are actually being validated as draft-2, ditto with 1.0

**Comment by denis-yuen** [comment]
@Ldcabansay to determine whether pcawg workflows can (need) to be updated to WDL 1.0

**Comment by agduncan94** [comment]
After playing around with a few different workflows, the code seems to properly choose the right language type (draft-2 vs 1.0)

**Comment by NatalieEO** [comment]
Seems like for 
[bwa-mem](https://dockstore.org/containers/quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0?tab=info) and [sanger](https://dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:2.1.0?tab=info) , just need to changed the task name so that it is not the same and the workflow name 
https://gist.github.com/scottfrazer/0131dc01fb31a451f624d664a9b095bf#fully-qualified-names 

[delly](https://dockstore.org/containers/quay.io/pancancer/pcawg_delly_workflow:2.1.0?tab=info) and [dkfz](https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow:2.2.0?tab=info) don't have wdl parts?

**Comment by denis-yuen** [comment]
Confirmed that https://staging.dockstore.org/my-tools/quay.io/pancancer/pcawg-bwa-mem-workflow has a merged commit https://github.com/ICGC-TCGA-PanCancer/Seqware-BWA-Workflow/pull/24 and this fixes the problem. 
Cannot find an equivalent commit/PR for https://staging.dockstore.org/my-tools/quay.io/pancancer/pcawg-sanger-cgp-workflow which is using  https://github.com/ICGC-TCGA-PanCancer/CGP-Somatic-Docker/blob/develop/Dockstore.wdl

Was a PR accidentally created?

**Comment by denis-yuen** [comment]
FYI, there was a PR to Delly (which is good) but is there a similar PR for Sanger stuck not checked-in as well? Not a blocker for 1.8.0 but need to understand the situation

**Comment by NatalieEO** [comment]
@denis-yuen I was not able to successfully make one for Sanger.

**Comment by denis-yuen** [comment]
Ah ok

**Comment by denis-yuen** [comment]
Actually, was able to edit the path on a specific version to workaround 3180.
Looks good for delly and bwa
