### ISSUE TITLE
Verify CLI use TRS extended

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2776]
### Desired behaviour
Verify command in the CLI should be using the new extended TRS verification (the one with files).
This will require modifications to the flags of the verify command too.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-917)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-917

**Comment by denis-yuen** [comment]
Related to #2384

**Comment by david4096** [comment]
I can confirm that the CLI now implements the verify function made available in TRS and was added with this commit https://github.com/dockstore/dockstore-cli/pull/6/commits/b7a976187f7533668d91635fa0d90df433635cb7
