### ISSUE TITLE
Deprecate Verify WorkflowVersion Webservice Endpoints

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2777]
### Desired behaviour
The Extended TRS verification endpoint should replace the current two verify endpoints in the workflowversion and tag resource.  These two endpoints should be removed to not cause potential issues with the TRS one.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-918)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-918

**Comment by denis-yuen** [comment]
Related to #2384

**Comment by denis-yuen** [comment]
Take a look and update this with current state

**Comment by coverbeck** [comment]
Verified that the `/containers/{containerId}/verify/{tagId}` and `/workflows/{workflowId}/verify/{workflowVersionId}` endpoints are no longer present in the swagger UI on staging.

API - 1.8.0-beta.0 dockstore status indicator
