### ISSUE TITLE
Should not be able to snapshot fileless versions

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2781]
## Bug Report

You shouldn't be able to snapshot a version that has no files.

Perhaps we should only allow snappshotting of valid versions. @denis-yuen -- thoughts?

Note: we also shouldn't allow creation of DOIs for empty versions, but since we can only create DOIs for frozen versions, disallowing snapshots on frozen versions would address that issue.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-920)
┆Issue Type: Story
┆Issue Number: DOCK-920

**Comment by denis-yuen** [comment]
For the question, I don't think our validation is robust enough to be a credible judge of what can be snapshotted/DOIed yet.

**Comment by agduncan94** [comment]
@denis-yuen Even so we should have some basic requirements for snapshots.
Below is a list of ideas in no order
* valid version
* at least a primary descriptor (and dockerfile for tools?)
* author/description (might require parsing which requires valid files)

**Comment by denis-yuen** [comment]
Thinking maybe we split the difference. 
i.e. you need an author and description for DOI creation, but you only need files to snapshot

**Comment by wshands** [comment]
Zenodo requires a file upload to create a DOI. If no author or description is available we just put 'unknown author' and 'no description' in the Zenodo deposit

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified on staging that an error occurs when trying to snapshot a fileless version. API returns 400, and UI displays error

API - 1.7.0-rc.0
UI - 2.4.0-rc.0
