### ISSUE TITLE
My Services page initially shows no services registered when there are

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2782]
## Bug Report

When you navigate to my-services, the page initially says you have no services registered, then displays your services.

Might already be fixed by dockstore/dockstore-ui2#747

### Steps to Reproduce

1. Navigate to https://staging.dockstore.org/my-services
2. Observe the behavior.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-921)
┆Issue Type: Story
┆Issue Number: DOCK-921

**Comment by garyluu** [comment]
Reproduce by blocking https://staging.dockstore.org/api/workflows/shared in browser

**Comment by denis-yuen** [comment]
Fixed as of 2.4.0-beta.5 on staging
