### ISSUE TITLE
Creating DOIs for tool versions not working/weird on swagger

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2785]
### Expected behaviour
If you try to create a DOI for a tool version, it should either fail and give an appropriate error of some kind, or be successful and actually create the DOI. 
### Actual behaviour
When trying to create a DOI for a tool version (not frozen) that's yours, you get a response that looks successful.
![image](https://user-images.githubusercontent.com/16004905/63475058-41a02780-c430-11e9-88a9-3fa14fcbc35c.png)
But no DOI is actually created. You can keep requesting it for the same one and get the same response above.
It does fail appropriately if it doesn't belong to you or it can't find the tool.
### Steps to reproduce the behaviour 
Go to https://staging.dockstore.org/api/static/swagger-ui/index.html#/containertags/requestDOIForToolTag
Try to create a DOI for some tool version

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-922)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-922

**Comment by denis-yuen** [comment]
Note to self: not-actually implementing for 1.7, but should leave a clear path for 1.8

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified on staging that trying to create a DOI for tools returns a 400 status code with the message “DOI creation for tools has not been implemented yet.”

API version: 1.7.0-rc.2
