### ISSUE TITLE
UI should indicate why Publish button is not enabled

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2786]
## Feature Request 

On the My Workflows page, when the publish button is disabled, the UI should at least have a tooltip, maybe more, indicating why.

I have a repo that's not a workflow, and the Publish button is not enabled. I assume because it's not a workflow, but it would nice if there were some indication -- presumably I might run into the issue with repos that are workflows if they don't meet certain (what?) criteria.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-923)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Seabright Sprint 19 Tanker
┆Issue Number: DOCK-923

**Comment by cricketsloan** [comment]
➤ Melaina Legaspi commented:

[~accountid:5d55a9c8c4be040db2d55b8d]
 take a look, and if stuck ping [~accountid:5c47ac5285c9b117bae2f908]

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified working in production

API - 1.7.1
UI - 2.4.0
