### ISSUE TITLE
Tell user to relink account after Zenodo error

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2787]
## Bug Report

If you get a Zenodo error creating a DOI, your Zenodo tokens apparently get revoked. In order for future operations to work you need to relink your Zenodo account.

We should indicate this in the UI after a failure, otherwise all future Zenodo operations will fail.

Also, in case the user ignores said message, and then subsequently tries to publish a DOI, the  unauthorized error displayed  in the UI should include a suggestion to relink the Zenodo account (we do this for Google when the refresh token expires).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-924)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-924

**Comment by denis-yuen** [comment]
> If you get a Zenodo error creating a DOI, your Zenodo tokens apparently get revoked. In order for future operations to work you need to relink your Zenodo account.

What.

**Comment by coverbeck** [comment]
Sounds bizarre to me too, but that's the behavior Walt has seen.

**Comment by agduncan94** [comment]
@coverbeck  Is there an easy way I can cause a Zenodo error?

**Comment by agduncan94** [comment]
I didn't want to believe it but was able to reproduce by doing the following:
1. non-hosted workflow version -> snapshot and add DOI (works)
1. hosted workflow version -> snapshot and add DOI (fails)
1. now I cannot snapshot and DOI another version from the workflow in step 1

This seems to strange to be true, will investigate if this is actually just an error with our code to refresh zenodo tokens (which may be a good solution anyways)

**Comment by coverbeck** [comment]
I think it's probably worth looking at the Zenodo codebase to see; I have a hard time too believing this.

**Comment by agduncan94** [comment]
I am not able to reproduce this locally.

**Comment by coverbeck** [comment]
Are you not able to get the error to happen in the first place, or you are able to get it to happen, but the refresh logic works and subsequent operations work OK?

**Comment by agduncan94** [comment]
I found a way to reproduce easily on staging since the button for doi generation was still visible even after you generated the doi (as long as you don't refresh the page). This didn't cause any issue initially locally, though I could see the error in my console. I somehow manager to get in the error state now though.

**Comment by agduncan94** [comment]
If I comment out the code which refreshes the token on every call, then even after I have an error with the API, the next time I try to use it it still works. So I think we are doing something wrong with how we refresh the token. Maybe zenodo doesn't expect it to be refreshed until it expires.

**Comment by agduncan94** [comment]
If the token expires after an hour, then you get the following 401 error

> {"message":"The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.","status":401}

If you have an error case and then try and issue another doi you get a 500 error

> Could not retrieve sandbox.zenodo.org token based on code

This seems to imply the issue is happening on the Zenodo servers when we do the refresh.

**Comment by denis-yuen** [comment]
What happens if you refresh the token only after `Could not retrieve sandbox.zenodo.org token based on code` as opposed to every call?

**Comment by agduncan94** [comment]
@denis-yuen I think we would only want to do it on 401 errors and not the 500. Refreshing the token after seeing that error message you mentioned just gives the same error.

**Comment by coverbeck** [comment]
1. When we first get the tokens, do we know the access token's expiration? I wonder if their response has that info, although I don't think we have anywhere to store it today. That way you could only request a new token when you know the old one as expired.
2. Or, for Google, what we do is make a call to get user info from the token to see if it's still valid, and if not, request a new one. Don't know if that's possible either.

This is just a brainstorm assuming that requesting access tokens too often is the issue, although it shouldn't be.

**Comment by agduncan94** [comment]
1. The token expires after 1 hour, I'm adding code to not refresh until the db entry is 1 hour old. Hopefully that helps resolve or lessen the frequency of the issue.
2. I'm not sure if this is possible but this is a good idea to look at.

Ya I'm thinking it might be requesting too much that is causing the issues.

**Comment by agduncan94** [comment]
So the issue is that we are using Unit of Work for the endpoint, meaning that we roll back all changes on failure. So say we have initial token AAAA. We try to generate DOI, but first we generate a new token BBBB. The DOI generation then fails, and the database rolls back to what it was before the call, with the token AAAA. The issue is that the token is no longer AAAA, it is now BBBB. So we have lost the new token and are using the old one.

@coverbeck @denis-yuen

**Comment by coverbeck** [comment]
Awesome find! That's a tricky one.

**Comment by denis-yuen** [comment]
Can confirm that token expiry seems much more robust 
Testing the specific failure case is fairly difficult now, will open specific follow-up tickets if needed
