### ISSUE TITLE
Web service logs constantly print out DB session metrics

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2792]
Looking at the webservice logs for the staging and production sites, a set of lines of the form

```
INFO [2019-08-23 17:43:34,611]  org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics  { ... }
```

 are constantly being printed out, making it hard to find actual logs. Would be nice to either reduce the frequency of these logs or make them appear as one line so they can be filtered out by regex.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-926)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-926

**Comment by garyluu** [comment]
Into the Dropwizard configuration file
```
logging:
  loggers:
    org.hibernate: ERROR
```

**Comment by denis-yuen** [comment]
I think the idea is more that our logs should have all the info available, but it should be easy to control the log level via regex like in this tutorial https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html#matching-terms-events

The problem is that these particular logs spread out across multiple lines and thus aren't easily filterable by regex

**Comment by coverbeck** [comment]
In general, unless I haven't discovered it or am using it incorrectly, the UI for searching in CloudWatch seems lacking. You can find things, but then you can't zoom out. E.g., if I look for an error in the logs, I want to see if there are any clues in the logs right before the error.

**Comment by denis-yuen** [comment]
Yeah, its not great as a UI, I like reliability/back-end impl. though
I guess that's why there is stuff like https://github.com/jorgebastida/awslogs

**Comment by coverbeck** [comment]
That looks cool. Will try next time I need to through the logs.

**Comment by garyluu** [comment]
Seems more condensed
