### ISSUE TITLE
Change two service endpoints paths

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2801]
## Feature Request 

The API has the following two endpoints with `path` in them:

* POST /workfows/path/services
* POST /workflows/path/services/upsertVersion

I don't think `path` adds anything, and suggest removing it, leaving either:

* POST /workflows/services
* POST /workflows/services/upsertVersion

Or just make services a top level endpoint:

* POST /services
* POST /services/upsertVersion

Note: If we change this, we need to update the lambda to call the new endpoints.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-932)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 31 Flounder
┆Issue Number: DOCK-932

**Comment by denis-yuen** [comment]
FYI @agduncan94  might be irrelevant with the new endpoint

**Comment by agduncan94** [comment]
Now we have one endpoint which creates associated workflows/services if they do not exist, and then adds/updates a tag/version. I think I call it something like workflows/githubapp/release or something. I am open to suggestions. @coverbeck

**Comment by agduncan94** [comment]
Closing since this is no longer relevant.
