### ISSUE TITLE
Capture some metadata at version level

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2803]
See research write-up from #2634 or Dock-820. Some metadata would make more sense to capture at the version level rather than the overall entry level. Implementation specifics and design choices need to further discussed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-933)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-933

**Comment by garyluu** [comment]
Author, description, email

**Comment by Ldcabansay** [comment]
LGTM, 1.8.0-beta.9
