### ISSUE TITLE
Annoying blue box when typing search term on staging

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2804]
## Bug Report

When entering a search term, a a constraining blue box appears around the text you are typing. This does not happen on production.

Happens in both FireFox and Chrome; only tried on a Mac.

### Steps to reproduce

1. Go to https://staging.dockstore.org/search?searchMode=files
2. Type a search term, e.g., "snap"
3. See blue box around the search term

Or is this on purpose?

![Screen Shot 2019-08-26 at 3 45 51 PM](https://user-images.githubusercontent.com/1049340/63728467-a389d400-c818-11e9-816e-d18c20d9f31b.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-934)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-934

**Comment by denis-yuen** [comment]
:+1:
