### ISSUE TITLE
DAG does not display for WDL workflow on staging

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2805]
## Bug Report

Navigating to the DAG for a workflow results in a "DAG cannot be created because some required tools are missing from Github repo." message instead of displaying the DAG.

Although visible in the UI, this issue is caused by the webservice being unable to generate a DAG.

### Steps to reproduce the behaviour 

1. Navigate to https://staging.dockstore.org/workflows/github.com/HumanCellAtlas/skylab/Snap-ATAC:gl_576?tab=dag

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-936)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-936

**Comment by denis-yuen** [comment]
Functional with 2.4.0-rc.0 on staging
