### ISSUE TITLE
UI displays error message while webservice calculating DAG

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2806]
## Bug Report

If you navigate to the DAG tab of a WDL file, the page immediately says "DAG cannot be created..." even if the webservice/UI is subsequently able to display the DAG.

The message should only be displayed once it has been determined that Dockstore really can't display the DAG.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-935)
┆Fix Versions: Dockstore 1.7.x
┆Issue Number: DOCK-935
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Looks good, staging with
```
API - 1.7.0-rc.1 
UI - 2.4.0-rc.1
```
