### ISSUE TITLE
Targetted refresh when setting default version

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2808]
### Desired behaviour

Setting the default branch/version in the UI also triggers a refresh (by choice) of the workflow for all versions.
This was to ensure that the most recent data was pulled in for metadata (author, description, etc.). 

However, especially with GitHub apps, this becomes less necessary. 
It would be more intuitive/performant to just refresh the one (default) version that is set.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-937)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-937

**Comment by denis-yuen** [comment]
FInd out if this even makes sense anymore, otherwise close

**Comment by agduncan94** [comment]
I believe @garyluu update to the UI makes this not make sense anymore. On initial addition of a version we now pull description, author, etc. Changing the default version would therefore not need a refresh since the metadata is already pulled for every version.

Gary can you confirm?

**Comment by garyluu** [comment]
Just checked on dev.dockstore.net, seems to not do a refresh anymore

**Comment by agduncan94** [comment]
Ok cool, I will close this ticket.
