### ISSUE TITLE
Tooltip for workflow mode shows [object object]

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2813]
If you hover over the Mode label in the info tab of a workflow, it will display [object object]. It should display some predefined HTML, but it seems to be failing to display it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-940)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-940

**Comment by denis-yuen** [comment]
note to self: fix added after 2.4.0-rc.0

**Comment by denis-yuen** [comment]
It's back
