### ISSUE TITLE
Use womtool to detect imports

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2817]
### Desired behaviour

We should use this to simplify our import parsing
https://github.com/broadinstitute/cromwell/releases/tag/45
Possibly recursive import checks

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-944)
┆Epic: Live tally of compatible workflows
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-944
┆Sprint: Sprint 65-Pyjama shark
┆Issue Type: Story

**Comment by garyluu** [comment]
womtool requires the actual files in a directory to figure out what all the imports are, which will need us to fetch the files in another external service for various reasons.  Blocked until we move our parsing code to external service.

**Comment by denis-yuen** [comment]
Think this was put into review accidentally based on last comments

**Comment by garyluu** [comment]
No, it's in review. The issue is use womtool to detect imports. Other tickets like DAG were created https://ucsc-cgl.atlassian.net/browse/SEAB-3112
