### ISSUE TITLE
Detect http(s) imports in CWL

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2819]
## Feature Request 

The CGC PR, dockstore/dockstore-ui2#766, is now calling [hasHttpImports$](https://github.com/dockstore/dockstore-ui2/blob/134232f2c0e2027f20e0cb56d8b99fd8a19585f3/src/app/workflow/launch-third-party/launch-third-party.component.ts#L124), which only "works" for WDL.

Update it to detect CWL http(s) imports as well.

Note: The current implementation is currently a crude regex test in the UI for WDL, and will probably continue to be so for CWL. Ideally we should have the webservice determine this, but I feel this is beyond the scope of getting this feature into the 1.7 release.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-945)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-945
┆Epic: Launch-with Support

**Comment by denis-yuen** [comment]
Oh I see, if not disruptive would be nice to get UI checking in 1.7, webservice in 1.8. 
It seems hard though

**Comment by agduncan94** [comment]
This seems like a good use case for adding to a lambda related to validation of tools/workflows.

**Comment by denis-yuen** [comment]
One for each language even

**Comment by agduncan94** [comment]
This doesn't work with the following workflow since the import is done with the run https://github.com/dockstore-testing-organisation/md5sum/blob/http/checker_workflow_wrapping_tool.cwl. I think we just need to add run to the regex

**Comment by coverbeck** [comment]
Do we know for sure that this won't run on on CGC?

**Comment by agduncan94** [comment]
@coverbeck I did not try since I forgot my credentials, I have the workflow at https://staging.dockstore.org/workflows/github.com/dockstore-testing-organisation/md5sum:http?tab=info

**Comment by agduncan94** [comment]
I tried with the above workflow version and I get the error "App could not be imported."

**Comment by agduncan94** [comment]
Fixed on staging 1.7.0-rc.2 and 2.4.0-rc.2

**Comment by cricketsloan** [comment]
➤ Melaina Legaspi commented:

[~accountid:5a2091b90dd5cd50523f734e] please create another ticket for this and link to https://ucsc-cgl.atlassian.net/browse/DOCK-957
