### ISSUE TITLE
Update readthedocs for CWL 1.1

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2820]
### Desired behaviour

https://beta.docs.dockstore.org/en/develop/getting-started/getting-started.html  should reflect CWL 1.1 (should also run through tutorial to ensure it still works)

Also https://beta.docs.dockstore.org/en/develop/advanced-topics/best-practices/best-practices.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-949)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-949
┆Epic: Update cwltool/cromwell 1.7.0

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

This statement could include ‘GCS' as one of the URL types.

Tip

The Dockstore CLI can handle inputs with HTTPS, FTP, and S3 URLs but that’s beyond the scope of this tutorial.
