### ISSUE TITLE
Update readthedocs for WDL 1.0

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2821]
### Desired behaviour

https://beta.docs.dockstore.org/en/develop/getting-started/getting-started.html should reflect WDL 1.0 (should also run through tutorial to ensure it still works)

Possibly https://beta.docs.dockstore.org/en/develop/advanced-topics/best-practices/wdl-best-practices.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-948)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-948
┆Epic: Update cwltool/cromwell 1.7.0

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

https://docs.dockstore.org/en/develop/getting-started/getting-started-with-wdl.html ( https://docs.dockstore.org/en/develop/getting-started/getting-started-with-wdl.html ) → second example (dockstore-tool-bamstats) is missing the version 1.0

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

https://docs.dockstore.org/en/develop/advanced-topics/best-practices/wdl-best-practices.html ( https://docs.dockstore.org/en/develop/advanced-topics/best-practices/wdl-best-practices.html ) → not using WDL 1.0
