### ISSUE TITLE
Create documentation for DOI and snapshots

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2822]
### Desired behaviour
Need documentation for DOI and snapshotting
Should cover

- what it means to snapshot
- what it means to create a DOI
- what users can do to make their DOI better (provide description, metadata)
- what we will likely add as future work (pull in imports, link ORCID, etc.)

Should look akin to 
https://beta.docs.dockstore.org/en/develop/advanced-topics/sharing-workflows.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-947)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-947
┆Epic: Create DOIs

**Comment by cricketsloan** [comment]
➤ Melaina Legaspi commented:

merge dock-402 descriptions
