### ISSUE TITLE
Launch-with documentation for Seven Bridges

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2823]
### Desired behaviour

Should look akin to https://beta.docs.dockstore.org/en/develop/end-user-topics/terra-launch-with.html 
Check in  with Seven Bridges to see if we can update the homepage footer to include them as well as a "works with"
Don't forget the https://beta.docs.dockstore.org/en/develop/end-user-topics/language-support.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-946)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-946
┆Epic: Launch-with Support

**Comment by denis-yuen** [comment]
Launch-with doc looks good to Seven Bridges

**Comment by denis-yuen** [comment]
Language support table still needs update

**Comment by garyluu** [comment]
> Language support table still needs update

Still true
