### ISSUE TITLE
Changelog  migration guide

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2826]
### Desired behaviour

Start working on an overall upgrade / migration guide for users
Should include

- breaking changes
- prominent improvements
- highlight what users will need to do to migrate

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-950)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-950

**Comment by denis-yuen** [comment]
Will need to follow-up with final Google Doc to readthedocs migration

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Placeholder is still at https://docs.dockstore.org/en/develop/news/2019-09-26-Dockstore-1.7.0.html ( https://docs.dockstore.org/en/develop/news/2019-09-26-Dockstore-1.7.0.html )
