### ISSUE TITLE
change the GitHub, quay.io, Docker Hub links to b/w icons

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2827]
### Desired behaviour

To save space for the tables, change the GitHub, Quay.io, Docker Hub links to b/w icons

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-953)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-953

**Comment by agduncan94** [comment]
Works on 2.5.0-alpha.0
