### ISSUE TITLE
Review AWS cloudbuild

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2829]
Take a look at AWS cloudbuild

Estimate cost/benefit, see what tasks can appropriately be spun off to this to save developer time

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/DOCK-955)
┆Issue Type: Task
┆Issue Number: DOCK-955
┆Epic: Speed up Builds

**Comment by denis-yuen** [comment]
Re-create in seab
