### ISSUE TITLE
Request entity too large when snapshotting

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2833]
## Bug Report

This is #2762 again. It got reintroduced by the refactoring of snapshot/DOI code.

The method `updateWorkflowToSnapshot`, where the fix for #2762 was applied, is no longer invoked. If the new fix continues to not use that method, then that method can be deleted.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-958)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-958

**Comment by agduncan94** [comment]
Not able to reproduce with webservice 1.7.0-rc.1 and UI 2.4.0-rc.1
