### ISSUE TITLE
Add CLI option for Cromwell config file

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#2835]
The option to use Singularity, and potentially other interesting features of Cromwell, are set in a config file. When running a workflow with Cromwell the configuration is included like this:
`java -Dconfig.file=/path/to/config -jar cromwell.jar workflow.wdl`

Currently there is no way to set the Cromwell configuration used by the dockstore CLI. It would be nice if there was an option for this analogous to `cwltool-extra-parameters` in ~/.dockstore/config, although it would be even better if both were available as command line arguments.

Reference:
https://cromwell.readthedocs.io/en/stable/tutorials/Containers/#singularity 
https://cromwell.readthedocs.io/en/stable/Configuring/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-960)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-960
┆Epic: Improve Cromwell Support

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

[~accountid:5c118bd3e91d16692a3a3ae8] Should we add a section to the Dockstore config file e.g. \[CROMWELL] as we did for WES?

Also should we allow the Cromwell options to the Dockstore command line? This would be good but will be more complicated and will require us to allow Dockstore command line Cromwell options to take precedence over the Cromwell options in the Dockstore config file.

**Comment by garyluu** [comment]
I get:
```
Executing: java -Dconfig.file=/Users/waltershands/cromwell.conf -Dfoo -jar /home/gluu/.dockstore/libraries/cromwell-45.jar run --inputs /tmp/foo8710753221380909602json -t WDL /home/gluu/dockstore-cli/dockstore-client/target/Dockstore.wdl

```
