### ISSUE TITLE
Determine way to harvest Docker checksums

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2837]
### Desired behaviour

Possible lead https://stackoverflow.com/questions/39375421/can-i-get-an-image-digest-without-downloading-the-image

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-963)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Sprint 21 Viking vessel
┆Issue Number: DOCK-963

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

This document describes a few ways of getting digest information for docker images from Quay and Docker Hub

https://docs.google.com/document/d/1c9fRVfq0uVAbpJa3Aq6bgIWOEZUt4U2UrnSfcUrXmhU/edit# ( https://docs.google.com/document/d/1c9fRVfq0uVAbpJa3Aq6bgIWOEZUt4U2UrnSfcUrXmhU/edit#|smart-link ) 

And a little shell script to do the same:

https://gist.github.com/david4096/26485d3c62793e0ae50167e0fcaebbb5 ( https://gist.github.com/david4096/26485d3c62793e0ae50167e0fcaebbb5 )
