### ISSUE TITLE
Update to TRS 2.0 final

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2838]
### Desired behaviour

Update to https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/2.0.0-beta.5
(hopefully)

May need to provide a https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/2.0.0-beta.2 fallback mode.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-962)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-962

**Comment by NatalieEO** [comment]
There is one failure when doing http://142.1.177.188:8080/trs/validator/debug?url=https://dev.dockstore.net/api

Beginning of error
```
info: Displaying failed tests...
fail: GET (200) /api/ga4gh/v2/tools?limit=30 duration: 8671ms
fail: headers: At '/self_link' Missing required property: self_link
headers: At '/current_limit' Missing required property: current_limit
headers: At '/last_page' Missing required property: last_page
...
```

**Comment by denis-yuen** [comment]
Heads-up, `/api/ga4gh/v2` looks like trs v2 beta
`/api/ga4gh/trs/v2` should be trs v2 final, the above looks like it was validating beta (which is definitely good to do), but we also need to validate the final

**Comment by garyluu** [comment]
hmm...i may or may not have overwritten the base path manually

**Comment by garyluu** [comment]
Issue title doesn't quite match description
