### ISSUE TITLE
EPAM WDL Visualizer cannot display DAG for some workflows

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#2839]
## Bug Report
EPAM WDL Visualizer cannot display DAG  for WDL 1.0 workflow https://staging.dockstore.org/workflows/github.com/wshands/hmmer-docker:1.0.0?tab=dag

### Expected behaviour
Should display DAG

### Actual behaviour
Error message: EPAM WDL Visualizer was unable to visualize this workflow. It returned the following error:
Finished parsing without consuming all tokens.

### Steps to reproduce the behaviour 
Go to https://staging.dockstore.org/workflows/github.com/wshands/hmmer-docker:1.0.0?tab=dag
Click on EPAM WDL Visualizer radio button

### Environment (Browser or OS and Dockstore version)
https://staging.dockstore.org/api/static/swagger-ui/index.html#
https://github.com/dockstore/dockstore-ui2/releases/tag/2.4.0-rc.0
Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS Mojave
![Screen Shot 2019-09-01 at 3 48 31 PM](https://user-images.githubusercontent.com/3650921/64083214-b1d06800-ccd0-11e9-8e59-44501c2bd907.png)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-964)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-964
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by coverbeck** [comment]
I had logged one issue, epam/pipeline-builder#56, although it is a different error.

**Comment by melainalegaspi** [comment]
@coverbeck: "EPAM builder removed until they support WDL 1.0; reopen if support ever added."
