### ISSUE TITLE
Descriptor file does not display for specific checker workflow

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#2843]
## Bug Report
Descriptor file does not display for checker workflow

### Expected behaviour
Should see descriptor workflow

### Actual behaviour
No descriptor displayed

### Steps to reproduce the behaviour 
Go to https://staging.dockstore.org/my-workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_freeze8_WDL_wdl_checker

### Environment (Browser or OS and Dockstore version)
https://staging.dockstore.org/api/static/swagger-ui/index.html#
https://github.com/dockstore/dockstore-ui2/releases/tag/2.4.0-rc.0
Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS Mojave

![Screen Shot 2019-09-03 at 4 39 31 PM](https://user-images.githubusercontent.com/3650921/64215403-73ba7c00-ce69-11e9-93c9-60958e4d8cb1.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-967)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-967

**Comment by denis-yuen** [comment]
Looks like URL for users without access is https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_freeze8_WDL_wdl_checker:feature/freeze8-wdl?tab=info

Looks like the workflow path is wrong ` /topmed-workflows/variant-caller/variant-caller-wdl-checker/freeze_8/topmed_freeze8_caller_checker.wdl ` should probably be `/variant-caller/variant-caller-wdl-checker/freeze_8/topmed_freeze8_caller_checker.wdl`

**Comment by wshands** [comment]
Fixed the workflow path, but still cannot seem to get a valid feature/freeze8 version

**Comment by wshands** [comment]
Tested on my local instance and everything worked OK. Somehow I may have corrupted a DB entry on staging?

**Comment by denis-yuen** [comment]
Tested with a copy of staging's DB or testing from scratch?

**Comment by garyluu** [comment]
Mysteriously dies on the first `Looking at reference` that isn't followed by:
```
ERROR [2019-09-06 21:23:10,917] io.dockstore.webservice.helpers.GitHubSourceCodeRepo: DataBiosphere: IOException on readFileFromRepo {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}
```

**Comment by denis-yuen** [comment]
to speed things up, can delete excess branches and tags

**Comment by garyluu** [comment]
Error message shows it's using draft-3 languageFactory even though it's draft-2 (https://raw.githubusercontent.com/DataBiosphere/topmed-workflows/feature/freeze8-wdl/variant-caller/variant-caller-wdl-checker/topmed_freeze3_calling_checker.wdl)

**Comment by garyluu** [comment]
womtool validate shows that it's valid

**Comment by agduncan94** [comment]
Was not able to reproduce locally. On staging, was able to reproduce from the same repo, from a forked version of the repo, and from a hosted version.

**Comment by agduncan94** [comment]
I tried making a version without http imports and I get the following error (again only on staging)

`WDL file is malformed or missing , cannot extract metadata`

**Comment by agduncan94** [comment]
This PR gets this valid https://github.com/dockstore/dockstore/pull/2941

**Comment by agduncan94** [comment]
Seems like the workflow the checker calls is now valid, but the checker workflow still has an error.

**Comment by melainalegaspi** [comment]
Appears to work
