### ISSUE TITLE
Improve successful Snapshot/DOI generation message and refresh

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2845]
### Desired behaviour

After a Snap/DOI is successfully created, the UI should:

- automatically refresh and update display snapshot/DOI icons, 
- hide relevant action from column
- and update the relevant information on info tab (DOI)
- should also show DOI in success message

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-969)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-969

**Comment by denis-yuen** [comment]
@david4096 let me know if this is too divergent from your current work, assigning it to you for now under the assumption it is fairly similar
