### ISSUE TITLE
missing metadata for verified tools

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2851]
### Expected behaviour

Same metadata as production

### Actual behaviour

Some verified tools are missing metadata comparing staging to production

prod
![Screenshot from 2019-09-05 11-47-56](https://user-images.githubusercontent.com/1730679/64357684-1e9a7980-cfd3-11e9-9e11-52974d9e7030.png)

staging
![Screenshot from 2019-09-05 11-47-58](https://user-images.githubusercontent.com/1730679/64357686-20643d00-cfd3-11e9-97c1-cf5f0db3486f.png)

### Steps to reproduce the behaviour 

Might be related to #2773 but note that that should be for WDL whereas the metadata shown should be from CWL

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-973)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-973

**Comment by garyluu** [comment]
Hmm...refreshing removes the metadata

**Comment by denis-yuen** [comment]
Metadata retained on staging 
```
API - 1.7.0-rc.1 
UI - 2.4.0-rc.1
```
