### ISSUE TITLE
Documentation Sidebar Suggestions

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2853]
## Feature Request 

Random observations on the sidebar, referring to the readthedocs version:

*  Getting started guide section has `Dockstore Tools`, `Dockstore Workflows`, but `Getting Started with Dockstore Services`. Suggest they all be the same, and lean towards getting rid of `Getting Started`, as it's already in the Getting Started section, and repetition is... repetitive. OTOH there are other elements with `Getting Started`, e.g., `Getting Started with Docker`, where that somehow makes more sense.
* `Alias` should probably be `Aliases`.
* Torn on this, but wonder if we shouldn't have another nested level, visible by default. Instead of having DNAstack Launch-With, DNANexus Launch-With, etc., maybe have something like `Launch-With` (although see next item) with children DNAstack, DNANexus, etc.
* Don't like `Launch-With` :), especially the hyphen
* Suggest topics be semi-alphabetical, otherwise it's hard to find things. Exceptions, which is why I say "semi-alphabetical": the `Intro` for each section, and the Getting Started section is in a logical order.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-974)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-974

**Comment by denis-yuen** [comment]
Is it possible to change titles without changing links?

**Comment by agduncan94** [comment]
@denis-yuen yes, the names of the pages come from the main title within the document, the links come from the names.

**Comment by agduncan94** [comment]
1. I agree, should change to Dockstore Services.
2. Agree
3. I like this idea too
4. I also dislike the hyphen
5. Sort of agree, though as you say it is a bit hard. Things like best practices should be grouped together, but they all start with different characters.

**Comment by david4096** [comment]
I can confirm that the current `develop` docs at dockstore.readthedocs.org includes these changes. There will have to be a specific release of the docs so that that URL links to the currently released version, I believe.
