### ISSUE TITLE
Getting Started with CWL should link to onboarding

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2855]
## Feature Request 

The Getting Started with CWL doc page should link to onboarding for installing CWL tool. I have been using Dockstore for a while, but don't typically do CWL; when I needed to, I went to the Getting Started with CWL page, which links to the CWL page, which when you follow the instructions, has you install the latest CWL runner.

This will not be the "blessed" CWL runner that Dockstore has been tested with.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-976)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-976

**Comment by NatalieEO** [comment]
Cwl tutorial does link to onboarding on dockstore.
