### ISSUE TITLE
Order of launch instructions seems out of order

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2856]
## Bug Report

The instructions for running a checker workflow are in reverse order; they first tell you how to run the checker workflow, then they tell you how to create a template JSON for running the checker.

Also, the instructions for generating a template JSON show `> Dockstore.json`, but the instructions for running show `--json checkparam.json`. The names should be the same, and I suggest checkparam.json as the name, because the instructions for the workflow itself already use Dockstore.json. Following the instructions I ended up overwriting my original Dockstore.json, which I would have just as soon kept.

### Steps to Reproduce

1. Go to https://staging.dockstore.org/workflows/github.com/dockstore-testing/md5sum-checker:develop?tab=launch
2. See the last two instructions on the page, starting with `Run a checker workflow with: `

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-977)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-977

**Comment by agduncan94** [comment]
Fixed as of 2.6.0-rc.0.
