### ISSUE TITLE
Add order/drag & drop feature to workflow collections

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#2859]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Feature Request 
It would be nice to be able to order workflows in a collection using a drag and drop feature (or something else) so that the end user would understand the flow of the analysis. Even when I add workflows in the order I want, they are displayed in a different order. Thanks!

### Steps to reproduce the behaviour 

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-978)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-978
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Duplicates https://github.com/dockstore/dockstore/issues/4510
