### ISSUE TITLE
Investigate CLI 1.6.0 client connection compatibility with 1.7.0 server

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2860]
#1451 Bug Report

### Expected behaviour
Dockstore 1.7.0 CLI should be able to pull workflows from both 1.6.0 and 1.7.0 servers. Note: should also test if 1.6.0 CLI can connect to 1.7.0 server (to do).

Edit should be: 
Dockstore 1.6.0 CLI should be able to pull workflows from both 1.6.0 and 1.7.0 servers. 
Dockstore 1.7.0 CLI should be able to pull workflows from 1.7.0 server

### Actual behaviour
The latest Dockstore CLI (Dockstore version 1.7.0-beta.3) can only download workflows when config is pointing to the staging server. Otherwise workflow is not found:

```
[main] ERROR io.dockstore.client.cli.ArgumentUtility - No workflow found with path github.com/dockstore-testing/md5sum-checker
```

### Steps to reproduce the behaviour:
1. Update to dependencies for 1.7.0 (2nd page of account set-up:  https://staging.dockstore.org/onboarding)
2. Upgrade to latest version of Dockstore (should be 1.7.0-beta.3) : 
`dockstore  --upgrade-unstable`
3. set ~/.dockstore/config to point to 1.6.0 server:  
```
server-url: https://dockstore.org/api
```
4. Try running a non-local workflow:

```
dockstore workflow launch --entry github.com/dockstore-testing/md5sum-checker:develop --json Dockstore.json
```
To run workflow create the following files:

- Dockstore.json:
```
{
  "input_file": {
        "class": "File",
        "path": "md5sum.input"
    }
}
```
- md5sum.input:
```
this is the test file that will be used when calculating an md5sum
```

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)
Dockstore CLI: 1.7.0-beta.3
Java 11, CWL1.1 with python 3 requirements

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-979)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-979

**Comment by Ldcabansay** [comment]
Alternatively, if you don't want to update CWL dependencies, you can run the WDL version with the same test files as above, should still get can't find workflow error. 
```
dockstore workflow launch --entry github.com/briandoconnor/dockstore-workflow-md5sum/dockstore-wdl-workflow-md5sum:1.2.0 --json Dockstore.json
```

**Comment by denis-yuen** [comment]
Crummy, this looks like it arose from the language refactoring I did. 
In particular, descriptorType changed from a String to an Enum, flipping the case in the JSON
Compare https://staging.dockstore.org/api/workflows/path/workflow/github.com%2Fh3abionet%2Fh3agatk/published?services=false with https://dockstore.org/api/workflows/path/workflow/github.com%2Fh3abionet%2Fh3agatk/published?services=false

**Comment by NatalieEO** [comment]
Hmm @denis-yuen , I'm still reproducing the same error reported in this ticket.
Dockstore version 1.7.0-rc.2
cwltool 1.0.20190621234233
java 11

**Comment by denis-yuen** [comment]
To be clear, are you seeing an issue with a 1.6.0 client talking to staging (1.7.0) or are you seeing an issue with a 1.7.0 client talking to production (1.6.0)?

The fix is only for the former situation and I should fix the issue description to make it clear that we don't expect backwards compatibility

**Comment by NatalieEO** [comment]
Ohhh okay, I see. Thanks for clearing that up. Yeah I was only testing the latter.

**Comment by NatalieEO** [comment]
1.6.0 client can talk to staging and still launch workflows.
