### ISSUE TITLE
Make default size of edit description for collections/organizations bigger

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2864]
## Feature Request 

![image](https://user-images.githubusercontent.com/16004905/64562398-c67cb380-d301-11e9-9567-e449e534f6c7.png)

The default size is too small. Should be bigger by default.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-983)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 25 Zille
┆Issue Number: DOCK-983

**Comment by garyluu** [comment]
Still starts with about one line, but at least it autosizes now.
