### ISSUE TITLE
Services table should drop "Format" column

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2867]
## Feature Request 
Since the format of a service is always "SERVICE", AFAIK, it serves no purpose and takes up extra space. Suggest that column be removed.

Goto https://staging.dockstore.org/services

![Screen Shot 2019-09-09 at 4 17 59 PM](https://user-images.githubusercontent.com/1049340/64572763-8c210f80-d31d-11e9-80e0-0dfb0fb5d68a.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-984)
┆Epic: Dockstore  My Services
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-984
┆Sprint: 131 - Dejima
┆Issue Type: Story

**Comment by denis-yuen** [comment]
In the future, this would probably be mapped to subclass for services
