### ISSUE TITLE
Dockstore TRS API does not support toolClass query parameter

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2868]
## Bug Report

The TRS API has a `toolClass` [query parameter](https://github.com/ga4gh/tool-registry-service-schemas/blob/0d99c7cf7bd01a7b80d82a4fc34b2181cb3b33c1/openapi/ga4gh-tool-discovery.yaml#L144), but it is not surfaced in the Dockstore API https://staging.dockstore.org/api/static/swagger-ui/index.html#/GA4GH/toolsGet

Also, the [Swagger UI](https://staging.dockstore.org/api/static/swagger-ui/index.html#/l) says Dockstore implements version 2.0.0-beta.2 of the API, but in the pom.xml we are pointing to 2.0.0-5.beta.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-985)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-985

**Comment by coverbeck** [comment]
Look like dockstore/tool-registry-service-schemas is behind ga4gh/tool-registry-service-schemas; the dockstore-webservice/pom.xml points to the former. Not sure how this is supposed to work.

It is confusing because release 2.0.0-beta.5 in the dockstore org does **not** have the toolClass query parameter, but release 2.0.0-beta.5 in the ga4gh org **does** have the parameter.

**Comment by denis-yuen** [comment]
See also #2838

**Comment by coverbeck** [comment]
Verified on dev.dockstore.net
