### ISSUE TITLE
Get published services x-total-count incorrect

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2870]
### Expected behaviour
The https://staging.dockstore.org/api/workflows/published?offset=0&limit=10&filter=&sortCol=stars&sortOrder=desc&services=true should return a response header x-total-count of 9 or so

### Actual behaviour
The https://staging.dockstore.org/api/workflows/published?offset=0&limit=10&filter=&sortCol=stars&sortOrder=desc&services=true should return a response header x-total-count of 317 or so

### Steps to reproduce the behaviour 
1. Go to https://staging.dockstore.org/services
2. Look at the pagination total services count

### Environment (Browser or OS and Dockstore version)
Webservice:  1.7.0-rc.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-986)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Issue Number: DOCK-986
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10183/Screen+Shot+2019-09-16+at+3.28.37+PM.png">Screen Shot 2019-09-16 at 3.28.37 PM.png</a>

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Went to https://staging.dockstore.org/services ( https://staging.dockstore.org/services ). Saw pagination total services count of 10. 

!Screen Shot 2019-09-16 at 3.28.37 PM.png|width=998,height=257!

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Also saw 10 dockstore.yml services files returned by https://staging.dockstore.org/api/workflows/published?offset=0&limit=10&filter=&sortCol=stars&sortOrder=desc&services=true ( https://staging.dockstore.org/api/workflows/published?offset=0&limit=10&filter=&sortCol=stars&sortOrder=desc&services=true )
