### ISSUE TITLE
Owner can't see hidden tag's test parameter files

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2871]
### Expected behaviour
If I'm the owner of a tool/workflow.  I can see all the test parameter files of all versions (even hidden ones)

### Actual behaviour
The endpoint that gets test parameter files says `Invalid or missing tag v1.0.0.`.

### Steps to reproduce the behaviour 
- Go to https://staging.dockstore.org/my-workflows/github.com/dockstore/hello_world (hopefully you have access and version v1.0.0 is still hidden from my testing)
- Go to versions tab
- Open up developer tools
- Click edit on the version v1.0.0 
There is now an errored out get-test-parameter-file-request in the network tab

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-987)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 19 Tanker
┆Issue Number: DOCK-987

**Comment by garyluu** [comment]
This also happens in production

**Comment by denis-yuen** [comment]
:cry:

**Comment by NatalieEO** [comment]
@garyluu The request in the network is successful following your steps, but I can't actually see the test parameter or descriptor files under the Files tab. Staging and production

**Comment by garyluu** [comment]
interesting

**Comment by NatalieEO** [comment]
Seems to be fixed 
API - 1.8.0-beta.0
UI - 2.5.0-beta.0
