### ISSUE TITLE
Docker CLI needs mechanism to pass extra docker params

### ISSUE THREAD

**Issue by briandoconnor** [dockstore/dockstore#288]
CWLTools needs a patch to, need to discuss

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-446)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-446
┆Sprint: Backlog
┆Issue Type: Story

**Comment by briandoconnor** [comment]
Jake at UCSC can probably work on this.  We should patch the CWL 1.0 version and issue a pull request.  This is related to #324

**Comment by denis-yuen** [comment]
Required for https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow

**Comment by denis-yuen** [comment]
Note to self, we have a mechanism to pass extra cwltool params as documented at https://staging.dockstore.org/docs/advanced-features#running-cwl-runner-with-extra-tags but we still have no solution to bypass cwltool and inject extra parameters to the `docker run`  command
