### ISSUE TITLE
Registering a workflow on staging will show duplicate types

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2895]
I went onto staging and tried to manually add a new remote workflow. I see duplicated descriptor types.
![Screenshot from 2019-09-16 09-28-37](https://user-images.githubusercontent.com/6331159/64961864-5ff91780-d864-11e9-987b-7b929b989066.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-997)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-997

**Comment by garyluu** [comment]
`curl 'https://staging.dockstore.org/api/metadata/descriptorLanguageList'`
returns 5 things

**Comment by denis-yuen** [comment]
Hmm, probably an unintended side-effect of https://github.com/dockstore/dockstore/issues/2860

**Comment by coverbeck** [comment]
@ByteMap I wonder if this is the same issue we saw during your Friday demo? Maybe try #2896 a try locally to see if it addresses your problem.
