### ISSUE TITLE
Update webserver/ui cwl dependency check to python 3

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2897]
### Expected behaviour
We have 2 places where we hardcode the python dependency for cwltool. In the webservice its in CWLToolWrapper.java and for the UI in downloadcliclient.component.ts. This should be set to python3 for 1.7.0

### Actual behaviour
Currently set to python 2, but I don't think it actually stops anything if not python2 (might just check if  python2 is installed, not  if default  python)

### Environment (Browser or OS and Dockstore version)
API - 1.7.0-rc.2 
UI - 2.4.0-rc.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-998)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-998

**Comment by denis-yuen** [comment]
This is grabbing the list of dependencies and then checking on specifically cwltool and schema-salad, which are the same between python 2 and 3. So this had no real effect, looks like the same for the GUI

**Comment by agduncan94** [comment]
So is this ticket just changing it to 3 in all places it occurs, even though it has no real impact?

**Comment by agduncan94** [comment]
Also note that CWLToolWrapper.java is now in the Dockstore client.

**Comment by denis-yuen** [comment]
I think the idea is one should enter the onboarding wizard and exit with an install of the dockstore cli using cwltool using Python 3. However, it looks like above when I tried it, the specific version of cwltool and schema-salad used was the same for both python 2 and python 3, so watch out for that

**Comment by agduncan94** [comment]
Ok I see. Do you mean it seems like we don't have to update the requirements.txt with newer versions of schema salad and what not?

**Comment by denis-yuen** [comment]
In September, I think I was under that impression.
Now with Python 2 officially dead, it might be a good idea to spin up a Ubuntu VM, explicitly delete all of Python 2, and see whether installing a CLI, launching a workflow works all via Python 3.

**Comment by agduncan94** [comment]
@denis-yuen I tried running with venv with python set to version 3 and it looks like they are working. Is that ok?

**Comment by denis-yuen** [comment]
I don't know. 
https://xkcd.com/1987/

Nuke the entire site from orbit, it's the only way to be sure.

**Comment by agduncan94** [comment]
I have created a ubuntu vm with only python 3 installed. I have installed the Dockstore CLI and have run a basic md5sum workflow and it works.

**Comment by coverbeck** [comment]
Ran https://staging.dockstore.org/workflows/github.com/denis-yuen/hello-dockstore-workflow/hello-world:1.2?tab=launch from within a Python3 virtual env and it works.

Dockstore CLI: 1.8.0-beta.2
API:  1.8.0-beta.9
