### ISSUE TITLE
CWL/WDL format is displayed twice in tools tab

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#2898]
### Expected behaviour

CWL/WDL should only appear once in the Format column

### Actual behaviour

- CWL/WDL repeats itself once in the Tools Tab for the homepage and search page
- When inspecting the page: Under network tab, a file 'published' shows that the descriptor type contains a duplicate format.

<img width="828" alt="Screen Shot 2019-09-16 at 11 45 32 AM" src="https://user-images.githubusercontent.com/42463687/64985036-dacc2d80-d878-11e9-838d-8fd61d1d8437.png">
<img width="498" alt="Screen Shot 2019-09-16 at 11 48 42 AM" src="https://user-images.githubusercontent.com/42463687/64985102-f8999280-d878-11e9-99e9-2ce6d0e33af3.png">

### Steps to reproduce the behaviour 

1. Go to your local host or staging.dockstore.org
2. Travel to the homepage or the search page and stay in the Tools tab
3. Bug should be visible in the Format column

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-999)
┆Issue Type: Story
┆Issue Number: DOCK-999

**Comment by denis-yuen** [comment]
Think this is #2878 again
