### ISSUE TITLE
possible robots.txt problem

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#2903]
Currently dockstore.org does not have a robots.txt file and it should not be necessary. staging.dockstore.org/robots.txt redirects to the home page. However, the Google lighthouse audit says the robots.txt is invalid. It looks like it's trying to parse some html as a robots.txt file. This could negatively affect search ranking if it appears incorrect to Google.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1002)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1002

**Comment by coverbeck** [comment]
I was thinking initially that we should just return a 404. But most sites seem to have a robots.txt, so I'm wondering if we shouldn't have one instead, even if we allow everything. And then if needed we can start disallowing things.

**Comment by agduncan94** [comment]
Works on staging as of 1.8.0-beta.6 and 2.5.0-beta.1
