### ISSUE TITLE
Better success message for updating a hosted workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2905]
## Feature Request 

When you update a hosted workflow, the snackbar pops up saying "Updating hosted workflow succeeded".

The message should be more specific, e.g., "Saved version 6 of workflow my-awesome-workflow". 

Although the doc talks about hosted workflows, the UI itself doesn't, so I feel like the word "hosted" is just slightly confusing in this context and we should just drop it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1004)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 25 Zille
┆Issue Number: DOCK-1004

**Comment by denis-yuen** [comment]
> Although the doc talks about hosted workflows, the UI itself doesn't, so I feel like the word "hosted" is just slightly confusing in this context and we should just drop it.

On this specific point, I feel like if the GUI is not making the distinction clear enough, we should make it more clear rather then erase the distinction. 
i.e. we want users to be aware of the trade-off they're making (convenience vs. stability of real source control)

**Comment by coverbeck** [comment]
> On this specific point, I feel like if the GUI is not making the distinction clear enough, we should make it more clear rather then erase the distinction.
> i.e. we want users to be aware of the trade-off they're making (convenience vs. stability of real source control)

Good point... then I suggest "Saved version 6 of hosted workflow my-awesome-workflow"

**Comment by garyluu** [comment]
Says `Saved version 2 of hosted workflow exampleHostedWorkflow`
