### ISSUE TITLE
Add tests to dockstore-cli for Docker alternatives

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2906]
In the Dockstore CLI repo, it currently runs 1 or 2 jobs. Create 2 new jobs- one for singularity and one for rootless docker.  Can run Cromwell to run singularity and can at least run CWL. For each one there's CWL and WDL. 

Workflows should be simple and relatively quick
For CWL 
https://dockstore.org/workflows/github.com/dockstore-testing/md5sum-checker/_cwl_checker:1.0.1?tab=info
For WDL 
https://dockstore.org/workflows/github.com/dockstore-testing/md5sum-checker/wdl_wdl_checker:1.0.1?tab=info

## Feature Request 
After Dockstore CLI is moved into its own repo, create tests to for Docker alternatives: singularity and rootless docker

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1005)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1005

**Comment by cricketsloan** [comment]
➤ Melaina Legaspi commented:

break up into tix for singularity and rootless docker

**Comment by coverbeck** [comment]
Verified that Singularity tests ran on develop at https://travis-ci.org/dockstore/dockstore-cli/builds/654559948?utm_medium=notification&utm_source=github_status
