### ISSUE TITLE
Sourcefile encoding issue

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2912]
##  Bug Report
Not sure if a refresh will fix it. This issue prevents the TRS validator from looking at all tools for the /tools endpoint validation.

Once this is fixed, remove the TRS validator tool limit.

### Expected behaviour
https://staging.dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fcancercollaboratory%2Fdockstore-tool-samtools-view to not have ��� 

### Actual behaviour
It has ���

### Steps to reproduce the behaviour 
Go to that URL

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1008)
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1008
┆Sprint: Sprint 53- Bull shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
@garyluu I tried creating my own workflow with the character that I think is the issue, which is u+2265 (≥), and when I imported the workflow, it worked correctly. Tried it with both a local build and staging.

My theory/hope is that a refresh will fix this. Can you try? (I don't belong to cancercollaboratory).

**Comment by garyluu** [comment]
Ya, looks like refreshing works.

**Comment by denis-yuen** [comment]
@coverbeck added you to cancercollab (louise and natalie are actually members already)

**Comment by coverbeck** [comment]
Closing this as it is fixed with refresh and also worked for me when setting up a fresh repo.

Presumably there was some encoding issue in the past that has been fixed.

Reopen if we can get into that state again.

**Comment by denis-yuen** [comment]
Looks like this rearing its head again with https://staging.dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fcancercollaboratory%2Fdockstore-tool-samtools-view

**Comment by denis-yuen** [comment]
Also should look into sort 
(i.e. why is this showing up again under the 30 tool limit in the TRS validator)

**Comment by garyluu** [comment]
Refreshed on prod, seems to work. not entirely sure what happened

https://dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fcancercollaboratory%2Fdockstore-tool-samtools-view

**Comment by garyluu** [comment]
checked out Oct 31, 2019 DB. it seems to not have been refreshed. I'm going to chalk this up to the prod db not actually being refreshed when we first closed this issue.
