### ISSUE TITLE
Hosted workflow request entity too large

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2915]
**This is likely blocked by migration to ADS RDS**
Trying to add a new version to a hosted workflow using the following two files

https://raw.githubusercontent.com/DataBiosphere/topmed-workflows/feature/freeze8-wdl/variant-caller/variant-caller-wdl-checker/freeze_8/topmed_freeze8_caller_checker.wdl

and

https://raw.githubusercontent.com/DataBiosphere/topmed-workflows/feature/freeze8-wdl/variant-caller/variant-caller-wdl/freeze_8/topmed_freeze8_caller.wdl

but am getting the error 413 Request Entity is too large.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1011)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1011
┆Sprint: Sprint 42 - Quahog
┆Issue Type: Bug

**Comment by coverbeck** [comment]
This shows the request size feature limit is working correctly. :)

We do intentionally have a limit of 50K. When we picked that, we thought nobody would have more than 50K in descriptors for a single version. The two files are just at 50K...

Seems like we should just decide what's a better limit.

**Comment by agduncan94** [comment]
I think we should update to maybe 100K and have a cleaner error message.

**Comment by NatalieEO** [comment]
@ByteMap I am able to register a hosted workflow that contains both the files listed above now. But if I try to go past the limit to test friendly error, it looks like 
![Screen Shot 2020-09-03 at 2 45 26 PM](https://user-images.githubusercontent.com/16004905/92176850-2c582a00-edf4-11ea-9b22-24d313b44134.png)

**Comment by ByteMap** [comment]
Hmm the message header on the top seems correct. However the body should only be `[HTTP 413]: 413 Request Entity Too Large`. Ill investigate further and see if I can pinpoint the bug and resolve it.

**Comment by coverbeck** [comment]
@ByteMap, nginx must be returning that. Try capturing the response on dev in Developer Tools.
