### ISSUE TITLE
Add icons on account linking page

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2917]
## Feature request

In the account linking page there is currently text for each of the possible integrations. Each of the other services have attached branding that would make it easier for dockstore users to see their relevant accounts.

We might apply the same CSS styling we do on the affiliates and make the logos clickable.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1012)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1012

**Comment by agduncan94** [comment]
The images are not loading. Upon further inspection it is because the src value is ../../../ prepended to it, even though it is a https url.

**Comment by agduncan94** [comment]
Gary pointed out that this is likely due to the circle ci job that does the find and replace for converting the relative paths to CDN paths. The UI circle ci config step with name "Swap for CDN paths" is where this must be fixed.

**Comment by agduncan94** [comment]
Fixed the relative paths.
