### ISSUE TITLE
Update our highlighting code for WDL 1.0 and CWL 1.1

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2921]
Our current highlighting code is based on older versions of these languages. We should add support for these new versions, while also making the existing code able to select the right highlighter based on version.

Might be useful storing some version metadata alongside a tool/workflow version (what version of the language are they).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1014)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1014
┆Sprint: Sprint 64-Oceanic shark
┆Issue Type: Story

**Comment by garyluu** [comment]
https://dev.dockstore.net/workflows/github.com/broadinstitute/gatk/cnv_somatic_pair_workflow:4.1.6.0?tab=files which is a WDL 1.0 looks reasonable to me. Kind of need a good broken example before creating an issue on https://github.com/broadinstitute/wdl-sublime-syntax-highlighter

**Comment by garyluu** [comment]
https://dev.dockstore.net/workflows/github.com/hubmapconsortium/sc-atac-seq-pipeline/HuBMAP_scATAC-seq_Pipeline:v1.0?tab=files which is CWL 1.1 looks reasonable to me. Kind of need a good broken example before creating an issue on https://github.com/rabix/benten or https://github.com/manabuishii/language-cwl . I regenerated our ace editor syntax highlighting using both repos and the syntax highlighting remains unchanged

**Comment by garyluu** [comment]
I think all future highlighting issues should be directed to the appropriate language repositories. Would be very odd for launch-with partners, Dockstore, etc to create their syntax highlighters for languages they don't work on. It'd be easier to find and have less duplicated efforts.
