### ISSUE TITLE
Remove font-awesome package from UI

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2922]
## Feature Request 

UI is using both [Angular FontAwesome](https://github.com/dockstore/dockstore-ui2/blob/4a7ad28ad8c5418898cb0aa222d858eee3d2a37f/package.json#L39l) and "plain" [FontAwesome](https://github.com/dockstore/dockstore-ui2/blob/4a7ad28ad8c5418898cb0aa222d858eee3d2a37f/package.json#L58).

We should try to get rid of the regular FontAwesome:

1. The Angular FontAwesome is pulling in FontAwesome 5, whereas we are explicitly including FontAwesome 4, which means duplicated and/or differently styled icons.
2. If we use Angular FontAwesome, unused icons can be tree shaken away.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1015)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1015
┆Sprint: Sprint 61- Leopard shark
┆Issue Type: Story

**Comment by garyluu** [comment]
Also note the current warning on any page with share buttons:

"FontAwesome: Global icon library is deprecated. Consult https://github.com/FortAwesome/angular-fontawesome/blob/master/UPGRADING.md for the migration instructions."

Ideally, the solution for this issue should also fix this.

**Comment by ByteMap** [comment]
Unable to remove font-awesome package at this time. Font-Awesome 4 is currently being included in bootstrap-social, which is used for social buttons such as 'Sign in with Github' and 'Sign in with Google'.
