### ISSUE TITLE
"See Also" links broken on readthedocs

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2925]
## Bug Report

On the readthedocs site, "See also" links are typically broken. It's generally happening because the link does not have ".html".

### Steps to Reproduce

1. Go to https://beta.docs.dockstore.org/en/develop/launch-with/dnastack-launch-with.html
2. Scroll to the bottom, to See Also
3. Click on any of the links -- you get a 404.

For example, clicking on AWS batch takes you to `https://beta.docs.dockstore.org/advanced-topics/aws-batch/`, but it should be taking you to `https://beta.docs.dockstore.org/en/develop/advanced-topics/azure-batch.html`-- note how the actual page has `.html` at the end, but the link does not.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1017)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Issue Number: DOCK-1017

**Comment by denis-yuen** [comment]
I killed a number of these in https://github.com/dockstore/dockstore-documentation/pull/19 but I think we probably need someone to go through it systematically and/or improve the link checker

**Comment by melainalegaspi** [comment]
Already fixed
