### ISSUE TITLE
Update CLI links from documentation

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2927]
## Bug Report

The documentation points to Dockstore CLI source code in several locations. For example, [as of today](https://github.com/dockstore/dockstore-documentation/blame/develop/docs/advanced-topics/advanced-features.rst#L12) (sorry for blame view, but GitHub doesn't let you view source code, other than in raw form for rst/md files).

The Dockstore CLI has been moved into its own repo so these links don't work.

For now, I am updating in dockstore/dockstore-documentation#31 the links so they point to the master branch, but for 1.8 we need to change the repo they point to.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1018)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-1018

**Comment by garyluu** [comment]
> ➤ David Steinberg commented:
> 
> Looks like walt got themhttps://github.com/dockstore/dockstore-documentation/commit/72ba55f531c3643ac506be510c5ed0f702232d33 ( [dockstore/dockstore-documentation@72ba55f](https://github.com/dockstore/dockstore-documentation/commit/72ba55f531c3643ac506be510c5ed0f702232d33|smart-link) )

The smart-link is not very smart

**Comment by garyluu** [comment]
Links seem fine
