### ISSUE TITLE
Copyright in RSS feed hard-coded and old

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2932]
## Bug Report

The copyright for the RSS feed is 2018.

It is set in [MetadataResource.java](https://github.com/dockstore/dockstore/blob/405558834a58c431ddbd9f4437b45f05d3b84d18/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/MetadataResource.java#L188).

For the fix, suggest it be dynamically determined, instead of needing to update the source code every year.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1024)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-1024

**Comment by denis-yuen** [comment]
See also #2973

**Comment by david4096** [comment]
I can confirm that the RSS feed now says 2020.

https://dev.dockstore.net/api/metadata/rss

tested on dev.dockstore.net
API - 1.9.0-alpha.1-SNAPSHOT
UI - 2.5.1-rc.1-5-gc535e6b4
