### ISSUE TITLE
Improve performance of sitemap endpoint

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2933]
## Feature Request 

Relates to and is mentioned in #2125, but I think the solution can be different than what's being considered for the TRS endpoints. Since sitemap only uses the workflow and tool paths from the POJOs, we could have queries that only fetch those columns.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1023)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-1023

**Comment by denis-yuen** [comment]
See also #1834

**Comment by coverbeck** [comment]
Manually verified that it is now blazingly fast, about .5 seconds against staging. That one is hitting the internal cache, so I tried a local instance, and the first hit, when the cache wasn't involved was still also .5 seconds (cached locally was 0.02 seconds).
