### ISSUE TITLE
Facet drop downs disappear if you preset reset filters

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2934]
### Expected behaviour
If I press reset filters, I expect that whatever filters I selected would get unchecked and that's it.
### Actual behaviour 
All the dropdowns disappear and only reappear if you change the text in the search bar. Does get reset though.
### Steps to reproduce the behaviour

1.  Go to https://dockstore.org/search
2. Enter a search term (or don't)
3. Click a facet (or don't)
4. Click reset filters

### Environment (Browser or OS and Dockstore version)
Chrome
API - 1.7.0 
UI - 2.4.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1025)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1025
┆Epic: Fix Facets

**Comment by agduncan94** [comment]
I believe this has been fixed by Gary.

**Comment by agduncan94** [comment]
Confirmed that this is fixed.
