### ISSUE TITLE
Search term persists if you navigate away and return to search page

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2935]
### Expected behaviour
I would think all my search criteria would get cleared if I navigate away and then come back to the search page later. Although I could see it the other way I suppose as a setting or something.

### Actual behaviour
The search term stays entered. But the facets don't get saved.  I'd say clear everything or save everything once a user navigates away.
### Steps to reproduce the behaviour 
1. Go to https://dockstore.org/search
2. Enter search term like pcawg
3. Click to navigate anywhere else on dockstore
4. Click Search to navigate back. See term is still there 

### Environment (Browser or OS and Dockstore version)
Chrome 
API - 1.7.0 
UI - 2.4.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1026)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1026

**Comment by garyluu** [comment]
Facets are being saved for me

**Comment by melainalegaspi** [comment]
@garyluu did you finish this? If so, link to correct PR

**Comment by denis-yuen** [comment]
Seems better on 
1.8.0-beta.6
2.5.0-beta.1
