### ISSUE TITLE
Whitelist wizard for selecting tools/workflows

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2939]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1029)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-1029
┆Epic: Streamlining workflow and tool registration

**Comment by garyluu** [comment]
Works for workflows. Need to create another issue for tool register. Also to add tooltips for disabled sliders.
