### ISSUE TITLE
Alphabetical ordering in facets affected by casing

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2942]
### Expected behaviour
In this case, I would expect casing to be ignored. 
### Actual behaviour
Case affects the order in the alphabetical list. 
### Steps to reproduce the behaviour 

1. Go to https://staging.dockstore.org/
2. Click alphabetical to sort by in the Author facet
3. Notice n/a appears before Aaron.
4. The same problem happens in the search results when clicking on the header to sort

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1030)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-1030
┆Epic: Fix Facets

**Comment by coverbeck** [comment]
Working in UI - 2.5.0-alpha.0 on staging.
