### ISSUE TITLE
News and Events Docs are empty

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2945]
They are linked from the landing page at Dockstore.org and are currently empty. To close this, move the News and Events in the correct section of the docs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1033)
┆Issue Type: Story
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-1033

**Comment by denis-yuen** [comment]
obsolete
