### ISSUE TITLE
Missing space for searches that use advanced search

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2947]
### Expected behaviour
As you add more to your search, the text in the box on the right that displays your search query spaced appropriately
### Actual behaviour
The end of advanced search portions are missing a space.
![image](https://user-images.githubusercontent.com/16004905/66234978-dd65ba00-e6a3-11e9-915a-113a6cccf2d3.png)

### Steps to reproduce the behaviour 

1. Go to https://dockstore.org/search
2. Add one input into advanced search
3. Click some facet option or add another input into advanced search. A space is missing

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1035)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Issue Number: DOCK-1035

**Comment by Ldcabansay** [comment]
LGTM, 
API - 1.8.0-alpha.2 
UI - 2.5.0-alpha.0
