### ISSUE TITLE
labels validation does not show valid format when not valid

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2949]
### Desired behaviour

When adding labels, if the format of the label is incorrect, we do not display the format for correct entries like other places on the site (like with registering workflows (source control repos)).

See https://discuss.dockstore.org/t/labels-interface-and-format-rules/3230
 
voted on/originates from @jmonlong

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1036)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-1036

**Comment by garyluu** [comment]
Seems unrelated. Appears to be a major problem of modifying anything.

**Comment by denis-yuen** [comment]
Also seeing `Could not convert Dockstore entry to Elasticsearch object` when publishing or unpublishing

**Comment by garyluu** [comment]
Unrelated but error on label saving does not indicate anything to the user.
