### ISSUE TITLE
Fix DOI ZenodoHelper Log instantiation

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2950]
ZenodoHelper.java line:
public final class ZenodoHelper {
    private static final Logger LOG = LoggerFactory.getLogger(WorkflowResource.class);

should read:
public final class ZenodoHelper {
    private static final Logger LOG = LoggerFactory.getLogger(ZenodoHelper.class);

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1037)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-1037
┆Epic: Create DOIs

**Comment by denis-yuen** [comment]
@wshands appreciate the thought, but this really isn't worth a whole issue

**Comment by garyluu** [comment]
Shows `private static final Logger LOG = LoggerFactory.getLogger(ZenodoHelper.class);` now
