### ISSUE TITLE
Deleting a non-existent test parameter file does not return an error

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2955]
## Bug Report

If you delete a non-existent test parameter file, the API returns a 200 status code.

It should return a 400 or 404 status code indicating that the file was not deleted.

This happens for both [tools](https://github.com/dockstore/dockstore/blob/469261112f80613393000b1d3fe51b46bfc15498/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java#L887) and [workflows](https://github.com/dockstore/dockstore/blob/469261112f80613393000b1d3fe51b46bfc15498/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/WorkflowResource.java#L1173) -- both methods just delete files they can find, but don't check if the files exist.

Not high priority.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1039)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1039

**Comment by agduncan94** [comment]
How does one get into a state where they have an associated test parameter file that does not exist?

**Comment by coverbeck** [comment]
The filenames are just parameters to the API endpoint -- you could specify any arbitrary, non-existent, names. Hence the low priority. :)

**Comment by agduncan94** [comment]
Tested on 1.9.0-alpha.9 and 2.6.0-rc.0, it works.
