### ISSUE TITLE
Source description from README.md (non-configurable path)

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2957]
* Have field/column that says it was pulled from descriptor file/README.md
* Display that info somehow in the UI, split this into new ticket****
* Priority is description from descriptor and if missing, from /readme.md (not case-sensitive?)
* Configuration can wait till a .dockstore.yml

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1041)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-1041

**Comment by denis-yuen** [comment]
Seems functional
