### ISSUE TITLE
UI and Docs should have Terra in works with section

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2959]
## Feature Request 

The footer of the home page, and [docs home page](https://docs.dockstore.org/en/develop/) should have the Terra logo in the "Works with" sections.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1042)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1042

**Comment by denis-yuen** [comment]
This requires approval on the Broad side

**Comment by abaumann** [comment]
I got approval for this, let me know what I should do to make the PR

**Comment by coverbeck** [comment]
@abaumann Sorry, I didn't realize, but we already have a [Broad logo](https://github.com/dockstore/dockstore-ui2/blob/develop/src/assets/images/sponsors/coloured/broad.png) in our repo, although we are not displaying it. Should we go ahead and use that one, or would you prefer a different Broad logo or even a Terra logo? Goto https://dockstore.org and scroll to the footer at the bottom to see the context.

If that's OK, I think your approval here on the issue is sufficient.

If you don't think we should use that logo, could you submit a PR with the image you want.

We have our docs in a [separate repo](https://github.com/dockstore/dockstore-documentation), hosted at docs.dockstore.org. If you change the logo, can you please do a PR for there too, putting it [here](https://github.com/dockstore/dockstore-documentation/tree/develop/docs/assets/images/affiliations). If the current logo is OK, we'll just copy the existing one over.

Thanks!

**Comment by denis-yuen** [comment]
Looks like the docs.dockstore.org ones don't use transparency either, but that can be a new ticket

**Comment by agduncan94** [comment]
On both UI and docs.
