### ISSUE TITLE
Add Tool dialog can come up with old error

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2960]
## Bug Report

If you attempt to register a tool and it fails, then attempt to register a tool again, when the dialog comes up, is prepopulated with the old error message. See attached screenshot.

### Steps to reproduce

1. Go to My Tools
2. Try to register a tool, specifying a Quay.io image from an org that you don't belong to. In my case I specified `cancercollaboratory/dockstore-tool-samtools-view`.
3. When you attempt to register the tool, you get a legitimate error.
4. Dismiss the dialog (or maybe it gets dismissed automatically, I forget)
4. Click the button to add a tool again. Not expecting to see an error in the dialog before I've even entered anything.

![Screen Shot 2019-10-11 at 3 23 23 PM](https://user-images.githubusercontent.com/1049340/66688450-7fa11700-ec3b-11e9-8b69-af3d88a3adb6.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1043)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-1043

**Comment by agduncan94** [comment]
This happens if you click outside the modal only. Clicking the close button will clear.
