### ISSUE TITLE
Facet buttons (alphabetical & count) improvements

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2963]
### Desired behaviour
Move the current default sort, count, to the button on the left
Bold the text of the sorting that is selected by the user to make the selection more obvious
The sort indicator should not be displayed if it's not the one currently selected.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1046)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1046
┆Epic: Fix Facets

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Could use a storytime to hash out, think this has switched before
