### ISSUE TITLE
Search should remember the page a user is on when back button pressed

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2966]
### Desired behaviour
If you click on a search result, what page you were previously on should be remembered when you click the back button.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1049)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-1049

**Comment by denis-yuen** [comment]
Looks better on 
API - 1.8.0-beta.6 
UI - 2.5.0-beta.1
