### ISSUE TITLE
Debatable format options for search page

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2968]
### Desired behaviour
- implementor will create mock-ups) For facets where a user can only select one option at a time, change to radio button instead. Add an option like “all” as default choice. 
   - This currently applies to Entry Type facet. I would rather keep this facet and get rid of the 
tabs for search in the future than the reverse. https://github.com/dockstore/dockstore/issues/2747 related to just getting rid of tabs entirely
   - Also applies to verified, has checker workflow, and tool: private access 
- (implementor will create mockups) reduce the amount of whitespace. I think each of the facet dropdowns occupy too much space.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1048)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1048
┆Sprint: Backlog
┆Issue Type: Story

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Probably needs storytime
