### ISSUE TITLE
Remove circular dependencies between dockstore and dockstore-cli

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2970]
## Bug Report

The Dockstore CLI [has a dependency on dockstore-common](https://github.com/dockstore/dockstore-cli/blob/ac343efe238494e66f2ab32f4c7b7b533880a8fc/dockstore-client/pom.xml#L43). The dockstore-integration module has a [dependency on Dockstore CLI](https://github.com/dockstore/dockstore/blob/e8501ecd29a5985a3119418a0858c1c2745802c6/dockstore-integration-testing/pom.xml#L47)

When you run the integration tests, it's going to use the Dockstore CLI that's a dependency, which is is compiled against a release of dockstore-common. If you've made changes to local dockstore-common, ~~they're not going to be used by the integration tests~~, your changes will be used, but the signatures of the methods it was compiled against must be present.

Because of this behavior, I had to leave some method signatures that I'd wanted to remove in [getParameterFile](https://github.com/dockstore/dockstore/blob/e8501ecd29a5985a3119418a0858c1c2745802c6/dockstore-common/src/main/scala/io/dockstore/common/WdlBridge.scala#L171); as part of this fix, we should get rid of that one as well as [getInputFiles](https://github.com/dockstore/dockstore/blob/e8501ecd29a5985a3119418a0858c1c2745802c6/dockstore-common/src/main/scala/io/dockstore/common/WdlBridge.scala#L143) and [getOutputFiles](https://github.com/dockstore/dockstore/blob/e8501ecd29a5985a3119418a0858c1c2745802c6/dockstore-common/src/main/scala/io/dockstore/common/WdlBridge.scala#L171)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1051)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 24 Yacht
┆Issue Number: DOCK-1051

**Comment by Ldcabansay** [comment]
API - 1.8.0-rc.0
Closing since can't really 'review' on staging, however this is the kind of ticket that 'reviews' itself since the webservice IT tests are run in the PR process. Instead, I double checked that webservice tests no longer call CLI in the codebase.
