### ISSUE TITLE
Utilities.executeCommand should allow environment to be specified

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2971]
## Feature Request 

The class io.dockstore.common.Utilities has several methods for executing commands. None of them allow environment variables to be set.

This will be useful for anticipated support for services in Dockstore CLI. There are probably other use cases where it will come in handy.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1052)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1052

**Comment by denis-yuen** [comment]
Exists, but not called anywhere (as expected). 
Considered completed since test seems to pass.
