### ISSUE TITLE
Improve performance of RSS endpoint

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2973]
### Desired behaviour

Same deal as #2933, likely the same solution too

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1053)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 22 Whaleboat
┆Issue Number: DOCK-1053

**Comment by NatalieEO** [comment]
Performance improves from ~1.6 sec to ~0.4 secs
API - 1.8.0-alpha.2 dockstore status indicator
UI - 2.5.0-alpha.0
