### ISSUE TITLE
Upgrade Lambdas to 10.x

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2978]
See if it takes an hour, if it takes longer, then reevaluate. 

## Feature Request 
AWS is making Node.js 8.x EOL; if we have 8.x lambdas, we should upgrade them to 10.x.

```
1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10

2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1055)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-1055

**Comment by cricketsloan** [comment]
➤ Andrew Duncan commented:

Tested on staging with the staging lambda and it works. Will leave it up so that other people can try it out too.

**Comment by agduncan94** [comment]
Wondering what to do with this ticket. Should we just also update production during the next release? Or should we just update it at any time? Should we do more testing on staging?

**Comment by coverbeck** [comment]
I think it's tested on staging well enough. I debated whether to close this and create a new ticket for prod or just leaving this one open, but in any case we don't want to forget to do it for prod. Probably safest to do it during the next release, IMHO.

**Comment by denis-yuen** [comment]
I think either time works, I don't think people rely on it enough that it should be a problem upgrading at any time, but upgrading during the release works too.

**Comment by denis-yuen** [comment]
Completed
