### ISSUE TITLE
Open api endpoints should use tags

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2982]
Figure out where our openapi.yaml is being served from

Currently most of the openAPI endpoints are under the tag default. We should update them to match those of the swagger tags.

[https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#tag](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#tag)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1056)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1056

**Comment by agduncan94** [comment]
Looks like the tags are working, but there is an error on the top of the page.

> Parser error on line 29
> end of the stream or a document separator is expected

**Comment by denis-yuen** [comment]
I think that happens if you don't go to https://staging.dockstore.org/api/openapi.yaml 
e.g. https://staging.dockstore.org/openapi.yaml

**Comment by agduncan94** [comment]
That method doesn't use swagger UI though. Is that ok?

**Comment by garyluu** [comment]
I think you type in https://staging.dockstore.org/api/openapi.yaml at the top of swagger-ui

**Comment by garyluu** [comment]
so basically https://staging.dockstore.org/api/static/swagger-ui/index.html?url=https://staging.dockstore.org/api/openapi.yaml

**Comment by agduncan94** [comment]
Works on 1.8.0-beta.6 and 2.5.0-beta.1
