### ISSUE TITLE
Strategy for setting the default version

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2988]
## Feature Request 

When Broad HCA publishes a new GitHub release, they want the latest release to be the default version in Dockstore.

Presumably others may not want always want that though.

The .dockstore.yml could have a strategy to define Dockstore's behavior for handling the default version when a new version is published.

I don't think we should do anything in this area without the .dockstore.yml; users would need to manually initiate a refresh in any case, and at that point they could set the default version as well (either through the UI or via the API).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1058)
┆Epic: Versions Table 
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1058
┆Sprint: Sprint 62- Mako shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@ewels voted for this in a private call, would automatically pick the default as the latest tag

**Comment by ewels** [comment]
Yup! We'd love to fully automate the addition of @nf-core pipelines and for us the latest release tag is always the gold standard default that we want people to use 🥇 The exception is for pipelines where there is no release - then we like people to use the default GitHub branch, which we set to `dev` in our case.

It would be no problem for us to specify this behaviour in the `.dockstore.yml` config file 👍🏻

**Comment by garyluu** [comment]
Related https://github.com/dockstore/dockstore/issues/3683
