### ISSUE TITLE
Add dockstore.yml support for workflows

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2991]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1060)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1060
┆Epic: Backport GitHub apps to workflows from services

**Comment by agduncan94** [comment]
This is going to be more complicated than with services. Just noting thoughts I have.

How do we determine whether a workflow is using the traditional approach vs dockstore.yml? When refreshing a workflow for the first time do we check every version for a dockstore.yml to make the decision?

How do we handle existing workflows that are not using dockstore.yml? Do we allow them to be migrated, or do we force users to make new workflows? Would it make sense to force all new workflows to use the dockstore.yml and all existing workflows use the current approach?

When registering a workflow with dockstore.yml, which version do we treat as correct. For example what if the workflow name was defined differently in different branches?

**Comment by denis-yuen** [comment]
brainstorming 

> How do we determine whether a workflow is using the traditional approach vs dockstore.yml? When refreshing a workflow for the first time do we check every version for a dockstore.yml to make the decision?

Can we use the API to determine whether our app is installed?

> How do we handle existing workflows that are not using dockstore.yml? Do we allow them to be migrated, or do we force users to make new workflows? Would it make sense to force all new workflows to use the dockstore.yml and all existing workflows use the current approach?

I think forcing a change would be reasonable. Migration is more tricky, generate a .dockstore.yml for them and show it in the UI?

**Comment by agduncan94** [comment]
> Can we use the API to determine whether our app is installed?

This is assuming we are only allowing dockstore.yml with github apps. Also if you have a github app install on a repo that is already a service that may mess this up.

> I think forcing a change would be reasonable. Migration is more tricky, generate a .dockstore.yml for them and show it in the UI?

I'll have to think more about how this may be done in a realistic sense (there are bound to be people who don't want to update to dockstore.yml but want to add new versions and such).

**Comment by denis-yuen** [comment]
> This is assuming we are only allowing dockstore.yml with github apps.

I think this may make things simpler, but I could be missing something. 
i.e. we assume that no .dockstore.yml is running in our current way
if you want to use GitHub Apps you need a .dockstore.yml  

I don't really want to allow GitHub Apps without a .dockstore.yml for example or allow a .dockstore.yml without Github apps

**Comment by coverbeck** [comment]
> I don't really want to allow GitHub Apps without a .dockstore.yml for example or allow a .dockstore.yml without Github apps

Probably not applicable, but just in case, we do have a .dockstore.yml for publishing zips to hosted workflows. I wonder if we should bag that API; I don’t think anybody is using it.

**Comment by agduncan94** [comment]
@denis-yuen 

> I don't really want to allow GitHub Apps without a .dockstore.yml for example or allow a .dockstore.yml without GitHub apps

If that is the case then I think it simplifies things greatly. Though we would have to start keeping track of which apps are added through GitHub apps and which are added the usual way.

**Comment by agduncan94** [comment]
@coverbeck 
I am for getting rid of that.
