### ISSUE TITLE
Give a warning/error if file in .dockstore.yml missing

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3007]
## Feature Request 

I accidentally specified healthcheck.json instead of healthcheck.sh in the .dockstore.yml for [my service](https://dockstore.org/services/github.com/coverbeck/galaxy-helm:dockstore-v10?tab=files). I did not realize I had made the mistake until I tried to run the service locally.

It would be nice if there were some sort of error or warning in the UI for cases like this. Probably requires a backend change too.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1069)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1069

**Comment by denis-yuen** [comment]
Can be hooked up as a validation error

**Comment by agduncan94** [comment]
Works on UI 2.5.1-rc.1 and WS 1.9.0-alpha.7
