### ISSUE TITLE
User got error registering with Google

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3008]
## Bug Report

A UCSC user got an error attempting to register with Google. He was subsequently able to register with GitHub, and then associate his Google account.

Saw this in logs:

```
08:32:54
INFO [2019-11-04 16:32:54,764] io.dockstore.webservice.resources.TokenResource: Google token created for <redacted>
08:32:54
WARN [2019-11-04 16:32:54,765] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: SQL Error: 0, SQLState: 22001
08:32:54
ERROR [2019-11-04 16:32:54,765] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR: value too long for type character varying(255)
ERROR [2019-11-04 16:32:54,765] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR: value too long for type character varying(255)
```

Given the stack trace and the fact that subsequent linking the Google account worked, and that only the username and avatarurl columns are VARCHAR(255) in the relevant tables, I suspect that he has a very long avatarurl.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1070)
┆Issue Type: Story
┆Issue Number: DOCK-1070

**Comment by jessebrennan** [comment]
I am not able to "link" the account now that it is created. The same error occurs,

```
Warning The webservice encountered an error.

[HTTP 500] Internal Server Error: org.hibernate.exception.DataException: could not execute statement could not execute statement ERROR: value too long for type character varying(255) 
```

**Comment by coverbeck** [comment]
Debugged with @jessebrennan and was able to confirm that for his profile, [Userinfoplus.getPicture()](https://github.com/dockstore/dockstore/blob/06368228796524c44324e6ee7ac7738ae23fb271/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/TokenResource.java#L346) returns a string with a length of 808.

We should probably just remove the limit, currently 255 for the avatarUrl column. Or maybe set it to something like 8k, which I think is the default max URI size in nginx.

**Comment by denis-yuen** [comment]
More evidence at https://gitter.im/ga4gh/dockstore?at=5dde9e4b5ac7f22fb51ba7c6

**Comment by denis-yuen** [comment]
Was tested and confirmed in Slack
