### ISSUE TITLE
Login should not always redirect to onboarding page

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#3009]
Go to staging.dockstore.org and log out and log back in. Every time it takes you to the onboarding page instead of the homepage. It seems like this should only be displayed the first time a user logs in.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1071)
┆Issue Type: Story
┆Issue Number: DOCK-1071

**Comment by agduncan94** [comment]
Closing due to duplication.
