### ISSUE TITLE
Add Launch with AnVIL button

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3012]
## Feature Request 

Add a Launch with AnVIL button. URL is https://anvil.terra.bio

This will follow the same rules as Terra -- this instance is behind scenes the same as Terra itself; it just has a different skin and url.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1073)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1073

**Comment by agduncan94** [comment]
Button works and properly links to Terra.
