### ISSUE TITLE
tool search page name sort is weird

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#3014]
On staging.dockstore.org/search, go to the Tools tab. Click on the 'name' header to sort by name. It seems to be sorting by the part of the name after the first slash, not the whole thing. For instance pfda2dockstore/bai/bai is before lynnlangit/blastn/blastn-test. 

This does not happen on the Workflows tab. It does make sense to sort first by tool name rather than organization, but the way this is displayed is confusing. Maybe the name and the organization prefix should be separated into adjacent columns for a cleaner look.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1075)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1075
┆Sprint: Sprint 46- Unicorn Fish
┆Issue Type: Bug

**Comment by NatalieEO** [comment]
Can confirm that the name column is alphabetically sorted in a way that makes sense now for tools and workflows

dev.dockstore.net
[Webservice](https://github.com/dockstore/dockstore/commits/d836384) - d836384

[UI](https://github.com/dockstore/dockstore-ui2/commits/17c33342) - 2.6.3-62-g17c33342

[Compose Setup](https://github.com/dockstore/compose_setup/commits/f067256a177048809c59dfc4ae76f918e4e820f4) - f067256a177048809c59dfc4ae76f918e4e820f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/ac878e6) - 1.9.3-50-gac878e6
