### ISSUE TITLE
Bump to newer version of Cromwell in CLI

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3018]
## Feature Request 
Bump to newer version of Cromwell that Dockstore uses by default in next Dockstore release. This is for the CLI.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1079)
┆Epic: Improve Cromwell Support
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1079
┆Sprint: Sprint 55- Dusky shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
There's also mortal kombat with Maven which is probably the biggest part of it

**Comment by NatalieEO** [comment]
Waiting for CLI release to test
