### ISSUE TITLE
Put workflow version alias in DOI entry as a Related Identifier

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3019]
# Feature Request 
Put workflow version alias (not workflow alias) in DOI entry as a Related Identifier

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1078)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 25 Zille
┆Issue Number: DOCK-1078

**Comment by garyluu** [comment]
I'm getting a 404 when going to my DOI on https://staging.dockstore.org/workflows/github.com/dockstore/hello_world:1.0.1?tab=versions

**Comment by wshands** [comment]
To test:
Add a DOI to a workflow
Go to the Zenodo site (sandbox.zenodo.org)
Click on Upload
<img width="127" alt="Screen Shot 2020-01-08 at 9 55 20 AM" src="https://user-images.githubusercontent.com/3650921/72002829-047cdc00-31fd-11ea-9cb0-e6cee0732933.png">

Check that your workflow is at the top of the list on the Zenodo upload page
Click on the your workflow path link on the Zenodo upload page
Click on the first Related Identifier link that points to an alias (it should have a form similar to http://localhost:4200/aliases/workflow-versions/10.5072-zenodo.438237)
<img width="395" alt="Screen Shot 2020-01-08 at 9 52 29 AM" src="https://user-images.githubusercontent.com/3650921/72002673-b667d880-31fc-11ea-996f-a6f1e9ca00d0.png">
Check that the link redirects to the same workflow VERSION that is display on the Zenodo page

**Comment by garyluu** [comment]
ok works with those instructions
