### ISSUE TITLE
Instructions for loading data in compose_setup no longer work

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3020]
## Bug Report

The [Loading up a database section](https://github.com/dockstore/compose_setup#loading-up-a-database) no longer works for after the [relinquish migrations](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/resources/migrations.1.7.0.relinquish.xml) have been run.

```
su - postgres
psql -f  /tmp/fix.sql 
```
leads to the data being created with the user `postgres` being the owner of all tables. However the webservice is [now configured](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/resources/migrations.1.7.0.relinquish.xml) for the user `dockstore` to be the owner, and so when the webservice launches it does not have permission to access the tables.

You'd think changing the psql command to something like `psql -f /tmp/fix.sql -U dockstore -d ...` would fix it, but when I tried it on staging, I got errors. I was trying to get staging back up, so I did not save them (should have), but I'm guessing the dockstore user doesn't have permission to execute all the commands in our psql file.

See first comment for probable solution.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1080)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1080

**Comment by coverbeck** [comment]
I think we need to change:

```
su - postgres
psql
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
\quit
psql -f  /tmp/backup.sql 
```

to:

```
su - postgres
psql
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
ALTER DATABASE postgres owner to dockstore;
\quit
psql -U dockstore -f  /tmp/backup.sql 
```

**Comment by denis-yuen** [comment]
Question: does this also occur in 1.7.0 or does this truly only occur in 1.8.0?

**Comment by coverbeck** [comment]
I think it will occur in both.

Liquibase records that it has done the relinquish migration. If you then load the data as the Postgres user, the relinquish migration will not execute, leaving Postgres as the owner of all the tables, which then leads to an auth failure when Docktore tries to connect to the database.

**Comment by denis-yuen** [comment]
Makes sense, I was trying to understand `The Loading up a database section no longer works for 1.8.` and couldn't hypothesize something that could break 1.8.0 but not 1.7.0

**Comment by coverbeck** [comment]
Ah right... I think I didn't fully understand the problem when I created the issue, having run into it when deploying 1.7 to staging after 1.8 had already been deployed there, and so the title ~~is~~ was misleading (will update it right after this comment)

**Comment by melainalegaspi** [comment]
done
