### ISSUE TITLE
Toggling between Checker and Parent workflow causes Start Discussion to get added each time

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3022]
## Bug Report

Every time you navigate between a checker workflow and parent entry, a "Start Discussion" gets added.

### Steps to reproduce the behaviour 

1. Navigate to https://dockstore.org/workflows/github.com/dockstore-testing/md5sum-checker/wdl_wdl_checker:1.0.1?tab=files
1. Click Parent Entry -- there are 2 Start Discussion
1. Click View Checker Workflow -- then there are 3 Start Discussion
1. etc.

![Screen Shot 2019-11-14 at 12 34 37 PM](https://user-images.githubusercontent.com/1049340/68899330-4a7a5f80-06e6-11ea-95e0-78725964a498.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1082)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 25 Zille
┆Issue Number: DOCK-1082

**Comment by garyluu** [comment]
I don't see it.

**Comment by coverbeck** [comment]
> I don't see it.

Figured out why; updated description and title.
