### ISSUE TITLE
Workflow title overwrites Publish and Refresh buttons

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3034]
## Bug Report
Workflow title overwrites Publish and Refresh buttons
### Expected behaviour
Workflow title wraps before hitting the Publish and Refresh buttons
### Actual behaviour
Workflow title overwrites Publish and Refresh buttons
### Steps to reproduce the behaviour 
https://dockstore.org/my-workflows/github.com/wshands/SnapTools/WaltSnapTools_part_of_snapATAC_for_HuBMAP
https://github.com/wshands/SnapTools

![Screen Shot 2019-11-22 at 11 05 04 AM](https://user-images.githubusercontent.com/3650921/69462447-db2bed80-0d2d-11ea-982c-24ab1c9de2bf.png)

### Environment (Browser or OS and Dockstore version)
API - 1.7.1
UI - 2.4.0
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1086)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1086

**Comment by garyluu** [comment]
Works for my-tools, my-workflows, my-services
