### ISSUE TITLE
Error message on Tools and DAG tabs for CWL workflow

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3035]
## Bug Report
Error message on Tools and DAG tabs for CWL workflow
### Expected behaviour
Should see list of CWL tools and DAG
### Actual behaviour
On Tools tab see " No Records Found"
On DAG tab see "  DAG cannot be created because some required tools are missing from Github repo."

### Steps to reproduce the behaviour 
https://dockstore.org/my-workflows/github.com/wshands/SnapTools/WaltSnapTools_part_of_snapATAC_for_HuBMAP
https://github.com/wshands/SnapTools

![Screen Shot 2019-11-22 at 11 04 54 AM](https://user-images.githubusercontent.com/3650921/69462656-6f965000-0d2e-11ea-9209-f3869a8e4c10.png)
![Screen Shot 2019-11-22 at 1 47 30 PM](https://user-images.githubusercontent.com/3650921/69462739-a9675680-0d2e-11ea-8137-434e05df3715.png)

### Environment (Browser or OS and Dockstore version)
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
API - 1.7.1
UI - 2.4.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1085)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 38 Manatee
┆Issue Number: DOCK-1085

**Comment by agduncan94** [comment]
@wshands The link is to my-workflows, could you attach a screenshot of the info tab?

**Comment by agduncan94** [comment]
When running locally I see the following error when trying to view the tools/dag tabs
```
Not a JSON Array: {"DockerRequirement":{"dockerPull":"snaptools:1.2.3"},"ResourceRequirement":{"ramMin":1024,"outdirMin":100000,"coresMin":1}}
```

Seems like CWLAvro isn't understanding this format.

**Comment by wshands** [comment]
cwltool validates snaptools_index_ref_genome_tool.cwl which contains the requirements section
~/Documents/UCSC/gitroot/SnapTools => cwltool --validate snaptools_index_ref_genome_tool.cwl
INFO /usr/local/bin/cwltool 1.0.20190621234233
INFO Resolved 'snaptools_index_ref_genome_tool.cwl' to 'file:///Users/waltershands/Documents/UCSC/gitroot/SnapTools/snaptools_index_ref_genome_tool.cwl'
snaptools_index_ref_genome_tool.cwl is valid CWL.

**Comment by wshands** [comment]
![Screen Shot 2019-11-27 at 12 27 29 PM](https://user-images.githubusercontent.com/3650921/69757231-4fd9a000-1111-11ea-903f-076efbce1dd9.png)

**Comment by wshands** [comment]
Also so the author and email do not show up; not sure why?

**Comment by agduncan94** [comment]
@wshands If it is failing to parse the files it will not be able to pull authorship.

**Comment by agduncan94** [comment]
@wshands I cannot find the file snaptools_index_ref_genome_tool.cwl in that repo. Did the file change?

**Comment by agduncan94** [comment]
Looks like I forked the original repo and not yours, which has the branch with the descriptor files.

**Comment by agduncan94** [comment]
@wshands What is the primary descriptor?

**Comment by wshands** [comment]
https://github.com/DockstoreTestUser2/SnapTools/blob/feature/docker_cwl_req_in_main/snaptools_create_snap_file.cwl is the primary descriptor.

**Comment by denis-yuen** [comment]
Seems to work with ` /snaptools_create_snap_file.cwl` on branch `feature/docker_cwl`
