### ISSUE TITLE
Use prebuilt web-service images

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3037]
## Feature Request 

The dockstore_webservice container is currently built on the fly by pulling a JAR from OICR artifactory.

Instead, the dockstore-webservice could be built on Quay.io, and compose_setup could just reference that image. This gives the following benefits:

1. It will be faster to use a pre-built image
2. This will give us the ability to do deploy at any time, rather than having to wait for a web service version to be pushed to the OICR artifactory.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1088)
┆Issue Type: Story
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-1088
┆Epic: Continuous Deploy

**Comment by coverbeck** [comment]
Related to #3065 , at least the building part. Still need to update compose_setup to use it.

**Comment by garyluu** [comment]
Someone invite me to the Quay.io namespace

**Comment by denis-yuen** [comment]
(resolved invite)

**Comment by garyluu** [comment]
A few failed builds on Quay.io.  https://github.com/dockstore/dockstore/blob/develop/Dockerfile#L24 will need to be updated for releases

**Comment by coverbeck** [comment]
> A few failed builds on Quay.io. https://github.com/dockstore/dockstore/blob/develop/Dockerfile#L24 will need to be updated for releases

Good catch on JAR... Will create a separate issue. Not sure what to do about failed builds.

**Comment by garyluu** [comment]
Good enough
