### ISSUE TITLE
Logged-in homepage misc information and tutorial

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3046]
On the off chance we can't get events on the homepage in time for the release, we should add other useful information to the logged in homepage. This could be similar to information we should on the logged-off homepage, including links to tutorials or quick tips.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1090)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1090

**Comment by agduncan94** [comment]
I think we decided we would not do this @denis-yuen can we delete?

**Comment by denis-yuen** [comment]
Yup, I think we have enough content
