### ISSUE TITLE
Differential Loading

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3047]
### Desired behaviour
The frontend should utilize differential loading to decrease bundle size for modern browsers.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1092)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1092
┆Sprint: Sprint 52- Angel shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
timebox investigation

**Comment by garyluu** [comment]
Didn't work, reverting changes. Still memory issues. Tried updating to latest lts node + latest Angular 8 CLI and setting node options memory to 4gb but none of that worked.  Probably gonna wait till Angular 9 change things up and see what happens.

**Comment by garyluu** [comment]
Issues with SRI + Differential Loading + Maybe Cloudfront.  Possibly an Angualr CLI issue and is out of our control.

https://github.com/angular/angular-cli/issues/18254  might reveal some insight.  Until then, no differential loading.
