### ISSUE TITLE
Whitelist wizard for selecting tool wizard

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3051]
### Desired behaviour
There should be a whitelist wizard for selecting tools users want to register.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1095)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1095

**Comment by denis-yuen** [comment]
Workaround: manually register one tool from the quay.io namespace and then refresh by namespace

**Comment by denis-yuen** [comment]
Would need this for quay.io
