### ISSUE TITLE
Whitelist Wizard disabled tooltips

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3052]
### Desired behaviour
Some sliders in the workflow whitelist wizard are disabled. There should be a tooltip for why.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1094)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 25 Zille
┆Issue Number: DOCK-1094

**Comment by agduncan94** [comment]
The sliders are disabled if they cannot be deleted. I think something along the lines of "This workflow is published so it cannot be deleted."

**Comment by NatalieEO** [comment]
Tooltip does appear for disabled sliders 
API - 1.8.0-beta.0
UI - 2.5.0-beta.0
