### ISSUE TITLE
Login for existing users shouldn't open to Onboarding

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3054]
Currently any login or register will go to the onboarding wizard. This makes sense for new users/inexperienced users, but no for those who are familiar with Dockstore. For advanced users we should just load the homepage, which will be their dashboard.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1096)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-1096

**Comment by denis-yuen** [comment]
Implement at same time as #3114

**Comment by agduncan94** [comment]
Is this due to the redirect URL from OAUTH?

**Comment by denis-yuen** [comment]
I don't believe so, I don't think we would have put the onboarding URL into the third party app but I could be wrong

**Comment by agduncan94** [comment]
Looks like there is a function in login.component.ts that navigates to onboarding.

**Comment by agduncan94** [comment]
Oops, this is a duplicate of https://github.com/dockstore/dockstore/issues/3009

**Comment by agduncan94** [comment]
This is done https://github.com/dockstore/dockstore-ui2/pull/903
