### ISSUE TITLE
Use pre-built jars for Swagger clients

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3062]
### Desired behaviour
Swagger clients that are relatively unlikely to change such as swagger-java-quay-client, swagger-java-discourse-client, etc should be prebuilt and have its jar uploaded to a maven repository once. The Dockstore backend can then import it without having to rebuild it every time a test runs. See https://github.com/garyluu/swagger-java-quay-client/runs/335422346 for an example.

This should save time in the CI.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1099)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1099
┆Sprint: Sprint 69- Tiger shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Also setup cron-like travis-ci builds to detect changes when/if discourse, zenodo, quay change their APIs

**Comment by denis-yuen** [comment]
Can split up into tickets for 
* swagger-java-quay-client (7.7 seconds)
* swagger-java-sam-client (5.5 seconds)
* swagger-java-bitbucket-client (11.9 seconds)
* swagger-java-discourse-client (6.7 seconds)
* swagger-java-zenodo-client (5.5 seconds)
