### ISSUE TITLE
Circular dependencies in UI

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3063]
In the UI there is a circular dependency. The following is the warning message:

> WARNING in Circular dependency detected:
> src/app/myworkflows/myworkflows.service.ts -> src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts -> src/app/myworkflows/myworkflows.service.ts
> 
> WARNING in Circular dependency detected:
> src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts -> src/app/myworkflows/myworkflows.service.ts -> src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts
>

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1100)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1100

**Comment by denis-yuen** [comment]
Doesn't really need verification on staging
