### ISSUE TITLE
Create Dockerfile for web service

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3065]
## Feature Request 

Add a Dockerfile for the web service so that we can build Docker images on Quay.io.

We will need to update compose_setup, where the image is currently built, to handle the fact init_migrations.sh and init_webservice.sh will no longer be part of the image.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1102)
┆Issue Type: Story
┆Sprint: Seabright Sprint 25 Zille
┆Issue Number: DOCK-1102
┆Epic: Continuous Deploy

**Comment by NatalieEO** [comment]
It's there
