### ISSUE TITLE
UI Edit dialog and hosted workflow

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3067]
## Bug Report
Can click edit on a hosted workflow that has a DOI

Editing a snapshotted hosted workflow and clicking 'Hidden' then 'Save Changes' results in error "Could not convert Dockstore entry to Elasticsearch object"

### Expected behaviour
Should not be able to edit a hosted workflow that has a DOI 
Edit Workflow Version dialog box:
Should be able to grab dialog and move it?
'Close' should say 'Cancel' instead?
### Steps to reproduce the behaviour 
https://staging.dockstore.org/my-workflows/dockstore.org/wshands/atestworkflowhosted

![Screen Shot 2019-12-09 at 3 49 21 PM](https://user-images.githubusercontent.com/3650921/70482836-801f2800-1a9b-11ea-8ce7-39581ca24169.png)

### Environment (Browser or OS and Dockstore version)
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
1.8.0-alpha.2 
UI - 2.5.0-alpha.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1105)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1105

**Comment by denis-yuen** [comment]
Better but still kinda weird, clicking on  "View" shows a 'Edit Workflow Version" dialog that cannot be edited but has a "Save Changes" button. Looking at network activity, clicking it does send a PUT to a snapshotted version?

**Comment by garyluu** [comment]
Eeek, forgot to change dialog mode

**Comment by denis-yuen** [comment]
Works with 
API - 1.8.0-beta.8 
UI - 2.5.0-beta.2
