### ISSUE TITLE
Organizations and collections without images show undesireable default image

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3070]
We should only show an image if one exists. If it doesn't exist we should not show a broken image.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1106)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1106
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Bug

**Comment by denis-yuen** [comment]
Think we should show an ugly icon or an auto generated one

**Comment by denis-yuen** [comment]
e.g.
* egg icon on twitter
* faceless icon
*

**Comment by coverbeck** [comment]
Waiting on 1.12 staging deploy to verify.

**Comment by coverbeck** [comment]
Confirmed that orgs that show the text "org logo" on prod now show a generic logo in staging.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0-beta.1) - 1.12.0-beta.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9.0-beta.0) - 2.9.0-beta.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/7323652) - 1.12.0-beta.0-5-g7323652

galaxyParsingLambdaVersion: 0.0.7
