### ISSUE TITLE
Generic Language Support for DAG and Tools

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3073]
## Feature Request 

Generic language `CompleteLanguageInterface` should support tools and DAG.

See [this commit](https://github.com/dockstore/dockstore/commit/42fee38cef80106d4099753441f761c587bf135e) for the. very beginnings of this.

Also see [Cytoscape type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cytoscape/index.d.ts); Java API should return a Java version of that class (there may be a native one already) instead of the String it currently returns.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1108)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1108

**Comment by denis-yuen** [comment]
@garyluu more info for #1172
