### ISSUE TITLE
Restore sponsors and works with logos on logged-in homepage

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3082]
### Desired behaviour

Need these even though it is redundant

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1117)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1117

**Comment by NatalieEO** [comment]
See them on the homepage
API - 1.8.0-beta.6 dockstore status indicator
UI - 2.5.0-beta.1
