### ISSUE TITLE
Mock-up labs/unstable annotation for access points to services including my-services dropdown

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3083]
### Desired behaviour

Create mock-ups for how to denote this feature as highly experimental and should not be used by non-partners at this time.

Includes my-services, sitemap, docs?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1118)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1118

**Comment by coverbeck** [comment]
Also see SEAB-697.

**Comment by garyluu** [comment]
Examples: 
https://material.io/collections/machine-learning/barcode-scanning.html#
https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github

**Comment by denis-yuen** [comment]
drydock?
under construction? (maybe this implies you can't use it?)

discussion about "experimental" 

don't overload tags that we use for development (alpha, beta, rc) but we can use terms that don't overlap

**Comment by agduncan94** [comment]
Preview label is in dropdown, sitemap, and header bar for my-services/services pages.
