### ISSUE TITLE
Investigate the existance of a checker workflow stub

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3088]
There seems to be an error with migrations deleting all stubs due to checker workflows. When we change the migration to only delete workflow stubs that are not checker, no error occurs. We need to investigate why this is the case.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1121)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1121

**Comment by agduncan94** [comment]
There is only one checker workflow which is a stub. It is for the tool quay.io/cri-iatlas/mcpcounter. The mode is "AUTO_DETECT_QUAY_TAGS_AUTOMATED_BUILDS".

The reason why the migration didn't work is that we didn't take into account tools with checker workflows. When we tried to delete the checker workflow stub, it couldn't be deleted since it is referenced by a tool. It results in the following error 
```
ERROR:  update or delete on table "workflow" violates foreign key constraint "fk_checkerid_with_tool" on table "tool"
```

Since tools can never be stubs, I think what we want to do here is make sure that when a checker workflow is added to a tool, we immediately refresh it. Even if the checker workflow is invalid, it is still not a stub, which is what we want.

**Comment by agduncan94** [comment]
Looking at the webservice code, the function registerCheckerWorkflow in WorkflowResource is what adds a checker workflow. It always adds a stub checker workflow. It should actually refresh the checker workflow after creating it.

Should see if the UI is smart enough to call a refresh after adding a checker workflow.

**Comment by agduncan94** [comment]
It looks like the UI already calls a refresh right after a checker workflow is registered.
So for the tool to have a stub checker workflow, I think either

* the UI refresh failed
* the user added via API (no refresh - not likely)
* the user set the checker as a stub in the UI

Currently, it looks like a restub of a workflow will clear it of any checker workflows, but there is nothing stopping a user from calling restub a checker workflow. Calling restub on a checker workflow also does not remove the connection to the parent entry, so if you try and restub a checker workflow, it will still be associated with the tool.

**Comment by agduncan94** [comment]
Based on my investigation, I think the solution is to update the restub code to not allow the stubbing of checker workflows.

I think what makes more sense is for there to be an endpoint that deletes a checker workflow entry and removes its association with its parent. We would also need to surface this button in the UI.

**Comment by agduncan94** [comment]
@denis-yuen Finished the investigation, what are your thoughts on the suggested solution? You'll probably want to read all the above comments as they show the investigation, but the last comment has my suggestions.

**Comment by denis-yuen** [comment]
>  update the restub code to not allow the stubbing of checker workflows 
seems reasonable

> Only workflows can be restubbed, and doing so will delete the associated checker workflow (if exists).
ditto

> endpoint that deletes a checker workflow entry and removes its association with its parent (leaving the parent tool/workflow intact) 
maybe, right now we cannot delete workflows, so do we need to delete checker workflows
or does this all become redundant with archive

> one should not be able to publish a tool/workflow if the checker is a stub.
this is unclear to me, explain

**Comment by agduncan94** [comment]
> maybe, right now we cannot delete workflows, so do we need to delete checker workflows
or does this all become redundant with archive

It depends on how you think of checker workflows. Should they be treated as first class workflows, or just as some extra files associated with a tool/workflow that do a check. Even though we have them in the DB as workflows, they aren't exactly the same as workflows. I think we had planned for their mode to mimic the associated entry, however, I think we may have overlooked that tools cannot be stubs, which is causing this weird case.

So I don't necessarily know whether or not this becomes redundant with archive. But another case where delete is useful is where a user doesn't know what a checker workflow is, tries setting one, realizes they don't need it, but now they are stuck with an associated entry (unless they restub the main workflow, assuming the parent entry is a workflow).

I think checkers should mimic their associated parent entry in terms of mode/state, however, maybe allow non-archived tools and workflows to be able to delete the associated checker (for now this means both published and unpublished).

Sorry for rambling, but there is a lot to think about with checker workflows and how the eventual changes to the entry lifecycle will impact. But for now, I really think that we should add a delete checker workflow endpoint (can eventually support deleting regular workflows).

> this is unclear to me, explain

For this I just mean, if I add a checker workflow to an unpublished tool/workflow, and the checker is a stub, it should not be able to publish. The user would have to be notified that the associated checker is not valid and requires a refresh of the parent entry. Though depending on if we end up supporting delete for checker workflows, this may not be necessary.

**Comment by denis-yuen** [comment]
> Sorry for rambling, but there is a lot to think about with checker workflows and how the eventual changes to the entry lifecycle will impact. But for now, I really think that we should add a delete checker workflow endpoint (can eventually support deleting regular workflows).

Not sure, thinking for the same reasons we will only allow redact and archive for workflows, tempted to keep things simple and only have redact and archive for checker workflows. Allowing a third option (delete) seems redundant and I think in the case that someone accidentally creates a checker workflow, archiving it seems to be sufficient. 

I am not particularly dedicated to this view though and probably can be persuaded.

**Comment by agduncan94** [comment]
If we archive a checker workflow, would it still be associated with a tool/workflow? If so, that means we cannot associate another checker workflow with that tool/workflow.

**Comment by agduncan94** [comment]
@denis-yuen Is a safe compromise the following:
* cannot restub checker workflows
* check whether the restub of a workflow actually deletes the checker workflow, or if it only deletes the connection (if the latter, then that is an issue)

I don't want to do any major changes for deletion and whatnot, since that is likely going to change based on lifecycle discussions that will happen in the near future.

**Comment by agduncan94** [comment]
Looks like restub of a workflow deletes only the association with a checker workflow. The checker workflow itself is not deleted.

**Comment by NatalieEO** [comment]
@agduncan94 wasn't entirely sure how to review, but I looked at whether you can still restub a checker workflow. You cannot, but the UI isn't intuitive. The restub button is still clickable, but nothing happens. There's only an error message in the console; it's not displayed to the user. Did you want to do that as part of this ticket?

**Comment by agduncan94** [comment]
@NatalieEO Hey, I would create another issue for the UI change that removes the restub button from checker workflows.

**Comment by NatalieEO** [comment]
Created issue #3704, closing this ticket.
