### ISSUE TITLE
Write response times in nginx logs

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3093]
## Feature Request 

Our nginx logs are using the default nginx log format, which does not include response times. If we have any issues server-side, it could be useful to see the response times, e.g., if we see the response times start to spike, it may give us a hint when something started to wrong.

See [nginx doc](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#setting-up-the-access-log)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1124)
┆Issue Type: Story
┆Issue Number: DOCK-1124
┆Epic: Grafana

**Comment by denis-yuen** [comment]
Done as part of https://github.com/dockstore/compose_setup/pull/123
