### ISSUE TITLE
Onboarding Wizard should better link to documentation

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3114]
Currently when users are onboarding and are setting up the Dockstore CLI, at the very end of installing there is just a link that says go to docs. This link goes to [Getting Started with Docker](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html).

This link is assuming that users are those creating tools/workflows/service and not those just launching. We should change it to have more useful links, such as "Getting started for developers" and "Getting started for launchers". We could also briefly describe what information is available in the docs at a high level.

Edit:
For more context, here is what it currently looks like.
![onboarding](https://user-images.githubusercontent.com/6331159/71930156-1b71ee80-3169-11ea-957e-c666e5bd7015.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1134)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Issue Number: DOCK-1134

**Comment by agduncan94** [comment]
Another idea would be another stepper option after setup CLI with some useful links and explanations for new users.

**Comment by kathy-t** [comment]
This Go to Docs link at the end of the onboarding wizard leads to a page that doesn't exist (https://docs.dockstore.org/en/latest/getting-started/getting-started-with-docker.html). The correct link should be https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html.

**Comment by garyluu** [comment]
Looks different and links work
