### ISSUE TITLE
Document new features for 1.8.0

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3115]
### Desired behaviour
Need docs.dockstore documentation for new features including
- [x] readme.md #2957 
- [x] whitelist wizard
- [ ] launch-with Anvil #3012

logged with homepage (might be intuitive enough to not need it

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1135)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-1135

**Comment by agduncan94** [comment]
Logged in home page seems like something a blog post would be best for.
