### ISSUE TITLE
Launch with BioData Catalyst Buttons

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3123]
## Feature Request 

Dockstore should have two Launch with BioData Catalyst buttons. There will be one for WDL and one for CWL. The WDL button will redirect to a Terra-based platform, the CWL button will redirect to a Seven Bridges based platform.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1140)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8.X
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-1140

**Comment by denis-yuen** [comment]
@coverbeck  Intended for 1.8.0

**Comment by coverbeck** [comment]
I had so intended, but just removed it.

**Comment by coverbeck** [comment]
> BDCat .gov transition is planned for Feb 21. Can the Launch With BDCatalyst button be released on/near that date? We will begin training early users that week with official launch on March 5.

That should be doable.

**Comment by mikebaumann** [comment]
Hi @coverbeck, FYI a *staging* deployment of Terra with the new BioData Catalyst *staging* URL is available now, here: https://staging.terra.biodatacatalyst.nhlbi.nih.gov/

We'll keep you posted as the date for availability on the *production* URL (https://terra.biodatacatalyst.nhlbi.nih.gov/) draws nearer.

Thanks!

**Comment by agduncan94** [comment]
Works on staging  with API 1.8.1 and UI 2.5.1.
