### ISSUE TITLE
Workflow Version Information (metadata)

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3124]
### Desired behaviour
Set Workflow Version Information to actually use the workflow version's metadata (email, description, author)

Currently, it's displaying default version no matter what

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1141)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10286/Screen+Shot+2020-11-17+at+12.29.00.png">Screen Shot 2020-11-17 at 12.29.00.png</a> | <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10285/Screen+Shot+2020-11-17+at+12.29.17.png">Screen Shot 2020-11-17 at 12.29.17.png</a> | <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10288/Screen+Shot+2020-11-17+at+14.13.00.png">Screen Shot 2020-11-17 at 14.13.00.png</a> | <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10287/Screen+Shot+2020-11-17+at+14.16.07.png">Screen Shot 2020-11-17 at 14.16.07.png</a>
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1141
┆Sprint: Sprint 44- Sea Horse
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Also happens with hosted workflows if using one with  version 2 including 
```
meta {
        author: "Andrew Duncan"
        email: "Andrew.Duncan@oicr.on.ca"
        description: "![build_status](https://quay.io/repository/collaboratory/dockstore-tool-bamstats/status) A Docker container for the BAMStats command. See the [BAMStats](http://bamstats.sourceforge.net/) website for more information."
    }
```
and  version 3 including
```
  meta {
        author: "Not Andrew Duncan"
        email: "not.Andrew.Duncan@oicr.on.ca"
        description: "not.![build_status](https://quay.io/repository/collaboratory/dockstore-tool-bamstats/status) A Docker container for the BAMStats command. See the [BAMStats](http://bamstats.sourceforge.net/) website for more information."
    }
```

version 3 will look ok but version 2 has version 3's email

**Comment by garyluu** [comment]
The web service appears to return two different authors for the two versions, so it looks correct to me

**Comment by garyluu** [comment]
Looking at the web service results, each version of the workflow has `null` as the author. The workflow itself has "David Jones" as the author which is why that can be seen in Elasticsearch.

What most likely happened is that the workflow was created a long time ago before version-level metadata was a thing. It already had an author at the entry-level.  Once version-level metadata became a thing, instead of copying the existing entry-level metadata to every version, it was left as null to avoid being possibly wrong.

**Comment by denis-yuen** [comment]
FYI, probably I duplicated this with #3929

**Comment by garyluu** [comment]
https://docs.google.com/document/d/1GvfVMfn5Uo0Ek0ZGdTnP7JGNlnQ2gXrvypFgjIs8tuI/edit#heading=h.mcublmvpysff in case people forgot what happened

**Comment by garyluu** [comment]
Denis had an example above
