### ISSUE TITLE
Generated swagger model seems wrong for dates

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3127]
## Bug Report

Swagger generates data models with a Date field, but when you look at the property in a browser debugger, it is just a timestamp/number.

### Steps to reproduce the behaviour 

1. Observe the generated model for organization, in src/app/shared/swagger/model/organization.ts. It contains the following:
```
...
    dbCreateDate?: Date;
    dbUpdateDate?: Date;
...
```
1. In a local build, go to http://localhost:4200/organizations, setting a breakpoint in organizations.ts. You'll see the following:
![Screen Shot 2020-01-10 at 10 40 23 AM](https://user-images.githubusercontent.com/1049340/72177545-be0eb500-3395-11ea-8754-bac8aa925506.png)

Note how dbCreateDate and dbUpdateDate are numbers not Dates.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1143)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 41 Pufferfish
┆Issue Number: DOCK-1143

**Comment by denis-yuen** [comment]
What are the consequences of this from a ui2 and cli pov (question for implementer/investigator)

**Comment by coverbeck** [comment]
I think it can cause bugs in ui2, e.g., if you call organization.dbCreateDate.getTime() you will get a runtime error. We ran into this during notifications UI dev. I think we haven't run into it so far, because all we do is display dates with an Angular pipe, and the pipe checks to see if the format is a string, a number, a date...

**Comment by garyluu** [comment]
`@ApiModelProperty(dataType = "long"` can fix this
