### ISSUE TITLE
The HTML title for Dockstore docs pages has 1.6.0 in it

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3128]
## Bug Report

Title mentions 1.6.0. Noticed it in a Google Doc with a link to the docs, which shows the title.

### Steps to Reproduce

1. Go to  docs.dockstore.org
2. Right-click, View Page Source

```
  <title>Welcome to Dockstore Documentation! &mdash; Dockstore 1.6.0 documentation</title>
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1144)
┆Issue Type: Story
┆Issue Number: DOCK-1144

**Comment by denis-yuen** [comment]
Gone now
