### ISSUE TITLE
Dockstore CLI Requested URL Different

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3130]
### Expected behaviour
```
wget https://github.com/dockstore/dockstore/releases/download/1.8.0-beta.6/dockstore
chmod a+x dockstore
./dockstore --help
```
should show help message

### Actual behaviour
```
https://github.com/dockstore/dockstore/releases/download/1.8.0-beta.1/dockstore-client-1.8.0-beta.1-shaded.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

```

### Steps to reproduce the behaviour 
See above

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1145)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1145

**Comment by denis-yuen** [comment]
Due to separation of cli and webservice, we can no longer assume matching cli and webservice versions.

**Comment by agduncan94** [comment]
Do we require existing users to update their dockstore bin file since that references dockstore/dockstore instead of dockstore/dockstore-cli?

**Comment by agduncan94** [comment]
Also has the link in the onboarding been updated to point to this new download location?

**Comment by denis-yuen** [comment]
Hmmm, link in onboarding is the same location (i.e. we still put the script in dockstore/dockstore)
But the script is different (download from dockstore/dockstore-cli instead of dockstore/dockstore)

That might also break the auto-upgrade come to think of it.
