### ISSUE TITLE
Swagger-UI says invalid swagger.json

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3131]
### Expected behaviour
Swagger-UI should not say in the bottom right corner that the swagger is invalid

### Actual behaviour
Swagger-UI does say in the bottom right corner that the swagger is invalid
Seems it doesn't handle the redirect to /api

### Steps to reproduce the behaviour 
Go to bottom right corner of https://dockstore.org/api/static/swagger-ui/index.html#

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1146)
┆Issue Type: Story
┆Issue Number: DOCK-1146

**Comment by coverbeck** [comment]
This duplicates #1444
