### ISSUE TITLE
Documentation for 1.8.0

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#3134]
The following are things that confused me while I was going through the [Dockstore Documentation tutorial](https://docs.dockstore.org/en/develop/). I followed the tutorial until I had a registered workflow.

**About Dockstore**
- [Built with Docker and Git](https://docs.dockstore.org/en/develop/dockstore-introduction.html#built-with-docker-and-git)
  - Not sure what a Docker image is
  - Lacks a description of the role that Docker containers play. It jumps to saying the “the services lack standardized ways of describing how to invoke tools contained within Docker containers”

**Getting Started with Docker**
- [Introduction to Docker](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html#introduction-to-docker)
  - Explains the question I had about the role Docker plays above but doesn’t explain what a Docker image is
- [Creating a Dockerfile](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html#creating-a-dockerfile)
  - What's a Dockerfile?
- [Building Docker Images](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html#building-docker-images)
  - Doesn't mention that docker should be installed. 
    - Could add a link on how to install: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - Unsure where to build the docker image. What is the context?
    - If following the tutorial, need to clone dockstore-tool-bamstats repo on local machine and run tutorial from that directory
  - What is happening when the docker image is being built?
- [Testing the Docker Image Locally](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html#testing-the-docker-image-locally)
  - I ran the following command since my user ID is 1001, not 1000: 
``docker run -it -v `pwd`:/home/ubuntu --user 1001:1000 `echo $UID`:1000 quay.io/collaboratory/dockstore-tool-bamstats:1.25-3 /bin/bash``
    - Got the following error:
      `Unable to find image '1001:1000' locally docker: Error response from daemon: pull access denied for 1001, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.`

**Getting Started with CWL**
- [Describe Your Tool in CWL](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-cwl.html#describe-your-tool-in-cwl)
  > This section links the Docker image used for this CWL, Notice it's exactly the same as the -t you used when building your image.
  - The above states that the dockerPull version and -t version used is the same but the version in the dockerPull string is different from the version used to build the image from the [Getting Started with Docker > Building Docker Images section](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-docker.html#building-docker-images).
    - dockerPull version is `quay.io/collaboratory/dockstore-tool-bamstats:1.25-6` but -t version is `quay.io/collaboratory/dockstore-tool-bamstats:1.25-3`
- [Testing Locally](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-cwl.html#testing-locally)
  - From the [Dockstore Quick Start Guide, Part 4](https://dockstore.org/quick-start)
    - Had a little trouble making cwltool available on my PATH because I wasn’t sure how to do that
    - The following is what I did:
    `pip3 show cwltool` to find the location that cwltool was downloaded to
    `vim ~/.profile`
    Add a new line that says `PATH="$PATH:<fill in download location of cwltool>"`
    `source ~/.profile`
- [Releasing on GitHub](https://docs.dockstore.org/en/develop/getting-started/getting-started-with-cwl.html#releasing-on-github)
  > I’m going to use the tag 1.25-6_1.1 which I’ll need to update in my docker image tag and also my CWL/WDL/Nextflow file ...
    - Not sure how to update this in the docker image and CWL/WDL/Nextflow file

**Workflows**
- Initially thought that the workflow had to use tools that were registered on Dockstore, but realized that workflow doesn't need to be connected to a tool registered on Dockstore
- [Create Workflow Stubs from GitHub, BitBucket, and GitLab](https://docs.dockstore.org/en/develop/getting-started/dockstore-workflows.html#create-workflow-stubs-from-github-bitbucket-and-gitlab)
  - After releasing workflow on GitHub, and refreshing on Dockstore, I couldn't publish it (message was "Unable to publish: no valid versions found")
    - Realized that if the workflow path isn’t Dockstore.cwl, need to edit the workflow path to the correct path in order to have a valid version to publish

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1148)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8.X
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1148

**Comment by NatalieEO** [comment]
Adding to this ticket that the quickstart guide where you confirm the CLI installation needs to be updated. It assumes the Dockstore version you'll get lines up with the webservice, but that's no longer the case.

**Comment by agduncan94** [comment]
Looks like proper changes have been made and are live on the doc site.
