### ISSUE TITLE
Cut-off messages

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3135]
### Desired behaviour

Message also seemed a bit unclear to me, suggestions welcome
![Screenshot from 2020-01-13 15-31-29](https://user-images.githubusercontent.com/1730679/72289820-e4dd1d80-3619-11ea-9191-fdd9517ea833.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1149)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-1149

**Comment by coverbeck** [comment]
"non-standard" sounds judgemental. :) Not sure what to say though.

**Comment by garyluu** [comment]
So it appears mat radio button content intentionally makes it nowrap.  Is the solution here to force it to wrap, scroll, or...?

**Comment by denis-yuen** [comment]
Maybe a more concise message with one of these (link and tooltip)
![Screenshot from 2020-01-13 15-53-39](https://user-images.githubusercontent.com/1730679/72291223-ea883280-361c-11ea-8372-3373b9c99dc2.png)

**Comment by agduncan94** [comment]
The definition of "standard" workflow in our case:
* one workflow per repository (so no workflow name)
* primary descriptor is /dockstore.cwl or /dockstore.wdl or /nextflow.conf

**Comment by denis-yuen** [comment]
Maybe the other way around would sound less judgemental. 
i.e. rather than standard vs non-standard 
                        (nothing) vs custom
                        quick vs custom

**Comment by coverbeck** [comment]
>     * primary descriptor is /dockstore.cwl or /dockstore.wdl or /nextflow.conf

As Dockstore gains traction, presumably many and even most workflows will not have the dockstore.cwl/wdl pattern. If I were writing a real workflow, which I've never done :), I would name my primary descriptor after the functionality, e.g., /aligner.wdl, and not after a platform it would be registered on.

My judgemental comment was sort of in jest, but I do think what we're now calling non-standard may actually end up being the norm more often than not. 

All that said, I'm not sure what to say.  I do like "Quick". Not sure about "custom".

**Comment by agduncan94** [comment]
For now should we just have the first option be something like "Quick" and second option be "Custom"?

**Comment by denis-yuen** [comment]
Working as expected on staging.dockstore.org
