### ISSUE TITLE
Returned events have too much content

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3139]
# Bug Report

### Expected behaviour

Returned events should have a reasonable amount of content

### Actual behaviour

Event calls seem to have way too much content including files and descriptions

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1151)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-1151

**Comment by NatalieEO** [comment]
Content returned reduced significantly. in the KBs instead of MBs

API - 1.8.0-beta.9 dockstore status indicator
UI - 2.5.0-beta.4
