### ISSUE TITLE
Populate logged-in homepage to substitute for recent events

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3140]
### Desired behaviour

- create some news and events for the logged in home page (may need to be a script that can be run against prod?)
- bring up affiliation and reduce grey bar on left

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1150)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 27 Barracuda
┆Issue Number: DOCK-1150

**Comment by denis-yuen** [comment]
* carryover some links from Next Steps on the on-boarding wizard

**Comment by denis-yuen** [comment]
Going to need that script for populating prod with events. 
(Looking for a Bash script where I can plug in a token, run it against prod and end up with some suitable news and updates when deploying)

**Comment by NatalieEO** [comment]
@denis-yuen made the script for news and events. Can see what I chose on staging.

**Comment by denis-yuen** [comment]
FYI, UI2 says that services is in preview but the news item links to a page that says services is in beta.

**Comment by denis-yuen** [comment]
Otherwise, makes sense

**Comment by denis-yuen** [comment]
(news items works for me, post in Slack so we can run when deploying to prod?)
