### ISSUE TITLE
Create or find a maven plugin for sorting openapi.yaml

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3141]
### Desired behaviour

We need this for improving the build. We can't tell what is actually changing in openapi/swagger.yaml and merge conflicts are annoying.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1152)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1152

**Comment by garyluu** [comment]
The swagger.yaml and the resulting openapi.yaml can be fixed through proper use of position and setting of ApiModelProperty, the openapi3/openapi.yaml I have no idea.

The swagger.yaml and openapi.yaml would still have the problem with BioWorkflow not extending workflow properly though.
