### ISSUE TITLE
Optimize user endpoints

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3143]
### Desired behaviour

Some endpoints are getting pokey and are doing too much in memory despite relatively low CPU use in general. 

Take a look at converting functionality in 
https://staging.dockstore.org/api/users/users/entries?count=10
https://staging.dockstore.org/api/users/user/extended
https://staging.dockstore.org/api/users/3/workflows

to better use the DB by using named queries instead of computing in memory.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1153)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1153

**Comment by coverbeck** [comment]
For the first two endpoints, may also be able to use a technique similar to [BioWorkflowDAO.java](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/BioWorkflowDAO.java), where only the relevant columns are fetched, reducing the number of joins in the DB query.

**Comment by Ldcabansay** [comment]
#978 related, might want to look into storing commit SHA to see if it has changed before updating
