### ISSUE TITLE
Check that the CLI auto-upgrade still works after migrating the CLI

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3150]
The CLI has been moved to another repo. The versions of the CLI and webservice no longer match up (at least there is no guarantee). This might break the CLI auto-upgrading. We should check that this works, and if it does not then we fix it.

https://github.com/dockstore/dockstore/issues/3130

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1155)
┆Issue Type: Story
┆Issue Number: DOCK-1155

**Comment by denis-yuen** [comment]
Taking a look, think this will still work after refactoring.  False alarm
