### ISSUE TITLE
Configure UI workflow languages based on plugins

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3154]
### Desired behaviour

The UI should automatically configure available workflow languages based on metadata endpoints. This can be broken up since this could be a big task including:
* drop-downs for languages when registering workflows
* regexes for language file types
* turning on and off DAG displays
* syntax highlighting
* search facets
* probably more

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1158)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1158

**Comment by garyluu** [comment]
Does this apply to tools too?

**Comment by denis-yuen** [comment]
Yes, you can assume they line up. 
i.e. if they have a future WDL plugin, it should support both WDL tools and workflows
you won't have a situation whether you need to support WDL workflows, but not WDL tools

**Comment by garyluu** [comment]
List of things to possibly change

- [x] tools
But in another PR
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by denis-yuen** [comment]
Took a first guess, general principle is that if a dialogue modal would be confusing/input superfluous parameters, then skip it. 
Otherwise, if there is excess documentation or metadata not visible to the user, that's probably ok.

**Comment by coverbeck** [comment]
On dev.dockstore.net, I created Galaxy workflows, and can search and view them. Demoed them to AnVIL tech meeting..dockstore.net. Since the demo, I see syntax highlighting has been added (yay!). Logged one issue, #3292 for the UI.

Also logged #3312, where Launch tab needs to be updated.
