### ISSUE TITLE
Expose Git SHA of webservice build

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3157]
## Feature Request 

Now that we are looking at deploying daily builds internally, it would be useful to know the Git SHA of the last commit of the particular build. This hasn't been an issue for our prod and staging environments because those are based on GitHub releases.

Looks like we can use [the commit-id plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin#plugin-compatibility-with-maven) to gather the information. The question is how to expose it:

1. We always add it to the version, writing it out to the manifest, which then gets surfaced in the API. Could make the footer in the UI look a little messier, although that could be handled in the UI (display commit id only if version does not contain SNAPSHOT).
2. We conditionally add it to the version, i.e., only add if web service is not being built off a release. This [looks tricky in Maven](https://stackoverflow.com/a/52241788/257235) though.
3. We expose a new endpoint, something like `/metadata/buildinfo` where this additional information is exposed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1159)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-1159
┆Epic: Continuous Deploy

**Comment by denis-yuen** [comment]
>     3. We expose a new endpoint, something like `/metadata/buildinfo` where this additional information is exposed.

There is something halfway there for this one

https://staging.dockstore.org/api/api/ga4gh/v2/metadata
```
{
  "api_version": "2.0.0",
  "country": "CAN",
  "friendly_name": "Dockstore",
  "version": "1.8.0-beta.8"
}
```

**Comment by coverbeck** [comment]
> There is something halfway there for this one
> 
> https://staging.dockstore.org/api/api/ga4gh/v2/metadata

I'd seen that one but had a hypothetical concern about adding the git SHA to the version from a TRS perspective, e.g., the spec perhaps specifies a format for the version. But I just went to the [spec](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/openapi/ga4gh-tool-discovery.yaml) to see if that would be an issue, and don't even see a metadata endpoint. Will we be dropping this endpoint for the v2.0 implementation?

If we do option 1 or 2, it would affect this endpoint. 3 was proposed as an option to avoid affecting the endpoint.

**Comment by denis-yuen** [comment]
I think GA4GH wants to standardize on https://github.com/ga4gh-discovery/ga4gh-service-info
i.e. /service-info so it is no longer present in TRS V2

That said that has https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/service-info.yaml#L112 or https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/service-info.yaml#L117 which could be used in the future. 

If it helpds, we're not going to destroy V1 or V2 beta after implementing V2 final. At least not until everyone has migrated

**Comment by agduncan94** [comment]
Visible with metadata endpoint in WS 1.9.0-alpha.9-SNAPSHOT
