### ISSUE TITLE
assorted tool delete errors

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#3171]
Tool deleting behavior depends on how it was added (the "from github, bitbucket, etc." option vs. "create and save on dockstore.org") and also what repo and image registry are used.
Sometimes it works, sometimes fails with multiple possible errors.
Should test every combination of tool adding options and make sure that they can all be deleted.
Should also check that these problems don't happen with workflows also.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1171)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1171

**Comment by melainalegaspi** [comment]
Should split up different bugs into different tickets.

**Comment by denis-yuen** [comment]
Breaking things down:
* workflows will eventually be redacted or archived (no straight-up deletion)
* was unable to delete self-hosted on dev.dockstore.net as well
* was able to delete quay.io automated tool

**Comment by garyluu** [comment]
Works for hosted tool and non-hosted tools
