### ISSUE TITLE
Hook up and test Galaxy plugin validation

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3173]
### Desired behaviour

Hook up and test Galaxy plugin validation for tools, workflows, and test parameter files
That last one may need input from Galaxy folks. See https://github.com/galaxyproject/dockstore-galaxy-interface/issues/1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1173)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1173

**Comment by NatalieEO** [comment]
Galaxy validation errors are surfacing in UI for descriptors. Don't believe test parameter validations exist yet, but there's an issue in the plugin repo for that. Will just close this ticket.
