### ISSUE TITLE
Investigate smartapi compatibility

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3178]
Look for a smart API validator 

### Desired behaviour
Would like to know if our autogen openapi3 description is compatible with Smart API
https://github.com/dockstore/dockstore/tree/develop/dockstore-webservice/src/main/resources/openapi3

The old version had a seemingly random [empty NIHdatacommons tag](https://github.com/dockstore/dockstore/blob/a1c6c18c5436a5ea0dfaf162b1f1041477c6b665/dockstore-webservice/swagger2open.sh#L11) with no operations/endpoints nested under it. Figure out what is going on and see if there is a smart API validator.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1177)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-1177

**Comment by agduncan94** [comment]
using editor.swagger.io I see the following errors
Semantic error at paths./organizations/{organizationId}/events.get.requestBody
GET operations cannot have a requestBody.
Jump to line 1267
Semantic error at paths./users/{userId}.get.requestBody
GET operations cannot have a requestBody.
Jump to line 1430
Semantic error at paths./users/user.get.requestBody
GET operations cannot have a requestBody.
Jump to line 1447
