### ISSUE TITLE
Versions Table Styling part 1

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3179]
### Desired behaviour
New material versions table will look odd (default version info button, actions dropdown alignment), will need some re-arranging and styling.

- When content is too long, both tables (workflow and tools handle it in a different way, make them handle it the same)
- Tools table has too many links in the first two columns, it's confusing.
- Links don't change the cursor on hover
- Add tooltips to disabled actions

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1178)
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1178
┆Sprint: Sprint 47- Vampire Squid
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Also the links out to explain what default branches/tags and verified mean

**Comment by coverbeck** [comment]
1. The link out icon (in the first column, that takes you to GitHub), seems too large to me, although maybe this will be rendered moot by the solution to the "too many links" issue described above.
2. The not a snapshot icon looks very close to being a snapshot icon -- I guess the difference is the the lock isn't quite closed. May want to just not have any icon if it's not a snapshot.
3. For public workflows, there is only one item in the  Actions dropdown
4. The actions dropdown column is very repetitive, saying Actions in every row.

**Comment by garyluu** [comment]
This should be 1.9.0 I think, it's pretty much unusable otherwise

**Comment by denis-yuen** [comment]
Setting as 1.9.x, it doesn't seem definitively worse than prod currently ...

**Comment by garyluu** [comment]
Reviewer just check if the columns are wrapped (no horizontal scroll, no truncated text). Issue split to https://github.com/dockstore/dockstore/issues/3920
