### ISSUE TITLE
Cannot change tool file paths

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3180]
### Expected behaviour

Go to https://staging.dockstore.org/my-tools/quay.io/pancancer/pcawg_delly_workflow
Change WDL Path, save, and refresh to get new WDL

### Actual behaviour

Path change is ignored. Can also switch between tools to see that the new path is not saved. 
See 400 error on webservice, seems like incorrect JSON

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1179)
┆Issue Type: Story
┆Issue Number: DOCK-1179

**Comment by garyluu** [comment]
Dropwizard doesn't the UI's starredUsers object for some reason.

**Comment by denis-yuen** [comment]
Working in staging 
API - 1.8.0-rc.0 
UI - 2.5.0-rc.3
