### ISSUE TITLE
Logged in homepage my entries and my orgs should wait for typing to stop before making API calls

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3182]
Currently when you are typing a query on the my entries or my organisations widgets of the homepage, every keystroke there is an API call. We should change this to have some sort of wait till user has typed in more of their query.

We have debounce time set to 250 currently.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1181)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 44- Sea Horse
┆Issue Number: DOCK-1181

**Comment by denis-yuen** [comment]
Re-evaluate experience after implementation of #3143
