### ISSUE TITLE
Logged-out homepage tweaks

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3183]
### Desired behaviour

1. Re-establish background images for logged-out homepage
2. Consider extending background colour for continuity
3. Either replace "Start Here" button with mission statement or have the "Start here" button scroll to the mission statement + video

CC @briandoconnor

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1182)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8.1
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1182

**Comment by garyluu** [comment]
That mostly covered what I wrote down.  Additionally, I had:

- Relies too much on text
- The previous one had a table that showed there's content

**Comment by denis-yuen** [comment]
In production
