### ISSUE TITLE
Nextflow tools

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3188]
According to Junjun, nextflow has the concept of process and workflow. This is similar to WDL with the task and workflow. We should investigate whether Nextflow tools would be a good idea.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1186)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-1186
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@ junjun-zhang
 ```
Nextflow has both process  and workflow in DSL2: https://www.nextflow.io/docs/latest/dsl2.html#process
```
