### ISSUE TITLE
Fix image on "getting started with WDL" page

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#3192]
In this section https://docs.dockstore.org/en/develop/getting-started/getting-started-with-wdl.html#testing-locally there is an image showing the steps of what the CLI does. One box says "execute tool with inputs using CWL" even though the page is about WDL. Need to make a corrected image for WDL to use on this page.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1193)
┆Issue Type: Story
┆Sprint: Seabright Sprint 28 Cuttlefish
┆Issue Number: DOCK-1193

**Comment by denis-yuen** [comment]
Looking good
