### ISSUE TITLE
Remove Deprecated Unstarring Endpoints

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3195]
### Desired behaviour
Remove the deprecated unstarring endpoints for tools/workflows/organizations at some point

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1190)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1190
┆Sprint: Sprint 56- Epaulette shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Investigate

**Comment by denis-yuen** [comment]
Looks like the last 1.8 series CLI usage was us in December and was 1.8.1
A surprisingly amount of 1.7.1 and 1.7.4 usage though from a bunch of random places like AWS and UCLA (not UCSC)
Seems to end in January

Will proceed anyway, unstar does not seem to be hiti a lot

**Comment by denis-yuen** [comment]
Silly. 
Think this already made it in https://github.com/dockstore/dockstore/commit/840ff14935a29dce2a50aebd7f2c5c4e8ecd7c55
