### ISSUE TITLE
update version of cwltool we test with / use in docs

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3196]
### Desired behaviour

Update cwltool, may want to check-in with https://gitter.im/common-workflow-language/common-workflow-language to see if they recommend a particularly stable recent version

Note that this may affect docs and https://dockstore.org/api/metadata/runner_dependencies?client_version=1.8.0&python_version=3

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1189)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1189
┆Sprint: Sprint 46- Unicorn Fish
┆Issue Type: Story

**Comment by GFJHogue** [comment]
Pasting my comments from SEAB-1499 since this appears to be the relevant ticket:

# Upgrades for Python 3.8
> The following versions were tested on the latest default Ubuntu 20.04 Python (3.8.2) with remaining Python packages in requirements.txt unchanged:
> 
> ## Minimal upgrades:
> 
> ruamel.yaml should be bumped to 0.15.100 (last 0.15.x release) https://pypi.org/project/ruamel.yaml/.
> 
> cwltool must be bumped to at least [1.0.20191022103248](https://github.com/common-workflow-language/cwltool/releases/tag/1.0.20191022103248) (or last 1.0.x release 1.0.20191225192155) for Python 3.8 & higher ruamel.yaml support.
> 
> schema_salad should be bumped to [4.5.20191204060541](https://github.com/common-workflow-language/schema_salad/releases/tag/4.5.20191204060541) (latest release) for Python 3.8 & higher ruamel.yaml support

---

> ## Maximal upgrades:
> 
> We can upgrade all python packages except for ruamel.yaml to their latest versions without any code changes on our end.
> 
> Newer versions of `ruamel.yaml` break for `dockstore-cli` integration tests due to:
> 
> ```
> [INFO] Running io.dockstore.client.cli.LaunchTestIT
> Starting test: cwlMissingIdParameters
> problems running command: cwltool --non-strict --validate /home/ghogue/repos/dockstore-cli/dockstore-client/target/test-classes/missingIdParameters.cwl
> stderr for command:
>         INFO /home/ghogue/miniconda/envs/seab1499/bin/cwltool 3.0.20200724003302
>         INFO Resolved '/home/ghogue/repos/dockstore-cli/dockstore-client/target/test-classes/missingIdParameters.cwl' to 'file:///home/ghogue/repos/dockstore-cli/dockstore-client/target/testclasses/missingIdParameters.cwl'
>         ERROR Tool definition failed validation:
>         target/test-classes/missingIdParameters.cwl:10:5: while parsing a block collection
>         target/test-classes/missingIdParameters.cwl:11:5:   expected <block end>, but found '?'
> ```
> 
> ruamel.yaml breaks for `dockstore` integration tests starting at version 0.15.91 where we get the following error (explained in https://stackoverflow.com/questions/55540686/configuring-ruamel-yaml-to-allow-duplicate-keys)
> 
> ```
> [INFO] Running io.dockstore.client.cli.GA4GHV2BetaIT
> INFO /home/ghogue/miniconda/envs/seab1499/bin/cwl-runner 3.0.20200724003302
> ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
> The error was: while constructing a mapping
>   in "http://localhost:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fgaryluu%2FtestWorkflow/versions/master/plain-CWL/descriptor/cwl/arguments.cwl", line 1, column 1
> found duplicate key "baseCommand" with value "javac" (original value: "javac")
>   in "http://localhost:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fgaryluu%2FtestWorkflow/versions/master/plain-CWL/descriptor/cwl/arguments.cwl", line 7, column 1
> To suppress this check see:
>     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
> Duplicate keys will become an error in future releases, and are errors
> by default when using the new API.
> ```
> 
> To get the latest `requirements.txt` for whatever `ruamel.yaml` we end up using, run the following:
> 
> `pip install cwl_runner==1.0 cwltool==3.0.20200724003302 ruamel.yaml==0.15.90`
> 
> `pip freeze > requirements.txt`
> 
> ```
> bagit==1.7.0
> CacheControl==0.11.7
> certifi==2020.6.20
> chardet==3.0.4
> coloredlogs==14.0
> cwl-runner==1.0
> cwltool==3.0.20200724003302
> decorator==4.4.2
> humanfriendly==8.2
> idna==2.10
> isodate==0.6.0
> lockfile==0.12.2
> lxml==4.5.2
> mistune==0.8.4
> mypy-extensions==0.4.3
> networkx==2.4
> prov==1.5.1
> psutil==5.7.2
> pydot==1.4.1
> pyparsing==2.4.7
> python-dateutil==2.8.1
> rdflib==4.2.2
> rdflib-jsonld==0.5.0
> requests==2.24.0
> ruamel.yaml==0.15.90
> schema-salad==7.0.20200612160654
> shellescape==3.4.1
> six==1.15.0
> typing-extensions==3.7.4.2
> urllib3==1.25.10
> ```

**Comment by denis-yuen** [comment]
In general, would prefer the "maximal" upgrade. Upgrading cwltool makes us retest all verified workflows anyway, so we might as well make it a big one. But would defer to asking to cwl community what would be the most recent, stable, recommended release.

**Comment by mr-c** [comment]
Hello! We don't have a concept of a stable release as we are a reference runner. Perhaps `toil-cwl-runner` would be better to recommend?

Or you could track the `cwltool` version they depend on.

**Comment by mr-c** [comment]
I would recommend at least version `3.0.20200807132242` of cwltool to get CWL v1.2 compatibility. This is also the version that the latest release of Tool depends on.

**Comment by denis-yuen** [comment]
to confirm, from context, this is the version that the latest release of cwltool depends on?

**Comment by mr-c** [comment]
@denis-yuen , yes :+1:

**Comment by NatalieEO** [comment]
https://dockstore.org/api/static/swagger-ui/index.html#/metadata/getRunnerDependencies does return the version mentioned above and following the quickstart CLI instructions does download that cwltool version as well.
