### ISSUE TITLE
Launch-with  DNAstack multicloud

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3197]
Implement launch-with DNAstack based on UI prototype.

Archive information:

### Expected behaviour
DNAstack should be able to read workflows from Dockstore. 
Launch-with button should open DNAstack with a workflow loaded

### Actual behaviour
Looks like a parsing error, we might be dealing with unintentional breakage with proprietary endpoints. Can either fix or consider updating to GA4GH TRS

![width=200,height=183](https://user-images.githubusercontent.com/1730679/73553014-373e7c80-4417-11ea-8e5f-276287b9b5b2.png)

FYI @vrockai or @mcupak (please let me know if there is someone better to email/tag)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1188)
┆Epic: Integration with DNAstack portal
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-1188
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Bug

**Comment by mcupak** [comment]
Thanks @denis-yuen! + @patmagee @hkeward

**Comment by coverbeck** [comment]
We need to populate the well-known server(s) with the API.
