### ISSUE TITLE
Wrong Cromwell Version in Documentation

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3204]
## Bug Report

The [doc](https://docs.dockstore.org/en/develop/advanced-topics/advanced-features.html#wdl-launcher-configuration) says WDL will automatically be run with Cromwell 36. It is currrently version 44.

Two suggestions for fix:

1. Change the doc to be a table with Dockstore CLI version and WDL version, e.g, Dockstore CLI 1.8 => Cromwell 44, Dockstore CLI 1.7 => Cromwell ?, etc., although we don't need to go that far back.
2. Add a comment in [Dockstore CLI](https://github.com/dockstore/dockstore-cli/blob/fbc3261494f36a8434b71783e1fd4716203ab102/dockstore-client/src/main/java/io/dockstore/client/cli/nested/CromwellLauncher.java#L37) that if you change the Cromwell version, to also update the doc.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1198)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1198

**Comment by NatalieEO** [comment]
I see the table on develop docs
