### ISSUE TITLE
Automatically sort imports for ui2

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3205]
### Desired behaviour

ui2 should have the equivalent of https://code.revelc.net/impsort-maven-plugin/ to automatically sort imports. Would reduce noise when reviewing PRs

Might be able to use a git hook or take advantage of prettier in some way  https://github.com/dockstore/dockstore-ui2/pull/683

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1199)
┆Issue Type: Story
┆Issue Number: DOCK-1199

**Comment by garyluu** [comment]
`npx ng lint --fix` does this, it just takes too long

**Comment by garyluu** [comment]
So it takes like 10 seconds normally but that's still too long
