### ISSUE TITLE
Locale error when connecting to webservice container

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3210]
## Bug Report

When you docker exec into the web service container from develop branch (not in prod nor staging), you see the following:

```
docker exec -it compose_setup_webservice_1 /bin/bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

This is most probably caused by the way we now build the Docker image in #3190

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1201)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1201

**Comment by emlys** [comment]
https://github.com/docker-library/docs/blob/master/debian/content.md#locales

**Comment by NatalieEO** [comment]
No longer see warning when running command in dev instance
