### ISSUE TITLE
Webservice Dockerfile only works with snapshot builds

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3214]
## Bug Report

The Dockerfile [assumes](https://github.com/dockstore/dockstore/blob/develop/Dockerfile#L24) there always be a SNAPSHOT jar. For release branches, there won't be a SNAPSHOT Jar.

See comments in #3037

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1204)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1204

**Comment by coverbeck** [comment]
1. Fix should not copy the sources JAR as well, which is why it is the way it is now.
2. See [first answer](https://stackoverflow.com/questions/49939960/docker-copy-files-using-glob-pattern/50010093) -- need to come up with a glob pattern

**Comment by NatalieEO** [comment]
Downloaded 1.9.0-alpha.8 from quay and saw the jar within container is not a SNAPSHOT JAR
