### ISSUE TITLE
Calls from Swagger/OpenAPI UI on dev.dockstore.net don't work

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3217]
## Bug Report

When you try out an API in the Swagger UI for dev.dockstore.net, it fails. The generated curls are missing a `/api`, i.e., instead of generating `curl -X GET "https://dev.dockstore.net/api/api/ga4gh/v1/metadata"` it just generates `curl -X GET "https://dev.dockstore.net/api/ga4gh/v1/metadata"`. Seems like basepath needs to be set in the openapi.yaml. But it looks like OpenAPI doesn't have basepath :(. May need to dynamically generate a server url.

### Steps to reproduce

1. Goto https://dev.dockstore.net/api/static/swagger-ui/index.html#
2. Try an API call

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1207)
┆Issue Type: Story
┆Issue Number: DOCK-1207

**Comment by garyluu** [comment]
Oh it's actually better than when I last checked.  It didn't have any info before

**Comment by denis-yuen** [comment]
Calls now actually work, some follow-up to do at #1444
