### ISSUE TITLE
No events found message should have user friendly text for the link

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3219]
## Feature Request 

If you have no events, the message displays a link whose text is the same as the link.

We typically display descriptive text instead of actual links. Expecting something like:

"No events found. Star entries or organizations to see events for them. Read the documentation to learn how to star entries." Or "...Learn how to star organizations and workflows in the documentation". Or...

![Screen Shot 2020-02-06 at 10 22 27 AM](https://user-images.githubusercontent.com/1049340/73966309-a100cf80-48ca-11ea-9863-d1510e2f6fb9.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1208)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1208

**Comment by garyluu** [comment]
About that...it was done on purpose because the "friendly text" looks identical to normal text.  Without a style change, it would not be obvious enough to the user.

**Comment by denis-yuen** [comment]
Is this comment in the right ticket? I don't follow.

**Comment by garyluu** [comment]
yes, right ticket.  Basically `[documentation](https://blahblahblah)` would look identical to `documentation`. No one would be able to tell it was a link unless they hovered over it.  Unless there's a style change.

**Comment by coverbeck** [comment]
I feel there should be a style change. It's also hard to tell the current link is a link, even with the text being a fully-qualified URL.

**Comment by garyluu** [comment]
Go for it :smile:

**Comment by garyluu** [comment]
@coverbeck can you provide the recommended style change? just underline or...?

**Comment by coverbeck** [comment]
Not sure; the main thing I was concerned about that it not be the literal text of the link.

The external link icon with an underline?

**Comment by garyluu** [comment]
Doesn't the link icon not make much sense when used in sentences?

**Comment by garyluu** [comment]
In more detail...we currently have several ways of displaying links right now.

1. Black sentence text:  use blue link with underline on hover
2. Link only: use blue link with underline on hover
3. External link only: use blue link + icon with underline on hover
4. Blue sentence text: use blue link (full URL) with underline on hover

So the idea is we change 4 to something that doesn't use full URL while still remaining as consistent to the others as possible.

**Comment by garyluu** [comment]
Nope, it's pretty uncommon for there to be blue sentences

**Comment by coverbeck** [comment]
> Doesn't the link icon not make much sense when used in sentences?

Probably not... I was just trying to think of something off-hand.

**Comment by garyluu** [comment]
so I think the current solution is just to remove number 4 by simply not using blue sentences no matter what

**Comment by NatalieEO** [comment]
Link text is no longer the full url and stands out more against the black text
API - 1.9.0-beta.2 dockstore status indicator
UI - 2.6.0-rc.3
