### ISSUE TITLE
Checksums for tool images can be missed if there are a lot of tags

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3233]
**Describe the bug**
The code that grabs the image and checksum info `getImagesForTag()` in `QuayImageRegistry.java` does not get all Tags for a Tool because the code does not page through when the response is too big.

**To Reproduce**
1. Find a Tool you want to register that has many Tags
2. Try to refresh the Tool on Dockstore and see that it misses grabbing checksum/image info

**Expected behavior**
Should grab the image info for all the tags that we have on the Dockstore side

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1211)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 31 Flounder
┆Issue Number: DOCK-1211
┆Epic: Implementation of Docker checksum harvesting for workflows

**Comment by garyluu** [comment]
How many tags are we talking? Also, got an example repo that I might have access to?

**Comment by NatalieEO** [comment]
I'm not entirely sure if this still happens for quay images since Denis rewrote that section. But an example would be 
https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow:2.2.0?tab=info
https://docs.quay.io/api/swagger/#!/tag/listRepoTags

It also is the case for DockerHub. I searched a bit, but haven't found an example of one registered on Dockstore that has too many tags. But if something like this https://hub.docker.com/_/postgres?tab=tags was registered on Dockstore with so many tags, then the code I wrote for tools does not perform another curl to page through.

**Comment by garyluu** [comment]
Ok, locally I tried loading the censor DB which doesn't have images for this tool and refreshed.  After the refresh, It seems to have the images for each workflowVersion.  Not sure if it's still an issue.

**Comment by denis-yuen** [comment]
> I'm not entirely sure if this still happens for quay images since Denis rewrote that section.

My understanding is that my changes should not have affected pagination.

**Comment by garyluu** [comment]
Tried Docker Hub, since it's Manual mode only, it does not automatically create a new Dockstore version for every tag.  When I manually add a new tag, it successfully adds the Image object.  All current published Docker Hub tools seem to have few tags so I can't really test with that either.

**Comment by denis-yuen** [comment]
Not sure if typo, but this will not happen for Docker Hub since we don't look at build information for it. 
This should be a QuayImageRegistry.java - only thing because their response limits the builds they return. 
IIRC (and it has been a while), they just return a list of n builds that can range across all tags and branches. So if there have been a lot of builds historically, then I think their API claims to paginate and we can miss tags that are beyond n.

**Comment by garyluu** [comment]
Tried our 3 tools with the most tags (pcawg_delly_workflow, pcawg-bwa-mem-workflow, pcawg-dkfz-workflow) and it seems to populate each version with images just fine. 

Also tested https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/QuayImageRegistry.java#L84

with calico/node and it seems to grab 500 tags which I find to be good enough.  Not sure what else to do.

**Comment by denis-yuen** [comment]
1. Let's figure out is paginated and code comment in our code links to how we found out certain things are paginated (swagger for particular version)
2. See if we can test pagination by artificially setting a low limit and look for headers that say what the next page is (might need to edit quay.io swagger)

**Comment by NatalieEO** [comment]
Okay, made a >500 tags on quay and I can the checksums for them

API - 1.9.0-alpha.8-SNAPSHOT
UI - 2.5.1-rc.1-34-gd99a76c6
