### ISSUE TITLE
Store error messages for lambda functions and store to database, make accessible through API

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3238]
If there is an error with a lambda call (ex. GitHub app + services), there is no way for the user to tell what the error is. We should store any failure of the lambda in Dockstore. A table should be created with fields such as GitHub user, tag version, repository path, error message, entry. There also must be a user endpoint for grabbing their errors (sorted with most recent first). A user should also be able to dismiss errors.

Consider: These sound a lot like user specific notifications, we should consider implementing a generic notification system for users, and errors from lambda calls would just be one type of message. The current org request system could also be moved to this generic notification system.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1214)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1214

**Comment by NatalieEO** [comment]
Was able to use https://dev.dockstore.net/api/static/swagger-ui/index.html#/lambdaEvents/getLambdaEventsByOrganization to see past events/errors.
API - 1.9.0-alpha.11-SNAPSHOT
UI - 2.6.0-rc.0-25-g2ee44acb
