### ISSUE TITLE
Error refreshing workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3245]
**Describe the bug**

A constraint violation happens when refreshing https://dockstore.org/my-workflows/github.com/broadinstitute/gatk-sv-clinical

**To Reproduce**
1. Go to https://dockstore.org/my-workflows/github.com/broadinstitute/gatk-sv-clinical
2. Click on Refresh
3. See "[HTTP 500] OK: org.hibernate.exception.ConstraintViolationException: could not execute statement could not execute statement ERROR: duplicate key value violates unique constraint "uk_encl8hnebnkcaxj9tlugr9cxh" Detail: Key (workflowversionid)=(26701) already exists."

**Expected behavior**

Refresh should succed with an error

**Screenshots**

**Additional context**
 - UI version: 2.5.0
 - Webservice version: 1.8.0
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1220)
┆Issue Type: Story
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-1220

**Comment by garyluu** [comment]
Possible lead to look into:

Check that the version metadata extraction code works for existing versions that do not have version metadata

**Comment by coverbeck** [comment]
@cwhelan: we are having troubles reproducing this locally, even though we see your errors in the logs.

This is a long-shot and it shouldn't make a difference, but would you mind trying one more refresh of the workflow? Please wait at least 20 minutes (lots of buffer-time, just to be safe), and don't refresh again during those 20 minutes. This is a fairly long running operation, as it can end up reading almost all your files in all your branches in the repo. I find it unlikely to be the case, but I just want to make sure that overlapping refreshes of a workflow aren't causing the problem.

Looking at the logs, it looks possible that overlapping refreshes for the same workflow might have been happening. 

Thanks,

Charles

**Comment by cwhelan** [comment]
@coverbeck I just tried again in a fresh browser tab and and made sure to only hit the page once. I got the same error:

warning The webservice encountered an error.

[HTTP 500] OK: org.hibernate.exception.ConstraintViolationException: could not execute statement could not execute statement ERROR: duplicate key value violates unique constraint "uk_encl8hnebnkcaxj9tlugr9cxh" Detail: Key (workflowversionid)=(26701) already exists.

**Comment by coverbeck** [comment]
@cwhelan Thanks for trying and sorry it didn't work.

Looking at our logs, the error you are getting is happening for the branch `cw_sync_wdls`. Is it feasible for you to delete that branch, and to then try refreshing in Dockstore again? If you need the branch history, then create another branch off of it with a different name, e.g., `cw_sync_wdls2` before deleting `cw_sync_wdls` -- our refresh logic is based on the branch name, so hopefully if you get rid of that branch, you'll get past that error.

I'm proposing this as a temporary solution so that you can get your latest changes on Dockstore, and I'm not even sure it will work. It's obviously not a real solution, but the problem seems to be some sort of race condition that we cannot reproduce yet. This might be a short-term workaround.

If you really need the branch with that name, another idea is that you could delete it on GitHub-only, but not locally, refresh, then push it again from your local copy.

**Comment by cwhelan** [comment]
@coverbeck I just tried deleting that branch on GitHub and got the same error. Then I tried deleting all of my other merged branches (I had a few that I hadn't deleted after merging). Still no dice, though -- the same error pops up.

**Comment by coverbeck** [comment]
@cwhelan Can you please try refreshing one more time? We believe we have fixed the problem in the database.

Please make sure not to do another refresh while one refresh is still going on. We discovered that can lead to duplicate versions which leads to the constraint problem you were seeing -- #3252.

We are working on a fix for #3252, but until that fix is deployed, please be careful to not have overlapping refreshes.

FYI, we're also working on slightly longer term fix using GitHub Apps where you won't need to manually refresh at all; refreshes will happen automatically.

**Comment by cwhelan** [comment]
@coverbeck Thanks, I'm now able to refresh the workflow through the UI successfully.
