### ISSUE TITLE
Stacked buttons (Search)

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3249]
**Describe the bug**
Buttons look "odd"

**To Reproduce**
1. Go to /search
2. Reduce browser width
See that the buttons are stacked on top of each other with different widths

**Expected behavior**
The buttons to look "better"
The buttons probably should not be different widths.
The buttons probably should have padding between them

**Screenshots**
https://user-images.githubusercontent.com/6299530/69269413-f61c2780-0b9e-11ea-8d55-d7414695d76f.png

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari
 - Version N/A

**Additional context**
API - 1.8.0
UI - 2.5.0
dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1224)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1224

**Comment by garyluu** [comment]
Related to https://github.com/dockstore/dockstore/issues/3031

**Comment by NatalieEO** [comment]
Buttons don't stack oddly anymore
API - 1.9.0-alpha.5-SNAPSHOT 
UI - 2.5.1-rc.1-23-g15a49baf
