### ISSUE TITLE
Remove ngx-bootstrap from hosted tools page

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#3251]
**Is your feature request related to a problem? Please describe.**
ngx-bootstrap should be removed from the UI

**Describe the solution you'd like**
Remove ngx-bootstrap entirely or replace its usages with other libraries like Material

**Additional context**

The hosted tools page is currently using ngx-bootstrap tabs under the files section. Instead of using ngx-bootstrap tabs, migrate to use Material tabs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1225)
┆Issue Type: Story
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1225
┆Epic: Remove ngx-bootstrap

**Comment by NatalieEO** [comment]
Not really reviewable, PR approval should be enough.

**Comment by coverbeck** [comment]
@NatalieEO It would be good to verify the behavior of hosted tools is the same/similar as it is in staging prod. Andy changed the tab component from bootstrap to Material, and it would be good to verify no UI broke, like layout or something like that.

**Comment by NatalieEO** [comment]
Good point, took a look and UI functionality seems intact/identical to staging
