### ISSUE TITLE
Overlapping refreshes can cause duplicate workflow versions in database

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3252]
**Describe the bug**

If a second refresh is launched while a refresh is happening for the same workflow, duplicate copies of new versions will be created.

This in turn can lead to #3245 where a user can get errors refreshing a workflow because a database constraint will be violated.

This happens because each invocation of the refresh creates a new Dockstore version object for the corresponding GitHub tag/branch, in parallel. When each refresh finishes, each version object is persisted to the database.

**To Reproduce**
1. Start with a workflow registered in Dockstore
2. In the corresponding GitHub repo, add a new tag or branch
3. Execute near simultaneous refreshes on the workflow. For example I did, because I am an owner of workflow 5095, `curl "http://localhost:8080/workflows/5095/refresh" -H "accept: application/json" -H "Authorization: Bearer $DS_TOKEN" & curl "http://localhost:8080/workflows/5095/refresh" -H "accept: application/json" -H "Authorization: Bearer $DS_TOKEN" &`
4. After step 3 completes, in the database, continuing to use workflow 5095, execute
```
select wv.name, count(*) c from workflowversion wv, workflow_workflowversion wvv
where wv.id = wvv.workflowversionid and wvv.workflowid = 5095
group by wv.name
order by c desc
```
The new tag has a count of 2.
5. Alternatively, you can just query the the workflow with the Dockstore API.

**Expected behavior**
There should only be one Dockstore version for each GitHub tag/branch

**Additional context**
 - UI version: 2.5.0
 - Webservice version: 1.8.0
 - host location: dockstore.org

See [this StackOverflow page](https://stackoverflow.com/questions/27107034/constraint-to-check-values-from-a-remotely-related-table-via-join-etc) with some thoughts on how to fix it -- either triggers or redundant columns. We could also try to solve it in the webservice with locks, but that solution wouldn't scale.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1226)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1226

**Comment by coverbeck** [comment]
Further thought: this is a one-to-many relationship, but we have an intermediate join table. If we got rid of the join table, then we could have a constraint in the workflow versions table to avoid duplicate names for the same workflow. Getting rid of the extra table would also improve performance (maybe not significantly in our case) and reduce storage in the database.

See [this article](https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/) for a discussion on Hibernate and one-to-many relationships.

**Comment by garyluu** [comment]
Seems to work on dev.dockstore.net when replaying refresh multiple times.
