### ISSUE TITLE
CircleCi database migration proposal should show the expected migration file

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3253]
The proposed migrations by CircleCI only prints the changeSet tags, without any content. So you can tell how many changeSets are missing, but have no idea what they are. Would be useful to display the changeSet information. It is possible that this worked before but broke at some point.

Below is what we currently see in the CircleCI output.

```
grep changeSet dockstore-webservice/target/detected-migrations.xml
    <changeSet author="circleci (generated)" id="1582059440430-1">
    </changeSet>
    <changeSet author="circleci (generated)" id="1582059440430-2">
    </changeSet>
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1227)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1227

**Comment by denis-yuen** [comment]
Hah, I think I might have had that idea at some point but I don't think I ever went that far.

**Comment by agduncan94** [comment]
Looking at 1.9.0-alpha.7, the changeset is now printed out.

**Comment by agduncan94** [comment]
Looking at 1.9.0-alpha.7, the changeset is now printed out.
