### ISSUE TITLE
Ability to delete organisations that are rejected

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3254]
Currently if an organisation has been rejected, it will just stay there name squatting until someone tries to re-request review. Users should be able to delete rejected organisations.

Also consider deleting organisations at other lifecycle stages.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1228)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 41 Pufferfish
┆Issue Number: DOCK-1228
┆Epic: Organization Improvements

**Comment by coverbeck** [comment]
Verified that this works on dev. Created a pending org in the UI, then deleted it via API (Swagger).
