### ISSUE TITLE
Display webservice git-commitID on UI footer

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3256]
**Describe the solution you'd like**
We've exposed the git commit of the running webservice build through the metadata/config endpoint. We now need to show this on the UI, possibly by appending to current API version ex: `API - 1.9.0-alpha.1-SNAPSHOT - a5ec081`.

Considerations: 
* might want to display/hide differently on production vs staging vs dev.dockstore (probably not necessary to show on production)
* Could remove 'SNAPSHOT' in current display in favor of the commit-ID, otherwise might be too long

**Additional context**
related to #3157

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1230)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1230
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
This has been fixed for a while.
