### ISSUE TITLE
Investigate Galaxy file highlighting for Ace Editor

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3268]
We should see if Galaxy has a syntax highlighter for their .ga files. If they don't consider either creating one or at least using the built in JSON highlighter for these files.

https://github.com/dockstore/dockstore/issues/3186

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1234)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1234

**Comment by garyluu** [comment]
Hmm...the first google result for "galaxy syntax highlight" does not quite return what i expect

**Comment by Ldcabansay** [comment]
Confirmed that JSON highlighter is working for .ga files as of UI - 2.5.1-rc.1-27-ga1115870. The whole file is still scrunched into one line though so its not really readable, but is highlighted.

**Comment by coverbeck** [comment]
Hmm, wonder if single line will addressed by dockstore/dockstore-ui2#934? Do you mean the editor is one line high, or do you mean that the text doesn't have any new lines and is one very wide line?
