### ISSUE TITLE
Add column to image table to store registry

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3275]
**Is your feature request related to a problem? Please describe.**
It was fine for tools since we can get the registry from the tool table, but can't do that for images within workflows. Should be storing which registry images come from in the image table. 

**Describe the solution you'd like**
Add column in image table and store registry info for images from tools and workflows.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1238)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1238
┆Epic: Implementation of Docker checksum harvesting for workflows

**Comment by coverbeck** [comment]
Verified that column has been added and that when you snapshot a version, it correctly populates on dev.dockstore.net.
