### ISSUE TITLE
Search Table Mobile Small Columns

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3277]
**Describe the bug**
Some search table columns are too small when on mobile or small browser window

**To Reproduce**
1. Go to the search page
2. Reduce your browser window to under 600px width

See really small name column

**Expected behavior**
There should be no extremely small name column

**Screenshots**
https://user-images.githubusercontent.com/1049340/71379699-1e71ba00-2581-11ea-8764-9421c3ca5cd3.PNG

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Chrome
 - Version: [0-9]+

**Smartphone (please complete the following information):**
 - Device: a potato

**Additional context**
 - API - 1.8.1 dockstore status indicator
 - UI - 2.5.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1239)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1239

**Comment by garyluu** [comment]
Related to #3031

**Comment by david4096** [comment]
I can confirm that this is fixed on dev

API - 1.9.0-alpha.6-SNAPSHOT
UI - 2.5.1-rc.1-31-gfe78544f

![image](https://user-images.githubusercontent.com/3795586/78281565-b6ac0300-74cf-11ea-9c6f-ac18eaec27d4.png)
