### ISSUE TITLE
Remove orphaned services when deleting user

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3291]
**Describe the bug**
UserResource.deleteSelfFromEntries() deletes tools and workflows from a deleted user (#1766), but hasn't been updated to include services. There might be other similar occurrences in the code that also need to be updated to include services. Assignee should investigate if other cases exist and spin out to new tickets as needed.

**Expected behavior**
Orphaned services should show similar delete behavior to orphaned tools and workflows when a user is deleted. See #1766 and #1697

@david4096 not sure how this is impacted by the delete/archive plan

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1249)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1249

**Comment by GFJHogue** [comment]
Note: In my scanning of the code, I've not been able to find other similar cases where Services aren't included where Tools/Workflows are.

**Comment by denis-yuen** [comment]
I think this is ok, there isn't any user-facing feature to really review here.
