### ISSUE TITLE
In UI, Dockstore should say "Galaxy" instead of gxformat2

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3292]
**Is your feature request related to a problem? Please describe.**
In the UI, e.g., on the search page and when you register a Galaxy workflow, the UI displays `gxformat2`. That is not very user friendly.

**Describe the solution you'd like**
It should say "Galaxy" or maybe "Galaxyv2".

![Screen Shot 2020-03-02 at 4 11 38 PM](https://user-images.githubusercontent.com/1049340/75730042-8559d080-5ca0-11ea-9a14-eaadefb5c9fc.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1250)
┆Issue Type: Story
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1250

**Comment by garyluu** [comment]
Need to structure this issue in terms of DescriptorLanguage.java

**Comment by denis-yuen** [comment]
Heads-up, will touch dockstore-deploy due to https://github.com/dockstore/dockstore/issues/3292

**Comment by garyluu** [comment]
> Heads-up, will touch dockstore-deploy due to #3292

which issue?

**Comment by denis-yuen** [comment]
Hmmm, was meant to be https://github.com/dockstore/dockstore-deploy/commit/b86ea7c7a6a7788d5c298629e81cbc338b0c0506#diff-71ae6304f9b90307912f12d75762faddR160

**Comment by Ldcabansay** [comment]
Verified that UI now shows the short friendly name 'Galaxy' as of UI - 2.6.0-rc.0-6-gd31307df
