### ISSUE TITLE
Eliminate refresh all

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3295]
**Is your feature request related to a problem? Please describe.**
Refresh all is too slow and bug-prone, should be eliminated

**Describe the solution you'd like**
Make sure that we can do everything uncommon that refresh all normally does in other ways
1. Be able to add new organizations (should be able to do through whitelist wizard or manual register)
2. Be able to add self to workflows others have created that you should have accessible (refresh by organization or sync for .dockstore.yml workflows)

Then eliminate the refresh all button in the UI and eliminate the endpoint/orphaned code

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1251)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 31 Flounder
┆Issue Number: DOCK-1251

**Comment by Ldcabansay** [comment]
Verified that endpoints and UI components relating to refresh all are gone as of: 
API - 1.9.0-alpha.8-SNAPSHOT 
UI - 2.5.1-rc.1-34-gd99a76c6
