### ISSUE TITLE
Quay.io build broken

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3297]
**Describe the bug**
The web service is failing to build on quay.io

**To Reproduce**
1. Go to https://quay.io/repository/dockstore/dockstore-webservice
2. See failed builds

**Expected behavior**
Builds should succeed

**Additional context**

Pretty sure this is due to yq.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1253)
┆Issue Type: Story
┆Issue Number: DOCK-1253

**Comment by denis-yuen** [comment]
Is present and builds properly on quay.io
