### ISSUE TITLE
Refresh individual version

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3301]
**Is your feature request related to a problem? Please describe.**
Based on discussions regarding dockstore.yml files and migrations, it would be useful to have the ability to refresh a specific version of a workflow. This would be able to refresh workflow versions that do not exist on Dockstore (but do on GitHub, Bitbucket, etc.).

**Describe the solution you'd like**
Endpoint that given a workflow on dockstore and a version name, will do an individual refresh on only that version. Also need to update the UI to have refresh individual versions. If versions already exist we could do this in the action column, but for new versions we would have to think of another option.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1254)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1254

**Comment by Ldcabansay** [comment]
Refreshing individual version works for some workflows and not others. Spun off bug into separate ticket #3452
