### ISSUE TITLE
Quickly Register Remote Bitbucket Workflow

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3303]
**Describe the bug**
When something is wrong with the bitbucket token and trying to register a bitbucket workflow with "Quickly Register Remote Workflow", the error message says to relink GitLab instead.

**To Reproduce**
1. Make sure your bitbucket token is wrong (but exists)
2. Go to "Quickly Register Remote Workflow"
3. Select bitbucket.org

**Expected behavior**
Error should say to relink bitbucket token

**Additional context**
 - UI version: 2.5.1
 - Webservice version: 1.8.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1255)
┆Issue Type: Story
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1255

**Comment by NatalieEO** [comment]
Correctly says bitbucket on quick register
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.6.0-rc.0-9-g264e5615
