### ISSUE TITLE
timestamps on news and updates UI

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3307]
**Is your feature request related to a problem? Please describe.**
UI for news and updates items don't have associated dates or timestamps, making it difficult to tell how stale or recent an announcement might be.

**Describe the solution you'd like**
It'd be nice to surface the date/timestamp of news and updates items on the UI. The dbCreateDate and dbUpdateDate are already returned in the response on the notifications endpoint. Ideas for how to display:

- automatically append to end of message

- Alternatively can surface using a tooltip, similar to organization events  

**Describe alternatives you've considered**
We could manually add the date/timestamp as part of the message, but ideally it would be automated

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1257)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 38 Manatee
┆Issue Number: DOCK-1257

**Comment by GFJHogue** [comment]
So the way I see to do this is using https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/shared/date.service.ts to produce a string from `dbCreateDate`.

With the existing functions we effectively get 2 options for timestamp text (ignoring how we want to format it for now):
- `getDateTimeMessage` ![Screenshot_2020-06-25 Dockstore(1)](https://user-images.githubusercontent.com/5513934/85775536-de38f300-b6ed-11ea-90d9-eebd74e78d1d.png)
- `getAgoMessage` ![Screenshot_2020-06-25 Dockstore](https://user-images.githubusercontent.com/5513934/85775617-edb83c00-b6ed-11ea-8963-d40587bf5157.png)

I personally like the ago message, but it feels like adding `X weeks ago` to `getAgoMessage()` would make it look better.

Also do we like the look of appending the date to the end of the message?

@Ldcabansay @denis-yuen

**Comment by denis-yuen** [comment]
The recent activity widget on the bottom of the page uses a different format (looks more like the former, but with a soft line break), so they should probably be consistent. 

Otherwise, both seem reasonable to me except I don't think we need second-by-second granularity

**Comment by GFJHogue** [comment]
Thanks for pointing out Recent Activity, I hadn't followed anything yet, but now that I see it mimicking that makes the most sense.
Also disregard everything I said about the `data.service.ts` because I didn't realize that https://angular.io/api/common/DatePipe is a thing.

@denis-yuen here I tried to make it look similar to recent activity, but only date, no time, and no soft line break:
![Screenshot_2020-06-25 Dockstore(2)](https://user-images.githubusercontent.com/5513934/85793647-52ca5c80-b703-11ea-91d4-737bc16a7d7b.png)
