### ISSUE TITLE
TRS endpoints relating to versions not working for hosted tools

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3317]
**Describe the bug**
GA4GH/TRS V1 and V2 endpoints relating to versions are not working as expected for hosted tools. They either return an empty response or fail completely. This bug seems to only be affecting hosted tools, all other entry types are working as expected. Dockstore API endpoints relating to hosted tool versions are also working as expected.

Example endpoints affected:

- /api/ga4gh/v1/tools/{id}/versions

- /api/ga4gh/v1/tools/{id}/versions/{version_id}

- /api/ga4gh/v2/tools/{id}/versions

- etc

**To Reproduce**
[Hosted tool example](https://dockstore.org/containers/registry.hub.docker.com/jamesrcounts/variantspark/variant-spark:3?tab=info), TRS id: `registry.hub.docker.com/jamesrcounts/variantspark/variant-spark`

[Non-hosted tool example](https://dockstore.org/containers/quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0?tab=info), TRS id: `quay.io/pancancer/pcawg-bwa-mem-workflow`

1. Query one of the ga4gh endpoints involving versions like `/api/ga4gh/v1/tools/{id}/versions` using TRS id any other needed info

2. Hosted tool will fail

3. Non-hosted tool (and every other entry type) will give expected response

**Additional context**
 - Webservice version: affects production (1.8.1), staging (1.8.1), hotfix (1.8.2), dev

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1261)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1261

**Comment by denis-yuen** [comment]
:cry:

**Comment by garyluu** [comment]
Version seems to be skipped when there's no ImageId, are hosted tools supposed to have it?

**Comment by denis-yuen** [comment]
On the other hand, didn't see https://github.com/dockstore/dockstore/pull/3330/files in JIRA. 
That could work too

**Comment by Ldcabansay** [comment]
Verified that TRS endpoints relating to versions for hosted tools now return a non-empty response as of API - 1.9.0-alpha.9. Spun off underlying image ID issue into separate ticket #3448
