### ISSUE TITLE
UI not redirecting to maintenance page

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3319]
**Describe the bug**
If the web service is down, the UI should redirect to the maintenance page.

As I'm writing this issue up, dev.dockstore.net web service is down, but navigating to dev.dockstore.net in the browser does not take me to the maintenance page.

**To Reproduce**
1. Go to dev.dockstore.net when the web service is down
2. You end up on home page instead of maintenance page

**Additional context**
 - UI version: UI - 2.5.1-rc.1-21-g29851811
 - host location: dev.dockstore.net

In browser tools, the Ajax requests are failing with 404s, our code tests for a 504 status code to redirect.

That is probably the cause, and I don't know why it's returning 404s -- could be a load balancer setting.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1263)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1263

**Comment by coverbeck** [comment]
There are at least 3 scenarios:

1. Things are normal, the user goes to the web site, the UI is loaded.  Then the stack goes down.
2. The stack is completely down before the user even attempts to go there.
3. The stack is up, except for the webservice container. For example, it is constantly restarting due to bad config settings.

As this bug was written up, it was covering case 3. The UI will get loaded in the browser, because the UI is loaded via the nginx_dockstore container. What then happens is that Ajax requests are redirected via nginx to a non-existent or partially up container, which returns a 404, which bubbles back up to the browser.

We do not handle case 1. The footer does the check for the web service working when the UI initially loads, i.e., when you first navigate to dev.dockstore.net, but does not check again. If the stack subsequently goes down, the user will get errors on the failing Ajax requests, but nothing will cause a redirect to the maintenance page.

Case 2 is "handled" by the UI never loading in the first place. We could improve that experience by going all out CloudFront, and I think there's another ticket for that.

Proposed solution for this is:

1. Assume a 404 for the endpoint the footer is invoking can also mean web service is down. Don't want to do this for all endpoints.
2. Add some additional checks, not sure yet how/where, to see if the service is up.

**Comment by denis-yuen** [comment]
1. could be interesting, I'm assuming it becomes 3 if the webservice container goes down (but not the nginx container)
