### ISSUE TITLE
Inform users how migration to dockstore.yml works

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3322]
**Is your feature request related to a problem? Please describe.**
Users with existing workflows on Dockstore will need to learn about the new way we update workflows, how to migrate to this new method, and how this may change their flow.

**Describe the solution you'd like**
Ideas
* generate skeleton/example base dockstore.yml and show to user to show them what file would look like for their workflow
* if current workflow is old method, user will see icon or something which links to how to migrate doc
* update registration flow with warning if user tries the old method

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1265)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1265

**Comment by agduncan94** [comment]
@denis-yuen What do you think the best approach is? Do you think all of the above should be done (first idea listed might be a bit time consuming but probably worth it)

**Comment by denis-yuen** [comment]
Reviewed as part of usability review
