### ISSUE TITLE
Upload lambdas to s3 as part of continuous integration

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3324]
**Is your feature request related to a problem? Please describe.**

Lambda deployment packages should be uploaded to s3 when the source in our [GitHub repo](https://github.com/dockstore/lambda) changes.

**Describe the solution you'd like**

A deployment package is a [zip with the source code](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html). When pushes to GitHub happen, we should via CircleCI create and upload the lambda deployment packages to an s3 bucket. We should follow the pattern we use for the UI and featured content -- <branch/tag name>-<first 7 characters of sha>

Before uploading, there should also be some sort of testing for the lambdas; ideally at least make sure they don't have syntax errors.

Cloudformation templates will deploy the deployment packages.

**Additional context**

Currently our lambdas have been created in the AWS console UI and saved to source control afterwards. This will reverse the flow.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1266)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1266
┆Epic: Continuous Deploy

**Comment by denis-yuen** [comment]
Ticket should either include or spawn a documentation tickets afterwards explaining "this how we should work with Lambdas as a developer"
