### ISSUE TITLE
Best Practices document for Dockstore

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#3334]
**Is your feature request related to a problem? Please describe.**
I would like better documentation on how to import workflows. 

**Describe the solution you'd like**
I would like an overall best practices document for generating workflows in Dockstore. I would specifically like for it to include:
- instructions for adding labels to improve the faceted search feature in Dockstore (for example: including a term for the type of analysis like "gwas"). If there is a way for Dockstore to show the top keyboards used or suggested naming conventions, it could help to provide better search capabilities. for example, always lowercase letters, spaces used as main separators?
- very detailed documentation in markdown files available with the workflow; maybe you can give example layouts for the markdown file: about/how to use workflows/example tutorials/author contacts
- include workflows that link together in a "collection" and use the markdown feature to describe how the workflows work together (e.g. in sequence?)
- suggestions/links to any current tutorials in other platforms where these workflows are used
- maybe also other best practices around github (master branches?)
- this document could link out to the best practices for each language

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1271)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1271

**Comment by agduncan94** [comment]
This is a great idea. I think it could even lead to a webinar for best practices for using Dockstore.
