### ISSUE TITLE
Version is valid but descriptor not found

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3335]
**Describe the bug**
A published [workflow](https://dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/multi_sample_assemble_kraken:master?tab=versions) is indicated as having valid versions, but when checking the files tab an error occurs and the descriptor file is not displayed: 
![image](https://user-images.githubusercontent.com/23464754/77126895-db03dc00-6a07-11ea-8209-7aeac3b3b4e6.png)
On an [invalid version](https://dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/multi_sample_assemble_kraken:dp-terra?tab=files) of this same workflow, the files tab displays the main descriptor but an error is still observed:
![image](https://user-images.githubusercontent.com/23464754/77126953-04246c80-6a08-11ea-8fb7-96cf8e4ff801.png)

**To Reproduce**
See [workflow versions](https://dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/multi_sample_assemble_kraken:master?tab=versions) and [files tab](https://dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/multi_sample_assemble_kraken:master?tab=files).

**Expected behavior**
When given a correct path, the main descriptor should be displayed in the file tabs especially since this is presumedly a valid wdl (given we can display the invalid version). Or in the case where the descriptor can't be found then the version should be invalid

**Additional context**
 - UI version: 2.5.1
 - Webservice version: 1.8.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1272)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1272

**Comment by coverbeck** [comment]
This looks like a TRS issue, it's having troubles resolving the relative path. Examples using a local build:

```
~/git/dockstore/dockstore$ curl -s -X GET "http://localhost:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fbroadinstitute%2Fviral-pipelines%2Fcso-kraken/versions/master/WDL/files" -H  "accept: application/json" | jq '.'
[
  {
    "file_type": "SECONDARY_DESCRIPTOR",
    "path": "../tasks/tasks_assembly.wdl"
  },
  {
    "file_type": "SECONDARY_DESCRIPTOR",
    "path": "../tasks/tasks_demux.wdl"
  },
  {
    "file_type": "SECONDARY_DESCRIPTOR",
    "path": "../tasks/tasks_metagenomics.wdl"
  },
  {
    "file_type": "SECONDARY_DESCRIPTOR",
    "path": "../tasks/tasks_reports.wdl"
  },
  {
    "file_type": "SECONDARY_DESCRIPTOR",
    "path": "../tasks/tasks_taxon_filter.wdl"
  },
  {
    "file_type": "PRIMARY_DESCRIPTOR",
    "path": "multi_sample_assemble_kraken.wdl"
  }
]
```

Fetching multi_sample_assemble_kraken.wdl works

But fetching one of the files with the `..` in front of it gives a 404:

```
curl -X GET "http://localhost:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fbroadinstitute%2Fviral-pipelines%2Fcso-kraken/versions/master/WDL/descriptor/..%2Ftasks%2Ftasks_assembly.wdl" -H  "accept: application/json"
```

Fetching the workflow with the Dockstore API does return all the files.

**Comment by coverbeck** [comment]
Started to debug it a little, but gave up. I think the problem starts a call to `cleanRelativePath` in `io.swagger.api.impl.ToolsApiServiceImpl#getFileByToolVersionID`, which converts `../tasks/tasks_assembly.wdl` to `tasks/tasks_assembly.wdl`, which seems wrong

**Comment by denis-yuen** [comment]
Taking notes for tomorrow
http://phoenix:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/CWL/files
goes to http://phoenix:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/PLAIN_CWL/descriptor/..%2F..%2Ftools%2Fbam_readgroup_to_json.cwl fine

http://phoenix:8080/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fbroadinstitute%2Fviral-pipelines%2Fmulti_sample_assemble_kraken/versions/master/PLAIN_WDL/descriptor/..%2Ftasks%2Ftasks_assembly.wdl
Has problems even though encoded.
Issue seems to be something to do with the normalization of the nested working directory, they both have one but something about the WDL version causes an issue

**Comment by NatalieEO** [comment]
forked and registed same repo mentioned in issue. For versions where the primary descriptor can't be found, it lists the version as invalid. And for versions where it can be found, but has an alert, it is marked as invalid.
API - 1.9.0-alpha.9-SNAPSHOT 
UI - 2.6.0-rc.0-11-g384e1614
