### ISSUE TITLE
Elasticsearch Indexing Too Much Information

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3337]
**Describe the bug**
Need to review what's being stored in elasticsearch.

Starred users should not be sent to elasticsearch at all.

Some things to consider:
- storing sourcefiles of every version is probably overkill (it only helps with the text search functionality)
- storing every version might also be too much (maybe just store default)

**To Reproduce**
1. Go to ElasticListener and debug from IDE
2. Try indexing endpoint
3. Observe what's being indexed

**Expected behavior**
Only the information required for the frontend facets + text search are required

**Additional context**
 - host location: all

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1274)
┆Issue Type: Story
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1274

**Comment by agduncan94** [comment]
The search is returning 50mb results. Takes very long to load.

**Comment by garyluu** [comment]
The information it returns should only be what's necessary to populate the search tables,

**Comment by denis-yuen** [comment]
hmmm, clarification needed. Are you saying that it "should" return only what is necessary or do you think that it "already" returns only what's necessary?

**Comment by garyluu** [comment]
should
