### ISSUE TITLE
Name should not be a required field for Dockstore yml workflows

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3344]
**Describe the bug**
Cannot register a dockstore.yml workflow unless the name is set.

**To Reproduce**
Try to register a dockstore.yml workflow without a name (workflowname)

**Expected behavior**
Should register a workflow that has no workflow name set.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1277)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1277

**Comment by coverbeck** [comment]
@agduncan94 reassigned to myself as I'm tackling this as part of #3237
