### ISSUE TITLE
Always have default workflow version set

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3345]
**Is your feature request related to a problem? Please describe.**
The workflow class has a defaultVersion field. The request is that it should never be null (although this may not be possible, see below).

See #3296 and in particular [this comment](https://github.com/dockstore/dockstore/issues/3296#issuecomment-600920425) for why a null defaultVersion can lead to problems, but TLDR;

If defaultVersion is not set, UI makes the most recently updated version the default version. Because the most recently updated version can change as the workflow is developed, the UI's default version can change without the user consciously realizing it.

**Describe the solution you'd like**
Ideally the defaultVersion column would have a not null constraint. For existing workflows that don't have the default set, we could migrate setting the default version using the same logic the UI uses. 

However, there might be an edge case that doesn't allow for that: if a workflow had no versions. So maybe we have just have to ensure it in code.

Also see #3340, where there are defaultVersion values pointing to non-existent versions -- may want to tackle that as part of this.

Another idea is not make the defaultVersion a String, and instead use a foreign key. This would solve #3340, although it still doesn't solve the no versions case.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1278)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1278

**Comment by denis-yuen** [comment]
See also #3340

**Comment by coverbeck** [comment]
Tested on dev:

# Had a tag 1.0.4 as the default version
# Deleted the tag  1.0.04 on GitHub
# Refreshed the workflow
# Version disappeared from versions table, correctly, but there was no longer a default version, even though other versions are still present.

@garyluu Is it supposed to pick a default version in this scenario?

**Comment by garyluu** [comment]
It's only going to pick a new default version on refreshes.

**Comment by coverbeck** [comment]
> It's only going to pick a new default version on refreshes.

I had refreshed; that's how the version went away. That means I would have to refresh twice?

**Comment by garyluu** [comment]
hmm...make another issue i guess

**Comment by coverbeck** [comment]
Verified, although spun off #3449.
