### ISSUE TITLE
Endless loading bar when adding version to hosted workflow

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3348]
**Describe the bug**
When you try to add a version to a hosted workflow, the loading bar never stops. But if you refresh the page, you'll see that the version was added at some point.
**To Reproduce**
1. Go to https://dockstore.org/my-workflows/ or on staging. Probably dev too, but didn't check.
2. Create a hosted workflow
3. Try to add a version

**Expected behavior**
I expect the loading bar to stop at some point whether adding the version was successful or not.

**Additional context**
production - API - 1.8.1 dockstore UI - 2.5.1
staging - API - 1.8.2 dockstore UI - 2.5.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1280)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1280

**Comment by coverbeck** [comment]
Saw this one the other day and meant to log it; thanks for capturing it.

**Comment by Ldcabansay** [comment]
I'm seeing this on refreshing a namespace on hosted tools as well. 
Staging UI - 2.5.1
Dev UI - 2.5.1-rc.1-28-g83e35787

**Comment by garyluu** [comment]
Original issue only happens on new hosted workflows

**Comment by agduncan94** [comment]
Fixed in 1.9.0-alpha.9 and 2.6.0-rc.0.
