### ISSUE TITLE
Get Postgres 11 working in Travis

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3354]
**Describe the bug**
Webservcie Travis CI builds started failing on the integration-tests profile. Rolling back from Postgres 11 to Postgres 9 fixed the problem. An [example](https://travis-ci.org/github/dockstore/dockstore/jobs/667051241) -- it's running out of database connections.

**To Reproduce**
Tried running locally and it passed. Seems to fail only on Travis.

**Additional context**

Postgres 11 was implemented on Travis by running it in a Docker container, as Travis CI does not have easy "native" support for 11 like it does for 9. It's possible that's the problem, or part of the problem -- fixer could try running Postgres 9 in a Docker container as a datapoint. 

There's an interesting [article](https://vladmihalcea.com/the-best-way-to-detect-database-connection-leaks/) on how to detect connection leaks in unit tests, which would be a good thing to have regardless.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1284)
┆Issue Type: Story
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1284

**Comment by denis-yuen** [comment]
Can also switch to postgres 10 first as another data point
