### ISSUE TITLE
Investigate need to log out and login again after deploying update

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3361]
**Describe the bug**
After a deploy, browser is left in a state where they might need to log out and login again.
Otherwise, they will see a message saying that they have no workflows.

**Expected behavior**
User should either be logged out or not have to login back in,

**Additional context**
API - 1.8.2 
UI - 2.5.1

Encountered by @bshifaw and @denis-yuen

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1290)
┆Fix Versions: Dockstore 1.11.X
┆Issue Number: DOCK-1290
┆Sprint: Sprint 64-Oceanic shark
┆Issue Type: Bug

**Comment by melainalegaspi** [comment]
@denis-yuen @garyluu @coverbeck See if this happens on staging when we deploy 1.11

**Comment by david4096** [comment]
You can replicate by modifying your `ng2-ui-auth_token` to something incorrect then refreshing the page. It doesn't give 401 errors and let's you browse around
