### ISSUE TITLE
Logging out of Dockstore should give a warning

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3363]
**Is your feature request related to a problem? Please describe.**
When logging out of Dockstore, there should be a warning to log out of the computer.

**Additional context**
If you log out of Dockstore, your OS could still "remember" that you are logged into GitHub and/or Google, and so another user, e.g., on a public computer, could log right back into Dockstore. There should be some sort of a warning about this when the user logs out of Dockstore.

The bigger issue IMHO is that they would have access to your Google and GitHub accounts themselves, but that's outside the scope of this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1292)
┆Issue Type: Story
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1292
┆Epic: Dockstore Compliance

**Comment by NatalieEO** [comment]
There is a warning once you log out
API - 1.9.0-alpha.9-SNAPSHOT 
UI - 2.6.0-rc.0-11-g384e1614
