### ISSUE TITLE
Remove ngx-bootstrap from Advanced Search

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#3364]
**Is your feature request related to a problem? Please describe.**
ngx-bootstrap dependency should be removed from from Deregister Modal Component and Advanced Search Component.

**Describe the solution you'd like**
Replace ngx-bootstrap modal with Material Dialog for the Deregister Modal Component and Advanced Search Component.

**Additional context**
Currently there is an existing issue that is not displayed on dev.dockstore.net where filtering through the Advanced Search would result in the error message of 'Cannot assign readonly property `Filter Option` of '[object Object]' '

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1293)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1293
┆Epic: Remove ngx-bootstrap

**Comment by david4096** [comment]
I can confirm the advanced search modal has changed in dev but I don't think it's working properly. The search terms aren't combining into the query, on staging you can combine `AND` and `NOT` terms.

![image](https://user-images.githubusercontent.com/3795586/81966739-c8082500-95ce-11ea-82c1-c889050818a8.png)

![image](https://user-images.githubusercontent.com/3795586/81966771-d2c2ba00-95ce-11ea-9e7d-7a8e06abb889.png)

This is how it looks on staging

![image](https://user-images.githubusercontent.com/3795586/81966795-deae7c00-95ce-11ea-826f-616056a08e6e.png)

![image](https://user-images.githubusercontent.com/3795586/81966819-e837e400-95ce-11ea-90af-8845f6b4ff10.png)
