### ISSUE TITLE
Create mock-up for user pages

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#3369]
Make clear what needs to be done for user pages in a mock-up.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1297)
┆epic: Add user pages
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-1297
┆sprint: SEAB 81- Jacques
┆taskType: Story

**Comment by agduncan94** [comment]
Bumping.
Also adding that we could also use these pages for registrants of a workflow. For example, if I register and publish a workflow, there would be a link to my profile page on the public workflow site.
