### ISSUE TITLE
Ability to refresh a version for a workflow that doesn't exist on Dockstore, but does on Git

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3379]
**Is your feature request related to a problem? Please describe.**
User has a lot of versions for a legacy workflow. They would like to add new versions but don't want to do a lengthy refresh all. If they can refresh an individual version that doesn't yet exist on Dockstore, then they don't have to refresh the workflow (more likely to break).

**Describe the solution you'd like**
Some UI elements on the versions tab where users can add versions. Perhaps a button that says 'Add Version' that opens a modal that lets a user type in a branch/release and adds that version to Dockstore. Similar to how you can add versions to manual tools.

**Describe alternatives you've considered**
Could also do this inline, though haven't put much thought into that.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1300)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1300
┆Sprint: Backlog
┆Issue Type: Story

**Comment by agduncan94** [comment]
Note that backend already supports refreshing versions that don't exist on Dockstore, so this is purely a UI change.

**Comment by denis-yuen** [comment]
Github apps seems to be functioning well as does conversion from legacy to github apps. Recommend conversion
