### ISSUE TITLE
Improve logging in web service

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3384]
**Is your feature request related to a problem? Please describe.**
We should have go through our code base and improve our logging. This will give us more useful information should we need to track down any issues in production.

**Describe the solution you'd like**
Here are some thoughts:

1. Ensure that exceptions themselves are always logged (sometimes we just log the message, not the exception itself).
2. Generally, exceptions should be logged with the ERROR level. We don't always do that. There are exceptions (hah!) to this though, so the implementor needs to verify on a case-by-case basis.
3. There are some things that are logged as ERROR that really aren't.
4. More generally, pay close attention to the debug level, especially ERROR, e.g., there might be non-exeception cases where we should be logging as ERROR. It is easy in CloudWatch to just filter by ERROR, but that works best if only relevant stuff shows up.
5. Try and not log, or drop the level to FINE/DEBUG very noisy things that aren't typically errors. Will need to look at CloudWatch logs to sample.

**Additional context**

See #3362 which will also provide useful logging info.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1303)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1303

**Comment by NatalieEO** [comment]
Not really reviewable.
