### ISSUE TITLE
AtrributeConverter null

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3385]
**Describe the bug**
Getting 500 error on https://dev.dockstore.net/api/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/descriptor

**To Reproduce**

1. Go to https://dockstore.org/api/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/descriptor
See error

**Expected behavior**
Not to see error

**Additional context**
 - host location: all of them

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1304)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1304

**Comment by agduncan94** [comment]
@garyluu are the paths supposed to be missing the github.com/ ?

**Comment by denis-yuen** [comment]
(I was under impression yes)

**Comment by agduncan94** [comment]
Now properly returns incorrect ID (404) instead of 500 error.
1.9.0-alpha.9 and 2.6.0-rc.0.
