### ISSUE TITLE
collections endpoint is slow

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3386]
**Describe the bug**
the /api/organizations/{organizationId}/collections endpoint can be extremely slow

**To Reproduce**
1. Go to https://dev.dockstore.net/api/organizations/16/collections
2. Wait for it...
3. Wait for it...
4. Wait for it...
5. Fall asleep

**Expected behavior**
To not fall asleep

**Additional context**
organization 16 is broadinstitute
On production this has also resulted in Java heap space error once

 - host location: All of them

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1305)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1305

**Comment by agduncan94** [comment]
Much faster as of 1.9.0-alpha.9.
