### ISSUE TITLE
Order of workflows in a collection is random and non-deterministic

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3394]
**Describe the bug**
The order of workflows on the collections page seems to be random. Refreshing the page can end up with the workflows in a different order.

**To Reproduce**
1. Go to https://dev.dockstore.net/organizations/HuBMAP/collections/HuBMAP
2. Note the order of the workflows
3. Refresh the page
4. Note the order of the workflows is probably different than what it was in step 2.

**Expected behavior**
The workflows should always be in the same order.

1. Sorted by date or alphabetically by name.
2. By org curator's preference.

**Additional context**
 - UI version: 2.5.1-rc.1-44-gcb9b4d8a
 - Webservice version: 1.9.0-alpha.9-SNAPSHOT

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1307)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 35 Jellyfish
┆Issue Number: DOCK-1307

**Comment by Ldcabansay** [comment]
Ideally the sorting should be handled by the webservice or database
