### ISSUE TITLE
No message on DAG alert box for invalid version of Galaxy workflow

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3397]
**Describe the bug**
On an invalid version of a Galaxy workflow, the DAG tab has an alert box with no message. 

**To Reproduce**
1. Create an invalid galaxy version on Dockstore
2. Click on DAG tab
3. See box with no error message inside

**Expected behavior**
There should be a message

**Screenshots**

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT 
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1310)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1310

**Comment by agduncan94** [comment]
The message is displayed.
1.9.0-alpha.9 and 2.6.0-rc.0.
