### ISSUE TITLE
Workflow path not changing when changing descriptor type to gxformat2

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3398]
**Describe the bug**
When your galaxy workflow is in a stub, changing the descriptor type doesn't change the default workflow path, but does so for the other 3 languages. 

**To Reproduce**
1. Go to a stub workflow
2. Change descriptor type to gxformat2
3. See that the workflow path did not change

**Expected behavior**
Should change to galaxy file extension

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT 
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1309)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1309

**Comment by agduncan94** [comment]
The workflow path now changes to /Dockstore.yml when you select Galaxy from a stub workflow.
1.9.0-alpha.9 and 2.6.0-rc.0.
