### ISSUE TITLE
Issues with creating hosted galaxy workflows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3399]
**Describe the bug**
You can not correctly create a hosted galaxy workflow. When created, you can not immediately navigate to it by clicking the link in the side listing in my-workflows. You must open another workflow or refresh the page. Pretty sure this is the same issue as #3287.

Once you navigate to it, the workflow path is Dockstore.cwl and you cannot create versions for it.

**To Reproduce**
1. Go to my-workflows
2. Click on + button and create a galaxy hosted workflow
3. Try to click on it on the left panel, but see you're unable to navigate to it.
4. Refresh page, and navigate to the galaxy workflow
5. Notice that the workflow path is Dockstore.cwl and you cannot click on a version

**Expected behavior**
You should be able to navigate immediately to a hosted galaxy workflow with the correct path and ability to create versions 

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT 
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1313)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1313

**Comment by melainalegaspi** [comment]
We're not sure what state this is in, it'd be good to find out.

**Comment by NatalieEO** [comment]
This is no longer an issue 
API - 1.9.0-alpha.10-SNAPSHOT
UI - 2.6.0-rc.0-23-ge4951bb8
