### ISSUE TITLE
error on workflow form for manual register makes no reference galaxy

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3400]
**Describe the bug**
When creating a workflow through manual register, the regex error for the workflow field doesn't include a reference to the galaxy file extension.

**To Reproduce**
1. Go to my workflows
2. Click on + and then register custom workflows
3. fill out workflow path with something invalide like `asdf`
4. See that the warning that appears doesn't mention .ga

**Expected behavior**
should include .ga

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1312)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1312

**Comment by garyluu** [comment]
Error message is getting long enough that it should really just have a different error message for each descriptor type.
