### ISSUE TITLE
 DAG for galaxy workflows does not always have arrows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3401]
**Describe the bug**
The DAG created galaxy workflows does not always have arrows. I imagine this isn't correct.

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/NatalieEO/galaxy-workflow-dockstore-example-1:master?tab=info
2. Click on DAG tab
3. See just 2 nodes with no arrow

**Expected behavior**
I would think it should have arrows or we should be sure that this is actually correct

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1311)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1311

**Comment by garyluu** [comment]
@NatalieEO can you check if this is still an issue?

**Comment by NatalieEO** [comment]
Seems fine now, the workflow I mentioned in the PR gives a validation error now. Tried two others and they had arrows.
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.6.0-rc.0-14-gaec853f7
Found a new bug in the process though... Will create ticket.
