### ISSUE TITLE
broken link when hovering over DAG node

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3403]
**Describe the bug**
When a node in a DAG has TBD as the Docker info, it still has it as a link to dev.dockstore.net/undefined

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/NatalieEO/training-material:master?tab=dag or any other dag with TBD listed a node for docker info
2. Hover over any node
3. See TBD as a link

**Expected behavior**
Should only be a link if we detect a docker image in the workflow

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1315)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 33 Herring
┆Issue Number: DOCK-1315

**Comment by agduncan94** [comment]
Fixed on 1.9.0-alpha.9 and 2.6.0-rc.0.
