### ISSUE TITLE
Grabbing description field on Galaxy workflows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3405]
**Describe the bug**
The description field gets filled in by `name:` from the galaxy workflow, but it'd make more sense to grab `doc:` if it is available.
https://github.com/galaxyproject/dockstore-galaxy-interface/blob/master/src/main/java/org/galaxyproject/dockstore_galaxy_interface/language/GalaxyWorkflowPlugin.java#L247

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/NatalieEO/galaxy-workflow-dockstore-example-1:master?tab=info
2. See description is `Test Workflow` on Info tab
3. Click files and see that `doc:` is provided in this workflow

**Expected behavior**
Doc makes more sense to be grabbed first rather than name.

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1317)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1317

**Comment by Ldcabansay** [comment]
Verified that description is populated first by doc when available. As of: 
API - 1.9.0-alpha.9
UI - 2.6.0-rc.0-13-g92b0cb05
