### ISSUE TITLE
Github => GitHub

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3407]
**Describe the bug**
GitHub is not "GitHub", it is instead "Github"

**To Reproduce**
1. Open UI2 in any IDE
2. Search everything for "Github" and match case

There are a lot of results

**Expected behavior**
Searching for "Github" should not return any user-facing results.

Bonus: Make a test that tests for names similar to "GitHub", "Bitbucket", "GitLab", "DNAstack", "DNAnexus", "Docker Hub"

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1318)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1318
┆Sprint: Sprint 44- Sea Horse
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
> Bonus: Make a test that tests for names similar to "GitHub", "Bitbucket", "GitLab", "DNAstack", "DNAnexus", "Docker Hub" 

:+1:

**Comment by garyluu** [comment]
Just noticed our footer says "Github". _literally unusable_
