### ISSUE TITLE
Improve Google search listing via metadata

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#341]
### Desired behaviour

There are a wealth of options to improve our Google search listing. 
These include
- Adding a site name, logo, and social profile links https://developers.google.com/search/docs/guides/enhance-site
- Adding breadcrumbs to our site searches
- Adding a sitelinks searchbox 
- Marking up our tools and workflows as rich content types for search https://developers.google.com/search/docs/guides/mark-up-content

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-87)
┆Issue Type: Story
┆Issue Number: DOCK-87

**Comment by denis-yuen** [comment]
Still needed

**Comment by denis-yuen** [comment]
As a possible library for investigation
https://ngxlite.com/docs/json-ld
https://coryrylan.com/blog/angular-seo-with-schema-and-json-ld

**Comment by denis-yuen** [comment]
Another possibility https://universal.angular.io/

**Comment by garyluu** [comment]
Angular Universal pretty much got merged into the Angular 5 platform server.

**Comment by denis-yuen** [comment]
As discussed in the meeting, you may find that older approaches will use server side rendering (i.e. rendering all pages ahead of time to make it easier for crawlers)
However, this should not be entirely necessary. I think modern google crawling does understand an angular site to some extent

For example 
![screenshot from 2019-02-01 16-41-35](https://user-images.githubusercontent.com/1730679/52151263-7b4e4400-2640-11e9-9c9f-78039d1b8dad.png)

this returns the description, but there's a lot more information that could be passed through to make our results look more attractive and useful.

**Comment by david4096** [comment]
I can confirm the JSON+LD schema and entry is on the tool page

```

      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "url": "https://dockstore.org",
        "logo": "https://gui.dockstore.org/2.4.0-beta.4-5305a09/assets/images/dockstore/dockstore.png",
        "sameAs": ["https://twitter.com/DockstoreOrg"]
      }
```

https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow:2.2.0?tab=info

API - 1.7.0-beta.5
UI - 2.4.0-beta.4

**Comment by denis-yuen** [comment]
Wooo!
@david4096 how did you actually test this in the end?
