### ISSUE TITLE
Try to inform user if .dockstore.yml is invalid

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3410]
**Is your feature request related to a problem? Please describe.**
When trying to create (or transform) a workflow via GitHub apps, it's difficult to determine if it fails because there's an issue with Dockstore or because the user incorrectly formatted the .dockstore.yml.

**Describe the solution you'd like**
 It'd be nice for the user to know their .dockstore.yml is invalid

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1320)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 35 Jellyfish
┆Issue Number: DOCK-1320

**Comment by denis-yuen** [comment]
Should hook up error to validation framework so that workflow developer can tell that there is a syntax error

**Comment by agduncan94** [comment]
This has some overlap with https://github.com/dockstore/dockstore/issues/3239 and https://github.com/dockstore/dockstore/issues/3238. Definitely something that is needed for 1.9.0

**Comment by denis-yuen** [comment]
Also doesn't show the .dockstore.yml on dev.dockstore.net today, might be in a different ticket

**Comment by agduncan94** [comment]
This is due to https://github.com/dockstore/dockstore-ui2/pull/963. It changed the Dockstore.yml workflows to use the old file component, which doesn't show dockstore.yml. I must've missed this when I was reviewing the PR.

**Comment by denis-yuen** [comment]
Context, and I might have mis-remembered, there was an error in the number of spaces or tabs used in the .dockstore.yml for a demo. This would catch that level of error, not an error that #3239 would catch (something terribly wrong with lambdas)

**Comment by agduncan94** [comment]
After putting more thought into this I don't think we can easily inform users whether or not a dockstore.yml is invalid.

So if a dockstore.yml file is an invalid format, there will be a DockstoreYamlException and we would not be able to grab the workflow/service to associate with the dockstore.yml (can't assume no name field). So we don't know which entries on dockstore to associate the dockstore.yml with. If there is a space/tabs issue as @denis-yuen mentioned above, then it is invalid yml that we cannot parse, so we have no idea what entries it is associated with.

The only errors we can easily display are the following:

For services, we can display for validations whether or not a file in the file array exists. This already works.

For workflows, we could validate whether the primary descriptor exists and also whether the test files are present.

We cannot do the validation of YML format until we add the table that keeps track of lambda calls.

**Comment by denis-yuen** [comment]
> can't assume no name field

Are there more trade-offs to this than creating a potentially "extra" Dockstore entry with no name field?

**Comment by agduncan94** [comment]
It could also associate it with a workflow not using github apps (would this migrate it from full to dockstore.yml, not sure).

I think we should just get started on the error handling stuff for lambdas very soon since it is going to be important.

**Comment by denis-yuen** [comment]
> It could also associate it with a workflow not using github apps (would this migrate it from full to dockstore.yml, not sure).

I think that would be reasonable. 

> I think we should just get started on the error handling stuff for lambdas very soon since it is going to be important.

Ideally, yes. Practically, I doubt we can squeeze it into 1.9

**Comment by agduncan94** [comment]
@denis-yuen For now I'm going to add error handling for the .dockstore.yml in the situation where the primary descriptor doesn't exist or a test parameter file doesn't exist. While this isn't handling structural YML validation, it could still surface more common errors.

The version will now be added even if these files are not found, and will have validation messages (saying primary descriptor doesn't exist or test param file is missing). Previously no version was added if the primary descriptor was not found.

**Comment by agduncan94** [comment]
Note there will need to be some front end changes related to https://github.com/dockstore/dockstore/issues/3430. Will we keep the TRS endpoints for the front end or will we use custom endpoints?

**Comment by denis-yuen** [comment]
Not sure, so thinking it through the issue in #3430 is that if there is no descriptor, we can't tell what language the workflow is in when there is no `.dockstore.yml`. However, looking at the TRS standard it appears that the `descriptor_type` is an array for multiple languages, it could be empty if 
we do pursue the road of returning something for the two cases of:

a) a blank workflow with no `.dockstore.yml`
b) a blank workflow with a `.dockstore.yml` but broken or corrupt with no references to other descriptors

Here, we want to tell the user about errors in their `.dockstore.yml` which might be corrupt, formatted incorrectly, etc.

Are `.dockstore.yml` files currently returned by TRS and what `file_type` do they get?
https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/openapi/ga4gh-tool-discovery.yaml#L502

**Comment by agduncan94** [comment]
They are returned only if there is a descriptor file present. The file type of the dockstore.yml is OTHER and it is returned.

**Comment by denis-yuen** [comment]
So it seems that if we want to use TRS to debug invalid/corrupt .dockstore.yml without any associated descriptors. We will need to relax that and somehow infer/ignore language. 
Alternatively, use a proprietary endpoint (which may not exist yet). 

Might be able to add something under https://dockstore.org/api/static/swagger-ui/index.html#/extendedGA4GH to preserve the same id and version format. 

`/api/ga4gh/v2/extended/tools/{id}/versions/{version_id}` for example

**Comment by agduncan94** [comment]
I think we could technically add a new descriptor type of ./dockstore.yml but that feels a bit hacky.

**Comment by garyluu** [comment]
I think the ./dockstore.yml is too dockstore-specific that we should just use proprietary endpoint.  mapping the dockstore SourceFile object to TRS ToolFile has always been a pain.

**Comment by agduncan94** [comment]
So it seems like we should change the dockstore.yml workflows and services to use the non-TRS file viewer and instead use the existing proprietary (might need small tweaks).
