### ISSUE TITLE
dockstore.yml Galaxy workflows don't correctly show Files tab

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3413]
**Describe the bug**
When a galaxy workflow is created via github apps, the files tab doesn't have the second files tab to show the .dockstore.yml

**To Reproduce**
1. Have a galaxy workflow and add the .dockstore.yml file
2. Register it on dockstore
3. Make a push to create a version
4. Go to files tab and see that there's a primary descriptor, but no .dockstore.yml file listed.

**Expected behavior**
Files tab should include sub Files tab like the other workflow languages.

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.5.1-rc.1-47-gd104ddc4
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1324)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1324

**Comment by garyluu** [comment]
Is the file returned by the TRS endpoint?

**Comment by denis-yuen** [comment]
Note to implementer, .dockstore.yml shows for WDL, in discussion this may be a difference for non-plugin languages or the GUI may be using a different files component

**Comment by NatalieEO** [comment]
> Is the file returned by the TRS endpoint?

I get a 404 for https://dev.dockstore.net/workflows/github.com/NatalieEO/galaxy-workflow-dockstore-example-1:master?tab=info

**Comment by garyluu** [comment]
That's...not a DOCKSTORE.YML workflow. It says FULL

**Comment by NatalieEO** [comment]
Whoops
okay, you can get it via the trs endpoint
https://dev.dockstore.net/workflows/github.com/NatalieEO/training-material/Diploid:github-apps-test?tab=files

**Comment by garyluu** [comment]
To clarify:
https://dev.dockstore.net/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FNatalieEO%2Ftraining-material%2FDiploid/versions/github-apps-test/GXFORMAT2/files does not work
https://dev.dockstore.net/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2FNatalieEO%2Ftraining-material%2FDiploid/versions/github-apps-test/gxformat2/descriptor/.dockstore.yml does

**Comment by Ldcabansay** [comment]
Verified .dockstore.yml now visible under files tab as of API - 1.9.0-alpha.9
