### ISSUE TITLE
Unnecessary SERVICE mode

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3415]
**Is your feature request related to a problem? Please describe.**
Unncessary SERVICE mode when it could be DOCKSTORE.YML instead.
descriptorType being service allows us to know if a workflow is service, 

**Describe the solution you'd like**
Just use DOCKSTORE.YML instead

**Describe alternatives you've considered**
Not have any mode for services since it's known to use .dockstore.yml (at least for now)

**Additional context**
```
webservice_test=# select count(*) from service where descriptorType='service';
 count
-------
    73
(1 row)

webservice_test=# select count(*) from service where mode='SERVICE';
 count
-------
    73
(1 row)

webservice_test=# select count(*) from service where mode='SERVICE' and descriptorType='service';
 count
-------
    73
(1 row)

webservice_test=# select count(*) from service;
 count
-------
    73
(1 row)

webservice_test=# select count(*) from workflow where descriptorType='service';
 count
-------
     0
(1 row)

webservice_test=# select count(*) from workflow where mode='SERVICE';
 count
-------
     0
(1 row)
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1325)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1325

**Comment by Ldcabansay** [comment]
A bit odd to review since mode isn't displayed in the info tab for the UI (not even on 1.8/prod). However the api response on a published service shows that mode = DOCKSTORE_YML as of API - 1.9.0-alpha.9.
