### ISSUE TITLE
Disable Refresh From Services

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3416]
**Describe the bug**
Services should not be able to be refreshed. The frontend and backend both allow it which changes the workflow mode from SERVICE to FULL.

**To Reproduce**

1. Have a SERVICE
2. Go to My Services
3. See the refresh button in the top right
4. Click it
See weird service

**Expected behavior**
The frontend doesn't have the button
The backend doesn't allow it (BAD_REQUEST, etc)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1326)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1326

**Comment by coverbeck** [comment]
Verified Sync button is no longer present on dev
