### ISSUE TITLE
Logged-in homepage find entries debounce

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3418]
**Describe the bug**
On the logged-in homepage, the find entries debounce is not working

**To Reproduce**
1. Go to the logged in homepage
2. Open the network tab of Chrome (or the equivalent)
3. Type in "asdf" into the Find Entries input field

See way more than 1 call in the network tab

Not only is there no debounce, it's making double the amount of calls per character. 

Additionally, pressing backspace on the empty field also makes a call (not sure if this should be a separate issue)

**Expected behavior**
There should be 1 call with "asdf" in it

**Screenshots**
![image](https://user-images.githubusercontent.com/24548904/80022052-7e358e80-84a9-11ea-8d6f-84eae6e6bacd.png)

**Additional context**
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1327)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1327

**Comment by agduncan94** [comment]
Both issues fixed as of
API - 1.9.0-beta.1
UI - 2.6.0-rc.2
