### ISSUE TITLE
Able to create a "/" file in hosted workflows

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3420]
**Describe the bug**
"/" signifies root/absolute path.  Creating a file which is just "/" seems...wrong

**To Reproduce**
1. Create a valid hosted workflow of any language
2. Click Add File
3. Rename the filename to just "/"
4. Save version and see no error

**Expected behavior**
It should probably ask you to name it something with a real file name

**Additional context**
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1329)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1329

**Comment by coverbeck** [comment]
Verified this is working in staging.
