### ISSUE TITLE
Dockstore CLI 1.8.2 tag installs 1.8.0, and --upgrade flag does not upgrade

### ISSUE THREAD

**Issue by chmreid** [dockstore/dockstore#3426]
**Describe the bug**

This may need to be split into two issues.

On a fresh install of dockstore on Ubuntu 18.04, I am downloading the dockstore binary from the 1.8.2 tag, but the command line interface version that is reported is 1.8.0.

When trying to upgrade to 1.8.2 using the `--upgrade` flag, the command line utility says the download is complete and I am now on version 1.8.2, but when I check the version again, it still says 1.8.0.

**To Reproduce**

I am creating a Vagrant box with a fresh install of Ubuntu 18.04. To install dockstore, I am using the following commands:

```
mkdir -p ~/bin
curl -L -o ~/bin/dockstore https://github.com/dockstore/dockstore/releases/download/1.8.2/dockstore
chmod +x ~/bin/dockstore
echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
```

**Output behavior**

Actual behavior:

```
vagrant@ubuntu-bionic:~$ which dockstore
/home/vagrant/bin/dockstore
vagrant@ubuntu-bionic:~$ dockstore --version
Dockstore version 1.8.0
The latest stable version is 1.8.2
Please upgrade with the following command:
   dockstore --upgrade
vagrant@ubuntu-bionic:~$ dockstore --upgrade
Current Dockstore version: 1.8.0
Upgrading to most recent stable release (1.8.0 -> 1.8.2)
Download complete. You are now on version 1.8.2 of Dockstore.
vagrant@ubuntu-bionic:~$ dockstore --version
Dockstore version 1.8.0
The latest stable version is 1.8.2
Please upgrade with the following command:
   dockstore --upgrade
```

Expected behavior:

* Version should be 1.8.2 to begin with (since that is the version that I used curl to download)
* The `--upgrade` flag should either upgrade or report an error

Please let me know if there is a better place to put this issue. I noticed issues are disabled in the [dockstore/dockstore-cli](https://github.com/dockstore/dockstore-cli) repo.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1334)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1334

**Comment by denis-yuen** [comment]
Thanks for the heads-up. 
Basically, 1.8.0 is the current version of the CLI code. 
We recently split out the CLI code from the webservice which is now on 1.8.2 and the help text seems to be assuming that the two should be the same.

**Comment by Ldcabansay** [comment]
@denis-yuen might be more than a documentation change. I was running into an issue upgrading to other versions and @coverbeck found that the code that handles upgrades is still on done by the [Java code on dockstore/dockstore ](https://github.com/dockstore/dockstore-cli/blob/15f7686eee178e954785e0e64defda16121d9fa9/dockstore-client/src/main/java/io/dockstore/client/cli/Client.java#L196), not in the split-off CLI repo. 

So for example, I verified that my dockstore executable has the script pointing correctly to:
```
DOCKSTORE_URL="https://github.com/dockstore/dockstore-cli/releases/download/$DOCKSTORE_VERSION/dockstore-client-$DOCKSTORE_VERSION-shaded.jar"
``` 
But when I try running `--upgrade-stable` or `--upgrade-unstable` I get: 
```
14:26:55.151 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Could not connect to Github. You may have reached your rate limit.
14:26:55.156 [main] ERROR io.dockstore.client.cli.ArgumentUtility - java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/dockstore/dockstore/releases/latest
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1129)
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1595)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2960)
	at io.dockstore.client.cli.Client.upgrade(Client.java:377)
	at io.dockstore.client.cli.Client.run(Client.java:742)
	at io.dockstore.client.cli.Client.main(Client.java:613)
```

**Comment by notestaff** [comment]
Also the warning about upgrading seems to go to stdout rather than stderr, so  running the suggested command
dockstore tool convert entry2json --descriptor wdl --entry quay.io/ilya_broad/docker-tool-cosi2:91948ed > Dockstore.json
puts non-json at the top of Dockstore.json

**Comment by garyluu** [comment]
It was put into stdout because some users didn't want to upgrade and also didn't want to see it the stderr when they run their workflows.  Ideally the solution for this will need to handle both these use cases.

**Comment by NatalieEO** [comment]
after running the commands in the ticket, it asks me to update to version 1.9.0. Doing `dockstore --upgrade` does correctly update the version.
