### ISSUE TITLE
Is dockstore YAML file in ~/.dockstore/ called .dockstore.yml or dockstore.yml?

### ISSUE THREAD

**Issue by chmreid** [dockstore/dockstore#3429]
**Describe the bug**

The instructions in the [dockstore readme](https://github.com/dockstore/dockstore/blob/develop/README.md) and on the wiki ([Setting Up Dockstore Locally](https://wiki.oicr.on.ca/display/DOC/Setting+Up+Dockstore+Locally) and [Dockstore Primer](https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=DOC&title=Dockstore+Primer)) instruct the user to create a dockstore.yml file and put it at `~/.dockstore/dockstore.yml`.

But the DockstoreYamlHelper class in Dockstore refers to this file as `.dockstore.yml` (note the leading dot) in several places (e.g., [this message](https://github.com/dockstore/dockstore/blob/develop/dockstore-common/src/main/java/io/dockstore/common/yaml/DockstoreYamlHelper.java#L28) and [this message](https://github.com/dockstore/dockstore/blob/develop/dockstore-common/src/main/java/io/dockstore/common/yaml/DockstoreYamlHelper.java#L69)). But it also refers to it as `dockstore.yml` (e.g. ,[here](https://github.com/dockstore/dockstore/blob/develop/dockstore-common/src/main/java/io/dockstore/common/yaml/DockstoreYamlHelper.java#L92)).

The DockstoreYamlHelper error messages are should be updated to refer to `dockstore.yml` instead of `.dockstore.yml`.

**To Reproduce**

No steps needed

**Expected behavior**

Code/documentation should refer to either `dockstore.yml` or `.dockstore.yml` consistently

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1335)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1335

**Comment by garyluu** [comment]
From what I can tell, I think this may be a misunderstanding.  The DockstoreYamlHelper refers to the `.dockstore.yml` which is the file people add to their workflows.

The one mentioned in the Primer and Readme is actually the dropwizard configuration file (which I actually call dropwizard.yml on my machine to avoid confusion).

Regardless, https://github.com/dockstore/dockstore/blob/develop/dockstore-common/src/main/java/io/dockstore/common/yaml/DockstoreYamlHelper.java#L92 seems wrong

**Comment by chmreid** [comment]
PR #3444 will fix that typo
