### ISSUE TITLE
Authenticated TRS handle valid .dockstore.yml workflow with invalid/non-existent descriptor

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3430]
**Describe the bug**
If you have a workflow (dockstore.yml) with no descriptor file (but does have a .dockstore.yml), the API returns an error for trying to retrieve the .dockstore.yml file on the files tab.

Request URL that is failing: <hostname>/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fagduncan94%2Fghapps-single-workflow%2Ffoobar1/versions/failure/CWL/descriptor/.dockstore.yml

Look at ToolsImplCommon.java (starting from line 217) to see roughly where this is occurring.
Edit: actually around 184 is when the descriptor type is set. Looks like this won't handle when no primary descriptor is present.

**To Reproduce**
Create a dockstore.yml workflow with a valid dockstore.yml but the primaryDescriptorPath points to a file that doesn't exist.
Go to the files tab of the version, the file will not load.
Can see this in the network requests tab too.

**Expected behavior**
Should display the .dockstore.yml, and for the descriptor file say one has not been found.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1336)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1336

**Comment by garyluu** [comment]
Issue is very confusing. Localhost url, strange title, can't tell if this is a frontend or backend issue.

**Comment by agduncan94** [comment]
I tagged it with UI

**Comment by agduncan94** [comment]
If a version is missing a primary descriptor file, the code at [ToolsImplCommon.java#L185-L215](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsImplCommon.java#L185-L215) will not know the descriptor type, so will not return the version in the converted workflow object (the result of the convertEntryToTool function).

**Comment by denis-yuen** [comment]
From a TRS perspective: 
Thinking if there are no relevant workflow files at all, should the entry even exist?
This seems like some zen thing, is a workflow with no workflow files really a workflow?

From a Dockstore perspective, we need to see the .dockstore.yml to debug things. Maybe we shouldn't use TRS for the .dockstore.yml file?

**Comment by NatalieEO** [comment]
@agduncan94 is this ready for review now or is this ticket still relevant?

**Comment by agduncan94** [comment]
It is still relevant. The question really is, should the TRS return .dockstore.yml (and other) files that are dockstore specific, and not specific to how the tools run. And the answer seems to be they shouldn't. So the TRS should not return .dockstore.yml files. The implication is that we have to rewrite the file component for the UI to no longer use the TRS. Hopefully we can use the new sourcefiles endpoint you will work on.

**Comment by agduncan94** [comment]
Closing since this will be irrelevant with https://ucsc-cgl.atlassian.net/browse/SEAB-1303
