### ISSUE TITLE
Embedded spaces in urls in advanced CLI docs page

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3431]
**Describe the bug**

There are embedded spaces in 4 of the 5 urls, see screenshot

Also, the sample config file points to Cromwell 50

Would have put these comments in dockstore/dockstore-documentation#56, but PR was merged before I had a chance.

**To Reproduce**
Go to https://docs.dockstore.org/en/develop/advanced-topics/advanced-features.html

**Screenshots**
![Screen Shot 2020-04-28 at 2 11 07 PM](https://user-images.githubusercontent.com/1049340/80538187-22ac4a80-895a-11ea-8eb1-54419c5aafa0.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1337)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1337

**Comment by garyluu** [comment]
Hmm...i only looked at diff changes :(

**Comment by NatalieEO** [comment]
no longer seeing spaces in doc
