### ISSUE TITLE
Make UI Version link actionable per commit

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3437]
**Is your feature request related to a problem? Please describe.**
The UI version in the footer can be misleading in a non-prod/non-staging environment.

**Describe the solution you'd like**
The UI version should accurately reflect the UI build.

**Additional context**
In [git.version.ts](https://github.com/dockstore/dockstore-ui2/blob/develop/git.version.ts), we call `git describe --tag`, which "the most recent tag that is reachable from a commit". If develop branch is ahead of that tag, it is confusing.

Ideally the tag portion of the version would only be set if tag matches the HEAD, otherwise it would leave it empty. And the footer would display accordingly.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1341)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Backlog
┆Issue Number: DOCK-1341

**Comment by denis-yuen** [comment]
display accordingly --> should display an appropriate short SHA-1 that matches the right column on https://github.com/dockstore/dockstore/commits/develop or can be used to/link to https://github.com/dockstore/dockstore/commit/X 

It seems like the current regex has issues and is pre-pending text

**Comment by david4096** [comment]
From slack:

> In a previous meeting there was some confusion about how to tie the info at the bottom of the page for the UI version to a commit. The confusion I had was that tag git adds the -g so the g is not included in finding the commit hash. UI - 2.6.0-21-g674d165d means there have been 21 commits since 2.6.0 and that the commit hash refers to g or git SCM https://git-scm.com/docs/git-describe

The href works when the git tag referenced is a released tag. However, if the link goes to this non-existing git tag, github responds with a 404, though the commit exists. To close this that href should point to an existing commit. This can be achieved in a few ways. Parse the tag for the existence of the commit hash (`-g3a7b33f`) and then create a link to the commit `https://github.com/dockstore/dockstore-ui2/commit/3a7b33f`. Alternatively, we could use tagged nightly releases.
