### ISSUE TITLE
Blank search table when backspacing

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3445]
**Describe the bug**
Depending on your search query, once you backspace the entire thing, the search table will go become empty and you can't get it to be filled until you refresh the page. 

**To Reproduce**
1. Go to search page
2. I think the requirement for the search query is one that will only have workflows as a result. So search for 'topmed'
3. See results in workflow tab. Backspace your search query. If you highlight and delete it all at once, it will work fine.
4. See empty search table.

**Expected behavior**
Shouldn't be empty. Backspacing shouldn't have different behavior than highlighting and deleting entire term at once.

**Additional context**
happens on production and dev

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1346)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1346

**Comment by garyluu** [comment]
I personally can't reproduce this on dev

**Comment by NatalieEO** [comment]
ah never mind, you're right @garyluu . Had too many similar looking tabs open when I did this. Closing
