### ISSUE TITLE
image IDs for hosted tools

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3448]
**Describe the bug**
Image IDs aren't populated for hosted tools. This originally caused the #3317 bug on TRS endpoints that hid versions for hosted tools because of the lacking image IDs. #3330 works around the hiding, but the underlying issue of retrieving image IDs/checksums for hosted tools still needs to be addressed. 

**Expected behavior**
Image IDs (Docker, Quay.io) should be populated for hosted tools or at least the behavior should be the same as externally hosted tools. See if something from checksum retrieval code can help with this.

**Additional context**
 - Webservice version: TRS versions hidden bug persists on webservice as of 1.8.2, but work around should deploy with 1.9.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1348)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 35 Jellyfish
┆Issue Number: DOCK-1348

**Comment by denis-yuen** [comment]
We should also document this limitation for 1.9.0 if true at https://docs.dockstore.org/en/1.9.0-bucket/advanced-topics/checksum-support.html?highlight=checksums#docker-image-checksum-support
