### ISSUE TITLE
No default workflow version set if default deleted by refresh

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3449]
**Describe the bug**
If the default version is set to version x, and a refresh of the workflow has causes version x to be deleted, the default version is no longer set.

Spun this off from verifying #3345 

**To Reproduce**
1. Go to My Workflows and select a workflow with a default version set
2. Goto GitHub and delete the default version
3. Refresh the workflow
4. No default version is set.

**Expected behavior**
The web service should set the default version, if there are any versions left. It already selects  a default version on a refresh if one isn't set, but just doesn't handle this case.

**Additional context**
This is on dev; requires a build with #3345 fix.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1349)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8.X
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1349

**Comment by garyluu** [comment]
Can't reproduce using https://github.com/garyluu/test which already exists on Dockstore
- Created a new branch called toBeDeleted on GitHub
- Refreshed workflow on Dockstore to pick up new version
- Set this new version to be the default
- Deleted branch on GitHub
- Refreshed workflow on Dockstore

Observed master being set to default version again

**Comment by denis-yuen** [comment]
@coverbeck maybe a specific workflow state?

**Comment by coverbeck** [comment]
I can no longer reproduce; tried both on dev and locally. I think it's safe to close.

I know I did see it. :) I reproduced several times when writing it up.
