### ISSUE TITLE
Do leaner queries and responses

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3453]
**Describe the bug**

Some endpoints are querying for and returning a massive amount of data. We have made some improvements in the response sizes, but the queries are still fetching too much data, consuming a lot of memory server-side.

At least whenever a workflow is involved (collections, collection, workflows) -- all of the versions and all of the versions' sourcefiles are fetched.

This ticket is intended for 1.8.x. There are deeper changes that can be done that are covered in #3442

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1353)
┆Issue Type: Story
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1353

**Comment by denis-yuen** [comment]
Might need to convert this into an epic and split off specific tickets for specific groups of endpoints.

**Comment by denis-yuen** [comment]
spot-checked for 1.8.6
