### ISSUE TITLE
Collection page showing loading bar too briefly

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3454]
**Describe the bug**
The loading bar for a very large collection shows for such a short time, that if you blink, you may miss it. This despite it taking several more seconds for the page to load. Which then tempts the user to click the browser refresh button, which puts more load on server, etc.

**To Reproduce**
1. Go to https://staging.dockstore.net/organizations/BroadInstitute/collections/GATKWorkflows
2. Look for loading bar

**Additional context**

Due to another bug, the response for that page can be huge. Needs investigation, but two unproven theories are:

1. The loading bar is tied to the wrong Ajax request, which is why it goes away so soon.
2. The response is so huge that the response is either tying up the browser, and/or our JavaScript that is processing the response is blocking for too long. Perhaps the #3453 fix will address this if so.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1354)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1354

**Comment by Ldcabansay** [comment]
Verified that loading bar now displays until page is loaded, also loading is a lot faster so not that big of an issue anymore. 
API - 1.9.0-beta.1-SNAPSHOT
UI - UI - 2.6.0-rc.0-37-g94f4b9a2
