### ISSUE TITLE
Change SourceFiles to be Fetch.Lazy

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3455]
**Is your feature request related to a problem? Please describe.**
Source files can consume a large amount of memory; we should avoid fetching them unless needed by the client.

**Describe the solution you'd like**
* In WorkflowVersion, annotate sourceFiles with `FetchType.LAZY` instead of `FetchType.EAGER`.
* That may not be enough though; if anything access the source files they'll end up getting loaded anyways.
*  Force fetching of sourceFiles via a new endpoint? Or via a query parameter?
* UI apparently doesn't use source files; except for the hosted entries.
* May require UI corresponding UI changes

**Additional context**
Overlaps with #3453 and #3442 . This might end up being addressed in either or both of those instead.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1355)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.10
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1355

**Comment by NatalieEO** [comment]
Yeah, a lot of things are broken. Search, my tools, my workflows, individual tool and workflow pages are varying levels of broken.

**Comment by denis-yuen** [comment]
Might be best to start with individual tool and workflow pages to see/debug the extent of the fixes needed since @garyluu may eventually be tinkering with my tools and my workflows due to https://ucsc-cgl.atlassian.net/browse/DOCK-1353

**Comment by garyluu** [comment]
Played around with this a bit.  Funny, we do use sourcefiles for a variety of places...but not for the file contents.  it's to determine the descriptor type so that we can use the TRS.

**Comment by NatalieEO** [comment]
Yeah, I think we also use it to get the verified source for each version. I'm not sure what's going on the with my-tools page since absolutely nothing loads.

**Comment by denis-yuen** [comment]
For review, I realize that we went a different direction with sourcefiles by adding a new endpoint 
But this means that we will need to actually make source file lazy in 1.10?
@NatalieEO please confirm

**Comment by NatalieEO** [comment]
Yes that's correct. I'll take the review label off of this.
