### ISSUE TITLE
Improve refresh by tracking Git commit

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3456]
**Is your feature request related to a problem? Please describe.**
When we refresh a repo, I believe we get every version and compare it to what Dockstore has indexed. This is inefficient.

**Describe the solution you'd like**
When we read from a Git repo, we should store the Git commit id. When we do a refresh, we should compare the stored commit id with the current one, and skip the refresh.

**Additional context**
#2668 has another idea for improving refresh. We probably don't want to put more load on the server for that one though.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1356)
┆Issue Type: Story
┆Sprint: Sprint 35 Jellyfish
┆Issue Number: DOCK-1356

**Comment by agduncan94** [comment]
We already store the commit ID, at least for GitHub.

**Comment by agduncan94** [comment]
Seems like this is done for GitHub workflows only. There is code that works for Bitbucket, but is only used for tools. No code for GitLab.

**Comment by Ldcabansay** [comment]
Verified that we now store git commitID at the version level for github, bitbucket, and gitlab. The commitID is included in the response workflow/{workflowID} endpoint, nested under version stuff. Git commitID is not included in the TRS response for workflow or workflowversion.

API - 1.9.0-alpha.9
