### ISSUE TITLE
Allow a max of one service in .dockstore.yml

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3460]
**Is your feature request related to a problem? Please describe.**
The .dockstore.yml supports both multiple workflows and multiple services. I think we need to only allow a max of one service.

The difference is that for services .dockstore.yml has information that can only be gleaned by client from reading the .dockstore.yml, e.g., datasets, possibly a port, etc. A platform that is going to run a Dockstore service will need to fetch and read the .dockstore.yml in order to, for example, determine which port to proxy.

If the .dockstore.yml contains an array of services, the client would not be able to tell which service in the .dockstore.yml applies to the current service.

**Describe the solution you'd like**
.dockstore.yml should allow 0-1 services.

**Describe alternatives you've considered**
Dockstore could capture the metadata in the .dockstore.yml and store that with the service. Using the port as an example, Dockstore could store the port with the service, and the client could query the api for the port. Similar to how, for example, a workflow stores the primaryDescriptorPath.

This might be the better approach, but:

* Ideally we want platforms to fetch services via the TRS API, and TRS does not have a way to surface the port. This would require changes to the TRS specification.
* The schema is still evolving; port may not even end up being there, or maybe it will be an array instead of a single port, etc. Other fields might get added. It might be better not to lock in.

Writing this up, maybe we should at least capture the additional info in the schema, even if we don't yet surface it.

May need a storytime.

**Additional context**
If we decide to do this, it would be good to get into 1.9; otherwise we have a model with a list of services that if anybody takes advantage of, we won't be able to migrate.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1358)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1358

**Comment by denis-yuen** [comment]
What would be the strategy be if someone does ask for multiple services in one repo ala workflows?
Or do we just put our hammer down?

**Comment by coverbeck** [comment]
We either put down the hammer, or we pursue the alternative, to capture the extra metadata. It's hard to know because we don't have any actual services, so I could be totally wrong, but I'm guessing the reasons for creating many workflows from one repo may not apply to services.

**Comment by coverbeck** [comment]
Having doubts about this solution, recap with options:

## Problem

Platforms launching a service defined in Dockstore will need metadata from the .dockstore.yml, which they have to get by fetching the .dockstore.yml via TRS. If the .dockstore.yml has an array of services, how will they determine which service in the array is the one?

## Possible Solutions
1. They look at the name field and see if it matches that section of the TRS id. Or if it's not set, they look for the non-existence of the portion of the TRS id. Puts a bit of work on the platform, but they're going to have to read the file anyway.
2. We expose the metadata in the .dockstore.yml through the API. I feel this would be the optimal solution, but 1) the schema is still evolving and 2) it will take a while to work this into TRS. Point 1 could be solved by making the API generic enough, e.g., having a Map of key-value pairs or something like that, but that will require thought, and maybe TRS doesn't want to go down that route.
3. We only allow one service instead of an array. There will be no confusion. One-repo-many-workflows is a popular model; this would not allow one-repo-many-services. Since there are no real services, who knows if people will want to do that? We could always reintroduce the array in a future version of the schema.

## Conclusion

Still lean towards third option, but not wild about it.

**Comment by agduncan94** [comment]
I'm ok with option 3. Services are new and I think it is better to restrict now and add later. The service dockstore.yml serves an additional function vs the workflow dockstore.yml. Instead of just being for indexing on Dockstore it is also for running. Due to this, I think I am ok with limiting to one per file (and therefore one per repository).

**Comment by denis-yuen** [comment]
I'm ok with 1 and 3, I think its not quite ready for 2/TRS 

1. Doesn't sound so bad and would be a future proof schema. The platform could do an initial implementation where they select the "first" service and that would probably be a 95% solution for quite a while.
