### ISSUE TITLE
Import existing branches with .dockstore.yml when registering a workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3473]
**Is your feature request related to a problem? Please describe.**
If you add a repo with branches that have a .dockstore.yml in them to Dockstore, the versions do not get read into Dockstore

**Describe the solution you'd like**
Configuring a GitHub app for a repo with .dockstore.yml in it should create Dockstore versions for all branches/tags with a .dockstore.yml.

**Additional context**
We're not doing this to avoid an expensive read the whole repo and all its branches operation. 

On the other hand if there are .dockstore.yml's in the repo, they should be honored. Especially if you fork an existing repo, there will be no way to retroactively create Dockstore versions for tags, unless you delete and recreate the tags.

I wasn't able to get this working in a brief experiment, but maybe we can do something like [this](https://stackoverflow.com/questions/25564760/how-can-i-search-file-name-in-specific-github-repository) to know which branches to load.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1364)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1364
┆Sprint: 105 - Colorado
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Going to wait for user requests
