### ISSUE TITLE
Add tools from bio-cwl-tools into Dockstore

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3475]
**Describe the solution you'd like**
Tools from https://github.com/common-workflow-library/bio-cwl-tools should be hooked up. 
Perhaps with GitHub apps and a .dockstore.yml depending on where we are with that when we work on this

**Additional context**
Thanks to @tetron for the heads-up

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1365)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1365
┆sprint: 89
┆taskType: Story

**Comment by wshands** [comment]
This bug may be an impediment to adding tools (https://ucsc-cgl.atlassian.net/browse/DOCK-1281) as in their requirements section https://github.com/common-workflow-library/bio-cwl-tools#requirements--hints-section- they show an empty JSON map
