### ISSUE TITLE
Existing documentation should better explain the purpose of the workflow name

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3484]
**Is your feature request related to a problem? Please describe.**
Dockstore.yml can be a bit confusing. The workflow name is mentioned as not being required, but is it not directly clear what it does and why it is important for uniquely identifying the workflow.

**Describe the solution you'd like**
Update the documentation for dockstore.yml to better explain the purpose of the workflow name and how entries in the dockstore.yml workflows array map to workflows (by path) on Dockstore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1368)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 41 Pufferfish
┆Issue Number: DOCK-1368
┆Epic: Dockstore documentation

**Comment by Ldcabansay** [comment]
Verified that docs that explain workflow name are now live on read the docs

https://docs.dockstore.org/en/develop/getting-started/dockstore-workflows.html
