### ISSUE TITLE
Change refresh org to use individual workflow refresh endpoints

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3485]
**Is your feature request related to a problem? Please describe.**
Refresh org can be pretty slow, and the request can sometimes time out.

**Describe the solution you'd like**
Change the refresh org button in the UI to chain together a bunch of refresh individual workflows. It would no longer add new workflows. Could chain in API call to add user to workflows they should have access to.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1370)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1370

**Comment by denis-yuen** [comment]
note to implementer: should not be parallel, should not send requests until previous requests are don

**Comment by coverbeck** [comment]
Are you referring to the existing behavior or to the behavior with my changes? I thought it would continue with my changes.

**Comment by agduncan94** [comment]
Oh if it is existing that is ok, I'll create a ticket that this must be fixed.
