### ISSUE TITLE
Smart refresh that only updates branches that have changed

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3487]
**Is your feature request related to a problem? Please describe.**
Currently, a refresh will update every version for a workflow on Dockstore, even if those versions haven't changed.

**Describe the solution you'd like**
Add a new bit to versions. After a refresh, set to true (meaning in sync). Updating a workflow on Dockstore (ex. change primary descriptor) changes the bit for all non-dirty versions to false, meaning they must be synced. Updating a version individually sets this bit to false.

When a version is added for the first time or a full refresh of that version is done, the bit is set to true.

If the bit is true, if the commit ID has not changed, do not update. If the commit ID has changed, then do a full version refresh.
If the bit is false, then no matter what do a full version refresh.

Note: This is not for GitHub App workflows, but instead all traditional workflows that use the refresh method.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1371)
┆Fix Versions: Dockstore 1.10
┆Issue Number: DOCK-1371
┆Sprint: Sprint 41 Pufferfish
┆Issue Type: Story

**Comment by agduncan94** [comment]
Notes from storytime.
Add a new column for versions called synced (boolean). Synced will be set to false if we don't need to update a version (based on changes to Dockstore). Synced will be true if we have not made any changes to a workflow or version since we last refreshed.

Refreshing changes the bit to true (meaning synced) and stores the commit ID.
On the next refresh
* if synced == true and the commitID is the same, don't refresh version
* if synced == true and commitID is different, refresh version
* if synced == false, refresh the version and set synced to true

We set sync to false for a version anytime we make changes to the version. Any changes to a workflow and we set all versions to false.

There can be an extra option called ignore sync. This would be equivalent to our current refresh code.

**Comment by agduncan94** [comment]
Notes from storytime.
Add a new column for versions called synced (boolean). A version is synced if it has been refreshed since the last time the version was edited on Dockstore. Anytime we change a version or dockstore information, we set synced to false. Any time a version is refreshed, we set synced to true.

Refreshing changes the bit to true (meaning synced) and stores the commit ID.
On the next refresh
* if synced == true and the commitID is the same, don't refresh version
* if synced == true and commitID is different, refresh version
* if synced == false, refresh the version and set synced to true

There can be an extra option called ignore sync. This would be equivalent to our current refresh code.

**Comment by denis-yuen** [comment]
Making a note that this is especially tricky to review to the how important refresh is to Dockstore. 
Putting ideas out there, I think we'll want to split up the work across more than one developer for reviews:
* github apps
* refresh for different source control (github, bitbucket, gitlab)

Should also report how much of a performance improvement there is (to justify the added complexity)
