### ISSUE TITLE
Cannot delete tool due to events

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3493]
**Describe the bug**
```
org.hibernate.exception.ConstraintViolationException: could not execute statement could not execute statement ERROR: update or delete on table "tool" violates foreign key constraint "FKToolId" on table "event"  Detail: Key (id)=(14256) is still referenced from table "event". 
```

**To Reproduce**
1. Add a tool
2. Refresh a tool (with success) to add some versions (and get some events)
3. Delete a tool

**Expected behavior**
Tool to be deleted

API - 1.8.5
UI - 2.5.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1374)
┆Issue Type: Story
┆Sprint: Sprint 36 Krill
┆Issue Number: DOCK-1374

**Comment by coverbeck** [comment]
Worked for me in staging with 1.8.6
