### ISSUE TITLE
Lazy load workflowVersions

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3495]
**Is your feature request related to a problem? Please describe.**
EAGER loading workflow versions is causing a bunch of performance issues and currently many solutions modify endpoints to use a new query but it's not a great solution.  

**Describe the solution you'd like**
LAZY load workflow versions instead.  Here are some things to keep in mind:
- input_file_formats and output_file_formats will force EAGER loading even if set to LAZY
- setWorkflowVersions surprisingly eagerly loads the original ones first.

**Describe alternatives you've considered**
🦗 

**Additional context**
Bunch of performance issues.
When I LAZY load workflow versions and JSON ignore the file formats, the MyWorkflows page endpoint reduces the number of JDBC statements by 80%.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1375)
┆epic: Performance improvements 
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-1375
┆sprint: Sprint 58- Goblin shark
┆taskType: Story

**Comment by denis-yuen** [comment]
See also #3455

**Comment by denis-yuen** [comment]
Good food for thought, had a more broad question asked in the doc.
