### ISSUE TITLE
TRS /tools self_link

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3499]
**Describe the bug**
Getting:
```
fail: GET (200) /api/ga4gh/v2/tools?limit=30 duration: 30602ms
fail: headers: At '/self_link' Missing required property: self_link
```

**To Reproduce**
1. Go to http://142.1.177.188:8080/trs/validator/debug?url=https://dev.dockstore.net/api
2. Wait a reallllllllllllly long time

See error

**Expected behavior**
11 tests passing, no failures

**Additional context**
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1376)
┆Issue Type: Bug
┆Sprint: Sprint 43- Ringed Seal
┆Issue Number: DOCK-1376

**Comment by denis-yuen** [comment]
Note to implementor: this looks like trs v2 beta rather than final

**Comment by garyluu** [comment]
weird...looks like validator has gone nuts and not able to find suitable parameters to test all the endpoints
