### ISSUE TITLE
Gracefully handle quay.io being down

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3501]
**Describe the bug**
If Quay.io is down and you try to refresh a tool, it just hangs in the refresh.

**To Reproduce**
Steps to reproduce the behaviour:
1. Quay.io is down
2. Go to my tools and select a quay tool
3. Refresh
4. No error, keeps trying to refresh

**Expected behavior**
Should fail with a message saying quay.io cannot be reached.

**Screenshots**

**Additional context**
 - UI version: [e.g. 2.5.2]
 - Webservice version: [e.g. 1.8.5]
 - host location: [e.g.dockstore.org]

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1378)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1378
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by garyluu** [comment]
Step 1: Bring down Quay.io 😈
