### ISSUE TITLE
Footer nits

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3509]
**Describe the bug**
There are a couple of small issues in the footer:

1. The GitHub link points to ga4gh/dockstore instead of dockstore/dockstore (but yeah it still works).
2. The copyright is still 2019. Fix would ideally be dynamic, so we don't have to update it every year.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1383)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 43- Ringed Seal
┆Issue Number: DOCK-1383

**Comment by NatalieEO** [comment]
Year is correct and looks dynamic, points to dockstore/dockstore, commits are shown, clipboard button works correctly
[Webservice](https://github.com/dockstore/dockstore/commits/c354528) - c354528

[UI](https://github.com/dockstore/dockstore-ui2/commits/df02f7cf) - 2.6.1-38-gdf02f7cf

[Compose Setup](https://github.com/dockstore/compose_setup/commits/8c083bddfa2e8cfcb517792d45b03b95dc3dda5d) - 8c083bddfa2e8cfcb517792d45b03b95dc3dda5d

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d87bd60) - 1.9.2-21-gd87bd60
