### ISSUE TITLE
Collections entries missing

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3516]
**Describe the bug**
(might be fixed after 1.8.6 is merged automatically)
https://dev.dockstore.net/organizations/bdcatalyst/collections/SVcalling
is missing entries as are the other organizations checked

**Additional context**
Failing with dev.dockstore (1.9.0-alpha)
Not failing on staging.dockstore.rg  (1.8.6)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1386)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1386

**Comment by garyluu** [comment]
Looks fine now I think (after the merge)
