### ISSUE TITLE
Have some sample code when creating a hosted tool/workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3518]
**Is your feature request related to a problem? Please describe.**
It's a little hard to get started writing a hosted tool/workflow if you don't know the language.

**Describe the solution you'd like**
When creating a  CWL/WDL hosted file in the UI, the file should be filled out with a hello world type program. The file contents are selected and the editor has focus, so if you don't like it, you just press one key and it's gone.

Perhaps only do it for the first file; once you've created one file, you could just copy from your previous files.

Could also go crazy and have a dialog pop up with options for the initial file.

**Describe alternatives you've considered**
Leave it like it is -- a file with no content.

**Additional context**
Sort of torn on this. Would be OK if issue rejected.

***Pros***
It would certainly make life easier for a beginner in WDL, CWL, etc. And for me when doing testing with Dockstore, since I don't know these languages. Some IDEs do similar things.

***Cons***
It might just get in the way of a more experienced WDL, etc. developer. It could get old pretty quick. Do we really want to become an IDE?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1388)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1388
┆Sprint: Sprint 52- Angel shark
┆Issue Type: Story

**Comment by garyluu** [comment]
Seems to work for hosted tool and workflow with CWL/WDL on dev.dockstore.net
