### ISSUE TITLE
Turn on ELB logs

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3521]
**Is your feature request related to a problem? Please describe.**
We don't have logs of requests made to our load balancer. Makes it hard to track down when something goes wrong.

**Describe the solution you'd like**
It's a free feature in AWS, just turn it on.

**Additional context**
We do log at the nginx level, but that only logs responses; it would be good to log requests as well the LB level.

If we do this, we may not need to do #3362, but we have to see what's logged.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1391)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1391

**Comment by garyluu** [comment]
I see logs for us-west put into s3 bucket
