### ISSUE TITLE
Remove refresh organization endpoint

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3523]
**Is your feature request related to a problem? Please describe.**
UI will no longer be invoking refresh organization endpoint, see dockstore/dockstore-ui2#987; we should remove the refresh organization API endpoint

**Describe the solution you'd like**
Remove the endpoint to refresh an organization.

**Additional context**
See #3522

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1392)
┆Issue Type: Story
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1392

**Comment by NatalieEO** [comment]
It's removed
