### ISSUE TITLE
Update GitHub Apps doc once lambda errors UI is done

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3530]
**Is your feature request related to a problem? Please describe.**
Once the lambda errors are available in the UI, we need to update the doc. In this file probably, unless it makes more sense somewhere else 
https://github.com/dockstore/dockstore-documentation/blob/feature/3490/GitHubAppDocChanges/docs/getting-started/github-apps-troubleshooting-tips.rst

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1396)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 40 Octopus
┆Issue Number: DOCK-1396
┆Epic: Automated sync of Dockstore and GitHub apps

**Comment by garyluu** [comment]
Visible on https://docs.dockstore.org/en/develop/getting-started/github-apps/github-apps-troubleshooting-tips.html
