### ISSUE TITLE
Language support for galaxy documentation

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3531]
**Is your feature request related to a problem? Please describe.**
Update https://docs.dockstore.org/en/1.9.0-bucket/end-user-topics/language-support.html for Galaxy

**Describe the solution you'd like**
Need a new column indicating what is supported

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1397)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 37 Lobster
┆Issue Number: DOCK-1397

**Comment by garyluu** [comment]
I see it on develop docs
