### ISSUE TITLE
Refresh org will fail if one of the individual refreshes change

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3542]
**Describe the bug**
If you have a GitHub organization where one of the individual workflows would fail refresh (ex. the workflow no longer exists on GitHub) then this will fail and stop the rest of the workflows from being refreshed. An individual workflow refresh failure should not fail a refresh org.

One issue with this is that we cannot delete these workflows that no longer have a github reference, so it will always fail and the user cannot fix this.

**To Reproduce**
1. Go to my workflows
2. Refresh an organization with a workflow where the corresponding GitHub repository no longer exists
3. Will fail

**Expected behavior**
Should pass, but maybe have some notification that some workflows could not be refreshed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1403)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Backlog
┆Issue Number: DOCK-1403

**Comment by denis-yuen** [comment]
Going to remove with #3538
