### ISSUE TITLE
Mock-up and then add Preview badge to appropriate locations for Galaxy preview

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3549]
Thinking when viewing a Galaxy workflow and in the radio selection for selecting Galaxy, open to additional ideas. 

**Describe the solution you'd like**
Should mock up a couple options in balsamiq or similar for voting in Slack and then implement choices.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1406)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 38 Manatee
┆Issue Number: DOCK-1406

**Comment by garyluu** [comment]
It's one of the PRs not in rc.3 https://github.com/dockstore/dockstore-ui2/compare/2.6.0-rc.3...release/2.6.0
