### ISSUE TITLE
Increase character limit for notifications

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3559]
**Is your feature request related to a problem? Please describe.**
The character limit  right now is 280, but we have to waste characters on markdown and inserting links. It can be annoying when making notifications

**Describe the solution you'd like**
Increase to 4 or 500 and add to the documentation to test our how your notification looks before adding to production.

**Describe alternatives you've considered**
No limit and assume developers will be reasonable and see how it looks before hand.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1414)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 44- Sea Horse
┆Issue Number: DOCK-1414

**Comment by denis-yuen** [comment]
There has to be some limit just in case, even if it is 640K ;)

**Comment by NatalieEO** [comment]
Confirmed on dev that notifications can be longer than 280 characters and fails once bigger than 1024 characters 
[Webservice](https://github.com/dockstore/dockstore/commits/cca5430) - cca5430

[UI](https://github.com/dockstore/dockstore-ui2/commits/d1788c83) - 2.6.1-50-gd1788c83

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6c50698b903981ca78f05759cc2c3a7049e847a6) - 6c50698b903981ca78f05759cc2c3a7049e847a6

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/da01baf) - 1.9.2-33-gda01baf
