### ISSUE TITLE
Local-entry WDL run mishandles escape character "\"

### ISSUE THREAD

**Issue by g3chen** [dockstore/dockstore#3562]
**Describe the bug**
Printing a string via `--local-entry` with a JSON containing the string causes "\t" or "\\\t" to be printed as "t"

**To Reproduce**
1. WDL:
```
version 1.0
workflow test_location {
    input {
        String readGroups
    }
    call find_tools {
        input:
            readGroups=readGroups
    }
}
task find_tools {
    input {
        String readGroups
    }
    command <<<
        echo ~{readGroups}
    >>>
    output{
        String result = read_string(stdout())
    }
    runtime {
        docker: "ubuntu:latest"
    }
}
```
2. JSON:
```
{
  "test_location.readGroups": "'@RG\\tID:121005_h804_0096_AD0V4NACXX-NoIndex_6\\tLB:PCSI0022C\\tPL:ILLUMINA\\tPU:121005_h804_0096_AD0V4NACXX-NoIndex_6\\tSM:PCSI0022C'"
}
```
3. Run with:
`dockstore workflow launch --local-entry test_location3.wdl --json test4.wdl.json`
4. Get result:
```
"outputs": {
    "test_location.find_tools.result": "@RGtID:121005_h804_0096_AD0V4NACXX-NoIndex_6tLB:PCSI0022CtPL:ILLUMINAtPU:121005_h804_0096_AD0V4NACXX-NoIndex_6tSM:PCSI0022C"
}
```
Note: Dockstore only prints "t" no matter now many "\\" are placed in front of it.

**Expected behavior**
When run with Cromwell:
`java -jar $cromwell run test_location3.wdl --inputs test4.wdl.json`
Gets the expected output:
```
"outputs": {
    "test_location.find_tools.result": "@RG\\tID:121005_h804_0096_AD0V4NACXX-NoIndex_6\\tLB:PCSI0022C\\tPL:ILLUMINA\\tPU:121005_h804_0096_AD0V4NACXX-NoIndex_6\\tSM:PCSI0022C"
}
```

**Desktop:**
OS:
- Distributor ID: Ubuntu
- Description: Ubuntu 18.04.4 LTS
- Release: 18.04
- Codename: bionic

Dockstore CLI:
- Current version : 1.8.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1416)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1416

**Comment by NatalieEO** [comment]
Correctly prints out the `\\t` now using Dockstore version 1.9.0-beta.0
"outputs": {
	    "test_location.find_tools.result": "@RG\\tID:121005_h804_0096_AD0V4NACXX-NoIndex_6\\tLB:PCSI0022C\\tPL:ILLUMINA\\tPU:121005_h804_0096_AD0V4NACXX-NoIndex_6\\tSM:PCSI0022C"
	  }
