### ISSUE TITLE
Add Mac install instructions to quickstart

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3570]
**Is your feature request related to a problem? Please describe.**
In quickstart instructions we say users can use Mac or Linux, but only give instructions for Ubuntu. Since instructions are hardcoded into UI, would be ideal to get in for 1.9

**Describe the solution you'd like**
Add Mac install instructions. It'd be nice if this was had tabs to toggle separate instruction tabs for each OS, but for 1.9 can inline the instructions. 

**Describe alternatives you've considered**
We can also separate out instructions to live just in documentation. 

**Additional context**
Part of #3558

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1422)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1422

**Comment by denis-yuen** [comment]
Note to implementer, can use CircleCI to test with Mac and/or Windows

**Comment by coverbeck** [comment]
Verified Mac instructions. Created a related but not caused by this issue, #3604 .
