### ISSUE TITLE
Improve CLI 1.9 refresh to discover workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3571]
**Is your feature request related to a problem? Please describe.**
The 1.9 refresh functionality is to refresh the user's existing repos. It does not discover repos that you have been added to.

**Describe the solution you'd like**
We should either add a new subcommand to find orgs, or modify refresh to also find.

**Additional context**

* [Slack discussion](https://ucsc-cgl.slack.com/archives/C16ET3CF4/p1591801389404100)
* #3522 -- initial implementation

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1423)
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1423
┆Sprint: Sprint 44- Sea Horse
┆Issue Type: Story

**Comment by GFJHogue** [comment]
**Review**: `dockstore workflow refresh` discovered workflows from all of my GitHub orgs - I am now enlightened.
