### ISSUE TITLE
Refresh a workflow fails if having issues parsing one workflow version

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3572]
**Describe the bug**
The repo https://github.com/HumanCellAtlas/skylab has at the time of this writing a branch that references an HTTP import that does not exist. This will throw an exception and the refresh will fail.

**To Reproduce**
1. Create a WDL workflow that imports a file with HTTPS that doesn't exist.
2. Try refreshing the workflow, should fail.

**Expected behavior**
Should not cause refresh to fail, should just make that version invalid.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1424)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1424

**Comment by garyluu** [comment]
Works when I added `import "https://raw.githubusercontent.com/garyluu/testWorkflow/testBranchInvalidImport/metadata_example0.wdls" as md5sum`
