### ISSUE TITLE
Update curator/admin status from the API

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3574]
**Is your feature request related to a problem? Please describe.**
Currently need to edit the DB to set curator and admin. This is not good.

**Describe the solution you'd like**
New API endpoints that do the following:
* Curators can use the API to add curators
* Admins can use the API to add curators or admins

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1425)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Sprint: Sprint 40 Octopus
┆Issue Number: DOCK-1425
┆Epic: Organization Improvements

**Comment by Ldcabansay** [comment]
Verified on dev as of API - 1.10.0-alpha.0-SNAPSHOT
* Curators can use the API to add curators (but not admins)
* Admins can use the API to add curators or admins
* could not edit own permissions
