### ISSUE TITLE
Remove refresh by namespace for tools

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3575]
**Is your feature request related to a problem? Please describe.**
Equivalent to https://github.com/dockstore/dockstore-ui2/commit/e4951bb839d1c5ae43cd241c43bb90af96e35161 for tools

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1427)
┆Issue Type: Story
┆Sprint: Sprint 38 Manatee
┆Issue Number: DOCK-1427

**Comment by garyluu** [comment]
it's not on staging
