### ISSUE TITLE
Handle duplicate service path with better error

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3577]
**Describe the bug**
If a user tries to register a service that has already been added, it will have a 500 error that looks like the following:
```
Duplicate key value violates unique constraint "partial_service_name"→  Detail: Key (sourcecontrol, organization, repository)=(github.com, foo, bar) already exists.
```
We found this throwing 500 errors on production.

**To Reproduce**
Since this occurs via github app calls, it is easier to recreate using the API. The only way services are added is through the release command, so this must be occurring from calling this command multiple times. However, there should already be checks for duplicate service names, so based on the error these are not working.

**Expected behavior**
Should be thrown as a CustomWebApplicationException, not a db error. Also should be a 400 level error since it is a duplicate registration.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1428)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 41 Pufferfish
┆Issue Number: DOCK-1428

**Comment by GFJHogue** [comment]
Couldn't reproduce this bug.

This error stopped appearing on production after June 24, 2020 which seems to align with 1.9.0 release. Seems to no longer be an issue.
