### ISSUE TITLE
openapi.yaml generation has large whitespace re-arrangements

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3579]
**Describe the bug**

After running `mvn clean install -DskipTests` with a small change 

```
$ git diff dockstore-webservice/src/main/resources/swagger.yaml | wc -l
13
$ git diff dockstore-webservice/src/main/resources/swagger.yaml 
diff --git a/dockstore-webservice/src/main/resources/swagger.yaml b/dockstore-webservice/src/main/resources/swagger.yaml
index 071810a1..2dfffe35 100644
--- a/dockstore-webservice/src/main/resources/swagger.yaml
+++ b/dockstore-webservice/src/main/resources/swagger.yaml
@@ -4527,7 +4527,7 @@ paths:
       - name: "dockerRegistry"
         in: "query"
         description: "Docker registry"
-        required: false
+        required: true
         type: "string"
       responses:
         200:
$ git diff dockstore-webservice/src/main/resources/openapi3/openapi.yaml | wc -l
8919
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1430)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Backlog
┆Issue Number: DOCK-1430

**Comment by denis-yuen** [comment]
Changes look like mostly different numbers of spaces
Consider https://github.com/dockstore/dockstore/pull/3580/commits/9d9ce3679c32eec4ce1fec4175933b27e56c8078#diff-93f24054fc12e4bdcc94a710e4f6b0e9

**Comment by garyluu** [comment]
I think the new yq version might have changed spacing.

**Comment by denis-yuen** [comment]
Seems like a reasonable possibility
