### ISSUE TITLE
Update cwltool version to a recent stable version

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3591]
**Is your feature request related to a problem? Please describe.**
Bump cwltool version to a more recent version

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1437)
┆Fix Versions: Dockstore 1.10
┆Issue Number: DOCK-1437
┆Sprint: Sprint 46- Unicorn Fish
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Relinking #3196

**Comment by coverbeck** [comment]
@wshands Was there any discussion on this, whether it should be a hotfix?

**Comment by garyluu** [comment]
> @wshands Was there any discussion on this, whether it should be a hotfix?

See https://github.com/dockstore/dockstore/pull/3866
