### ISSUE TITLE
Truncated versions table for tools

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3593]
**Describe the bug**
On staging, versions table is horizontally truncated for at least one tool (the first one in search, alas). Tried a couple of other tools and workflows, and they seemed OK.

**To Reproduce**
1. Go to https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:2.1.0?tab=versions
2. See truncated actions column; cannot scroll to view covered up part.

![Screen Shot 2020-06-19 at 5 04 27 PM](https://user-images.githubusercontent.com/1049340/85186614-f5d82d80-b24e-11ea-9263-a2205b0effb2.png)

**Expected behavior**
Actions column should be visible or there should be a scroll bar.

**Additional context**
 - host location: staging.dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1439)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1439

**Comment by garyluu** [comment]
Duplicate of https://github.com/dockstore/dockstore/issues/3179

**Comment by denis-yuen** [comment]
Interesting, didn't realize you could mark things as duplicate that way on GitHub. 
That said, I'm not sure its doing anything but maybe they'll expose it later to search

**Comment by coverbeck** [comment]
Since it's a dupe, closing it.
