### ISSUE TITLE
Grafana Config is not completely parameterized

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3603]
**Describe the bug**

The Grafana configuration template assumes certain things about its environment

* For example, [these 3 lines](https://github.com/dockstore/dockstore-deploy/blob/5b95708a8bc25aa4ca1c41ee0ee4570224c3648d/dockstore-dashboard.json#L99) assume AZ, load balancer, and target group. Several more instances in that file.
* [This line](https://github.com/dockstore/dockstore-deploy/blob/5b95708a8bc25aa4ca1c41ee0ee4570224c3648d/dockstore.yml.template#L828) also assumes the region.

**Expected behavior**

Template should be generic to work in whatever AZ/region it is deployed in.

** Additional Context **

Probably want to run either sed or mustache on the downloaded json file. Also, optionally, just get the file from directly from github and skip having to upload the file to s3.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1446)
┆Epic: Grafana 
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1446
┆Sprint: Sprint 48- Walrus
┆Issue Type: Bug

**Comment by NatalieEO** [comment]
Not really reviewable, closing.
