### ISSUE TITLE
On staging, the Getting started page has CLI issues

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3604]
**Describe the bug**
1. The Download CLI takes you to a GitHub page not found.
2. The url in the download instructions point fails as well: `curl -L -o ~/bin/dockstore https://github.com/dockstore/dockstore/releases/download/1.9.0-beta.1/dockstore`

**To Reproduce**
1. Go to https://staging.dockstore.org/quick-start

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1447)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 38 Manatee
┆Issue Number: DOCK-1447

**Comment by wshands** [comment]
A pre-release would have to be drafted for 1.9.0-beta.1 and the 'dockstore' script added as an asset. Is this what we want to do?

**Comment by denis-yuen** [comment]
Was that the recommendation from the CLI storytime? If so, that sounded reasonable. 
I don't think we have an explicit assignee for CLI releases, maybe you can handle it for 1.9.0 and then write up a SOP for post 1.9.0 when it becomes more straightforward.

**Comment by NatalieEO** [comment]
Download working on staging
API - 1.9.0 dockstore 
UI - 2.6.0
