### ISSUE TITLE
Errors details not obviously accessible in GitHub apps logs

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3606]
**Is your feature request related to a problem? Please describe.**
If there are errors in GitHub app logs, it's not clear that there are more details.

Also, just because I'm too lazy to create another issue, and because it should be a simple null check fix, there is an error in console for install events.

**Describe the solution you'd like**
There should be some sort of indicator that more details are available, and/or errors should be displayed by default.

The screen you get:
![Screen Shot 2020-06-24 at 8 22 42 AM](https://user-images.githubusercontent.com/1049340/85584385-f3315b80-b5f3-11ea-9ef1-bcc925148580.png)

If you click on the error row, you get:

![Screen Shot 2020-06-24 at 8 23 45 AM](https://user-images.githubusercontent.com/1049340/85584490-0b08df80-b5f4-11ea-9803-6111c013f92f.png)

It's not obvious how you get from the first screen shot to the second screen shot.

Also, if you have developer tools open, you'll see these error messages for the install events:

```
null/undefined passed into the pipe along with the key: reference
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1449)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Backlog
┆Issue Number: DOCK-1449
┆Epic: Automated sync of Dockstore and GitHub apps

**Comment by denis-yuen** [comment]
Closing for now (doesn't seem like greyed out arrows have enough contrast, but will address in new ticket)
