### ISSUE TITLE
Sourcefiles endpoint being called twice

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3608]
**Describe the bug**
Looks like the new source files endpoint is being called twice. Only happens, I think, with workflows that have a .dockstore.yml.

**To Reproduce**
1. Open your browser's Developer tools
2. Goto https://staging.dockstore.org/workflows/github.com/coverbeck/md5sum-dockstore-yml/foobar:stagingtest?tab=files (if that workflow goes away due to a staging data reset, go to any workflow with a .dockstore.yml, including in My Workflows if it is not published).
3. Click on Files tab
4. Note two calls to sourcefiles endpoint in dev tools

**Expected behavior**
There should only be one request to fetch source files.

**Additional context**
 - UI version: 2.6.0-rc2
 - host location: staging.dockstore.org

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1451)
┆Epic: Performance improvements 
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1451
┆Sprint: Sprint 41 Pufferfish
┆Issue Type: Bug

**Comment by NatalieEO** [comment]
@garyluu this was labeled 1.9.x but I only see it fixed in dev
