### ISSUE TITLE
GitHub App logs returning null/undefined reference

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3610]
**Describe the bug**
Sometimes the GitHub App logs are returning null reference from /lambdaEvents/{organization}

**To Reproduce**
TBD

**Expected behavior**
GitHub App logs to never return null reference

**Screenshots**
![image](https://user-images.githubusercontent.com/24548904/85734418-06fbc100-b6cb-11ea-8c82-f490ad2b6f0b.png)

**Additional context**
 - host location: [staging.dockstore.org]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1453)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1453

**Comment by agduncan94** [comment]
In the logs, I see the following error
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'includes' of undefined",
    "stack": [
        "TypeError: Cannot read property 'includes' of undefined",
        "    at IncomingMessage.<anonymous> (/var/task/index.js:51:50)",
        "    at IncomingMessage.emit (events.js:203:15)",
        "    at IncomingMessage.EventEmitter.emit (domain.js:448:20)",
        "    at endReadableNT (_stream_readable.js:1145:12)",
        "    at process._tickCallback (internal/process/next_tick.js:63:19)"
    ]
}
```

That area of the lambda looks like the following
```
var contentType = res.headers['content-type'];
var responseMessage = contentType.includes('text/plain') ? bodyString : res.statusMessage;
```

I think the contentType is not set for the installationEvents due to the response returned by our API. So in this case I think the fix is
```
var responseMessage = contentType && contentType.includes('text/plain') ? bodyString : res.statusMessage;
```

**Comment by garyluu** [comment]
Ok, turns out null/undefined reference is legit for install events.  Should be handled by the frontend

**Comment by NatalieEO** [comment]
Made a new install but do not see an error in the console. 
API - 1.10.0-alpha.0-SNAPSHOT dockstore status indicator
UI - 2.6.0-18-gb9dd8cd6
