### ISSUE TITLE
Better introduction to DIY-ing your own workflows on BDC

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#3614]
**Is your feature request related to a problem? Please describe.**
Users of the Biodata Catalyst platform have said that better documentation and guides on writing their own workflows is lacking. The issue is for compounded by BDC's lack of synchronised documentation, however, since Dockstore is the workflow repository for this grant and others it makes the most sense for Dockstore to host this information, with the specific content likely having some input from parties who have a stake in WDL, CWL, and Nextflow.

I'm aware Dockstore already has tutorials on getting started with WDL, CWL, and Nextflow. I think the main issue is that BDC users do not know how to finding the existing docs, but for tracking purposes I've been asked to make a ticket here.

**Describe the solution you'd like**
A clear guide on how to go about making bioinformatics workflows that is easy to access (perhaps linked on the homepage), searchable, and reasonably up to date on the current specifications of workflow descriptor languages.
 
**Describe alternatives you've considered**
Hosting these docs/linking them on BDC pages.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1457)
┆Epic: Dockstore Outreach and Training
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1457
┆Sprint: Backlog
┆Issue Type: Story

**Comment by bethsheets** [comment]
@denis-yuen @melainalegaspi On the BDC side, we have already responded to this feedback and created documentation in the BDC Gitbook called "Bring Your Own Tool" (https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/community-tools-and-integration/bring-your-own-tool-s-to-biodata-catalyst). Do you want to change the scope of this ticket to linking to this doc in Dockstore doc repo or did you have other ideas?
