### ISSUE TITLE
Support for CWL with extension fields

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3616]
**Is your feature request related to a problem? Please describe.**
Seven Bridges uses extension fields in their CWL as hints, e.g., for machine type (I think).

Is there anything Dockstore can do to better support these extension fields?

Can it be somehow tied into WDL hints, e.g., this workflow requires an 8-core machine?

This is just a placeholder to get things started; I don't know enough about it to offer intelligent guesses.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1459)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.10
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1459

**Comment by denis-yuen** [comment]
brainstorming
1) don't break on hints (obviously) whether ingest or parsing
2) take advantage of for search?

**Comment by denis-yuen** [comment]
@briandoconnor extensions might break CWL parsing, but should fulfill normal definition of CWL extensions

**Comment by NatalieEO** [comment]
So we currently handle the extensions fields. For example, this tool has one https://dev.dockstore.net/containers/registry.hub.docker.com/sevenbridges/pcawg_muse_sbg_modified/pcawg_muse_vc_sbg_modified:1.0?tab=files
and there's no validation error

We could take advantage of `sbg:fileTypes` for search https://staging.dockstore.org/containers/registry.hub.docker.com/sevenbridges/pcawg_delly_sbg_modified/pcawg_delly_vc_sbg_modified:1.0?tab=files
