### ISSUE TITLE
Improve addUserToDockstoreWorkflows performance

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3619]
**Is your feature request related to a problem? Please describe.**
The [endpoint](https://github.com/dockstore/dockstore/blob/2caf914821431764f13228fad1539bf0d1588656/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java#L805) to discover a user's workflows is inefficient and has the potential to consume a lot of memory.

The current implementation:

1. Fetches all source control orgs the user belongs to, except hosted.
2. Gets all workflows for each org
3. Adds the user to each workflow from step 2
4. Fetches all of the user's workflows

This ends up with all of the user's workflows loaded into memory. Twice, although maybe Hibernate optimizes that.

**Describe the solution you'd like**

Some of this may be rendered moot by our upcoming and ongoing optimizations, but:

* Step 4 could arguably be skipped; we've already fetched all of the users workflows in steps 1-3, and we could just return that, adding the hosted workflows. However, there is a edge case where the user belongs to a workflow but no longer belongs to the source control org, so I'm not sure.
* Depending on what we do for the previous step, steps 2 and 3 could be changed in a couple of ways
    * Only fetch workflows for each org that don't already have the user
    * Don't even fetch the workflows at all, and instead do a JPQL update.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1462)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1462

**Comment by garyluu** [comment]
Before:
```
INFO  [2020-07-06 21:44:25,403] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    58300 nanoseconds spent acquiring 2 JDBC connections;
    56600 nanoseconds spent releasing 2 JDBC connections;
    101177300 nanoseconds spent preparing 10989 JDBC statements;
    9696065500 nanoseconds spent executing 10989 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    2088400 nanoseconds spent executing 1 flushes (flushing a total of 219 entities and 517 collections);
    199596100 nanoseconds spent executing 11 partial-flushes (flushing a total of 16377 entities and 16377 collections)
```

**Comment by coverbeck** [comment]
Another thought is that we only update the workflows that the user doesn't belong to. And only return the workflows that were added.
