### ISSUE TITLE
Error in EPAM WDL Visualizer

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3620]
Error in EPAM WDL Visualizer for github.com/DataBiosphere/topmed-workflow-variant-calling:1.0.3

**To Reproduce**
Go to https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflow-variant-calling:1.0.3?tab=dag
Click on EPAM WDL Visualizer
See error message

**Expected behavior**
Should see EPAM drawing

**Screenshots**
![Screen Shot 2020-06-29 at 9 59 31 AM](https://user-images.githubusercontent.com/3650921/86034989-71c13b00-b9f0-11ea-8606-37f2b4001d40.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser Chrome 
 - Version Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context**
 - UI version: UI - 2.6.0-rc.5
 - Webservice version: API - 1.9.0-beta.2 
 - host location: staging.dockstore.org

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1463)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1463
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by coverbeck** [comment]
Might be a duplicate for #2839

**Comment by melainalegaspi** [comment]
@coverbeck: "EPAM builder removed until they support WDL 1.0; reopen if support ever added."
