### ISSUE TITLE
Add descriptorType database column for tools

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3632]
**Is your feature request related to a problem? Please describe.**
We want sourcefiles to be lazy loaded #3455, but the @jsonproperty descriptorType for tools needs to get stored in the db before we can do that.

**Describe the solution you'd like**
Create db column for descriptorType
Run script/migration to populate all the rows
update rows on refresh

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1468)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.10
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1468

**Comment by agduncan94** [comment]
I can't seem to find the the endpoint for insertDescriptorType. Has it already been added?

**Comment by NatalieEO** [comment]
I should have changed my PR description, but ended up not doing the endpoint. I ended up writing a migration in psql and the descriptor type will get updated on refresh or edithosted. So you can test if the migration seems for some random tools, if updating it with refresh/edithosted is correct, and that it works for brand new tools as well.

**Comment by agduncan94** [comment]
I noticed there is no format options for tools in the search, is that related to this PR?

**Comment by agduncan94** [comment]
Everything else seems to be working though.

**Comment by NatalieEO** [comment]
Ohh, it probably is a side effect of this PR lol.

**Comment by NatalieEO** [comment]
Could go either way

**Comment by agduncan94** [comment]
Everything seems to be working. Made an issue for a possibly related bug.
