### ISSUE TITLE
Search facets don't display list after expanding and un-expanding

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3637]
**Describe the bug**
Search facets don't display list after expanding and un-expanding

**To Reproduce**
Click on 'Search'
On Author facet click on '137 more' at bottom right of list
Click on '^' (up arrow) or 'Author' to shrink list
There are now no authors listed

**Expected behavior**
Should have seen 5 authors listed as was seen when Search first clicked

**Screenshots**
![Screen Shot 2020-07-02 at 2 40 57 PM](https://user-images.githubusercontent.com/3650921/86411735-5e250700-bc72-11ea-9bd1-1c69f9b19540.png)

![Screen Shot 2020-07-02 at 2 41 07 PM](https://user-images.githubusercontent.com/3650921/86411733-5d8c7080-bc72-11ea-86a4-3025a051b338.png)

![Screen Shot 2020-07-02 at 2 41 14 PM](https://user-images.githubusercontent.com/3650921/86411732-5cf3da00-bc72-11ea-9aec-c1790f358cdf.png)

**Desktop (please complete the following information):**

* OS: Mac OS Mojave
* Browser Chrome
* Version Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context**

* UI version: 2.6.0
* Webservice version: 1.9.0
* host location: dockstore.org

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1472)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10373/Hide+button.png">Hide button.png</a>
┆Epic: Fix Facets 
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1472
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Bug

**Comment by garyluu** [comment]
Hmm...might be a usability issue.

Opposite of "137 more" is "Hide".  The "Click on '^' (up arrow) or 'Author' to shrink list" is for collapsing or expanding the entire facet.
