### ISSUE TITLE
Add @jsonignore to sourcefile and make changes to UI

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3644]
**Is your feature request related to a problem? Please describe.**
We want sourcefiles to be lazy loaded #3455, and that will break the UI. Ignoring the sourcefiles should reveal all the areas in the UI that will be broken by this change, and the UI should be fixed accordingly.

**Describe the solution you'd like**
jsonignore sourcefiles in webservice
UI PR to address areas broken by no longer receiving sourcefiles.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1478)
┆Epic: Performance improvements 
┆Fix Versions: Dockstore 1.10
┆Issue Number: DOCK-1478
┆Sprint: Sprint 41 Pufferfish
┆Issue Type: Story

**Comment by agduncan94** [comment]
Is it possible to review this or does it need the UI PR as well? @NatalieEO

**Comment by NatalieEO** [comment]
@agduncan94 doesn't make sense to review right now. Can you put this back into progress on the jira side.
