### ISSUE TITLE
Browser back button doesn't work in collections

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#3650]
**Describe the bug**
If you navigate to a workflow from a collection page and then hit the back button, you will be taken to Dockstore's main page. This makes looking through multiple workflows in a collection a bit frustrating as you have to instead control-click to open each of them as a separate tab.

**To Reproduce**
1. Go to organizations 
2. Pick one 
3. Go to one of the collections of that organization
4. Click a workflow
5. Hit browser back button

For example: https://dockstore.org/organizations --> https://dockstore.org/organizations/SevenBridges --> https://dockstore.org/organizations/SevenBridges/collections/PCAWG --> https://dockstore.org/containers/registry.hub.docker.com/sevenbridges/pcawg_bwa_sbg_modified:1.0?tab=info --> hit back button, end up at https://dockstore.org/

**Expected behavior**
Back button should take me to the collections page (https://dockstore.org/organizations/SevenBridges/collections/PCAWG in above example), not the homepage of Dockstore.

**Desktop (please complete the following information):**
 - Mac OSX Catalina
- Chrome v. 83 (current)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1482)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1482
┆Sprint: Sprint 61- Leopard shark
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
note to implementer:
doesn't happen with all organizations, happens to be with LifeOmic and Seven Bridges, but not Broad and UCSC orgs
also not for all workflows in those orgs, weird

**Comment by garyluu** [comment]
random guess, might have to do with alias

**Comment by denis-yuen** [comment]
Update: noticed by Kim Cullion on prod

**Comment by melainalegaspi** [comment]
Chat with @denis-yuen on progress. Otherwise, delay to 1.12.

**Comment by david4096** [comment]
I also just ran into this. Can add to the original bug that if you click back again you will end up back at the collection.
