### ISSUE TITLE
Some TRS data is not populated

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3656]
**Is your feature request related to a problem? Please describe.**
Going through the code on another ticket, noticed some TODOs that don't seem to have a ticket and makes TRS implementation incomplete.

1. We don't set size nor date on image data. See the following code snippet from io.swagger.api.impl.ToolsImplCommon.java, which I'm refactoring, so no link:

```
        final ImageData imageData = new ImageData();
        imageData.setImageType(ImageType.DOCKER);
        imageData.setRegistryHost(trsImageDTO.getRegistryHost().getDockerPath());
        imageData.setImageName(trsImageDTO.getImageName());
        //TODO: hook up proper size
        imageData.setSize(0);
        //TODO: hook up proper date
        imageData.setUpdated(new Date().toString());
```
2. Included Apps is always set to an empty array. Looks like it might require a feature change in Dockstore to gather the info. See this code where it sets it to itself:

```
            ToolVersion toolVersion = new ToolVersion();
            toolVersion.setAuthor(MoreObjects.firstNonNull(toolVersion.getAuthor(), Lists.newArrayList()));
            //TODO: would hook up identified tools that form workflows here
            toolVersion.setIncludedApps(MoreObjects.firstNonNull(toolVersion.getIncludedApps(), Lists.newArrayList()));
```

This could be split into two tickets.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1485)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1485
┆Sprint: Sprint 52- Angel shark
┆Issue Type: Bug

**Comment by garyluu** [comment]
Can anyone clarify what includedApps is supposed to be?

**Comment by denis-yuen** [comment]
As in the comment, it was intended to be some way of denoting which tools form part of a workflow. 
I think `1` is more important than `2` at this point.

**Comment by garyluu** [comment]
Can anyone clarify what includedApps is supposed to be? Perhaps provide an example and not repeat the comment.
