### ISSUE TITLE
Remove unstar endpoints

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#3657]
Now that starring in the UI is done in a consistent manner following https://github.com/dockstore/dockstore/issues/2395 we can remove the `unstar` endpoints from organizations, tools, and workflows.

You can see the DELETE endpoints with the verb unstar here: https://staging.dockstore.org/api/static/swagger-ui/index.html#/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1486)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1486

**Comment by NatalieEO** [comment]
No longer see either unstart endpoint https://dev.dockstore.net/api/static/swagger-ui/index.html#
API - 1.10.0-alpha.1-SNAPSHOT dockstore status indicator
UI - 2.6.1-30-g2d21f244
