### ISSUE TITLE
TRS tools endpoints doesn't filter out null values

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3660]
**Is your feature request related to a problem? Please describe.**

When using the query parameters on the [TRS tools endpoint](https://dockstore.org/api/static/swagger-ui/index.html#/GA4GHV20/toolsGet), null values pass the filter.

See [this code](https://github.com/dockstore/dockstore/blob/22a244a51d15d536eccb69bb1210189eb2cd3fdc/dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java#L337) -- if description is null in the database, then descriptions.

While this is SQL-like behavior, I don't think we want this for our API; if I'm searching for the description "Foo", I only want to see workflows with the word "Foo" in their descriptions; I don't want to see ones with no descriptions.

We stumbled across this with description; I don't know which of the other fields can be null in this scenario.

*** Steps to Reproduce ***

1. `curl -X GET "https://staging.dockstore.org/api/ga4gh/trs/v2/tools?description=Foo" -H  "accept: application/json"`
2. Look at the response; lots of workflows with empty descriptions are in the results.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1489)
┆Issue Type: Bug
┆Sprint: Sprint 40 Octopus
┆Issue Number: DOCK-1489

**Comment by garyluu** [comment]
Note for future me: Use "mmmrrrggglll" instead of "Foo".  there's a surprising amount of workflows that legit have foo in it
