### ISSUE TITLE
Copy TRS ID Button

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3666]
**Is your feature request related to a problem? Please describe.**
Copying the TRS ID of a Dockstore entry is too hard.  Need an easier way.

**Describe the solution you'd like**
A button of some sort that lets you copy the TRS ID with a click.

**Describe alternatives you've considered**
"Hey Gugu, copy the TRS ID off this workflow"

**Additional context**
https://www.youtube.com/watch?v=D59ftjdme3o showed someone using the TRS ID

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1494)
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1494
┆Sprint: Sprint 48- Walrus
┆Issue Type: Story

**Comment by NatalieEO** [comment]
Copy buttons on a tool (cwl and wdl) and workflow working correctly. Used info on this endpoint https://dev.dockstore.net/api/static/swagger-ui/index.html#/GA4GHV20/toolsIdGet

[Webservice](https://github.com/dockstore/dockstore/commits/8d9d617) - 8d9d617

[UI](https://github.com/dockstore/dockstore-ui2/commits/092723ef) - 2.6.3-74-g092723ef

[Compose Setup](https://github.com/dockstore/compose_setup/commits/a4858c6) - a4858c6

[Deploy](https://github.com/dockstore/dockstore-deploy/) - null
