### ISSUE TITLE
Document CI/CD best practices for workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3669]
**Is your feature request related to a problem? Please describe.**
There is a Dockstore user who is using CI/CD for their workflows, using the Dockstore GitHub apps:

1. Pushes to repo A
1. CI Server builds, lints, run tests, flattens, and pushes to repo B
1. Repo B is configured with Dockstore and GitHub apps, so that Dockstore refreshes from changes to repo B almost immediately.

Brian O suggested documenting this as a best practice.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1495)
┆Epic: Dockstore documentation 
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-1495
┆Sprint: 128 - Arsenale
┆Issue Type: Story

**Comment by melainalegaspi** [comment]
This may be the approach that Galaxy IWC takes, so look for a pre-made document from the group.

**Comment by denis-yuen** [comment]
FYI @mvdbeek @dpark01
Do either of you have anything written down that we can endorse and/or contribute to?
