### ISSUE TITLE
Wrong descriptor value for Galaxy

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3670]
**Describe the bug**
TRS says descriptor type for Galaxy should be [GALAXY](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/openapi/ga4gh-tool-discovery.yaml#L723).

Dockstore says it is GXFORMAT2.

**To Reproduce**
```
curl -X GET "https://dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Fjmchilton%2Fgalaxy-workflow-dockstore-example-2" -H  "accept: application/json" | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   929  100   929    0     0   2191      0 --:--:-- --:--:-- --:--:--  2191
{
  "aliases": [],
  "checker_url": "",
  "description": "Test Workflow",
  "has_checker": false,
  "id": "#workflow/github.com/jmchilton/galaxy-workflow-dockstore-example-2",
  "meta_version": "2020-07-17 16:37:36.993",
  "name": "galaxy-workflow-dockstore-example-2",
  "organization": "jmchilton",
  "toolclass": {
    "description": "Workflow",
    "id": "1",
    "name": "Workflow"
  },
  "url": "https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fjmchilton%2Fgalaxy-workflow-dockstore-example-2",
  "versions": [
    {
      "author": [],
      "containerfile": false,
      "descriptor_type": [
        "GXFORMAT2"
      ],
      "id": "#workflow/github.com/jmchilton/galaxy-workflow-dockstore-example-2:master",
      "images": [],
      "included_apps": [],
      "is_production": false,
      "meta_version": "2019-12-03 17:50:48.0",
      "name": "master",
      "signed": false,
      "url": "https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fjmchilton%2Fgalaxy-workflow-dockstore-example-2/versions/master",
      "verified": false,
      "verified_source": []
    }
  ]
}
```

**Additional context**
 - Webservice version: 1.9.0
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1496)
┆Issue Type: Story
┆Sprint: Sprint 40 Octopus
┆Issue Number: DOCK-1496

**Comment by garyluu** [comment]
Essentially we don't support 2.0.0 yet

**Comment by coverbeck** [comment]
Just noticed that the subclass for Galaxy workflows in .dockstore.yml is also `GXFORMAT2`. Sigh.

**Comment by garyluu** [comment]
> Just noticed that the subclass for Galaxy workflows in .dockstore.yml is also `GXFORMAT2`. Sigh.

That's not related to TRS though, so it should be fine?  Dockstore's descriptor language internally is still gxformat2 or w/e we decide to name it.

**Comment by coverbeck** [comment]
> That's not related to TRS though, so it should be fine? Dockstore's descriptor language internally is still gxformat2 or w/e we decide to name it.

Wasn't sure... I guess for the other languages they (happen to?) match up though, don't they?

**Comment by garyluu** [comment]
> > That's not related to TRS though, so it should be fine? Dockstore's descriptor language internally is still gxformat2 or w/e we decide to name it.
> 
> Wasn't sure... I guess for the other languages they (happen to?) match up though, don't they?

ya, it just so happens to match up.
