### ISSUE TITLE
Investigate parsing of Nextflow DSL2

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3674]
Does it break basic parsing of metadata for refresh?
Does it break parsing for DAG support?
Should we validate differently and/or display which Nextflow workflows are DSL2?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1499)
┆Issue Type: Story
┆Sprint: Sprint 42 - Quahog
┆Issue Number: DOCK-1499
┆Epic: Third-party integrations

**Comment by denis-yuen** [comment]
Used by ICGC-Argo and nf-core

**Comment by junjun-zhang** [comment]
👍  would be nice for Dockstore to support NF DSL 2

**Comment by Ldcabansay** [comment]
Spun off specific pieces to fix into the referenced tickets. Seems like nothing blocks users from uploading their DSL2 workflows to dockstore and the launch tab still has the correct command (granted, user would need the correct version of the nextflow executable installed). Validation strangely still says that the nextflow DSL2 workflow is valid even though the webservice nextflow executable is from an older version. Could be from backwards compatibility, something to look out for though.
