### ISSUE TITLE
Investigate parsing and storage of license information

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3675]
We should store this and display this information rather than having to look back at github
Would enable search and/or badges for types of open source workflows
Probably need to store version by version

Of interest (the library we use may have support for this)
https://github.com/hub4j/github-api/pull/820

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1500)
┆Issue Type: Story
┆Sprint: Sprint 42 - Quahog
┆Issue Number: DOCK-1500

**Comment by NatalieEO** [comment]
I do see the license info in the response body after refreshing a workflow and by updating via github apps
API - 1.10.0-alpha.1-SNAPSHOT 
UI - 2.6.1-30-g2d21f244
