### ISSUE TITLE
Better error messages for github app failures

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3678]
**Is your feature request related to a problem? Please describe.**
I was trying to create a nextflow dockstore.yml, however I used nextflow instead of nfl for the subclass. This caused an error. The UI only shows "HTTP 418". It is likely the message is lost by the lambda.

**Describe the solution you'd like**
The error messaged should display what the error was (message), and not just the error code.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1503)
┆Epic: Automated sync of Dockstore and GitHub apps 
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1503
┆Sprint: Sprint 51- Zooplankton
┆Issue Type: Story

**Comment by agduncan94** [comment]
After some investigation, the DB only contains "HTTP 418" for the message for many lambda events. Not sure if this is the error message being returned by our webservice, or if the lambda is overwriting.

**Comment by GFJHogue** [comment]
Looks like this is already all done!
The UI for lambda error messages is already covered by GitHub App Logs.

![Screenshot_2020-12-23 Dockstore My Workflows(1)](https://user-images.githubusercontent.com/5513934/103019886-7dac3680-4515-11eb-9017-707a8c75cbe7.png)
![Screenshot_2020-12-23 Dockstore My Workflows](https://user-images.githubusercontent.com/5513934/103019891-800e9080-4515-11eb-946f-00664855c51d.png)

**Comment by GFJHogue** [comment]
The useful error messages were added in #3409 (April) and the UI in https://github.com/dockstore/dockstore-ui2/pull/999 (June), so I'm guessing that sometime after this ticket was made (July) these got tied together. Confusing timeline.

Since I'm essentially reviewing this now, it looks to be working fine - closing.
