### ISSUE TITLE
Nextflow workflow launch information

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3680]
**Describe the bug**
I added a nextflow workflow (nf-core/rnaseq) using github apps. The launch tab shows a nextflow command, however the referenced git repo is undefined.

Occurred on dev (1.10.0-alpha.0-SNAPSHOT). Doesn't seem to occur on the 1.9.0 release on prod, but please double check.

**To Reproduce**
1. Fork https://github.com/nf-core/rnaseq
2. Install gh app
3. Add .dockstore.yml (see below)
4. Check launch tab, see "nextflow run http://undefined -r master"

ex. dockstore.yml
version: 1.2
workflows:
   - subclass: nfl
     primaryDescriptorPath: /nextflow.config

**Expected behavior**
undefined should be the workflow path.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1505)
┆Epic: Third-party integrations 
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1505
┆Sprint: Backlog
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
Should this be a 1.9.x rather than 1.10?

**Comment by denis-yuen** [comment]
>  but please double check.

**Comment by NatalieEO** [comment]
Doesn't seem to be a problem anymore

Tried a new .dockstore.yml workflow and transitioned a full workflow to a .dockstore.yml one and both showed the correct github link
