### ISSUE TITLE
Support Dockstore.yml existing in the /.github folder

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3682]
**Is your feature request related to a problem? Please describe.**
nf-core suggested allowing users to put the .dockstore.yml in the /.github directory. This is nice because it doesn't clutter up the root of a repo with config information.

**Describe the solution you'd like**
Support .dockstore.yml existing in /.github folder. Default to /.dockstore.yml.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1507)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 41 Pufferfish
┆Issue Number: DOCK-1507
┆Epic: Automated sync of Dockstore and GitHub apps

**Comment by agduncan94** [comment]
Note for tiebreaking - first check for .dockstore.yml, then only if that doesn't exist check for .github/.dockstore.yml.

**Comment by coverbeck** [comment]
On dev, both moved .dockstore.yml back and forth between root and .github folder, and also made duplicates of the file, and all push events worked.

**Comment by ewels** [comment]
This is brilliant - thanks all!
