### ISSUE TITLE
Automatically use most recent tag as default version

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3683]
**Is your feature request related to a problem? Please describe.**
Automation is nice. Setting the default version can be a bit of a hassle when you have many workflows. Would be nice if we could set automatically.

**Describe the solution you'd like**
This could be either set on Dockstore or in a .dockstore.yml. 

If in .dockstore.yml could go in a general config section.
ex. 
```
workflows:
   - subclass: ...
     primaryDescriptorPath: ...
     config:
        defaultVersion: tag/branch/manual
```

If on Dockstore, have a place where a user can set the default version to be automatic.
There could be a checkbox that when clicked, will automatically update the default version. I think it is fine if we default this to true for new workflows and default to most recent tag.

They could have a few options - most recent tag, most recent branch, most recent tag/branch

I am leaning towards the second option as it works for all workflows.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1508)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1508
┆Sprint: Sprint 62- Mako shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Initial thought: how do we handle different branches having different values for the defaultVersion in the .dockstore.yml? Most recent one wins? One problem is that I'm not sure that the events the web service would reciever would be deterministic. And

**Comment by agduncan94** [comment]
Fair enough, I think that is enough of a reason just to have this set on Dockstore. Since this is a workflow level option and not a branch option. I could see something like hidden being set on the .dockstore.yml, though it could also be set on the UI (it is now)

**Comment by denis-yuen** [comment]
Thought: `defaultVersion: tag/branch/manual` looks a bit like a mode switch, which is confusing because we need to reconcile conflicting values between branches. 
What if it was just a single boolean like "setDefault" that defaults to false for current behavior and can be set to true in order for us to process that single tag/branch as the default?
It could even be "setDefaultIfTag" to ignore branches so the user wouldn't need to change it back and forth when working on branches.

**Comment by denis-yuen** [comment]
Yeah, and the scope of the variable would be just that branch as opposed to the workflow as a whole. 
It would suffer from that determinism with rapid releases, but that seems a bit like an edge case.

**Comment by agduncan94** [comment]
After more thought, I think that the dockstore.yml should not have workflow specific information. It should only ever have version specific information. I think the default branch should be set on Dockstore.

**Comment by denis-yuen** [comment]
Elaborate?
I think I agree that .dockstore.yml should not have workflow-wide information. 
But I think it should be possible to define a flag in a way that the webservice doesn't need to look at the .dockstore.yml in other branches, i.e. version specific

**Comment by agduncan94** [comment]
I guess I see the default version as a property of the workflow and not a property of the version. The .dockstore.yml is version specific (besides the implicit path to the workflow). If this was something like hidden, which is a version specific property, I'd be inclined to include it (though still need to put in more thought). I think allowing for workflow properties just adds too much complexity to both the code and to users. I also don't think it is something people should have to make a commit to github for.

**Comment by agduncan94** [comment]
After more thought, I think I like my idea of having the options on Dockstore, where a user can select one of the following

- [ ] most recent tag

- [ ] most recent branch

- [ ] most recent tag/branch

- [ ] custom (current approach)

We could default to most recent tag or something (open for discussion). Though I'm wondering if this would make a good user level or organisation level property. For example, maybe nf-core just always wants to use recent tag, so would be nice if that is automatically applied to new workflows.

**Comment by denis-yuen** [comment]
Yeah, also philosophically, I would implement it almost resembling a filter as in #3695
i.e. like 
```
workflows:
  - name: gwas
    primaryDescriptorPath: /gwas.wdl
    filter: 
      - gwas*
      - develop
   default:
      - tags
```

Implementing an organization default would be a good follow-up, but maybe much later since we don't really have organizations (aside from in the context of organizations and collections).

**Comment by agduncan94** [comment]
In that case, filter is version specific. Its value does not matter to any other versions, since it is purely whether or not to add the current version.

For the default version, how would we handle different values between versions? What if the master branch had -tags and the develop branch had -branches. Which one would we use?

**Comment by denis-yuen** [comment]
Yeah, I'm probably being unclear. In both cases I would treat it essentially as a filter. 
In my proposal, they're basically just two kinds of filter i.e.
1) Does this filter mean that the current push I'm looking at should be ignored?
2) Does this default filter mean that the current push I'm looking at should be set as a default?

We don't need to look at other branches.

**Comment by agduncan94** [comment]
I understand but am still wary about it. I think it adds some extra confusion to the user.

They could be in a case where it is set to branches in one version, but in another, it is set to tags. If they were to keep alternating pushes between these, it would keep changing the default version. This and situations like it could confuse the user.

I could be swayed to having it in the dockstore.yml, but I think we need to think of cases that may cause strange behaviour for the end user first in order to make sure it is the best option.

**Comment by denis-yuen** [comment]
I agree, there may well be cases that I have not considered. This is almost a devil's advocate/strawman proposal. 

But for the alternating pushes, this doesn't seem entirely different from someone having a `.travis.yml` that tests using python 2 in one branch and python 3 in a different branch. Or for that matter a `.dockstore.yml` that has 
```
workflows:
  - name: gwas
    primaryDescriptorPath: /gwas.wdl
    filter: 
      - gwas*
``` 
in one branch and 
```
workflows:
  - name: gwas
    primaryDescriptorPath: /other-path.wdl
    filter: 
      - develop
```
in another

**Comment by coverbeck** [comment]
The problem I see with `default` in the .dockstore.yml is that the order in which versions will be processed won't be deterministic. If multiple branches have conflicting defaultVersions, which one wins? The last one processed by Dockstore, but that won't necessarily be the last one pushed: Dockstore might be temporarily down, so they end up in different order in the queue; when we move to multiple Dockstore instances, one might finish before the other, etc.

 That's a variant of Andrew's alternating pushes example.
