### ISSUE TITLE
Migrate Dockstore created/maintained workflows to using GitHub app

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3694]
**Is your feature request related to a problem? Please describe.**
Dockstore created/maintained workflows still need to be manually refreshed on Dockstore

**Describe the solution you'd like**
Would be a good idea to 'eat our own dog food' and migrate the workflows created or maintained by the Dockstore team to using the Dockstore GitHub app. Also a good starter project. 

**Additional context**
Some examples (probably more)
* [bamstats](https://github.com/CancerCollaboratory/dockstore-tool-bamstats)
* [bcc2020-training](https://github.com/dockstore/bcc2020-training)
* [TOPmed workflows](https://github.com/DataBiosphere/topmed-workflows/tree/develop)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1512)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 44- Sea Horse
┆Issue Number: DOCK-1512
┆Epic: Automated sync of Dockstore and GitHub apps

**Comment by coverbeck** [comment]
Confirmed that bcctraining-2020 repo exists on prod, has .dockstore.yml
