### ISSUE TITLE
Remove restub button for checker workflows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3704]
**Describe the bug**
From this issue https://github.com/dockstore/dockstore/issues/3088, a PR was created to no longer allow restubbing of checker workflows. But this needs UI changes. The restub is still there and clicking on it results in an error in the console, but nothing is displayed to the user.

**To Reproduce**
1. Create a checker workflow
2. Navigate to it
3. Click restub
4. Nothing happens

**Expected behavior**
Since it's not allowed, I expected the button to be gone entirely or greyed out with a reason.

**Additional context**
dev.dockstore.net
API - 1.10.0-alpha.0-SNAPSHOT 
UI - 2.6.0-18-gb9dd8cd6

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1517)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1517
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Bug

**Comment by garyluu** [comment]
Doesn't work. Seems like webservice is returning is_checker instead of isChecker (which is what swagger/openapi says)
