### ISSUE TITLE
Lazy Load Sourcefiles: Investigate/fix remaining issues in webservice

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3712]
**Is your feature request related to a problem? Please describe.**
Been working towards lazy loading sourcefiles and I think the last thing is actually doing so is setting it in the web service and seeing how broken it is. Looks like a number of tests fail https://github.com/dockstore/dockstore/pull/3709. Not sure how much work it will be hence the "invesigate/fix" title.

**Describe the solution you'd like**
Set sourcefiles to lazy and fix what's broken in the webservice or at least get a sense of the remaining work.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1521)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.10
┆Sprint: Sprint 41 Pufferfish
┆Issue Number: DOCK-1521
┆Epic: Performance improvements

**Comment by Ldcabansay** [comment]
A bit difficult to do check only api endpoints to verify that sourcefiles are removed, should review with UI after #1068 is merged
