### ISSUE TITLE
Allow users to delete rejected orgs in UI

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#3714]
**Is your feature request related to a problem? Please describe.**
Users should be able to delete rejected organizations in the UI. This feature should be done after dockstore/dockstore#3254.

**Describe the solution you'd like**
Implement a button in the UI that calls the endpoint to delete rejected organizations.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1522)
┆Issue Type: Story
┆Sprint: Sprint 43- Ringed Seal
┆Issue Number: DOCK-1522
┆Epic: Organization Improvements

**Comment by coverbeck** [comment]
Verified that I can delete pending/rejected orgs on dev. And that I cannot delete approved orgs, even as an admin.
