### ISSUE TITLE
Versions dropdown should be sorted alphabetically in My Workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3722]
**Is your feature request related to a problem? Please describe.**
In My Workflows, the versions dropdown selector displays the versions in, I think, date modified order. If you have a lot of versions, makes it hard to find the version you are looking for.

**Describe the solution you'd like**
Versions in the dropdown should be sorted alphabetically.

1. Goto https://dev.dockstore.net/my-workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_cwl (or if you don't belong to that org, any workflow with a lot of versions.
2. Click versions dropdown at top -- see versions in non-alphabetical order -- makes it hard to find the one you are looking for.

![Screen Shot 2020-08-06 at 10 54 30 AM](https://user-images.githubusercontent.com/1049340/89565379-56a5d000-d7d3-11ea-9e2d-706c42895c19.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1525)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-1525
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by garyluu** [comment]
funny, i remember it was originally alphabetical

**Comment by denis-yuen** [comment]
... yeah, this seems like a preference kind of thing. 
Maybe just add a search field if you know what you're looking for rather than recently changed ones
