### ISSUE TITLE
Error messages for multiple accounts somewhat confusing

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3729]
**Describe the bug**
A user can login to Dockstore in one of two ways, Google and GitHub. However, if they unknowingly do this (or forget), they can run into a situation where they cannot link their "second" account to their first. This is on purpose (imagine being able to login to two different accounts with the same github account).
However, the error messages could be more clear. Attaching a specific user interaction and feedback

https://oicr.slack.com/archives/C16ET3CF4/p1597099060157900

Ideas: the error message indicates  `[HTTP 409] OK: A 'github.com' token already exists on Dockstore for the account 'foo'`
But it isn't clear that foo in this case is a github account and it doesn't indicate that it is linked to a different account or what the name of that other account is. We should indicate something about multiple accounts, give the name of that alternate account and what login method was used plus link to a FAQ entry on the issue. 
https://docs.dockstore.org/en/develop/faq.html#what-is-the-difference-between-logging-in-with-github-or-logging-in-with-google

**Additional context**
 - UI version: 2.6.0
 - Webservice version:1.9.0

Thanks @nivasquez

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1527)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10359/Screen+Shot+2021-03-23+at+2.06.11+PM.png">Screen Shot 2021-03-23 at 2.06.11 PM.png</a>
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1527
┆Sprint: Sprint 55- Dusky shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Another user just ran into this today. Already scheduled for 1.11 release, but noting it in case we're tempted to push it back another release (which still may be necessary.
