### ISSUE TITLE
Sending notification via swagger-ui for openapi fails with 415, same notification via swagger suceeds

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3735]
**Describe the bug**
Tried to send 
```
{
  "message": "We will have downtime on Thursday August 13th around 12:30 PM PST or 3:30pm EST for a new minor release of Dockstore.",
  "expiration": "2020-08-14T20:20:02.221Z",
  "type": "SITEWIDE",
  "priority": "LOW"
}
```

When using https://dockstore.org/api/static/swagger-ui/index.html#/curation/createNotification 
It died with 
```
{
  "code": 415,
  "message": "HTTP 415 Unsupported Media Type"
}
```

Pointed swagger-ui at https://dockstore.org/api/swagger.yaml
The same thing succeeded

**Additional context**
 - Webservice version: [e.g. 1.9.0]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1530)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1530

**Comment by coverbeck** [comment]
Confirmed that I was able to create and delete a notification via OpenAPI on dev
