### ISSUE TITLE
Investigate adding views or download information for workflows

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3736]
**Is your feature request related to a problem? Please describe.**
Seeing how many people have looked at or downloaded a workflow can help users determine which workflows are likely of higher quality.

**Describe the solution you'd like**
In the UI, we should surface some information regarding usage of a workflow. This could be as simple as how many views a page for a workflow gets, or how many times a zip bundle is downloaded. We could possibly also use how many times our API is called (TRS/proprietary)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1533)
┆Issue Type: Story
┆Sprint: Sprint 42 - Quahog
┆Issue Number: DOCK-1533

**Comment by denis-yuen** [comment]
Might be able to seed this with information from google analytics

**Comment by agduncan94** [comment]
Some ideas. Downloading doesn't make much sense in our case. I think it would be cooler to have views and launches.
Views
* could simply be the number of page views for a tool/workflow (might be able to use Google Analytics)
* count of the TRS endpoints being called
* a combination

Launches
* a count for the number of clicks of our launch with buttons
* a count of launching using our CLI
* a combination

**Comment by agduncan94** [comment]
I made a doc on the google drive (under storytimes)

**Comment by garyluu** [comment]
https://docs.google.com/document/d/1o_SKfRZHBNgaj2H6_BfLt7N6rrWBgYKMcBLU-XnWwUE/edit

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore/issues/3781
