### ISSUE TITLE
new read-only role for organizations

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3742]
Basically an affiliate role with no permissions, just to show support or cheerleading a particular organization

See also: 
- https://docs.dockstore.org/en/develop/advanced-topics/organizations-and-collections.html?highlight=maintainer#organization-membership

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1536)
┆Issue Number: DOCK-1536
┆Sprint: Sprint 42 - Quahog
┆Issue Type: Story

**Comment by Ldcabansay** [comment]
If no issues with changing/shifting existing names, I think think the more explanatory hierarchy role names would be:
1. Admin (can add, remove, edit the roles of other users in Organization, plus all permissions of 'Maintainer') 
2. Maintainer (can edit organization and collections)
3. Member (read-only)
So pretty much everyone who is currently a 'Maintainer' will be shifted to 'Admin', all current 'Members' will become 'Maintainer' and then read-only affiliate role will then be 'Member'

**Comment by NatalieEO** [comment]
Reviewer can make sure the new user roles are there and work as described below.
New user roles:
Members: No permissions
Maintainers: Can create and update organizations and collections
Admins: Maintainer permissions and can add, remove and edit the roles of other users.
