### ISSUE TITLE
Infinite loading when editing unpublished tools

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#3758]
**Describe the bug**
Editing unpublished tools results in the Mat Dialog popping up and loading indefinitely. This should not happen and it seems to be happening on dev, prod, and staging.

**To Reproduce**
1. Create a tool manually via dockstore and create two versions of that tool
2. Make sure that the tool is not published
3. Navigate to the 'Versions' tab and click on edit

**Expected behavior**
The Material Dialog should not pop up at all and an error should be displayed indicating that the tool has been published so it cannot be edited. Workflows seems to be handling this error, so the expected behavior should be similar to that. Looking into the console would also display the HTTP error message for a better understanding of the bug.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1547)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 45- Trumpetfish
┆Issue Number: DOCK-1547

**Comment by GFJHogue** [comment]
I can't seem to reproduce this, so whoever investigates this may need more details.

It might be helpful to include how you've registered the tool (Quay.io, manual register, etc.).
Also you can see if there's a failed Network request or Console error in your browser's dev tools & include that here.

**Comment by ByteMap** [comment]
> I can't seem to reproduce this, so whoever investigates this may need more details.
> 
> It might be helpful to include how you've registered the tool (Quay.io, manual register, etc.).
> Also you can see if there's a failed Network request or Console error in your browser's dev tools & include that here.

Thanks for the input! I’ve included that the tool needs to be manually created via Dockstore.

**Comment by denis-yuen** [comment]
Additonal info 
https://oicr.slack.com/archives/C16ET3CF4/p1599679218124900

**Comment by Ldcabansay** [comment]
Seems to affect unpublished hosted tools (versions tab > actions > edit)

**Comment by coverbeck** [comment]
Reopening, should be merged, not done in JIRA.

**Comment by garyluu** [comment]
It does fix the infinite loading bar, but it also causes double the amount of requests.
