### ISSUE TITLE
Ensure THIRD-PARTY-LICENSES.txt is checked in

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#3763]
**Describe the bug**
Currently THIRD-PARTY-LICENSES.txt is changing whenever a maven build is executed.

**Expected behavior**
THIRD-PARTY-LICENSES.txt should be checked in. Please make a CI build fail to address this. 

Additionally, the file should leave out our own project (e.g., io.dockstore:swagger-java-bitbucket-client) as anything that we create is deemed as first-party instead of third-party.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1550)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.10
┆Sprint: Sprint 45- Trumpetfish
┆Issue Number: DOCK-1550

**Comment by denis-yuen** [comment]
Clarifying that the file changes when dependencies change, but if an author for a PR doesn't check it in, the changes could end up getting checked-in in a different PR that is unrelated.
