### ISSUE TITLE
Add a Launch with Galaxy button

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3764]
**Describe the solution you'd like**

After galaxyproject/galaxy#9999 is merged and released,  Dockstore should add a launch with button that lets users export a Galaxy workflow in Dockstore to a Galaxy instance.

This will be more complex than our current other launch with buttons. Other platforms are accessible through known urls. With Galaxy, dozens or hundreds of instances may be spun up and down. Some thoughts in increasing order of complexity:

1. Initially only point to well-known instance(s) of Galaxy, e.g. usegalaxy.org
2. Prompt the user for a url. The user could either type in the url, or select from some list of well-known and previously entered urls (see next sub-bullets):
    1. Save the url(s) in local storage
    2. Save the url on the web service (if the user is logged in)

**Additional context**

@jmchilton -- What is the pattern of the endpoint we should redirect to?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1551)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10427/Screen+Shot+2021-06-02+at+2.27.18+PM.png">Screen Shot 2021-06-02 at 2.27.18 PM.png</a>
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1551
┆Sprint: Sprint 62- Mako shark
┆Issue Type: Story

**Comment by jmchilton** [comment]
``https://usegalaxy.org/workflows/trs_search?trs_server=dockstore.org&trs_id=<ID>``

**Comment by bgruening** [comment]
I think it is `https://usegalaxy.org/workflows/trs_import?trs_server=dockstore.org&trs_id=<ID>`

**Comment by NatalieEO** [comment]
Hey @jmchilton and @bgruening I just started looking into adding the Launch with Galaxy button. 

I was trying out the redirect urls you all provided, and I don't believe they are working quite right. For example, if I use the second link, https://usegalaxy.org/workflows/trs_import?trs_server=dockstore.org&trs_id=#workflow/github.com/afgane/galaxy-workflows it doesn't auto-populate or perform the search. The search itself works fine once I use the TRS ID. The first link doesn't work and says it's searching for a long time.

I was also wondering if you all intend to make use of the version name in the redirect url?

**Comment by coverbeck** [comment]
@NatalieEO , looks like you need to escape the hashtag:

```
https://usegalaxy.org/workflows/trs_import?trs_server=dockstore.org&trs_id=%23workflow/github.com/afgane/galaxy-workflows
```

I looked at the source code, and there it does look like there is a trs_version_id, but I can't get it to work.

**Comment by bgruening** [comment]
@NatalieEO WorkflowHub has this here working: https://workflowhub.eu/workflows/110

But I think there is a problem on the Galaxy side for the dockstore integration. Its a little bit unfortunate that both TRS endpoints behave differently. We will look into this tomorrow.

**Comment by bgruening** [comment]
> Does galaxy support file imports? http(s) imports?

For workflows or data? But yes it should.

> Is there a galaxy language specification you can provide a link to?

What do you mean here? Which language? For workflows or tools? Or do you mean [Galaxy API](https://docs.galaxyproject.org/en/release_21.01/api_doc.html)?

**Comment by denis-yuen** [comment]
I think we're looking for http://galaxyproject.github.io/gxformat2/v19_09.html but its not clear how file imports are specified.

**Comment by bgruening** [comment]
The screenshot does not work, but this is cool! Thanks for getting this in!

**Comment by denis-yuen** [comment]
The screenshot not working is a JIRA/Github integration thing
Looks like ![Screen Shot 2021-06-02 at 2 27 18 PM](https://user-images.githubusercontent.com/1730679/120659551-78540000-c454-11eb-9a97-1c0b22db7006.png) and is taken of https://dev.dockstore.net/workflows/github.com/jmchilton/galaxy-workflow-dockstore-example-2:master?tab=info
