### ISSUE TITLE
Nextflow  DSL2 DAG support

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3766]
Building off #3674 

**Is your feature request related to a problem? Please describe.**
Nextflow DSL2 workflows have broken DAG visualizations.

**Describe the solution you'd like**
Add DAG visualization support for DSL2 Nextflow workflows. 

Upgrading the webservice executable from `19.01.0` to `20.07.1` doesn't seem to resolve this issue. Would need to look deeper into what's needed for this to work. 

**Describe alternatives you've considered**
Unsure whether this will be dependent on indexing modules (#3761), depends on whether we generate the DAG visualization ourselves or if we use the nextflow executable.

**Additional context**
Example:
Workflow [rnaseq-nf tag v1.2](https://github.com/Ldcabansay/rnaseq-nf/tree/v1.2)  is DSL1 and dag works:
![image](https://user-images.githubusercontent.com/23464754/91363961-9ba99a80-e7b2-11ea-9c7a-e5df5c5b388b.png)

However [tag v2.0](https://github.com/Ldcabansay/rnaseq-nf/tree/v2.0) is DSL2 and dag does not work:
![image](https://user-images.githubusercontent.com/23464754/91363851-6604b180-e7b2-11ea-8c89-c691c857d3e2.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1553)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1553
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Note for implementer: A temporary 1.9.x hotfix would be to display a message saying we're working on DSL2 before implementing it

**Comment by melainalegaspi** [comment]
This needs to be investigated. If there's not a lot of work to be done, leave in 1.12, if there's a substantial amount of work then this can wait for a later release.
