### ISSUE TITLE
Nextflow DSL2 tools tab support

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3767]
Building off #3674

**Is your feature request related to a problem? Please describe.**
Nextflow DSL2 workflows have broken tools tab support. When navigating to the tools tab of a DSL2 workflow with module imports you get the error:
```
 Some tools associated with this workflow are missing from Git repo.
```

**Describe the solution you'd like**
Add support for showing the tools and associated images for nextflow DSL2 workflows.

Seems like #3761 will be required before implementing this. Upgrading the webservice executable from 19.01.0 to 20.07.1 doesn't seem to resolve this issue. 

**Additional context**
Example:
Workflow [rnaseq-nf tag v1.2](https://github.com/Ldcabansay/rnaseq-nf/tree/v1.2)  is DSL1 and tools tab shows the different process names and the docker image associated:
![image](https://user-images.githubusercontent.com/23464754/91364644-13c49000-e7b4-11ea-8870-d9c790a2fa74.png)

However [tag v2.0](https://github.com/Ldcabansay/rnaseq-nf/tree/v2.0) is DSL2 and does not work:
![image](https://user-images.githubusercontent.com/23464754/91364586-f263a400-e7b3-11ea-897a-5c43dae3d674.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1554)
┆Issue Number: DOCK-1554
┆Sprint: Sprint 50- Yellowfin Tuna
┆Issue Type: Story

**Comment by denis-yuen** [comment]
A temporary 1.9.x hotfix would be to display a message saying we're working on DSL2 before implementing it

**Comment by garyluu** [comment]
Main difference is that the v2.0 has imports that show the "process" whereas v1.2 only has the main.nf that shows it

**Comment by garyluu** [comment]
For those who are reviewing this, you want to register a new DSL 2.0 workflow on Dockstore.
