### ISSUE TITLE
Requesting re-review for rejected org outputs a 403 error

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#3780]
**Describe the bug**
Requesting a re-review for rejected orgs as a non-admin/curator results in an error dialog stating `Getting my memberships failed`. This is most likely due to the fact that requesting a re-review updates the curators' orgs in the service. 

This issue occurs on prod.

**To Reproduce**
1. Create an organization filling in only the 3 required fields
2. Ensure that you have admin/curator status
3. Go to My Account -> Requests
4. Reject the organization that was just created
5. Remove your admin/curator status and refresh the requests page
6. Request a re-review for the rejected organization
7. Error should pop up

**Expected behavior**
Requesting a re-review on a rejected organization should not result in a 403 error. 

If I am correct and this error is caused by updating the curators' organizations after requesting a re-review, then adding a checker to ensure that the user who is requesting the re-review is an admin/curator before calling on the API call to update the curators' orgs may be a solution.

**Screenshots**
<img width="478" alt="Screen Shot 2020-09-01 at 5 08 41 PM" src="https://user-images.githubusercontent.com/42463687/91917847-fab95480-ec75-11ea-91db-82d42ffaf643.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1560)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10433/Screenshot+2021-06-10+at+14.19.46.png">Screenshot 2021-06-10 at 14.19.46.png</a>
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1560
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
This is marked for 1.11, so you'll need to review on dev. Do you have permissions there?

**Comment by denis-yuen** [comment]
FYI @chmreid , I've made you a curator on dev. Give it a shot
