### ISSUE TITLE
Bug or null handling during rewrite of json

### ISSUE THREAD

**Issue by keiranmraine** [dockstore/dockstore#3784]
**Describe the bug**

I'm getting the following error when testing the dockstore interaction with cwltool for updates to an existing tool (new arguments).  Files are pulled from FTP addresses before this error occurs, the error also occur if json file references local files:

```bash
10:25:35.810 [main] ERROR io.dockstore.client.cli.ArgumentUtility - null
10:25:35.813 [main] ERROR io.dockstore.client.cli.ArgumentUtility - java.lang.NullPointerException
	at io.github.collaboratory.cwl.CWLClient.createUpdatedInputsAndOutputsJson(CWLClient.java:963)
	at io.github.collaboratory.cwl.CWLClient.provisionInputFiles(CWLClient.java:244)
	at io.dockstore.client.cli.nested.BaseLanguageClient.launchPipeline(BaseLanguageClient.java:164)
	at io.github.collaboratory.cwl.CWLClient.launch(CWLClient.java:289)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1185)
	at io.dockstore.client.cli.nested.AbstractEntryClient.checkEntryFile(AbstractEntryClient.java:815)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:1132)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:278)
	at io.dockstore.client.cli.Client.run(Client.java:715)
	at io.dockstore.client.cli.Client.main(Client.java:614)
```

Runs cleanly via cwltool if files are made local in advance.

**To Reproduce**

`curl` points to head of `feature/dockstoreLayerOnly` of [dockstore-cgpmap](https://github.com/cancerit/dockstore-cgpmap/tree/feature/dockstoreLayerOnly) at time of writing:

```
curl -L https://github.com/cancerit/dockstore-cgpmap/archive/352e2fd7371fee01c555992ff813452a303d23f0.tar.gz | tar zx
cd dockstore-cgpmap*
docker build -t quay.io/wtsicgp/dockstore-cgpmap:3.2.0 .
dockstore tool --script launch --local-entry cwls/cgpmap-bamBaiOut.cwl --json examples/cgpmap/bamBaiOut/bam_in.json
```

**Expected behavior**

No error, workflow runs.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: NA
 - Browser: NA
 - Version:

Built following [quick-start](https://dockstore.org/quick-start) on 2020-09-03 (cwltool is very old in that document)

```
$ dockstore --version
Dockstore version 1.9.0
You are running the latest stable version...
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
$ cwltool --version
/home/ubuntu/.local/bin/cwltool 1.0.20190621234233
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1563)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 44- Sea Horse
┆Issue Number: DOCK-1563

**Comment by denis-yuen** [comment]
Linking to https://github.com/dockstore/dockstore/issues/3591 for cwltool version. 
I also think I ran into a problem with ruamel with the current requirements.txt

At first glance, it looks like it could be an error in dealing with the array structure  or the removal of bams_in
```
  "seq_in": [
    {"class": "File",
      "path": "ftp://ngs.sanger.ac.uk/production/cancer/dockstore/cgpmap/insilico_21.bam"}
  ],
```

Note that we've launched https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap:2.0.3?tab=files before in our testing framework. https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap:3.0.0?tab=files shows a validation error which might be related. 

@garyluu  (may want to run in Openstack)

**Comment by coverbeck** [comment]
@garyluu Is this something Richard could look at, or do you think the OpenStack environment is required? Seems like it is failing in the provisioning phase, at least to start with, so OpenStack may not be necessary?

**Comment by garyluu** [comment]
yup, it's not necessary to use OpenStack for this

**Comment by Richard-Hansen** [comment]
The error is caused by having null values within the JSON, and is being fixed. In the above example, replacing/removing {"threads" : null} to a non-null value should solve the immediate bug.

**Comment by keiranmraine** [comment]
I can confirm that all 6 CWL routes through the code work if the nulls are replaced by values.
