### ISSUE TITLE
Cannot change language of .dockstore.yml workflow

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3790]
**Describe the bug**
After registering as the wrong language, cannot change

**To Reproduce**
1. Add a workflow with a .dockstore.yml as Nextflow
2. Change language  in .dockstore.yml
3. Create a new release to signal github apps
4. Will display old language

**Additional context**
API - 1.9.1 
UI - 2.6.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1567)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 45- Trumpetfish
┆Issue Number: DOCK-1567

**Comment by coverbeck** [comment]
Note to self for verification: The code fix is a new endpoint that lets the user change the entry's descriptor type.

**Comment by coverbeck** [comment]
Verified in dev, with a workflow registered via GitHub apps.

1. Create a Galaxy workflow, but  had NFL as the subclass in .dockstore.yml
1. Pushed the branch, saw error in UI
1. Changed the descriptor type with new endpoint to Galaxy
1. Updated the .dockstore.yml’s subclass to galaxy and pushed again
1. Saw the Galaxy version.

Note, there was an unexplained bit of delay for the last step, but it did work.
