### ISSUE TITLE
.dockstore.yml does not appear with workflow with workflow name

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3791]
**Describe the bug**
Have a workflow which is in DOCKSTORE_YML mode but the .dockstore.yml doesn't show up in the files tab. 
Might be related to the fact that this is the first one with a workflow name that I tried (there is also an entry for repo without a name)
https://github.com/denis-yuen/hello-dockstore-workflow/blob/testCWL/.dockstore.yml

Alternatively `0.769e56badc962b0c30d6.js:1 commitId or providerUrl is not truthy`?

**Expected behavior**
Should see .dockstore.yml in files tab like other workflows

**Screenshots**
![Screenshot from 2020-09-04 12-07-36](https://user-images.githubusercontent.com/1730679/92261409-5f0f2a80-eea7-11ea-8d2e-030f6218c581.png)
![Screenshot from 2020-09-04 12-07-38](https://user-images.githubusercontent.com/1730679/92261415-60405780-eea7-11ea-9113-1247a2b16e78.png)

**Additional context**
API - 1.9.1 
UI - 2.6.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1568)
┆Issue Type: Story
┆Sprint: Sprint 44- Sea Horse
┆Issue Number: DOCK-1568

**Comment by garyluu** [comment]
The files tab is version specific, the testBoth version does not appear to have a .dockstore.yml

**Comment by denis-yuen** [comment]
Good call, can confirm that `testCWL` has it.
