### ISSUE TITLE
Add local link checking to read the docs

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3793]
**Is your feature request related to a problem? Please describe.**
We currently only test for broken external links when doing link checks on read the docs. We should add local link checks so errors/warnings pop up when references to internal links are broken.

**Describe the solution you'd like**
`make linkcheck` should also check for broken internal links and give errors when found. Consider how link checks will relate to re-directs (if necessary).

**Describe alternatives you've considered**
We also can enforce an SOP that uses preferred way to refer to local links (ie only absolute paths, only certain types of referencing styles, etc)

**Additional context**
This is part of the documentation overhaul, should probably be completed before/during adding re-directs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1570)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1570

**Comment by melainalegaspi** [comment]
@Richard-Hansen completed this

**Comment by coverbeck** [comment]
Fixed via dockstore/dockstore-documentation#85
