### ISSUE TITLE
Investigate/update broken tests in CLI due to ignoring sourcefiles

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3795]
**Describe the bug**
This PR https://github.com/dockstore/dockstore/pull/3789 may break tests in the CLI, so fix if it does.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1571)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.10
┆Sprint: Sprint 46- Unicorn Fish
┆Issue Number: DOCK-1571

**Comment by coverbeck** [comment]
Note: this is blocked by a web service release.
