### ISSUE TITLE
Delete GitHub App WorkflowVersion Default Version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3796]
**Describe the bug**
Cannot delete a version using GitHub Apps when the version is a default version

**To Reproduce**
1. Have a GitHub Apps workflow with a version that is set as the default version
2. Try Deleting that version on GitHub
See error on webservice:

ERROR [2020-08-26 17:38:47,194] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR: update or delete on table "workflowversion" violates foreign key constraint "fk_workflow_default_workflowversion" on table "workflow"→  Detail: Key is still referenced from table "workflow".

**Expected behavior**
No 500 error, default version set to another

**Additional context**
 - UI version: [e.g. 2.6.1]
 - Webservice version: [e.g. 1.9.1]
 - host location: [dockstore.org]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1572)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 45- Trumpetfish
┆Issue Number: DOCK-1572

**Comment by denis-yuen** [comment]
Correctly iterated from tag to master branch on delete

[Webservice](https://github.com/dockstore/dockstore/commits/c05258a) - c05258a

[UI](https://github.com/dockstore/dockstore-ui2/commits/78c22deb) - 2.6.1-52-g78c22deb

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6c50698b903981ca78f05759cc2c3a7049e847a6) - 6c50698b903981ca78f05759cc2c3a7049e847a6

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/da01baf) - 1.9.2-33-gda01baf
