### ISSUE TITLE
Edit unpublished hosted version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3801]
**Describe the bug**
There is a "[HTTP 403] OK: Entry not published" error that happens when you Click "Edit" on a hosted version

**To Reproduce**
1. Go to My Tools and/or My Workflows
2. Have a hosted tool/workflow
3. Click versions
4. Click edit
5. See either
- indefinite loading bar
- alert that pops up at the top saying "[HTTP 403] OK: Entry not published"

**Expected behavior**
Two things:
- If we are allowed to edit an unpublished entry, then there should be no error
- When there is an error (for whatever reason), there should not be an indefinite loading bar

**Additional context**
 - host location: [dockstore.org and dev]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1575)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1575
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by Ldcabansay** [comment]
I only see the entry not published error on unpublished hosted Workflows, whereas infinite loading happens on unpublished tools. 

I think we _should_ be able to edit unpublished hosted tools/workflows so this is odd, not sure why published ones are okay to edit. From what I can recall, edit currently has 2 functions: 
1. add a test parameter file
2. hide a version

For hosted entries only hiding a version seems actionable. You add test parameter files via the files tab in hosted entries.

**Comment by garyluu** [comment]
Note: The missing alert is slightly tricky for tools because it calls two endpoints

**Comment by garyluu** [comment]
Might've been fixed already
