### ISSUE TITLE
Handle new OrgUser role for deleting orgs

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3808]
**Describe the bug**
Hotfix branch adds a new org user role; what was maintainer is now an admin. There is [new code in develop](https://github.com/dockstore/dockstore/blob/8c4d0bc0590a155641f93ad769d5ae3bd32e7bab/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java#L434) that probably needs to be updated, that the hotfix didn't update, because the code doesn't exist on the hotfix branch.

There is probably also UI code that needs to updated as well.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1581)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1581
┆Sprint: Backlog
┆Issue Type: Story

**Comment by NatalieEO** [comment]
The code Charles linked should probably check the user is a organization admin not maintainer now. Maintainers became admins.

**Comment by coverbeck** [comment]
@NatalieEO , I'm going to reassign to you since you're more familiar with it. :)

**Comment by GFJHogue** [comment]
**Review**: Was able to delete a pending Org I created on dev - issue seems to be resolved!
