### ISSUE TITLE
Refresh Organization fails once a .dockstore.yml workflow is reached

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3811]
**Describe the bug**
If you've registered/migrated a workflow using github apps, doing a `Refresh Organization` will fail once it gets to that workflow. 
**To Reproduce**

1. Have at least one .dockstore.yml workflow in an organization
1. Click on `Refresh Organization`
1. See that once it reaches the .dockstore.yml workflow, the call fails and stops.

**Expected behavior**
It should skip over any .dockstore.yml workflows and continue to refresh the others.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/c354528)

* c354528

[UI](https://github.com/dockstore/dockstore-ui2/commits/df02f7cf)

* 2.6.1-38-gdf02f7cf

[Compose Setup](https://github.com/dockstore/compose_setup/commits/8c083bddfa2e8cfcb517792d45b03b95dc3dda5d)

* 8c083bddfa2e8cfcb517792d45b03b95dc3dda5d

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d87bd60)

* 1.9.2-21-gd87bd60

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1583)
┆Fix Versions: Dockstore 1.11.X
┆Issue Number: DOCK-1583
┆Sprint: Sprint 72-Yellowspotted Catsha
┆Issue Type: Story

**Comment by denis-yuen** [comment]
(note to self: this is a synthetic operation refreshing each one individually, not 
https://github.com/dockstore/dockstore/issues/3523  come back to haunt us all)

**Comment by denis-yuen** [comment]
UI could also not refresh .dockstore.yml workflows, what error code does the UI get back?

**Comment by NatalieEO** [comment]
.dockstore.yml workflows do fail, but the refresh org call continues on to other workflows
[Webservice](https://github.com/dockstore/dockstore/commits/45e63c0) - 45e63c0

[UI](https://github.com/dockstore/dockstore-ui2/commits/476caf35) - 2.7.3-96-g476caf35

[Compose Setup](https://github.com/dockstore/compose_setup/commits/80a6669) - 80a6669

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/8e3f6bd) - 1.10-71-g8e3f6bd

**Comment by NatalieEO** [comment]
Reopening because not sure if this actually isn't working in prod, or if the error appears and continues to refresh https://ucsc-gi.slack.com/archives/C16ET3CF4/p1632860210390100

**Comment by garyluu** [comment]
tested this on dev, the error appears and continues to refresh

**Comment by NatalieEO** [comment]
Refreshing the org does correctly skip over .dockstore.yml workflows. No errors.
[Webservice](https://github.com/dockstore/dockstore/commits/83de67a) - 83de67a

[UI](https://github.com/dockstore/dockstore-ui2/commits/3e14769a) - 2.8.4-119-g3e14769a

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/920b171) - 1.11.3-113-g920b171

galaxyParsingLambdaVersion: 0.0.6
