### ISSUE TITLE
Version validation not updated on .dockstore.yml workflows

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3812]
**Describe the bug**
On a .dockstore.yml workflow, if you have a branch with an invalid workflow descriptor and then push changes to correct it
the the Files tab will get rid of the validation messages, but the Versions tab tab will still not indicate it is valid. The reverse is true as well. If you have a valid branch and update it to be invalid, the Versions tab will not get updated properly, but the Files tab will.

This will prevent users from using the Launch-With Buttons or seeing the commands in the Launch tab. 

**To Reproduce**
1. Register a .dockstore.yml workflow that contains one invalid version
2. Go to GitHub and push changes that will make the workflow valid
3. Return to Dockstore and see that your file changes got pushed, but your version is still marked as invalid.

**Expected behavior**
Versions tab needs to get updated appropriately

**Additional context**
Production and Dev
API - 1.9.1 dockstore status indicator
UI - 2.6.1

[Webservice](https://github.com/dockstore/dockstore/commits/c354528) - c354528

[UI](https://github.com/dockstore/dockstore-ui2/commits/df02f7cf) - 2.6.1-38-gdf02f7cf

[Compose Setup](https://github.com/dockstore/compose_setup/commits/8c083bddfa2e8cfcb517792d45b03b95dc3dda5d) - 8c083bddfa2e8cfcb517792d45b03b95dc3dda5d

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d87bd60) - 1.9.2-21-gd87bd60

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1584)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1584
┆Sprint: Sprint 52- Angel shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Run into and confirmed by @afshinmessiah
