### ISSUE TITLE
Link for non-DockerHub tools is incorrect

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3820]
**Describe the bug**
If a workflow references a non-DockerHub Docker image, the link incorrectly has hub.docker.com as the domain.

**To Reproduce**
```
curl -s 'https://dockstore.org/api/workflows/5874/tools/13615' -H 'Accept: application/json' | jq '.'
[
  {
    "id": "icgc_pcawg_dkfz_workflow",
    "file": "dkfz/icgc_pcawg_dkfz_sbg.cwl",
    "docker": "images.sbgenomics.com/bogdang/pcawg-dkfz:1.0",
    "link": "https://hub.docker.com/_/images.sbgenomics.com/bogdang/pcawg-dkfz"
  },
  {
    "id": "pcawg_icgc_delly_workflow_1",
    "file": "delly/icgc_pcawg_seqware_delly_sbg.cwl",
    "docker": "images.sbgenomics.com/bogdang/pcawg-delly:10072019",
    "link": "https://hub.docker.com/_/images.sbgenomics.com/bogdang/pcawg-delly"
  }
]
```

Note how the links are to DockerHub, even though the images are hosted on SB.

Visible in the UI by navigating to https://dockstore.org/workflows/github.com/sbg/sbg_dockstore_tools/icgc_pcawg_dkfz_embl_sbg_modified:master?tab=tools 

**Expected behavior**
Links should be to SB Docker image repository.

**Additional context**
 Happens on prod and dev. Dev info:

[Webservice](https://github.com/dockstore/dockstore/commits/2589683) - 2589683

[UI](https://github.com/dockstore/dockstore-ui2/commits/3b3889cf) - 2.6.1-42-g3b3889cf

[Compose Setup](https://github.com/dockstore/compose_setup/commits/8c083bddfa2e8cfcb517792d45b03b95dc3dda5d) - 8c083bddfa2e8cfcb517792d45b03b95dc3dda5d

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/3fa31af) - 1.9.2-24-g3fa31af

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1588)
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1588
┆Sprint: Sprint 45- Trumpetfish
┆Issue Type: Story

**Comment by GFJHogue** [comment]
Current logic for making the link doesn't yet support non-DockerHub/Quay entries (the code just reaches the last else clause):
https://github.com/dockstore/dockstore/blob/96424cf3dc0f7ca623efc17670613db659242b55/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java#L361

A simple solution for now could be to check if the entry looks like a URL with regex?

**Comment by NatalieEO** [comment]
> Current logic for making the link doesn't yet support non-DockerHub/Quay entries (the code just reaches the last else clause):
> https://github.com/dockstore/dockstore/blob/96424cf3dc0f7ca623efc17670613db659242b55/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java#L361
> 
> A simple solution for now could be to check if the entry looks like a URL with regex?

Didn't do much with it, but wrote some code that tries to detect the other image registries we support as an FYI https://github.com/dockstore/dockstore/blob/96424cf3dc0f7ca623efc17670613db659242b55/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java#L373

**Comment by coverbeck** [comment]
I may be oversimplifying this, but when discussing with Andy and we were trying to figure this out for the spreadsheet, it seems that if the image has one slash in it, it's DockerHub; if it has two, it's not (unless they redundantly specify DockerHub).

**Comment by coverbeck** [comment]
In dev, the link is no longer DockerHub and is to sbgenomics.

However, the http link for SB doesn't work, and per [this page](https://docs.sevenbridges.com/docs/the-image-registry), SB does not have a web page, so there is no place to link to. Options:

1. It's OK as is
2. Link should be null
3. ?

**Comment by GFJHogue** [comment]
> In dev, the link is no longer DockerHub and is to sbgenomics.
> 
> However, the http link for SB doesn't work, and per [this page](https://docs.sevenbridges.com/docs/the-image-registry), SB does not have a web page, so there is no place to link to. Options:
> 
> 1. It's OK as is
> 2. Link should be null
> 3. ?

Both (1) and (2) make sense in their own ways.

My case for (1) is that assuming the link works in the default case is probably a good thing for using new/unsupported registries.

**Comment by coverbeck** [comment]
Going to close. We can revisit link discussion if it comes up from a user, otherwise, I think it's good for now.
