### ISSUE TITLE
Descriptors for published entries should all have checksums.

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#3826]
**Is your feature request related to a problem? Please describe.**
Descriptors for published entries should all have checksums. Some descriptors have null checksums if they haven't been refreshed recently, [see here](https://docs.dockstore.org/en/develop/advanced-topics/checksum-support.html?highlight=checksum#file-descriptor-checksum-support).

**Describe the solution you'd like**
Update the database via migrations.
Dynamically calculate on the fly.

**Describe alternatives you've considered**

**Additional context**
When validating descriptor checksums, we could enforce stronger actions (such as exiting a launch) if a checksum is not present. In the current state, there are published tools/workflows that haven't been refreshed recently, and thus do not have checksums. Reference #3664

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1591)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1591
┆sprint: Seabright Sprint 78- Flotsam
┆taskType: Story

**Comment by melainalegaspi** [comment]
May have been addressed by PR for sha256.

**Comment by denis-yuen** [comment]
Interesting, I think it actually should. A null and empty string actually have the same values. 
https://stackoverflow.com/a/27493820

```
$ sha256sum test.out
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test.out
$ sha256sum /dev/null
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /dev/null
$ md5sum /dev/null
d41d8cd98f00b204e9800998ecf8427e  /dev/null
$ md5sum < /dev/null
d41d8cd98f00b204e9800998ecf8427e  -
```

**Comment by coverbeck** [comment]
Agreed, I think it should as well (and that's how the sha256 function behaves in Postgres as well).

@kathy-t for verification, can you please make sure that TRS is returning the sha256 values as well?
