### ISSUE TITLE
Tools not being counted in language facet

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3834]
**Describe the bug**
On dev, the counts for the language facet don't seem to include tools.

Works in prod and staging

**To Reproduce**
1. Go to https://dev.dockstore.net/search?searchMode=files
2. Compare with https://dockstore.org/search?searchMode=files

**Expected behavior**
As in prod, the sum of all language facets should add up to the sum of tools and workflows.

**Screenshots**
![Screen Shot 2020-09-28 at 3 10 12 PM](https://user-images.githubusercontent.com/1049340/94491355-edbc5200-019c-11eb-9f7f-55a12d8328e2.png)

523 workflows + 238 tools = 761

318 WDL + 175 CWL + 28 NF + 2 GALAXY = 523 (the number of workflows)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/6e877bf) - 6e877bf

[UI](https://github.com/dockstore/dockstore-ui2/commits/23d6e519) - 2.6.1-46-g23d6e519

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6c50698b903981ca78f05759cc2c3a7049e847a6) - 6c50698b903981ca78f05759cc2c3a7049e847a6

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/da01baf) - 1.9.2-33-gda01baf

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1597)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1597
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by garyluu** [comment]
Seems extremely unlikely that it would add up since tools can have multiple languages

**Comment by denis-yuen** [comment]
To clarify, elaborate, expected behavior would be " As in prod, the sum of all language facets should be greater than or equal to the sum of tools and workflows." Looking in prod today, its off by 6 (so, not a lot).

**Comment by coverbeck** [comment]
> Seems extremely unlikely that it would add up since tools can have multiple languages

I was wondering about that as well, but could have sworn they added up yesterday. My math was probably off.

**Comment by denis-yuen** [comment]
Note to implementer, see if this checks out. There might not be any work

**Comment by denis-yuen** [comment]
Still seems a little weird
https://dev.dockstore.net/workflows says we have 555 workflows
https://dev.dockstore.net/search?entryType=workflows&searchMode=Files has a sum of 528 workflows across all languages.
The difference isn't (just) checker workflows which would take us to 547?

We have https://dev.dockstore.net/tools 243 tools, 252 in search but that is probably as Gary mentioned having to do with multiple languages for tools. Going to create a new ticket since that workflow discrepancy seems different enough from the original issue.

**Comment by denis-yuen** [comment]
Branched to https://ucsc-cgl.atlassian.net/browse/SEAB-2815
