### ISSUE TITLE
Default version can't be changed after making invalid version the default

### ISSUE THREAD

**Issue by mvdbeek** [dockstore/dockstore#3847]
I registered a Galaxy workflow using the .dockstore.yml procedure. I then removed the leading forward slash in `primaryDescriptorPath` and `testParameterFiles` and pushed this to another branch. Curiously without forward slashes I see the tool ids and DAG for this workflow, even though this seems to be invalid (see screenshot, where the error message is also missing .ga as valid extension for Galaxy workflows). With leading forward slash the workflow appears to be valid, but tools ids and DAG can't be displayed. If I now set the default version to the invalid workflow I can't change it back to the valid workflow.

<img width="602" alt="Screenshot 2020-10-06 at 09 39 09" src="https://user-images.githubusercontent.com/6804901/95172577-ce827d80-07b7-11eb-85a6-e38d1fe60993.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1601)
┆Issue Number: DOCK-1601
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Hi, 

I can confirm that the error message should list `.ga` as an extension for Galaxy workflows. 
I cannot reproduce the error where the default version cannot be changed after making the invalid version default. 
Do you happen to have a screenshot of the error message?

**Comment by mvdbeek** [comment]
There's no error message, the action had just disappeared from the actions menu. Which is now there again, but I did push a version with a leading slash to that branch.

**Comment by denis-yuen** [comment]
Could it be possible that you navigated to the public version of the workflow which only has view as an option?
i.e. https://dockstore.org/workflows/github.com/mvdbeek/workflow-testing-repo/COVID-19%20variation%20analysis%20on%20Illumina%20metagenomic%20data:no_forward_slash?tab=versions

**Comment by mvdbeek** [comment]
That could be what happened, yes.

**Comment by denis-yuen** [comment]
(discussion continues at https://github.com/galaxyproject/galaxy/issues/10359 )
