### ISSUE TITLE
Broken link in github apps wizard

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3848]
**Describe the bug**
Broken link in ui2 wizard page
Reproduced in dev and prod
Also see https://discuss.dockstore.org/t/broken-link-in-register-using-github-apps-instructions/3896

Thanks @mr-c ! for the heads-up

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1602)
┆Issue Number: DOCK-1602
┆Sprint: Sprint 46- Unicorn Fish
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Also bumping https://github.com/dockstore/dockstore/issues/3793

**Comment by GFJHogue** [comment]
Already done by @denis-yuen in hotfix 2.7.2 - works on staging :)
https://github.com/dockstore/dockstore-ui2/pull/1075

**Comment by GFJHogue** [comment]
Confirmed also working on dev.
Likely we forgot the change was made to hotfix/2.7.2 and then assumed it wasn't done, because it wasn't on dev until we merged the hotfix back into develop.

**Comment by denis-yuen** [comment]
Oh, whoops
