### ISSUE TITLE
Galaxy workflow assumes *.ga Galaxy workflow has json parameters when it actually has yaml parameters

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3851]
**Describe the bug**
Pretty much the title, it also seems to break the tool and DAG pages (might be that we don't display a DAG if a workflow doesn't validate?)

**To Reproduce**
![Screenshot from 2020-10-07 16-30-22](https://user-images.githubusercontent.com/1730679/95384404-9021b700-08ba-11eb-8a4a-7baac301ebee.png)

Fork repo at https://github.com/mvdbeek/workflow-testing-repo/commit/438edfaef2d192285d2f1c1eb9ed4f6366dad7aa

**Expected behavior**
Should parse test parameter as a yaml (based on file extension ... or possibly for all Galaxy workflows?)

**Additional context**
API - 1.9.1 
UI - 2.6.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1604)
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1604
┆Sprint: Sprint 46- Unicorn Fish
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Relevant log is 
```
10.0.0.22 - - [07/Oct/2020:20:44:10 +0000] "GET /workflows/15813/primaryDescriptor?tag=master&language=gxformat2 HTTP/1.0" 400 19 "https://dockstore.org/workflows/github.com/mvdbeek/workflow-testing-repo/COVID-19%20variation%20analysis%20on%20Illumina%20metagenomic%20data:master?tab=dag" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 41
```

Message in web browser is `No descriptor found`

**Comment by garyluu** [comment]
Unrelated. I didn't realize we allowed non-alphanumberic workflow names

**Comment by coverbeck** [comment]
Verified working on dev

[Webservice](https://github.com/dockstore/dockstore/commits/8d9d617) - 8d9d617

[UI](https://github.com/dockstore/dockstore-ui2/commits/092723ef) - 2.6.3-74-g092723ef

[Compose Setup](https://github.com/dockstore/compose_setup/commits/a4858c6) - a4858c6

[Deploy](https://github.com/dockstore/dockstore-deploy/) - null
