### ISSUE TITLE
Failing to refresh a token returns 500

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3855]
**Describe the bug**

While registering a workflow a user got "Could not retrieve bitbucket.org token" with a 500 status code.

**To Reproduce**
See screenshot. Theory is the BitBucket refresh token has expired. Relinking the BitBucket account fixed the issue.

**Expected behavior**
* This is not a server error. It is normal for refresh tokens to expire, and these errors should not trigger our alerts.
* It should be a 4XX error, not sure which -- I guess a 401, because you're no longer authorized.
* The UI should display a friendly message, e.g., please relink your BitBucket account. I believe we do something similar for when your Google refresh token expires.
* This point may be worth splitting out into a separate ticket, but it seems odd that it's even trying to refresh the BitBucket token in this scenario. Still need to handle the above points though, because there will be cases when it does need to refresh.
* Error is being thrown from [here](https://github.com/dockstore/dockstore/blob/15ad4ce281b1c063e8968dc72b0a84b7c1271b6b/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/SourceControlResourceInterface.java#L109).

**Screenshots**
![image](https://user-images.githubusercontent.com/1049340/95631527-be2d0580-0a38-11eb-8581-8a8ea302cf3e.png)

**Additional context**
dockstore.org 1.9.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1606)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1606
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Quick note if there is follow-up, refresh tokens do not expire https://community.atlassian.com/t5/Bitbucket-questions/May-I-ask-how-long-will-the-refresh-tokens-expires/qaq-p/351138#M12372 
At least my token from February 2021 was not old enough to trigger

That said, revoking application straight up from Bitbucket seemed sufficient to cause the same situation

**Comment by NatalieEO** [comment]
Does return a 401 now, but will create a new ticket for 

> This point may be worth splitting out into a separate ticket, but it seems odd that it's even trying to refresh the BitBucket token in this scenario. Still need to handle the above points though, because there will be cases when it does need to refresh.
