### ISSUE TITLE
Downloading a Tool's Dockerfile returns an un-parsed JSON.

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#3862]
**Describe the bug**
When downloading the dockerfile for a tool from, the downloaded file is a json in the form [{content:"..."}] rather than just the desired portion.

**To Reproduce**
1. Go to https://dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:2.1.0?tab=files
2. Click on the download button:
<img width="58" alt="Screen Shot 2020-10-13 at 3 36 03 PM" src="https://user-images.githubusercontent.com/36607471/95923206-de770000-0d69-11eb-9668-b49623b3e62b.png">
3. View the downloaded Dockerfile.

**Expected behavior**
Should only download the content of the Dockerfile, and not the JSON from the API call.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1610)
┆Fix Versions: Dockstore 1.9.X
┆Issue Number: DOCK-1610
┆Sprint: Sprint 47- Vampire Squid
┆Issue Type: Story

**Comment by denis-yuen** [comment]
needs to hit different endpoint
