### ISSUE TITLE
Linking Zenodo token 500

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3865]
**Describe the bug**
Going to `https://dockstore.org/auth/zenodo.org?error=invalid_request&error_description=Missing%20response_type%20parameter` should not produce a NPE or 500 error, BAD REQUEST is more suitable

**To Reproduce**
1. Log into Dockstore.org
2. Put `https://dockstore.org/auth/zenodo.org?error=invalid_request&error_description=Missing%20response_type%20parameter` in your browser
3. See 500

**Expected behavior**
No NPE, no 500

**Additional context**
 - UI version: 2.6.1
 - Webservice version: 1.9.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1611)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1611
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Looks out of date, getting a 404 on 1.10.1
