### ISSUE TITLE
A workflow has two Descriptor Files tabs

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3867]
**Describe the bug**
A particular workflow has two "Descriptor Files" tabs in the Files tab.

Did not research more, i.e., does it occur with other workflows or not, etc.

**To Reproduce**
1. Go to 'https://dockstore.org/workflows/github.com/nf-core/eager:2.1.0?tab=files

**Expected behavior**
There should be one tab, or the tabs should have different names.

**Screenshots**
![Screen Shot 2020-10-14 at 5 29 48 PM](https://user-images.githubusercontent.com/1049340/96059608-43525900-0e43-11eb-8e0f-f13bbed1614b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 - UI version: 2.6.1
 - Webservice version: 1.9.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1612)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1612
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by garyluu** [comment]
Probably the main question to ask is...when the webservice returns primary descriptors and secondary descriptors like:

```
[{file_type: "SECONDARY_DESCRIPTOR", path: "bin/endorS.py"},…]
0: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/endorS.py"}
1: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/extract_map_reads.py"}
2: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/kraken_parse.py"}
3: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/markdown_to_html.py"}
4: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/merge_kraken_res.py"}
5: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/print_x_contamination.py"}
6: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/scrape_software_versions.py"}
7: {file_type: "SECONDARY_DESCRIPTOR", path: "conf/base.config"}
8: {file_type: "SECONDARY_DESCRIPTOR", path: "conf/igenomes.config"}
9: {file_type: "SECONDARY_DESCRIPTOR", path: "main.nf"}
10: {file_type: "PRIMARY_DESCRIPTOR", path: "nextflow.config"}
```

 what should happen?
 
1. A hack to combine them into a singular Descriptor Files tab that has both
2. 2 tabs (Primary Descriptor and Secondary Descriptor)
3. 2 tabs but with a different name than 2

**Comment by denis-yuen** [comment]
(Actually, I didn't see the image on JIRA. What I saw on a workflow recently was two Descriptor tabs vertically on top of each other, not horizontally. Keep an eye out I guess)

For this, I would have assumed they would be combined in one tab with the primary descriptor being the first selected or highlighted in some way. This is related to https://github.com/dockstore/dockstore/issues/4004
