### ISSUE TITLE
Can't Delete Account

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3868]
**Describe the bug**
Cannot delete account, throws 500

**To Reproduce**
1. Have lambda events (possibly by setting up GitHub Apps)
2. Make sure everything is unpublished and account is ready for deletion
3. Try deleting account
4. See 500 error

```
ERROR [2020-10-14 18:02:13,352] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR: update or delete on table "enduser" violates foreign key constraint "fkj387wwrofm9u30t4mwiiwa835" on table "lambdaevent"→ Detail: Key (id)=(9001) is still referenced from table "lambdaevent".

14:02:13
INFO [2020-10-14 18:02:13,352] org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl: HHH000010: On release of batch it still contained JDBC statements

14:02:13
ERROR [2020-10-14 18:02:13,352] io.dockstore.webservice.jdbi.UserDAO: something happened with delete, probably cascades are broken

14:02:13
! org.postgresql.util.PSQLException: ERROR: update or delete on table "enduser" violates foreign key constraint "fkj387wwrofm9u30t4mwiiwa835" on table "lambdaevent"

14:02:13
! Detail: Key (id)=(9001) is still referenced from table "lambdaevent".
```

**Expected behavior**
The account should be deleted

**Additional context**
 - UI version: 2.6.1
 - Webservice version: 1.9.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1613)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1613
┆Sprint: Sprint 54- Cat shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
@garyluu 
This has already been fixed? I can't reproduce this. I made a new account on dev, set up a github app workflow on it, and successfully deleted my account.

**Comment by NatalieEO** [comment]
@garyluu Okay, I found the user this was originally affecting by going through the logs and locally was able to delete his account. Seems like Greg's PR here https://github.com/dockstore/dockstore/pull/3630 fixed this problem, but that wasn't deployed until 1.10.0
