### ISSUE TITLE
500 Getting Tool Zip

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3869]
**Describe the bug**
Getting a 500 when trying to get zip file

**To Reproduce**
1. Go to https://dockstore.org/api/containers/1754/zip/6353
2. See error

**Expected behavior**
Either return a zip file or a bad request with a good error message

**Additional context**
 - UI version: 2.6.1
 - Webservice version: 1.9.1
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1615)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1615
┆Sprint: Sprint 57- Frilled shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
From https://github.com/dockstore/dockstore/issues/3869# it doesn't look right, it should be reporting a 404 so I think we have a regression

**Comment by denis-yuen** [comment]
Hmmm, actually @chmreid did you try the exact URL above?
This is a 1.11 fix so it won't be in production, just in dev

https://dev.dockstore.net/api/containers/1754/zip/6353 gives a 404 which could be legit
https://dev.dockstore.net/api/containers/84/zip/20956 works
https://dev.dockstore.net/api/containers/84/zip/99999999999 is 404
https://dev.dockstore.net/api/containers/999999999999/zip/20956 is 404
