### ISSUE TITLE
Double test parameter files requests

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3871]
**Describe the bug**
There's double the amount of requests when trying to edit a version.

**To Reproduce**
1. Go to my-tools and have a tool version that can be edited
2. Open the dev tools to look at requests
3. Click on Actions -> Edit
4. See 2+2 requests

**Expected behavior**
Should only see 2 requests.  1 for WDL, 1 for CWL

**Additional context**
 - UI version: dev
 - Webservice version: dev
 - host location: dev.dockstore.net

Introduced by https://github.com/dockstore/dockstore/issues/3758

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1616)
┆Issue Number: DOCK-1616
┆Sprint: Sprint 47- Vampire Squid
┆Issue Type: Story

**Comment by coverbeck** [comment]
Looks good to me in dev, staging, and prod.
