### ISSUE TITLE
An organization admin/maintainer should be able to delete a collection

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3874]
**Is your feature request related to a problem? Please describe.**
As an organization maintainer (role changing to admin soon), you can create and edit a collection, add and remove dockstore entries from a collection, but you cannot delete the collection as whole.

**Describe the solution you'd like**
You should be able to delete an entire collection if you are a maintainer (soon to be admin) of the organization.

**Describe alternatives you've considered**
I guess "archive" instead of delete.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1618)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1618
┆Sprint: Sprint 72-Yellowspotted Catsha
┆Issue Type: Story

**Comment by bethsheets** [comment]
I agree that there should be an ability to delete a collection. For example, an organization may want to change what they promote over time. Or, maybe their workflow catalog is growing at such a rate that they want to organize them in a different way, like reduce and consolidate the number of collections. 

Additionally, as some orgs take a stronger stance on secure workflows, they may want to remove older workflow collections that aren't up to their current standards.
