### ISSUE TITLE
Set publishing on in .dockstore.yml

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3876]
**Describe the solution you'd like**
https://discuss.dockstore.org/t/ability-to-have-have-new-workflow-repos-become-public-by-default/3920/2

**Describe alternatives you've considered**
Could hit https://dockstore.org/api/static/swagger-ui/index.html#/workflows/publish_1 but this would be more user-friendly

Requested by @mvdbeek

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1619)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10376/image-20210415-184212.png">image-20210415-184212.png</a>
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1619
┆Sprint: Sprint 56- Epaulette shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
I agree with the need, the implementation might be tricky... The .dockstore.yml is a version level setting, publishing is a a workflow-level operation. What happens if the .dockstore.yml in one version says publish and in another version it doesn't publish? Or do we just say that whenever we run across this setting, the workflow gets published if it's not already?

We had talked about the ability to publish versions rather than workflows, but that's a much bigger change. That would work well with this setting.

**Comment by garyluu** [comment]
Ya, would be tricky. A compromise is to only use that setting during install events.  So upon initial install, the database makes note of the setting. Then all subsequent push events with that setting (regardless of whether it's different than the original) is ignored.

**Comment by denis-yuen** [comment]
voted on by @ewels in call

**Comment by ewels** [comment]
This would be super handy for us in @nf-core as we are adding new pipelines on a semi-regular basis that are (hopefully) based on our template. This has a `.dockstore.yml` file in it, so we could define such as setting there.

Doing a manual sync and publish of all workflows every once in a while is a possibility, but having it automated would mean that this doesn't get forgotten and that there is no lag in addition of new workflows to Dockstore 👍🏻

**Comment by GFJHogue** [comment]
**Notes for reviewer**:

Adds optional boolean `publish` field to .dockstore.yml workflows & services.

Added a `PUBLISH` LambdaEvent to GitHub Apps logs indicate success/failure of YML publish/unpublish operations.

Behaviour:
- Publishing is version-agnostic, using the latest push with a `publish` setting regardless of version.
- Setting `publish: True` or `publish: False` runs the same logic as `POST ​/workflows​/{workflowId}​/publish`.
- Not setting `publish` runs no publishing logic, effectively keeping the current setting.

Example workflow YML:

```
version: 1.2
workflows:
   - subclass: CWL
     primaryDescriptorPath: /Dockstore.cwl
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json
```
