### ISSUE TITLE
Document .dockstore.yml filters feature

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3886]
**Is your feature request related to a problem? Please describe.**
It's hard to tell somebody how to use the filters feature in the .dockstore.yml because there is no doc describing how to use it.

**Describe the solution you'd like**
Document it.

**Additional context**
#3695 -- the code change.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1623)
┆Issue Number: DOCK-1623
┆Sprint: Sprint 47- Vampire Squid
┆Issue Type: Story

**Comment by garyluu** [comment]
![image](https://user-images.githubusercontent.com/24548904/99701643-b498b380-2a62-11eb-9a85-2341d39e1fd8.png)


Can see changes at https://docs.dockstore.org/en/develop/getting-started/github-apps/github-apps.html
