### ISSUE TITLE
DELETE hostedEntry workflow endpoint 500 error

### ISSUE THREAD

**Issue by GFJHogue** [dockstore/dockstore#3915]
**Describe the bug**
500 error showing up on prod for `DELETE /workflows/hostedEntry/...` endpoint.
Possibly a side-effect of deleting one version after another.
```
INFO [2020-11-05 03:52:24,916] io.dockstore.webservice.helpers.statelisteners.ElasticListener: Performing index update with UPDATE.
INFO [2020-11-05 03:52:24,916] io.dockstore.webservice.helpers.statelisteners.ElasticListener: Could not perform the elastic search index update.
ERROR [2020-11-05 03:52:24,939] org.hibernate.internal.ExceptionMapperStandardImpl: HHH000346: Error during managed flush [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]
INFO [2020-11-05 03:52:24,940] org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl: HHH000010: On release of batch it still contained JDBC statements
... "DELETE /workflows/hostedEntry/15770?version=2 HTTP/1.0" 500 ...
```

**Expected behavior**
No 500 error and the deletion succeeds.

**Additional context**
 - Webservice version: 1.9.2
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1635)
┆Issue Number: DOCK-1635
┆Sprint: Sprint 48- Walrus
┆Issue Type: Story

**Comment by coverbeck** [comment]
@NatalieEO @GFJHogue Is the verification to make sure deleting a frozen hosted version does not throw a 500? It looks like it from PR but not from the description.

**Comment by NatalieEO** [comment]
@coverbeck Yeah it shouldn't throw a 500, but the deletion should fail with a better error message.

**Comment by coverbeck** [comment]
@NatalieEO Sorry, I wasn't clear -- I was asking if this only happens for frozen versions, or if there were other cases where a 500 might be returned.

**Comment by coverbeck** [comment]
Confirmed on staging that attempting to delete a snapshotted version fails with a 400.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.0-rc.1) - 1.10.0-rc.1

[UI](https://github.com/dockstore/dockstore-ui2/commits/f123e815) - 2.6.3-77-gf123e815

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/release/1.10) - release/1.10

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/db73433) - 1.10.0-rc0-2-gdb73433
