### ISSUE TITLE
Search page tag cloud and format is broken

### ISSUE THREAD

**Issue by nrzhao4** [dockstore/dockstore#3916]
**Describe the bug**
On Search page, the Tag Cloud is broken and thus is not displayed. Also, in Search results table, Format column is displayed as empty

**To Reproduce**
1. Go to Search page while running Dockstore locally
2. See there is no "Tag cloud" button at top of results table
3. See there are no contents in "Format" column of results table

**Expected behavior**
Clicking Tag Cloud button should expand and show correct tag cloud for the current tab (Tools or Workflows)
Format column should show correct format of each entry (WDL, CWL, etc) and should be sortable when you click on the header Format.

**Screenshots**
![Screen Shot 2020-11-05 at 11 28 05 AM](https://user-images.githubusercontent.com/50606789/98268020-05d07f80-1f5a-11eb-9d7a-fbc065844b41.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1636)
┆Issue Number: DOCK-1636
┆Sprint: Sprint 48- Walrus
┆Issue Type: Story

**Comment by coverbeck** [comment]
This is working in dev on

[Webservice](https://github.com/dockstore/dockstore/commits/8d9d617) - 8d9d617

[UI](https://github.com/dockstore/dockstore-ui2/commits/092723ef) - 2.6.3-74-g092723ef

[Compose Setup](https://github.com/dockstore/compose_setup/commits/a4858c6) - a4858c6

[Deploy](https://github.com/dockstore/dockstore-deploy/) - null
