### ISSUE TITLE
Duplicate descriptor files tabs

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3923]
**Describe the bug**
Duplicate tabs with the same name.

**Expected behavior**
Think this was meant to be one tab for descriptors and one for the primary descriptor or .dockstore.yml?

**Additional context**
API - 1.9.2
UI - 2.6.3

**Screenshots**

![Screenshot from 2020-11-11 10-34-41](https://user-images.githubusercontent.com/1730679/98858003-e0e27d80-242d-11eb-8167-bbe857270427.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1640)
┆Issue Number: DOCK-1640
┆Sprint: Backlog
┆Issue Type: Story

**Comment by garyluu** [comment]
More info:
https://dockstore.org/workflows/github.com/nf-core/eager:2.1.0?tab=files

Looks like the webservice is correct:
```
[{file_type: "SECONDARY_DESCRIPTOR", path: "bin/endorS.py"},…]
0: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/endorS.py"}
1: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/extract_map_reads.py"}
2: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/kraken_parse.py"}
3: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/markdown_to_html.py"}
4: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/merge_kraken_res.py"}
5: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/print_x_contamination.py"}
6: {file_type: "SECONDARY_DESCRIPTOR", path: "bin/scrape_software_versions.py"}
7: {file_type: "SECONDARY_DESCRIPTOR", path: "conf/base.config"}
8: {file_type: "SECONDARY_DESCRIPTOR", path: "conf/igenomes.config"}
9: {file_type: "SECONDARY_DESCRIPTOR", path: "main.nf"}
10: {file_type: "PRIMARY_DESCRIPTOR", path: "nextflow.config"}
```

This issue looks familiar though...

**Comment by garyluu** [comment]
yup, https://github.com/dockstore/dockstore/issues/3867

**Comment by denis-yuen** [comment]
Closing as duplicate
