### ISSUE TITLE
Two star icons on search page

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3925]
**Describe the bug**
There are two star icons on the search table results

**To Reproduce**
1. https://dev.dockstore.net/search?searchMode=files
2. See the two icons in the stars column

**Expected behavior**
One icon

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/8d9d617) - 8d9d617

[UI](https://github.com/dockstore/dockstore-ui2/commits/092723ef) - 2.6.3-74-g092723ef

[Compose Setup](https://github.com/dockstore/compose_setup/commits/a4858c6) - a4858c6

[Deploy](https://github.com/dockstore/dockstore-deploy/) - null

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1643)
┆Issue Number: DOCK-1643
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
@Richard-Hansen Wild guess, any chance this is the Material Icons changes?

**Comment by coverbeck** [comment]
Confirmed that it working in staging.

It's not working on dev, but turns out that's because our latest CI build on develop failed, so no build was pushed to s3.
