### ISSUE TITLE
Tool author information seems inconsistent

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3929]
**Describe the bug**
The search page ( https://dockstore.org/search?_type=tool&searchMode=files )  shows authors available for https://dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow 

However, clicking through, verified versions seem to have authorship info in the descriptors but only show "n/a" in the info tabs. 

API - 1.9.2
UI - 2.6.3

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1645)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1645
┆Sprint: Backlog
┆Issue Type: Story

**Comment by garyluu** [comment]
Seems like it is the intended behaviour? https://docs.google.com/document/d/1GvfVMfn5Uo0Ek0ZGdTnP7JGNlnQ2gXrvypFgjIs8tuI/edit#heading=h.mcublmvpysff

**Comment by denis-yuen** [comment]
Will give it a refresh when we next deploy on staging
