### ISSUE TITLE
Cannot execute update Organization API from OpenAPI

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3935]
**Describe the bug**
When trying to execute an [update Organization](https://dev.dockstore.net/api/static/swagger-ui/index.html#/organizations/getOrganizationById) in the OpenAPI, you can get a 415 error, unsupported media type.

**To Reproduce**
1. Go to https://dev.dockstore.net/api/static/swagger-ui/index.html#/organizations/updateOrganization
2. Click on 'Try it out'
3. Specify the id of an org you are admin of
4. Specify a valid body
5. Execute - see error

This is failing because the `Content-type` header value is `*/*`; it needs to be `application/json`.

**Expected behavior**
Should be able to execute this successfully.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/c0e20a8) - c0e20a8

[UI](https://github.com/dockstore/dockstore-ui2/commits/8de4d47c) - 2.6.3-76-g8de4d47c

[Compose Setup](https://github.com/dockstore/compose_setup/commits/a4858c6) - a4858c6

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/49f00b6) - 1.9.3-66-g49f00b6

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1649)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1649
┆Sprint: Backlog
┆Issue Type: Story

**Comment by garyluu** [comment]
Did you mean https://dev.dockstore.net/api/static/swagger-ui/index.html#/organizations/updateOrganization ?

**Comment by coverbeck** [comment]
> Did you mean https://dev.dockstore.net/api/static/swagger-ui/index.html#/organizations/updateOrganization ?

Yes, will update description
