### ISSUE TITLE
Private tool status bar text

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#3942]
**Describe the bug**
Hovering over the 'Request Access' Button of a private tool shows an odd href on the bottom status bar. It ends with:
`
"%20My%20user%20name%20on%20undefined%20is%20%3Cusername%3E"
`

**To Reproduce**
1. Go to a private tool (https://dockstore.org/containers/registry.hub.docker.com/broadinstitute/pcawg_broad_wgs_variant_callers/pcawg-broad-wgs-variant-caller:master?tab=launch)
2. Hover over the 'Request Access" button
3. View status bar message, or inspect the element

**Expected behavior**
href should be filled in with the correct information, such as user and email.

**Additional context**
 - UI version: https://github.com/dockstore/dockstore-ui2/commits/release/2.7, f123e81

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1652)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1652
┆Sprint: Sprint 53- Bull shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
What happens when you click on iit though?

**Comment by GFJHogue** [comment]
**Review**:
The href now shows the Docker registry and makes it obvious that the user must fill out their username for the registry in the email body.
`%20My%20username%20on%20Docker%20Hub%20is%20%3Cinput%20username%20here%3E`
