### ISSUE TITLE
500 Delete Workflow

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3946]
**Describe the bug**
When deleting a workflow, there's a `org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR: update or delete on table "workflow" violates foreign key constraint "FKWorkflowId" on table "event"→  Detail: Key (id)=(15643) is still referenced from table "event".`
Endpoint: DELETE /workflows/registries/github.com/organizations/masri2019/repositories/hpp-assembly

This may or may not be fixed by a similar issue

**To Reproduce**
1. Try deleting a similar workflow

**Expected behavior**
The workflow to be deleted

**Additional context**
 - UI version: 2.6.3
 - Webservice version: 1.9.2
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1654)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1654
┆Sprint: Sprint 57- Frilled shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
Was able to delete a workflow following the instructions Denis left 
[Webservice](https://github.com/dockstore/dockstore/commits/90e9a7a) - 90e9a7a

[UI](https://github.com/dockstore/dockstore-ui2/commits/415a72c2) - 2.7.3-86-g415a72c2

[Compose Setup](https://github.com/dockstore/compose_setup/commits/80a6669) - 80a6669

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6a0ce9d) - 1.10-68-g6a0ce9d
