### ISSUE TITLE
Discourse 'Error Embedding' for new Workflows on Staging 

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#3950]
**Describe the bug**
When creating a new tool/workflow (Hosted, or linking a repository that isn't already in the Staging database from a backup of the prod database), when you publish the entry there may be an 'Error Embedding' in place of the discussion section. 

This is a little flaky, as it can pop up on different browsers ([Slack discussion](https://app.slack.com/client/T09P9H91S/C16ET3CF4/thread/C16ET3CF4-1606340909.192200) has good details)

**To Reproduce**
1. Go to 'My workflows'
2. Register a Hosted Workflow (Or link a new repository)
3. Publish the entry
4. Visit the the public page for the entry
5. Bottom of the page should display the error

**Expected behavior**
Discourse discussion should be available.

**Screenshots**
![Screen Shot 2020-11-25 at 4 55 14 PM](https://user-images.githubusercontent.com/36607471/100296491-6734ae80-2f5a-11eb-929e-fd7bce2dd46e.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser Chrome
 - Version 85.0.4183.83

**Additional context**
 - UI version: [2.7](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7)
 - Webservice version: [1.10](https://github.com/dockstore/dockstore/releases/tag/1.10.0)
 - host location: staging.dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1655)
┆fixVersions: Dockstore 1.13.x
┆friendlyId: DOCK-1655
┆sprint: 95- W
┆taskType: Story

**Comment by coverbeck** [comment]
I see the behavior in Steve's hypothesis; if I'm logged into discuss as an admin, it works; if I'm not logged in I get the error embedding.
