### ISSUE TITLE
Regression integration tests - launch command error

### ISSUE THREAD

**Issue by GFJHogue** [dockstore/dockstore#3958]
**Describe the bug**
Automated regression integration tests only run for releases & master.
The tests started getting the following error starting with `release/1.10`:
https://app.circleci.com/pipelines/github/dockstore/dockstore/5017/workflows/c8d4e924-6e7c-4bb3-a712-34aaae7cabfb/jobs/6365
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 79.943 s <<< FAILURE! - in io.dockstore.client.cli.GeneralWorkflowRegressionIT
[ERROR] testActualWorkflowLaunch(io.dockstore.client.cli.GeneralWorkflowRegressionIT)  Time elapsed: 11.879 s  <<< ERROR!
java.lang.RuntimeException: problems running command: /tmp/junit16906159488294156053/dockstore --config /home/circleci/project/dockstore-integration-testing/target/test-classes/config_file2.txt workflow launch --entry github.com/DockstoreTestUser2/md5sum-checker/testname --json /tmp/junit16906159488294156053/md5sum-wrapper-tool.json --script
	at io.dockstore.client.cli.GeneralWorkflowRegressionIT.testActualWorkflowLaunch(GeneralWorkflowRegressionIT.java:726)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: /tmp/junit16906159488294156053/dockstore --config /home/circleci/project/dockstore-integration-testing/target/test-classes/config_file2.txt workflow launch --entry github.com/DockstoreTestUser2/md5sum-checker/testname --json /tmp/junit16906159488294156053/md5sum-wrapper-tool.json --script (Exit value: 3)
	at io.dockstore.client.cli.GeneralWorkflowRegressionIT.testActualWorkflowLaunch(GeneralWorkflowRegressionIT.java:726)
```
Running the same `dockstore` CLI command locally under the same versions (CLI 1.7.4, same `requirements.txt` 1.7.0, staging webservice 1.10.0) works fine for me, so the problem is likely something with the CI setup.

**To Reproduce**
Open a new dockstore branch.
https://github.com/dockstore/dockstore/blob/0de036d8412f5453a232e21bccdd55402e9da539/.circleci/config.yml#L56
Change
```
      - regression-integration-tests:
          filters:
            branches:
              only:
                - master
                - /^release.*$/
```
to
```
      - regression-integration-tests:
          requires:
            - build
```
and commit to run the tests.

**Expected behavior**
Regression tests should pass.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1659)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1659
┆Sprint: Sprint 51- Zooplankton
┆Issue Type: Story

**Comment by garyluu** [comment]
See https://github.com/dockstore/dockstore/tree/feature/dockerInDockerTest
and https://app.circleci.com/pipelines/github/dockstore/dockstore?branch=feature%2FdockerInDockerTest for simple failing example
