### ISSUE TITLE
Boolean facets don't work on search page

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#3964]
**Describe the bug**
Boolean facets don't work on the search page. Selecting one will lead to the default, un-filtered search view. Looks like boolean facets are using 1 and 0 instead of true or false.

**To Reproduce**
1. Go to dockstore.org
2. Click on search
3. Select 'verified' facet, giving the url https://dockstore.org/search?verified=1&searchMode=files, which is invalid
4. The above URL is invalid. Switching the boolean query value from ```1``` to ```true```: https://dockstore.org/search?verified=true&searchMode=files, works as expected

**Expected behavior**
Boolean facets should filter correctly

**Additional context**
 - UI version: [2.7](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7)
 - Webservice version: [1.10](https://github.com/dockstore/dockstore/releases/tag/1.10.0)
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1664)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1664
┆Sprint: Sprint 50- Yellowfin Tuna
┆Issue Type: Story

**Comment by garyluu** [comment]
Search page broken, need to fix that first

**Comment by Richard-Hansen** [comment]
> https://dockstore.org/search?verified=1&searchMode=files broken, need to fix that first

Looks like this is the real issue. I expect

**Comment by garyluu** [comment]
So essentially all boolean facets are broken
