### ISSUE TITLE
Hosted workflows can't have more than two descriptors.

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#3968]
**Describe the bug**
When adding files to a hosted workflow, the total descriptor count isn't able to exceed 2. Sometimes one of the existing files gets replaced when you add a new entry, sometimes it doesn't, not sure if there is a parsing/ASCII comparison which is determining which descriptors are kept when hitting "Save as new version".

**To Reproduce**
1. Go to https://docs.dockstore.org/en/develop/getting-started/hosted-tools-and-workflows.html
2. Follow the steps in the tutorial
3. Upon saving as a new version, you wont see 1 of the 3 descriptors added.

**Expected behavior**
The expected behavior should be to have multiple descriptor files (probably do want a maximum count anyways), as described in the tutorial https://docs.dockstore.org/en/develop/getting-started/hosted-tools-and-workflows.html.

**Screenshots**
When adding files (note 3 descriptor files):
![Screen Shot 2020-12-08 at 1 29 19 PM](https://user-images.githubusercontent.com/36607471/101525579-7f90ca00-3959-11eb-9b53-47f01642aaf3.png)

After saving (note 2 descriptor files):
![Screen Shot 2020-12-08 at 1 29 30 PM](https://user-images.githubusercontent.com/36607471/101525632-8f101300-3959-11eb-8cbb-e4458242627d.png)

**Additional context**
 - UI version: 2.7
 - Webservice version: 1.10
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1667)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1667
┆Sprint: Sprint 54- Cat shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
Was able to save the 3 files in our tutorial
[Webservice](https://github.com/dockstore/dockstore/commits/0311203) - 0311203

[UI](https://github.com/dockstore/dockstore-ui2/commits/b7a996fa) - 2.7.3-36-gb7a996fa

[Compose Setup](https://github.com/dockstore/compose_setup/commits/f24bc92) - f24bc92

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/f68b014) - 1.10-25-gf68b014
