### ISSUE TITLE
Add WDL checker workflow examples to workflow checker documentation

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#3973]
The checker workflow documentation (https://docs.dockstore.org/en/develop/advanced-topics/checker-workflows.html), only shows examples in CWL. Can we provide examples in all languages (starting with WDL)? This will provide more ease and clarity to end users. 

This an important feature in the chain of trust deliverable.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1669)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1669
┆Sprint: Sprint 52- Angel shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
All else failing, can use https://dockstore.org/workflows/github.com/dockstore-testing/md5sum-checker:1.0.1?tab=info
