### ISSUE TITLE
Language labels wrapping on search page on dev on Firefox

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3996]
**Describe the bug**
On the search page, in dev, if a tool has 2 languages,  the language labels are wrapping in mid-label. They shouldn't.

**To Reproduce**

1. Go to https://dev.dockstore.net/search?searchMode=files

![Screen Shot 2021-01-04 at 1 07 12 PM](https://user-images.githubusercontent.com/1049340/103579800-d96bad80-4e8d-11eb-815b-f3929f18fbd0.png)

**Additional context**
 [Webservice](https://github.com/dockstore/dockstore/commits/dc3e2c1) - dc3e2c1

[UI](https://github.com/dockstore/dockstore-ui2/commits/ba262407) - 2.7-12-gba262407

[Compose Setup](https://github.com/dockstore/compose_setup/commits/47a7d7f) - 47a7d7f

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/dac44c7) - 1.10-4-gdac44c7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1685)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10324/image-20210114-184726.png">image-20210114-184726.png</a> | <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10323/image-20210114-184815.png">image-20210114-184815.png</a> | <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10327/image-20210126-222053.png">image-20210126-222053.png</a>
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1685
┆Sprint: Sprint 53- Bull shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
I'm on FireFox, and just checked, the problem only happens there for me, not on Safari nor Chrome. I should have mentioned that in the description -- didn't realize it was relevant.

**Comment by denis-yuen** [comment]
It happens for me as well on Firefox
