### ISSUE TITLE
Add support for Docker images  GitHub packages

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4002]
ICGC-Argo is using Nextflow with Docker images hosted on GitHub container registry / packages as a response to image expiry (partly discussed in #423 )

https://docs.github.com/en/free-pro-team@latest/packages/guides/about-github-container-registry

Add support for it for tools. Implementer can sync up with @junjun-zhang or the softeng team

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1688)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1688
┆Sprint: Sprint 65-Pyjama shark
┆Issue Type: Story

**Comment by junjun-zhang** [comment]
Thanks @denis-yuen. The ARGO bioinformatics workflows have been using https://quay.io/organization/icgc-argo (quay.io) for docker registry, we plan to switch to GitHub Container Registry after it becomes production. However the work of the migration has just begun, basically, we will push docker images to both quay.io and ghcr.io for the time being.

**Comment by jonrkarr** [comment]
We have a collection of Docker images for simulating biomodels (biosimulators.org) in GHCR which we'd also like to further share through Dockstore. We've embraced GHCR for the same reasons as @denis-yuen. We'd love to see Dockstore support GHRCR.

**Comment by denis-yuen** [comment]
Note to implementer: will likely need to phase this into two parts
1) Make sure workflows pointing at Docker images on GitHub work properly with features like harvesting checksums, calculating DAG/tools tab
b) Adding support for tools either via the existing tools feature or sync up with #3476

**Comment by kathy-t** [comment]
This ticket implements part 1: support for GitHub Container Registry images in workflows (ensuring features like checksum harvesting and calculating the DAG/tools tab works).

Part 2 is split out to another ticket: #4353

**Comment by garyluu** [comment]
Added a hosted WDL with ghcr.io/kathy-t/dockstore-tool-helloworld:1 and such in it. DAG and Tools tab looks fine
