### ISSUE TITLE
Reset search filters test

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4008]
**Describe the bug**
https://dashboard.cypress.io/projects/1ya4vj/runs/16434/test-results/5fbda9f3-82eb-473d-9250-754bbcd5674c/video appears to indicate that the reset filters test isn't working as intended https://github.com/dockstore/dockstore-ui2/blob/develop/cypress/integration/manualTests/search.ts#L25-L30   . It is likely a timing issue. The assertion should ensure that the filters are cleared before moving on to the next test .  There is a possibility that the reset filters button is legit broken sometimes, that would be more tricky to fix.

**To Reproduce**
1. Run that manualTests/search.ts a million times on dev
2. See error

**Expected behavior**
The reset filters test should 100% ensure that the filters are reset before continuing with the next test.
The reset filters test should not fail sometimes.

**Additional context**
 - host location: [dev.dockstore.net]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1691)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1691
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
How often is this occurring on circle?

**Comment by garyluu** [comment]
It's a manualTest so it's ran once per day. It's only happened once so far but in any case, the current assertion doesn't really do anything.
