### ISSUE TITLE
Notification for build info button

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4009]
Good suggestion from @kcullion the build info button should display a notification (toast, snackbar, etc,) that the info was successfully copied. 

![](https://files.slack.com/files-pri/T029E087Q-F01LAACCPRN/image.png)
![image (3)](https://user-images.githubusercontent.com/1730679/105530243-84b19a80-5cb5-11eb-939e-1fb2c5d82172.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1692)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1692
┆Sprint: Sprint 55- Dusky shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
We should do this for all buttons that copy to the clipboard (or maybe this is the only one that's not doing it).

**Comment by kcullion** [comment]
yeah that would help. Just something simple like https://styleguide.pivotal.io/components/copy-to-clipboard/

**Comment by kcullion** [comment]
@coverbeck I did notice the copy button in the workflow entity page, it does have the "copied" feedback...fyi
<img width="313" alt="Screen Shot 2021-01-22 at 2 08 41 PM" src="https://user-images.githubusercontent.com/18424138/105534375-68186100-5cbb-11eb-86ca-1843a21b3188.png">

**Comment by coverbeck** [comment]
I think you **could** have an [attribute directive](https://angular.io/guide/attribute-directives). And/or a service... It's not a lot of code, but it would be nice to avoid the duplicating [this](https://github.com/dockstore/dockstore-ui2/blob/4318e60c684339ed5a640697a602c4d3ad0dc026/src/app/footer/footer.component.ts#L65) 20 times.

@garyluu might have a strong feeling on the best way.
