### ISSUE TITLE
Galaxy plugin creates 500s on certain Galaxy workflows on the tools tab

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4016]
**Describe the bug**
On some galaxy workflows, a 500 is encountered on the tools tab

**To Reproduce**
Use https://github.com/afgane/galaxy-workflows

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1695)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1695
┆Sprint: Sprint 57- Frilled shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Core of the problem may be that the main "version" seems messed up. But the main version and the 1.0.0 branch have the same contents on GitHub -- seems like there was an error reading from the branch but not the tag.

https://dockstore.org/workflows/github.com/afgane/galaxy-workflows:main?tab=files

![Screen Shot 2021-01-27 at 11 57 59 AM](https://user-images.githubusercontent.com/1049340/106046294-eb103180-6096-11eb-9555-75e8cb7c8ab9.png)

**Comment by coverbeck** [comment]
More background on the history of this workflow:

```
As a bit more background, I tried registering the workflow via github apps but after multiple attempts, nothing happened so I went down the path of quickly register remote wf , and then finally register custom remote wf, which I think ultimately included it under the my workflows list. Perhaps that runaround caused some issue on the import backend…```
