### ISSUE TITLE
Incorrect source code link on workflow, leads to 2 workflows from 1 repository

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4018]
**Describe the bug**
The workflow https://staging.dockstore.org/workflows/github.com/Richard-Hansen/dockstore-whalesay:master?tab=info is linked to a non existing repository. If you click the repository link, you get 'correctly' redirected to https://github.com/Richard-Hansen/dockstore-whalesay2/tree/master. This workflow can be refreshed as normal.

I registered a second workflow using the same repository, https://staging.dockstore.org/my-workflows/github.com/Richard-Hansen/dockstore-whalesay2, which is has the correct source code URL, marked as a DOCKSTORE_YML workflow, and also receives updates from the GitHub Apps feature.

I'm not sure how https://staging.dockstore.org/my-workflows/github.com/Richard-Hansen/dockstore-whalesay ended up with the wrong source code url in the first place (maybe I deleted a repository? Don't remember)... When viewing which repositories I have linked to Dockstore workflows, there are only 2, but I have 3 unique registered workflows from GitHub.

I expect the redirecting is related to the original repository: https://github.com/DockstoreTestUser/dockstore-whalesay, which I forked.

**To Reproduce**
May be tricky, I'm not sure how to get the incorrect source code link in the first place.
1. Go to https://staging.dockstore.org/my-workflows/github.com/Richard-Hansen/dockstore-whalesay
2. Take note of the source code link
3. Click the source code link, verify you are redirected to a slightly different page on GitHub
4. See the repository on GitHub as a .dockstore.yml file, but the Dockstore workflow is not marked as DOCKSTORE_YML

**Expected behavior**
This is more of an issue related to how the incorrect source code url got there in the first place, should have a way to verify the intended repository still exists, or is an exact match perhaps?

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.1) - 1.10.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.1) - 2.7.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.1) - 1.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1697)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1697
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
Confirmed the entry is in the FAQ
