### ISSUE TITLE
basic-enduser smoke test failing

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4019]
**Describe the bug**
A smoke test for the Dockstore UI is failing in cypress/integration/manualTests/basic-enduser.ts. 

1. Unable to find the 'Popular keywords' selector within the tag cloud
2. The second issue is already a ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-2071?focusedCommentId=32911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-32911

Looks like the smoke test just needs to be updated.

**To Reproduce**
1. run the test-staging-no-auth
2. See failing tests

**Expected behavior**
Smoke tests should be updated

**Screenshots**
<img width="480" alt="Screen Shot 2021-01-28 at 12 28 29 PM" src="https://user-images.githubusercontent.com/36607471/106175635-596ef580-6164-11eb-8445-f7b02ecd3d5e.png">

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.1) - 1.10.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.1) - 2.7.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.1) - 1.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1698)
┆Issue Number: DOCK-1698
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
Which branch are you running the smoke tests from?

**Comment by Richard-Hansen** [comment]
> Which branch are you running the smoke tests from?

Pulled the latest develop branch

**Comment by Richard-Hansen** [comment]
I was running wrong smoke testing version, everything looks good (The linked ticket is still an issue).
