### ISSUE TITLE
Launch with nextflow tower

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4040]
The nextflow core site has a launch with mechanism that looks an awful lot like what we ended up with for WDL/CWL launch-with. 
Let's see if we can use it!
Example at https://nf-co.re/launch?pipeline=mag&release=1.2.0 (pick ampliseq, pick a few parameters)

Note that the browser goes to https://tower.nf/launch?pipeline=https:%2F%2Fgithub.com%2Fnf-core%2Fampliseq&revision=1.2.0&paramsText=%7B%0D%0A%20%20%20%20%22FW_primer%22:%20%22foo%22,%0D%0A%20%20%20%20%22RV_primer%22:%20%22foo%22%0D%0A%7D&resume=false
However https://tower.nf/launch?pipeline=https:%2F%2Fgithub.com%2Fnf-core%2Fampliseq&revision=1.2.0 also works in lieu of us implementing #4039 

This could be a nice way of filling this feature gap without much development

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1708)
┆Issue Number: DOCK-1708
┆Sprint: Sprint 55- Dusky shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Isn't NextFlow Tower going to be like Galaxy, where people can spin up their own? If so, we may eventually need to bring in the DNAstack/Galaxy UI where users can specify an endpoint.

**Comment by denis-yuen** [comment]
```
The community version of Tower is available from this repository. It can be deployed in a user's own environment and has features for single users to monitor their Nextflow pipelines, deployed anywhere.

The fully-featured enterprise version of Tower is available from Seqera Labs. It can be deployed in a customers own on-premise or cloud environment and includes advanced workflow management, resource optimization and enterprise-grade support. 
```
Yup

**Comment by pditommaso** [comment]
Hello, that would be welcome! Just one note, the [Tower community distribution](https://github.com/seqeralabs/nf-tower) linked above currently does not include the launch feature.

**Comment by denis-yuen** [comment]
@pditommaso  Thanks for the heads-up!
So to clarify, https://tower.nf/ is running the Tower enterprise distribution. https://github.com/seqeralabs/nf-tower contains the source code for the community edition but not the enterprise edition. If this is correct, we'll note this in our documentation for launch with.

Out of curiosity/keeping up, is there a page that lists the differences between the two versions?

**Comment by pditommaso** [comment]
Yes, exactly.

> Out of curiosity/keeping up, is there a page that lists the differences between the two versions?

We should have a new web site in a few days, with a comparing matrix. I'll link it here. But in a nutshell, the community just monitoring. The enterprise version adds pipelines launch and multi-cloud supports.
