### ISSUE TITLE
Use batches to send search data to elastic search

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4042]
The request size limit for AWS elastic search is 10 MiB
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html

So as one of the stepping stones to moving to it, send data over in 10MiB batches rather than in one big bulk batch that we currently use. There may be stumbling blocks and/or may not be straightforward https://forums.aws.amazon.com/message.jspa?messageID=759682

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1710)
┆Issue Number: DOCK-1710
┆Sprint: Sprint 55- Dusky shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Overlaps with #2352 -- fixing this will fix that and vice-versa.
