### ISSUE TITLE
Add 'how to cite Dockstore' to UI

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#4045]
**Is your feature request related to a problem? Please describe.**
To make it easier for others to reference Dockstore in publications we should make it easy to find this information on the main site UI.

**Describe the solution you'd like**
Add 'How to cite Dockstore' information on UI, either as something on the homepage (findable regardless of logged-in or not) or possibly as a footnote link that leads to either the [github citation link](https://github.com/dockstore/dockstore/blob/develop/CITATION) or the [docs page with all publications](https://docs.dockstore.org/en/develop/posters-and-talks.html). For the latter option, the main citation should be identified at the top of the page as the main reference to use.  

Alternatively add the full citation information to the [Dockstore about page](https://docs.dockstore.org/en/develop/dockstore-introduction.html) and link to it from UI. Redundancy of where we display this is probably not a bad idea as long as each is correct.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1724)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1724
┆Sprint: Sprint 61- Leopard shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Note for implementer, text is available from https://github.com/dockstore/dockstore/blob/develop/CITATION
Bonus points for pulling that in during build time or some similar automatic process

**Comment by denis-yuen** [comment]
Can take inspiration from https://gatk.broadinstitute.org/hc/en-us/articles/360035530852-How-should-I-cite-GATK-in-my-own-publications- 
DOI for second paper is 10.1093/nar/gkab346

**Comment by coverbeck** [comment]
Confirmed that citation is on about page on dev

[Webservice](https://github.com/dockstore/dockstore/commits/52333dd) - 52333dd

[UI](https://github.com/dockstore/dockstore-ui2/commits/030d6b4e) - 2.7.3-105-g030d6b4e

[Compose Setup](https://github.com/dockstore/compose_setup/commits/80a6669) - 80a6669

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d1eca79) - 1.10-80-gd1eca79
