### ISSUE TITLE
Update organization about info

### ISSUE THREAD

**Issue by wendidy** [dockstore/dockstore#4047]
**Is your feature request related to a problem? Please describe.**
Some "About Organization" descriptions are outdated, e.g. https://dockstore.org/organizations/bdcatalyst. The things that need to be changed, please refer to mock-up.

**Describe the solution you'd like**
The mock-up only includes one or two organizations, so to fix this issue entirely, will need to talk with Kim or Denis.

**Describe alternatives you've considered**
N/A

**Additional context**
Refer to mock-up

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1712)
┆Issue Number: DOCK-1712
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Adding a curator label, I guess this would be a job for that curator position. 
Undecided whether these should be SEAB or DOCK, FYI @melainalegaspi @coverbeck

**Comment by denis-yuen** [comment]
I think Ash can take a look and see if the mock-up changes are intentional and/or are an improvement 
If they aren't, then this can just be closed
