### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by wendidy** [dockstore/dockstore#4051]
**Describe the bug**
1. Texts on the right hand side should over flow when screen is small, but they exceed the sidebar
 ![image](https://user-images.githubusercontent.com/57231021/108408865-91ada500-71f3-11eb-90b8-9cef829e6fc6.png)
2.
 ![image](https://user-images.githubusercontent.com/57231021/108898292-095d4480-75e5-11eb-86fe-917f4d741b91.png)
3. This is likely not a bug, but thought styling could be done better
![image](https://user-images.githubusercontent.com/57231021/108913065-7aa5f300-75f7-11eb-92fa-4a6e7e94eb84.png)
4. 
![image](https://user-images.githubusercontent.com/57231021/108917557-ec813b00-75fd-11eb-9a55-00d3370f14a7.png)

**To Reproduce**
1. e.g.https://dockstore.org/workflows/github.com/broadinstitute/gatk/MitochondriaPipeline:master?tab=info
2. In staging https://dev.dockstore.net/search?descriptorType=gxformat2&searchMode=files Galaxy language label
3. This issue was found on localhost with database, therefore unable to pin point other workflows with this button, but here is the URL for localhost: /workflows/github.com/iwc-workflows/sars-cov-2-variant-calling/COVID-19%20variation%20analysis%20on%20Illumina%20metagenomic%20data:master?tab=info
4. Resize screen: https://dockstore.org/workflows/github.com/broadinstitute/gatk/MitochondriaPipeline:master?tab=info

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
 - UI version: 2.7.3
 - Webservice version: [e.g. 1.8.0]
 - host location: dockstore.org(prod)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1714)
┆Issue Number: DOCK-1714
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Is this a regression? 
https://github.com/dockstore/dockstore/issues/3451
Please fill in the additional context, is this staging or prod?

**Comment by garyluu** [comment]
The screenshot in this issue has a version that is essentially one long string like: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" which cannot be word-break or w/e
The screenshot in the linked issue shows a very long version name that can be word-break or w/e

Solution is to probably copy whatever styling that the versions table uses and put it in the sidebar

**Comment by coverbeck** [comment]
Noticed and created #4106 in verifying this.

A little hard to be sure on everything, since some was written up with local data, but tried to reproduce using browser tools and looks good.

[Webservice](https://github.com/dockstore/dockstore/commits/737a7de) - 737a7de

[UI](https://github.com/dockstore/dockstore-ui2/commits/27bfbed2) - 2.7.3-50-g27bfbed2

[Compose Setup](https://github.com/dockstore/compose_setup/commits/f24bc92) - f24bc92

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/cda0452) - 1.10-36-gcda0452
