### ISSUE TITLE
Searching for a phrase using Advanced Search doesn't work

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#4059]
** Description**
Searching for a phrase with multiple words does not work in Dockstore Search.

**To Reproduce**
Click on Search at top of Dockstore page
Click on Open Advanced Search
Enter 'version 1.0' with or without quotes in 'The exact word or phrase' edit box
Click on Advanced Search (also Return does not work for this dialog)
The Share text says "Search: contains exactly "version, 1.0" which seems to indicate it is searching for two words 'version' and '1.0'
The workflows found have either 'version' or '1.0' in them I think.

**Expected behavior**
Only workflows with files that contain the phrase 'version 1.0' should be found.

**Screenshots**
![Screen Shot 2021-02-24 at 9 36 38 AM](https://user-images.githubusercontent.com/3650921/109048744-47fa0a00-768c-11eb-81d2-405d29cd87ac.png)
![Screen Shot 2021-02-24 at 9 33 39 AM](https://user-images.githubusercontent.com/3650921/109048748-492b3700-768c-11eb-94b1-ec32148c1c2d.png)
I

**Desktop (please complete the following information):**
 - OS: iOS Big Sur 11.2.1 (20D74)
 - Browser Chrome
 - Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**
 - UI version: UI - 1ffd9819 or UI - 2.7.3
 - Webservice version: API - ca2236f or API - 1.10.1 
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1718)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1718
┆sprint: 92- T
┆taskType: Story

**Comment by denis-yuen** [comment]
this seems more broken now in that it doesn't seem to return anything no matter what I put in exact word or phrase

**Comment by denis-yuen** [comment]
maybe the whole advanced search is just broken
