### ISSUE TITLE
Documentation missing 1.10 in News and Events

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4064]
1. Go to https://docs.dockstore.org/en/develop/index.html
2. Scroll down in the left sidebar to News and Events
3. See no 1.10

Should this part of our release checklist?

![Screen Shot 2021-02-25 at 1 43 45 PM](https://user-images.githubusercontent.com/1049340/109223508-8288a300-776f-11eb-965c-17233e156c78.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1719)
┆Issue Number: DOCK-1719
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Alternatively, maybe we can delete the changelog ones and redirect to https://github.com/dockstore/dockstore/releases
This doesn't seem useful
