### ISSUE TITLE
Possible variant of consecutive releases issue

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4071]
See https://discuss.dockstore.org/t/github-app-missed-tag-event/4186/2 for context

Looks like a quick release of main and tag 0.1 in pretty much the same minute might cause an issue. 
Relevant log to search for is 

```
ERROR [2021-03-01 20:19:43,021] io.dockstore.webservice.resources.AbstractWorkflowResource: User iwc-workflows-bot: Unhandled error while handling push event for repository iwc-workflows/sars-cov-2-variation-reporting and reference refs/tags/v0.1→org.hibernate.exception.ConstraintViolationException: could not execute statement
```

A redelivery worked, so there might be a race condition. 
Webhook delivery is `506147e2-7acb-11eb-93bf-be7974f4eff4` if investigator wants to take a look

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1723)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1723
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Could be variant on https://github.com/dockstore/dockstore/issues/3689

**Comment by coverbeck** [comment]
#3770 might be a partial solution to this.

**Comment by coverbeck** [comment]
I wonder if we're running into [this](https://zaccharles.medium.com/lambda-concurrency-limits-and-sqs-triggers-dont-mix-well-sometimes-eb23d90122e0).

**Comment by denis-yuen** [comment]
FWIW, at least not in the last 4 weeks
