### ISSUE TITLE
New/update endpoint to get the category tags in organizations workflows & tools

### ISSUE THREAD

**Issue by wendidy** [dockstore/dockstore#4075]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
1. The languages and other additional tags need to be returned and displayed on the UI
2. Number of stars also needs to be returned
Current UI: https://dev.dockstore.net/organizations/bdcatalyst/collections/GWAS
Mock up: https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/60073f22c824b7b8dfde055c

**Describe alternatives you've considered**
N/A

**Additional context**
Similar issues: https://github.com/dockstore/dockstore/issues/4074 https://github.com/dockstore/dockstore/issues/4038
e.g. 
![image](https://user-images.githubusercontent.com/57231021/109821315-da0d8f80-7c03-11eb-990c-2fa3abd227e9.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1725)
┆Issue Number: DOCK-1725
┆Sprint: Sprint 57- Frilled shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
One thought is that we could one single endpoint, off `/metadata`, that returns all the information needed. May not be very very RESTful, but it seems like it would work and we could make it very fast with the right queries.

**Comment by wendidy** [comment]
Closing this since it's a duplicate of https://github.com/dockstore/dockstore/issues/4053 and https://github.com/dockstore/dockstore/issues/4052.
To address Charles' comment, we had a private chat and decided modifying the endpoints are the easiest, and the best for performance.
