### ISSUE TITLE
WDL 1.1 early support

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4077]
**Is your feature request related to a problem? Please describe.**

Dockstore should have some support for Wdl 1.1 workflows.

Full support is covered by #4021, and is dependent on Cromwell/WOM supporting WDL 1.1.

Before Cromwell supports 1.1, we would ideally have a "use at your own risk" support for WDL 1.1. A message pops up warning the user, complete validation may not be possible, etc. But we don't want to block anybody from putting a 1.1 WDL workflow in Dockstore, even before we can fully support it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1728)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1728
┆Sprint: Sprint 57- Frilled shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Should also display this meme in the DAG tab
https://knowyourmeme.com/photos/200420-neil-degrasse-tyson-reaction

**Comment by coverbeck** [comment]
Working on dev. I was able to push a WDL 1.1 and see the warning.

[Webservice](https://github.com/dockstore/dockstore/commits/580a271) - 580a271

[UI](https://github.com/dockstore/dockstore-ui2/commits/d167ef76) - 2.7.3-72-gd167ef76

[Compose Setup](https://github.com/dockstore/compose_setup/commits/36c8ddc) - 36c8ddc

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/da5d5ab) - 1.10-56-gda5d5ab
