### ISSUE TITLE
Better handling for many workflows in a .dockstore.yml

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4080]
**Is your feature request related to a problem? Please describe.**
If you have multiple workflows in a .dockstore.yml, the web service's GitHub release endpoint loads all the workflows into memory. This includes a lot of data, we're seeing 261MB responses for the GATK repo, which has ~15 workflows in it.

Needs investigation as to why it's consuming so much memory -- is it just versions, or does it also include source files? Source files should be lazy, but maybe something is fetching them.

**Describe the solution you'd like**
Brainstorm:

1. Improve the efficiency
    *  I think we load all versions so we can look for a matching one. Can we search for an existing version directly with HQL? Would we be able to add a new version in Hibernate without having all the existing versions?
    * Are we loading the sourcefiles? If so, why, and can it be avoided.
2. Process each workflow in its own transaction
    * Programatically start and finish a transaction for each workflow in the .dockstore.yml
    * This way each workflow can be garbage collected right way, instead of waiting for all 15 workflows to be processed
    * But how do you handle some of the transactions passing and some failing, especially in notifying the lambda.
3. The lambda fetches the .dockstore.yml, parses it, and invokes an endpoint for each workflow. I don't really like this, but:
    * On the minus side, puts .dockstore.yml logic in the lambda.
    * Lambda will also need a token.
    * On the plus side, saves a lot of noise hitting the web service, e.g., all the events we get for repos that don't even have a .dockstore.yml

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1730)
┆Issue Number: DOCK-1730
┆Sprint: Sprint 58- Goblin shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
> I think we load all versions so we can look for a matching one. Can we search for an existing version directly with HQL? Would we be able to add a new version in Hibernate without having the existing version?

Important and I kinda assumed this was happening (but can easily see how this was missed/regressed)

**Comment by NatalieEO** [comment]
> * Are we loading the sourcefiles? If so, why, and can it be avoided.

We do load the sourcefiles because they need to get updated to match what's on github

**Comment by coverbeck** [comment]
> We do load the sourcefiles because they need to get updated to match what's on github

But in theory only for the version that has been updated/added? I'm trying to understand where 260MB comes from, and was guessing all sourcefiles from all versions are being loaded, which wouldn't seem necessary.

**Comment by GFJHogue** [comment]
Review: verified that many workflows in .dockstore.yml still works as expected with changes in dev.
