### ISSUE TITLE
Documentation build should check for discourse topic

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4081]
**Is your feature request related to a problem? Please describe.**
Several pages in the doc do not have a Discourse topic.

**Describe the solution you'd like**
A build step should flag them and GitHub PRs should be configured to fail.

The build check would need to exclude some files from the check, e.g., the 1.7.0 news and the index pages don't need topics. But any new pages added should have a topic unless explicitly excluded.

```
rg discourse --type rst --files-without-match
index.rst
news.rst
changelog.rst
advanced-topics/verification.rst
advanced-topics/docker-alternatives.rst
advanced-topics/checksum-support.rst
getting-started/building-on-quayio.rst
getting-started/releasing-on-github.rst
getting-started/getting-started-with-galaxy.rst
getting-started/adding-a-test-parameter-file.rst
news/2019-09-26-Dockstore-1.7.0.rst
news/2020-01-27-Dockstore-1.8.0.rst
advanced-topics/best-practices/best-practices-secure-fair-workflows.rst
advanced-topics/best-practices/sample-parameter-files-intro.rst
advanced-topics/best-practices/authorship-metadata-outro.rst
advanced-topics/best-practices/authorship-metadata-intro.rst
getting-started/github-apps/github-apps-troubleshooting-tips.rst
getting-started/github-apps/github-apps-landing-page.rst
getting-started/github-apps/migrating-workflows-to-github-apps.rst
advanced-topics/best-practices/best-practices-dockstore.rst
assets/templates/template.rst
advanced-topics/best-practices/best-practices-intro.rst
news/2020-07-06-Dockstore-1.9.0.rst
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1731)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10820">image-20220824-161453.png</a>
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1731
┆sprint: 89
┆taskType: Story

**Comment by denis-yuen** [comment]
I forget the logic here, why do we not let them auto-create? 
I remember why auto-creation sucks for Dockstore workflows, but I forget why for documentation

**Comment by coverbeck** [comment]
>  forget the logic here, why do we not let them auto-create?
> I remember why auto-creation sucks for Dockstore workflows, but I forget why for documentation

Hmm, I don't know, I was just following the instructions. Is it because you don't have to be authorized to view the docs?

**Comment by coverbeck** [comment]
We're using this plugin: https://github.com/pdavide/sphinxcontrib-discourse; instructions require an existing topic.
