### ISSUE TITLE
Remove "Preview" label from Galaxy

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4107]
**Is your feature request related to a problem? Please describe.**

I feel like we've supported it long enough; Galaxy is importing/searching Dockstore from within Galaxy. Seems like the support is mature enough...

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1740)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1740
┆Sprint: Sprint 61- Leopard shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Yeah, I feel  #3764  gates this, but hopefully it will be in 1.11
