### ISSUE TITLE
Build info link at bottom of main Dockstore page doesn't copy information

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#4127]
**Describe the bug**
Build info link at bottom of main Dockstore page doesn't copy information

**To Reproduce**
1. Go to main dockstore.org page
2. Click on link 'Build info' at bottom of page
3. Paste clipboard somplace
4. No build information has been saved in clipboard

**Expected behavior**
Build information should be stored in clipboard

**Screenshots**
![Screen Shot 2021-03-19 at 11 10 47 AM](https://user-images.githubusercontent.com/3650921/111830030-aa6cb180-88aa-11eb-9277-265209edb605.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.2.3 (20D91)
 - Browser chrome
 - Version Version 89.0.4389.90 (Official Build) (x86_64)

**Additional context**
 - UI version: 12.7.4
 - Webservice version: 1.10.2
 - host location: production

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1743)
┆Issue Number: DOCK-1743
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
I find I usually just need to click it more than once

**Comment by garyluu** [comment]
Have been using this for quite a while

[Webservice](https://github.com/dockstore/dockstore/commits/f894cfb) - f894cfb

[UI](https://github.com/dockstore/dockstore-ui2/commits/ead92717) - 2.8.4-127-gead92717

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/91fc396) - 1.11.3-119-g91fc396

galaxyParsingLambdaVersion: 0.0.6
