### ISSUE TITLE
Broken TOS links on the swagger/openapi pages

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4146]
**Describe the bug**
The TOS links are `about:blank` on the api page https://dockstore.org/api/static/swagger-ui/index.html#. The link is also nonexistant on the swagger side of the API.

**To Reproduce**
1. Go to https://dockstore.org/api/static/swagger-ui/index.html#
2. Click on the terms of service link.

**Expected behavior**
Should have a link to the most recent TOS, much like the footer in the UI pages.

**Desktop (please complete the following information):**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.2) - 1.10.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.4) - 2.7.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.10.1) - 1.10.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1749)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1749
┆sprint: Seabright Sprint 78- Flotsam
┆taskType: Story

**Comment by denis-yuen** [comment]
Well
https://github.com/dockstore/dockstore/blob/dockstore-1.10.0-alpha.2/dockstore-webservice/src/main/resources/swagger.yaml#L10
https://github.com/dockstore/dockstore/blob/dockstore-1.10.0-alpha.2/dockstore-webservice/src/main/resources/openapi3/openapi.yaml#L1794
