### ISSUE TITLE
SupportedLanguages not working as expected on CloudInstances

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4163]
**Describe the bug**
1. Cannot create a CloudInstance with non-empty supported languages
2. After fixing previous item locally, fetching a CloudInstance does not return any languages

**To Reproduce**
1. Go to https://dev.dockstore.net/api/static/swagger-ui/index.html#/Cloud%20Instances/postCloudInstance
2. In Request Body, click on Schema and expand
3. Notice how there are fields for language

This is because [Language](https://github.com/dockstore/dockstore/blob/9c48baeed4d037da4d5d66688e77a32cb49e5064/dockstore-webservice/src/main/java/io/dockstore/webservice/core/Language.java#L16) has no getters.

Fixed that locally, successfully posted a supported language.

Did a GET, and the supported language did not come back.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/36dd73d) - 36dd73d

[UI](https://github.com/dockstore/dockstore-ui2/commits/48a245cc) - 2.7.3-53-g48a245cc

[Compose Setup](https://github.com/dockstore/compose_setup/commits/a682a69) - a682a69

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d3024ad) - 1.10-48-gd3024ad

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1753)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1753
┆Sprint: Sprint 61- Leopard shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Also, it's unfortunate that for Galaxy you need to specify the language as "GXFORMAT2"; it should be "GALAXY". But I know we have GXFORMAT2 baked into our code in many places, so it might be tricky to deal with.

**Comment by garyluu** [comment]
> Also, it's unfortunate that for Galaxy you need to specify the language as "GXFORMAT2"; it should be "GALAXY". But I know we have GXFORMAT2 baked into our code in many places, so it might be tricky to deal with.

Not really. As it stands right now, it's supposed to be the languages specified in https://github.com/dockstore/dockstore/blob/develop/dockstore-common/src/main/java/io/dockstore/common/DescriptorLanguage.java  .  As long as people didn't make up new languages other places in the codebase (ex. the infamous "cwl", "wdl", etc). It should be pretty easy to rename any language.

**Comment by garyluu** [comment]
For implementers (once the frontend mockup is more finalized), it can be decided whether to make the SupportedLanguages eager loaded or not. Getter (and setter) should be added too.

**Comment by NatalieEO** [comment]
Didn't realize it was already closed...was able to make a cloud instance with the supported language and see it there when I do a GET
