### ISSUE TITLE
Better Error messages when exporting to ORCID

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#4180]
**Is your feature request related to a problem? Please describe.**
I was testing out the export to orcid feature on dev and came across `Could not export to ORCID: Not Found` a lot. Seems like the orcid sandbox is really flakey and it eventually went completely down later (endpoint started working later once the sandbox was back). The message is confusing and makes it seem like the id of the Dockstore entry/version can't be found.

**Describe the solution you'd like**
The message should indicate it's a problem with orcid and not Dockstore.

**Additional context**
Hopefully it is just their sandbox that is really flakey, so this might only be annoying for developers.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1764)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1764
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by denis-yuen** [comment]
Could look at new message for review

**Comment by denis-yuen** [comment]
Tests use hoverfly

**Comment by garyluu** [comment]
Not sure how to reproduce barring spamming sandbox orcid until it goes down. Based on the error message and assuming e.getMeessage() cannot produce "Not Found". It seems:

https://github.com/dockstore/dockstore/blob/82f1dd03440a27610994affd517aa42e9c15981e/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EntryResource.java#L288

https://github.com/dockstore/dockstore/blob/82f1dd03440a27610994affd517aa42e9c15981e/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EntryResource.java#L303

are the only two possible sources for that message.

However, those two have been replaced with `throw new CustomWebApplicationException("Could not export to ORCID.\n" + response.body(), response.statusCode());`

which results in a fairly detailed message like:

![image](https://user-images.githubusercontent.com/24548904/152572263-0dab0a5c-ca70-4a83-8d42-08e8c51644db.png)

**Comment by garyluu** [comment]
seems to be a different issue. this issue is for better error message. that issue (with the infinite progress bar) implies no error message is displayed because the frontend didn't handle it

**Comment by denis-yuen** [comment]
Sounds hard to reproduce and more likely to affect developers (sandbox) than users. Going to close, please re-open if seen again
