### ISSUE TITLE
Obtain the "Category" tag among all the labels of an entry

### ISSUE THREAD

**Issue by wendidy** [dockstore/dockstore#4184]
**Is your feature request related to a problem? Please describe.**
Currently, the labels of an entry look like this: 
![image](https://user-images.githubusercontent.com/57231021/114580873-3c1ed300-9c4d-11eb-817b-34dc80298bb5.png)
![image](https://user-images.githubusercontent.com/57231021/114581691-ed256d80-9c4d-11eb-9a67-23e116587670.png)

We want only the categories of this entry to be displayed on the entry index inside collections([mock](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/60073cb04ab9d01346312637)):
![image](https://user-images.githubusercontent.com/57231021/114580974-52c52a00-9c4d-11eb-900e-0ca898b29457.png)

**Describe the solution you'd like**
We first need to decide what categories are and then go from there, suggest running it through with Kim, Denis and Charles first. 
Might need to add a new column inside the `Entry` class in the web-service to hold onto the categories.

**Describe alternatives you've considered**
Leave it as it is

**Additional context**
Previously, I returned all the entry's labels([PR](https://github.com/dockstore/dockstore/pull/4138)), if it's needed, please revert these changes. Anyways please still refer to this optimization ticket when the new solution is being applied: https://github.com/dockstore/dockstore/issues/4152

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1765)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1765
┆sprint: Sprint 72-Yellowspotted Catsha
┆taskType: Story

**Comment by coverbeck** [comment]
This could be something that curators set, so that there is consistency across Dockstore. Not sold on this, just a thought.

**Comment by denis-yuen** [comment]
@NatalieEO this needs a back-end specification, but Kim's mock-ups have much of the UI so you can skip that

**Comment by garyluu** [comment]
I see it:
![image](https://user-images.githubusercontent.com/24548904/145634672-261ae8f0-8f6c-4211-9c22-473b02d96428.png)
