### ISSUE TITLE
Broken restub button on dev

### ISSUE THREAD

**Issue by wendidy** [dockstore/dockstore#4193]
**Describe the bug**
When clicking on restub, an error shows up `HttpErrorResponse {headers: HttpHeaders, status: 400, statusText: "Bad Request", url: "http://localhost:4200/api/workflows/16199/restub"...`

**To Reproduce**
1. Go to a workflow in my workflows(if you don't have one please create one)
2. Click on "restub"
3. See error in console

**Expected behavior**
The error should be gone

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
 - UI version: https://github.com/dockstore/dockstore-ui2/commits/91cb3b07
 - Webservice version: https://github.com/dockstore/dockstore/commits/6265e21
 - host location: localhost & dev. No error on staging

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1769)
┆Issue Number: DOCK-1769
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Confirmed, no restub buton for checker workflows
