### ISSUE TITLE
reduce number of function calls in ngOnChanges

### ISSUE THREAD

**Issue by wendidy** [dockstore/dockstore#4194]
**Is your feature request related to a problem? Please describe.**
A new function `changeDescriptor` is added in this PR https://github.com/dockstore/dockstore-ui2/pull/1203, now when you `console.log`, `reactToDescriptor ` gets called 2 times at the beginning, and `changeDescriptor` gets called 4 times. 

**Describe the solution you'd like**
Try to reduce the number of calls

**Describe alternatives you've considered**
Leave it as it is

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1770)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1770
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by garyluu** [comment]
```
params -> changeDescriptor() -> this.path -> input()
                             -> this._selectedVersion.name -> input()
                             -> this.currentDescriptor -> filterDescriptors() -> this.descriptors -> descriptorLanguageService.filteredDescriptorLanguages$
                                                                              -> this._selectedVersion -> input()
                                                                              -> this.versionsFileTypes -> input()
```
params is a string that's updated using the changeDescriptor() function. The changeDescriptor() function depends on this.path, and this_selectVersion, and this.currentDescriptor. path and selectVersion are input()s. This.currentDescriptor is updated using the filterDescriptors function which depends on this.descriptors, this._selectVersion, this.versionsFileTypes. This descriptors depends on filteredDescriptorLanguages$ from the state.

```
filteredDescriptorLanguages$: [] -> [<the four of them>]
ngOnChanges(): everything -> just versionsFileTypes
```

changeDescriptor() gets called when ngOnChanges() is triggered or when filteredDescriptorLanguages$ changes so there's 4 calls in total when ideally it should be one or two.
