### ISSUE TITLE
Discourse topic missing on at least one workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4202]
**Describe the bug**
A particular workflow has a "No Discourse topic exists for this workflow" warning.

**To Reproduce**
1. Go to https://dockstore.org/workflows/github.com/theiagen/public_health_viral_genomics/Titan_ClearLabs:v1.0?tab=info
2. See a warning at the bottom of the main content.

**Expected behavior**
There should be a Discourse topic

**Screenshots**
![Screen Shot 2021-04-19 at 2 37 32 PM](https://user-images.githubusercontent.com/1049340/115306683-0a11e300-a11d-11eb-9477-557f6519391c.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.2) - 1.10.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.4) - 2.7.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.10.1) - 1.10.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1773)
┆Fix Versions: Dockstore 1.13.x
┆Issue Number: DOCK-1773
┆Sprint: 102 - Dutchman, The Flying
┆Issue Type: Story

**Comment by denis-yuen** [comment]
> I recommend deleting old (pre-prefix) topics in the staging and dev categories, and determining a solution (in another ticket) which does not allow users to create separate entries with names which differ only by capitalization and/or punctuation.

:+1:
