### ISSUE TITLE
Register tool with invalid git url

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4221]
**Describe the bug**
A user should not be able to register a tool when the Git repository does not exist

**To Reproduce**
1. See https://github.com/dockstore/dockstore/pull/4218/commits/0403cddb6bb94197e6a68869ba473dfd9c67dd93
2. Revert that or change it to any bitbucket repository that doesn't exist
3. Run io.dockstore.client.cli.GeneralIT.testGrabChecksumFromDockerHub(GeneralIT.java:1044)
4. See that the test fails and that the error was only caught while setting version type.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/760f2bb) - 760f2bb

[UI](https://github.com/dockstore/dockstore-ui2/commits/a47dbf39) - 2.7.3-81-ga47dbf39

[Compose Setup](https://github.com/dockstore/compose_setup/commits/80a6669) - 80a6669

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/1ac35c1) - 1.10-64-g1ac35c1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1778)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1778
┆sprint: 94- Vampire Pleco
┆taskType: Story

**Comment by denis-yuen** [comment]
My understanding is this doesn't work for workflows already

**Comment by denis-yuen** [comment]
"doesn't work" as in correctly disallows registering a workflow from a non-existent repo
