### ISSUE TITLE
Can't dismiss TOS warning on iPhone

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4223]
**Describe the bug**
The "X" to dismiss the TOS warning is not visible on my iPhone 7.

Not high priority.

**To Reproduce**
1. Go to dev.dockstore.net on your iPhone (happens in prod too)
2. If logged in, log out
3. See TOS status notification without the "X" and no way to close it

**Expected behavior**
Should be able to dismiss the notification.

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/1049340/116616360-7c3eb080-a8f1-11eb-9f9c-741581f5e7c0.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 14.4.2
 - Browser Safari, Chrome

**Additional context**
 [Webservice](https://github.com/dockstore/dockstore/commits/760f2bb) - 760f2bb

[UI](https://github.com/dockstore/dockstore-ui2/commits/a47dbf39) - 2.7.3-81-ga47dbf39

[Compose Setup](https://github.com/dockstore/compose_setup/commits/80a6669) - 80a6669

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/1ac35c1) - 1.10-64-g1ac35c1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1780)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10653">image-20220224-170847.png</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10652">image-20220224-170925.png</a>
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1780
┆Sprint: 104 - Blue Nile
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Firefox on Android Pixel 2
![Screenshot_20210430-102738](https://user-images.githubusercontent.com/1730679/116709676-e6f9f580-a99e-11eb-9f92-ec141a1d2a77.png)

Chrome on Android Pixel 2
![Screenshot_20210430-102812](https://user-images.githubusercontent.com/1730679/116709746-faa55c00-a99e-11eb-9118-3fe69ca61ce1.png)

**Comment by denis-yuen** [comment]
Might be an amusing one if @KimberleyChong you have access to an iPhone

**Comment by coverbeck** [comment]
As noted in my previous comment, on [qa.dockstore.org](http://qa.dockstore.org/) with my iPhone 7, the text is somewhat truncated, as in Kim’s screenshots, but I am able to dismiss, so I'm going to close.
