### ISSUE TITLE
Some filenames missing path in Nextflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4229]
**Describe the bug**
A particular workflow is showing many instances of a "functions.nf" file. The GitHub repo does have multiple instances of the file, and their contents are identical. But for some reason they are not preceded with the path in the file dropdown.

**To Reproduce**
1. Go to https://dockstore.org/workflows/github.com/nf-core/rnaseq:dev?tab=files
2. Click on the dropdown with the list of files
3. Notice how "functions.nf" appears multiple times (screenshot shows two of them).

**Expected behavior**
The filenames should be preceded with the path.

**Screenshots**
![Screen Shot 2021-05-03 at 11 48 41 AM](https://user-images.githubusercontent.com/1049340/116919243-d39c9380-ac05-11eb-924d-7bc1e727099a.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.2) - 1.10.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.4) - 2.7.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.10.1) - 1.10.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1782)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1782
┆Sprint: Sprint 63- Nurse Shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
FYI was probably meant to link to https://github.com/dockstore/dockstore/issues/1873

**Comment by garyluu** [comment]
What I know:
- we have two paths ("path" and "absolute path")
- path is not unique (it's relative to its own parent)
- absolute path is unique

What I infer:
- we can't use path or else this issue will occurs
- we have to absolute path
- absolute path is too long often times

**Comment by NatalieEO** [comment]
I don't see the file tree anywhere in dev
[Webservice](https://github.com/dockstore/dockstore/commits/26d60e4) - 26d60e4

[UI](https://github.com/dockstore/dockstore-ui2/commits/3b7a7164) - 2.8.0-rc.0-20-g3b7a7164

[Compose Setup](https://github.com/dockstore/compose_setup/commits/7ad0764) - 7ad0764

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/94dee6d) - 1.11.0-18-g94dee6d

**Comment by NatalieEO** [comment]
Never mind, this was only added to .dockstore.yml workflows and I do see the file tree on those workflows
