### ISSUE TITLE
Relinking only changes the token but not the orcid id on the dockstore profile

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#4243]
**Describe the bug**
Relinking only changes the token but not the orcid id on the dockstore profile

Exporting a workflow to ORCID using https://dev.dockstore.net/api/static/swagger-ui/index.html#/entries/exportToORCID fails if Relink ORCID Account is clicked and the original ORCID account is no longer present.

Error message is something like:
`
Could not export to ORCID.
{"response-code":"401","developer-message":"401 Unauthorized: The client application is not authorized for this ORCID record. Full validation error: Access token is for a different record","user-message":"The client application is not authorized.","error-code":"9017","more-info":"https://members.orcid.org/api/resources/troubleshooting"}
`

**To Reproduce**
Create an account on sandbox.orcid.org (you will need to add a mailinator.com email address, e.g. blah@mailinator.com, to verify the account at mailinator.com. 
Link to the sandbox.orcid.org account on your Dockstore Accounts page
Create another account on sandbox.orcid.org
Go to the new ORCID account on sandbox.orcid.org Account page
Click on Remove duplicate record and merge the first sandbox.orcid.org account in the new account

![Screen Shot 2021-05-12 at 1 12 30 PM](https://user-images.githubusercontent.com/3650921/118038282-c4af9280-b323-11eb-9483-89e88ceb52dc.png)

On the Dockstore Accounts page click 'Relink ORCID Account'

Create a DOI for a workflow
Export the workflow to ORCID using https://dev.dockstore.net/api/static/swagger-ui/index.html#/entries/exportToORCID

See error above

**Expected behavior**
A dialog should ask you to login to the new ORCID account

**Screenshots**

**Desktop (please complete the following information):**

* Device: Mac
* OS: Big Sur 11.2.3 (20D91)
* Browser Chrome
* Version Version 89.0.4389.114 (Official Build) (x86_64)

**Additional context**

* UI version: 
* Webservice version: [e.g. 1.8.0]
* host location: dev.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/45e63c0)

* 45e63c0

[UI](https://github.com/dockstore/dockstore-ui2/commits/d412ffc8)

* 2.7.3-92-gd412ffc8

[Compose Setup](https://github.com/dockstore/compose_setup/commits/80a6669)

* 80a6669

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/803c792)

* 1.10-70-g803c792

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1790)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1790
┆sprint: 95- W
┆taskType: Story

**Comment by denis-yuen** [comment]
Probably can live with a FAQ warning about duplicate record merging

**Comment by coverbeck** [comment]
Reading up on it, this is a really extreme case. ORCID [is designed to discourage more than one account for an individual](https://support.orcid.org/hc/en-us/articles/360006971593-Do-you-have-more-than-one-account-). That same page has a proviso for removing a duplicate account though, but I don't think you can't actually "transfer" your data between accounts. In thise Dockstore ends up with a putCode that refers to a record that's been deleted...

I'll add something to the FAQ; just noting this. 

Also, looking at the code, I'm not sure we should be storing the putCode in the first place. It seems like we could get it dynamically. But that's another issue.
