### ISSUE TITLE
Please update code and docs to use Synapse access tokens

### ISSUE THREAD

**Issue by stacey-w-taylor** [dockstore/dockstore#4260]
Sage Bionetworks has improved the security of Synapse by adding the the ability to create and manage scoped access tokens, rather than an API key (the API key feature is being deprecated). 

We request an update to your code and [docs](https://docs.dockstore.org/en/develop/advanced-topics/advanced-features.html?highlight=synapse#synapse) to use Synapse access tokens rather than the Synapse API key. 

Relevant information about the Synapse access tokens can be found [here](https://help.synapse.org/docs/Managing-Your-Account.2055405596.html#ManagingYourAccount-PersonalAccessTokens).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1802)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1802
┆Sprint: Sprint 65-Pyjama shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
Hi @stacey-w-taylor, I'm trying to update our [Synapse plugin](https://github.com/dockstore/synapse-plugin), but I'm having trouble building the project because it's unable to resolve the [synapse java client](https://github.com/dockstore/synapse-plugin/blob/master/pom.xml#L218). Do you have more up-to-date info on where you store jars?

**Comment by brucehoff** [comment]
Hi, @NatalieEO.  Stacey is no longer with our org' but I am an engineer in the Synapse team and would be happy to help.  Here's the entry for your maven `pom.xml` file to pull down the Synapse Java client:

```
	<repositories>
		<repository>
			<id>sagebionetworks-releases-local</id>
			<name>sagebionetworks-releases-local</name>
			<url>https://sagebionetworks.jfrog.io/sagebionetworks/libs-releases-local
			</url>
		</repository>
		<repository>
			<id>sagebionetworks-ext</id>
			<name>sagebionetworks-releases-ext</name>
			<url>https://sagebionetworks.jfrog.io/sagebionetworks/ext-releases-local
			</url>
		</repository>
	</repositories>
```

Looking at [your pom](https://github.com/dockstore/synapse-plugin/blob/master/pom.xml#L218) I see you are using 171 of the Synapse Java client. Please upgrade to a newer version.   The latest is 364, i.e. you would put this in your pom:

```
	<dependencies>
		<dependency>
			<groupId>org.sagebionetworks</groupId>
			<artifactId>synapseJavaClient</artifactId>
			<version>364.0</version>
		</dependency>
```

(The version upgrades weekly and can be seen in the lower right corner of [this page](https://www.synapse.org.)

To authenticate using a personal access token:

```
import org.sagebionetworks.client.SynapseClientImpl;
String personalAccessToken = "...";
SynapseClient synapseClient = new SynapseClientImpl();
synapseClient.setAuthEndpoint("https://repo-prod.prod.sagebase.org/auth/v1");
synapseClient.setRepositoryEndpoint("https://repo-prod.prod.sagebase.org/repo/v1");
synapseClient.setFileEndpoint("https://repo-prod.prod.sagebase.org/file/v1");
synapseClient.setBearerAuthorizationToken(personalAccessToken);
```

Any further questions, please ask!
