### ISSUE TITLE
Remove @material-extended/mde

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4265]
**Is your feature request related to a problem? Please describe.**
Updating Angular is a pain because `@material-extended/mde` is using an old version of Angular

**Describe the solution you'd like**
Just remove it. We've made a popover before with just material menu, we should not require another dependency.

**Describe alternatives you've considered**
🦗 

**Additional context**
It's still on Angular 9 (although it still works)
`@material-extended/mde" has an incompatible peer dependency to "@angular/cdk" (requires "^8.0.0 || ^9.0.0-0", would install "11.2.13")`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1805)
┆fixVersions: Dockstore 1.14
┆friendlyId: DOCK-1805
┆sprint: 95- W
┆taskType: Story

**Comment by melainalegaspi** [comment]
Assignee to figure out how many popovers we have and determine how difficult this will be.

**Comment by melainalegaspi** [comment]
@denis-yuen : "do this while checking out the new version of Angular."

**Comment by coverbeck** [comment]
There is only one usage of this component, when clicking the Share button on the Search page.

**Comment by coverbeck** [comment]
https://github.com/dockstore/dockstore-ui2/pull/1614 (visible on the GitHub issue, but not on the DOCK ticket) :(
