### ISSUE TITLE
Add Galaxy and Nextflow Tower to Integration Partners

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4266]
**Is your feature request related to a problem? Please describe.**
We have launch with buttons for Galaxy and Nextflow Tower, but they are not listed on our [about page](https://dev.dockstore.net/about).

We should confirm with Nextflow if they are OK with us adding them first.

**Describe the solution you'd like**

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1806)
┆fixVersions: Dockstore 1.13.x
┆friendlyId: DOCK-1806
┆sprint: 95- W
┆taskType: Story

**Comment by denis-yuen** [comment]
@pditommaso

The current launch with nextflow goes to the tower.nf as noted in https://github.com/dockstore/dockstore/issues/4040#issuecomment-782868612

Two questions
1) There are trademark rules for https://github.com/nextflow-io/trademark are there similar rules for Nextflow Tower https://github.com/seqeralabs/nf-tower/blob/master/tower-web/src/assets/landing/assets/img/nf-tower-purple.svg
2) Would you be comfortable with us listing Nextflow Tower as an integration partner? (Nextflow as a language will remain listed as being compatible with Dockstore on the main logged-off homepage)

**Comment by pditommaso** [comment]
Hi Denis, the "nextfow tower" trademark belongs to Seqera, you are welcome to use it as a reference for the launching feature you are implementing.

**Comment by denis-yuen** [comment]
simple with no side-effects, I think it is worth doing

**Comment by coverbeck** [comment]
@hyunnaye Can you please cherry-pick your fix to a PR against the hotfix.

**Comment by coverbeck** [comment]
Confirmed this is fixed in staging.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.1) - 1.13.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.1) - 2.10.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.1) - 1.13.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.13.1) - 1.13.1
