### ISSUE TITLE
Relax rules for Amazon ECR tools

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4283]
**Describe the bug**
It's currently difficult to register tools with Amazon ECR because of aggressive checks (both backend and frontend)

**To Reproduce**
1. Register tool with remote site
2. Choose Amazon ECR
3. Try registering with something like https://gallery.ecr.aws/x5g7o3i3/appropriate/curl
4. See sanity check errors in both the Image Registry and Docker Registry Path

**Expected behavior**
Should be able to register a tool using an Amazon ECR image like https://gallery.ecr.aws/x5g7o3i3/appropriate/curl

**Additional context**
 [Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.2) - 1.10.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.4) - 2.7.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.10.1) - 1.10.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1815)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1815
┆Sprint: Sprint 65-Pyjama shark
┆Issue Type: Story

**Comment by pgroves** [comment]
(I originally brought up this issue on the Discourse forum)

You could also consider a 'catch all' option that takes any valid docker url, which is the underlying requirement of wdl. For instance, we have some old images like: `hub.ncsa.illinois.edu/phyloflow/pyclone` hosted on our own hub. I don't think it makes sense for dockstore to try to hardcode a menu option for every small hub like that. 

Thank you for your fast response.

**Comment by NatalieEO** [comment]
Registered a tool that used an amazon ecr image and was able to see it appear in the DAG and Tools tabs
