### ISSUE TITLE
DAG 500 for workflow version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4284]
**Describe the bug**
There's a 500 error when looking at the DAG for certain workflow versions

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/dockstore/hello_world:1.03?tab=dag
2. See the developer network tools
3. See error

**Expected behavior**
No 500 error, either the DAG loads or there's a frontend error message of some sort

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/e6917fb) - e6917fb

[UI](https://github.com/dockstore/dockstore-ui2/commits/6e8b18cc) - 2.8.0-rc.0-12-g6e8b18cc

[Compose Setup](https://github.com/dockstore/compose_setup/commits/ca97667) - ca97667

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/dd42013) - 1.10-83-gdd42013

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1816)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1816
┆Sprint: Sprint 63- Nurse Shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
From Slack conversation, one possibility is some bug between DAG caching and snapshotting

**Comment by coverbeck** [comment]
This happens in prod and staging too. :(
