### ISSUE TITLE
documentation covering options for how SevenBridges CWL workflows can be used on Dockstore

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#4286]
**Is your feature request related to a problem? Please describe.**
How do CWLs developed on the SevenBridges platforms work on Dockstore? Do they need to be updated to remove SB labels or can they be uploaded as-is? If they require further testing with cwltool, it will likely deter folks from publishing on Dockstore. 

**Describe the solution you'd like**
If errors don't arise when using SB-developed CWL tools on Dockstore, I would suggest adding this information to our documentation.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1818)
┆fixVersions: Dockstore 1.11.X
┆friendlyId: DOCK-1818
┆sprint: Sprint 64-Oceanic shark
┆taskType: Story

**Comment by garyluu** [comment]
Ah, we still have a hotfix/1.11.1 branch in docs even though 1.11.2 is out

**Comment by garyluu** [comment]
I see it on https://docs.dockstore.org/en/stable/getting-started/getting-started-with-cwl.html

![image](https://user-images.githubusercontent.com/24548904/129270996-bba07331-73bc-4d71-ba6c-642905d9617f.png)
