### ISSUE TITLE
language support needs an update

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4288]
Galaxy will be out of date for 1.11, possibly others
https://docs.dockstore.org/en/develop/end-user-topics/language-support.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1819)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1819
┆Sprint: Sprint 64-Oceanic shark
┆Issue Type: Story

**Comment by garyluu** [comment]
I see the changes made it https://docs.dockstore.org/en/1.11.2/end-user-topics/language-support.html
