### ISSUE TITLE
Refreshing on the my tools/workflows page will always set the first namespace to be expanded

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#429]
On my tools or my workflows, when you do an action which causes a refresh, it should keep the namespace of the currently selected workflow open, instead of opening the first in the list.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-453)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-453

**Comment by melainalegaspi** [comment]
closed in favor of  #978
