### ISSUE TITLE
Remove duplicate IP accounting for fedramp inventory lambda

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4298]
**Describe the bug**
The inventory lambda duplicates instance entries that have multiple IP addresses https://github.com/dockstore/lambda/blob/f2686d21854246e82e6a426dbe4f9832a3101456/fedramp-integrated-inventory-workbook/deployment/inventory/mappers.py#L102.

This was done on purpose, but is not compliant with control requirements, so it should be removed.

**Expected behavior**
Only 1 row entry per unique resource. Include both IPs as necessary for the row.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1825)
┆Issue Number: DOCK-1825
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Should probably be SEAB

**Comment by Richard-Hansen** [comment]
Moving to SEAB
