### ISSUE TITLE
Pkj

### ISSUE THREAD

**Issue by Pkanjai** [dockstore/dockstore#4299]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 - UI version: [e.g. 2.5.0]
 - Webservice version: [e.g. 1.8.0]
 - host location: [e.g. staging.dockstore.org]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1827)
┆Issue Number: DOCK-1827
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Going to assume this was a typo
