### ISSUE TITLE
Changing staging/prod smoke tests

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4306]
**Describe the bug**
If staging/prod smoke tests are flakey (or just wrong) and needs changing, it should be able to do so without creating another release to staging/prod.

**To Reproduce**
1. See failing staging tests for the past 3 weeks since the creation of this issue despite the tests are supposedly fixed on the dev branch already

**Expected behavior**
Since tests are not production code, it should not be tied to a release anywhere.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.0-rc.0) - 1.11.0-rc.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.0-rc.1) - 2.8.0-rc.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.0-rc.1) - 1.11.0-rc.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0-rc.0) - 1.11.0-rc.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1829)
┆Issue Number: DOCK-1829
┆Sprint: Sprint 64-Oceanic shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Should probably be SEAB

**Comment by garyluu** [comment]
> Seems reasonable, but should probably be SEAB

Thought in one of the retros, someone mentioned we should use GitHub issues more unless it's security related

**Comment by denis-yuen** [comment]
Fair point, I think end users/collaborating can see our smoke tests, so let's leave it.
