### ISSUE TITLE
CLI entry2json generates invalid JSON file

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4307]
**Describe the bug**
The  generated JSON file has an upgrade message in it, making the JSON invalid.

**To Reproduce**
```
dockstore workflow convert entry2json --entry github.com/DockstoreTestUser/dockstore-whalesay/dockstore-whalesay-wdl:master > Dockstore.json
~/temp$ cat Dockstore.json
Current version : 1.10.0
You have the most recent stable release.
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
{
  "test.hello.name": "String"
}
```

**Expected behavior**
The generated JSON should be valid. The upgrade message shouldn't be in there.

Not a huge deal, as you'll probably edit the JSON file anyway, but still.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1830)
┆Issue Number: DOCK-1830
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Same underlying issue as https://github.com/dockstore/dockstore/issues/4307 
(does the upgrade message go to stdout, stderr, something else?)
