### ISSUE TITLE
Logged-in home page events only showing certain events

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4311]
**Describe the bug**
This may be as designed, as we may not want to show everything, but in my case it the only event being shown was a workflow being added to a collection, where that workflow was no longer in a collection.

**To Reproduce**
1. Log in to staging
2. Go to https://staging.dockstore.org/organizations/UCSCGI
3. Star the org if you haven't already
4. Go to the home page
5. Hopefuly see, depending on what else you've starred. 
![Screen Shot 2021-06-16 at 4 32 04 PM](https://user-images.githubusercontent.com/1049340/122308045-6c3e5880-cec0-11eb-8af9-095ab9245407.png)
6. Click "hello_world"
7. It's not in a collection

**Expected behavior**
Show all events, or show events in pairs, e.g., if showing add to collection, show remove from collection.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.0-rc.0) - 1.11.0-rc.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.0-rc.1) - 2.8.0-rc.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.0-rc.1) - 1.11.0-rc.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0-rc.0) - 1.11.0-rc.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1833)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1833
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
this is rendered obsolete by https://github.com/dockstore/dockstore/pull/4960
