### ISSUE TITLE
Search should have a workflow language version facet

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4320]
**Is your feature request related to a problem? Please describe.**
CWL Viewer only works for CWL 1.0 and up; it would be nice to know which versions are CWL 1.0.

That's more of a demo scenario, but there are probably other scenarios where certain platforms may only support certain versions, and it would be useful to find applicable versions.

**Describe the solution you'd like**
I guess a workflow version facet, e.g., WDL 1.0, CWL 1.0, WDL 1.1, etc. Might get tricky, as one workflow could have many workflow versions.

**Describe alternatives you've considered**
Leave it as is

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1838)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-1838
┆Sprint: 101 - Cheeks, Sandy
┆Issue Type: Story

**Comment by denis-yuen** [comment]
This probably needs to be split up but will be important for implementing TRS 2.0.1 which includes information on what versions of the workflow languages the descriptors in a workflow contain. See https://github.com/ga4gh/tool-registry-service-schemas/pull/219
