### ISSUE TITLE
New home page should have Galaxy and Nextflow Tower logos

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4323]
**Is your feature request related to a problem? Please describe.**
There's a diagram on the 1.11 logged out home page that doesn't include all of our partners. In particular Galaxy and Nextflow Tower are missing.

**Describe the solution you'd like**
It should include all of our launch with partners

**Describe alternatives you've considered**
A disclaimer that it's incomplete.

Referring to this image:

![Screen Shot 2021-06-22 at 5 28 41 PM](https://user-images.githubusercontent.com/1049340/123016425-68f31300-d37f-11eb-9c42-806fdb97df92.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1839)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1839
┆Sprint: Backlog
┆Issue Type: Story

**Comment by melainalegaspi** [comment]
Nextflow tower is a bit different and Galaxy is done, closing.
