### ISSUE TITLE
Confusing search results for n/a author

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4324]
**Describe the bug**
The number of workflows with the author `n/a` does not match the facet number for `n/a` in at least one case.

Without looking at the code, my wild guess is that one workflow actually has `n/a` as the author, whereas the others don't have an author at all, and we display `n/a` when there is no author. 

**To Reproduce**
1. Go to https://staging.dockstore.org/search?organization=broadinstitute&entryType=workflows&searchMode=files
2. See a bunch of entries with the author `n/a`
3. But, see the count for the `n/a` facet is only 1.

**Expected behavior**
Ideas:
* Display nothing instead of `n/a` if we don't have the author. 
* Display something else, e.g., `<unknown>`, that is less likely to conflict with an actual value
* ?

**Screenshots**
![Screen Shot 2021-06-22 at 5 47 34 PM](https://user-images.githubusercontent.com/1049340/123017776-22eb7e80-d382-11eb-9c83-4841bca6c654.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.3) - 1.11.3

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.0-rc.1) - 2.8.0-rc.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1840)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1840
┆sprint: 93- Ursula
┆taskType: Story

**Comment by garyluu** [comment]
A clear and concise description of what you expected to happen.

**Comment by garyluu** [comment]
> * Display nothing instead of `n/a` if we don't have the author.

Didn't we originally do this but someone thought it was confusing?
