### ISSUE TITLE
New Dockstore email address for Medium blog/ newsletter publication

### ISSUE THREAD

**Issue by avani-k** [dockstore/dockstore#4327]
**Is your feature request related to a problem? Please describe.**
As part of the Dockstore outreach efforts, a blog that can eventually turn into a newsletter has been proposed. We have determined [Medium](https://medium.com/) to be a good platform. 

**Describe the solution you'd like**
A Dockstore email that can be used to get a [Medium](https://medium.com/) subscription. Something relevant to the purpose of this email such as, info@dockstore.org or news@dockstore.org?

**Describe alternatives you've considered**

**Additional context**

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1842)
┆Issue Number: DOCK-1842
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Some stuff to look into here https://news.ycombinator.com/item?id=27819814

**Comment by melainalegaspi** [comment]
Decided not to have a shared email.
