### ISSUE TITLE
Info box that shows up when hovering over a DAG node doesn't disappear

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4333]
**Describe the bug**
When hovering over a node on the DAG tab for a workflow, an info box appears. When I stop hovering over the node, the info box still remains. The info box doesn't disappear, even if I change from the DAG tab to another tab, like the Versions tab.

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=dag
2. Hover over a node, like the `sum_cram_file_sizes` node. An info box appears for the node.
3. Stop hovering over the node.
4. The info box remains.
5. Click on the Versions tab. The info box remains.

This bug seems to only happen on dev. Staging is okay. View the corresponding workflow on staging: https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=dag.

**Expected behavior**
The info box disappears when the mouse is not hovering over the node.

**Screenshots**
I hovered over a bunch of nodes and the info boxes remained after I stopped hovering over a node.
![Screenshot 2021-06-30 at 11-24-24 Dockstore Workflow](https://user-images.githubusercontent.com/25287123/123991554-d236df80-d998-11eb-92eb-aef3f883509d.png)
I changed to the Versions tab. Shown below, the info boxes remained.
![Screenshot 2021-06-30 at 11-24-45 Dockstore Workflow](https://user-images.githubusercontent.com/25287123/123991562-d531d000-d998-11eb-9c9d-c514f679be81.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/26d60e4) - 26d60e4

[UI](https://github.com/dockstore/dockstore-ui2/commits/3b7a7164) - 2.8.0-rc.0-20-g3b7a7164

[Compose Setup](https://github.com/dockstore/compose_setup/commits/7ad0764) - 7ad0764

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/94dee6d) - 1.11.0-18-g94dee6d

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1846)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1846
┆Sprint: Sprint 65-Pyjama shark
┆Issue Type: Story

**Comment by garyluu** [comment]
ah crud, must've been when i blindly updated one of the deps
