### ISSUE TITLE
Add file tree to other types of entries on Dockstore

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#4334]
**Is your feature request related to a problem? Please describe.**
I was reviewing #4229, but didn't see the file tree anywhere because I didn't realize it was only added to .dockstore.yaml workflows. 

**Describe the solution you'd like**
I think the file tree should be in every entry that has more 10 files.

┆Issue is synchronized with this [Jiraserver Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1847)
┆Issue Number: DOCK-1847
┆Sprint: Sprint 67- Reef shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
The link to 4229 actually works on github, might need to ping @garyluu to link the relevant PR

**Comment by garyluu** [comment]
https://github.com/dockstore/dockstore-ui2/pull/1316  it's linked to another issue but it kind of solves this one
