### ISSUE TITLE
Fetching workflows slower on staging about 25% slower than prod

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4338]
**Describe the bug**
Fetching workflows on staging is a bit slower than on prod.

Suspect authors is to blame.
**To Reproduce**
Note that because web service caches responses, the following steps may not always be reproducible.

```
gtime curl -X GET "https://staging.dockstore.org/api/ga4gh/trs/v2/tools?toolClass=Workflow&limit=1000" -H  "accept: application/json" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9015k    0 9015k    0     0   283k      0 --:--:--  0:00:31 --:--:-- 2617k
0.04user 0.04system 0:31.88elapsed 0%CPU (0avgtext+0avgdata 6288maxresident)k
0inputs+0outputs (0major+1782minor)pagefaults 0swaps
~$ gtime curl -X GET "https://dockstore.org/api/ga4gh/trs/v2/tools?toolClass=Workflow&limit=1000" -H  "accept: application/json" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9120k    0 9120k    0     0   377k      0 --:--:--  0:00:24 --:--:-- 2484k
0.04user 0.04system 0:24.16elapsed 0%CPU (0avgtext+0avgdata 6304maxresident)k
0inputs+0outputs (0major+1781minor)pagefaults 0swaps
```

**Expected behavior**
Should be closer in performance

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.3) - 1.11.3

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.0-rc.1) - 2.8.0-rc.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1850)
┆Issue Number: DOCK-1850
┆Sprint: Sprint 65-Pyjama shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
FYI @garyluu

**Comment by garyluu** [comment]
not really related to my issue i think. since staging and dockstore.org are both 1.11.5
