### ISSUE TITLE
Cannot update a notification via Swagger UI

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4351]
**Describe the bug**
Attempting to update a notification via Swagger UI returns 415, Unsupported Media Type.

In generated curl, content-type needs to be `application/json` instead of `*/*`.

Note to implementer: when fixing, it would be good to go through all our APIs and check. It seems like these keep popping up.

**To Reproduce**
1. Go to ..../api/static/swagger-ui/index.html#/curation/updateNotification
2. Authorize with an admin token
3. Create a notification if one doesn't exist
4. Update the existing notification

**Expected behavior**
It should work

**Screenshots**
![Screen Shot 2021-07-12 at 10 20 04 AM](https://user-images.githubusercontent.com/1049340/125329792-c208f380-e2fa-11eb-9e58-f6c5d05598ea.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.2) - 1.10.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.4) - 2.7.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.10.1) - 1.10.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1856)
┆Issue Number: DOCK-1856
┆Sprint: Sprint 66- Quagga shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
This is working now
[Webservice](https://github.com/dockstore/dockstore/commits/6f701da) - 6f701da

[UI](https://github.com/dockstore/dockstore-ui2/commits/95bc00b5) - 2.8-44-g95bc00b5

[Compose Setup](https://github.com/dockstore/compose_setup/commits/abf5bef) - abf5bef

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/9fc59c9) - 1.11.0-29-g9fc59c9
