### ISSUE TITLE
ORCID ID null during export

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4357]
**Describe the bug**
Sometimes while exporting a workflow to ORCID, ORCID would respond with "ORCID iD is null"

**To Reproduce**
1. Locally have a db dump where you don't have an ORCID ID at all (user.orcidId is null)
2. Reload the database with the db dump and do the migrations and such
3. Start webservice, link ORCID iD, immediately try to export to ORCID

**Expected behavior**
There should be no error

**Additional context**
It is possibly caching?

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.5) - 1.11.5

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8) - 2.8

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1858)
┆Issue Number: DOCK-1858
┆Sprint: Sprint 66- Quagga shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
In prod:

* Unlinked ORCID yesterday.
* Relinked today and immediately exported to ORCID
* Worked.

Verified in:

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1
