### ISSUE TITLE
Snackbar messages for snapshot/export to ORCID have "null" in them

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4366]
**Describe the bug**
Snackbar messages for snapshotting and exporting to orcid have the word `null' in them.

**To Reproduce**
1. Go to My Workflows
2. Select a published workflow
3. Go to versions tab
4. Export to ORCID

See "null" in the message.

Also happens when you just do a snapshot.

**Expected behavior**
The message should have the workflow name, not `null`.

**Screenshots**
![Screen Shot 2021-07-21 at 3 30 09 PM](https://user-images.githubusercontent.com/1049340/126568410-4c8f8765-f585-4650-b28d-c5bf42201eb7.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.5) - 1.11.5

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8) - 2.8

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1862)
┆Fix Versions: Dockstore 1.11.X
┆Issue Number: DOCK-1862
┆Sprint: Sprint 68- Smoothbound shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
I see the version in the message when you snapshot and export to orcid now
[Webservice](https://github.com/dockstore/dockstore/commits/17a5046) - 17a5046

[UI](https://github.com/dockstore/dockstore-ui2/commits/16b3816d) - 2.8.1-56-g16b3816d

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4) - dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/bdb7ceb) - 1.11.1-46-gbdb7ceb
