### ISSUE TITLE
Pasting a very long string into the Search box causes 500 error

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#4373]
**Describe the bug**
Pasting a very long string into the Search box causes 500 error

**To Reproduce**
Type 'This is a very long search string' in Search box
Copy search string into clipboard, e.g. Ctrl-c
Repeatedly paste the string into the Search box perhaps 20 times, e.g. Ctrl-v
Note 500 error box appears and Monitor down Alarm is generated

**Expected behavior**
Should just notify user that the string is too long

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS 
 - Browser Chrome
 - Version Big Sur 11.4

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.5) - 1.11.5

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8) - 2.8
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

 - host location: dockstore.org

┆Issue is synchronized with this [Jiraserver Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1865)
┆Issue Number: DOCK-1865
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@NatalieEO  what was the story here, is this a duplicate maybe?

**Comment by NatalieEO** [comment]
@denis-yuen I asked Walt to make it a SEAB issue instead https://ucsc-cgl.atlassian.net/browse/SEAB-3181, although I thought I had fixed this before :/

**Comment by wshands** [comment]
To make the 500 happen I repeatedly pasted the search string into the search box; the method of reproducing the 500 is not just pasting a large string into the search box. This may be an unrealistic scenario, but the 500 should be prevented.
