### ISSUE TITLE
Perform search once user hits enter

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#4404]
**Is your feature request related to a problem? Please describe.**
The Dockstore search page currently does a search after the user stops typing some text in the search field. It's pretty clunky and performs a lot of unnecessary/unwanted search requests. I also can't think of another search page that behaves this way.

**Describe the solution you'd like**
A search should only be done once the user hits enter and/or presses a button.

**Describe alternatives you've considered**
Increase the debounce time?

**Additional context**
Related to 
https://ucsc-cgl.atlassian.net/browse/SEAB-3181

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1878)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1878
┆sprint: SEAB 81- Jacques
┆taskType: Story

**Comment by garyluu** [comment]
presumably the autocomplete still works after this change
