### ISSUE TITLE
500 collection creation

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4407]
**Describe the bug**
Users appears to be unable to create a collection in certain circumstances

**To Reproduce**
1. POST /api/organizations/17/collections (after becoming an admin of the org presumably)
2. See error

**Expected behavior**
Be able to create the collection

**Additional context**
Log:
[06/Aug/2021:13:27:15 +0000] "POST /api/organizations/17/collections HTTP/1.1" 500 269 "https://dockstore.org/organizations/LSGxE" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.5) - 1.11.5

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8) - 2.8

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1881)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1881
┆Sprint: Sprint 69- Tiger shark
┆Issue Type: Story

**Comment by david4096** [comment]
I can confirm that the error 

```
[HTTP 400] Bad Request: A collection already exists with the display name 'NameName' in the specified organization.
```

shows up when you request a duplicate displayName in the same org.

[Webservice](https://github.com/dockstore/dockstore/commits/aa974f8) - aa974f8

[UI](https://github.com/dockstore/dockstore-ui2/commits/9ffdccc7) - 2.8.2-62-g9ffdccc7

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4) - dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d7d397a) - 1.11.1-50-gd7d397a
