### ISSUE TITLE
Add checksum harvesting for GitHub Container Registry tools

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4410]
**Is your feature request related to a problem? Please describe.**
Currently we only harvest checksums for GitHub Container Registry images in workflows, but not for GitHub Container Registry tools.

**Describe the solution you'd like**
We should also harvest checksums for GitHub Container Registry tools.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1883)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1883
┆sprint: Backlog
┆taskType: Story

**Comment by melainalegaspi** [comment]
Ensure this works for "tool as workflow"
