### ISSUE TITLE
"contact us" button on homepage doesn't work

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#4412]
**Describe the bug**
It seems like there is no URL linked to "contact us" on the homepage. It won't let me click on it. 

**To Reproduce**
1. Go to 'https://dockstore.org/
2. Scroll to the bottom and click on 'contact us'

**Expected behavior**

**Additional context**
 - UI version: 1.11.5

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1885)
┆Issue Number: DOCK-1885
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Duplicates https://github.com/dockstore/dockstore/issues/4375
