### ISSUE TITLE
UI bug in collections that have a table in the README

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#4413]
**Describe the bug**

**To Reproduce**
1. Go to https://dockstore.org/organizations/bdcatalyst/collections/Utilities

When I'm a maintainer of the Org and logged in, the table in the README is too large and squishes the workflow entry
![Screen Shot 2021-08-16 at 1 04 54 PM](https://user-images.githubusercontent.com/7770106/129623022-f2343d25-ac83-46b0-82c0-4b99240ddc9c.png)

**Expected behavior**
I would expect that README tables would have a maximum width set?

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome 92.0.4515.107 

**Additional context**
 - UI version: 2.9
 - Webservice version: 1.11.5
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1886)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1886
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by aofarrel** [comment]
Some further context: This isn't quite as bad when logged out, but still isn't in line with other collections. This screenshot is from staging.
<img width="1354" alt="Screen Shot 2021-10-21 at 10 46 07 AM" src="https://user-images.githubusercontent.com/27784612/138330230-6710cf1a-7c7e-4e63-87eb-4af8fd2a848c.png">
