### ISSUE TITLE
CLI bug where Cromwell is incorrectly installed

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#4416]
**Describe the bug**
A researcher attempted to download the Dockstore CLI to develop a WDL. When trying to execute a WDL locally with the CLI, she got the error `Error: Invalid or corrupt jarfile cromwell`. She looked in the Dockstore library and found that Dockstore is still using 57 (any reason why we aren't using the latest 66?). She found a similar error on the internet where if using curl instead of wget that Cromwell is downloaded as HTML. She successfully debugged by installing and using wget to get Cromwell-66, and was able to run the test WDL.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1887)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1887
┆sprint: Backlog
┆taskType: Story

**Comment by coverbeck** [comment]
This works for me. What Operating System and version? What version of the CLI (`dockstore --version`)?

My steps:

1. `rm ~/.dockstore/cromwell*.jar` (to force CLI  to download Cromwell again)
2. `dockstore workflow convert entry2json --entry github.com/Richard-Hansen/dockstore-whalesay:master > Dockstore.json`
3. dockstore workflow launch --entry github.com/Richard-Hansen/dockstore-whalesay:master --json Dockstore.json

On the Cromwell version, we've only tested with 57, but we should look at updating. You can override the the default [Cromwell version the CLI uses](https://docs.dockstore.org/en/stable/advanced-topics/advanced-features.html?highlight=cromwell#wdl-launcher-configuration).

**Comment by bethsheets** [comment]
Java 16.0.2
Dockstore 1.11
Can ask about OS
