### ISSUE TITLE
Enable requester pays in gs-plugin.

### ISSUE THREAD

**Issue by DailyDreaming** [dockstore/dockstore#4419]
**Is your feature request related to a problem? Please describe.**
Requester pays gs:// files don't seem to work with the dockstore cli.

I believe it should pick it up when the client is instantiated somewhere around here: https://github.com/dockstore/gs-plugin/blob/develop/src/main/java/io/dockstore/provision/GSPlugin.java#L147 ?

I believe the error is “bucket is requester pays but no user project specified”.

**Describe the solution you'd like**
I'd love it to work.

**Describe alternatives you've considered**
Generate a signed url prior to the workflow run.  Kind of a pain though, as they expire.

**Additional context**
This was originally encountered/reported by @aofarrel .  I was told I could post the issue here by @NatalieEO .

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1889)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-1889
┆sprint: Backlog
┆taskType: Story

**Comment by aofarrel** [comment]
I don't know if this will help and I am a little embarrassed by my try/except block, but I made a quick edit of Lon's code to pull gs files from jsons by leveraging off gsutil -u: https://github.com/DailyDreaming/fetch_gs_frm_json/blob/0ba13cd88b91ba3de166b8e72a004af4295205bf/dl_gsfiles_frm_json.py

gsutil -u seems to sidestep some issues, and we could put the name of the billing project as something that goes in the .dockstore/config file.
