### ISSUE TITLE
"entries" property missing in OpenAPI 3.0 schema for Collection

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4422]
After implementing

https://github.com/dockstore/dockstore/pull/4421

the validator issues a warning about the OpenAPI 3.0 openapi.yaml file, indicating that CollectionEntry schema is unused.  Charles advised it should be referenced, so I investigated, and in openapi.yaml, the Collection schema was indeed missing the "entries" property of type array of CollectionEntry.  I spent a lot of time trying to fix it, taking several different approaches: making sure the annotations were correct, changing JsonProperty to a different name to see if it appeared (it did!), rewriting the code to make sure fields and method names were not somehow "shading" the relevant properties, etc.  Didn't work.

Reverting openapi-annotations-version to 2.1.3 makes the proper "entries" property appear in openapi.yaml with no code changes, suggesting that we are hitting a bug in subsequent versions of swagger-maven-plugin.  I believe it broke when we upgraded from 2.1.1 to 2.1.7.  The evidence is not conclusive or even entirely consistent, but there are possibly-related bug reports here and there, for example:

https://github.com/swagger-api/swagger-ui/issues/6021

The sticky part is that 2.1.3 introduced sorting, which was the motivation for 2.1.1 -> 2.1.7, but the sorting feature is partially broken (confirmed) until 2.1.4, which has the "entries" bug.  Sorting feature is important, and the current problem does not break the UI, so consensus was to create an issue, and hope it's fixed upstream before we need to address it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1890)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-1890
┆Sprint: 115 - Niagara
┆Issue Type: Story

**Comment by coverbeck** [comment]
Seeing something similar with the `users` property in Organization. It's showing up in Swagger but not OpenAPI. This might mean the issue isn't related to the name `entries`, one of the theories [here](https://github.com/dockstore/dockstore/pull/5541#issue-1742650998). Or it's a different problem.

**Comment by denis-yuen** [comment]
> Seeing something similar with the `users` property in Organization. It's showing up in Swagger but not OpenAPI. This might mean the issue isn't related to the name `entries`, one of the theories [here](https://github.com/dockstore/dockstore/pull/5541#issue-1742650998). Or it's a different problem.

Yeah, I'm leaning toward the clashing name theory and not specifically "entries". It's just bad practice to have "entries"", ignore it, and then export something entirely different as "entries". Is that what you're seeing in Organization?

**Comment by svonworl** [comment]
> > Seeing something similar with the `users` property in Organization. It's showing up in Swagger but not OpenAPI. This might mean the issue isn't related to the name `entries`, one of the theories [here](https://github.com/dockstore/dockstore/pull/5541#issue-1742650998). Or it's a different problem.
> 
> Yeah, I'm leaning toward the clashing name theory and not specifically "entries". It's just bad practice to have "entries"", ignore it, and then export something entirely different as "entries". Is that what you're seeing in Organization?

Yeah, it's definitely evidence against "entries" itself being uniquely cursed.  Although, if it was just a simple name clashing issue, either you or I would have typically pinpointed and fixed it in about five seconds.  So weird...

**Comment by coverbeck** [comment]
> > Seeing something similar with the `users` property in Organization. It's showing up in Swagger but not OpenAPI. This might mean the issue isn't related to the name `entries`, one of the theories [here](https://github.com/dockstore/dockstore/pull/5541#issue-1742650998). Or it's a different problem.
> 
> Yeah, I'm leaning toward the clashing name theory and not specifically "entries". It's just bad practice to have "entries"", ignore it, and then export something entirely different as "entries". Is that what you're seeing in Organization?

I hadn't paid close attention to the details of the other bug and hadn't noticed the shadowing there. I don't see any shadowing in this case.

**Comment by denis-yuen** [comment]
> I don't see any shadowing in this case.

:sad:
Well, that's a pain. Can you write what you know and assign the ticket to me? Maybe I can get some inspiration by looking at the Organization version of the issue.
