### ISSUE TITLE
Unpublishing #4436's workflow results in nonsensical errors

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4437]
**Describe the bug**
Unpublishing the mysterious workflow of #4436 additionally throws a Google credentials error even though I don't have Google connected to my Dockstore account. Furthermore, when I unpublish or republish the workflow, the popup at the bottom of the screen reads "failed" in lowercase, indicate an error code is getting cut off.
![](https://user-images.githubusercontent.com/27784612/131581110-736bb927-06af-498d-8f90-6e22bf6ce5c9.png)

**Expected behavior**
Although this may become moot if #4436 is resolved, this may indicate an error in the way errors are handled.

![](https://user-images.githubusercontent.com/27784612/131581009-6d36940e-41ef-459c-b359-71178bbda015.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1899)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-1899
┆sprint: Sprint 74- Aquaman
┆taskType: Story

**Comment by coverbeck** [comment]
Discussed with @aofarrel , he cannot reproduce -- attempting to unpublish the workflow in this example leads to a (correct) cannot unpublish checker workflow error. Things have a changed a bit in the year since this bug was written, I don't think it's worth pursuing further unless it arises again.
