### ISSUE TITLE
Workflow name and tool name aren't validated when manually publishing using CLI

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4447]
**Describe the bug**
The UI performs validation on the workflow name, like making sure it doesn't contain slashes. 
![image](https://user-images.githubusercontent.com/25287123/131895822-bd92b2aa-89cc-4228-be11-59574eca1601.png)

It seems like this type of validation isn't done on the CLI because I was able to manually publish a workflow with a workflow name containing slashes. This leads to several problems in the UI.

I can see this workflow on the search page: https://dev.dockstore.net/search?entryType=workflows&search=foo%2Fbar, but clicking on it leads to nowhere.

It shows up on my "My Workflows" page, but I can't unpublish it. The View Public button also leads to nowhere.
![image](https://user-images.githubusercontent.com/25287123/131896115-5f137071-d97a-476e-98b0-5a25a3bdfafc.png)

I didn't perform extensive testing for registering tools via the CLI, but I was able to register a tool with a tool name containing slashes (didn't publish), so a similar problem may also happen for tools.

**To Reproduce**

1. Using the CLI, I created a workflow with a workflow name containing slashes:
{{ dockstore workflow manual_publish --repository ghcr-workflow --organization kathy-t --git-version-control github --workflow-path /Dockstore.wdl --descriptor-type WDL --workflow-name foo/bar}}. 
1. Go to dev.dockstore.net and go to the Search page.
1. Search for "foo/bar" to find the workflow that was successfully registered and published.
1. Click on the workflow link. It takes you to the homepage instead of the workflow's page.
1. Go to My Workflows.
1. View the workflow that was published.
1. Observe that the "Unpublished" button is disabled.
1. Click on the "View Public" button. It takes you to the homepage instead of the public workflow page.

**Expected behavior**
Shouldn't be able to register a workflow/tool with a workflow/tool name containing slashes. Should perform similar validation that the UI does for workflow/tool name.

**Screenshots**
This is the workflow on the Search page:
![image](https://user-images.githubusercontent.com/25287123/131896459-8223f0a3-9703-4395-a007-593c75313ee6.png)

When I click on the workflow link, it takes me to the homepage:
![image](https://user-images.githubusercontent.com/25287123/131896534-8f5c78ab-5ecd-4f6c-ad54-6aa9a10b4409.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/d2b3048)

* d2b3048

[UI](https://github.com/dockstore/dockstore-ui2/commits/c61d706b)

* 2.8.1-54-gc61d706b

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4)

* dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/b119630)

* 1.11.1-44-gb119630

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1902)
┆Fix Versions: Dockstore 1.11.X
┆Issue Number: DOCK-1902
┆Sprint: Sprint 72-Yellowspotted Catsha
┆Issue Type: Story

**Comment by chmreid** [comment]
Sounds good!
