### ISSUE TITLE
Maven wrapper and CI maven version discrepancy

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4448]
**Is your feature request related to a problem? Please describe.**
Updating to a different maven version in the maven wrapper vs CI can cause problems (different generated pom files will cause build failure). in particular, there are differences in generated pom files in version 3.8.2 vs 3.8.1.

**Describe the solution you'd like**
Maven wrapper's maven version should be the same as CircleCI for consistency which means changing one of them
This is applicable to both Dockstore-CLI and dockstore/dockstore (and also other repos that use maven wrapper)

**Describe alternatives you've considered**
Using the latest compatible version in maven wrapper (3.8.1), keeping the CI's image the same (3.6.3)

**Additional context**
https://github.com/dockstore/dockstore-cli/pull/81#discussion_r701321680

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1903)
┆Issue Number: DOCK-1903
┆Sprint: Sprint 70- Whale shark
┆Issue Type: Story

**Comment by david4096** [comment]
I can confirm both the POM and circle are pointing to the same maven distributions. https://github.com/dockstore/dockstore-cli/pull/83/files#diff-1df564955cac198c2a317aceb01d86891160f1b185d9875b384b7d54819af358R1

https://github.com/dockstore/dockstore-cli/pull/83/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R476
