### ISSUE TITLE
Columns for a published workflow's Authors table is squished if the author name is long

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4462]
**Describe the bug**
The authors table for this workflow on dev looks strange and squished since the Author's name is very long: 
https://dev.dockstore.net/workflows/github.com/AnalysisCommons/genesis_wdl/genesis_GWAS:v1_4_1?tab=info
![image](https://user-images.githubusercontent.com/25287123/133096290-2cb00aca-e294-49cf-9fd5-26492febd29e.png)

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/AnalysisCommons/genesis_wdl/genesis_GWAS:v1_4_1?tab=info
2. Look at the Authors table

**Expected behavior**
The Role, Affiliation, and Email columns shouldn't be squished together like that. The Author column shouldn't be so large. The width of the Authors table columns aren't fixed right now. Maybe they should be to avoid this squishing.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/fb2f90a) - fb2f90a

[UI](https://github.com/dockstore/dockstore-ui2/commits/9ffdccc7) - 2.8.2-62-g9ffdccc7

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4) - dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/d7d397a) - 1.11.1-50-gd7d397a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1911)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1911
┆sprint: Seabright Sprint 78- Flotsam
┆taskType: Story

**Comment by denis-yuen** [comment]
Might want to compare with zeplin mocks as well

**Comment by coverbeck** [comment]
Confirmed that the author no longer wraps and the column headers are no longer smushed together.

[Webservice](https://github.com/dockstore/dockstore/commits/66a9a38) - 66a9a38

[UI](https://github.com/dockstore/dockstore-ui2/commits/f37c36c3) - 2.8.4-117-gf37c36c3

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/a77a2fb) - 1.11.3-111-ga77a2fb

galaxyParsingLambdaVersion: 0.0.6
