### ISSUE TITLE
CLI should validate SHA256 file checksums

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4464]
**Is your feature request related to a problem? Please describe.**
With #4424, Dockstore will be returning sha256 checksums in 1.12. CLI is looking for sha-1 checksums, which Dockstore used to return.

**Describe the solution you'd like**
CLI should look for SHA=256 checksums

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1912)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1912
┆sprint: Seabright Sprint 78- Flotsam
┆taskType: Story

**Comment by svonworl** [comment]
Verified done, using an instrumented dev build to confirm that the CLI receives and verifies SHA-256 hashes.
