### ISSUE TITLE
UI issue: Workflow not displaying in collection

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#4467]
**Describe the bug**
The king-WDL Dockstore entry says that it has been added to the "UWGAC..." collection (https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/king-wdl:assoc-agg?tab=info). 

However, when I look at the collection in the bdcatalyst organization, I do not see it listed: https://dockstore.org/organizations/bdcatalyst/collections/UWGACAncestryRelatedness

I confirmed that Ash could not see it on their system. 

**Expected behavior**
I would like for king-wdl to be visible in the collection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 11.6
 - Browser : Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
 - UI version: 2.8
 - Webservice version: 1.11.5??
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1913)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1913
┆Sprint: Sprint 71- Xenacanthus shark
┆Issue Type: Story

**Comment by garyluu** [comment]
Title says UI issue, tag says web-service...is this for both, unknown, or...?

**Comment by denis-yuen** [comment]
Not sure, I just confirmed that the webservice response doesn't include the workflow

**Comment by garyluu** [comment]
Not a UI issue. Reviewer should check that adding an entry (with and without version) to a collection is possible and then it's automatically removed when the version/entry is deleted (kind of difficult to delete version, can use hosted workflows).  As a bonus, check that removing an entry (with and without version) from a collection does NOT delete the entry/version

**Comment by coverbeck** [comment]
Logged 4 new issues in verifying this: #4511, #4512, and #4513, and #4514. :)

* Added an entry, with and without version, to a collection. Worked. Then removed each from collection. Neither entry nor version was deleted.
* Added entry with version to collection, then deleted version. Collection no longer showed version.
* Tried deleting an entry that was in collection, but couldn't. :) Can't delete hosted entry (logged issue), and non-hosted entries can only be deleted if they're stubbed, but you can't stub a published entry. If there's a way I'm missing short of going into the DB, let me know.

[Webservice](https://github.com/dockstore/dockstore/commits/8f17415) - 8f17415

[UI](https://github.com/dockstore/dockstore-ui2/commits/4976846a) - 2.8.2-69-g4976846a

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4) - dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/404ae01) - 1.11.1-70-g404ae01
