### ISSUE TITLE
Link to DOI from ORCID work created by Dockstore does not take you to Zenodo

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4478]
**Describe the bug**
If you click the link to the DOI from an ORCID work created by Dockstore, it does not take you to Zenodo; it opens the same ORCID page on a new tab.

**To Reproduce**
1. Create a work on ORCID via Dockstore UI via Snapshot/DOI/Export to ORCID dialog
2. Go to your ORCID page and find the created work
3. Click on the DOI link.
4. New tab opens on the same page

**Expected behavior**
It should take you to Zenodo

**Screenshots**

Screenshot showing relative path in inspector:

![Screen Shot 2021-09-27 at 10 16 05 AM](https://user-images.githubusercontent.com/1049340/134957906-e022f6a4-44a8-44dc-b2de-d789f08de638.png)

**Additional context**

* The links in the UI to DOI are prefaced with "https://doi.org"... 
* The versions table in our DB does not store the full url, but is confusingly called doiurl. At least I don't think it's a URL, seems like a URI
* [Suspect code](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ORCIDHelper.java#L68) given the above, although it might be more complicated than that.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1919)
┆friendlyId: DOCK-1919
┆sprint: Seabright Sprint 75- Crush
┆taskType: Story

**Comment by garyluu** [comment]
Tried export to orcid with https://dev.dockstore.net/my-workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_cwl 

The link in my orcid account matches the zenodo badge in the versions column
