### ISSUE TITLE
Link to install CLI does not take you to CLI installation page

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4485]
**Is your feature request related to a problem? Please describe.**
The Dockstore web site's link to install the CLI takes you to a page that doesn't tell you how to install the CLI.

In the screenshot, clicking on the "Dockstore CLI" link takes you to a [documentation page](https://docs.dockstore.org/en/stable/launch-with/launch.html#dockstore-cli), which doesn't tell you how to install the CLI.

The second link, "configuration file", takes you to the Quickstart which **does** have installation instructions. 

**Describe the solution you'd like**
There should be one link in that sentence, and it should take you to Quickstart. The sentence should probably be reworded, given the previous sentence suggestion.

**Additional context**
Slack discussion [here](https://app.slack.com/archives/C16ET3CF4/p1633131493440600)

![Screen Shot 2021-10-01 at 4 56 44 PM](https://user-images.githubusercontent.com/1049340/135696834-3620bcfe-e9cc-4488-b619-3e4e548b116c.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1924)
┆fixVersions: Dockstore 1.11.X
┆friendlyId: DOCK-1924
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by aofarrel** [comment]
Renamed to avoid confusion with https://github.com/dockstore/dockstore/issues/4486

**Comment by coverbeck** [comment]
Confirmed on staging that there is now only one link, and it takes you to the quick start page.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.12) - 1.11.12

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.5) - 2.8.5

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2.1) - 1.11.2.1
