### ISSUE TITLE
Wrong commands to install openJDK

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4486]
**Describe the bug**
Our quickstart says...

```
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk11
java -version
```
[This isn't valid syntax as of early 2021](https://github.com/Homebrew/discussions/discussions/902#discussioncomment-1239464).

Furthermore, if you do brew install, openjdk does not become the default version of Java. There are instructions on how to do this, but they are presented as only being needed if you do not use homebrew at all.

**Expected behavior**
The code block should probably be something like
```
brew tap AdoptOpenJDK/openjdk
brew install adoptopenjdk11
unset JAVA_HOME
export JAVA_HOME=`/usr/libexec/java_home -v 11`
java -version
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1925)
┆friendlyId: DOCK-1925
┆sprint: Sprint 74- Aquaman
┆taskType: Story

**Comment by chmreid** [comment]
Documentation written as an escaped Markdown string in a Javascript variable in a file deep in an application directory structure? Yuck.
