### ISSUE TITLE
Generated Java OpenAPI createCollection() and updateCollection() methods fail

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4489]
When using the Java OpenAPI API to programmatically create/update a collection, the generated Java OpenAPI methods io.dockstore.openapi.client.api.OrganizationsApi.createCollection and io.dockstore.openapi.client.api.OrganizationsApi.updateCollection both throw a MessageBodyProviderNotFoundException.  The equivalent swagger Java methods work properly.

Charles suggested that this is because of a missing @Consumes("application/json") annotation on the methods, and he was correct.

This issue will be fixed in #4476 

**To Reproduce**
1. Download develop and build webservice.
2. Create a program that correctly invokes one of the above methods.

**Expected behavior**
The above methods correctly create/update a collection.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1927)
┆friendlyId: DOCK-1927
┆sprint: Sprint 72-Yellowspotted Catsha
┆taskType: Story

**Comment by coverbeck** [comment]
Confirmed that I can invoke both endpoints successfully from https://dev.dockstore.net/api/static/swagger-ui/index.html#/

[Webservice](https://github.com/dockstore/dockstore/commits/193ca8b) - 193ca8b

[UI](https://github.com/dockstore/dockstore-ui2/commits/f38844a9) - 2.8.2-103-gf38844a9

[Compose Setup](https://github.com/dockstore/compose_setup/commits/136e5c5) - 136e5c5

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6552d96) - 1.11.1-101-g6552d96

galaxyParsingLambdaVersion: 0.0.6
