### ISSUE TITLE
Multiple Entry versions in Collection = multiple listings of Collection in Entry Page sidebar

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4490]
When you add N versions of the same entry to a Collection, then view the entry's page, the Collection will appear N times in the "Collections" listing on the right side of the page. 

Will be fixed in #4476

**To Reproduce**
1. Create an approved organization.
2. Add a Collection.
3. Add multiple versions of an Entry to the Collection.
4. Go to the Entry's page, and view the "Collections" listing part way down on the right side.

**Expected behavior**
The Collection should be listed no more than once on the Entry page, no matter how many versions have been added to the Collection.  Preferably, this is implemented in the webservice.

**Screenshots**
![dups_1](https://user-images.githubusercontent.com/88108675/136316234-2d74c8c2-dad3-4177-ac09-8554ff6f6e2b.JPG)
![dups_2](https://user-images.githubusercontent.com/88108675/136316240-7289456b-bb96-4f91-98b5-adb5cd94d3a8.JPG)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/24d67e0) - 24d67e0

[UI](https://github.com/dockstore/dockstore-ui2/commits/c23d1890) - 2.8.2-67-gc23d1890

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4) - dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/04f3975) - 1.11.1-68-g04f3975

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1928)
┆friendlyId: DOCK-1928
┆sprint: Sprint 72-Yellowspotted Catsha
┆taskType: Story

**Comment by garyluu** [comment]
Added multiple versions to the same collection which works
