### ISSUE TITLE
Some entries' Files show full paths (which get cut off), others show just basename (which is preferable)

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4491]
**Describe the bug**
Some Dockstore entries show the full path for their files, which results in them getting quickly getting cut off and no longer showing useful information. ~~I think this might be the result of an older UI design getting grandfathered in, as the ones I see it in are some of our classic workflows such as the UM Aligner.~~ There are definitely some inconsistencies among different entries but it's not related to when the workflow was uploaded; see comment below.

**To Reproduce**
Most WDLs and CWLs don't seem have this but it can be seen [on this CWL](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_cwl:1.32.0?tab=files) and [this WDL](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl:1.32.0?tab=info). This two are synced with the GitHub app so I can't try refreshing them.

**Expected behavior**
Our UI should be consistent across workflows, and ideally should go with the "new" style of just showing the filename instead of the full path.

**Screenshots**
<img width="969" alt="screen_shot_2021-10-05_at_11 18 42_am" src="https://user-images.githubusercontent.com/27784612/136458705-939b1409-cc86-449b-99c2-8bf15200cc33.png">

**Desktop (please complete the following information):**
 - Present in production and staging
 - Browser-agnostic

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1929)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-1929
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by aofarrel** [comment]
I think my earlier theory that this is an older UI getting grandfathered in is wrong. It seems [manually added workflows](https://dockstore.org/workflows/github.com/DataBiosphere/toolbox/CRAM_md5sum_cwl:1.30.0?tab=info) have basenames while github app/dockstore.yml workflows have the full path.

**Comment by aofarrel** [comment]
.dockstore.yml workflows can also have this, even if there is only one test parameter file for the entry. https://dockstore.org/workflows/github.com/broadinstitute/gatk/cnv_somatic_panel_workflow:4.2.0.0?tab=files
<img width="902" alt="Screenshot 2021-12-14 at 11 41 31 AM" src="https://user-images.githubusercontent.com/27784612/146068204-c564bbcb-e452-4078-a6a5-38419aecde16.png">

**Comment by aofarrel** [comment]
Actually, considering the .dockstore.yml entry should only grant this one wdl, but there's two in the entry, this entry might be otherwise malformed? If this isn't malformed, then we have a case where one WDL uses ../ notation while another uses the full path.
<img width="894" alt="Screenshot 2021-12-14 at 11 41 59 AM" src="https://user-images.githubusercontent.com/27784612/146068297-dd15147c-53f7-41ed-bf3f-d7d68f1ce144.png">

**Comment by hyunnaye** [comment]
Fixed with https://github.com/dockstore/dockstore-ui2/pull/1702
