### ISSUE TITLE
Website title ought to be more specific

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4493]
**Is your feature request related to a problem? Please describe.**
Trying to use your browser's history feature with Dockstore is a hassle, as all workflow pages will say "Dockstore | Workflow" instead of the name of the actual workflow. Compared to other websites such as the Github entry at the top, our titles are not informative.

<img width="961" alt="Screen Shot 2021-10-07 at 3 39 48 PM" src="https://user-images.githubusercontent.com/27784612/136471815-7121f5d6-612b-42c4-ae20-3fb343c9fbab.png">

This is also a problem for people who use multiple tabs or windows as you cannot tell which one relates to which workflow at a glance. The first of these tabs is the UWGAC Null Model WDL, the other tab is the CRAM MD5sum CWL. There's no way to tell which is which at a glance.
<img width="422" alt="Screen Shot 2021-10-07 at 3 43 14 PM" src="https://user-images.githubusercontent.com/27784612/136472178-42a43318-b4da-42ac-8017-7317751cd600.png">

**Describe the solution you'd like**
I gave this a little more time thinking than I'd care to admit, then realized that a potential answer was right in front of me. Here's the tabs I have open at the moment.

<img width="1435" alt="Screen Shot 2021-10-07 at 3 28 39 PM" src="https://user-images.githubusercontent.com/27784612/136470880-f0ad4389-4b4c-4a06-a0c2-16090fa47e64.png">

All of these websites use their favicon† to communicate what the website is, and use the title to communicate what the specific content is. The Github tabs name the repo, Terra names the workspace, Jira names the board I'm looking at, Google Docs and Slides list the title of the document and presentation respectively, and Seven Bridges has the name of the workspace.

†This is actually a bit of a problem for some BioData Catalyst websites including BDC!Seven Bridges, as they all use the same favicon. But we have a very unique icon and, as far as I know, will never be needing a BDC favicon.

**Describe alternatives you've considered**
Something like "UM Aligner | Dockstore" would work if we really don't want to remove the Dockstore part.

Something like "Dockstore | Workflow | UM Aligner" would only be helpful for going through browser history, as anyone with a respectable number of tabs would just see "Dockstore" with the unique part getting cut off.

<img width="260" alt="Screen Shot 2021-10-07 at 3 40 46 PM" src="https://user-images.githubusercontent.com/27784612/136472014-77cb5d86-1821-49ce-9308-73f47925cd16.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1930)
┆Issue Number: DOCK-1930
┆Sprint: Sprint 73- Zebra shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
Confirmed that public workflows and public tools have unique titles on dev.

[Webservice](https://github.com/dockstore/dockstore/commits/ba5f42c) - ba5f42c

[UI](https://github.com/dockstore/dockstore-ui2/commits/48e7b23d) - 2.8.2-91-g48e7b23d

[Compose Setup](https://github.com/dockstore/compose_setup/commits/00df5f2) - 00df5f2

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/0c853bc) - 1.11.1-92-g0c853bc
