### ISSUE TITLE
500 create cloud instance - general constraint mechanism

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4496]
**Describe the bug**
When creating a duplicate cloud instance, it should not result in a  500

**To Reproduce**
1. Try to create a duplicate cloud instance (/api/users/59141/cloudInstances)
2. See something like:
```
ERROR [2021-09-28 22:55:03,186] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR: duplicate key value violates unique constraint "unique_user_instances"→  Detail: Key (url, user_id, partner)=(https://notebooks.firecloud.org/proxy/google/v1/apps/firecloud-cgl/something/galaxy, 59141, GALAXY) already exists.
```

**Expected behavior**
Not a 500 (maybe bad request?) and a more friendly message

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1934)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1934
┆Sprint: Sprint 72-Yellowspotted Catsha
┆Issue Type: Story

**Comment by NatalieEO** [comment]
[Webservice](https://github.com/dockstore/dockstore/commits/c5e85f0) - c5e85f0

[UI](https://github.com/dockstore/dockstore-ui2/commits/d10573de) - 2.8.2-83-gd10573de

[Compose Setup](https://github.com/dockstore/compose_setup/commits/00df5f2) - 00df5f2

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/351cfc2) - 1.11.1-86-g351cfc2
No longer a 500
```
{
  "code": 409,
  "message": "Your request has been blocked by a database constraint \"unique_user_instances\". Please change your request and try again"
}
```
