### ISSUE TITLE
500 on specific tool refresh

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4497]
**Describe the bug**

**To Reproduce**
1. Try to refresh a tool (GET /containers/17072/refresh). Might need to use that specific tool
2. See something like
```
ERROR [2021-09-30 18:32:22,251] io.dockstore.webservice.resources.DockerRepoResource: Could not parse Git URL: Unable to refresh tool!
```

**Expected behavior**
If it's a tool that already exists, there should be no reason for the Git URL to be unparseable.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1933)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1933
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Is there anything special about the tool?
