### ISSUE TITLE
Add WES instructions to Launch Tab

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4500]
**Is your feature request related to a problem? Please describe.**
It's not easy to figure out how to run a workflow against a WES endpoint.

**Describe the solution you'd like**
The launch tab in the UI, e.g., [here](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=launch), should have an additional section describing how to launch the workflow using WES. Ideally, you could cut and paste it, fill in the url and auth, and you're off and running. Maybe there's an option with a shell script where the url, auth, and test parameter file are params.

**Additional context**
Can wait until our CLI WES support has matured.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1936)
┆epic: Dockstore CLI AGC support
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1936
┆sprint: SEAB 81- Jacques
┆taskType: Story

**Comment by coverbeck** [comment]
This might useful for a demo; tentatively proposing for 1.12, but we should revisit during our 1.12 triage.

**Comment by Richard-Hansen** [comment]
> This might useful for a demo; tentatively proposing for 1.12, but we should revisit during our 1.12 triage.

(Side note) Since we removed passing in bearer tokens / profiles as program arguments for the WES portion of the CLI, I'm not certain how we would choose to show this info. Perhaps a two-fold  help block? One to show the WES section of the CLI config file and one for the remaining CLI command. ie.:

> Add the following section to your dockstore-cli config file:
> ```
> [WES]
> ...
> ...
> ...
> ```
> Launch the workflow with:
> ```
> dockstore workflow wes launch ...
> ```

Not sure, just throwing out ideas

**Comment by coverbeck** [comment]
Ah, good point. Another idea, instead or as well, would be a link to the doc for configuring WES in your config file.
