### ISSUE TITLE
CLI cannot run WDL if cwltool is not on path

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4503]
**Describe the bug**
Dockstore relies on cwltool to run CWLs, but it turns out it also relies on it to run WDLs. We refer to cwltool as an optional component in our quick start installation instructions, not as a dependency, so it shouldn't be getting used at all. It seems that dockstore is trying to get the version of cwltool regardless of what is actually being run, resulting in an error.

**To Reproduce (not recommended)**
1. Have hardware issues with your work laptop and drop it off at UCSC ITS -- my issue involved the screen and USB-C ports, but feel free to get creative here
2. Realize your backup only has the contents of things like /Documents, not any actual programs
3. Install the Dockstore CLI on your loaner laptop
4. Don't install cwltool, as you generally work with WDLs
5. Attempt to run a WDL

**Expected behavior**
The WDL to run.

**Actual behavior**
CBSELoaPD96HV29:~ aofarrel$ dockstore tool launch --entry Documents/GitHub/analysis_pipeline_WDL/assoc-aggregate/assoc-aggregate.wdl --json Documents/GitHub/analysis_pipeline_WDL/assoc-aggregate/assoc-aggregate-local-fast.json 
[##################################################] 100%
problems running command: cwltool --version
15:06:06.869 [main] ERROR io.dockstore.client.cli.ArgumentUtility - java.lang.RuntimeException: problems running command: cwltool --version
	at io.cwl.avro.Utilities.executeCommand(Utilities.java:96)
	at io.github.collaboratory.cwl.cwlrunner.CWLToolWrapper.checkForCWLDependencies(CWLToolWrapper.java:39)
	at io.dockstore.client.cli.Client.checkForCWLDependencies(Client.java:459)
	at io.dockstore.client.cli.nested.CwltoolLauncher.initialize(CwltoolLauncher.java:32)
	at io.dockstore.client.cli.nested.BaseLanguageClient.launchPipeline(BaseLanguageClient.java:156)
	at io.github.collaboratory.cwl.CWLClient.launch(CWLClient.java:289)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1257)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:1217)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:296)
	at io.dockstore.client.cli.Client.run(Client.java:720)
	at io.dockstore.client.cli.Client.main(Client.java:619)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: cwltool --version (Exit value: -559038737)
	at io.cwl.avro.Utilities.executeCommand(Utilities.java:92)
	... 10 more

**Desktop (please complete the following information):**
 - Mac OS Big Sur
 - Version: 1.11

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1938)
┆Issue Number: DOCK-1938
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
I think you need to add `--descriptor WDL` -- it's assuming it's CWL, your file extension not withstanding.

```
~/git/dockstore/dockstore$ dockstore tool launch

 ____             _        _
|  _ \  ___   ___| | _____| |_ ___  _ __ ___
| | | |/ _ \ / __| |/ / __| __/ _ \| '__/ _ \
| |_| | (_) | (__|   <\__ \ || (_) | | |  __/
|____/ \___/ \___|_|\_\___/\__\___/|_|  \___|

---------------------------------------------
See https://www.dockstore.org for more information

Usage: dockstore tool launch --help
       dockstore tool launch [parameters]

Description:
  Launch an entry locally.

Required parameters:
  --entry <entry>                     Complete entry path in Dockstore (ex. quay.io/collaboratory/seqware-bwa-workflow:develop)
   OR
  --local-entry <local-entry>         Allows you to specify a full path to a local descriptor instead of an entry path

Optional parameters:
  --json <json file>                  Parameters to the entry in Dockstore, one map for one run, an array of maps for multiple runs
  --yaml <yaml file>                  Parameters to the entry in Dockstore, one map for one run, an array of maps for multiple runs
  --descriptor <descriptor type>      Descriptor type used to launch workflow. Defaults to CWL
  --local-entry                       Allows you to specify a full path to a local descriptor for --entry instead of an entry path
  --wdl-output-target                 Allows you to specify a remote path to provision output files to ex: s3://oicr.temp/testing-launcher/
  --uuid                              Allows you to specify a uuid for 3rd party notifications
  --ignore-checksums                  Allows you to ignore validating checksums of each downloaded descriptor

**Comment by aofarrel** [comment]
On my previous laptop, which had cwltool installed, I don't believe I ever used --descriptor, but I might be misremembering.

That said I did forget to use --local-entry instead of --entry, and --local-entry (without --descriptor) does seem to be running cromwell without throwing the error. If it turns out my using --entry was the issue as it didn't know how to parse the local path and therefore defaulted to cwl, that's on me and this can be closed.

**Comment by coverbeck** [comment]
I'm going to close then.

One could argue that it should first check that the entry exists and fail there. But the flip-side would be why check for an entry if you don't have the runner installed. :)
