### ISSUE TITLE
Deleting a hosted entry version fails if there is no default version

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4511]
**Describe the bug**
I got a 500 error attempting to delete a hosted entry version for a hosted workflow that does not have a default version.

**To Reproduce**
1. Go to a hosted workflow in My Workflows without a default version. For me, it's [this one](https://dev.dockstore.net/my-workflows/dockstore.org/coverbeck/helloworld).
2. Delete a version in the UI
3. See error

**Expected behavior**
The version should get deleted.

**Additional context**
Suspect code is [here](https://github.com/dockstore/dockstore/blob/d37e3b1e658543e9934b3cd03e28348866530261/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractHostedEntryResource.java#L403).

I don't know how that workflow got into that state; normally a workflow should have a default.

[Webservice](https://github.com/dockstore/dockstore/commits/8f17415) - 8f17415

[UI](https://github.com/dockstore/dockstore-ui2/commits/4976846a) - 2.8.2-69-g4976846a

[Compose Setup](https://github.com/dockstore/compose_setup/commits/dfb11f4) - dfb11f4

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/404ae01) - 1.11.1-70-g404ae01

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1944)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-1944
┆Sprint: 106 - Don River
┆Issue Type: Story

**Comment by garyluu** [comment]
It's possible that old workflows do not have a default version
