### ISSUE TITLE
Disable username input field if user isn't allowed to change username 

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4537]
**Describe the bug**
Noticed that even though I'm not allowed to change my username, I can still type in the username input field. Should make this input field disabled or read-only if the user isn't allowed to change their username.

![image](https://user-images.githubusercontent.com/25287123/138900653-9240a66c-003a-47da-937f-1ed3dc52015f.png)

**To Reproduce**
1. Go to Accounts page
2. Click on the Dockstore Account Controls tab
3. Assuming that the user isn't allowed to change their username, observe that the Update Username button is disabled but the input field isn't

**Expected behavior**
Username input field should be disabled or readonly if the user isn't allowed to change their username

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1959)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1959
┆sprint: SEAB 83- Luca
┆taskType: Story

**Comment by denis-yuen** [comment]
related to https://ucsc-cgl.atlassian.net/browse/SEAB-4116
