### ISSUE TITLE
Tool registration error is obscured by its own window

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4538]
**Describe the bug**
If you error out when registering a tool, an error appears under the registration window. When you close the registration window the error message disappears, so in order to see the error you would likely need to hide some elements.

**To Reproduce**
I did this attempting to manually register my fork of Stephanie Gogarten's tool. I don't have access to her DockerHub, which is probably the error.

**Expected behavior**
* The red error message at the top of the page, the one that is obscured, should not trigger when another window is covering it 
* The error message at the bottom of the page, the one that is actually visible, should be more helpful or show the contents of the red error message

**Screenshots**
<img width="1241" alt="Screen Shot 2021-10-26 at 10 51 28 AM" src="https://user-images.githubusercontent.com/27784612/138934753-3511e104-24f5-4a59-a5d3-e4b733410a8f.png">

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
- [Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8
- [UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2
- [Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11
- [Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1960)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10565/Screen+Shot+2021-12-09+at+4.58.21+PM.png">Screen Shot 2021-12-09 at 4.58.21 PM.png</a>
┆friendlyId: DOCK-1960
┆sprint: Sprint 74- Aquaman
┆taskType: Story

**Comment by garyluu** [comment]
The error message is actually displayed in the dialog/modal itself.

Depending on the screen size, it's still slightly visibile even when scrolled all the way down
![image](https://user-images.githubusercontent.com/24548904/141317272-96f3d465-f15c-431d-adb0-d9b9e26934de.png)

On another note, It's a little odd though that the scrollbars aren't visible in the original screenshot

Probably going to make  the error message always visible in the dialog (fixed position like the header)

**Comment by NatalieEO** [comment]
> On another note, It's a little odd though that the scrollbars aren't visible in the original screenshot

I think macs don't show the scrollbar unless you are actively scrolling

**Comment by aofarrel** [comment]
> > On another note, It's a little odd though that the scrollbars aren't visible in the original screenshot
> 
> I think macs don't show the scrollbar unless you are actively scrolling

This is usually the case for modern Mac OS, yep. If you have an iThing you'll note that this usually is the case with them too.
