### ISSUE TITLE
Improperly formatted tools link to a non-existent commit

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4540]
## Describe the bug 
This is one of those bugs that seems to only happen if something else goes wrong, but it may indicate an underlying issue and it does make things confusing for users and obscures issues, so I think it is still worth looking into.

A malformed tool entry points to a GitHub commit ID that does not exist. Even curiouser, it consistently points to the _same_ non-existent commit ID.

## To Reproduce
1. Clone https://github.com/UW-GAC/simulate_phenotypes
2. Within Dockstore, in my tools, register "Create tools on remote sites" (second option)
3. Register as normal, but use any Docker Hub image you have Dockstore access to in order to get pass the usual permissions error -- I used ashedpotatoes/cheers2019
<img width="1228" alt="Screen Shot 2021-10-26 at 10 51 13 AM" src="https://user-images.githubusercontent.com/27784612/138953975-63ce8d5b-61ef-487e-8946-baae3cb02e90.png">
4. Add version tag v0.2.2-cwl, which points to a valid GitHub tag (https://github.com/aofarrel/simulate_phenotypes/releases/tag/v0.2.2-cwl), but not a valid Docker Hub tag.
<img width="583" alt="Screen Shot 2021-10-26 at 12 57 49 PM" src="https://user-images.githubusercontent.com/27784612/138952793-efcbf8a5-9469-4d40-ab34-b2956af4b7db.png">
5. Observe that you end up with a commit ID (634f31...) that does not exist
<img width="1030" alt="Screen Shot 2021-10-26 at 12 58 07 PM" src="https://user-images.githubusercontent.com/27784612/138952842-ed093bf9-04f8-4a7a-8682-90d19c11e689.png">
6. Click the GitHub tag link and get taken to that commit that indeed does not exist; GitHub will 404 if you click it
7. Go back to the Dockstore page, go to info, and click the other link instead -- this time, it does correctly take you to the v0.2.2-cwl tag on GitHub
<img width="906" alt="Screen Shot 2021-10-26 at 1 16 15 PM" src="https://user-images.githubusercontent.com/27784612/138954458-79b09916-5e4f-4ae2-a6c3-13c2f43b032f.png">

## 634f31, consistently
The exact same commit ID (634f31...) is also used for the person who owns the original repo, provided they set up tags the same way I did in the screenshots. They are taken to [the same commit ID](https://github.com/UW-GAC/simulate_phenotypes/tree/634f31af26106a4e22b634187aadcbf8b87edb69). 

According to the owner of the original repo, there was no rebasing or squashed commits. There may have been a branch called v0.2.2-cwl which has since been deleted, but that shouldn't be causing us to point to non-existent commits.

## Dockstore examples
* https://dockstore.org/containers/registry.hub.docker.com/uwgac/simphen/allele_freq:v0.2.2-cwl?tab=versions
* https://dockstore.org/containers/registry.hub.docker.com/ashedpotatoes/cheers2019/allele_freq:latest?tab=info

## Expected behavior
Instead of taking users to a GitHub commit that doesn't exist, we should take them to a GitHub commit that does exist. Even if this only happens when an incorrect Docker Hub tag is being referenced somewhere -- and maybe that deserves an error message of some sort -- it doesn't make sense for the GitHub side to be broken.

## Additional context
* Chrome
* [Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8
* [UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2
* [Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11
* [Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1962)
┆fixVersions: Dockstore 1.11.X
┆friendlyId: DOCK-1962
┆sprint: Sprint 75- Barbossa
┆taskType: Story

**Comment by garyluu** [comment]
From how we implement the commit ID, it looks like: https://api.github.com/repos/sbg/sbg_dockstore_tools/git/refs/tags/v1.0.0 has the object with type commit 
https://api.github.com/repos/UW-GAC/simulate_phenotypes/git/refs/tags/v0.2.2-cwl has the object with type tag

First one SHA could be put into https://github.com/sbg/sbg_dockstore_tools/tree/a951acb0eb254f928d028b1bb4718d0e4d1e9ffe which works.
2nd one SHA can't be put into https://github.com/UW-GAC/simulate_phenotypes/tree/634f31af26106a4e22b634187aadcbf8b87edb69

Dockstore needs to somehow arrive at https://api.github.com/repos/UW-GAC/simulate_phenotypes/git/tags/634f31af26106a4e22b634187aadcbf8b87edb69 and get the commit ID from the object there which would result in https://github.com/UW-GAC/simulate_phenotypes/tree/70a605539a1ce2683af7d0a1c1d01e8f5b84a59c

**Comment by garyluu** [comment]
if getCommitID function got changed to
```
            repo = github.getRepository(repositoryId);
            // Why are we getting all branches and tags only to narrow them down to the specific one we want?
            GHRef[] refs = getBranchesAndTags(repo);

            for (GHRef ref : refs) {
                String reference = StringUtils.removePattern(ref.getRef(), "refs/.+?/");
                if (reference.equals(version.getReference())) {
                    // Sometimes the object isn't of commit type for some reason
                    if ("commit".equals(ref.getObject().getType())) {
                        return ref.getObject().getSha();
                    }
                    if ("tag".equals(ref.getObject().getType())) {
                        return repo.getTagObject(ref.getObject().getSha()).getObject().getSha();
                    }
                    return null;
                }
            }
```            
it would work, but it does another call, needs a bunch of null checks, and doesn't explain why

**Comment by coverbeck** [comment]
Looks good to me on staging.

@aofarrel Thanks for the detailed instructions! If you want to verify it too, on staging.dockstore.org, that would be great!

**Comment by coverbeck** [comment]
I verified incorrectly. It doesn't work for an annotated tag. It shows no link at all for me in that case.

**Comment by coverbeck** [comment]
This is working for me in 1.11.10. I made sure this time to test with an annotated tag.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.10) - 1.11.10

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.4) - 2.8.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2) - 1.11.2
