### ISSUE TITLE
Dockstore can find a CWL, but not its test file

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4541]
**Describe the bug**
I've only observed this in the context of https://github.com/dockstore/dockstore/issues/4540, so there is a chance this is a bug-within-a-bug and not a separate issue. As is always the case in science, more testing is needed.

It is possible to have a Dockstore entry wherein the Dockerfile and CWL are found with no problem, but Dockstore, but not the test descriptor file, and this persists even if:
* allele_freq.test.json is moved from the test directory into the same directory as allele_freq.cwl
* allele_freq.test.json is renamed allele_freq.test.yml
* Both of the above happen and the Dockstore entry is changed appropriately (ie it still can't find it in /tools/allele_freq.test.yml if you tell it is in /tools/allele_freq.test.yml)
* This happens even if you move things around on different branches, have different default versions, etc

**To Reproduce**
See #4540. 
https://dockstore.org/containers/registry.hub.docker.com/ashedpotatoes/cheers2019/allele_freq:v0.2.2-cwl?tab=info

**Expected behavior**
If a CWL can be found, its test file should also be found. Even if the entry is malformed, it should be consistently malformed rather than giving the appearance of being half-functional.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1963)
┆Fix Versions: Dockstore 1.11.X
┆Issue Number: DOCK-1963
┆Sprint: Sprint 74- Aquaman
┆Issue Type: Story

**Comment by garyluu** [comment]
Assignee should pick up above closed PR. Double-check the above PR's fix works, then add a test.

**Comment by aofarrel** [comment]
It turns out this can also result in the Dockerfile going missing, although in the Dockerfile's case it can be fixed by a hard reload of the my-tools webpage.
