### ISSUE TITLE
Autocomplete commands on tab in CLI

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#455]
The CLI should autocomplete commands when tab is pressed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-459)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-459
┆Sprint: Backlog
┆Issue Type: Story

**Comment by agduncan94** [comment]
http://www.tldp.org/LDP/abs/html/tabexpansion.html

**Comment by denis-yuen** [comment]
There's a SeqWare implementation of this already which installs a Bash completion script via `seqware --completion` This was tested with 1.2.0-alpha.1-SNAPSHOT.

Also attaching a script to give an idea of structure (an ideal implementation would also handle parameters)
`_seqware()

{

   local cur prev opts 

   COMPREPLY=()

   cur="${COMP_WORDS[COMP_CWORD]}"

   prev="${COMP_WORDS[COMP_CWORD-1]}"

   opts="--help --verbose --version --debug --metadata --completion annotate query bundle copy create files study workflow workflow-run checkdb dev"

   #

   # Nested commands

   #

   case "${prev}" in

   annotate)

      local nestedOpts="experiment file ius lane processing sample sequencer-run study workflow workflow-run"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   query)

      local nestedOpts="experiment file ius lane processing sample sequencer-run study workflow workflow-run"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   bundle)

      local nestedOpts="dry-run install install-dir-only launch list package"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   create)

      local nestedOpts="experiment ius lane sample sequencer-run study workflow workflow-run"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   files)

      local nestedOpts="report refresh"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   study)

      local nestedOpts="list"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   workflow)

      local nestedOpts="ini list report schedule"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   workflow-run)

      local nestedOpts="cancel launch-scheduled propagate-statuses retry reschedule stderr stdout report watch ini delete"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   dev)

      local nestedOpts="map files2workflowruns"

      COMPREPLY=( $(compgen -W "${nestedOpts}" -- ${cur}) )

      return 0

      ;;

   *)

   ;;

   esac

   

   if [ "${prev}" == "seqware" ] 

      then

         COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )

   fi

   return 0

}

complete -F _seqware seqware`
