### ISSUE TITLE
Our handling of bad URLs doesn't provide information, can lead to infinite loop

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4553]
Not sure if I should classify this as a bug or a feature request, feel free to modify as appropriate.

**Describe the bug**
We currently direct users to the Dockstore homepage when they attempt to resolve an invalid URL. This redirect is immediate and no error is shown. In my opinion, not showing an error is a problem in and of itself as the user does not know how they got to the homepage and it leaves the user with no idea why their old URL did not work -- Unauthorized? Deleted entry? Entry never existed? There's no indication of which of these is the case.

I think an argument can be made for this redirect, but there's another side effect: The browser's back button will now loop you infinitely as you cannot mash it quickly enough to escape the direct.

Of course, the user can click and hold (or some other equivalent) to go back more than one page, but it's still a mildly annoying experience.

**To Reproduce**
1. Go to an invalid URL, such as https://dockstore.org/containers/quay.io/aofarrel/aaaaaaaaaaaaaaaaaaaaaaaaaaaa
2. Immediately get redirected
3. Hit the back button
4. Immediately get redirected
5. etc

**Expected behavior**
When a URL is invalid for some reason for another, I think we should do one of the following:
* Leave them on the same URL and throw an error explaining why it is invalid -- the error message should be different if someone tried to access a my-workflows URL when not logged in as the user who owns that workflow versus the URL not being valid for anyone because it just plain does not exist
* Leave them on the same URL, throw an error explaining why it is invalid, hold for a few seconds, *then* redirect them to the homepage
* Immediately redirect them to a specific error page instead of the homepage (would still have infinite loop problem but would at least provide some context)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1974)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1974
┆sprint: 94- Vampire Pleco
┆taskType: Story

**Comment by denis-yuen** [comment]
Probably worth a custom error page.
We may eventually need this if we do permanent delete and there's an argument for it even with soft delete
https://stackoverflow.com/questions/36260839/angular-2-how-to-redirect-to-404-or-other-path-if-the-path-does-not-exist
