### ISSUE TITLE
Github tag conflated with Docker tag, but in reverse, kind of, this isn't a repeat ticket I promise

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4554]
## Describe the bug
In attempting to find a workaround for #4540 and #4541, I found a new bug. It can be seen at https://dockstore.org/containers/registry.hub.docker.com/uwgac/simphen/allele_freqq:0.2.2?tab=versions

## To Reproduce
1. Repeat the setup for #4540 
2. [Create a new tag in the Github repo (0.2.3)](https://github.com/aofarrel/simulate_phenotypes/releases/tag/0.2.3) but [NOT in Docker Hub](https://hub.docker.com/r/uwgac/simphen/tags)
3. Re-register the tool
4. Observe #4541 might appear again, even after refreshing the tool, [as well as the Dockerfile going missing](https://github.com/dockstore/dockstore/issues/4541#issuecomment-956514846) _-- note that other replications did not have the Dockerfile disappear nor the parameter file; this part might not be part of this particular bug_
5. Refresh the my-tools webpage (browser page refresh not tool refresh) to get the Dockerfile back, note that parameter file is still missing _-- again, this may or may not be necessary for replicating_
6. Hit publish anyway and view the public page
7. Observe the exact opposite of #4540's problem -- the github link under Versions is correct, but the github link on the main page is incorrectly pointing to 0.2.2, which does not exist on github

## Result: Main page GitHub link points to tag that does not exist
This link is wrong. In #4540, it was correct. 
<img width="671" alt="Screenshot 2021-11-01 at 12 20 12 PM" src="https://user-images.githubusercontent.com/27784612/139728848-26cac850-53c3-44c0-b3ec-0b5d28a099b8.png">
Be aware that there is a GitHub tag called v0.2.2, but not 0.2.2, and what was said earlier about the original repo having a deleted branch may still be affecting things.

## Inconsistency: Versions page GitHub link points to a valid link
This link is correct. In #4540, it was wrong.
<img width="670" alt="Screenshot 2021-11-01 at 12 20 24 PM" src="https://user-images.githubusercontent.com/27784612/139728866-48b28a01-6082-43b4-a863-fe9399119ebd.png">
Strictly speaking, this is linking to https://github.com/aofarrel/simulate_phenotypes/tree/6e801d49782ee22c358c1b56df845688e5462cf0, not https://github.com/aofarrel/simulate_phenotypes/tree/0.2.3, but that is the commit that is tagged as 0.2.3 so I'll consider that valid.

## Expected behavior
Docker Hub tags should not be conflated with GitHub tags, and coming up with a workaround for #4540 should not result in a new bug that reverses its issue.

## Additional context
- [Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8
- [UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2
- [Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11
- [Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1975)
┆friendlyId: DOCK-1975
┆sprint: Sprint 75- Barbossa
┆taskType: Story

**Comment by garyluu** [comment]
works as far as i can tell:
`git tag -a v1.4 -m "my version 1.4"` and `git push origin v1.4` to make the annotated tag
https://staging.dockstore.org/containers/registry.hub.docker.com/uwgac/simphen/asdf2:1?tab=info
