### ISSUE TITLE
Warn snapshots with HTTP imports

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4560]
**Is your feature request related to a problem? Please describe.**
Snapshots are supposed to be reproducible. Ones with HTTP imports kind of aren't.

**Describe the solution you'd like**
Warning somewhere when viewing a snapshotted version that there's HTTP imports so it may not be reproducible

**Describe alternatives you've considered**
🦗 

**Additional context**
See https://docs.google.com/document/d/1HbyMKKVGP8ELL0dG3Pq_GXDPT22qip5nv3ZgFmi2tK4/edit

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1978)
┆Issue Number: DOCK-1978
┆Sprint: Sprint 74- Aquaman
┆Issue Type: Story

**Comment by coverbeck** [comment]
Confirmed that https://dev.dockstore.net/workflows/dockstore.org/coverbeck/hcatest:9?tab=info has the warning.

[Webservice](https://github.com/dockstore/dockstore/commits/0eae84c) - 0eae84c

[UI](https://github.com/dockstore/dockstore-ui2/commits/8569af25) - 2.8.2-95-g8569af25

[Compose Setup](https://github.com/dockstore/compose_setup/commits/120d9b9) - 120d9b9

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/e26f8b5) - 1.11.1-100-ge26f8b5

galaxyParsingLambdaVersion: 0.0.6
