### ISSUE TITLE
Determine what it takes to support Dockstore development on Apple Silicon Macs

### ISSUE THREAD

**Issue by bvizzier** [dockstore/dockstore#4567]
**Is your feature request related to a problem? Please describe.**
Apple is in the process of migrating to its own ARM-based processors.  

This issue is to determine what modifications, if any, are needed to contribute to the development of Dockstore using an Apple Silicon Mac. 

**Describe the solution you'd like**
Updated documentation on how to contribute to Dockstore development using an Apple Silicon Mac.

**Describe alternatives you've considered**
Mentioning what the status is of Apple Silicon-based Mac support.

**Additional context**
None at this time.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1982)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-1982
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by bvizzier** [comment]
This ticket is related to issue 4535.

**Comment by denis-yuen** [comment]
> MavenMaven version 3.8.4 is the first to support Apple Silicon. Currently, Dockstore recommends Maven 3.8.2.

FWIW, I don't think this is a problem. We currently build with 3.8.4 https://github.com/dockstore/dockstore/blob/develop/.mvn/wrapper/maven-wrapper.properties#L1
