### ISSUE TITLE
Optimize Index Update

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4569]
**Is your feature request related to a problem? Please describe.**
The entire TRS cache can be invalidated too easily. It's relatively expensive to create, we should try to avoid that.

**Describe the solution you'd like**
Address [this TODO](https://github.com/dockstore/dockstore/blob/db15223af216d10633e6fbd08000080d8b60ffde/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/TRSListener.java#L42).

1. Ideally it would just update the one entry, as the TODO says.
2. Additionally, for certain updates, e.g., an entry being added to or removed from a category, the TRS cache doesn't need to updated at all, as categories are not surfaced in TRS.

**Additional context**
Noticed in reviewing #4568; modifying or deleting a collection will invalidate entire TRS cache.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1983)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-1983
┆sprint: Backlog
┆taskType: Story

**Comment by coverbeck** [comment]
TRS cache also gets invalidated if you change a label, which isn't surfaced in TRS response.

**Comment by denis-yuen** [comment]
I'm ok with this, worse case scenario we may be able to just autoscale and spin up more webservices
