### ISSUE TITLE
Refactor label, categories, verified elements

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4580]
**Is your feature request related to a problem? Please describe.**
The 3 of them look near identical from the mockup: 

![image](https://user-images.githubusercontent.com/24548904/142038324-aedc79dc-ce29-4b62-ae59-ebeddcfbe3bc.png)

with near identical intended functionality (clicking on them brings the user to another page)

However, they have different styling and components used (2 are mat-chips, 1 is button).  The labels are missing a hover effect.

**Describe the solution you'd like**
- The 3 components used should be the same (all buttons, all mat-chips, or w/e)
- A minimal number of classes to handle the general look of these elements (the verified one will likely require more for the icon)
- A detailed comment saying when this new style should be used for components (want to avoid someone creating another style for a possible similar but new component)

**Describe alternatives you've considered**
- having the styles linearly grow with the number of components with slight differences in each of them

**Additional context**
https://github.com/dockstore/dockstore-ui2/pull/1390 added the category, going to have to dig around to find what added the labels and verified

Unclear from material 2 what the difference between buttons and chips is but https://m3.material.io/components/chips/guidelines makes it pretty clear that "Multiple chips should appear together in a group, whereas there should be no more than 3 buttons in a single arrangement."  This actually complicates things because although this clearly means labels and categories must not be buttons, the verified button/chip or w/e is unknown.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1990)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1990
┆sprint: Seabright Sprint 77- Eelektrik
┆taskType: Story

**Comment by NatalieEO** [comment]
Well the code is merged and the labels, categories, and verified elements look and work the same as far as I can tell. 
[Webservice](https://github.com/dockstore/dockstore/commits/83de67a) - 83de67a

[UI](https://github.com/dockstore/dockstore-ui2/commits/3e14769a) - 2.8.4-119-g3e14769a

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/920b171) - 1.11.3-113-g920b171

galaxyParsingLambdaVersion: 0.0.6
