### ISSUE TITLE
Register Workflow has a case-sensitive sort for repos

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4583]
**Describe the bug**
The list of repositories when registering a workflow is sorted case-sensitive.

**To Reproduce**
1. Go to My Workflows
2. Click on +
3. Click on Quickly Register Remote Workflows, then Next
4. Specify Github, an org with mixed case repos

**Expected behavior**
It should be case insensitive

**Screenshots**
![Screen Shot 2021-11-17 at 11 05 16 AM](https://user-images.githubusercontent.com/1049340/142265983-9e6b2eb2-312d-41c1-bbd3-06d3a705d208.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.8) - 1.11.8

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.2) - 2.8.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.1) - 1.11.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1993)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-1993
┆sprint: 88 Poseidon
┆taskType: Story

**Comment by denis-yuen** [comment]
capitalized repo names? :frowning:

**Comment by coverbeck** [comment]
> capitalized repo names? 😦

In my defense, it's a fork. :)
