### ISSUE TITLE
Better timestamps in rate limit errors

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4590]
**Is your feature request related to a problem? Please describe.**
As usual, I accidentally hit "refresh organization" instead of "discover existing workflows" and got a slap on the wrist. Problem is, at first glance, I don't really know how long it will last.

_[HTTP 400] OK: Out of GitHub rate limit, please wait til +53866-10-24T21:50Z[Etc/UTC]_

**Describe the solution you'd like**
Human-readable date and time. This could either be "wait X minutes" or it could be "wait until this time."

If we go with "wait until this time" there's some additional considerations:
* If datestamps are necessary, we should take care not to confuse our friends across the pond who use DD/MM/YYYY format instead of MM/DD/YYYY - maybe give the actual month name? 
* UTC time is fine, but it'd be really cool if it was based on user's time zone.

**Describe alternatives you've considered**
Not hitting "refresh organization."

**Additional context**
<img width="1260" alt="Screenshot 2021-11-23 at 1 58 04 PM" src="https://user-images.githubusercontent.com/27784612/143135727-1ccc2d82-31b0-4fbc-9b06-cd613e973212.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1999)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10636">Screenshot 2022-02-04 at 11-25-24 Dockstore My Workflows.png</a>
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-1999
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
![FE7jymYXMAoQRRx](https://user-images.githubusercontent.com/1730679/143465256-c9dc77ab-0601-4b27-ac8c-5df79dbf184f.jpeg)
https://twitter.com/mattl/status/1463357843969609729

**Comment by coverbeck** [comment]
Pretty sure this was addressed by #4364, which I didn't create an issue for. Should be fixed in dev.
