### ISSUE TITLE
Hosted workflow forumUrl (and topic)

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4591]
**Is your feature request related to a problem? Please describe.**
A hosted workflow's forumUrl (and soon to be added topic or other workflow-level properties) should be able to be updated. Right now it doesn't work from the website  (edit button isn't shown) or the API (PUT workflow/{workflowId} disabled on hosted)

**Describe the solution you'd like**
PUT workflow/{workflowId} should work

**Describe alternatives you've considered**
Reconsidering whether or not we need forumUrl on hosted workflows. if not, hide it from private and public view.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2000)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2000
┆sprint: 93- Ursula
┆taskType: Story

**Comment by garyluu** [comment]
Additionally, it should be explored and commented on why NFL workflows doesn't show forumUrl on the website

**Comment by coverbeck** [comment]
For the topic, you get the big red error box if you click on the Manual radio button in the UI.

**Comment by denis-yuen** [comment]
Note that this ticket seems to have two parts, the ability to edit the topic and the ability to edit the forum url in the UI. 
The next PR will address the former for 1.13 but not the latter. Reviewer can review and edit milestone based on this.
