### ISSUE TITLE
Cancel workflow info editing doesn't revert

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#4592]
**Describe the bug**
Error and cancel doesn't revert back to the original.

**To Reproduce**
1. Have a workflow where you can edit some workflow level info (default descriptor path, default test parameter path, etc)
2. Click edit
3. Change to something weird
4. Click cancel
5. See that the weird text still remains

**Expected behavior**
5. the weird text is not there, the original text remains

**Screenshots**
![image](https://user-images.githubusercontent.com/24548904/143482501-b15af8d7-8e8a-4351-b11d-7a703877ff41.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/0eae84c) - 0eae84c

[UI](https://github.com/dockstore/dockstore-ui2/commits/8569af25) - 2.8.2-95-g8569af25

[Compose Setup](https://github.com/dockstore/compose_setup/commits/120d9b9) - 120d9b9

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/7f09f05) - 1.11.1-99-g7f09f05

galaxyParsingLambdaVersion: 0.0.6

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2001)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2001
┆sprint: 93- Ursula
┆taskType: Story

**Comment by coverbeck** [comment]
To clarify, the change is not saved to the backend; the UI is showing the unsaved changes.

**Comment by coverbeck** [comment]
Notes for myself, this is a tad confusing:

* info-tab.component.ts has an `extendedWorkflow`property. This is set via an `@Input`, and comes from the Akita store.
* info-tab.component.ts has a `workflow` property/object. It is initialized in the `ngOnChanges`, which fires when a data-bound property changes. In practice for this case, I think, it fires once, essentially after the componenent initializes and the `@Input`s are processed. The `ngOnChanges` sets the `workflow` property to a copy of the `extendedWorkflow`.
* The UI edits the `workflow` object, i.e., the copy of the `extendedWorkflow`.

When you click the edit button, it invokes a toggle method, e.g., 

```
toggleEditWorkflowPath() {
    if (this.workflowPathEditing) {
      this.save();
    }
    this.infoTabService.setWorkflowPathEditing(!this.workflowPathEditing);
  }
```
This invokes `next` on a BehaviorSubject in info-tab.service.ts, whose sole listener is info-tab.component.ts, which updates `this.workflowPathEditing`.

IOW, the effect of the above code is the same as:

```
toggleEditWorkflowPath() {
    if (this.workflowPathEditing) {
      this.save();
    }
    this.workflowPathEditing = !this.workflowPathEditing;
  }
```

* The `save()` method invokes info-tab.service.ts:`updateAndRefresh` with `this.workflow` as a parameter.
* The `cancelEditing` method, which is invoked when you cancel, remember, after `this.workflow` has been updated via the HTML
    1. Calls `infoTabService.cancelEditing()`, which
    2. Calls the BehaviorSubjects with false, i.e., so that this.workflowPathEditing ends up being false
    3. Calls `infoTabService.restoreWorfklow()`, which reverts `infoTabService.workflow`. But `infoTabComponent` never reads infoTabService.workflow`, I think. Hence the problem.
