### ISSUE TITLE
CLI Build Improvements

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4637]
**Describe the bug**
Walt built a branch locally and it did not update his generated pom.xml's.

**Expected behavior**
The CLI should behave like the web service to ensure the correct builds:

* Supply a mvnw to ensure the correct version
* Enforce the JDK version in the pom.xml

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2020)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-2020
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by denis-yuen** [comment]
mvnw and jdk version seem worth doing, but not sure how it affects generated pom.xmls.
