### ISSUE TITLE
CLI Quick Start instructions have confusing headers and header styles

### ISSUE THREAD

**Issue by chmreid** [dockstore/dockstore#4639]
**Describe the bug**

On the Dockstore Quick Start instructions page in dev environment <https://dev.dockstore.net/quick-start> the headers have a few problems that are distracting for the user:

* Step 2 appears twice
* Step 1 has a different style from Step 2

See screenshot below showing problem.

![Screenshot 2021-12-17 at 13-55-12 Dockstore Quick Start](https://user-images.githubusercontent.com/53452777/146612781-cfb267c2-464f-4918-994f-9611335c5f5c.png)

**To Reproduce**

1. Visit <https://dev.dockstore.net/quick-start>
2. See error

**Expected behavior**

Header styles should be consistent and Step 2 should not appear twice.

Build info:

[Webservice](https://github.com/dockstore/dockstore/commits/6d891ef) - 6d891ef

[UI](https://github.com/dockstore/dockstore-ui2/commits/97af6aee) - 2.8.4-107-g97af6aee

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/b5fc8b9) - 1.11.2-106-gb5fc8b9

(dev environment)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2022)
┆friendlyId: DOCK-2022
┆sprint: Seabright Sprint 78- Flotsam
┆taskType: Story

**Comment by denis-yuen** [comment]
Seems to apply to prod as well
