### ISSUE TITLE
"Last modified" should represent when current branch/tag was modified, not repo overall

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4640]
**Is your feature request related to a problem? Please describe.**
This implies that 4.1.6.0 is from six hours ago. It's not. Because GATK has a bazillion branches, a user would need to do quite a bit of scrolling to learn it's actually from March 2020.

![Screenshot 2021-12-17 at 2 58 52 PM](https://user-images.githubusercontent.com/27784612/146617348-edb4c213-cc33-4023-bf4e-7a8a4b95eb9b.png)

**Describe the solution you'd like**
Either a "last modified" representing the currently selected/branch tag's last modified tag, or two seperate lines, ie

Last commit to this branch: March 3rd 2020
Last sync to repo: 6 hours ago

For tags:

Tag created: March 3rd 2020
Last sync to repo: 6 hours ago

**Describe alternatives you've considered**
Default sorting the currently selected tag or branch to the top of the versions tab

**Additional context**
This potentially has security implications; users may think a workflow (or more precisely, the Docker it uses) is more up to date than it actually is.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2023)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2023
┆sprint: 92- T
┆taskType: Story

**Comment by denis-yuen** [comment]
Quick note re: `Last sync to repo`
Repos don't actually get synced, we get events corresponding to particular branches. 
So changing this to something like 

```
Last commit to this branch: March 3rd 2020
Last commit to this to repo: 6 hours ago
```

**Comment by aofarrel** [comment]
I really like how this looks, thank you!
