### ISSUE TITLE
Labels on tool pages link to workflow search results

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4641]
**Describe the bug**
When a label on a tool page is clicked, it shows the search results for workflows with that label.  

**To Reproduce**
1. Go to the page of a tool with a label, which you can find via the Labels facet in Search.
2. Click on the label.
3. See a list of workflows that have that label.

**Expected behavior**
IMHO, clicking a label on a tool page should show the _tools_ with that label.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Reproduced on staging:
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.10) - 1.11.10

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.4) - 2.8.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2) - 1.11.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2024)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2024
┆sprint: SEAB 84- Mermaid
┆taskType: Story

**Comment by denis-yuen** [comment]
This happens with github app tools as well
