### ISSUE TITLE
Console errors after setting the default version in dev

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4643]
**Describe the bug**
I had my browser tools open when setting a default version, and noticed console errors.

No obvious errors that I could see that were visible to the user, but I can't tell for sure.

It happens with a local build as well.

**To Reproduce**

1. Go to My Workflows
1. Select a workflow
1. Open browser tools
1. Set the default version. It doesn't seem to matter if the a default is already set or not.
1. See error in console

**Expected behavior**
There should be no console errors.

**Screenshots**

```
ERROR TypeError: this.selectedVersion.orcidAuthors is null
    ngOnChanges https://gui.dockstore.org/develop-97af6ae/294-es2018.acbc617c330cc5ae75c9.js:1
    xt https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    Oe https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    Ie https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    Se https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    ws https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    bs https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    ks https://gui.dockstore.org/develop-97af6ae/294-es2018.acbc617c330cc5ae75c9.js:1
    Fs https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    Ps https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
    Ps https://gui.dockstore.org/develop-97af6ae/main-es2018.a58bd12e3c75524417c7.js:1
```

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/6d891ef)

* 6d891ef

[UI](https://github.com/dockstore/dockstore-ui2/commits/97af6aee)

* 2.8.4-107-g97af6aee

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a)

* 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/b5fc8b9)

* 1.11.2-106-gb5fc8b9

galaxyParsingLambdaVersion: 0.0.6

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2025)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2025
┆sprint: 94- Vampire Pleco
┆taskType: Story

**Comment by denis-yuen** [comment]
might be related to https://github.com/dockstore/dockstore-ui2/pull/1574 
(some selectedVersions are null, for stub workflows, possibly others)

**Comment by coverbeck** [comment]
I'm not able to reproduce this any more in neither staging nor dev.
