### ISSUE TITLE
Merge security schemes

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4671]
**Describe the bug**
TRS uses "BEARER" as a security scheme. https://github.com/ga4gh/tool-registry-service-schemas/blob/2.0.1-beta.0/openapi/openapi.yaml#L467
Dockstore uses "bearer" https://github.com/dockstore/dockstore/blob/1.11.10/dockstore-webservice/src/main/resources/openapi3/openapi.yaml#L8878
The TRS schema is used during the build process and essentially merged into the Dockstore API. 

We probably didn't notice before because our webservice probably is not case sensitive but the validator in https://github.com/dockstore/dockstore/pull/4659 did notice. 

**To Reproduce**
Go to the swagger interface and attempt to authorize
![image (4)](https://user-images.githubusercontent.com/1730679/150166307-c7932fa8-90ce-4fed-9dbb-a4ba941d09da.png)

**Expected behavior**
Only one authorization should show up and we should also validate successfully. 

**Additional context**

[Webservice](https://github.com/dockstore/dockstore/commits/66a9a38) - 66a9a38

[UI](https://github.com/dockstore/dockstore-ui2/commits/f37c36c3) - 2.8.4-117-gf37c36c3

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/a77a2fb) - 1.11.3-111-ga77a2fb

galaxyParsingLambdaVersion: 0.0.6

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2036)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2036
┆sprint: 88 Poseidon
┆taskType: Story

**Comment by kathy-t** [comment]
Only "bearer" authenticates successfully.

"bearer" and "BEARER" shows up if you authenticate at the top of the page:
![image](https://user-images.githubusercontent.com/25287123/150168780-5c9be179-af18-4388-a071-3026c78ca5b5.png)


If you authenticate from an endpoint (like below), only "bearer" shows up
![Screenshot 2022-01-19 at 10-58-42 Swagger UI](https://user-images.githubusercontent.com/25287123/150167974-60a8230f-ea83-4d44-b38f-1108ada8089e.png)

**Comment by coverbeck** [comment]
Confirmed that there is only 1 box to enter your token, and that using your token correctly authenticates.

[Webservice](https://github.com/dockstore/dockstore/commits/995c2c8) - 995c2c8

[UI](https://github.com/dockstore/dockstore-ui2/commits/fef68a49) - 2.9.2-111-gfef68a49

[Compose Setup](https://github.com/dockstore/compose_setup/commits/46fef8e) - 46fef8e

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c313e2c) - 1.12.6-114-gc313e2c

galaxyParsingLambdaVersion: 0.0.7
