### ISSUE TITLE
Have Google index stable documentation release

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4682]
**Is your feature request related to a problem? Please describe.**
Google hits for our documentation site point to "...en/develop...". They should point to "...en/stable...".

**Describe the solution you'd like**
Consolidate urls via Google: https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls

**Describe alternatives you've considered**
Leave it; delete the develop release on readthedocs, umm...

**Additional context**
Go to Google and search for "wdl getting started". The first hit will have a link to https://docs.dockstore.org/en/develop/getting-started/getting-started-with-wdl.html; it should be to https://docs.dockstore.org/en/stable/getting-started/getting-started-with-wdl.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2044)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10850">image-20221011-155104.png</a>
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2044
┆sprint: Backlog
┆taskType: Story

**Comment by svonworl** [comment]
Might also be able to solve via robots.txt
https://developers.google.com/search/docs/advanced/robots/intro

**Comment by chmreid** [comment]
From the [developers.google.com link above](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-link-method), the methods listed all require modifying the page in a way we don't necessarily control on readthedocs.org - inserting a link tag in the head tag, or adding an http header, or returning a particular http response code. Re robots.txt, that page also says:

> General guidelines
> For all canonicalization methods, follow these general guidelines:
>    Don't use the robots.txt file for canonicalization purposes.

Fortunately though, RTD addresses this: https://govpress.readthedocs.io/en/latest/canonical.html

**Comment by denis-yuen** [comment]
Hmmm, looks looks like the default is already stable. 
https://docs.readthedocs.io/en/stable/versions.html#redirects-on-root-urls

Any chance Google is just indexing develop because other people are pointing to develop?

**Comment by coverbeck** [comment]
> Any chance Google is just indexing develop because other people are pointing to develop?

It could be. They are a small number of actual referrals from these sites, but they might add up. Here are ones we could address and/or ask people to change:

* bdcatalyst.gitbook.io/biodata-catalyst-documentation/written-documentation/getting-started/analyze-data-1/dockstore/intro-to-docker-wdl-cwl	
* bdcatalyst.gitbook.io/biodata-catalyst-documentation/written-documentation/getting-started/community-tools-and-integration-1/bring-your-own-tool-s-to-biodata-catalyst/creating-testing-and-scaling-wdl-workflows	
* bdcatalyst.gitbook.io/	
* terra.biodatacatalyst.nhlbi.nih.gov/	
* github.com/CancerCollaboratory/dockstore-tool-bamstats	
* github.com/dockstore/dockstore	
* github.com/openwdl/learn-wdl/blob/master/5_reference_material/4_external-links.md	
* openwdl.org/
