### ISSUE TITLE
Getting started w/ WDL fluctuates between "tool" and "workflow"

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4695]
Most of the time, we say it's a tool, but...

> Below we show an example metadata section and how it will display on your workflow’s landing page:

> description: "## Bamstats \n This is the Bamstats workflow.\n\n Adding documentation improves clarity."

> Image saying "the bamstats workflow"

And possibly more, will need to take a closer look.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2050)
┆friendlyId: DOCK-2050
┆sprint: Backlog
┆taskType: Story

**Comment by coverbeck** [comment]
I think we should always say workflow. We've talked about not allowing WDL to be registered as a tool, since WDL doesn't make a formal distinction in the language like CWL does.

But we have some WDL tools registered already, sigh -- I hope the doc is not referencing it.

**Comment by aofarrel** [comment]
According to my very quick check, only about 1.5% of all WDLs on Dockstore are tools that are not just hello-world/the bamstats tutorial. There is an argument to be made about focusing more on a docker image versus the descriptor file being good for some WDL use cases, I think, but I don't know if that's worth some of the confusion.

I'm thinking it might be best to move the existing tutorial to the advanced topics section, and make a new one that creates a WDL workflow instead of a WDL task -- I made myself a ticket to look into that.

**Comment by coverbeck** [comment]
You probably know this, but WDL "tools" are not importable into Terra (that's a primary reason to not allow users to register them going forward).

**Comment by aofarrel** [comment]
Yep, that's the other reason why I think we should guide new users away from it, regardless of whether or not we ultimately depreciate the feature.

I wonder... can we still get the benefit of WDL tools being "docker focused" with WDL workflows? Is there a way to show off the Dockerfile in a WDL workflow entry?

**Comment by aofarrel** [comment]
This ticket overlaps with #4694. If we ultimately decide to keep the WDL tool documentation and move it somewhere else, this ticket is still relevant. If not, it should be closed.

**Comment by aofarrel** [comment]
Addressed in https://github.com/dockstore/dockstore-documentation/pull/174
