### ISSUE TITLE
Org's logo appears correctly on some pages and is broken on others

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4700]
**Describe the bug**
There is at least one organization for which the org logo image is correctly displayed on some pages, but appears broken on others.  A quick code inspection shows that where the logo appears correctly, the admin-specified org logo img tag url is wrapped in a gravatar url, and where the logo is broken, it is not.

**To Reproduce**
1. Go to https://dockstore.org/organizations
2. Find the European Molecular Biology Laboratory org summary box.
3. Note the broken org logo in the org summary box.
4. Click on the European Molecular Biology Laboratory org summary box.
5. Hey, the org logo appears on the organization page!

**Expected behavior**
For a given org, the logo image should have a consistent visual state: it should either appear correctly in all places, or not appear correctly in all places.

**Screenshots**
<img width="251" alt="Screen Shot 2022-01-31 at 7 20 14 PM" src="https://user-images.githubusercontent.com/88108675/151908333-ec427f37-197b-4c0a-8ea5-fdf892ea75a7.png">
<img width="274" alt="Screen Shot 2022-01-31 at 7 20 49 PM" src="https://user-images.githubusercontent.com/88108675/151908601-3dbb82ef-c073-4e09-b164-709bef066d63.png">

**Desktop (please complete the following information):**
MacOS Chrome

**Additional context**
reproducible on prod

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2054)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10658">image-20220304-214804.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10660">image-20220304-214844.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10659">image-20220304-214926.png</a>
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-2054
┆sprint: SEAB 80- Hugs
┆taskType: Story

**Comment by coverbeck** [comment]
Notes:

* The only org where this happens, where the logo is visible on the individual organization page, but not on the multiple organizations page, is EMBL. It's because their logo is hosted with `strict-origin-when-cross-origin`, so we can't display it directly.
* Other orgs that don't have a log on the multiple organizations page, also don't have it on the single organization page.
* Using the gravatar url address it.

**Comment by coverbeck** [comment]
Please verify on staging.
