### ISSUE TITLE
Restubbing a worklow with a snapshot version returns a 500 error

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4717]
**Describe the bug**
Restubbing a workflow with a snapshot version returns a 500 error.

**To Reproduce**
1. Create a workflow and successfully snapshot a version.
2. Click on 'Restub'.
3. See that nothing happens. No error is displayed in the UI.
4. Check the developer tools to see the 500 error.

**Expected behavior**
Should be able to restub the workflow. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/f894cfb) - f894cfb
[UI](https://github.com/dockstore/dockstore-ui2/commits/ead92717) - 2.8.4-127-gead92717
[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a
[Deploy](https://github.com/dockstore/dockstore-deploy/commits/91fc396) - 1.11.3-119-g91fc396
galaxyParsingLambdaVersion: 0.0.6

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2060)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2060
┆sprint: 92- T
┆taskType: Story

**Comment by denis-yuen** [comment]
Short term issue: Fix the 500, might be a 409 or something depending on why it is failing/being constrained

Longer term issue: I think it depends a bit on our philosophy here. Arguably, a workflow that has a DOI or has been exported to ORCID should not be able to be re-stubbed. We may decide that a workflow that has been published can only be archived.  Snapshotting alone might be ok for restubbing
