### ISSUE TITLE
Add labels to tool/workflow inconsistent/buggy behaviour 

### ISSUE THREAD

**Issue by KimberleyChong** [dockstore/dockstore#4719]
**Describe the bug**
Adding a label to a workflow or tool has buggy/inconsistent behaviour.
1. Issue 1: Clicking save does not always save the label right away, the "save" button remains present and you need to click it a second time for it to go through
2. Issue 2: The last label added shows up repeated when you go to edit existing labels

**To Reproduce**

**Issue 1: - this behviour happens inconsistently, repeat until reproduced** 
1. Go to "My Workflows" and click on any workflow
2. Click on "Manage Labels" and remove all labels if labels exist > click "Save"
3. Now click on "Manage Labels" > type "potato" > click "Save"
4. If bug occured then the save button should still be present after clicking. After clicking "Save" again it should eventually go through
![image](https://user-images.githubusercontent.com/97123241/153462224-0ec80310-fc0d-464a-8b85-ba839e856f52.png)

This bug follows the cypress mytools.ts/myworkflows.ts test which checks for the save button disappearing after being clicked once

**Issue 2:**
1. Go to "My Workflows" and click on any workflow with existing labels or add your own labels and click save
2. Click on "Manage Labels" 
3. At the end of the list of labels there is a repeated label (it repeats the last one added)
![image](https://user-images.githubusercontent.com/97123241/153462657-4a5b77f1-6497-4619-b9ce-4e4c483b0d02.png)
![image](https://user-images.githubusercontent.com/97123241/153463188-b93b03cd-1b75-4830-be54-7a13e6b1c684.png)

**Expected behavior**
**Issue 1:** - label should save after first click on "Save" button
**Issue 2:** - should have have trailing duplicated label when editing

**Screenshots**
(see above)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [96.0.4664.110]

**Smartphone (please complete the following information):**

**Additional context**
 - UI version: [2.8.4]
 - Webservice version: [1.11.10]
 - host location: [dockstore.org]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2061)
┆fixVersions: Dockstore 1.13.x
┆friendlyId: DOCK-2061
┆sprint: 95- W
┆taskType: Story

**Comment by coverbeck** [comment]
Confirmed this is working on staging.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.1) - 1.13.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.1) - 2.10.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.1) - 1.13.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.13.1) - 1.13.1
