### ISSUE TITLE
support relative paths in .dockstore.yml (and elsewhere?)

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4731]
**Is your feature request related to a problem? Please describe.**
When creating a `.dockstore.yml`, many users probably (very reasonably) assume that the primary descriptor and test file paths can be relative, most likely to the repo root.  However, our documentation (https://docs.dockstore.org/en/develop/getting-started/github-apps/github-apps.html) prescribes absolute paths, and relative paths cause the webservice to malfunction in some situations.

For example, the workflow described in https://ucsc-cgl.atlassian.net/browse/DOCK-2035 has a `.dockstore.yml` with relative paths, which causes the workflow `primaryDescriptor` endpoint to fail because it can't find a `SourceFile` that matches the specified primary descriptor in this loop (the file names would match, except the source file names are prefixed by /, and the primary descriptor is not): https://github.com/dockstore/dockstore/blob/c59924138e1490a71afc0a889fc00777580650fe/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryVersionHelper.java#L285

There may other similar bugs scattered about.

**Describe the solution you'd like**
Allow the user to specify relative paths in `.dockstore.yml`, and perhaps, more generally, all other parts of the system where the user specifies file paths.

**Describe alternatives you've considered**
Leave as is.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2067)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-2067
┆Sprint: Backlog
┆Issue Type: Story

**Comment by Richard-Hansen** [comment]
Whatever is decided for this PR will also apply to https://github.com/dockstore/dockstore/issues/4715

**Comment by hyunnaye** [comment]
Closing as this [PR](https://github.com/dockstore/dockstore/pull/5641) fixes this issue
