### ISSUE TITLE
Internal TRS cache hashcode should use actual limit

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4739]
**Describe the bug**
Looking at the code when reviewing #2125, I noticed that the [hash](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java#L301) is calculated using the `limit` parameter. Because any limit greater than 100 [is treated as 100](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java#L309), that means a separate cache will created for each limit > 100, but the cache content for all of them will be identical.

Was just going to do a PR, but I think it's worth an issue for tracking purposes.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2070)
┆friendlyId: DOCK-2070
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
related to https://ucsc-cgl.atlassian.net/browse/SEAB-3936
