### ISSUE TITLE
Investigate/remedy suspect code in EntryVersionHelper

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4740]
**Describe the bug**
The code near this line in `EntryVersionHelper` looks odd:
https://github.com/dockstore/dockstore/blob/c59924138e1490a71afc0a889fc00777580650fe/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryVersionHelper.java#L285
The adjacent code appears to be intended to compute a path, preferring the workflow version path and using the workflow path as a backup, but instead, both the `workflowPath` and `workflowVersionPath` variables are assigned the same value (`workflowVersion.getWorkflowPath()`).  As a result, some of the following code has no functional effect.

Investigate and fix if necessary.

**Expected behavior**
Whatever we determine is correct.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2071)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2071
┆sprint: 93- Ursula
┆taskType: Story

**Comment by coverbeck** [comment]
Looked at the code again; looks good. Difficult to do end-user testing for this.
