### ISSUE TITLE
Add links to Dockstore blog to docs.dockstore.org and dockstore.org footer

### ISSUE THREAD

**Issue by bvizzier** [dockstore/dockstore#4741]
**Is your feature request related to a problem? Please describe.**
The Dockstore Blog (https://medium.com/dockstore) should be added to the documentation and Dockstore pages.

**Describe the solution you'd like**
There are two modifications being asked for here:  
1) Add a link to the Dockstore Blog in the table of contents section of docs.dockstore.org.   My initial thoughts are to add a new section in the ToC near the VIDEOS section.

2) Add a link to the blog to the dockstore.org footer.  I think a link in the "Help Resources" section is appropriate. 

**Describe alternatives you've considered**
The links are not a requirement.   The blog contains information that is useful to users and, IMO, should be both visible and easily accessible from these two sites. 

**Additional context**
Ask if more is needed. :-)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2072)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2072
┆sprint: 86 - Nemo
┆taskType: Story

**Comment by coverbeck** [comment]
Verified that the link is in dev.

[Webservice](https://github.com/dockstore/dockstore/commits/d50cfd6) - d50cfd6

[UI](https://github.com/dockstore/dockstore-ui2/commits/344740c0) - 2.9.1-78-g344740c0

[Compose Setup](https://github.com/dockstore/compose_setup/commits/f0518f2) - f0518f2

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/1796ce1) - 1.12.5-82-g1796ce1

galaxyParsingLambdaVersion: 0.0.7
