### ISSUE TITLE
Update Cromwell bindings in webservice

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#4758]
Dockstore webservice uses an older version of Cromwell

Update Cromwell bindings and test with something newer from https://github.com/broadinstitute/cromwell/releases
Doesn't look like they have the concept of a stable version either

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2084)
┆friendlyId: DOCK-2084
┆sprint: SEAB 82- Karen
┆taskType: Story

**Comment by coverbeck** [comment]
The PR was #4759
