### ISSUE TITLE
The Dockstore CLI launch command should not require input files.

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4763]
**Is your feature request related to a problem? Please describe.**
When launching a dockstore workflow locally using `dockstore workflow launch`, you are required to pass in an input test parameter file, such as with `--json`, even if the workflow doesn't need it.

The command `dockstore workflow launch --entry my/dockstore/entry` should be accepted.

**Describe the solution you'd like**
Input JSONs should be optional, not required.

**Describe alternatives you've considered**
❌

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2087)
┆friendlyId: DOCK-2087
┆sprint: 88 Poseidon
┆taskType: Story

**Comment by denis-yuen** [comment]
this seems very zen

**Comment by coverbeck** [comment]
Confirmed I was able to run workflows without and without test parameter files
