### ISSUE TITLE
My Tools temporarily shows no tools registered

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4777]
**Describe the bug**
If you have tools, when you go to My Tools, you see a message "You have not registered any tools" until your tools are fetched. It's confusing.

For me, it takes 3 seconds to load my tools (I might be an outlier or this might be another bug), so it's pretty visible.

**To Reproduce**
1. Log in
2. Go to /my-tools
3. See "You have not registered any tools"  message, which eventually goes away.

**Expected behavior**
We should only display "you have not registered any tools" if you haven't registered any tools.

**Additional context**
If you go to My Workflows, there's also a delay (much shorter than for My Tools for me) before it loads your workflows, but it does not display "You have not registered any workflows", so we should follow that pattern.

[Webservice](https://github.com/dockstore/dockstore/commits/b08519d) - b08519d

[UI](https://github.com/dockstore/dockstore-ui2/commits/2662a269) - 2.8.5-137-g2662a269

[Compose Setup](https://github.com/dockstore/compose_setup/commits/638b53a) - 638b53a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/7c9a8a0) - 1.11.2.1-127-g7c9a8a0

galaxyParsingLambdaVersion: 0.0.4

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2096)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2096
┆sprint: 87 Octocat
┆taskType: Story

**Comment by coverbeck** [comment]
I still see it on dev.dockstore.net. It's more noticeable for me probably because I clearly have something in my tools in particular that is making the API respond super slowly (which is a separate issue), but you should be able to simulate this by throttling your network connection.

Made a GIF, but I don't think it plays back at real-time, seems slower. But like I said, it is there for 3-4 seconds.

![slowtools](https://user-images.githubusercontent.com/1049340/167740438-0ded92c7-7917-4730-ad76-29496c14797b.gif)

**Comment by denis-yuen** [comment]
Interesting, I don't get this with a bunch of different speeds in Firefox or Chrome. 
I wonder if there is something different that triggers it, for example I have a github app tool and some glitchy looking Amazon ECR tools

**Comment by coverbeck** [comment]
> Interesting, I don't get this with a bunch of different speeds in Firefox or Chrome.

I had only been trying it on Firefox; just tried on Safari and Chrome with the same results. On a Mac.

The call to `https://dev.dockstore.net/api/users/<userid>/containers` is taking 3 seconds for me; I'm surprised throttling didn't reveal the issue.
