### ISSUE TITLE
Describing value propositions in Dockstore Intro/Getting Started page

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#4785]
**Is your feature request related to a problem? Please describe.**
In https://docs.dockstore.org/en/stable/getting-started/getting-started.html, we should provide a succinct "Why" statement that helps the end-user understand the value of using our product and they are engaged to "get started". This is like an elevator pitch for our novice users. 

**Describe the solution you'd like**
The value could include referencing FAIR principles for sharing scientific methods, but very succinctly!
Additionally, you could give an example outcome that the end-user could achieve, maybe even a before/after example. Like: "Have you read a data science paper and seen the methods reference `X analysis was done using a custom script`, but the authors didn't share the script in their reference material or you couldn't figure out how to get the script they shared to work on your computing environment? Dockstore can help you share your analysis methods so that others in the community can actually reuse it. We do this by... etc etc"

**Alternatives**
There are some values brought up in the "About Dockstore" but they get a bit too in the weeds and could be overwhelming for a novice user.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2101)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2101
┆sprint: S11 - Jot Em Down, Texas
┆taskType: Story

**Comment by denis-yuen** [comment]
We do occupy a somewhat unique position. Presumably there are some users that are looking for the workflow equivalent of https://play.google.com/store/apps but we also want to accommodate the npm style of browsing ( https://www.npmjs.com/search?q=material ) since we do eventually want to encourage folks to mix-and-match workflows just like people normally mix and match dependencies.
