### ISSUE TITLE
Update .dockstore.yml authors documentation

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4787]
**Is your feature request related to a problem? Please describe.**
Our current [docs](https://docs.dockstore.org/en/stable/getting-started/github-apps/github-apps.html#workflow-yml-file) say that `authors` is an array of authorship information, requiring at least the `name` of each author, which isn't true. It requires at least the `name` of each author OR only an author's `orcid`. If an `orcid` is specified, no other information should be provided because the author's information will be retrieved from their ORCID record.

**Describe the solution you'd like**
Update the documentation

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2103)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-2103
┆sprint: SEAB 82- Karen
┆taskType: Story

**Comment by aofarrel** [comment]
I can take this ticket, but I want some clarification to make sure I get it right. What happens if one author has an orcid id and the other one does not? ie, would this example, where I give Andrew's information manually but for me just my orcid, be valid?

>      authors:
>        - name: "Andrew Duncan"
>          email: "andrew@foobar.com"
>          affiliation: "UCSC"
>        - orcid: "0000-0003-4896-1858"

**Comment by kathy-t** [comment]
@aofarrel Yes, your example would be valid. If for some reason Andrew's entry also had an ORCID ID, then all his information would be retrieved using his ORCID ID and the name, email, and affiliation provided in the .dockstore.yml would be ignored.

Have you started this ticket yet? I was assigned this ticket on JIRA, but it wasn't reflected here on GitHub, and I'm unsure if I should proceed to work on it.

**Comment by aofarrel** [comment]
I have not started this ticket yet. Please feel free to assign to me or yourself, whatever works best for you. 👍
