### ISSUE TITLE
Vague GitHub Apps error on invalid YAML key

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4791]
**Describe the bug**
Logged as a Discuss issue: https://discuss.dockstore.org/t/workflow-not-showing-when-using-github-app/5152/4

In the case of an imroper key (i.e. a typo) in the `.dockstore.yml` file of a GitHub App, the logs reported to the user can be vague. For example, if a user mis-types the word `subclass`, the returned GitHub Apps log looks like: 
![Screen Shot 2022-03-13 at 14 38 44](https://user-images.githubusercontent.com/36607471/158237879-9099d20a-27ec-4070-8997-493137e899ca.png)

This is caused during the validation stage of the YAML file and the error message is reported here: https://github.com/dockstore/dockstore/blob/c562b20d3d1037b72d4695284609f1320af9ef05/dockstore-common/src/main/java/io/dockstore/common/yaml/DockstoreYamlHelper.java#L374. 

**To Reproduce**
1. This commit fixes a malformed `.dockstore.yml`: https://github.com/Richard-Hansen/cumulus/commit/ce34f740efa153d60e671d3253eb4088b2f20920, take the pre-commit file with key `sublicass`
2. Attempt to sync with GitHub Apps
3. View GitHub Apps logs and see `must not be null`

**Expected behavior**
Key validation errors for the `.dockstore.yml` should be verbose in pointing out the offending key. Ideally a message such as:
`Missing dockstore.yml required key 'subclass' for workflow XYZ`, or perhaps `Unknown dockstore.yml key 'sublicass'`. This will make it easier for a user to determine what is wrong with their file.

Note: The error in the above `.dockstore.yml` file is caused by `subclass` being a required key that is absent. We should provide errors for both cases of:
1. A required key is missing
2. An unknown key is provided

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.12) - 1.11.12

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.5) - 2.8.5

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2) - 1.11.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2105)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10732">Screenshot 2022-05-03 at 09-47-30 Dockstore My Workflows.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10731">Screenshot 2022-05-03 at 10-30-57 Dockstore My Workflows.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10733">Screenshot 2022-05-03 at 10-41-53 Dockstore My Workflows.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10788">Screenshot from 2022-07-11 09-13-47.png</a>
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2105
┆sprint: SEAB 83- Luca
┆taskType: Story

**Comment by coverbeck** [comment]
> Re-iterating that https://github.com/dockstore/dockstore/pull/4843 ( https://github.com/dockstore/dockstore/pull/4843%7Csmart-link ) which was targeted to the hotfix branch has not been verified yet.

I verified that it works in staging, at least for the original bug described by Richard. I do find it slightly disconcerting that message has an array index, even if there is only 1 workflow, `Property "workflows[0].subclass" is missing`, but the PR did say that, and this is a major improvement over what was there.

This ticket has a lot of discussion; @kathy-t, let me know if you feel it's OK to close this ticket or not.

[Webservice](https://github.com/dockstore/dockstore/commits/d50cfd6) - d50cfd6

[UI](https://github.com/dockstore/dockstore-ui2/commits/344740c0) - 2.9.1-78-g344740c0

[Compose Setup](https://github.com/dockstore/compose_setup/commits/f0518f2) - f0518f2

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/1796ce1) - 1.12.5-82-g1796ce1

galaxyParsingLambdaVersion: 0.0.7
