### ISSUE TITLE
Overhaul github apps related documentation

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4802]
**Is your feature request related to a problem? Please describe.**
All of these relate to each other and have some overlap so I'm putting them into one big ticket, but maybe they can be scoped into smaller tasks.

### Inconsistent language
https://docs.dockstore.org/en/stable/getting-started/github-apps/github-apps.html appears to be intended as a generic doc does not mention tools at all nor does it link to the tools part of the github apps docs

### Confusing user flow
When a user goes to register a tool with github apps, they are brought to https://docs.dockstore.org/en/stable/getting-started/github-apps/github-apps.html, which as mentioned before does not mention tools

### Templates
* The only template in our docs' templates section is a services .yml file. We don't have one for workflows or tools.
* We do have templates for services and workflows on https://docs.dockstore.org/en/stable/getting-started/github-apps/github-apps.html, but not tools, and also the services breakdown is kind-of-sort-of a duplicate of the template one in the templates section
* There is a template for tool dockstore.ymls in the new documentation for tools on migrating-tools-to-github-apps.rst, but it's sort of buried in there

I think we need a total of six dockstore.yml examples:
* A barebones workflow template that can be copy-pasted, mostly for users who know what they're doing and just need a quick template file
* ' ' tool template 
* ' ' services template
* A comprehensive example which includes a breakdown of optional fields, etc, for workflows
* ' ' ' ' ' ' ' ' ' ' ' for tools
* ' ' ' ' ' ' ' ' ' ' ' for services
The bare-bones ones should be as easy to access as possible with little or no text around them (ie not buried in docs), but we could have all three on the same webpage. The comprehensive ones should probably each get their own page as they will very long and users will not want to scroll through a bunch of text for (say) tools and services if they just need a workflow example. I get that there's going to be heavy overlap in many of the fields for all six of these, but for maximum clarity I think redundancy in explanation is the way to go here.

### FAQ
(copy-pasted from "TLP Usability review CWL tool" google doc comment)
1. It only references workflows, not tools
2. FAQ implies that you do not need to make a new commit to find a new dockstore.yml workflow/tool if you have already installed the github app for your organization/"user organization". My experience, where it appears I had previous installed the app because it already had access to covstats, indicates this may not be true, although I am not 100% certain -- it is possible I clicked covstats too without realizing it. We'll need to check the recorded video to be sure.
3. The FAQ's point about needing to make a new commit is in a paragraph that starts off with making sure the app is in the correct organization. Someone scanning quickly will see that first sentence and say "yeah, it's in the right organization" and miss the second sentence that says you need to make a new commit

**Describe the solution you'd like**
Touched on some solutions in the above text, although I am not quite sure how to approach the user flow one. Not sure if github-apps.html needs to more generic, or if we should just take users to github-apps-landing-page.html instead, or maybe both?

**Additional context**
Some but not all of this came out of testing involving the TLP tests of the new dockstore.yml github apps registration for tools.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2109)
┆friendlyId: DOCK-2109
┆sprint: S6 - Embarrass, Wisconsin
┆taskType: Story

**Comment by aofarrel** [comment]
Additional things to address: 
* Workaround on github-apps-land-page.rst which uses a reference to an internal link of dockstore-workflows.rst, which takes the user to the expected header, but there's other information not related to dockstore.yml surrounding it. It also means that portion cannot appear in the toctree. Ignoring the toctree part, this could be addressed by making that particular section a standalone file that gets imported into a new page that github-apps-land-page.rst links to, and also get imported into dockstore-workflows.rst
* dockstore-workflows.rst talks about registration with the GitHub App, but dockstore-tools.rst does not

**Comment by aofarrel** [comment]
Draft PR: https://github.com/dockstore/dockstore-documentation/pull/180

**Comment by denis-yuen** [comment]
>  Figure out what "The GitHub user who first adds a workflow onto Dockstore must correspond to a user on Dockstore." actually means -- it seems self-evident 

Think what this means is that in order for the workflow/tool to show up on Dockstore a push event must correspond to a github user known to Dockstore. For example, if you had a robot user or just some other user unknown to us, they could push even with a .dockstore.yml present and the github app installed and it wouldn't show up until at least one user known to Dockstore pushed. After a known user has pushed, it will show up and those unknown users can also update the workflow by pushign to it, but not before. 

That's my interpretation anyway
