### ISSUE TITLE
.dockstore.yml processing should continue after error

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4803]
**Is your feature request related to a problem? Please describe.**
Currently, when the webservice processes a github apps request via the webhook endpoint, if any error occurs while parsing and processing `.dockstore.yml` or the associated source files, the process aborts and no workflows/apptools are loaded, even though `.dockstore.yml` might contain many other valid workflows/apptools.

**Describe the solution you'd like**
`.dockstore.yml` should be completely processed, and all valid workflows/apptools should be loaded.  If an error occurs while processing a particular entry, information about the error should be logged (to the github apps logs) and displayed, and `.dockstore.yml` processing should continue to the next prospective entry.

We cooked up a draft PR that demonstrates a possible approach:
https://github.com/dockstore/dockstore/pull/4796
But consensus was that it might be too risky for the imminent 1.12 release.

**Describe alternatives you've considered**
Leave as is.  But not really, we should do this.

**Additional context**
 See this ticket for a repo that demonstrates the problem: https://ucsc-cgl.atlassian.net/browse/SEAB-4033

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2110)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2110
┆sprint: 89
┆taskType: Story

**Comment by denis-yuen** [comment]
![Screenshot from 2022-09-06 12-02-09](https://user-images.githubusercontent.com/1730679/188682708-1f003f35-2bb9-4dba-8c7e-76441e0d47bd.png)

Confirmed with https://github.com/dockstore-testing/one-workflow-many-ways/tree/master that a messed up workflow between two working ones didn't knock out the other two
