### ISSUE TITLE
Duplicate Discuss elements for entries

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4812]
**Describe the bug**
Some entries on Dockstore are showing duplicated discuss topic lines:
<img width="997" alt="Screen Shot 2022-03-24 at 3 02 27 PM" src="https://user-images.githubusercontent.com/36607471/159991336-ca4d207a-ce46-4de9-b8c7-651c8828eff1.png">

<img width="1015" alt="Screen Shot 2022-03-24 at 3 04 41 PM" src="https://user-images.githubusercontent.com/36607471/159991447-a91110af-d8cd-4130-87f0-0280b8309e3f.png">

**To Reproduce**
1. https://staging.dockstore.org/workflows/github.com/dockstore-testing/wes-testing/agc-fastq-read-counts:main?tab=info
2. Scroll down to see the duplicated topics

**Expected behavior**
This shouldn't be duplicated. As an additional note, it seems not all entries are showing this duplication. 

**Screenshots**

**Additional context**
Dev:
[Webservice](https://github.com/dockstore/dockstore/commits/6377918) - 6377918

[UI](https://github.com/dockstore/dockstore-ui2/commits/36968b21) - 2.8.5-140-g36968b21

[Compose Setup](https://github.com/dockstore/compose_setup/commits/638b53a) - 638b53a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6eb06d7) - 1.12.0-4-g6eb06d7

galaxyParsingLambdaVersion: 0.0.7

Staging: 
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9.0-rc.1) - 2.9.0-rc.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.0) - 1.12.0

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2114)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2114
┆Sprint: 96- X-Ray Tetra
┆Issue Type: Story
┆Link To Issue: https://ucsc-cgl.atlassian.net/browse/DOCK-2114

**Comment by denis-yuen** [comment]
Wonder if bad merge, but then it would only be dev and this has it on both staging and dev

**Comment by coverbeck** [comment]
This page is one entry for me when I start out: https://staging.dockstore.org/workflows/github.com/dockstore-testing/wes-testing/agc-fastq-read-counts:main?tab=info

If I leave the page and come back, e.g., go to search, then press the back button, then there are sometimes two entries.

Seems like it could be a UI bug, we're loading twice.
