### ISSUE TITLE
Rethink prominence of Docker in our documentation

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4816]
Ticket reframed here: https://github.com/dockstore/dockstore/issues/4816#issuecomment-1083207881

Old ticket:

**Is your feature request related to a problem? Please describe.**
Our getting started with CWL guide assumes that the user wants to create a Docker based legacy tool. As we shift our definition of tools, our getting started tutorial is telling people to set up an autobuilding Docker image and then immediately after telling them they shouldn't have done that.

**Describe the solution you'd like**
Remake the getting started with CWL guide like I did the WDL guide.

Even though I believe the current getting started with CWL guide is no longer fit for purpose as a getting started, it is still perfectly serviceable for Docker-based tools. When I revamped the getting started with WDL guide, I removed the old getting started with WDL stuff completely, but I think there is a good reason to keep the CWL equivalent around (albeit in advanced topics, and with some changed wording to indicate that it is for legacy tools).

**Describe alternatives you've considered**
Remake the getting started with CWL guide like I did the WDL guide, and do not keep the legacy tools version around.

**Additional context**
I can attempt to integrate this idea into https://github.com/dockstore/dockstore-documentation/pull/180 because it does fit into the theme of revamping docs r/e github apps, but I am leaning towards doing it in a new PR as that one is monstrously large enough as is, and I want to make sure I give reviewers enough time to look it over.

Make sure to deal with the paragraph in dockstore-tools.rst that assumes you have a dockerfile!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2118)
┆friendlyId: DOCK-2118
┆sprint: S7 - Forks of Salmon, CA
┆taskType: Story

**Comment by aofarrel** [comment]
@bethsheets There would be a lot of things that would fit under that category... 
advanced-topics/
--> legacy/
------> legacy-registration-of-tools.rst (currently in dockstore-tools.rst)
------> legacy-registration-of-wfs.rst (currently in dockstore-workflows.rst)
------> services-1.1-template.yml (currently in assets/templates, just never rendered)
------> wdl-tool-tutorial.rst (currently deleted, but could be brought back because git is magic)

...but I'm not quite sure if making an autobuilding Docker-based CWL tool is strictly legacy? You can have an autobuilding Docker image and still use gh-app registration, as far as I'm aware, the resulting entry just won't be connected to your Docker image's tags nor will the Dockerfile be embedded in the Dockstore entry. So, my issue with GSW-CWL as it currently stands isn't that it goes over how to make an autobuilding Docker image, but rather that an autobuilding Docker image is not required for gh-app tools. It's making a new user do extra work unnecessarily, ie, increasing the barrier of entry to writing a CWL tool which is a big deal when you're brand new to CWL like the tutorial assumes. But the process of setting up a quay.io account is not something Dockstore controls nor is it strictly legacy.

@denis-yuen @coverbeck Would love your thoughts on this.

**Comment by denis-yuen** [comment]
> ather that an autobuilding Docker image is not required for gh-app tools. It's making a new user do extra work unnecessarily, ie, increasing the barrier of entry to writing a CWL tool which is a big deal when you're brand new to CWL like the tutorial assumes 

Hmmm, several ideas here. 
Using Docker is definitely increasing the barrier to writing a CWL tool (or workflow), but it (or something similar to it) is required to make a portable reproducible tool that can be used somewhere else which is kind of our main reason for existing. 
That said, our method for registering tools by linking a quay.io account and looking at builds, that method will eventually be legacy after the github apps for tools process rolls out. 

Which is a long-winded way of saying that even when github apps for tools is front and center, and some of these legacy approaches are dismantled, I think Docker should be prominent in our documentation and not glossed over. You could introduce the idea of using pre-created containers like biocontainers if one is available as an alternative to making your own Docker container, but I think it is still a worthwhile exercise to learn how to create simple Docker containers to know what is going on.

**Comment by aofarrel** [comment]
Although this has already been merged, Denis brings up a good point and I want to revisit it.

**Comment by denis-yuen** [comment]
(re-opened based on last comment)

**Comment by bethsheets** [comment]
@aofarrel 
For Dockstore's [Intro to **CWL](https://docs.dockstore.org/en/stable/getting-started/getting-started-with-cwl.html),** we could use a different example to make this a little easier on the end user. Instead of using a Docker container created/maintained by Dockstore (the bamstat tools), we could instead show an example where we reuse a container from Biocontainers. This could signal to the end user that they don't have to make their own container to get started when writing a workflow.
