### ISSUE TITLE
Create a command line tool to check Dockstore YAML files

### ISSUE THREAD

**Issue by juklucas** [dockstore/dockstore#4838]
Uploading workflows using a YAML file (w/ GitHub apps) is really convenient, but can be a bit opaque from the users perspective -- especially when things go wrong. When the upload fails it is hard to tell if there was a problem with the YAML or if there was a problem with permissions on the repo, for instance.

It would be nice to have a command line tool that can check both the YAML file itself for syntactical error as well as the YAML against the files it is telling Dockstore to upload. This would include: 
* The syntax of the YAML file
 * is the version number correct?
 * Are all required fields present (and spelled correctly)?
 * Are the entered values allowed? 
* Check that all file paths referenced in the file exist in the repo
* Is the .dockstore.yaml file named properly
* Is the .dockstore.yaml file in the correct location (root of the repo directory)

Ideally errors would return values that are understandable to non-experts. For instance, if subclass is missing, the return value would be something like:
```
Subclass is missing. Subclass is the workflow language the workflow is written in. Examples include WDL, CWL...
```
If it existed, this tool would allow users to execute a command (similar to how womtool is used to validate WDLs) and find out if their .dockstore.yaml file is valid. This would really aid in troubleshooting when, for instance, a workflow is not showing up in Dockstore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2129)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2129
┆sprint: 89
┆taskType: Story

**Comment by coverbeck** [comment]
Good idea! It could also and/or instead be something in the UI, e.g., upload a .dockstore.yml file or point to one on GitHub.

The plus of having it in the CLI is that it could also validate your primary descriptor path, which we couldn't do with a file upload.

**Comment by coverbeck** [comment]
Reopening (should only be closed after it's been verified).

**Comment by denis-yuen** [comment]
:laughing:
