### ISSUE TITLE
GitHub/Google bios presented differently

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4840]
**Is your feature request related to a problem? Please describe.**
When listing the profiles of a user (say with: https://dockstore.org/api/static/swagger-ui/index.html#/users/getUser) the `bio` field of profiles is either an empty string or null. Although this is not technically a bug, it seems like there could be an improvement by making a standard format for empty bios.

```
  "userProfiles": {
    "github.com": {
      "avatarURL": "...",
      "bio": "",     <---------------- Empty String
      "company": null,
      "email": "...",
      "location": null,
      "name": null,
      "username": "..."
    },
    "google.com": {
      "avatarURL": "...",
      "bio": null,     <-------------- null
      "company": null,
      "email": "...",
      "location": null,
      "name": "...",
      "username": "..."
    }
  }
```

**Describe the solution you'd like**
The formatting for empty bios should be consistent. Which would be GitHub displaying `null` for an empty bio, or Google displaying `""` for an empty bio.

This may be a simple change in the DB to store empty strings as null for the `bio` column.

**Describe alternatives you've considered**
Leave as-is, this isn't a big deal.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2131)
┆friendlyId: DOCK-2131
┆sprint: SEAB 84- Mermaid
┆taskType: Story

**Comment by denis-yuen** [comment]
Implementer should see also https://github.com/dockstore/dockstore/issues/4839 
(should probably tackle both while in the area)
