### ISSUE TITLE
Add GitHub Container Registry to table of supported Docker image repositories

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4842]
**Is your feature request related to a problem? Please describe.**
In the [Docker Image Checksum Support docs](https://docs.dockstore.org/en/stable/advanced-topics/checksum-support.html#docker-image-checksum-support), we refer to GitHub Container Registry in the note section here:  
![image](https://user-images.githubusercontent.com/25287123/162262089-17a32fc7-4b86-43ee-9c17-705a412cc030.png)
but it’s not actually in the table of supported Docker image repositories:
![image](https://user-images.githubusercontent.com/25287123/162262142-275f76d6-a2e1-4733-8244-3b461f53a805.png)

**Describe the solution you'd like**
Should add GitHub Container Registry to the table to indicate that checksum harvesting is supported for it.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2132)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2132
┆sprint: 93- Ursula
┆taskType: Story

**Comment by aofarrel** [comment]
I can add this. Should it be added to all rows?

**Comment by kathy-t** [comment]
Yeah, GitHub Container Registry should be added to all rows
