### ISSUE TITLE
"Published / Unpublished" tools/workflows toggle option is sometimes obscured

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4851]
**Describe the bug**
In the list that displays "My tools" and "My workflows", the input component that selects whether to display "Published" or "Unpublished" tools/workflows is sometimes too wide and overflows the available space.  As a result, the unselected option sometimes scrolls out of view and is effectively hidden, perhaps completely for certain browser widths.

Described in TLP's user testing feedback: https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing

**To Reproduce**
1. Go to 'My tools' or 'My workflows'
2. Select an organization.
3. See the "Published / Unpublished" toggle above the list of entries.  Adjust the width of your browser until you see the bug.

**Expected behavior**
It should always be visually apparent that there are two states to select from: "published" and "unpublished".  This may require a different type of component to be substituted.

**Screenshots**
![bug0](https://user-images.githubusercontent.com/88108675/163253698-6545c38e-20d4-416e-b4fd-c336cc5e88d6.JPG)

**Additional context**
reproducible on staging and dev

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2134)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10802">image-20220802-172550.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10803">image-20220802-172622.png</a>
┆fixVersions: Dockstore 1.14
┆friendlyId: DOCK-2134
┆sprint: Backlog
┆taskType: Story

**Comment by coverbeck** [comment]
I can't reproduce neither. It turns out I was thinking of a different ticket when I said I could reproduce this in our backlog grooming meeting.

**Comment by svonworl** [comment]
Yeah, looks fixed.
