### ISSUE TITLE
Typo in "Default Version Required" dialog

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4853]
**Describe the bug**
There is a double-"the" grammar error ("the the") in the text of the "Default Version Required" dialog.

Described in TLP's user testing feedback: https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing

**To Reproduce**
1. Add a workflow without a default version to Dockstore.
2. Attempt to publish the workflow via the Publish button.
3. A dialog will pop up that prompts you to set a default version.
4. See "the the" in the dialog text.

**Expected behavior**
Correct grammar.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2135)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2135
┆sprint: 87 Octocat
┆taskType: Story

**Comment by coverbeck** [comment]
Confirmed there is no double "the" in staging.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.2) - 1.12.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9.2) - 2.9.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.2) - 1.12.2

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7
