### ISSUE TITLE
"Checker Workflow" label/value briefly disappears when Topic is toggled between Manual and Automatic

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4854]
**Describe the bug**
In the "Info" tab of a workflow or apptool, toggling the Topic Selection radio button between Automatic and Manual causes the line containing the "Checker Workflow" label and value, immediately below, to briefly disappear (before reappearing with the same value as before).  During user testing, the testers were already unsure about what the various Topic values and options meant, which the "blinking" exacerbated.

The cause of the "blink" is probably that the information backing the component is being completely refreshed after any update, which means that the fix is probably not trivial.

Described in TLP's user testing feedback: https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing

**To Reproduce**

1. Go to the Info tab for a workflow.
1. Change the "Topic Selection" to a different value.
1. See the "Checker Workflow" line briefly go away, then return.

**Expected behavior**
Changing an input should not trigger unrelated UI activity.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2137)
┆Fix Versions: Dockstore 1.18
┆Issue Number: DOCK-2137
┆Sprint: 143 - Piraeus
┆Issue Type: Story

**Comment by denis-yuen** [comment]
`not trivial` delaying
