### ISSUE TITLE
 Workflows/apptools from a newly-added repo do not appear in Dockstore until after a commit

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4856]
**Describe the bug**
When a user first adds a repo to the Dockstore github app, the repo is not processed, and the entries described within are not registered in Dockstore, until the user pushes a subsequent commit to the repo.

Most first-time users probably expect that when they add a repo to the github app, that shortly thereafter, the associated entries will appear on Dockstore in the My tools/workflows lists, with no further action required.  Indeed, during TLP's usability testing, they expected the system to behave as such, and could not figure out why the tool in the repo they had added was not appearing.  After some time, they asked me for help, and I told them what was happening.  They made a commit, and ~5 minutes later, the tool appeared.

There are at least three types of solutions to the problem, some of which may not be possible:

1. Make our github app tell the webservice about a newly-added repo, when it is added.
1. Process some or all of a newly-added repo, via a mechanism similar to our pre-github-apps registration.
1. If we can't or don't want to immediately register a newly-added repo, make sure the user understands that they need to make a commit for their entries to register, and that there is a delay.

Described in TLP's user testing feedback: [https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing](https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing)

**To Reproduce**

1. Add a repo to the Dockstore github app.
1. Check "My tools" and "My workflows" to see if your entries have been registered.
1. See the entries not appear.  Wait.  Hey, the entries are still not there.
1. Make a commit to the repo.
1. See the entries appear, some minutes later.

**Expected behavior**
Implement the behavior that the typical, naive user will expect, or inform them to expect something else.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2139)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2139
┆Sprint: 105 - Colorado
┆Issue Type: Story

**Comment by coverbeck** [comment]
> Make our github app tell the webservice about a newly-added repo, when it is added.

The web service does get notified, the problem is there's no UI indication of it until an entry also gets added.

If we address #4845, that may solve this.

**Comment by melainalegaspi** [comment]
@coverbeck : "in 1.13 GitHub app logs will be visible for new organizations, this is close to this feature but not quite there because it relates to the organization and not the specific repo. Also see #3473 "
