### ISSUE TITLE
Prioritize github apps tool registration method above other options

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4857]
**Describe the bug**
We've decided that GitHub Apps is our preferred tool/workflow registration method.  It appears that we have changed the workflow registration dialog to prioritize GitHub Apps.  However, we have not made similar changes to the tool registration dialog.

Change the tool registration interface to prioritize GitHub Apps (move the GitHub Apps option to top of list in step 1, tag it as recommended, etc)

Described in TLP's user testing feedback: https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing

**To Reproduce**

1. Log into Dockstore
1. Start to add a workflow, scrutinize dialog.
1. Start to add a tool, compare dialog.

**Expected behavior**
Tool registration should feature GitHub Apps option similar to workflow registration. 

**Screenshots**
![bug2a](https://user-images.githubusercontent.com/88108675/163269962-234be1f0-4fa8-45a0-a8a8-74745cba8778.JPG)
![bug2b](https://user-images.githubusercontent.com/88108675/163269976-d52ab8f5-b0bf-46cc-afec-928649783346.JPG)

**Additional context**
screenshots from staging, but the behavior is similar on both dev and staging

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2140)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2140
┆Sprint: 101 - Cheeks, Sandy
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Changing this to 1.13, think we need to gather some user feedback/experiences before recommending
