### ISSUE TITLE
Edit and streamline information presented during the new user registration process

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4858]
**Describe the bug**
An excerpt from TLP's user testing feedback, regarding the new user registration process:

> Registration step 2: Do we really want to suggest Set Up Dockstore CLI when registering for the first time? It doesn’t say optional. Seems like an unnecessary barrier for end-users to wade through.
> Registration step 3: Overhaul this setup wizard. It’s overly complicated and does not explain what Dockstore does. It makes a lot of assumptions. 

I believe they are referring to the last two dialog boxes of the registration process.

Evaluate the current process, the feedback, and implement desired changes.

Described in TLP's user testing feedback: https://docs.google.com/document/d/1r77-c4DT9juE7Ps2wtbcy2OnTprevtO7D6S0v_E_k2g/edit?usp=sharing

**To Reproduce**
1. Begin the new user registration process. 
2. Proceed, scrutinizing each step from the point-of-view of the typical user, with the above feedback in mind.

**Expected behavior**
Present the information that is most beneficial, clearly and concisely.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2141)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2141
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by coverbeck** [comment]
Seems to overlap with #4797
