### ISSUE TITLE
Improve feedback upon successful publish/unpublish of workflow

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4859]
**Describe the bug**
When you successfully publish/unpublish a workflow via the button on the entry page, the only feedback, besides the label on the button changing, is a tiny dialog that pops up and says "Getting version's unique file types succeeded."  This is not very useful and might be confusing to the average user.

Discovered while I reviewed the video of TLP's user testing.

**To Reproduce**
1. Go to a workflow page.
2. Press the "Publish"/"Unpublish" button.  You might have to set the default version first.
3. See the tiny dialog with the "weird" message.

**Expected behavior**
A message that confirms that the operation was successful, clearly and unambiguously.

**Screenshots**
![bug3](https://user-images.githubusercontent.com/88108675/163274440-785eea4a-78b6-4669-932a-57b23cf3aca1.JPG)

**Additional context**
 same behavior on dev and staging

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2142)
┆friendlyId: DOCK-2142
┆sprint: Backlog
┆taskType: Story

**Comment by coverbeck** [comment]
Overlaps with #4644
