### ISSUE TITLE
Logged out vs logged in homepages are very different

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4863]
**Context**
During Dockstore storytime today, Julian and I mentioned that Dockstore's homepage should maybe contain some of the information currently on our docs. We then remembered that what a logged out and logged in user sees is different. Even outside the context of documentation though, I think the juxtaposition is a little jarring, and honestly, I really like the look of our logged out homepage and want to see it more often.

**Is your feature request related to a problem? Please describe.**
We seem to be assuming that anyone who is logged into Dockstore has already been sold on Dockstore as a platform and knows how it works, as our homepage for logged in users is totally different than the homepage for logged out users. I'm not sure if that's the approach we should be taken.

**Describe the solution you'd like**
Logged in users should see something like the logged out homepage, with a link that takes them to a "dashboard" or something similar which shows what is the current logged in page.

Additionally, I think "recent activity" should be at the top of the logged in user page/dashboard, rather than a news section followed by links to featured material.

**Describe alternatives you've considered**

* No "dashboard"; logged out and logged in users see the same thing almost everywhere.
* Logged out users see the "news" section that logged in users see.

**Additional context**
![](https://user-images.githubusercontent.com/27784612/164073240-5ef0ecba-3016-467d-8051-7ac64154aa30.png)
![](https://user-images.githubusercontent.com/27784612/164073247-a8d9892d-98f8-44f2-9c48-1e5c87a52f9d.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2145)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2145
┆sprint: 88 Poseidon
┆taskType: Story

**Comment by denis-yuen** [comment]
Note: this is part of the zeplin-based UI redesign
