### ISSUE TITLE
Add non-empty constraints to user profile fields

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4871]
**Is your feature request related to a problem? Please describe.**
This PR https://github.com/dockstore/dockstore/pull/4868 converted empty strings in the `user_profile` table to `null` values, but it did not add non-empty constraints to the columns, which could lead to a regression where empty strings make their way back into the table.

The APIs that we use to get user profile information can use both empty strings and null values to represent the absence of data. Adding non-empty constraints will make it less confusing when dealing with this information. 

**Describe the solution you'd like**
Add non-empty constraints to the columns of the `user_profile` table. 

**Describe alternatives you've considered**
n/a

**Additional context**
Comment from the mentioned PR: https://github.com/dockstore/dockstore/pull/4868#discussion_r856269485

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2148)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2148
┆sprint: 89
┆taskType: Story

**Comment by denis-yuen** [comment]
constraints confirmed after migration
