### ISSUE TITLE
Menu bar items overlap on narrow window on Firefox on Ubuntu

### ISSUE THREAD

**Issue by jessebrennan** [dockstore/dockstore#4872]
**Describe the bug**
Menu bar items overlap on narrow window on Firefox on Ubuntu (see first screenshot). This does not happen with Chrome.

When narrowing the widow further, menu options for "Forum" and "About" disappear (see second screenshot). This does happen on Chrome, so it's probably intentional behavior

**To Reproduce**
Go to the home page, make sure the window is narrow

**Expected behavior**
I should be able to view menu bar items which don't overlap

**Screenshots**
![dockstore](https://user-images.githubusercontent.com/10734740/164789274-bbd0b245-e500-4b92-8e9b-b2eb9d414142.png)
![docstore2](https://user-images.githubusercontent.com/10734740/164789278-2e0e0023-7f4e-4e1f-be22-d7b243e28057.png)

**Desktop (please complete the following information):**

* OS: Menu bar items overlap on narrow window on Firefox on Ubuntu
* Browser: Firefox
* Version 99.0.1 (64-bit)

Let me know if I can help debug this!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2149)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10789">image-20220711-171355.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10790">image-20220711-171419.png</a>
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2149
┆sprint: 89
┆taskType: Story

**Comment by denis-yuen** [comment]
FWIW, I can reproduce. Looks like it happens when the window is just narrow enough to lose icons, but not so narrow that it starts putting the items into a second row

**Comment by aofarrel** [comment]
Can't replicate the overlap on Mac!FireFox, but I can replicate the hidden aspects (including the hidden register button) at a certain point. Also, I can see the logo in the top left corner get bigger when the screen gets smaller?

https://user-images.githubusercontent.com/27784612/165161435-bebba5b3-3f0e-4880-91a4-94225d8368ff.mov
