### ISSUE TITLE
Move/Archive/Delete dev-focused material from our docs

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4873]
**Is your feature request related to a problem? Please describe.**
Our docs range from simple tutorials to brand new users to instructions for developers looking to create new file localization plugins for the Dockstore CLI.

**Describe the solution you'd like**
Some of that information belongs on GitHub repos, some of it should be archived, and some of it should probably be removed altogether.

**Describe alternatives you've considered**
Only reorganizing the docs and keeping everything that is already there, there. I don't think this is a good idea as we already have about 80 pieces of docs.

**Additional context**
This ticket came out of the April 19th storytime.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2150)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2150
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Kinda lean toward https://github.com/dockstore/dockstore/issues/4874 
Reformatting/relinking docs seems like a pain and may be more work than it is worth

**Comment by aofarrel** [comment]
I think this is more or less finished. It could be argued some of the Dockstore CLI stuff is dev-focused, but that's more in the vein of #4874.
