### ISSUE TITLE
Dockstore.org quickstart should not have all of new users install the Dockstore CLI

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4875]
**Is your feature request related to a problem? Please describe.**
The Dockstore CLI is not necessary to install for users who are seeking to launch existing workflows on cloud platforms, or for users who want a Dockstore account to manage existing workflows/tools (either their own, or ones created by a team that they head). We should 

**Describe the solution you'd like**
At the quickstart, ask users if they want to find/cloud-launch existing workflows, register/manage existing workflows, or develop workflows/tools. Based on that, guide them through different activities. Only guide them through Dockstore CLI installation via the quickstart if they want to develop workflows/tools.

**Describe alternatives you've considered**
* Remove the Dockstore quickstart entirely and do not replace it with anything similar 
* Put the information all in the docs instead of dockstore.org (as much as I love docs, this is less "interactive" so I am against this, but I would be in favor of the docs mirroring some of the information/linking back to the quickstart)

**Additional context**
Tangentially related to April 19th storytime, but tbh this confused me all the way back when I was first onboarded to Dockstore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2152)
┆friendlyId: DOCK-2152
┆sprint: Backlog
┆taskType: Story

**Comment by coverbeck** [comment]
Sort of duplicates your #4797. Do you want to close either one?

**Comment by aofarrel** [comment]
Oops! I was afraid I may have done that, so I searched "quickstart" before making this ticket, but the older ticket doesn't use that language. Will close this one.
