### ISSUE TITLE
Quick registering a workflow takes you to your first published workflow, not the workflow you just registered

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4885]
**Describe the bug**
When you go through the quick registration method, after you finish the wizard, you are taken to your alphabetically first published workflow on some GitHub organization/your personal GitHub*. This is especially confusing because our UI tends to hide the unpublished workflow tab where your newly registered workflow actually is.

*My GitHub name starts with A, so it comes alphabetically before any orgs I'm in. Not sure if it's going for alphabetical first github org, or if it always goes for personal orgs.

**To Reproduce**
1. Clone https://dockstore.org/workflows/github.com/dockstore-testing/dockstore-workflow-md5sum-unified/cwl_checker:develop?tab=info to your personal github
2. On my-workflows in dockstore, press the + and go through quick registration
3. Once the wizard is done, see that you are on a totally different workflow page (in my case, bam to cram)

**Expected behavior**
1. I should be taken to the workflow I just registered
2. The publish/unpublished tabs should not be obscuring each other at a window width of 1292 

**Screenshots**
(Sorry for my cursive, the add text part of Preview decided not to work today, and I don't have the patience to wait for Gimp to load.)
<img width="1294" alt="Screen Shot 2022-04-29 at 12 30 57 PM" src="https://user-images.githubusercontent.com/27784612/166058502-9c4adc37-d5ff-40d5-a9ee-7ca378e5476e.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser: Chrome
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0) - 1.12.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9) - 2.9
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.3) - 1.12.3

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2161)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2161
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by denis-yuen** [comment]
> The publish/unpublished tabs should not be obscuring each other at a window width of 1292
 
FWIW, this kicks in for me at a widths of less than 1988
