### ISSUE TITLE
ConstraintViolationException when updating a .dockstore.yml

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4893]
**Describe the bug**
I'm trying to get two workflows by someone else published onto Dockstore via the app. As always I forked the original repo, made a .dockstore.yml on my fork, and went to /my-workflows on Dockstore to ensure that what I offer in my PR is a valid .dockstore.yml. 

[This repo](https://github.com/sheilagaynor/STAAR_workflow) has two workflows, naming them staar-workflow-wdl and staar-workflow-cwl. I confirmed those appeared as expected in my unpublished tab. I then realized [there is already a WDL version on Dockstore](https://dockstore.org/workflows/github.com/sheilagaynor/STAAR_workflow:main?tab=info) which is linked in a [publication](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btac272/6571143), so I decided to get rid of one name field in the .dockstore.yml so that what was previously called staar-workflow-wdl would instead match the name of the existing entry (github.com/sheilagaynor/staar_workflow). I did not create the existing entry, so I know that the entry will not transfer, I'm just making sure I am getting the workflow names to match before I open a PR against the original entry.

Unfortunately, the entries are not updating on Dockstore anymore. The logs keep saying org.hibernate.exception.ConstraintViolationException: could not execute statement

Current version of .dockstore.yml, but you can see in the commit history I've tried a few iterations to no avail: https://github.com/aofarrel/STAAR_workflow/blob/main/.dockstore.yml 

<img width="778" alt="Screen Shot 2022-05-04 at 12 19 56 PM" src="https://user-images.githubusercontent.com/27784612/166809998-fd751eea-2089-4973-9e00-2b0310163208.png">

**To Reproduce**
[See commit history for my fork.](https://github.com/aofarrel/STAAR_workflow/commits/main/.dockstore.yml)

**Expected behavior**
I *think* the issue is that I made a .dockstore.yml with an entry that had a name, then edited the .dockstore.yml to remove that entry's name. If that is the issue, then I should be able to remove the name of an unpublished workflow.

The other part of the issue is that I don't actually know what the issue is. The error message needs to be clearer for users.

**Build**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0) - 1.12.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9) - 2.9
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.3) - 1.12.3
galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2166)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2166
┆sprint: 93- Ursula
┆taskType: Story

**Comment by aofarrel** [comment]
It can't just be removing the name, I think. [This commit](https://github.com/aofarrel/fairyland/commit/5b203dd5ebd971286ab1bb2ae4eb398169ce4667) on my test repo also throws an error. So the .dockstore.yml is probably malformed, but in what way?

<img width="779" alt="Screen Shot 2022-05-04 at 12 36 11 PM" src="https://user-images.githubusercontent.com/27784612/166812566-86e338a9-b4b7-4d40-9370-8101e5b4d2a4.png">

**Comment by denis-yuen** [comment]
Yeah, this needs a better message 
` org.postgresql.util.PSQLException: ERROR: null value in column "name" of relation "author" violates not-null constraint`

Think it's something to do with the two authors at https://github.com/aofarrel/STAAR_workflow/blob/main/.dockstore.yml#L8-L9
It probably should just be one author

Same thing on 14 and 15

**Comment by aofarrel** [comment]
@denis-yuen Your hunch about the authors seems to be correct, but when I delete them, something even stranger happens. https://github.com/dockstore/dockstore/issues/4893
