### ISSUE TITLE
Deleting author from .dockstore.yml results in WDL being interpreted as a CWL

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4894]
**Describe the bug**
Deleting the author information in the .dockstore.yml of https://github.com/dockstore/dockstore/issues/4893, as seen in this [commit](https://github.com/aofarrel/fairyland/commit/f81b700d258ab81ca821631eedd9b52bd1bed666), does not throw an error in the github app logs but does result in the WDL being considered a CWL.

**To Reproduce**
#4893 --> [delete authors](https://github.com/aofarrel/fairyland/commit/f81b700d258ab81ca821631eedd9b52bd1bed666) --> look at unpublished Dockstore entry for the repo (in my case, fairyland) --> select staar-analysis branch --> see WDL is being interpreted as a CWL

**Expected behavior**
If I declare a WDL as a WDL in a .dockstore.yml, then it should be considered a WDL.

**Screenshots**
<img width="773" alt="Screen Shot 2022-05-04 at 12 52 55 PM" src="https://user-images.githubusercontent.com/27784612/166815200-6deba19f-8863-4098-bdfb-d60c9a2eb3bd.png">
<img width="1332" alt="Screen Shot 2022-05-04 at 12 53 43 PM" src="https://user-images.githubusercontent.com/27784612/166815295-5ae65edf-80e0-4f11-a6dd-a7c967af4f66.png">
<img width="1345" alt="Screen Shot 2022-05-04 at 12 51 59 PM" src="https://user-images.githubusercontent.com/27784612/166815054-ad56f56a-fe64-4bd5-aa0b-fcc1bbd7d553.png">
<img width="1387" alt="Screen Shot 2022-05-04 at 12 52 10 PM" src="https://user-images.githubusercontent.com/27784612/166815064-c933a541-9a8f-4c28-8046-c2b75f95ff0a.png">

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2167)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2167
┆sprint: 93- Ursula
┆taskType: Story

**Comment by denis-yuen** [comment]
might be related to https://github.com/dockstore/dockstore/issues/4862

**Comment by denis-yuen** [comment]
(probably not related)

**Comment by coverbeck** [comment]
Can only verify when 1.13.x pushed to staging

**Comment by coverbeck** [comment]
I deleted the author and changed the type of one workflow in a multi-workflow .dockstore.yml from CWL to WDL. It worked as far as I can tell after a push:

1. The workflow whose type I didn't change correctly updated
2. The workflow whose type I did change didn't get updated
3. The app logs showed a good error message, see screenshot.

My nit would be that the logs didn't indicate the other workflow did successfully update, but that's a more general problem we have in not being able to indicate partial success.

![Screen Shot 2022-11-01 at 5 12 47 PM](https://user-images.githubusercontent.com/1049340/199365205-2685451a-4695-4a11-99c4-7b682029d082.png)

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.1) - 1.13.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.1) - 2.10.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.1) - 1.13.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.13.1) - 1.13.1
