### ISSUE TITLE
Add ElasticSearch configuration information to template

### ISSUE THREAD

**Issue by amarjandu** [dockstore/dockstore#4904]
**Is your feature request related to a problem? Please describe.**
When starting up the dockstore-webservice and the dockstore-ui2 (from the develop branch), the UI tries to hit ES thought some requests. This configuration option is missing from the [example configuration file](https://github.com/dockstore/dockstore/blob/develop/dockstore-integration-testing/src/test/resources/dockstore.yml). In order to find out what configuration options need to be added you have to have access to the wiki page [Setting Up Dockstore Locally](https://wiki.oicr.on.ca/display/DOC/Setting+Up+Dockstore+Locally) which has the config information that needs to be added to the config file.

```
esconfiguration:
  port: 9200
  hostname: localhost
```

**Describe the solution you'd like**
Add default config to the template file.

**Describe alternatives you've considered**
NA

**Additional context**
NA

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2169)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2169
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
FWIW, we also have https://github.com/dockstore/compose_setup/blob/develop/templates/web.yml.template
