### ISSUE TITLE
Users can't see ORCID authors for public workflows

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4916]
**Describe the bug**
A user who's not logged in can't see ORCID authors for public workflows because the `GET /workflows​/{workflowId}​/workflowVersions​/{workflowVersionId}​/orcidAuthors` returns 401 Unauthorized. 

A user who is logged in can't see ORCID authors for public workflows they don't own because the endpoint returns a 403 `Forbidden: you do not have the credentials required to access this entry.`

These errors can be seen for workflows without ORCID authors, since this endpoint is called every time a workflow is displayed.

**To Reproduce**
1. Log out of your Dockstore account.
2. Open your developer tools console.
3. Go to a public workflow. (Example, Go to search page and select any of the workflows)
4. View the error in the console.
5. Login to your Dockstore account and repeat steps 2 - 4.

**Expected behavior**
Should not get a `401` or `403` error for the `GET /workflows​/{workflowId}​/workflowVersions​/{workflowVersionId}​/orcidAuthors`endpoint when viewing public workflows.

**Screenshots**
n/a

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0) - 1.12.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9) - 2.9

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.3) - 1.12.3

galaxyParsingLambdaVersion: 0.0.7
 
host location: prod

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2173)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2173
┆sprint: 92- T
┆taskType: Story

**Comment by denis-yuen** [comment]
double-check this after https://github.com/dockstore/dockstore/pull/4918 
seems to be similar code, I remember having to toggle a couple of these in tests

**Comment by coverbeck** [comment]
Confirmed that I can see the ORCID for a public workflow when not logged in.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0) - 1.13.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0) - 2.10.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0) - 1.13.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7
