### ISSUE TITLE
Update roadmap, or remove links to it - TBD

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4941]
**Describe the issue**
On both https://dockstore.org/about and [its docs equivalent](https://docs.dockstore.org/en/stable/dockstore-introduction.html), we link to https://github.com/dockstore/dockstore/wiki/Dockstore-Roadmap, which hasn't been updated since March 2021.

On both the main webpage and the docs version it is under the heading "future plans".

**Expected behavior**
If we are linking people to a roadmap, that roadmap should be updated regularly.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2178)
┆fixVersions: Dockstore 1.14
┆friendlyId: DOCK-2178
┆sprint: 98- Zebra fish
┆taskType: Story

**Comment by denis-yuen** [comment]
THink we're going to update, it might at a get-together some time later in the year though

**Comment by denis-yuen** [comment]
Yeah, I threw in that "past year" reference because we neglected to add a 2022 section and now it seems a little like rewriting history to write a pretend section as if the 1.12 and 1.13 sections were what we intended to do ahead of time. .
