### ISSUE TITLE
Pre 1.13.0 CLI install likely broken for python 3.10 users 

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4961]
**Describe the bug**

Ran into https://github.com/ckan/ckanext-dcat/pull/213  while debugging https://github.com/dockstore/dockstore/pull/4958  build
In short, installation of the CLI dependencies is likely broken for Python 3.10 (possibly 3.9) 

Should not be an issue in CLI 1.13 install since we're past the affected dependency version

**To Reproduce**
Use newer CircleCI machine image like this change https://github.com/dockstore/dockstore/pull/4958/commits/986097f302e6b94ca05c4ab84aaca2bb4faa1ea4 then try to install Dockstore CLI

**Expected behavior**
Backwards compatibility

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2187)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2187
┆sprint: 93- Ursula
┆taskType: Story

**Comment by coverbeck** [comment]
Confirmed that https://dockstore.org/quick-start has instructions for the fallback.
