### ISSUE TITLE
runner_dependencies endpoint does not support prerelease

### ISSUE THREAD

**Issue by amarjandu** [dockstore/dockstore#4981]
**Describe the bug**
PR #4915 validates the client version parameter against regular expression. The regular expression that is used does not support pre-release or metadata within the semvar and needs to be updated.

**To Reproduce**
```
curl -X GET "https://dev.dockstore.net/api/metadata/runner_dependencies?client_version=1.13.0-alpha.7&python_version=3&runner=cwltool&output=text" -H  "accept: application/json"
Invalid value for client version: `1.13.0-alpha.7`. Value must be like `1.13.0`)
```

Related https://app.circleci.com/pipelines/github/dockstore/dockstore-cli/1095/workflows/606e0ab4-0745-4605-9ac3-a1817cdeaa2a/jobs/4007/steps

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2193)
┆friendlyId: DOCK-2193
┆sprint: 90- Rusalka
┆taskType: Story

**Comment by coverbeck** [comment]
Verified the curl command in the description now works.

[Webservice](https://github.com/dockstore/dockstore/commits/1bf8045) - 1bf8045

[UI](https://github.com/dockstore/dockstore-ui2/commits/89b50d3b) - 2.9.2-89-g89b50d3b

[Compose Setup](https://github.com/dockstore/compose_setup/commits/46fef8e) - 46fef8e

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/b7965d5) - 1.12.6-103-gb7965d5

galaxyParsingLambdaVersion: 0.0.7
