### ISSUE TITLE
Branches with special characters break .dockstore.yml sync

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4993]
**Describe the bug**
A .dockstore.yml workflow will not update on Dockstore (and by extension Terra) any branches that contain the following characters: `(){}<>'Ó` (and possibly others)

**Context**
I have a branch of analysis_pipeline_wdl that has a bugfix involving chrX. [I got a little too clever for my own good and gave the branch a punny name (calling it a pun is a stretch, really)](https://github.com/DataBiosphere/analysis_pipeline_WDL/tree/stop-drop(ing-chr-X)-and-roll). That being said, the name has gotten compliments and helped me find this bug, which I take to mean I should name all of my branches with puns going forward.

**To Reproduce**
1. Have any valid .dockstore.yml repo
2. Create a new branch with `(` in the title, or whatever other special character you're in the mood to test
3. Go to Dockstore's github app logs and see the failure
4. Confirm that adding brand new branches with no special characters doesn't error and does update successfully (ie not just a temporary hiccup)

**Expected behavior**
For Dockstore to be truly international I'd prefer the first option, but there's four possible routes we could take this:
* Support all characters that GitHub allows in branch names
* Support parenthesis, apostrophes, CJK characters, and accented roman characters; and document which characters cannot be used
* Support all ASCII extended characters, which includes accented roman characters
* Support basic ASCII characters such as apostrophes -- we don't need to support [Little Bobby Tables](https://xkcd.com/327/), but I'd appreciate it if we at least support [me](https://en.wikipedia.org/wiki/O%27Farrell)

**Screenshots**
Problematic branch in question plus the error itself
![Screen Shot 2022-07-06 at 3 35 41 PM](https://user-images.githubusercontent.com/27784612/177655906-e85883e0-73ca-4f5e-974c-9d97c295e476.png)

General testing (aaaaaaa did work)
![Screen Shot 2022-07-06 at 3 35 54 PM](https://user-images.githubusercontent.com/27784612/177655896-2808f20a-e059-4a55-a9f1-5d048b6c0245.png)

💔
![Screen Shot 2022-07-06 at 3 49 34 PM](https://user-images.githubusercontent.com/27784612/177655975-e5d185f7-bc5b-49ae-a53c-e3e04a8cafe1.png)

**Desktop (please complete the following information):**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0) - 1.12.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9) - 2.9
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.3) - 1.12.3
galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2195)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2195
┆Sprint: 106 - Don River
┆Issue Type: Story

**Comment by aofarrel** [comment]
@denis-yuen Do you think it is worth documenting this limitation in the meantime?

**Comment by denis-yuen** [comment]
Some of these should work barring restrictions in https://git-scm.com/docs/git-check-ref-format

**Comment by coverbeck** [comment]
In qa, added, then deleted `stop-drop\(ing-chr-X` branch, and it properly showed up, then went away.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
