### ISSUE TITLE
Most starred workflows not appearing at the top of search

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5016]
**Describe the bug**
When you go the search page, the most starred workflows are not at the top of the list.

This is in prod. Seems to work in dev, and might work in staging (workflows with more stars).

I didn't investigate tools; it's presumably the same issue, but needs to be researched.

**To Reproduce**
1. Go to [search](https://dockstore.org/search?entryType=workflows&searchMode=files)
2. Observe how the first workflow in the list has 2 stars
3. Select Galaxy from the language facet
4. Note how several of the workflows there have 13 stars.

**Expected behavior**
I expect that the most starred workflows would appear at the top. I think that's been our behavior.

Click on the sort column header only sorts the workflows that are in the browser (they're fetched in batches), not all workflows, so that doesn't help.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.2) - 1.12.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9.2) - 2.9.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.2) - 1.12.2

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2201)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2201
┆sprint: 91- Sheldon
┆taskType: Story

**Comment by denis-yuen** [comment]
interesting, for implementer can compare with https://dockstore.org/workflows and https://dockstore.org/tools
(doing this comparison, its not quite right for tools either but the issue is more glaring for workflows)

**Comment by denis-yuen** [comment]
note: a reindex changed the order somewhat, wonder if we've hit some sort of threshold 
also all the highly scoring galaxy workflows are missing

**Comment by coverbeck** [comment]
Hmm, I don't think we're requesting a sort order at all and maybe we've been relying on the client-side sorting, which has less coverage as our content grows.

https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html -- I don't see a sort in the request body. But I also don't know the ES code very well, so I may be overlooking something.
