### ISSUE TITLE
Smoke tests should test hiding/unhiding a workflow version

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5017]
**Is your feature request related to a problem? Please describe.**
The smoke tests don't test hiding and unhiding a workflow version, so when we are testing a new deployment, we have to manually run that test.

**Describe the solution you'd like**
Add a test that hides and unhides a version.

**Describe alternatives you've considered**
Continue the painstaking, laborious process of manually testing the feature when we deploy a new release.

**Additional context**
We already have a [smoke test](https://github.com/dockstore/dockstore-ui2/blob/b816e88c38018b5b9ef888e9d9d5211abcbbd94b/cypress/integration/smokeTests/sharedTests/auth-tests.ts#L183) for hiding and unhiding a tool version; should be easy to use as a base for workflows.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2202)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2202
┆sprint: 94- Vampire Pleco
┆taskType: Story

**Comment by fhembroff** [comment]
Created this PR with some (hopefully) helpful comments https://github.com/dockstore/dockstore-ui2/pull/1601. Unfortunately it is unfinished.
