### ISSUE TITLE
Remove 1.13 stuff in documentation stable branch

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5026]
**Describe the bug**
On our documentation repo, develop got merged/rebased/cherrypicked into the hotfix/1.12.2 branch. There's 99% chance I'm the guy who did this, so I'm going to be the guy who fixes it. The rebase/merge/whatever doesn't break anything, but it does include a few small details about the next release (such as which version of Cromwell 1.13 will be using). 

**To Reproduce**
You can see 1.13 referenced in https://docs.dockstore.org/en/stable/advanced-topics/dockstore-cli/advanced-features.html?highlight=cromwell#wdl-launcher-configuration

**Expected behavior**
~Ash is banned from using `git rebase`~ 1.13 should not be referenced on master/stable

**Additional context**
I found this issue this afternoon. Charles and I did some digging, using the addition of images to index.rst (which should be on only develop due to [not being on 1.12's release branch](https://github.com/dockstore/dockstore-documentation/pull/170#issuecomment-1075628831)) as our clue. Charles found the comment "merged commit 9748946" in https://github.com/dockstore/dockstore-documentation/pull/206, so that's probably where the rebase happened. Knowing me, I did it to bring in a linkcheck fix.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2206)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2206
┆sprint: 94- Vampire Pleco
┆taskType: Story

**Comment by denis-yuen** [comment]
> here's 99% chance I'm the guy who did this, so I'm going to be the guy who fixes it.

:grin:

**Comment by aofarrel** [comment]
@denis-yuen I tried, but I don't have the permissions required to do this in a timely manner. The change to be made [is just this](https://github.com/dockstore/dockstore-documentation/pull/214/files). I would recommend someone with the proper permissions just make this commit on stable and push it. It could be done with our hubflow tooling but it will require you immediately undo the commit on develop again.
