### ISSUE TITLE
DNAstack WDL import warnings persist in Launch with box

### ISSUE THREAD

**Issue by dpark01** [dockstore/dockstore#5028]
**Describe the bug**
Although the DNAstack "launch with" button has been removed from the public pages of WDL workflows, there is a DNAstack-specific warning message that is still displayed for any WDL containing imports. The message reads:

> Warning: this version of the WDL has imports, which are not supported by DNAstack. Make sure to select a version without imports in DNAstack.

**To Reproduce**
1. Go to a WDL workflow with imports (e.g. https://dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/align_and_count:master?tab=info)
2. Note the warning about DNAstack in the Launch with box, even though there is no DNAstack button in the launch with box.

**Expected behavior**
This warning can be removed, as all remaining WDL-supporting launch with platforms support imports.

**Screenshots**
<img width="314" alt="Screen Shot 2022-07-19 at 4 21 42 PM" src="https://user-images.githubusercontent.com/8513746/179841290-a8ce9338-173c-4429-8551-29bebe6b78d3.png">

**Desktop (please complete the following information):**
 - Browser: Chrome

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2208)
┆friendlyId: DOCK-2208
┆sprint: 92- T
┆taskType: Story

**Comment by coverbeck** [comment]
Confirmed that this is working correctly in prod:

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0) - 1.13.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0) - 2.10.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0) - 1.13.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7
