### ISSUE TITLE
Error when adding master version of a workflow to Category on staging

### ISSUE THREAD

**Issue by avani-k** [dockstore/dockstore#5040]
**Describe the bug**
While adding a [Broad Institute Viral Genomics workflow](https://staging.dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/assemble_denovo:master?tab=info) to a Category on [staging](https://staging.dockstore.org/), an error popped up when the master version was selected. The workflow could be added successfully when another version was chosen.

**To Reproduce**
1. Go to [Dockstore staging](https://staging.dockstore.org/)
2. Click on Organizations > Broad Institute > Viral Pipelines > [assemble_denovo](https://staging.dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/assemble_denovo:master?tab=info)
3. Click on **+Add to my collection** in the bottom right corner.
4. Choose Dockstore for Organization, COVID-19 for Collection, master for version and click on **+Add to my collection**

**Expected behavior**
Workflow gets added to category, the category label is added in the workflow description at the top and a message saying **Adding to collection succeeded** is displayed.

**Screenshots**
<img width="1460" alt="Screen Shot 2022-07-28 at 11 31 25 AM" src="https://user-images.githubusercontent.com/83619546/181613800-cbf061cf-4cda-470a-8dc2-d5e2ed7123c6.png">

**Desktop (please complete the following information):**
 - iOS: [e.g. iOS]
 - Google Chrome

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2212)
┆friendlyId: DOCK-2212
┆sprint: Backlog
┆taskType: Story

**Comment by avani-k** [comment]
Faced the same issue with [SARS-CoV-2 Lineages workflow](https://staging.dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/sarscov2_lineages:master?tab=info).

**Comment by svonworl** [comment]
Is it possible that the particular entry+version that you tried to add was already in the Category?  That error message would be consistent with that situation...

**Comment by avani-k** [comment]
I just rechecked and that is true. It is interesting though that I did not see this category tag when I was looking at the workflow before trying to add it to the category. There is no way to reproduce that now and to check if it was actually a bug or that I did not see it. In any case, makes sense to close this right now.
