### ISSUE TITLE
TRS files endpoint is inefficient

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5069]
**Describe the bug**
Fetching the files for a workflow using the TRS endpoint causes 792 JDBC statements to be executed.

**To Reproduce**
1. Run web server locally, turn on StatisticalLoggingSessionEventListener
2. `curl http://localhost:4200/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Fbroadinstitute%2Fgatk%2FMitochondriaPipeline/versions/cn_vcf_header_refactor/WDL/files`
3. In web server logs, see 792 JDBC statements executed.

**Expected behavior**
Fewer JDBC statements

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/9f85da0) - 9f85da0

[UI](https://github.com/dockstore/dockstore-ui2/commits/89b50d3b) - 2.9.2-89-g89b50d3b

[Compose Setup](https://github.com/dockstore/compose_setup/commits/46fef8e) - 46fef8e

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/0ba5e9e) - 1.12.6-104-g0ba5e9e

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2223)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2223
┆sprint: 93- Ursula
┆taskType: Story

**Comment by coverbeck** [comment]
The old [getWorkflowVersions](https://github.com/dockstore/dockstore/blob/0268774c94f40727a3b4badaeaf7c77c425478ce/dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java#L829) problem.

**Comment by denis-yuen** [comment]
Spin-off is https://ucsc-cgl.atlassian.net/browse/SEAB-4725
