### ISSUE TITLE
New Dashboard doesn't distinguish organization statuses

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5113]
**Describe the bug**
When I go to the new dashboard, in the organizations box I see approved, pending, and rejected orgs with no visual distinction.

**To Reproduce**
1. Log-in to dev
2. If you don't have a pending org request, create one or two
3. If you're a curator, reject one of the above request
4. Go to https://dev.dockstore.net/dashboard?newDashboard=
5. See all organizations mixed together

**Expected behavior**
There should be some visual distinction between different types of orgs. There is a "pending" link, but the list doesn't distinguish.

**Screenshots**
![Screen Shot 2022-08-30 at 4 15 05 PM](https://user-images.githubusercontent.com/1049340/187559699-cfe0926f-c53e-41af-adf2-b372b5230bf9.png)

`potato3` has been rejected; `Delme` is pending approval. One cannot tell from the above screenshot.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/commits/995c2c8) - 995c2c8

[UI](https://github.com/dockstore/dockstore-ui2/commits/fef68a49) - 2.9.2-111-gfef68a49

[Compose Setup](https://github.com/dockstore/compose_setup/commits/46fef8e) - 46fef8e

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c313e2c) - 1.12.6-114-gc313e2c

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2235)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2235
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Replaced by https://ucsc-cgl.atlassian.net/browse/SEAB-5267
