### ISSUE TITLE
Experiment with podman

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5119]
**Is your feature request related to a problem? Please describe.**
Experiment with podman and update the documentation at https://docs.dockstore.org/en/stable/advanced-topics/docker-alternatives.html?highlight=rootless%20docker to see whether this combination works well or not. 

**Describe the solution you'd like**
Experiment with wdl, cwl and see how well they currently work with podman. 

**Describe alternatives you've considered**
Consider/ experiment with updating rootless docker documentation while at it

**Additional context**
See details at https://discuss.dockstore.org/t/dockstore-cli-support-podman-alternatrive-docker-or-workaround/5849/2 
https://www.commonwl.org/user_guide/introduction/prerequisites.html
https://github.com/broadinstitute/cromwell/issues/6660

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2236)
┆fixVersions: Dockstore 1.14
┆friendlyId: DOCK-2236
┆sprint: 95- W
┆taskType: Story

**Comment by junaruga** [comment]
Thanks!
