### ISSUE TITLE
GitHub app tool registration link on new dashboard doesn't work

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5123]
**Describe the bug**
The "Manage Dockstore Installations on GitHub" link for registering a GitHub app tool on the new dashboard redirects you to the home page, not the GitHub app installation page.

**To Reproduce**
1. Login to staging
2. Go to https://staging.dockstore.org?newDashboard and click on My Dockstore
3. Click on Register a Tool > Register using GitHub Apps > Next
4. Click on Manage Dockstore Installations on GitHub
5. Observe that it redirects to staging.dockstore.org instead of GitHub.

**Expected behavior**
It should redirect you to GitHub to install the Dockstore GitHub App.

**Screenshots**
Clicking on this button takes you to the home page.
![image](https://user-images.githubusercontent.com/25287123/188895795-a5dd7586-a2b0-47b7-baed-a0ca0489a8ae.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0-rc.0) - 1.13.0-rc.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0-rc.0) - 2.10.0-rc.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0-rc.0) - 1.13.0-rc.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2239)
┆epic: Reimplement dashboard based on UI design
┆fixVersions: Dockstore 1.14
┆friendlyId: DOCK-2239
┆sprint: 96- X-Ray Tetra
┆taskType: Story

**Comment by svonworl** [comment]
IMHO, this should be a 1.13.x hotfix ticket, since it appears to derail our preferred registration process.

**Comment by denis-yuen** [comment]
> IMHO, this should be a 1.13.x hotfix ticket, since it appears to derail our preferred registration process.

👍

**Comment by coverbeck** [comment]
I was just about to comment on the PR that this should target the hotfix branch, based on the milestone, but then noticed this ticket is for the new dashboard, which is not turned by default for new users and only accessible via a not publicized query parameter, so moving the milestone back to 1.14.

**Comment by denis-yuen** [comment]
> I was just about to comment on the PR that this should target the hotfix branch, based on the milestone, but then noticed this ticket is for the new dashboard, which is not turned by default for new users and only accessible via a not publicized query parameter, so moving the milestone back to 1.14.

👍
