### ISSUE TITLE
Hitting enter when searching for an organization clears the search

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5129]
**Describe the bug**
When you search for an organization on Dockstore, you don't need to hit the enter key as it begins search pretty much immediately. If you hit the enter key out of habit, the search gets cleared immediately and every organization on Dockstore shows up.

**To Reproduce**
1. Go to https://dockstore.org/organizations
2. Click on Search Organizations
3. Type CDPH, but do not hit enter
4. See [CDPHE](https://dockstore.org/organizations/CDPHE) organization show up, as expected
5. Hit enter
6. See that search is blanked and now every organization shows up

**Expected behavior**
When I (needlessly) hit enter when searching, search shouldn't be cleared. Workflow and Tool search does not clear when hitting enter, so this shouldn't be happening for organizations.

**Desktop (please complete the following information):**
 - Browser: Chrome 105.0.5195.102

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.2) - 1.12.2
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9.2) - 2.9.2
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.2) - 1.12.2
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6
galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2243)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2243
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Duplicates https://github.com/dockstore/dockstore/issues/5318 (which I realize is newer, but we already scheduled into a sprint)
