### ISSUE TITLE
Dockstore entry markdown decides "this is a bullet point" differently from GitHub markdown

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5130]
**Describe the bug**
One of my [github-app workflows](https://dockstore.org/workflows/github.com/aofarrel/clockwork-wdl/clockwork_tuberculosis_example:main?tab=info) has a readme with bullet points and bold text. On GitHub the readme renders as expected, but on Dockstore a piece of bold text is being misinterpreted as another bullet point + italics.

The general pattern seems to be:
```
*foo*
 * foo 1
 * foo 2
 
*bar*
 * bar 1
 * bar 2
```
GitHub: "bar is not a bullet point."
Dockstore: "bar is a bullet point."

**To Reproduce**
The formatting above should trigger the issue, but if not, [here's the problematic readme in question](https://github.com/aofarrel/clockwork-wdl/blob/main/README.md).

**Expected behavior**
Markdown is weird and doesn't work the same everywhere, but ideally we should try to match GitHub's version (at least when an entry is pulling from a GH-hosted README.md). Even if we put aside GitHub, I think the fact there is two newlines between the last bullet point and the next piece of text should not result in a bullet point in markdown.

**Screenshots**

github:
<img width="881" alt="git" src="https://user-images.githubusercontent.com/27784612/189465894-d3ec0c85-b91f-47f6-8083-99637f4ee6be.png">

dockstore:
<img width="750" alt="dockstore" src="https://user-images.githubusercontent.com/27784612/189465897-f6e42d56-9c14-4883-9a01-5d44aaaf8224.png">

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.2) - 1.12.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9.2) - 2.9.2

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.2) - 1.12.2

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2244)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2244
┆Sprint: 102 - Dutchman, The Flying
┆Issue Type: Story

**Comment by aofarrel** [comment]
n/b: [GitHub Flavored Markdown](https://github.github.com/gfm/) isn't quite the same as Common Markdown. This may (or may not) be the reason behind this issue.

> GitHub Flavored Markdown, often shortened as GFM, is the dialect of Markdown that is currently supported for user content on GitHub.com and GitHub Enterprise. This formal specification, based on the CommonMark Spec, defines the syntax and semantics of this dialect. GFM is a strict superset of CommonMark. All the features which are supported in GitHub user content and that are not specified on the original CommonMark Spec are hence known as extensions, and highlighted as such.

[Here's GFM's specification on bullet points.](https://github.github.com/gfm/#list-items)

**Comment by denis-yuen** [comment]
Ok, we may or may not have the ability to totally match then since they didn't follow a standard :grimacing:

**Comment by aofarrel** [comment]
@denis-yuen I think this is actually a bug -- it seems that commonmark would render the same way as GFM in this case, which would mean that our commonmark implementation isn't working correctly.

**Comment by aofarrel** [comment]
This is admittedly loose verification compared to analyzing precise wording of the commonmark spec, but I did a quick test on our docs. Our docs use https://github.com/executablebooks/MyST-Parser to handle markdown (most of our docs use RST instead but MD is supported). I peeked at MyST-Parser's testing, and it appears to be using commonmark standards for rendering markdown files. So, under the assumption that if I throw a .md file at our docs, it will be a commonmark implementation I can compare against, I tossed the problematic bit of the readme + the general pattern into our docs.

<img width="860" alt="Screen Shot 2022-09-12 at 12 43 27 PM" src="https://user-images.githubusercontent.com/27784612/189742124-36fe663d-c0dd-4422-bd42-18e05550ba7d.png">

This is what I would expect from a markdown document. The bold (or italic) text is not considered a bullet point, just like on GitHub, but unlike how our main Dockstore website renders markdown.

**Comment by aofarrel** [comment]
I don't know what y'all did in UI 2.10 but it seems this isn't an issue anymore/at the moment. Agreed with Denis' comment above that this may still be looking into.

<img width="746" alt="fixed?" src="https://user-images.githubusercontent.com/27784612/195925699-681ff819-fe0b-4d2e-990d-04b7f1a60f4a.png">

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0) - 1.13.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0) - 2.10.0
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0) - 1.13.0
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6
