### ISSUE TITLE
Inconsistencies with dates for entries and their versions for tools

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#514]
Tools:

* Last build only available for Automated build Quay.io
  * Non-auto tools show N/A
  * Non-automated Quay.io tools show upload date of image (if it is available from the API)
* Last Modified shows last modification of source code of any version
  * Any update to the source code should update the last modified date
  * Currently is wrong, displays when you last hit refresh button

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-9)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-9
┆Epic: Dates

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/issues/331

**Comment by coverbeck** [comment]
@agduncan94, in my tests the `Last build` looks to be correct. Does this issue still happen for you?

Regarding `Last Modified`, that label no longer exists, and it looks like it has been renamed to `Last Updated`. It shows when information was last fetched/refreshed. Although I find its location and label a little confusing, I believe it's behaving correctly.

I suggest we either leave this as is, or we change the layout, maybe moving the `Last Updated` to the top, above the tabs. And/or change the label, although I'm don't know to what... `Last Refreshed`?

I want to make sure that I'm not missing something in your report first.

Thanks,

Charles

**Comment by agduncan94** [comment]
@coverbeck Last build seems to be right. 

As for Last Modified (which is now Last Updated), I agree that it might be too vague. I'm not sure why we changed from Last Modified to Last Updated. I think we need to figure out what we would rather have, Last Refreshed (time of last refresh on dockstore) or Last Modified (time of last update to the sourcecode). Whichever we chose, we would need to make it consistent with workflows.

@denis-yuen @garyluu Do you think it makes more sense to store the last time source control was updated, or last time an entry was refreshed?

For the location, I think it makes sense putting it in a place where it is more noticeable.

**Comment by denis-yuen** [comment]
As an update, date modified would in fact be useful for tools and workflows. 
Basically, it would be nice to see when a tool or workflow was last touched in the underlying source control or Docker repo. 

I also noticed an oversight. The DB doesn't store original publication time/date which is annoying. I think the closest we can get is to make sure dates work on the versions of tools and workflows so we can pick out the oldest one.

**Comment by denis-yuen** [comment]
See also #514  for a partial implementation of pulling down dates from github

**Comment by NatalieEO** [comment]
replaced by #2598 #2597 #2570
