### ISSUE TITLE
Dockstore does not recognize all valid GitHub branch/tag names

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5141]
**Describe the bug**
Some valid GitHub branch/tag names will not be read into Dockstore. These include names with accented characters, as well as certain other characters. This restriction may only happen for .dockstore.yml based workflows (unproven).

**To Reproduce**
I didn't reproduce, but see discussion [here](https://github.com/dockstore/dockstore-documentation/pull/229#discussion_r976574435).

**Expected behavior**
If a branch/tag exists in GitHub, Dockstore should be able to process it. Although there may be some other issues we need to consider; see #5005 for SourceFile names.

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0) - 1.13.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0) - 2.10.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0) - 1.13.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2250)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2250
┆Sprint: 106 - Don River
┆Issue Type: Story

**Comment by coverbeck** [comment]
Note: if/when this is fixed, be sure to revert or tweak dockstore/dockstore-documentation#229 to match the new fixed behavior.

**Comment by aofarrel** [comment]
Related but not equivalent: https://github.com/dockstore/dockstore/issues/5143

**Comment by denis-yuen** [comment]
Will take a look, note https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names#naming-branches-and-tags though. This is probably the definition that we started with, I'll try to figure out a safe way to expand

**Comment by denis-yuen** [comment]
Some of these should work barring restrictions in https://git-scm.com/docs/git-check-ref-format
