### ISSUE TITLE
GH branch-regex doesn't seem to work as expected with leading characters

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5143]
**Describe the bug**
As discussed in https://github.com/dockstore/dockstore-documentation/pull/229, we use this regex string when parsing branches from GitHub via the Dockstore GHA: `([a-zA-Z0-9]+([./_-]?[a-zA-Z0-9]+)*)$`

My grasp of regular expressions is shaky at best, but something about it looked a little odd. It seems that it's intended to disallow leading underscores, periods, forward slashes, and dashes whilst still allowing them elsewhere. Playing around with regxr.com indicates that it might actually be matching everything *after* a leading [./_-] -- for example, it seems that a branch named `foo_bar` will return `foo_bar` as expected, but a branch named `_foobar` will return `foobar` which likely isn't the name of any actual branch.

I could very well be barking up the wrong tree here, but the logs are giving me reason to suspect something isn't being handled the same way as most disallowed branch names are. I suspect every workflow in the repo might be trying to look up a branch that doesn't exist.

**To Reproduce**
1. Give an existing GHA repo a new branch named `_leadingunderscore`
2. Make a cupán tae
3. Check Dockstore and notice the "repo last modified" hasn't changed
4. Check the GitHub App logs for the relevant organization and notice there is one error per workflow in the .dockstore.yml rather than one error for the whole repo

**Expected behavior**
Either:
 * Branches with leading periods, dashes, underscores, and forward slashes should work
 * Branches with leading periods, dashes, underscores, and forward slashes should be blocked, but should throw the same error as any other branch with special characters

**Screenshots**
Leading underscore log:
<img width="780" alt="Screen Shot 2022-09-22 at 1 43 38 PM" src="https://user-images.githubusercontent.com/27784612/191849859-d37e16d6-dfe5-4139-a12c-8a3209505577.png">

Compare that to most other branches with special characters:
<img width="780" alt="Screen Shot 2022-09-22 at 1 59 29 PM" src="https://user-images.githubusercontent.com/27784612/191849996-0e1af8d9-bc65-43cc-8e42-c6252ad51228.png">

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0) - 1.13.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0) - 2.10.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0) - 1.13.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2252)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2252
┆Sprint: 106 - Don River
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Good find. Also, gross.

**Comment by denis-yuen** [comment]
>  leading periods, dashes, underscores, and forward slashes 

Some of these should work barring restrictions in https://git-scm.com/docs/git-check-ref-format
