### ISSUE TITLE
Facetted search may be under reporting workflows reported by workflow language

### ISSUE THREAD

**Issue by bvizzier** [dockstore/dockstore#5154]
**Describe the bug**
I'm looking to automate some reporting and downloaded a copy of the production database (2022-09-28T05-01-31+0000) and installed it locally.  I then started executing some queries.  The general form of the query is:

`select workflowname, dbupdatedate, organization, repository, descriptortype from workflow where ispublished = true AND descriptortype = 'wdl' ORDER BY workflowname;`

When I execute the command, I obtain a value of 1493.  According to the faceted search, there are 1342 WDL workflows.

|Workflow Language|Faceted Search|SQL Query| |
|----|----|----|----|
|WDL|1342|1493| |
|CWL|202|220| |
|Nextflow|55|57| |
|Galaxy|30|31| |

It makes sense to me that we filter some internal/test workflows; however, I can't find a query that produces the same numbers.

svonworl did a bit of investigation and found some inconsistencies that indicate some workflows may be missing from the ElasticSearch query results.  I'll let him report on his findings.

svonworl here!  My findings follow:

If you modify Ben’s query above to exclude checker workflows, it matches our ElasticSearch (ES) filtering logic, and the number of workflows returned by the query should match the number reported in the “WDL” part of the search facet.  However, as 29/Sep/2022, on prod, this was not the case, the facet reported a significantly smaller number of workflows than the query.

Some investigation indicated that at that time, on prod, there were published workflows that appeared on the site that did not appear in the search results.  For example, [https://dockstore.org/workflows/dockstore.org/yuliamostovoy/KmerCount](https://dockstore.org/workflows/dockstore.org/yuliamostovoy/KmerCount|smart-link) did not appear when searching for the keyword ‘yuliamostovoy’.

Upon downloading and installing the prod db locally, these entries did appear in the search results in my local install, and the query count and search facet count were the same.

A likely cause is that a fraction of published workflows were not indexed in prod ES for some (currently unknown) reason.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2257)
┆fixVersions: Dockstore 1.13.x
┆friendlyId: DOCK-2257
┆sprint: 97- Yazoo Darter
┆taskType: Story

**Comment by coverbeck** [comment]
As temporary fix, try reindexing. Check if staging has same problem, and try there first.

**Comment by coverbeck** [comment]
On staging before reindex:

858 WDL, 201 CWL, 44 Nextflow, 26 Galaxy.

After reindex: 883 WDL, 201 CWL, 44 Nextflow, 26 Galaxy. Still a big gap. I wonder if we're missing something in the SQL query, or if we're (intentionally?) skipping something in the ES code.

**Comment by coverbeck** [comment]
If I reindex locally with a snapshot of staging data, I correctly get 1,058 WDL, 209 CWL, 46, Nextflow and 28 Galaxy, which adds up to 1,341.

**Comment by coverbeck** [comment]
qa: 1,135 faceted workflows, 1,248 published and not checkers before reindex; after reindex: 1,129 faceted workflows (it actually went down!).

**Comment by coverbeck** [comment]
Upgraded the ES instances on qa, reindexed again, and this time got 1,240, which is closer to 1,248. Noticed two "Executing bulk [37] with 4 requests" followed by "413 Request Entity Too Large" in the logs, which could explain the difference of 8.

See this Stackoverflow [post](https://stackoverflow.com/questions/70905693/transporterror413-during-bulk-request-into-elasticsearch-via-python) -- similar confusion; we're setting the it to 2.5Mb [here](https://github.com/dockstore/dockstore/blob/dfa2cd65405e1a1822eb7b316edba9e8a824d7e9/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/ElasticListener.java#L284), and the default request size should be 100MB. Unless I did the units wrong.

**Comment by coverbeck** [comment]
AWS OpenSearch sets its own limits; 10MB in our case: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/limits.html#network-limits

**Comment by coverbeck** [comment]
I think there is one main issue going on here: we are occasionally submitting requests with > 10MB payloads. This is caused by #5042 -- we submitting the source files from all of versions. This problem causes an entire bulk request to fail, e.g., if you have a bulk request with 3 entries with sizes 1MB, 1MB, and 9MB, all 3 entries will fail to index.

Reindexing a recent prod snapshot locally, with the same max request limit as AWS OS, only successfully reindexes 1,632 out of 1,793 published workflows.

A hypothetical but probable secondary issue is that if ES is unresponsive (due to it being underpowered), the [code to update ES](https://github.com/dockstore/dockstore/blob/d70b474dcdc6dcb6807f7c89d718cb45d3467b1d/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java#L953) will fail silently and the index won't get updated.

**Comment by coverbeck** [comment]
If there's a default version, we only submit the default version's source files for indexing. But if there isn't, we submit the source files from all version. See [code](https://github.com/dockstore/dockstore/blob/dfa2cd65405e1a1822eb7b316edba9e8a824d7e9/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/ElasticListener.java#L398).

**Comment by bvizzier** [comment]
For the record, the query also needs to contain "`AND ischecker = false`":

`select workflowname, dbupdatedate, organization, repository, descriptortype from workflow where ispublished = true AND ischecker = false AND descriptortype = 'wdl' ORDER BY workflowname;`

The numbers now match using that query (modified for the appropriate language).
