### ISSUE TITLE
UI's README.md instructions for local install are out of date (Mac and front-end)

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5165]
**Describe the bug**

At a skim, noticed the following:

* ~Mentions Java 8 -- may work, but we're pushing Java 11 and 17 in our Java repos, so we shouldn't be asking developers to install an older version of Java~
* ~Installs Angular ng globally, which we don't do any more (prefer npx)~
* ~I think we require Node 14 (README says 10)~
* ~Add instructions for Apple Silicon ([this page](https://devzilla.io/using-nodejs-14-with-mac-silicon-m1) was helpful, as there is no Apple Silicon build of node 14 (only starts in 16)~

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2258)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2258
┆Sprint: 105 - Colorado
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Did 1 and 3 in https://github.com/dockstore/dockstore-ui2/pull/1690

**Comment by coverbeck** [comment]
> Add instructions for Apple Silicon ([this page](https://devzilla.io/using-nodejs-14-with-mac-silicon-m1) was helpful, as there is no Apple Silicon build of node 14 (only starts in 16)

The instructions say to install node 18, and installing node 18 with nvm correctly installs the Apple Silicon version on my M1. So removing that.
