### ISSUE TITLE
Unable to retrieve files with Unencoded "parent directory" ../ in the path

### ISSUE THREAD

**Issue by patmagee** [dockstore/dockstore#5182]
**Describe the bug**
(This is a similar case to https://github.com/dockstore/dockstore/issues/2255)

The TRS specification requires file paths to be retrievable with encoded AND unencoded paths. In general, resolving files via TRS works for all unencoded symbols except for a "parent dirctory" `../` in the path. If there is a literal `../` in the path then the API returns 404, whereas encoding the `../` to `..%2F` will result in the actual file contents being returned

**To Reproduce**
1.  Retrieve the list of  files for a workflow with parent directories in the paths (ie https://staging.dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/CWL/files) 
2. using curl, attempt to resolve a workflow with parent directories
3. receive a 404 error `{"code":404,"message":"HTTP 404 Not Found"}`

**Expected behavior**
To retrieve the actual content

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2264)
┆Fix Versions: Dockstore 1.13.x
┆Issue Number: DOCK-2264
┆Sprint: 103 - Arroyo Seco
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Apologies for the delay (grant reporting). 

Can confirm the issue 
```
 2012  curl http://phoenix:4200/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/PLAIN_CWL/descriptor/..%2F..%2Ftools%2Fsamtools_idxstats.cwl
 2013  curl http://phoenix:4200/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/PLAIN_CWL/descriptor/../../tools/samtools_idxstats.cwl
```
correspond to 
```
127.0.0.1 - - [09/Nov./2022:21:11:13 +0000] "GET /ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/PLAIN_CWL/descriptor/..%2F..%2Ftools%2Fsamtools_idxstats.cwl HTTP/1.1" 200 818 "-" "curl/7.81.0" 3312
127.0.0.1 - - [09/Nov./2022:21:11:18 +0000] "GET /ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/tools/samtools_idxstats.cwl HTTP/1.1" 404 43 "-" "curl/7.81.0" 8
```

**Comment by denis-yuen** [comment]
Oh
```
curl --path-as-is https://staging.dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2FNCI-GDC%2Fgdc-dnaseq-cwl%2FGDC_DNASeq/versions/master/PLAIN_CWL/descriptor/../../tools/samtools_idxstats.cwl | head -n 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   818  100   818    0     0   1916      0 --:--:-- --:--:-- --:--:--  1920
#!/usr/bin/env cwl-runner
#$namespaces:"
  #edam: "http://edamontology.org/"
cwlVersion: v1.0
```
is fine.

FYI @patmagee , can you confirm this isn't what you ran into?

**Comment by denis-yuen** [comment]
FYI, re-tagging @patmagee in case it was missed

**Comment by denis-yuen** [comment]
(re-open if this comes up again)
