### ISSUE TITLE
Remove @ngx-lite/json-ld

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5218]
**Is your feature request related to a problem? Please describe.**
Updating Angular is a pain because `@ngx-lite/json-ld is` using an old version of Angular. The repo is also not getting much activity.

**Describe the solution you'd like**
Remove it. We're using it for json-ld on some pages; either reimplement or reuse some of the code from `@ngx-lite/json-ld`. Or drop the json-ld support in Dockstore -- it doesn't seem like it's got a lot of traction.

**Describe alternatives you've considered**
Continue as is -- seems to install and work with `--legacy-peer-deps`.

**Additional context**
Issue modeled after #4265 :)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2272)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2272
┆Sprint: 100 - Betsy Crabs
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Look at old PRs, see if we added this for google search or other. 
Does this end up actually working? Or did we get stymied and never actually completed, otherwise could remove
