### ISSUE TITLE
CLI should only log if --debug command line switch is used

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5223]
**Is your feature request related to a problem? Please describe.**
CLI output is sometimes difficult to read by the end-user because we use the `Logger`for stack traces  and (some) messages. The stack traces are typically only of interest to developers of the CLI, and the messages' formats are more machine friendly than user-friendly.

**Describe the solution you'd like**
We should only use the logger if the CLI's existing `--debug` command line switch is used. This will allow developers to get the additional information if tracing down bugs, but won't by default clutter up the end-user experience.

**Describe alternatives you've considered**
Leave it

**Additional context**
See #5186 for an example of a stack trace cluttering up the screen.

And here's another one -- the user only cares about the message `dockstore: foo is not a dockstore command. See 'dockstore --help'.` -- not the timestamp, nor the class the message is coming from.

```
dockstore foo
09:18:27.756 [main] ERROR io.dockstore.client.cli.ArgumentUtility - dockstore: foo is not a dockstore command. See 'dockstore --help'.
```

These are just two examples. The implementer will have to go through all the code to address this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2275)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2275
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by coverbeck** [comment]
I didn't know, but there's also an undocumented `--info` switch, which we could perhaps trigger off.

**Comment by denis-yuen** [comment]
(may be done already, @fhembroff to link ticket)

**Comment by coverbeck** [comment]
Verified this works as expected in 1.14.0-SNAPSHOT
