### ISSUE TITLE
Hookup TRS to descriptor type versions

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5247]
**Is your feature request related to a problem? Please describe.**
After this information is available, hook it up to TRS

**Additional context**
Blocked by https://ucsc-cgl.atlassian.net/browse/SEAB-4857
#4320

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2282)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2282
┆Sprint: 104 - Blue Nile
┆Issue Type: Story

**Comment by coverbeck** [comment]
On QA, the text on the swagger page still says 2.0.0, although the link is correctly 2.0.1:
![Screen Shot 2023-01-10 at 9 35 27 AM](https://user-images.githubusercontent.com/1049340/211622434-e35c033a-244a-4bb3-b79a-30d4aaf33149.png)

**Comment by coverbeck** [comment]
Workflow language versions work as expected in QA.

On the format zip, it now looks like the Accept header is the only thing that matters, and the query parameter is irrelevant. For example, `curl -X 'GET' 'https://qa.dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Fcoverbeck%2Fdockstore-whalesay-wdl-only/versions/master/WDL/files?format=zip'` leads to a 400 response, whereas, no query parameter, `curl -X 'GET' 'https://qa.dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Fcoverbeck%2Fdockstore-whalesay-wdl-only/versions/master/WDL/files?' -H "Accept: application/zip` returns a zip. 

Whether the response is a ZIP is purely determined by `Accept: application/zip`. I think this is the correct behavior, although it's a little confusing given that the query parameter is baked into the spec.

I think it'll be OK, but I want to make sure you're aware of the behavior.

**Comment by denis-yuen** [comment]
Hmmm, I think that is a bug.
 It should use the query parameter when there is no accept header or the accept header is a wildcard.
