### ISSUE TITLE
Update logged-in user drop down to match UI redesign

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5261]
**Is your feature request related to a problem? Please describe.**
Currently, the logged-in user drop down looks like:
![image](https://user-images.githubusercontent.com/25287123/205333834-fc429ea8-58d7-4d3e-bb89-fa66d849d0ad.png)

In the UI redesign, the logged-in user drop down looks like:
![image](https://user-images.githubusercontent.com/25287123/205333989-750ace27-f123-483e-9c3b-31633e158b0f.png)
 
The redesigned logged-in user button/drop down looks better because it matches the hover behaviour of other navigation buttons. It's also cleaner because it doesn't repeat the sidebar buttons (My Workflows/Tools/etc).

**Describe the solution you'd like**
Implement the logged-in user drop down according to the UI mockup: https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/6022acb6632937281e6935ec

**Describe alternatives you've considered**
Leave as is

**Additional context**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2290)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2290
┆Sprint: 104 - Blue Nile
┆Issue Type: Story

**Comment by coverbeck** [comment]
Confirmed this is addressed in QA.
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/500294a) - 500294a

[UI](https://github.com/dockstore/dockstore-ui2/commits/6cbb12f7) - 2.10.1-95-g6cbb12f7

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
