### ISSUE TITLE
Validate BioData Catalyst logos

### ISSUE THREAD

**Issue by bvizzier** [dockstore/dockstore#5262]
**Is your feature request related to a problem? Please describe.**

BioData Catalyst® has recently updated its logo and name usage.   

https://www.biodatacatalyst.org/consortium-resources/bdcatalyst-branding/

**Describe the solution you'd like**

Validate that Dockstore is complying with the new requirements.

**Describe alternatives you've considered**

NA

**Additional context**

NA

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2291)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10887">BDC-Logos.zip</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10885">BioDataCatalyst-StyleGuide.pdf</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10886">Color Icons.zip</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10888">Gray Icons.zip</a>
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2291
┆Sprint: 104 - Blue Nile
┆Issue Type: Story

**Comment by coverbeck** [comment]
Confirmed that logos are correctly updated.
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
