### ISSUE TITLE
Implement language version parsing for CWL

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5267]
**Is your feature request related to a problem? Please describe.**
View the description of https://github.com/dockstore/dockstore/issues/4320

**Describe the solution you'd like**
Parse CWL descriptor files for the language version and set it for CWL `SourceFile`'s and CWL entry `Version`'s. Note that CWL workflows can have tools of mixed versions.

**Describe alternatives you've considered**
n/a

**Additional context**
Follow up work for https://github.com/dockstore/dockstore/issues/4320

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2293)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2293
┆Sprint: 103 - Arroyo Seco
┆Issue Type: Story

**Comment by coverbeck** [comment]
I can see language version facets in QA search for CWL workflows.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
