### ISSUE TITLE
Valid .dockstore.yml wf does not appear in unpublished tab

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5272]
**Describe the bug**
There's [a WDL I want to test on Terra](https://github.com/aofarrel/Stuart-WDL/blob/segment_scatter/segment_scatter.wdl), but the Broad Methods Repo is throwing 500s left and right today, so I figured I'd put my workflow on Dockstore and import it into my workspace. I threw together [a seemingly valid .dockstore.yml](https://github.com/aofarrel/Stuart-WDL/blob/segment_scatter/.dockstore.yml) on the branch I'm working on (not main) and verified that the Dockstore GH App reported a success.
<img width="1305" alt="Screen Shot 2022-12-06 at 4 32 46 PM" src="https://user-images.githubusercontent.com/27784612/206058009-b913cc1f-d2e9-4af7-8a09-ce3886ceabf1.png">

The workflow isn't showing up in the unpublished workflow section, though.
<img width="798" alt="Screen Shot 2022-12-06 at 4 33 43 PM" src="https://user-images.githubusercontent.com/27784612/206058006-3c84ace9-53e5-425c-b382-53e06344e488.png">

In fact sometimes the section doesn't load at all, or lags a few seconds... more on that here: https://github.com/dockstore/dockstore/issues/5273

**To Reproduce**
It seems unlikely that the Dockstore GitHub App would report a success if I didn't write the .dockstore.yml correctly, so I have a hunch the actual issue is either (A) a UI bug hiding my workflow, or (B) I have too many unpublished workflows under my GitHub username so I've hit an unknown limit. If the answer is A, I don't know how to reproduce it, but if it's B this might be reproducible on anyone else who has been known to create .dockstore.yml files in order to open PRs on other organization's workflows.

**Expected behavior**
The workflow should appear immediately or after a short delay, since the app is reporting a success.

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser: Chrome 107.0.5304.110

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.1) - 1.13.1
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.1) - 2.10.1
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.1) - 1.13.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.13.2) - 1.13.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2297)
┆Issue Number: DOCK-2297
┆Sprint: Backlog
┆Issue Type: Story

**Comment by aofarrel** [comment]
It turns out WDL in question has a circular import which causes womtool to lock up. That probably explains why Terra + Dockstore are locking up. #5273 may be different.

**Comment by aofarrel** [comment]
Confirmed that this is not an issue once the circular imports are resolved.

**Comment by coverbeck** [comment]
Closing in favor of #5274
