### ISSUE TITLE
Unpublished workflows tab sometimes lags or doesn't load at all

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5273]
**Describe the bug**
Sometimes #5272 gets a little bit weird and the contents of the unpublished workflow tab does not load. 

<img width="309" alt="Screen Shot 2022-12-06 at 4 36 14 PM" src="https://user-images.githubusercontent.com/27784612/206060052-ee58800d-9b44-49d9-b88b-1cc45391f310.png">

**To Reproduce**
I haven't nailed down a 100% consistent trigger for the two cases (slow load vs not-at-all) but this seems close:
1. Have 51 unpublished workflows on one GitHub namespace (your personal username or an organization)
2. Go to my-workflows
3. Click the unpublished tab
4. Refresh the page
5. If the contents of the unpublished tab disappears, clear browser cache and refresh again to see it appear after some lagging
6. Refresh the page to see it disappear again
7. Switch to published, then back to unpublished, and see the unpublished workflows come back

**Expected behavior**
Either:
* Our UI is able to load a large page of unpublished workflows quickly and consistently
* Implementing https://github.com/dockstore/dockstore/issues/1201 

**Desktop (please complete the following information):**
* OS: Mac OS Catalina
* Browser: Chrome 107.0.5304.110

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2298)
┆Issue Number: DOCK-2298
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
Closing in favor #5274

**Comment by aofarrel** [comment]
In favor of closing this -- I cannot reproduce this issue after fixing my circular imports.
