### ISSUE TITLE
Disallow very similar entry names

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#5287]
**Describe the bug**
The Dockstore webservice currently allows entries to be created with names that only differ from existing names by capitalization or punctuation.  For example, a user can create three entries, represented simultaneously by different rows in our database, with names `CoolBeans`, `coolbeans`, and `cool-beans`.

In general, this might lead to confusion, it’s probably undesirable for other reasons (some of which we don’t even know yet), and it causes the Discourse topic creation mechanism (see [https://ucsc-cgl.atlassian.net/browse/DOCK-1773](https://ucsc-cgl.atlassian.net/browse/DOCK-1773), #4202), which uses the entry name as the topic title and is not case sensitive, to be unable to create a new topic for one of the entries, because, per its criteria, the topic title is already taken.

**To Reproduce**

1. Load a recent production dump into your database.
1. Run the following SQL query:
`select organization,repository,workflowname,descriptortype,topicid from workflow where organization = 'CDCgov';`
1. Note the two workflows with names `phoenix` and `PHoeNIx`.

**Expected behavior**
Possibly, the webservice should refuse to create a new entry if the new entry name is very similar to an existing entry name, i.e. the same except that it's capitalized and/or punctuated differently.

It's unclear what (if any) action we should take regarding the existing entries with very similar names.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2303)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2303
┆Sprint: 106 - Don River
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Well, this is a terrible sql query but ...
```
webservice_test=# with cte_relevant_workflows as (select * from (select count(*) as count, organization,repository, lower(workflowname) from workflow where workflowname is not null  group by organization, repository, lower(workflowname)) as query where count > 1)select organization,repository,workflowname,descriptortype,topicid, ispublished from workflow where organization in (select organization from cte_relevant_workflows) and repository in (select repository from cte_relevant_workflows) and lower(workflowname) in (select lower from cte_relevant_workflows) order by organization, repository, workflowname;
  organization  |            repository            |       workflowname        | descriptortype | topicid | ispublished 
----------------+----------------------------------+---------------------------+----------------+---------+-------------
 broadinstitute | gatk                             | Funcotator                | wdl            |         | t
 broadinstitute | gatk                             | funcotator                | wdl            |         | f
 broadinstitute | warp                             | CreateSS2AdapterMetadata  | wdl            |         | t
 broadinstitute | warp                             | CreateSs2AdapterMetadata  | wdl            |    4537 | t
 broadinstitute | warp                             | Optimus                   | wdl            |    3797 | t
 CDCgov         | phoenix                          | PHoeNIx                   | nfl            |    5527 | t
 CDCgov         | phoenix                          | phoenix                   | wdl            |         | t
 cwl-apps       | predixcan_tools                  | Predixcan                 | cwl            |         | f
 cwl-apps       | predixcan_tools                  | predixcan                 | cwl            |    4534 | t
 DNAstack       | PacBio-Workflows                 | PacBio-Human-WGS-Workflow | wdl            |         | f
 DNAstack       | PacBio-Workflows                 | Pacbio-Human-WGS-Workflow | wdl            |    5059 | f
 HumanCellAtlas | skylab                           | Optimus                   | wdl            |    3201 | f
 HumanCellAtlas | skylab                           | optimus                   | wdl            |         | f
 Kincekara      | C-BIRD                           | C-BIRD                    | wdl            |    5506 | f
 Kincekara      | C-BIRD                           | c-bird                    | wdl            |         | f
 theiagen       | public_health_bacterial_genomics | BC_N_QC_PE                | wdl            |         | f
 theiagen       | public_health_bacterial_genomics | BC_n_QC_PE                | wdl            |         | f
 theiagen       | public_health_viral_genomics     | SC2_pubRepo_prep_se       | wdl            |         | f
 theiagen       | public_health_viral_genomics     | sc2_pubRepo_prep_se       | wdl            |    4159 | t
 theiagen       | public_health_viral_genomics     | TheiaCoV_Validate         | wdl            |         | t
 theiagen       | public_health_viral_genomics     | TheiaCov_Validate         | wdl            |    4956 | f
 theiagen       | public_health_viral_genomics     | Titan_ClearLabs           | wdl            |         | t
 theiagen       | public_health_viral_genomics     | titan_clearlabs           | wdl            |    4156 | f
 theiagen       | public_health_viral_genomics     | Titan_Illumina_PE         | wdl            |         | t
 theiagen       | public_health_viral_genomics     | Titan_Illumina_pe         | wdl            |    4158 | f

```

**Comment by coverbeck** [comment]
Created a .dockstore.yml with workflows named `Test` and `test`: https://github.com/coverbeck/dockstore-whalesay-wdl-only/blob/test/.dockstore.yml 

Pushed and only the first one, `Test`, got created.

GitHub App logs showed the following. If I didn't know what to expect, the message isn't that helpful in diagnosing the problem for the end-user. But this is a bit of an edge case, so closing.

```
In version 'test' of workflow 'dockstore-whalesay-wdl-only':
...
Error processing workflow coverbeck/dockstore-whalesay-wdl-only/test:
org.hibernate.exception.ConstraintViolationException: could not execute batch
Entry skipped.
```
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
