### ISSUE TITLE
Indicate if an entry is syncing with GitHub Apps

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5331]
**Is your feature request related to a problem? Please describe.**
It's sometimes hard to tell if the Dockstore App has been enabled for a repo. If it's a personal org or you're an admin, it's easy enough, but if you're a member of an organization, you have to ask the admin to look. And even for a personal repo, it would probably be easier to see it right on Dockstore, rather than having to go into GitHub, log-in with your MFA device, etc.

**Describe the solution you'd like**
The UI should indicate whether the Dockstore app is enabled on per entry basis. Probably only in the My Workflows/My Tools page, i.e., don't make that info public.

**Describe alternatives you've considered**
Leave it, document it better.

**Additional context**
See https://ucsc-cgl.atlassian.net/browse/SEAB-5204, which sparked this thought.

**Implementation thoughts**

1. Get the info from the GitHub API, although at a skim, I don't know if that's possible. It would be preferred.
1. We get notified when the app is installed, removed, etc. We could start tracking that in our DB, and then we could calculate whether a repo should have the App installed or not.
  * See above mentioned [SEAB-5204](https://ucsc-cgl.atlassian.net/browse/SEAB-5204), where we're apparently not tracking everything.
  * They'll be a problem with apps installed/removed in the past. We can go through the logs to generate something, but it will be incomplete, e.g., when logging a repo being removed, we don't log it.

[SEAB-5204]: https://ucsc-cgl.atlassian.net/browse/SEAB-5204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2312)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2312
┆Sprint: 135 - Hondarribia
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Amused, there's an app here that files an issue when de-installed https://github.com/MicrosoftDocs/CSIDev-Public/issues/462
