### ISSUE TITLE
Refactor code on the GitHub apps workflow creation path

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#5338]
**Is your feature request related to a problem? Please describe.**
The code that accesses the repo and creates a workflow when handling a GitHub apps push might be able to be improved.

Specifically, some of the involved methods take a confusingly-large number of arguments, which we could reduce, and some of the data structures used to bundle information are quite generic, making it hard to interpret code which uses them.  Related comments and code snippets:
https://github.com/dockstore/dockstore/pull/5329#discussion_r1088214556
https://github.com/dockstore/dockstore/blob/abeccca6dfc52d6042008bd6492b9f26efa3018f/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitHubSourceCodeRepo.java#L745
https://github.com/dockstore/dockstore/blob/abeccca6dfc52d6042008bd6492b9f26efa3018f/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java#L696

Another possible issue is that when handling a push, the associated `.dockstore.yml` is sometimes parsed multiple times, in some cases long after the first parse, thus coupling the involved code directly to the dockstore.yml abstraction.  If we parsed the yaml, and then put the resulting information into a "blueprint"-type object, we could pass it around and avoid said coupling.  Such a scheme would also simplify testing, allow us to implement alternative registration schemes (in which the source information might be stored in a different place/medium), and streamline the addition of new inputs to the system.

**Describe the solution you'd like**
Refactor as above.

**Describe alternatives you've considered**
Leave as is.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2314)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2314
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by svonworl** [comment]
Another improvement would be to refactor so the repo access code is separated from the registration/push processing code.  Right now they are intertwingled, which appears to limit our `.dockstore.yml`-based registration code to supporting github only.  The forementioned refactor would allow us to implement a manual/periodic refresh for other source code control sites or storage systems (if desired), create a mock source code repo for testing purposes, and generally be more understandable and maintainable.

**Comment by coverbeck** [comment]
Verified that after a push, qa gets updated with the latest.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/500294a) - 500294a

[UI](https://github.com/dockstore/dockstore-ui2/commits/6cbb12f7) - 2.10.1-95-g6cbb12f7

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
