### ISSUE TITLE
Unable to publish WDL workflow after registering

### ISSUE THREAD

**Issue by molly-hetheringtonrauth** [dockstore/dockstore#5356]
I've registered a WDL wofklow on dockstore; however I'm unable to publish the workflow because the publish button remains greyed out. When I hover over the publish button it reads "Unable to publish; no valid version found". Here is the link to the github repository: https://github.com/CDPHE/CDPHE-influenza/blob/main/tasks/irma_task.wdl

**Screenshots**
![image](https://user-images.githubusercontent.com/73671146/217608178-7094cd9a-c993-4fd3-b987-88ff1d4fcf1a.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2321)
┆Issue Number: DOCK-2321
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Hi, you may find https://discuss.dockstore.org/ more timely for end user discussions. That said, are there valid versions when you click on versions?

**Comment by molly-hetheringtonrauth** [comment]
Hi Denis,

This is what I see.
[image: image.png]
[image: image.png]

On Wed, Feb 8, 2023 at 10:57 AM Denis Yuen ***@***.***> wrote:

> Hi, you may find https://discuss.dockstore.org/
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__discuss.dockstore.org_&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=lAjz862iF3C7yaxZ6BQysxHkqIqhscaaqB8cpROcJNGGjp62pYdyQNO2rWgYcEwN&m=ygMtrh3stgV7Fdh1pP0tw16XFgxYXt4qDGVoeCwF6mM9FG2aEesVIwen8C4TGDZO&s=yy-c15Dtxm9gNjEsuNQ6u-UtVoqXb3HW_fSzke_fRl4&e=>
> more timely for end user discussions. That said, are there valid versions
> when you click on versions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dockstore_dockstore_issues_5356-23issuecomment-2D1423022267&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=lAjz862iF3C7yaxZ6BQysxHkqIqhscaaqB8cpROcJNGGjp62pYdyQNO2rWgYcEwN&m=ygMtrh3stgV7Fdh1pP0tw16XFgxYXt4qDGVoeCwF6mM9FG2aEesVIwen8C4TGDZO&s=wRfqy0zb9fC2A3zbp-ni3SvyO63FQnbd6WzE7Ag89Pk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ARSCD2XCED7ZQWCQDBY4YQ3WWPNBXANCNFSM6AAAAAAUVRU4GY&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=lAjz862iF3C7yaxZ6BQysxHkqIqhscaaqB8cpROcJNGGjp62pYdyQNO2rWgYcEwN&m=ygMtrh3stgV7Fdh1pP0tw16XFgxYXt4qDGVoeCwF6mM9FG2aEesVIwen8C4TGDZO&s=sFRK7rwbMFbXKG2OG4XVoEjXA7AZsNBvZ3qY9J_g-t0&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

Molly Hetherington-Rauth

PSRSII/Bioinformatican

Colorado State Public Health Laboratory

Division of Disease Control and Public Health Response (DCPHR)

​Colorado Department of Public Health and Environment (CDPHE)



gender pronouns: she, her



8100 Lowry Blvd., Denver CO, 80230

desk: 303.692.3090
***@***.***  | www.colorado.gov/cdphe
<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.colorado.gov_cdphe&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=yUWEGd-csUUExXVNUjlInk_amUBC0sNh_udFgdp_zAg&m=K2QGaF-9M3SauzZIeir_64m75a35tUpYk5ba3BF2tMY&s=38qMcWX8-kk64YtEQZw0tWkCrTJ08ekfo4CQi3th8lQ&e=>

**Comment by denis-yuen** [comment]
FYI, the images didn't really survive the conversion between email and github issues.

**Comment by denis-yuen** [comment]
Ok, I think that helped narrow it down. It looks like the workflow is legitimately invalid. In the first post, you can see the github app logs button which gives this kind of input 

![Screenshot from 2023-02-09 10-40-27](https://user-images.githubusercontent.com/1730679/217862116-1d1fe10d-bc87-42de-8a19-6acaed7b2129.png

(i.e. empty.json does seem missing and the are validation errors)
If you grab womtool, you should be able to re-produce these validation errors locally as well for quick iteration 
```
$ java -jar ~/Downloads/womtool-84.jar validate workflows/influenza_assembly.wdl 
Failed to import '../tasks/post_assembly_tasks.wdl' (reason 1 of 2): Failed to process task definition 'concat_post_qc_metrics' (reason 1 of 2): Failed to process expression 'write_lines(bam_results_array)' (reason 1 of 1): Invalid parameter 'IdentifierLookup(bam_results_array)'. Expected 'Array[String]' but got 'Array[File?]'
Failed to import '../tasks/post_assembly_tasks.wdl' (reason 2 of 2): Failed to process task definition 'concat_post_qc_metrics' (reason 2 of 2): Failed to process expression 'write_lines(per_cov_results_array)' (reason 1 of 1): Invalid parameter 'IdentifierLookup(per_cov_results_array)'. Expected 'Array[String]' but got 'Array[File?]'

```

**Comment by molly-hetheringtonrauth** [comment]
Thanks Denis! I found the error in the WDL and I'm now able to publish!
