### ISSUE TITLE
Add sorting to language facets

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5362]
**Is your feature request related to a problem? Please describe.**
There are a fair number of language facets which may make it hard to find the one you care about.

**Describe the solution you'd like**
Add the sort buttons, like we have for the author facet

**Describe alternatives you've considered**
Leave it

**Additional context**
Came up at sprint review of feature.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2322)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2322
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Seems out of date, today in prod it looks like we have sorting for "language versions" and "engine versions"
