### ISSUE TITLE
The "Verifications Process" page in the documentation has a link to an incomplete workflow

### ISSUE THREAD

**Issue by bvizzier-ucsc** [dockstore/dockstore#5368]
**Describe the bug**
I was writing an outline for someone on how to create a Verified Workflow and looking at the documentation.  When I went to the ["Verification Process" section](https://docs.dockstore.org/en/stable/advanced-topics/verification.html) and clicked on the dockstore-tool-md5sum:1.0.4 link, it generates the message "A Dockerfile associated with this Docker container could not be found."

**To Reproduce**
1. Go to 'https://docs.dockstore.org/en/stable/advanced-topics/verification.html'
2. Click on 'https://dockstore.org/containers/quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4?tab=files'
3. Scroll down to '....'  (No scrolling required)
4. See error "A Dockerfile associated with this Docker container could not be found."

**Expected behavior**
A workflow without an error message.

**Screenshots**

![Verification — Dockstore documentation 2023-02-14 06-59-26](https://user-images.githubusercontent.com/15311001/218775467-7756206e-61da-4971-9e7e-3ea9c4242fd7.png)

![Dockstore | Tool | quay io/briandoconnor/dockstore-tool-md5sum 2023-02-14 06-58-02](https://user-images.githubusercontent.com/15311001/218774959-b50c8831-0389-4888-9a5f-2a65288e0ae9.png)

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser: Chrome
 - Version: 110.0.5481.77 (Official Build) (arm64)

**Additional context**
 - UI version: [e.g. 2.5.0] N/A
 - Webservice version: [e.g. 1.8.0] N/A
 - host location: [docs.dockstore.org](https://docs.dockstore.org/en/stable/advanced-topics/verification.html)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2327)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2327
┆Sprint: 112 - Jialing
┆Issue Type: Story

**Comment by coverbeck** [comment]
Test comment for Unito

**Comment by denis-yuen** [comment]
Ooops, did this through the UI, but the change is small enough that it probably doesn't matter
