### ISSUE TITLE
Remove hacky smoke test code post-1.14 release

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5372]
**Describe the bug**
A smoke test has [a selector](https://github.com/dockstore/dockstore-ui2/pull/1710/files#diff-0e83ac8adb043831f00e87fd557c3cbe8a82257c2ca3d5772e2a31d01dbc77feR247) to work with both the 1.13 UI and the 1.14 UI. Once 1.14 is released to prod, update the selector to be for 1.14 code only.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2328)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2328
┆Sprint: 115 - Niagara
┆Issue Type: Story

**Comment by coverbeck** [comment]
Testing Unito integration.

**Comment by coverbeck** [comment]
Test Unito, bis.

**Comment by KimberleyChong** [comment]
**Additional follow-up:** Remove the check for "NFL" in `basic-enduser` after the release, see this [PR](https://github.com/dockstore/dockstore-ui2/pull/1715)
