### ISSUE TITLE
Determine Open data for CWL workflows

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5385]
**Describe the bug**
Open data calculations are not correct; see #5339. In PR #5347, we've improved the check for open data for WDL workflows. This ticket is to extend the logic for CWL workflows.

**Expected behavior**
Open data calculations for CWL should correctly figure out open data test parameter files.

**Notes**
This looks more complicated than the WDL work; we already had logic in WDLHandler that determined file inputs. For CWL, it looks like that logic is only in the CLI.  Ideally move the CLI code to the common module in the web service to avoid duplication.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2331)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10938">Screenshot from 2023-03-28 17-45-58.png</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/10939">Screenshot from 2023-03-28 17-47-44.png</a>
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2331
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by coverbeck** [comment]
Currently we get the file inputs for file provisioning in the CLI using CWL Avro, which we don’t use in the web service. We've also been trying to move away from CWL Avro, although CWL Java  turned out not to be the answer (at least not yet). So we have these options:

1. Move or copy, preferably move, the code from the CLI to dockstore.common.
2. Build on top of the current CWLHandler, which "just" uses a Map, but on the other hand handles CWL "imports" better.

**Comment by denis-yuen** [comment]
FYI @svonworl as well. 

Just to understand where we are at, if the parameter file has links to non-open data, then we deem it closed and vice versa. 
The exception is if the workflow doesn't have any input files in the first place, then it is open. So we need to look at the descriptors for this last case?

**Comment by coverbeck** [comment]
As an example, a workflow has 3 input parameters, `file1`, `file2`, and `cpu`. We need to parse the descriptor to know that `file1` and `file2` are of type file.

Then we look in the test parameter files for input parameters `file1` and `file2`, and we see if they exist and are open data. We don't even bother to look for file the parameter `cpu`, because it's not a file input.

The previous approach was to not look at the descriptors at all, and only look at the values in the test parameter file. If the value looked like an URL, we would see if it was open or not. That would cause false positives for something like `"file1": "path/localfile"`, because `path/localfile` doesn't look like an url, so we wouldn't check it, and the data would be considered open.

**Comment by coverbeck** [comment]
D'oh! I didn't realize until now that the test parameter file in CWL actually has the type! I think I can just go off the test param file; I don't need to read the descriptor at all. We can just punt, for now, on incomplete test param files (workflow defines 2 file parameters, test parameter file only has one of them).

CWL test param file example:

```
example_flag: true
example_string: hello
example_int: 42
example_file:
  class: File
  path: whale.txt
```

whereas a WDL test param file is:

```
{
  "wf.t1.s": "some_string",
  "wf.t2.s": "some_string",
  "wf.int_val": 3,
  "wf.my_ints": [5,6,7,8],
  "wf.ref_file": "/path/to/file.txt"
}

```
