### ISSUE TITLE
Nextflow language versions need to include engine version

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5389]
**Is your feature request related to a problem? Please describe.**
From GA4GH call, it is insufficient to track just DSL 1 vs DSL 2 for Nextflow to determine whether a nextflow workflow will work in a partticular environment. At least nf-core workflows have a hint that we can take advantage of 
https://github.com/nf-core/hicar/blob/1.0.0/nextflow.config#L235
We need to find a way to integrate this info with https://github.com/dockstore/dockstore/issues/5268

**Describe the solution you'd like**
* Be able to see what nextflow engine version is compatible with a particular workflow in TRS
* Search by Nextflow engine version in search
* Do this in a generic way since other workflow languages like Snakemake may have similar issues (i.e. no independent schema version in language itself)

**Describe alternatives you've considered**
Will need to ponder

**Additional context**
GA4GH call on this date, see https://docs.google.com/presentation/d/1xgksBrlB0hOZ7RItWDEnXBcSwBk8d8frfdelJFQb3OU/edit?usp=sharing

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2333)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2333
┆Sprint: 108 - Fraser
┆Issue Type: Story

**Comment by coverbeck** [comment]
The engine version in Nextflow is described as a [minimum](https://www.nextflow.io/docs/latest/config.html?highlight=nextflowversion#nextflow-version), although it's more of a range.

I grepped all the nf-core workflows I have pulled locally (may not be up to date), and there are 14 unique values on the default branches.

```
!>=20.01.0
!>=21.04.0
!>=21.10.3
!>=22.10.1
>=0.31.1
>=0.32.0
>=18.10.1
>=19.04.0
>=19.10.0
>=20.04.0
>=20.07.1
>=20.10.0
>=20.11.0-edge
>=21.04.2
```

I think this will clutter up the language facets, and it's not really a language version anyway, so it seems like it should be a new facet -- "workflow engine"?

If so, showing it in the UI will be a pain, as the versions table is pretty full, and most workflows, which aren't Nextflow, won't have an engine version, but so be it.

@denis-yuen @kathy-t -- does this sound reasonable?

**Comment by denis-yuen** [comment]
Proposal is, store in DB using language versions alongside dsl1/2, but display in UI/search as a workflow engine? 
I think that would be reasonable (not having strong feelings about it)

**Comment by coverbeck** [comment]
> Proposal is, store in DB using language versions alongside dsl1/2, but display in UI/search as a workflow engine? I think that would be reasonable (not having strong feelings about it)

Yes, they'd be stored in the same version_metadata table, but I'd think in a new column.

**Comment by coverbeck** [comment]
Hmm, I just realized, in separating this out, we won't be able to surface this in TRS. TRS should probably have something similar to the WES proposal at ga4gh/workflow-execution-service-schemas#181.

For now, just surface it in the proprietary API and ElasticSearch.
