### ISSUE TITLE
[QA only] GH source code URLs incorrect for GHA workflows in my-workflows view

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5414]
_n/b I might be missing some context as to how qa works, if this is by design feel free to close this ticket_

**Describe the bug**
URLs for GHA Dockstore workflows are incorrect in the my-workflows view on QA -- they add in an additional `/` just before the workflow name. If you click the link shown in this view, you will be taken to the shown incorrect URL and GH will throw a 404.

<img width="630" alt="Screen Shot 2023-03-09 at 12 34 47 PM" src="https://user-images.githubusercontent.com/27784612/224152365-994423df-bd6b-47fd-b60c-147340c69713.png">

URLs are correct on public workflow view on QA (and prod). This issues just in my-workflows.

**To Reproduce**
1. Have an existing public .dockstore.yml workflow
2. Log into qa
3. Look at that existing workflow in the my-workflows section and see that its source code URL is incorrect ~~and it hasn't been updated in a while~~ (edit: see first comment)

**Expected behavior**
Workflows should have the correct source code URL in all views ~~and stay in date as needed~~ (edit: see first comment).

**Desktop (please complete the following information):**
 - OS: Montery 12.6.3
 - Browser: Firefox 110.0

**Additional context**
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/1b01385) - 1b01385

[UI](https://github.com/dockstore/dockstore-ui2/commits/f3aaa31e) - 2.10.1-87-gf3aaa31e

[Compose Setup](https://github.com/dockstore/compose_setup/commits/e3b0aa3) - e3b0aa3

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/152e590) - 1.13.2-29-g152e590

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2345)
┆Fix Versions: Dockstore 1.14.x
┆Issue Number: DOCK-2345
┆Sprint: Backlog
┆Issue Type: Story

**Comment by aofarrel** [comment]
This was originally in the ticket body, but I now think this part is separate and user error on my part -- I forgot each flavor of Dockstore has its own GHA. Just installed the qa GHA; will see if workflows update.

**Comment by coverbeck** [comment]
Confirmed that links are correct in qa.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/810ca07) - 810ca07

[UI](https://github.com/dockstore/dockstore-ui2/commits/45783983) - 2.10.1-117-g45783983

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c54d86a) - 1.13.2-34-gc54d86a

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
