### ISSUE TITLE
[QA only] Workflow-specific readmes not working

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5421]
**Describe the bug**
As perhaps the most verbose person on UCSC's payroll, as soon as I found out about #5384 I had to play around with it. In doing so I may have broken it.

**To Reproduce**
1. Have an existing .dockstore.yml repo with at least two existing published workflows ([myco](https://dockstore.org/workflows/github.com/aofarrel/myco/myco:2.0.0?tab=info) + [myco_sra](https://dockstore.org/workflows/github.com/aofarrel/myco/myco_sra:3.1.0?tab=info))
2. [Make a new feature branch on that repo](https://github.com/aofarrel/myco/tree/split-further)
3. On the feature branch, update the repo and .dockstore.yml: [give myco_sra a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_sra.md), [rename myco to myco_raw and update file paths accordingly](https://github.com/aofarrel/myco/commit/09d4dd3271026a8bde7851e00d5c62ac46d0defd#diff-b9bbccb9c5c3e6720960c5becc0491350838b6fc2ec5f27e5f4f7502940ea592), and give [myco_raw a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_raw.md)
4. Ensure qa's flavor of the dockstore GHA has access to that repo, and that recent pushes are showing without error in the logs
5. Navigate to the not-renamed-but-now-theres-a-wf-level-readme workflow (myco_sra) from the published section of my-workflows
6. Select the new feature branch version and see that no readme shows up
7. Go to [the public version of qa's myco_sra](https://qa.dockstore.org/workflows/github.com/aofarrel/myco/myco_sra:split-further?tab=info) and see that its readme doesn't load here either, and a small window saying "failed" at the bottom of the screen briefly shows up
8. Navigate to the renamed-and-also-theres-a-wf-level-readme workflow (myco_raw) from the unpublished section of my-workflows (no need to change branches as it doesn't exist on main) and see that no readme shows up there either

**Expected behavior that did happen**
* myco_raw showing up as an unpublished new workflow
* myco's Dockstore entry not being renamed to myco_raw
* myco_sra showing up as published, since it wasn't renamed

**Expected behavior that did not happen**
Workflow-level readmes showing up on Dockstore entries that have a field for that in the .dockstore.yml for the currently selected workflow version (ie the feature branch).

If the issue is that I renamed a published workflow, I should be seeing an error in the GHA logs that myco can't be found. That being said, an issue with myco/myco_raw should not be blocking myco_sra's workflow level readme from showing up.

**Ruled out**
Typos in the readme paths.[ I did this earlier, and the .dockstore.yml logs correctly noted that they could not find the file.](https://github.com/aofarrel/myco/commit/47f9d4a637ba7f6102be38751f5b9cd92831a6ac)

**Untested**
If readmes would've worked if I hadn't renamed myco to myco_raw in the .dockstore.yml on the feature branch. Nothing about the renaming was unexpected behavior, I just think there's a chance it might have something to do with this.

**Screenshots**
<img width="1047" alt="Screen Shot 2023-03-10 at 3 12 18 PM" src="https://user-images.githubusercontent.com/27784612/224447938-50c5dcad-a0e9-4ee2-b319-e77a1bcc9d40.png">
<img width="1438" alt="Screen Shot 2023-03-10 at 3 11 57 PM" src="https://user-images.githubusercontent.com/27784612/224449082-43261c6f-9fb3-4a4f-96c7-aea44b156f24.png">
<img width="1441" alt="Screen Shot 2023-03-10 at 3 11 47 PM" src="https://user-images.githubusercontent.com/27784612/224449084-cfd381a2-1cff-4bab-a51e-e50b8b280c87.png">
<img width="1378" alt="Screen Shot 2023-03-10 at 3 57 05 PM" src="https://user-images.githubusercontent.com/27784612/224450848-ebbf38ac-d5af-451a-8ef1-11052426690e.png">

**Desktop (please complete the following information):**
 - OS: MacOS Montery
 - Browser: Firefox 110.0 (64-bit)

**Additional context**
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/eb1214b) - eb1214b

[UI](https://github.com/dockstore/dockstore-ui2/commits/bf5b134e) - 2.10.1-91-gbf5b134e

[Compose Setup](https://github.com/dockstore/compose_setup/commits/e3b0aa3) - e3b0aa3

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/152e590) - 1.13.2-29-g152e590

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2350)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2350
┆Sprint: 109 - Ganges
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@aofarrel can you confirm that these steps were performed in this order? 

```
* On the feature branch, update the repo and .dockstore.yml: [give myco_sra a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_sra.md), [rename myco to myco_raw and update file paths accordingly](https://github.com/aofarrel/myco/commit/09d4dd3271026a8bde7851e00d5c62ac46d0defd#diff-b9bbccb9c5c3e6720960c5becc0491350838b6fc2ec5f27e5f4f7502940ea592), and give [myco_raw a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_raw.md)
* Ensure qa's flavor of the dockstore GHA has access to that repo, and that recent pushes are showing without error in the logs
```
Alternatively, you may have installed the qa github app after modifying the .dockstore.yml. 
If so, could you try a silly push like modifying the readme.md in a trivial way?

**Comment by denis-yuen** [comment]
Hmmm, potential silly question

> 1. On the feature branch, update the repo and .dockstore.yml: [give myco_sra a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_sra.md), [rename myco to myco_raw and update file paths accordingly](https://github.com/aofarrel/myco/commit/09d4dd3271026a8bde7851e00d5c62ac46d0defd#diff-b9bbccb9c5c3e6720960c5becc0491350838b6fc2ec5f27e5f4f7502940ea592), and give [myco_raw a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_raw.md)
> 2. Ensure qa's flavor of the dockstore GHA has access to that repo, and that recent pushes are showing without error in the logs

Did you happen to add the github app after modifying the .dockstore.yml? 
If so, could you try a silly push like modifying a readme.md in a trivial way on the `split-further` branch?

**Comment by aofarrel** [comment]
> @aofarrel Hmmm, potential silly question
> 
> > 1. On the feature branch, update the repo and .dockstore.yml: [give myco_sra a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_sra.md), [rename myco to myco_raw and update file paths accordingly](https://github.com/aofarrel/myco/commit/09d4dd3271026a8bde7851e00d5c62ac46d0defd#diff-b9bbccb9c5c3e6720960c5becc0491350838b6fc2ec5f27e5f4f7502940ea592), and give [myco_raw a wf-level readme](https://github.com/aofarrel/myco/blob/split-further/doc/myco_raw.md)
> > 2. Ensure qa's flavor of the dockstore GHA has access to that repo, and that recent pushes are showing without error in the logs
> 
> Did you happen to add the github app after modifying the .dockstore.yml? If so, could you try a silly push like modifying a readme.md in a trivial way on the `split-further` branch?

I did [a silly push on split-further](https://github.com/aofarrel/myco/commit/c6b6edad6dc2cf4f5e71a2d3376f262c4715f64e) after [updating the .dockstore.yml](https://github.com/aofarrel/myco/commit/47f9d4a637ba7f6102be38751f5b9cd92831a6ac). Not sure if that was before or after GHA installation but I just did [another one now](https://github.com/aofarrel/myco/commit/4ba8abb1ef1bf3619cd784773ad08acace2b4e0e) and I'm still seeing the same behavior.

**Comment by aofarrel** [comment]
myco_raw and myco_cleaned are now correctly showing their readmes. myco_sra is showing it on its newest branch too.

I don't know what fixed it -- here's the commits I've made to [split-further](https://github.com/aofarrel/myco/commits/split-further), which is now merged into develop. It works now though, so feel free to close this.

**Comment by denis-yuen** [comment]
Ok, thanks for the update. 
I'll close this for now but keep an eye out for similar issues
