### ISSUE TITLE
Unable to download files from App Tools

### ISSUE THREAD

**Issue by fhembroff** [dockstore/dockstore#5428]
**Describe the bug**
There exists tools in QA that if you go the files section of the tool and hit the download button, a new screen is opened, but no file is downloaded.

I discovered this error after creating this [tool](https://qa.dockstore.org/containers/github.com/fhembroff/CWL-many-words/BASIC-CWL-FROM-TUTORIAL:main?tab=files), as when I went to download it, a new tab opened, but nothing happened.

It appears that the download button for the above workflow is calling this URL,
https://qa.dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Ffhembroff%2FCWL-many-words%2FBASIC-CWL-FROM-TUTORIAL/versions/main/PLAIN_CWL/descriptor/%2Fworkflows%2Fexample%2Fexample.cwl
Which, if you call it at the time of writing this issue, gives this error,
```
HTTP ERROR 404 Not Found : incorrect id
URI:	/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Ffhembroff%2FCWL-many-words%2FBASIC-CWL-FROM-TUTORIAL/versions/main/PLAIN_CWL/descriptor/%2Fworkflows%2Fexample%2Fexample.cwl
STATUS:	404
MESSAGE:	Not Found : incorrect id
SERVLET:	jersey
```

After talking with @denis-yuen , it appears that the URL that is called should be (if you call it, it does do what is intended),
https://qa.dockstore.org/api/ga4gh/trs/v2/tools/github.com%2Ffhembroff%2FCWL-many-words%2FBASIC-CWL-FROM-TUTORIAL/versions/main/PLAIN_CWL/descriptor/%2Fworkflows%2Fexample%2Fexample.cwl

**To Reproduce**
To see the above error
1. Go to https://qa.dockstore.org/containers/github.com/fhembroff/CWL-many-words/BASIC-CWL-FROM-TUTORIAL:main?tab=files
2. Click on the button to download `workflows/example/example.cwl`
3. Observe that no file is downloaded, a new tab is opened (which is blank).

You can find the problematic URL by using inspect element on the download button.

I created the problematic tool using GitHub apps and a `.dockstore.yml` file, the repo is found [here](https://github.com/fhembroff/CWL-many-words).

**Expected behavior**
The desired file should be downloaded when you click the download button.

**Screenshots**
![_private_var_mobile_Containers_Data_Application_2727E09F-4EB8-4112-A101-92F412A7E82E_tmp_C2038574-BD9C-4F3C-BC88-D630C0E1B8CE_Image](https://user-images.githubusercontent.com/85577755/225134264-1bf8a3e3-7c47-45e8-ac6e-577ac0daaaa8.jpeg)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Additional context**
 - host location: qa.dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2354)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2354
┆Sprint: 109 - Ganges
┆Issue Type: Story

**Comment by fhembroff** [comment]
I believe @denis-yuen has an explanation for what is causing this error.

**Comment by fhembroff** [comment]
I created a new tool on dockstore.org, and all of the download buttons seem to be working.

**Comment by denis-yuen** [comment]
Looked like the issue is with apptools and also exists in prod
https://dockstore.org/containers/github.com/dockstore/dockstore-tool-bamstats/bamstats_cwl:1.25-9?tab=files demonstrates this issue

```
incorrect: https://qa.dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Ffhembroff%2FCWL-many-words%2FBASIC-CWL-FROM-TUTORIAL/versions/main/PLAIN_CWL/descriptor/%2Fworkflows%2Fexample%2Fexample.cwl
correct:   https://qa.dockstore.org/api/ga4gh/trs/v2/tools/github.com%2Ffhembroff%2FCWL-many-words%2FBASIC-CWL-FROM-TUTORIAL/versions/main/PLAIN_CWL/descriptor/%2Fworkflows%2Fexample%2Fexample.cwl
```

Looks like the incorrect link has a prefix of `%23workflow%2F` or `#workflow/` un-escaped. 
Basically, we have this prefix to ensure that IDs do not clash between tools and workflows, but apptools are kind of a weird hybrid, so this isn't entirely surprising but needs to be fixed. 

I think it makes sense to skip the prefix for apptools, fix the UI, and potentially add a test (may already exist) to ensure that we do the right thing if an apptool and a workflow try to claim the same id.
