### ISSUE TITLE
Galaxy DAG causing a 500 response status in QA

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5432]
**Describe the bug**
Getting a 500 response status trying to get the dag for a particular Galaxy workflow on QA. This was found in verifying the fix for #5285 on QA, which is fixed, but now reveals this issue.

**To Reproduce**
```
curl 'https://qa.dockstore.org/api/workflows/20406/dag/173939'
{"code":500,"message":"There was an error processing your request. It has been logged (ID 06bd16c9d5362e44)."}
```

Or, with browser tools open, go to [this page](https://qa.dockstore.org/workflows/github.com/Delphine-L/iwc/Long_read_assembly_with_Hifiasm_and_HiC_data:VGP?tab=dag) on the UI.

**Expected behavior**
It should either work or return a 4xx.

**Additional context**
Seeing this in server logs:

```
2023-03-16T15:45:06.605-07:00 | ! java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "elementsDefinition.nodes" is null
-- | --
  | 2023-03-16T15:45:06.605-07:00 | ! at io.dockstore.webservice.helpers.DAGHelper.cleanDAG(DAGHelper.java:42)
  | 2023-03-16T15:45:06.605-07:00 | ! at io.dockstore.webservice.languages.LanguageHandlerInterface.getCleanDAG(LanguageHandlerInterface.java:204)
  | 2023-03-16T15:45:06.605-07:00 | ! at io.dockstore.webservice.resources.WorkflowResource.getWorkflowDag(WorkflowResource.java:1424)

```
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/f96e92a) - f96e92a

[UI](https://github.com/dockstore/dockstore-ui2/commits/6cbb12f7) - 2.10.1-95-g6cbb12f7

[Compose Setup](https://github.com/dockstore/compose_setup/commits/e3b0aa3) - e3b0aa3

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/2fd0b7e) - 1.13.2-30-g2fd0b7e

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2355)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2355
┆Sprint: 109 - Ganges
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Link is gone but https://dockstore.org/workflows/github.com/Delphine-L/iwc/Export-WF7-Scaffolding_Bionano:VGP?tab=dag illustrates the same issue (or at least a 500)

Hmmm, or similar 

```
! java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
! at org.galaxyproject.gxformat2.Cytoscape.getElements(Cytoscape.java:118)```

**Comment by coverbeck** [comment]
Confirmed with a local build that the error on workflow 20406 no longer occurs.
