### ISSUE TITLE
Create Documentation/Tutorial for how to run CWL workflows through TOIL (running on AGC) and WES 

### ISSUE THREAD

**Issue by fhembroff** [dockstore/dockstore#5435]
**Is your feature request related to a problem? Please describe.**
After working on this [PR](https://github.com/dockstore/dockstore-support/pull/454), I have found that the dockstore CLI can run CWL workflows through TOIL (running on AGC) and WES . This is currently not reflected in our documentation.

It would be good to create some documentation regarding the support for running CWL workflows through TOIL and WES.

We might also want to update the launch pages for CWL workflows to specify that they can be launched through TOIL and WES. This would be similar to what is done for[ WDL workflows](https://qa.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl:1.32.0?tab=launch).

**Describe the solution you'd like**
Create documentation/tutorial for the above and update launch pages.

**Describe alternatives you've considered**
Leave as is

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2356)
┆Fix Versions: Dockstore 1.14.x
┆Issue Number: DOCK-2356
┆Sprint: 111 - Indus
┆Issue Type: Story

**Comment by fhembroff** [comment]
> It would be nice to cover CWL tools as well :) -- document if they work or don't.

CWL tools can be given to the [WES endpoint](https://github.com/dockstore/dockstore-cli/blob/ca43df582a43ae7998080978bf3c6ad68699252f/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L119-L126), however, whenever I try passing a CWL tool to the CLI using this command,
 ```
> dockstore workflow wes launch --entry quay.io/pancancer/pcawg-sanger-cgp-workflow:2.1.0 --json Dockstore.json
```
I get this error (or something similar)
```
Current version : 1.13.1
You have the most recent stable release.
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
12:32:50.388 [main] ERROR io.dockstore.client.cli.ArgumentUtility - No workflow found with path quay.io/pancancer/pcawg-sanger-cgp-workflow

```

I'm guessing it has something to do with the [API](https://github.com/dockstore/dockstore-cli/blob/ca43df582a43ae7998080978bf3c6ad68699252f/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L154) we are using to get the "workflow". 

So currently CWL tools are not supported, but with some (hopefully) simple modifcations to the CLI, it should work.

**Comment by coverbeck** [comment]
You run tools with `dockstore tool launch`... I wonder if we never added `wes` to `dockstore tool`? If we didn't, then adding tools is getting to be a bit out of scope.

**Comment by fhembroff** [comment]
Currently, wes is only supported for workflows.

https://github.com/dockstore/dockstore-cli/blob/ca43df582a43ae7998080978bf3c6ad68699252f/dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java#L363-L370
