### ISSUE TITLE
Browse page for apptools is messed up in terms of pagination and total count

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5436]
**Describe the bug**
Pagination (probably total count header) is messed up for browse page
https://qa.dockstore.org/apptools
Occurs in prod too

**To Reproduce**
Go to above page, set pagination size to 100 and browse to the end

**Expected behavior**
Display correct number and browse like https://qa.dockstore.org/tools

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/967a0b5) - 967a0b5

[UI](https://github.com/dockstore/dockstore-ui2/commits/5da825bb) - 2.10.1-100-g5da825bb

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2357)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2357
┆Sprint: 109 - Ganges
┆Issue Type: Story

**Comment by coverbeck** [comment]
Confirmed on qa that total number of app tools in the UI matches the count of published app tools in the DB. Pagination works fine as well.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
