### ISSUE TITLE
Publishing a DOI should add ORCiD id to the DOI metadata

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5437]
**Is your feature request related to a problem? Please describe.**
The Zenodo API lets you specify the ORCiD id of the author. If it's part of the DOI record, then [auto-update features](https://support.orcid.org/hc/en-us/articles/360006894594-Auto-updates-in-third-party-systems-DataCite) could automatically update your ORCiD account

**Describe the solution you'd like**
If the user has linked an ORCiD account, we should set it when creating the DOI. Around [here](https://github.com/dockstore/dockstore/blob/5c76df50ce8cc32949195d3b196ca12b3e0b92f3/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ZenodoHelper.java#L302-L301).

Optionally, torn on this one, the UI could suggest or even enforce that your ORCiD account be linked before publishing a DOI. If "nobody" is typically going to have a Zenodo account without having an ORCiD account, this is reasonable, otherwise perhaps not.

**Describe alternatives you've considered**
1. Don't change anything
2. Tell the user to manually add the ORCiD id after it's been published in Zenodo (yuck).

**Additional context**
Discovered in researching [SEAB-5303](https://ucsc-cgl.atlassian.net/browse/SEAB-5303)

[SEAB-5303]: https://ucsc-cgl.atlassian.net/browse/SEAB-5303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2358)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2358
┆Sprint: 112 - Jialing
┆Issue Type: Story

**Comment by coverbeck** [comment]
Looking at it further since I wrote it up, it turns out the author is a required field, and we get around it by specifying a value of `Author not specified` if we don't know it, which is probably wrong.

This also starts treading into the sticky issue of who the author of a workflow is (the one in the descriptor, in the .dockstore.yml, the GitHub account of the "publisher", etc.

**Comment by denis-yuen** [comment]
Yeah, it's an interesting one. Maybe we can do something more general?
Like in an ideal world, we would somehow match the authors in the list of authors with the current user and if there's a match, to associate the ORCID id's and/or update the entry. 

More realistically, put a check in the wizard to check that there is at least one ORCID id in the upload we send to zenodo?
