### ISSUE TITLE
Workflows show as authorless if using workflow-level readmes

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5441]
**Describe the bug**
In this day and age, many questions are being raised about AI and what it means for authorship. If a program scrapes your workflow readmes and then generates something, who is the author of the result? The person whose writing was scraped? The programmer? The prompter? The program itself?

It's an open question, that's for sure, but qa.dockstore.org is determined to settle the debate by deciding that a workflow that has both authors and readMePath specified in its .dockstore.yml wasn't written by anybody.

**To Reproduce**
1. Make a .dockstore.yml which has both an authors and readMePath
2. Go to qa.dockstore.org (which has workflow-level readmes)
3. On the my-workflows view of the workflow or the public view, see that the author has been removed
4. Go to dockstore.org (which does not have workflow-level readmes yet)
5. On the my-workflows view of the workflow or the public view, see that the author is present 

Public example: 
* Shows author: https://dockstore.org/workflows/github.com/aofarrel/myco/myco_cleaned
* Does not show author: https://qa.dockstore.org/workflows/github.com/aofarrel/myco/myco_cleaned

**Expected behavior**
People should be able to see my workflow-level readmes and my ORCID.

**Screenshots**
### qa
<img width="882" alt="no author" src="https://user-images.githubusercontent.com/27784612/227809164-2fe1ab05-268d-4947-bab6-90d7a143719a.png">  

### prod
<img width="967" alt="author" src="https://user-images.githubusercontent.com/27784612/227809463-4cb93bc8-8a7c-4194-b326-12969c01139f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Montery
 - Browser: Firefox 111.0.1

**Additional context**
- [Domain] - https://qa.dockstore.org
- [Webservice](https://github.com/dockstore/dockstore/commits/967a0b5) - 967a0b5
- [UI](https://github.com/dockstore/dockstore-ui2/commits/f252012c) - 2.10.1-102-gf252012c
- [Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328
- [Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057
- cwlParsingLambdaVersion: n/a
- wdlParsingLambdaVersion: n/a
- nextflowParsingLambdaVersion: n/a
- galaxyParsingLambdaVersion: 0.0.6
- checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2361)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2361
┆Sprint: 110 - Humber River
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Thanks for the heads-up!

**Comment by denis-yuen** [comment]
Must have modified parameters wrong 
```
2023-04-04T14:03:41.667-04:00
ERROR [2023-04-04 18:03:41,667] io.dockstore.webservice.helpers.ORCIDHelper: Could not get ORCID access token: 
{
    "error": "invalid_client",
    "error_description": "Client not found: replaceme"
}
```

**Comment by coverbeck** [comment]
FYI, https://ucsc-cgl.atlassian.net/browse/SEAB-4985

**Comment by denis-yuen** [comment]
Hmmm, could be. Wonder why the public access token doesn't work in staging (or maybe qa as well)

**Comment by coverbeck** [comment]
Confirmed that the author now shows up in qa at https://qa.dockstore.org/workflows/github.com/aofarrel/myco/myco_cleaned:develop?tab=info

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/810ca07) - 810ca07

[UI](https://github.com/dockstore/dockstore-ui2/commits/45783983) - 2.10.1-117-g45783983

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c54d86a) - 1.13.2-34-gc54d86a

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
