### ISSUE TITLE
Extra slash in source code link

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5444]
**Describe the bug**
On qa for 1.14 (not in prod), looks like our source code links in "my workflows" have gained an extra slash breaking the link.
Seems to affect all workflows, published or not. Leads to 404 such as https://github.com/ga4gh/benchmarking-tools/tree//Dockstore.cwl

**To Reproduce**

![Screenshot from 2023-03-28 12-00-37](https://user-images.githubusercontent.com/1730679/228298809-2e712620-5adb-47bc-823d-e8bc39a10602.png)

**Expected behavior**

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2363)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2363
┆Sprint: 110 - Humber River
┆Issue Type: Story

**Comment by aofarrel** [comment]
duplicated here: https://github.com/dockstore/dockstore/issues/5414  t

**Comment by denis-yuen** [comment]
Missed that, thanks!

**Comment by coverbeck** [comment]
Confirmed there is no extra slash in neither public nor my-workflows view.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/c7cc38b) - c7cc38b

[UI](https://github.com/dockstore/dockstore-ui2/commits/45783983) - 2.10.1-117-g45783983

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c54d86a) - 1.13.2-34-gc54d86a

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
