### ISSUE TITLE
DAG tooltips can appear over footer

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5446]
**Describe the bug**

When reviewing DAG behavior for a CWL workflow I noted that the tooltips appeared to be showing up on the bottom of screen over the footer.

**To Reproduce**
1. Go to https://dockstore.org/workflows/github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/pcawg-oxog-full-workflow:master?tab=dag
2. Mouseover nodes in the DAG
3. Scroll down to footer
4. See tooltip items covering footer
![image](https://user-images.githubusercontent.com/3795586/228391882-2cd5a141-f981-4840-b89b-207c7f64dd9d.png)

**Expected behavior**

The tooltips should be visible near the mouse pointer and should go away onmouseout.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: xubuntu 22.04.2
 - Browser firefox
 - Version 111.0.1 (64-bit)

**Additional context**

Affects both current prod and QA
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/fb9ebdf) - fb9ebdf

[UI](https://github.com/dockstore/dockstore-ui2/commits/a76609e6) - 2.10.1-107-ga76609e6

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2365)
┆Fix Versions: Dockstore 1.14.x
┆Issue Number: DOCK-2365
┆Sprint: 112 - Jialing
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Hmmmm, doesn't seem to be occurring anymore in Firefox 113.0.1 either way.
Well, re-open if there is a regression
