### ISSUE TITLE
Display the base filename in entry "File" tab dropdown 

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#5455]
**Describe the bug**
The entry "File" tab dropdown displays the path of the current file, and sometimes, long paths are truncated so that the first part appears and the base filename is hidden.  The most useful information should be displayed, and arguably, the base file name is more useful than the path prefix.

**To Reproduce**
View:
https://qa.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl:1.32.0?tab=files

**Expected behavior**
Always include the base filename of the currently-selected file in the "File" tab's drop down menu.  Harmonize any other related UI elements.

**Additional context**
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/199226f) - 199226f

[UI](https://github.com/dockstore/dockstore-ui2/commits/274e8dee) - 2.10.1-112-g274e8dee

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/140c057) - 1.13.2-31-g140c057

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2369)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2369
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
Implementor: discuss before doing -- it's possible that the dropdown, which has the full name/path, may be enough of a solution.
