### ISSUE TITLE
Order of operations bug with workflow level readme

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5456]
**Describe the bug**

> Additionally, I had a GitHub apps workflow in QA that was using the description from the descriptor. I removed the description from the descriptor and updated the .dockstore.yml with a readMePath to a README in a subfolder. However, the description for my workflow is still the old description from the descriptor even though the description no longer exists in the descriptor. I expected that it would show the README specified by the .dockstore.yml.

https://github.com/dockstore/dockstore/issues/5018

**To Reproduce**
See above

**Expected behavior**
Description retrieval should be independent from push to push. 

**Additional context**

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/a5e7f12) - a5e7f12

[UI](https://github.com/dockstore/dockstore-ui2/commits/565d9fb9) - 2.10.1-113-g565d9fb9

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/e0a6c93) - 1.13.2-33-ge0a6c93

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2370)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2370
┆Sprint: 110 - Humber River
┆Issue Type: Story

**Comment by coverbeck** [comment]
Tried various description sequences as outline in the PR on staging, works!

[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-beta.0) - 2.11.0-beta.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0
