### ISSUE TITLE
Cannot release specific app tool

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5457]
**Describe the bug**
https://github.com/dockstore-testing/tooltester-wes-testing/blob/14aaf6f06583f5c4d42500db36e50fadef422574/.dockstore.yml#L2-L11 dies not show up on release on qa. 
Tried deleting  comment, message in github app log is non-specific

Seems to match formatting in docs https://docs.dockstore.org/en/stable/assets/templates/tools/tools.html

**To Reproduce**
Fork, install github app, release. 
Can probably use WebHookIT.java as a framework to reproduce as well

**Expected behavior**
1. Should release
2. Message should be more helpful (which path is the issue?)

**Screenshots**
![Screenshot from 2023-04-11 11-46-03](https://user-images.githubusercontent.com/1730679/231217331-f97a4f79-d3a5-4be3-9db7-e328b22a2d85.png)

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/c7cc38b) - c7cc38b

[UI](https://github.com/dockstore/dockstore-ui2/commits/a4a8bdb4) - 2.10.1-114-ga4a8bdb4

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c54d86a) - 1.13.2-34-gc54d86a

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2371)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2371
┆Sprint: 110 - Humber River
┆Issue Type: Story

**Comment by coverbeck** [comment]
* Cloned https://github.com/coverbeck/tooltester-wes-testing
* Verified it has a test parameter file referenced from .dockstore.yml with a location in it
* Registered on qa, pushed, and the version appeared.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/0a146cf) - 0a146cf

[UI](https://github.com/dockstore/dockstore-ui2/commits/ccea277f) - 2.10.1-130-gccea277f

[Compose Setup](https://github.com/dockstore/compose_setup/commits/6f68328) - 6f68328

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/4d100bf) - 1.13.2-37-g4d100bf

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
