### ISSUE TITLE
Implement the ngx-markdown-wrapper to interpret files to its GitHub page and also embed the raw image

### ISSUE THREAD

**Issue by hyunnaye** [dockstore/dockstore#5459]
**Describe the bug**
Currently the images do not load on the readme description of workflows. This is because the `baseUrl` for our `ngx-markdown` wrapper is set to the GitHub link instead of the raw image itself. In GitHub, their readme files get rendered in a way that external files are linked to its GitHub link and the raw link for images are also fetched. We should implement the wrapper to behave in this way as well. 

In other words, we want all non-image files to be linked to its GitHub link and all image files to be linked to its raw file so it can be loaded onto our readme.

**To Reproduce**

1. Go to https://qa.dockstore.org/workflows/github.com/denis-yuen/myco/myco_sra:main?tab=info
1. Note that the images in the readme are linked to https://github.com/denis-yuen/myco/blob/split-further/doc/doc_making_resources/myco_sra_flowchart_1.png and not https://raw.githubusercontent.com/denis-yuen/myco/split-further/doc/doc_making_resources/myco_sra_flowchart_1.png

**Expected behavior**
Images should load and other links should be redirected to its GitHub link instead of its raw file.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2373)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2373
┆Sprint: 125 - Xingu
┆Issue Type: Story

**Comment by svonworl** [comment]
The problem described in this ticket also afflicts the notebook markdown, resulting in "broken" icons for images referenced via Markdown syntax with relative links.
