### ISSUE TITLE
Inconsistent errors for UI adding manual tool/workflow and updating tags

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#546]
There are some inconsistencies with how we generate error messages and also validate input. We should make sure that each required value is valid before allowing submission of changes, to ensure that the webservice doesn't break.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-467)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-467

**Comment by denis-yuen** [comment]
Too broad
