### ISSUE TITLE
Viewing user page when logged out shows an error banner

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5480]
**Describe the bug**
On QA, when logged out, viewing a user page on Dockstore displays a `[HTTP 401] Unauthorized: Credentials are required to access this resource.` error banner. This also happens on prod.

![image](https://user-images.githubusercontent.com/25287123/234609089-fd3e6241-e0f5-42fb-a36b-25afedde9572.png)

The console says it's from calling the `users/checkUser` endpoint.

**To Reproduce**
1. Log out of Dockstore
2. Go to any user page (can look at organization members, or go to your own user page)
3. See error banner

**Expected behavior**
There shouldn't be an error banner when viewing user pages when logged out

**Screenshots**
View above

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2383)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2383
┆Sprint: 112 - Jialing
┆Issue Type: Story

**Comment by denis-yuen** [comment]
No longer see error on https://staging.dockstore.org/users/kathy-t

[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-rc.0) - 1.14.0-rc.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-rc.0) - 2.11.0-rc.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0
