### ISSUE TITLE
Request DOI authors are the default version authors

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5509]
**Describe the bug**
When you request a DOI, the default workflow version's author(s) is used for the DOI author instead of the author(s) from the version you are requesting the DOI for.

**To Reproduce**

1. Do this in staging ideally, you shouldn't create test DOIs on zenodo (staging is hooked up to sandbox.zenodo.org)
1. Create a hosted workflow
1. Save version 1 with author set to `Version one`
1. Save version 2 with author set to `Version two`. Version 2 will be the default
1. Request DOI for version 1
1. Look at the DOI -- you'll see the author is `Version two`

**Expected behavior**
It should use the author of the version you are publishing.

See ZenodoHelper#setMetadataCreator -- it takes a `Workflow` as a parameter, not a `WorkflowVersion`, and `Workflow.getAuthors()` returns the default version's authors.

**Additional context**
[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-beta.0)

* 1.14.0-beta.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-beta.0)

* 2.11.0-beta.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0)

* 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0)

* 1.14.0-beta.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2399)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11176">image-20240621-184812.png</a>
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2399
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@kathy-t check on history of this, was this intentional and/or wise
