### ISSUE TITLE
Add "Back to top" links for Dockstore FAQ documentation

### ISSUE THREAD

**Issue by hyunnaye** [dockstore/dockstore#5510]
**Is your feature request related to a problem? Please describe.**
In this [PR](https://github.com/dockstore/dockstore-documentation/pull/216), the "back to top" links were added to the "GitHub App Troubleshooting & FAQs" [page](https://docs.dockstore.org/en/latest/getting-started/github-apps/github-apps-troubleshooting-tips.html?highlight=github%20app). 

We should add this same thing to the [Dockstore FAQ page](https://docs.dockstore.org/en/latest/faq.html) and [Dockstore CLI FAQ](https://docs.dockstore.org/en/stable/advanced-topics/dockstore-cli/dockstore-cli-faq.html)

**Describe the solution you'd like**
The other Dockstore FAQ pages should also have the "back to top" buttons

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2400)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2400
┆Sprint: Backlog
┆Issue Type: Story

**Comment by aofarrel** [comment]
I can't assign myself to tickets anymore but I'm on it.
