### ISSUE TITLE
Snackbar failure when refreshing page if logged in user is not a curator or admin

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5520]
**Describe the bug**
There's a snackbar failure when refreshing the page if you're logged in and you're not a curator or admin. Encountered in staging and QA, but not prod.
![Screenshot from 2023-05-16 14-26-03](https://github.com/dockstore/dockstore/assets/25287123/986aad15-3126-413c-ad7c-747a12b3e781)

The [endpoint](https://staging.dockstore.org/api/static/swagger-ui/index.html#/organizations/getAllOrganizations) being called requires admin or curator access.

**To Reproduce**
1. Log into an account that does not have curator or admin access.
2. See snackbar failure.
3. Open browser developer tools on network tab
4. Reload page
5. See 403 response for that endpoint in the screenshot

**Expected behavior**
There shouldn't be a 403 error. The UI shouldn't call that endpoint if the user is not an admin or curator.

**Screenshots**
See above

**Additional context**
[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-beta.0) - 2.11.0-beta.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2402)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2402
┆Sprint: 113 - Liao
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Which page?

**Comment by kathy-t** [comment]
> Which page?

I think all pages as long as you refresh the page. It's the nav bar component that's making the request [here](https://github.com/dockstore/dockstore-ui2/blob/1ff633033c3be1fa552f7fe393579471d605ddd6/src/app/navbar/navbar.component.ts#L80)

**Comment by coverbeck** [comment]
Confirmed no 403 on staging with a non-curator/non-admin account.

[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-rc.0) - 1.14.0-rc.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-rc.0) - 2.11.0-rc.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0
