### ISSUE TITLE
The UI should exclusively use OpenAPI

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5538]
**Is your feature request related to a problem? Please describe.**
The UI is using a combination of Swagger-generated and OpenAPI-generated code. This causes a couple of issues:

1. It's making it difficult to full address #5471, as sometimes we have, for example, a Swagger Workflow, and sometimes an OpenAPI Workflow, and you can't interchange them from a compiler perspective.
2. We're no longer updating the Swagger generated YAML on the web service, so new/updated APIs will not be available.
3

**Describe the solution you'd like**
The UI should exclusively use

**Describe alternatives you've considered**
Struggle along like we have

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2410)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2410
┆Sprint: 114 - Mekong
┆Issue Type: Story

**Comment by denis-yuen** [comment]
> 1. and you can't interchange them from a compiler perspective

Sounds like Typescript doesn't have qualified package names like in Java (that said, it is still a pain in Java)

**Comment by coverbeck** [comment]
> Sounds like Typescript doesn't have qualified package names like in Java? (that said, it is still a pain in Java)

They do; I didn't explain it very well. The problem we have is a component that takes an OpenAPI Workflow as a parameter, but the parent component is fetching the the workflow with Swagger -- you can't pass the Swagger Workflow to a component expecting an OpenAPI workflow.
