### ISSUE TITLE
An entry with a valid WDL can be declared to have no content, can't be imported

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5551]
**Describe the bug**
It's possible to end up in a situation where [a .dockstore.yml workflow entry that has a valid WDL](https://dockstore.org/workflows/github.com/aofarrel/goleft-wdl:main?tab=info) is considered to be empty. When this happens, you can't export it to any of our cloud partners. Only Terra and BDC are grayed out, but all of the buttons show the same error when moused over.

![](https://github.com/dockstore/dockstore/assets/27784612/0f8b86b5-36c7-4898-90cd-e23969d6d412)

**To Reproduce**
(It is entirely possible that only step 7 onwards is relevant.)

1. Create a repo with a valid WDL workflow.
1. Make a .dockstore.yml like this:

```
version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: goleft_functions.wdl
     testParameterFiles:
         - goleft_terra.json
      name: goleft-wdl
```

1. Publish the workflow
1. Make a new branch called `checker` and don't mess with it
1. Back on the main branch, delete the workflow's name. [Don't know why I did that, but I did.](https://github.com/aofarrel/goleft-wdl/commit/7b77b76860b2e7da500aab1cf5e615636537beb2) However, do not cherrypick that change to the checker branch.
1. As expected, you now have a published `github.com/aofarrel/goleft-wdl` entry from main and an unpublished `github.com/aofarrel/goleft-wdl/goleft-wdl` entry from checker.
1. Create a new branch based on main called `revamp`
1. On revamp, update the .dockstore.yml as you prepare to split your workflow into three... but mess it up the first three times. [[1](https://github.com/aofarrel/goleft-wdl/commit/4687b0e80bcbf1cf31e918038c4b2c54d9d29f4a)] [[2](https://github.com/aofarrel/goleft-wdl/commit/40846db29a671cc61ce9bd611226e40d281acf8a)] [[3](https://github.com/aofarrel/goleft-wdl/commit/fe2ac6e58001fc2746a25007944b72bb5c30fe2e)] [[4](https://github.com/aofarrel/goleft-wdl/commit/3d7fa689ab5148438a1957b1eb8c990310d30a7c)]
1. This will create, as expected, a new unpublished entry. There is now a total of two unpublished entries and one published entry -- that is expected. 
1. Go to the published entry in my-workflows view and verify that it looks fine. There's no error about the WDL being invalid.

![](https://github.com/dockstore/dockstore/assets/27784612/cf872c21-a32d-40aa-8f4b-ea4dac368eae)

![](https://github.com/dockstore/dockstore/assets/27784612/8f4ea6c3-e7ea-416b-9244-40558e993b43)

1. Go to the public page for the published entry and notice that you can't import it anywhere.

**.dockstore.yml logs for the four commits**
commit [1](https://github.com/aofarrel/goleft-wdl/commit/4687b0e80bcbf1cf31e918038c4b2c54d9d29f4a)'s error
![](https://github.com/dockstore/dockstore/assets/27784612/e045f71d-4e0d-404d-a77c-33ea4fe2d89a)

commit [2](https://github.com/aofarrel/goleft-wdl/commit/40846db29a671cc61ce9bd611226e40d281acf8a)'s error
![](https://github.com/dockstore/dockstore/assets/27784612/a6d86ad8-37d8-4fbd-b35e-a8b25bd7dfdd)

commit [3](https://github.com/aofarrel/goleft-wdl/commit/fe2ac6e58001fc2746a25007944b72bb5c30fe2e)'s error
![](https://github.com/dockstore/dockstore/assets/27784612/df0bb5dd-3af0-44ed-88ca-e1b769930acb)

The last commit [4](https://github.com/aofarrel/goleft-wdl/commit/3d7fa689ab5148438a1957b1eb8c990310d30a7c) seems to have been fine.

**Expected behavior**
Even though I foolishly renamed a workflow twice, that shouldn't cause an existing entry to declare itself contentless when I can see the WDL exists on both Dockstore [and GitHub](https://github.com/aofarrel/goleft-wdl/blob/main/goleft_functions.wdl).

**Additional context**
This workflow is in active develop so things might change over time, but I'll avoid squashing relevant commits.

[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0)

* 1.14.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0)

* 2.11.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14)

* 1.14

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14)

* 1.14

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2415)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2415
┆Sprint: 117 - Pearl
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Note to implementer, there are relative paths in here which could be consistent with https://github.com/dockstore/dockstore/issues/4670

We're currently working on making it more obvious that relative paths aren't quite working right

**Comment by denis-yuen** [comment]
Another related event is this thread https://discuss.dockstore.org/t/this-wdl-has-no-content-error/7523/2

**Comment by coverbeck** [comment]
Verified that there is an error message in the logs if the primary descriptor path is not absolute. Spun out a new ticket, #5685 for things I noticed while verifying.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/b6db850) - b6db850

[UI](https://github.com/dockstore/dockstore-ui2/commits/926a30eb) - 2.11.1-68-g926a30eb

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/7ae1315) - 1.14.1-47-g7ae1315

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
