### ISSUE TITLE
Include Dockstore CLI version

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#5552]
Tooltester was set up to only include the webservice version (previously we had CLI and webservice on the same repo).  

It needs to somehow handle the CLI version (as a flag/parameter passed to Jenkins)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2416)
┆Issue Number: DOCK-2416
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Not sure this is relevant with the AGC WES-cli move
