### ISSUE TITLE
Should be able to generate tool tester report without uploading to S3

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#5554]
We do not necessarily want every run of tooltester to be uploaded to S3 and available to Dockstore. Sometimes we may be trying development builds, or testing a pre-release version of the webservice/cli, where we don't want to display the results on Dockstore.

Perhaps a flag that can be passed to the tooltester report function that will not upload to S3.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2418)
┆Issue Number: DOCK-2418
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Not relevant with tooltester re-write around AGC
