### ISSUE TITLE
Create metrics search

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5568]
**Is your feature request related to a problem? Please describe.**
How do you find metrics for Dockstore, obvious option is to create a new search facet

**Describe the solution you'd like**
New search facet for metrics, tied into metrics feature flag

**Describe alternatives you've considered**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2423)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2423
┆Sprint: 123 - Volga
┆Issue Type: Story

**Comment by coverbeck** [comment]
I'm thinking of these facets:

* Has execution metrics
* Has validation metrics
* Platforms, e.g., DNAstack, Terra, AGC, etc.

We could also add a number of times executed metric, grouped, e.g., 1-1000, 1000-10,000, > 10,000, but I don't think we have enough data yet.
