### ISSUE TITLE
Add "how to cite dockstore"

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5598]
**Is your feature request related to a problem? Please describe.**

Dockstore receives citations from researchers but might not know how best to cite us. [See](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.001051?crawler=true) [citations](https://academic.oup.com/bioinformatics/article/38/11/3116/6571143?login=false
) for some examples of how citations look for a) the site as a whole and b) for individual pages

![image](https://github.com/dockstore/dockstore/assets/3795586/1f08a03e-5aa0-42f9-9df8-60d9de8875fa)

![image](https://github.com/dockstore/dockstore/assets/3795586/09bc62a4-d2af-4165-bbf0-ece8f90f2eea)

![image](https://github.com/dockstore/dockstore/assets/3795586/a0671b94-108b-44a5-9b02-21b9f070c14c)

**Describe the solution you'd like**

1) A part of the docs that explains how to cite Dockstore and a copy-paste-able citation. Also in the readme.

2) A link from the ui (perhaps in the footer?)

Nice-to-have: Instructions on how to cite individual pages properly or a "cite this page" link in the UI. Include author information in the citation if they are linking an entry with that info. (DOI if available?)

**Describe alternatives you've considered**

Just adding docs for this. 

Tell people wanting to cite their workflows to generate a DOI using zenodo instead of citing us directly.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2432)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11055">image-20230829-165754.png</a>
┆Fix Versions: Dockstore 1.14.x
┆Issue Number: DOCK-2432
┆Sprint: 119 - Rouge River
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Note for implementer, can build off of:
https://github.com/dockstore/dockstore/blob/develop/CITATION or badge at https://github.com/dockstore/dockstore but adding it to the UI makes sense too. 

https://docs.dockstore.org/en/stable/faq.html?highlight=citation#how-do-i-cite-dockstore needs updating to the NAR paper

**Comment by denis-yuen** [comment]
```
<span class="__dimensions_badge_embed__" data-doi="10.1093/nar/gkab346" data-hide-zero-citations="true" data-style="small_rectangle"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
```
from https://badge.dimensions.ai/?identifier=pub.1137547513#build
