### ISSUE TITLE
Webservice builds failing on CircleCI installing aws-sam-cli

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5603]
**Describe the bug**
Starting yesterday, web service builds on CircleCI started failing.

We found this bug: https://github.com/aws/aws-sam-cli/issues/5543 that is probably the cause.

**To Reproduce**

See, for example, https://app.circleci.com/pipelines/github/dockstore/dockstore/10190/workflows/7d212d06-cca0-4428-9732-609befa3d471/jobs/35603

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2434)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2434
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Attempting fixes in https://app.circleci.com/pipelines/github/dockstore/dockstore?branch=feature%2Fnew-sam-cli

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore/pull/5609
