### ISSUE TITLE
Generated TypeScript OpenAPI code have a class hierarchy

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5605]
**Is your feature request related to a problem? Please describe.**
Our generated TypeScript OpenAPI code doesn't have the same class hierarchy as the Java code. For example, in the Java code, `WorkflowVersion` and `Tag` extend `Version`, but in the generated TypeScript code, while there are  generated `Version`, `WorkflowVersion`, and `Tag` classes, `WorkflowVersion` and `Tag` do not extend `Version`.

See discussion starting [here](https://github.com/dockstore/dockstore-ui2/pull/1816#discussion_r1267338295). 

**Describe the solution you'd like**
Generated TypeScript classes should have a class hierarchy.

If we're able to address this, the implementor should roll back the change in the UI [this thread](https://github.com/dockstore/dockstore-ui2/pull/1816#discussion_r1267338295) is commenting on -- change `@Input() versions: WorkflowVersion[] | Tag[];` back to `@Input() versions: Version[];`

**Describe alternatives you've considered**
Nothing, other than leaving it as is.

**Additional context**
Addressing this may require changes to both the web service, for the OpenAPI generation, and the UI, for generation from the openapi.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2435)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2435
┆Sprint: 121 - Tigris
┆Issue Type: Story

**Comment by denis-yuen** [comment]
To be clear, I think the Java generated code is also missing the hierarchy. Only Java Jackson seems aware

**Comment by denis-yuen** [comment]
I think that just means Jackson understands the hierarchy when serializing/deserializing. I don't think that means the generated classes are aware of it in either language

**Comment by coverbeck** [comment]
The generated classes do have some hierarchy, although they're not extending `Entry`, our ultimate goal. The BioWorkflow class in Typescript:

```
export interface BioWorkflow extends Workflow { 
    parent_id?: number;
}
export namespace BioWorkflow {
}
```

I thought I'd traced that generation down to the `@Json...` annotations, as I don't see any OpenAPI annotations for  this, but I'll double-check.

**Comment by denis-yuen** [comment]
At least that narrows it down (we can try to figure out why there is inheritance info for BioWorkflow but not for Workflow)

**Comment by denis-yuen** [comment]
For tomorrow, 
https://github.com/swagger-api/swagger-codegen/issues/8148
https://github.com/swagger-api/swagger-codegen/pull/10262 
https://github.com/swagger-api/swagger-codegen-generators/pull/685

**Comment by denis-yuen** [comment]
Getting close, https://github.com/dockstore/dockstore/pull/5627 has tests and a proper class hierarchy. 
The problem is the generated code duplicates the methods in Workflow which should be inherited from Entry which fails a pile of tests (possibly more tests)

**Comment by denis-yuen** [comment]
Remaining pain points
1) `io.swagger.client.ApiException: {"code":400,"details":"Could not resolve subtype of [simple type, class io.dockstore.webservice.core.Tool]: missing type id property 'type'","message":"Unable to process JSON"}`
In other words, the old swagger client will send out json without the new discriminators. This breaks backwards compatibility with older CLI versions (also UI, but only for a short duration) and certain tests
2)  Children of workflow get an odd structure where they have both the property under their own name but doubled with a prefix of `workflow` as well. For example, AppTools have both   `workflowTopicId` and `topicID`. Think this has something to do with the generated client not understanding the hierarchy of `Entry -> Workflow -> AppTool`
![Screenshot from 2023-08-16 17-38-27](https://github.com/dockstore/dockstore/assets/1730679/13fe1289-2382-48f9-b60b-13fd2fc9c263)
3) Odd `EntryObjectObject`  in definition (could try merging the removal of self-referencing generics above)
