### ISSUE TITLE
Unknown user image not showing up

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5612]
**Describe the bug**
We use the Gravatar mystery person icon as the image for an unknown user when displaying starred events on the My Dashboard page. The Gravatar URL that we use results in a 404 so the image isn't displayed: https://www.gravatar.com/avatar/?d=mp&s=500

![image](https://github.com/dockstore/dockstore/assets/25287123/b6497248-75f8-4f93-92f1-136b9223296c)

**To Reproduce**

1. Login and star this tool https://qa.dockstore.org/containers/github.com/dockstore/dockstore-tool-bamstats/bamstats_cwl:1.25-9?tab=info
1. Go to My Dashboard and look at the Starred box. You should see an event with an Unknown user.
1. See that the mystery person icon is not displayed.

**Expected behavior**
The mystery person icon should be displayed.

**Screenshots**
See above

**Additional context**

* host location: I can reproduce this in all 3 environments

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2438)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2438
┆Sprint: 118 - Quillayute
┆Issue Type: Story

**Comment by coverbeck** [comment]
I see the avatar in QA.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/13cf489) - 13cf489

[UI](https://github.com/dockstore/dockstore-ui2/commits/3054d58f) - 2.11.1-57-g3054d58f

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/c4108ce) - 1.14.1-35-gc4108ce

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
