### ISSUE TITLE
Add links to current User profiles

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5615]
**Is your feature request related to a problem? Please describe.**

Dockstore has user profiles, but there's no easy way to navigate to "my profile" without entering into the address bar.

**Describe the solution you'd like**

Add links to user profiles in places that make sense. https://dockstore.org/users/david4096

1. Rename the Account & Profiles pulldown to just say "Account" and have a separate link for "Profile"
1. Link from the Account page

**Describe alternatives you've considered**

More in addition to the above

1. In places where the username shows up on Dockstore (e.g. a public entry) ensure a link to the public profile is there

**Additional context**

This came up when looking at the usage of our public profile API https://ucsc-cgl.atlassian.net/browse/SEAB-5631

GitHub does this 
![image](https://github.com/dockstore/dockstore/assets/3795586/5cbad77e-5ae2-4d74-9214-219b9e05fa55)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2439)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2439
┆Sprint: 119 - Rouge River
┆Issue Type: Story

**Comment by coverbeck** [comment]
Works, but I think the Organization update page isn't quite right. I'm going to log a separate ticket for that and close this one.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/7da93c1) - 7da93c1

[UI](https://github.com/dockstore/dockstore-ui2/commits/6b02daed) - 2.11.1-61-g6b02daed

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6c0f33c) - 1.14.1-38-g6c0f33c

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
