### ISSUE TITLE
Investigate and fix flaky error in the UI

### ISSUE THREAD

**Issue by hyunnaye** [dockstore/dockstore#5631]
**Describe the bug**
During my PR, I found a flaky error for the test in `deletion.ts` https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/10546/workflows/17a22c97-ec8d-4787-b5ca-39bda1f5e2db/jobs/46982/tests

**Expected behavior**
Test should pass

**Additional context**

* UI version: 2.11.1
* Webservice version: 1.14.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2445)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2445
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
We believe this was fixed in dockstore/dockstore-ui2#1857
