### ISSUE TITLE
Publishing a Service fails with "primary descriptor not found"

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5636]
**Describe the bug**

I had previously registered a service in dev using the repository https://github.com/david4096/jupyter-dockstore

I can no longer publish the service due to an error processing the .dockstore.yml . However, the Service does seem to register.

![image](https://github.com/dockstore/dockstore/assets/3795586/eccdf01a-3d95-43f6-90f2-74af27b2a7b7)

![image](https://github.com/dockstore/dockstore/assets/3795586/ae87cc95-2c95-44a2-9a19-6cdcb11684c9)

Note: additionally the My Services page lacks the "View GitHub logs" link

**To Reproduce**

1. Go to My services
1. Register a service by connecting github
1. Make a commit to the underlying repo
1. See error in github apps logs and no Service registered

I tried both 1.1 and 1.2 schemas unsuccessfully. Verified by coverbeck

**Expected behavior**

The Service should register and publish

**Additional context**

We took a look at the codebase and it is possible that a change for 1.14 broke this by assuming the primary descriptor file is needed for services. The [existing test](https://github.com/dockstore/dockstore/blame/develop/dockstore-integration-testing/src/test/java/io/dockstore/webservice/ServiceWithSessionIT.java) does not use a .dockstore.yml but creates the service using Java objects.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/d0a47bc)

* d0a47bc

[UI](https://github.com/dockstore/dockstore-ui2/commits/838ae696)

* 2.11.1-58-g838ae696

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/12e31e6)

* 1.14.1-36-g12e31e6

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2447)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11063">image-20230925-195002.png</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11064">image-20230925-195251.png</a>
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2447
┆Sprint: 122 - Ural
┆Issue Type: Story

**Comment by coverbeck** [comment]
First finding; it looks like this only happens for previously registered services; newly created services seem to work.

**Comment by coverbeck** [comment]
There are two problems here:

1. Registering a new service -- it will be invalid because the default workflow path for a service is now `/Dockstore.cwl`, which propagates to the version, which doesn't exist, which fails validation, which means it can't be published. Fix committed locally.
2. The bulk of existing services in the DB have `descriptortypesubclass` set to the literal value `n/a`. When we try to add a new version to such a service, the version's `descriptortypesubclass` is *not* `n/a`, it's something like `DOCKER_COMPOSE`, and the web service throws trying to add a different `descriptortypesubclass` to a workflow.
