### ISSUE TITLE
Reach out to warp about tagging strategy 

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5645]
**Is your feature request related to a problem? Please describe.**
The warp tagging strategy https://github.com/broadinstitute/warp/tags with tags per workflow on develop, re-created daily(?) has a bad interaction in terms of load on Dockstore since each tag includes a .dockstore.yml with 30 workflows. https://github.com/broadinstitute/warp/blob/WholeGenomeReprocessing_develop/.dockstore.yml
It looks like 7 tags were re-created yesterday, so 210 updates?

Confirm whether Dockstore has a performance issue with this type of simultaneous update and potentially reach out to see what is going on and if there is a more performant method of achieving the goal. 

See also https://github.com/broadinstitute/warp/pull/1066 (is this occurring due to a workaround or problem on our end?)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2452)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2452
┆Sprint: 121 - Tigris
┆Issue Type: Story

**Comment by coverbeck** [comment]
> Confirm whether Dockstore has a performance issue

There's definitely a performance issue on our side with deletes for branches and tags. See the more generic #5025 and the more specific SEAB-5849. These have been addressed in #5658, #5659, and #5662, which will be part of the 1.15 release.

**Comment by coverbeck** [comment]
Also see the comment for broadinstitute/warp#1066

**Comment by coverbeck** [comment]
Had a discussion with warp developers.

- They do create "moving tags" on the develop branch; this is their development process.
- The performance issues on the Dockstore side with the deletion of tags and branches are captured in SEAB-5849 and addressed in PRs #5658 and #5662
