### ISSUE TITLE
Metrics Validator info not shown when All Platforms is selected

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5646]
**Describe the bug**
If you select All Platforms, you don't see validator information. If you select a platform that has validator info, then you do see the validator information. You would have to cycle through every platform in the UI to see if any have a validator. Admittedly, there are only 2 platforms in the example.

**To Reproduce**

1. Go to https://qa.dockstore.org/workflows/github.com/gatk-workflows/seq-format-conversion/BAM-to-Unmapped-BAM:3.0.0?tab=metrics&metrics
1. Click on the Metrics tab
1. At the bottom of the page, it says "No validator tool metrics exist"
1. Change the selection of the "Select a Platform" dropdown from "All Platforms" to "DNAstack"
1. The validator information appears!

**Expected behavior**
If all platforms is selected, I expect to see data from all platforms, for both execution and validator metrics.

**Screenshots**
All platforms selected:
![Screen Shot 2023-08-25 at 2 07 16 PM](https://github.com/dockstore/dockstore/assets/1049340/606bbb00-002d-427e-8c83-9ad67e3b9203)

DNAstack platform selected:
![Screen Shot 2023-08-25 at 2 07 27 PM](https://github.com/dockstore/dockstore/assets/1049340/b3641bf1-3378-492e-80ca-66cd5d07b269)

**Additional context**
Happens in prod too.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/c4ce5d8)

* c4ce5d8

[UI](https://github.com/dockstore/dockstore-ui2/commits/5a654266)

* 2.11.1-59-g5a654266

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6c0f33c)

* 1.14.1-38-g6c0f33c

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2454)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11066">image-20230927-190054.png</a>
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2454
┆Sprint: 122 - Ural
┆Issue Type: Story

**Comment by kathy-t** [comment]
Hmm, wonder if this is a metrics aggregator problem instead of the UI. The response from getting all the metrics is:
```
{
	"DNA_STACK": {
		"cost": null,
		"cpu": null,
		"executionStatusCount": null,
		"executionTime": null,
		"id": 7387,
		"memory": null,
		"validationStatus": {
			"id": 7388,
			"validatorTools": {
				"MINIWDL": {
					"id": 7375,
					"mostRecentVersionName": "Not specified",
					"numberOfRuns": 1,
					"passingRate": 100,
					"validatorVersions": [
						{
							"dateExecuted": "2023-06-02T19:50:28Z",
							"errorMessage": null,
							"id": 7375,
							"isValid": true,
							"name": "Not specified",
							"numberOfRuns": 1,
							"passingRate": 100
						}
					]
				}
			}
		}
	},
	"AGC": {
		"cost": null,
		"cpu": {
			"average": 8,
			"id": 81,
			"maximum": 8,
			"minimum": 8,
			"numberOfDataPointsForAverage": 15,
			"unit": null
		},
		"executionStatusCount": {
			"count": {
				"SUCCESSFUL": 48
			},
			"id": 16728,
			"numberOfFailedExecutions": 0,
			"numberOfSuccessfulExecutions": 48
		},
		"executionTime": {
			"average": 8226.604166666666,
			"maximum": 24974,
			"minimum": 504,
			"numberOfDataPointsForAverage": 48,
			"id": 82,
			"unit": "s"
		},
		"id": 16720,
		"memory": null,
		"validationStatus": null
	},
	"ALL": {
		"cost": null,
		"cpu": {
			"average": 8,
			"id": 83,
			"maximum": 8,
			"minimum": 8,
			"numberOfDataPointsForAverage": 15,
			"unit": null
		},
		"executionStatusCount": {
			"count": {
				"SUCCESSFUL": 48
			},
			"id": 16729,
			"numberOfFailedExecutions": 0,
			"numberOfSuccessfulExecutions": 48
		},
		"executionTime": {
			"average": 8226.604166666666,
			"maximum": 24974,
			"minimum": 504,
			"numberOfDataPointsForAverage": 48,
			"id": 84,
			"unit": "s"
		},
		"id": 16721,
		"memory": null,
		"validationStatus": null
	}
}
```

Notice how `ALL` has a null `validationStatus`

**Comment by kathy-t** [comment]
Checked the QA metrics S3 bucket for this workflow, and it has no DNAstack metrics so technically, it shouldn't even show the DNAstack platform. 

I think there's a data inconsistency issue between QA and prod because [prod](https://dockstore.org/workflows/github.com/gatk-workflows/seq-format-conversion/BAM-to-Unmapped-BAM:3.0.0?tab=metrics&metrics) shows the validation metrics when the platform is ALL:
![image](https://github.com/dockstore/dockstore/assets/25287123/995bcd67-2feb-4947-8182-2efbf6fcdb67)

We did a restore from prod in QA on July 7th, 2023 according to this [comment](https://ucsc-cgl.atlassian.net/browse/DOCK-2422?focusedCommentId=45604) which may have caused this inconsistency where the database thinks there's metrics but there's no corresponding metrics in S3 for the DNAstack platform. It confuses me that there's no ALL metric for the DNAstack validation metrics because if it copied the metrics data from prod, then it should have it :thinking: 

I think I will try another restore from prod in QA to see if that fixes the issue.

**Comment by coverbeck** [comment]
Confirmed that it now works in qa.
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/77f7f73) - 77f7f73

[UI](https://github.com/dockstore/dockstore-ui2/commits/37729cbb) - 2.11.1-70-g37729cbb

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/7ae1315) - 1.14.1-47-g7ae1315

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
