### ISSUE TITLE
Cannot search for a phrase

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5647]
**Describe the bug**
You can't search for a phrase in the UI, only individual words. Or maybe you can, but the UI indicates otherwise.

**To Reproduce**

1. Go to https://qa.dockstore.org/search?entryType=workflows&searchMode=files
1. Enter "variant caller", with the quotes, in the search term box.
1.  Results are displayed, I'm not sure what exactly, with the message `Search: contains one of ""variant, caller""` -- note the double double quotes and the comma. According to the message, it's presumably searching for workflows that contain either `variant` or `caller`.

**Expected behavior**
It should search for the phrase `variant caller`, and indicate so in the UI.

**Screenshots**
![Screen Shot 2023-08-25 at 4 27 46 PM](https://github.com/dockstore/dockstore/assets/1049340/b61c859e-590c-4bf8-9c01-2f142efd521a)

**Additional context**
Happens in prod too.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/c4ce5d8)

* c4ce5d8

[UI](https://github.com/dockstore/dockstore-ui2/commits/5a654266)

* 2.11.1-59-g5a654266

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6c0f33c)

* 1.14.1-38-g6c0f33c

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2455)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2455
┆Sprint: 144 - Qinhuangdao
┆Issue Type: Story

**Comment by david4096** [comment]
Jumping in to add that it appears that when trying to use quotes in the freetext box you get a 400 until the quotes are closed

![image](https://github.com/dockstore/dockstore/assets/3795586/854464fc-7f3d-4eac-b9ad-dad1054e06fa)

**Comment by coverbeck** [comment]
> Jumping in to add that it appears that when trying to use quotes in the freetext box you get a 400 until the quotes are closed. 

That one should be fixed by SEAB-3957
