### ISSUE TITLE
Search results table and most facets can disappear

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5648]
**Describe the bug**
A certain set of steps, with a boolean facet involved being relevant, I think, can cause the search results table and most facets to disappear.

**To Reproduce**

Short version

1. Go to https://qa.dockstore.org/search?descriptorType=gxformat2&has_checker=1&entryType=workflows&searchMode=files

Long version, how I discovered the issue:

1. Go to https://qa.dockstore.org/search
1. Select the WDL and Galaxy language facets.
1. Select the `has a checker workflow` facet.
1. Deselect the WDL facet. See the mainly empty screen, screenshot attached.~~

**Expected behavior**
All the facets should be displayed, and there should be a search table, even if there are no results.

**Screenshots**
![Screen Shot 2023-08-29 at 10 41 15 AM](https://github.com/dockstore/dockstore/assets/1049340/e3043119-d22c-46d2-9a08-dd9950ed91fd)

**Additional context**
The number of checker workflows facet jumps at step 3. Prior to selecting the facet, the facet reflected the number of Galaxy and WDL workflows that had checkers. After selecting it, the facet number reflected all workflows that have checkers; the (previously selected) Galaxy facet disappeared. I'm guessing the fact that I have a language facet selected that does not match any values in the boolean `has checker workflow` facet is tied into the bug.

Happens in prod, staging, and qa.
[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.2)

* 1.14.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.1)

* 2.11.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14)

* 1.14

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.1)

* 1.14.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2456)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2456
┆Sprint: 124 - Welland Canal
┆Issue Type: Story

**Comment by coverbeck** [comment]
Capturing my investigation so far before I take a few days off...

I'd never paid close attention, but in looking at this, our facets intentionally disappear from the UI when they are no longer applicable.

For example, the `Engine Versions` facet currently only has values for Nextflow workflows -- click a non-Nextflow language facet, e.g., `CWL`, and the Engine Versions facet disappears. It makes sense. Amazon does something similar when you narrow down a search.

What's happened here is that we've ended up in state where two facets are selected, `Galaxy` and `has checker workflow`, and there are no overlapping hits between the two.

Ideas:

1. Add a message in the blue box saying there are no hits. Instruct them to click the Reset button to start over.
2. Still need to figure out why, in the example, only the language facet is appearing. But if we want to be consistent in not showing non-applicable facets, then that facet should probably go away as well.
3. If we implement idea 2, then the facets column will be totally empty, so we should probably have something there; maybe the message from  idea 1.
4. Alternatively, if we detect no matches, maybe we auto reset, and have some sort of message saying, very roughly, "No matches found, resetting search".
5. Alternative 2, if we detect no matches, we display a message and go back to the last state that had matches (as opposed to doing a complete reset of search as proposed in step 4).

**Comment by denis-yuen** [comment]
1 seems least confusing (looks like good does a "did you mean" result, but duckduckgo still does no results https://duckduckgo.com/?q=%22striking+salmon+air+quality+%22&ia=web ) 
2 is worth looking into.

Feel like the message in 4 and  5 could be missed and be confusing.
