### ISSUE TITLE
Search needs to be more relevant

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5651]
**Is your feature request related to a problem? Please describe.**
Users (myself included) often have issues finding widely-used tools or workflows on Dockstore using the search feature, because it's not specific enough. Addressing #5647 probably isn't sufficient since this affects one-word searches too, eg the top result for "samtools" is the [UM variant caller](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=files), which doesn't even mention samtools on its (primary) WDL or readme.

**Specific examples**

#### [default (non-advanced) search for "samtools" AND "index", narrowed down to WDL](https://dockstore.org/search?descriptorType=WDL&entryType=workflows&search=samtools%20index)
* Top result: [UM variant caller](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=files). ~~This entry doesn't seem to even mention samtools at all -- however, it does import a WDL that does have a single call to `samtools index`.~~ It's in the secondary entry file.
* [Actual samtools index workflow 1](https://dockstore.org/workflows/github.com/MilanParikh/samtools_index:master?tab=info): Present, but at rank 191, just before the 200 result cutoff.
* [Actual samtools index workflow 2](https://dockstore.org/workflows/github.com/aofarrel/samtools-index-WDL/samtools_index:main?tab=info): Not present
![](https://github.com/dockstore/dockstore/assets/27784612/dc84e09c-3a0f-43f9-acff-cabd2654921b)

#### [advanced search for "samtools" AND "index", narrowed down to WDL, search descriptors instead of files](https://dockstore.org/search?descriptorType=WDL&entryType=workflows&ANDNoSplitFilter=samtools%20index&searchMode=description)
* Top result: [Julian's bootcamp testing WDL](https://dockstore.org/workflows/github.com/juklucas/ucsc-bootcamp-wdl:main?tab=info), which is indeed a samtools bam indexer
* [Actual samtools index workflow 1](https://dockstore.org/workflows/github.com/MilanParikh/samtools_index:master?tab=info): Not present.
* [Actual samtools index workflow 2](https://dockstore.org/workflows/github.com/aofarrel/samtools-index-WDL/samtools_index:main?tab=info): Present, but it's the last result.
![](https://github.com/dockstore/dockstore/assets/27784612/544cc354-730b-43ee-873c-447a84f4201f)

**Describe the solution you'd like**
If a user searches files for "samtools"+"index" (putting aside exact phrase search for now due to #5647), search results should be ranked like this:

1. Workflow name includes "samtools-index" or "samtools_index" (rank capitals same as lowercase for this and all others)
1. Workflow topic includes "samtools index"
1. Workflow name includes "samtools" and "index"
1. Workflow topic includes "samtools" and "index"
1. Workflow name contains either "samtools" or "index", and the word the name doesn't contain is in a file somewhere
1. Workflow entry has a task, workflow, or subworkflow named "samtools_index", or "samtools-index"
1. Workflow entry has a task, workflow, or subworkflow that contains "samtools" or "index", and the word the task/workflow/subworkflow doesn't contain is in the file somewhere
1. Workflow entry has "samtools index" in a file somewhere
1. Workflow entry has "samtools" and "index" in some files somewhere

Within these criteria, workflows would be ordered based on "popularity" (stars, imports, views), "maturity" (time since entry was made), whether or not they are verified, whether or not the have open sample data, and probably other metrics I can't think of. But, ultimately, a verified mature workflow like the UM Variant Caller shouldn't be the first result for "samtools index" over two actual samtools index entries.

**Describe alternatives you've considered**

* Allow users to choose between ranking algorithms -- such as relevance vs popularity 
  * search results can already be ordered by author, verification, and format -- perhaps new fields are needed?
* If someone's not searching an exact phrase, don't rank the exact phrase above the separated form, eg: "samtools"+"index" ranking instead looks like:
  1. Workflow name includes "samtools" and "index"
  1. Workflow topic includes "samtools" and "index"
  1. Workflow name contains either "samtools" or "index", and the word the name doesn't contain is in a file somewhere
  1. Workflow entry has a task, workflow, or subworkflow named contains "samtools" or "index", and the word the task/workflow/subworkflow doesn't contain is in the file somewhere
  1. Workflow entry has "samtools" and "index" in some files somewhere

**Additional context**
This is something I've been trying to articulate for a while now, but the immediate inspiration was https://support.terra.bio/hc/en-us/community/posts/360056467732/comments/18357117456155

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2458)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-2458
┆Sprint: Backlog
┆Issue Type: Story

**Comment by david4096** [comment]
Agreed with all of the above with the addition that samtools sort appears in the secondary descriptor file in this case.
