### ISSUE TITLE
Flaky test on the UI for mytools.ts

### ISSUE THREAD

**Issue by hyunnaye** [dockstore/dockstore#5696]
**Describe the bug**
Encountered this flaky test on the UI for my PR. 

```
AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-cy=topicInput]`, but never found it.
    at Context.eval (webpack://dockstore-ui2/./cypress/e2e/group3/mytools.ts:99:9)
```

https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/10741/workflows/45e9d688-6602-4e8a-9c0a-8669e19fe6e0/jobs/47884/tests

**Expected behavior**
Test should pass

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2471)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2471
┆Sprint: 124 - Welland Canal
┆Issue Type: Story

**Comment by coverbeck** [comment]
In dockstore/dockstore-ui2#1848, skipped flaky test. Implementer of this fix should remove the skip [here](https://github.com/dockstore/dockstore-ui2/pull/1848/files#diff-41f85017f384885a5423e1476541ac02606ef7127ebf482a6046fc6e87d0cd16R60).
