### ISSUE TITLE
Remove deprecated updateEntryToGetTopics one-time endpoint

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5712]
**Describe the bug**
The following endpoint is deprecated and should be remove, along with its associated code. This endpoint was only meant to be run once when we first introduced `topicAutomatic`.
https://github.com/dockstore/dockstore/blob/b6984668f4a2249b06a59e355c1aad5d71e65867/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EntryResource.java#L683-L700

**To Reproduce**
n/a, code cleanup

**Expected behavior**
Deprecated and unused code related to the endpoint should be removed.

**Screenshots**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2475)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2475
┆Sprint: 137 - Jacksonville
┆Issue Type: Story

**Comment by denis-yuen** [comment]
FYI, introduced in 1.12
