### ISSUE TITLE
Creating a Zenodo DOI results in a 500

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5740]
**Describe the bug**
A user is unable to request a DOI because it results in a 500. Interestingly, the DOI is actually created successfully on Zenodo, so there's something wrong on Dockstore's end.

Looking at the logs, it's failing with a null pointer exception on this line, meaning that the DOI URL passed to the function is null.
https://github.com/dockstore/dockstore/blob/5cef678c176ee3c4abe81b1856be0887abc7a84c/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ZenodoHelper.java#L180

The DOI URL provided to the function is the concept DOI URL, retrieved on this line:
https://github.com/dockstore/dockstore/blob/5cef678c176ee3c4abe81b1856be0887abc7a84c/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ZenodoHelper.java#L163

Testing locally, I don't see this `conceptdoi` key in the published deposit's `links` array. Zenodo may have changed their API somehow, making the way we retrieve the concept DOI invalid.

**To Reproduce**

1. Publish a valid workflow
1. Click Request DOI
1. See that the DOI request failed with a 500 error

**Expected behavior**
The DOI should be created successfully and there should be no error. If we're unable to retrieve the concept DOI for whatever reason, return an appropriate error that is not 500.

**Screenshots**
This screenshot was from @aofarrel's attempt to request a DOI

![image](https://github.com/dockstore/dockstore/assets/25287123/e3bfe66a-667c-430d-b4b1-722e17a4dfcd)

[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.3)

* 1.14.3

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.1)

* 2.11.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14)

* 1.14

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.4)

* 1.14.4

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2489)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11105">image-20231219-183246.png</a>
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2489
┆Sprint: 127 - Zora
┆Issue Type: Story

**Comment by denis-yuen** [comment]
> Testing locally, I don't see this `conceptdoi` key in the published deposit's `links` array. Zenodo may have changed their API somehow, making the way we retrieve the concept DOI invalid.

Total guess, could be related to the [InvenioRDM](https://inveniordm.docs.cern.ch/reference/rest_api_index/) release
https://help.zenodo.org/docs/about/whats-new/
