### ISSUE TITLE
Detect and display DOIs that are generated by Zenodo's integration with GitHub

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5745]
**Is your feature request related to a problem? Please describe.**
Zenodo is able to generate a DOI for each release of a GitHub repository. There are details about it [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content). These releases may be workflow versions that exist on Dockstore.

**Describe the solution you'd like**
Investigate if Dockstore is able to detect DOIs that are generated from this Zenodo/GitHub integration. If we're able to detect them, we should save and display them in the UI.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2493)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2493
┆Sprint: 138 - Keelung
┆Issue Type: Story

**Comment by coverbeck** [comment]
Some observations:

* When Zenodo creates a DOI for a GitHub release, the DOI has a reference to the GitHub repo, but not vice-versa. We will need to query Zenodo to figure this out.
* It looks like Zenodo creates versions for the different branches, under one "concept" DOI. Which I think is what Dockstore does when creating DOIs as well.
* It looks like we can use the Zenodo search API. Still figuring out details about how to construct the query. So far, just using curl, I can do it anonymously. Not sure if I'll run into rate limits though.

**Comment by coverbeck** [comment]
Started a document here: https://docs.google.com/document/d/14RhZnnzkYFWW0-SU0NtKN31aeMyVTQGNXkkImD6VZw8/edit
