### ISSUE TITLE
"Not found" entry page needs adjustment

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#5785]
**Describe the bug**
When you navigate to the public URL of an existing Dockstore entry that is no longer published, Dockstore displays some "could not be found" content.  This content needs some fixin':

1. The correct entry type should be displayed.  For example, in the screenshot below, "workflow" should be "notebook".
1. The links appear to be malformed/wrong.
1. Arguably, if I have access to the entry's private page, I should be redirected there, instead. 

There could be other issues.

It should be noted that I found the bug when clicking on the link on my profile page, to one of my own notebooks.  In lieu of the above redirect, perhaps, when, I’m viewing my own profile, the entry links should be to the private entry page?

Inspect for the various entry types, devise solutions, and implement them.

**To Reproduce**

1. Enter the public URL of a Dockstore entry that exists, but is not published.
1. See the bugs.

**Expected behavior**
Correct information is displayed, and the redirection mentioned above happens.

**Screenshots**

![width=200,height=183](https://github.com/dockstore/dockstore/assets/88108675/4847ed28-73fe-4038-a558-2c0e5f93accd)

**Additional context**
[Domain] - [https://qa.dockstore.org](https://qa.dockstore.org/)

[Webservice](https://github.com/dockstore/dockstore/commits/3879929)

* 3879929

[UI](https://github.com/dockstore/dockstore-ui2/commits/6251a483)

* 2.12.0-beta.0-14-g6251a483

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/ef77999)

* 1.14.4-62-gef77999

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2499)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2499
┆Sprint: 132 - Elutherios
┆Issue Type: Story

**Comment by denis-yuen** [comment]
See also https://github.com/dockstore/dockstore/issues/5728
