### ISSUE TITLE
Better messaging for secondary files

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#579]
### Desired behaviour

See #548 
Currently, it looks like default logging for secondary files is unclear (can confuse an error on the next file with an error for the current file). Improve this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-170)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-170

**Comment by melainalegaspi** [comment]
reopen if it shows up again
