### ISSUE TITLE
Tooltips in Versions table obstruct user actions

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#5793]
**Describe the bug**
When I view the Versions table for an Entry, then mouse down and right to the Info/Actions button, when my cursor reaches the button, a tooltip that says "Actions to apply to the version" appears over the button, and I can't click the button until I do a little dance with my cursor to make the tooltip disappear.

I understand the value of tooltips, but I run into this type of problem nearly every time I use Dockstore, it's probably quite frustrating for our users.

**To Reproduce**
See above.

**Expected behavior**
I can use the Dockstore UI without interference from tooltips.

**Screenshots**

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome

**Additional context**
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/edbb65e)

* edbb65e

[UI](https://github.com/dockstore/dockstore-ui2/commits/dd56cbb3)

* 2.12.0-rc.1-11-gdd56cbb3

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/136ec86)

* 1.14.4-71-g136ec86

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2504)
┆Fix Versions: Dockstore 1.15.x
┆Issue Number: DOCK-2504
┆Sprint: 130 - Carthago
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Could be variant of https://github.com/dockstore/dockstore/issues/5258
