### ISSUE TITLE
GA4GH service registry has incorrect TRS information

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5803]
**Describe the bug**
The GA4GH service registry returns the wrong url for the Dockstore TRS API.

**To Reproduce**
```
curl -s https://registry.ga4gh.org/v1/services/org.dockstore.dockstoreapi | jq '.'
{
  "id": "org.dockstore.dockstoreapi",
  "name": "Dockstore",
  "type": {
    "group": "org.ga4gh",
    "artifact": "trs",
    "version": "2.0.0"
  },
  "organization": {
    "id": "org.dockstore",
    "name": "Dockstore",
    "url": "https://dockstore.org"
  },
  "version": "1.8.1",
  "url": "https://dockstore.org/api/api/ga4gh/v2/",
  "description": "Dockstore TRS implementation",
  "documentationUrl": "https://dockstore.org/api/static/swagger-ui/index.html"
```

Note the url value `https://dockstore.org/api/api/ga4gh/v2/`  should be `https://dockstore.org/api/ga4gh/trs/v2/`.

Also, the `version` value looks wrong, assuming that's the Dockstore version.

**Expected behavior**
The url should be `https://dockstore.org/api/ga4gh/trs/v2/`

**Additional context**
I probably should log this in a GA4GH repo, but I don't know which one.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2510)
┆Issue Number: DOCK-2510
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment]
Just noticed that two versions are wrong:

* `type.version` should be `2.0.1` instead of `2.0.0`.
* `version` should be `1.15` or `1.15.0` instead of `1.8.1`.

**Comment by denis-yuen** [comment]
Not a ton of info, but this is fixed now. 
FYI @kathy-t if it came up during that TRS notebook example
