### ISSUE TITLE
GitHub App push events are ignored for annotated tags

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5807]
**Describe the bug**
Push events for annotated tags are ignored with a `This event was ignored because a subsequent event was processed instead` message. 

This does not affect lightweight tags.

**To Reproduce**
1. Create an annotated tag in GitHub for a repository that's registered as a GitHub app workflow.
2. Go to the GitHub App workflow on Dockstore and view the GitHub App logs.
3. See that the PUSH event for the tag was ignored.

![image](https://github.com/dockstore/dockstore/assets/25287123/bb8d7c6d-62cf-45b4-9051-79871e312e04)

**Expected behavior**
Annotated tags should not be ignored in push events.

**Additional context**
[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.0) - 1.15.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.0) - 2.12.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0) - 1.15.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2512)
┆Issue Number: DOCK-2512
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Reviewed by hotfix and  https://github.com/dockstore/dockstore/issues/5806 essentially
