### ISSUE TITLE
Optimize executions endpoints - jpql - s3client

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5831]
**Is your feature request related to a problem? Please describe.**
The executions endpoint validate a version exists by iterating through the workflow's versions in Java. This can be slow and resource intensive for certain workflows with hundreds of versions.

**Describe the solution you'd like**
`WorkflowVersionDAO` has a method to fetch a workflow version by name, using JPA/SQL. We should use that.

**Describe alternatives you've considered**

**Additional context**
Discovered during metrics testing

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2515)
┆Fix Versions: Dockstore 1.15.x
┆Issue Number: DOCK-2515
┆Sprint: 133 - Freeport
┆Issue Type: Story

**Comment by coverbeck** [comment]
Another optimization we could do is not [create a new S3Client](https://github.com/dockstore/dockstore/blob/d542752dde9c2751a6256d54c6b64426e1e0c889/dockstore-common/src/main/java/io/dockstore/common/S3ClientHelper.java#L60) for every request. The S3Client is thread-safe, so we should be able to instantiate it just once.

**Comment by denis-yuen** [comment]
Seems like the s3client part could be a hotfix

**Comment by denis-yuen** [comment]
Took a look, it looks like setting `@UnitOfWork(readOnly= true)` should be worth a try. 
I think you still need the db connection, but it does improve performance 

https://github.com/dockstore/dockstore/issues/3525
https://github.com/dockstore/dockstore/issues/3582

https://thorben-janssen.com/read-only-query-hint/

**Comment by coverbeck** [comment]
> ➤ Kathy Tran commented:
> 
> There’s also a CRT-based S3 client that has enhanced performance https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/ ( [https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/|smart-link](https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/%7Csmart-link) )

Interesting, skimming it, I think it would make more of a difference for files larger than what we're dealing with, but definitely worth a shot.
