### ISSUE TITLE
Refresh of tools not pulling in new versions

### ISSUE THREAD

**Issue by keiranmraine** [dockstore/dockstore#584]
### Expected behaviour

Should pick up new versions when Quay.io image and GitHub have tags

### Actual behaviour

Nothing happens

### Steps to reproduce the behaviour 

Open an existing tool which has a new GitHub tag and Quay image already built.  Hit refresh.  The new version doesn't appear in the list.

Specifically occurred on dockstore-cgpwxs v1.0.3.  Noted that previous tag (1.0.2) was not marked as 'Automated' so deleted that version and refreshed to see if that resolved the issue.

Worked on dockstore-cgpmap on Feb 1st.

### Environment (Browser or OS and Dockstore version)

Chrome 55.0.2883.95 (64-bit)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-471)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-471

**Comment by keiranmraine** [comment]
FYI, continues to affect dockstore-cgpwxs, but not dockstore-cgpmap or dockstore-cgpwgs

**Comment by garyluu** [comment]
@keiranmraine Dockstore-cgpmap and dockstore-cgpwgs has a build mode that's Fully-Automated.  Dockstore-cgpwxs has a build mode that's Manual.  Refreshing a manual tool currently does not automatically add versions/tags.  If you wish to convert dockstore-cgpwxs to one that is Fully-Automated, a workaround is to deregister it and then "Refresh All Tools".  Dockstore should automatically add that tool.

**Comment by denis-yuen** [comment]
@garyluu @keiranmraine  
Reviewing issues for the 1.2 release. It looks like a workaround is in play since dockstore-cgpwxs looks like it displays versions from 1.0.3 and onward. 

That said, it looks like dockstore-cgpwxs is registered as a "manual" mode tool rather than an automated build as expected. @keiranmraine would this be a use case for a tool delete feature (so that the tool can be re-created properly)

**Comment by keiranmraine** [comment]
@denis-yuen , I'll have to see what happens when I try the next tag.  I've always had to add them manually.  I've previously tried deregistering and re-adding but the same issue persisted on the next tagging of the repo.

Likely I'll be doing a new tag quite soon.

(@garyluu sorry I didn't respond sooner)

**Comment by garyluu** [comment]
https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwxs:3.1.6?tab=info looks like its in fully-automated mode.  I do see new tags, but not sure if that was manually added or not.

**Comment by garyluu** [comment]
Closing in favor of https://github.com/dockstore/dockstore/issues/2760
