### ISSUE TITLE
Don't display AI bubble if the AI topic has been approved/selected by a user

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5866]
**Is your feature request related to a problem? Please describe.**
If a user chooses to use an AI topic (as opposed to automatically being opted-in because there's no topic), we should not display the AI bubble because it has been vetted by the user.

**Describe the solution you'd like**
Some ideas:

1. If the user manually selects AI generated as the topic selection, don't display the AI bubble, but I'm not sure how we would differentiate that
1. Better UI to handle the copying of the AI topic to the manual topic like a button that says "Approve AI topic" which copies and sets it as the manual topic?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2521)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2521
┆Sprint: 142 - Ostia Antica
┆Issue Type: Story

**Comment by coverbeck** [comment]
Perhaps when editing the manual topic, we could have a suggest topic button that puts the AI topic into the manual field, then the user has chance to tweak it if the want to.

**Comment by denis-yuen** [comment]
> like a button that says "Approve AI topic"  

Like the one button idea
