### ISSUE TITLE
"Cite all versions" DOI is unclear, and also wrong

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5892]
**Describe the bug**
While looking into https://github.com/dockstore/dockstore/issues/5891, I found a fifth(!) DOI appeared in my workflow. This DOI is an invalid link and doesn't seem to match any of the DOIs mentioned in that ticket. This shows in both my-workflows view and also the public view:
![](https://github.com/dockstore/dockstore/assets/27784612/a3608859-c505-4d09-9e21-a91c33ff20e7)

I eventually realized the 11237485 DOI is actually the cite-all-versions DOI:

![](https://github.com/dockstore/dockstore/assets/27784612/abb4e2b0-743e-4ef5-875d-9257426e0fa3)

Except there's two problems:

* The URL is `https://doi.org/doi/10.5281/zenodo.11237485` but should be `https://doi.org/10.5281/zenodo.11237485`
* It's not listed as a "cite all versions" DOI or something of the sort, so it's not at all clear to the user why it contradicts version-specific DOIs directly under it 

**To Reproduce**
It seems very likely this is totally separate from the disappearing DOI issue discussed in https://github.com/dockstore/dockstore/issues/5891, so reproducing should just be:

1. Make a DOI of some version of a workflow
1. Make a DOI of another version of a workflow
1. See a third DOI in the workflow view that is unclearly labeled, and also an invalid link

**Expected behavior**

* All DOI URLs should be correct
* It should be clear why there can be two different DOIs on a workflow's page

**Additional context**
[Domain] - https://dockstore.org
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.2)

* 1.15.2
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.1) - 2.12.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0) - 1.15.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2527)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11171">image-20240610-175828.png</a> | <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11172">image-20240610-175856.png</a>
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2527
┆Sprint: 138 - Keelung
┆Issue Type: Story

**Comment by denis-yuen** [comment]
I think this is https://github.com/dockstore/dockstore/issues/5875 (at least the broken link part)

**Comment by aofarrel** [comment]
Ooh, yep, #5875 beat me to the punch. I do think there is still a UI issue because it's not clear what the concept DOI is in the first place, but feel free to adjust this into a UI ticket as needed.
