### ISSUE TITLE
Make github-landing-page example .dockstore.yml copyable

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5904]
**Is your feature request related to a problem? Please describe.**

Tried to use the example .dockstore.yml on the GitHub landing page and the indentation made it difficult. There is one level of indentation added to every line

![image](https://github.com/dockstore/dockstore/assets/3795586/7a895005-9b6f-4556-9027-eb3d551290e7)

**Describe the solution you'd like**

The editor text should be more readily usable by removing the indentation.

**Describe alternatives you've considered**

n/a

**Additional context**

Came up during prep for presentation for WDL bootcamp

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2532)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11177">Screenshot 2024-06-24 at 2.39.28 PM.png</a>
┆Fix Versions: Dockstore 1.15.x
┆Issue Number: DOCK-2532
┆Sprint: 139 - Lothal
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Probably better than https://ucsc-cgl.atlassian.net/browse/SEAB-6486 (should be public), can close when jira is back up

**Comment by david4096** [comment]
Noting that the new code cell fixes the indentation problem but that the version field is not copyable. The comment on the schema line causes the parsing to fail I believe.

![image](https://github.com/dockstore/dockstore/assets/3795586/1c2a9d61-ccca-4bc0-b2c9-285702910fbf)

I removed it and was able to successfully push

![image](https://github.com/dockstore/dockstore/assets/3795586/3105b4d1-843c-44b0-8c02-e9437b7c961f)

**Comment by denis-yuen** [comment]
Hmmm, I'd think that would be a bug in the parsing code rather than an issue with the landing page. 

circleci yaml has a ton of this https://github.com/dockstore/dockstore/blob/develop/.circleci/config.yml and as separated comments 6.9  https://yaml.org/spec/1.2.2/#66-comments

**Comment by denis-yuen** [comment]
(attempted fix as part of merge of hotfix 2.12.3)
