### ISSUE TITLE
Versions page for Nextflow should display engine versions not DSL1/2

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5918]
**Is your feature request related to a problem? Please describe.**
See https://github.com/dockstore/dockstore/issues/5917 

Engine versions will be more useful than distinction between DSL1/2 (presume that there will not be a DSL3, 4, etc.)

**Describe the solution you'd like**
Display engine version instead of language version on pages such as https://dockstore.org/workflows/github.com/nf-core/rnaseq:dev?tab=versions for Nextflow

**Describe alternatives you've considered**
Rename and consider engine version the new language version?

**Additional context**

[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.2)

* 1.15.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.2)

* 2.12.2

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0)

* 1.15.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2536)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2536
┆Sprint: 143 - Piraeus
┆Issue Type: Story

**Comment by coverbeck** [comment]
Agreed this makes a lot of sense for Nextflow, and the issue title says Nextflow. I think we should keep the language version for other languages, since we only capture engine version for Nextflow.

**Comment by bentsherman** [comment]
Moving forward the engine version and language version will essentially be the same, so they can be used interchangeably
