### ISSUE TITLE
Nextflow engine version not up-to-date with file contents

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5919]
**Describe the bug**
Sometimes it looks like the engine version we parse from nextflow does not match the file we stored. 

**To Reproduce**

https://dockstore.org/workflows/github.com/nf-core/rnaseq:dev?tab=files displays `!>=23.04.0` but the info page displays `!>=22.10.1 ` 
A similar issue with https://dockstore.org/workflows/github.com/nf-core/rnaseq:master?tab=info

On the other hand https://dockstore.org/workflows/github.com/nf-core/rnaseq:strand_param_fixes?tab=info is up-to-date

**Expected behavior**
Files page engine version should match version parsed into info and search

[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.2)

* 1.15.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.2)

* 2.12.2

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0)

* 1.15.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2537)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2537
┆Sprint: 141 - Narbo
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Split from https://github.com/dockstore/dockstore/issues/5917

**Comment by coverbeck** [comment]
See [this comment](https://github.com/dockstore/dockstore/issues/5917#issuecomment-2189410758) -- I think it is there, if I understand correctly.

**Comment by denis-yuen** [comment]
I think there's something more going on. So if we look at the Info page we see `!>=22.10.1`

![Screenshot from 2024-06-25 14-02-21](https://github.com/dockstore/dockstore/assets/1730679/996f9420-eb02-40da-a204-4233ff88a7e5)

But on the same version if we switch to files we see `!>=23.04.0` 

![Screenshot from 2024-06-25 14-02-08](https://github.com/dockstore/dockstore/assets/1730679/cad21747-5dfb-4341-aecf-1f34d42d3463)
