### ISSUE TITLE
Pictures in Mastodon posts are undefined and break the account dropdown

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5930]
**Describe the bug**
The account dropdown on the home page was broken because of an error from the Mastodon feed. See discussion in https://oicr.slack.com/archives/C05EZH3RVNY/p1720052421982209.

Turns out, we recently created a post that has a picture and that resulted in `undefined` errors.

**To Reproduce**

1. Create a Mastodon post with a picture 
1. Go to prod or QA and open the developer's tool console. See the undefined errors
1. From the home page, click the account dropdown. See that nothing happens

**Expected behavior**
Photos in Mastondon posts should be displayed in the feed and the account dropdown should not be broken

**Additional context**
[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.3)

* 1.15.3

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.3)

* 2.12.3

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0)

* 1.15.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2546)
┆Fix Versions: Dockstore 1.15.x
┆Issue Number: DOCK-2546
┆Sprint: 141 - Narbo
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Actually, marked as done in jira
