### ISSUE TITLE
Adding an AI topic for a snapshotted workflow leads to 500

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5986]
**Describe the bug**

In testing AI topic feature I found that trying to add a topic via the API for a snapshotted workflow threw a 500

**To Reproduce**

```
curl -X 'PUT' \
  'https://qa.dockstore.org/api/api/ga4gh/v2/extended/%23workflow%2Fdockstore.org%2Fdavid4096%2Ftestw/updateAITopic?version=1' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{
  "aiTopic": "string t"
}'
```

```
{
  "code": 500,
  "message": "Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: /* update io.dockstore.webservice.core.WorkflowVersion */ update workflowversion set aiTopicProcessed=?, commitID=?, dbUpdateDate=?, dirtyBit=?, frozen=?, name=?, parentid=?, readMePath=?, reference=?, referenceType=?, userFiles=?, valid=?, versioneditor_id=?, dagJson=?, isLegacyVersion=?, kernelImagePath=?, lastModified=?, synced=?, toolTableJson=?, workflowPath=? where id=? Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: /* update io.dockstore.webservice.core.WorkflowVersion */ update workflowversion set aiTopicProcessed=?, commitID=?, dbUpdateDate=?, dirtyBit=?, frozen=?, name=?, parentid=?, readMePath=?, reference=?, referenceType=?, userFiles=?, valid=?, versioneditor_id=?, dagJson=?, isLegacyVersion=?, kernelImagePath=?, lastModified=?, synced=?, toolTableJson=?, workflowPath=? where id=? "
}
```

**Expected behavior**

I believe the topic is tangential to snapshotting and should be allowed. That or a useful error message.

**Additional context**

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/ebb5684)

* ebb5684

[UI](https://github.com/dockstore/dockstore-ui2/commits/20802cb8)

* 2.12.5-92-g20802cb8

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/b4fac4c)

* 1.15.2-58-gb4fac4c

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2573)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11206">image-20241016-193748.png</a>
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2573
┆Sprint: 146 - Tsim Sha Tsui
┆Issue Type: Story

**Comment by denis-yuen** [comment]
See also https://github.com/dockstore/dockstore/pull/5970#issuecomment-2289448347
