### ISSUE TITLE
Feature request: separate repositories for Dockerfile and CWL file(s)

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [dockstore/dockstore#605]
### Desired behaviour

It sometimes happens that a person might create a docker container with some tools in it, and another person might want to create a CWL tool based on that container, and register it. Currently, dockstore.org requires that the Dockerfile of a tool/workflow reside in the same repository as the CWL/WDL for it. But this gets complicated if the Dockerfiles and CWLs are created separately, in separate repositories. This can happen if a user decides to create a CWL file based on someone else's Dockerfile, but wants to reference the original docker image rather than create their own derivative.

Possible workarounds include a stub Dockerfile that references the main docker file (via `FROM`) or pull requests from one repo to another, but it would be cleaner, I think, if there was an option to have different repositories for Dockerfiles and CWL/WDL files.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-473)
┆Epic: Automated sync of Dockstore and GitHub apps  for Tools
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-473
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
FWIW, this gets complicated due to a number of ways in which Dockstore is currently built. For example, versioning is harvested from quay.io and then traced back to the GitHub repo. However, if there are two, then is gets messy and/or confusing. Permissions could also get weird with two repos if you have rights to one but not the other.

**Comment by SolomonShorser-OICR** [comment]
Hmmmm, that does sound tricky. :(

In the meantime, I've opened a pull request to Jonathan for the consensus-calling tool, to add the CWL to the repo with the Dockerfile.
