### ISSUE TITLE
Separate "Add Tool" for manual and automated tools

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#717]
### Desired behaviour
Current "Add Tool" button may create tool in manual mode or fully-automated mode depending on different circumstances.  What build mode the tool will be created with is not shown to the user until after creation.  They should be split up to explicitly indicate what mode the tool will be in.

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.2
DockstoreApi - 1.2.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-482)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-482
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@garyluu  I believe that you worked on this, is this still an issue?
