### ISSUE TITLE
Azure file provisioning plugin

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#737]
### Desired behaviour

Build an Azure plugin along the lines of https://github.com/dockstore/s3-plugin to read/write files from Azure. https://github.com/Azure/azure-storage-java#code-sample provides examples of code for read/writing from Azure

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-483)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-483

**Comment by melainalegaspi** [comment]
reopen if needed
