### ISSUE TITLE
Create parameter json including implicit input variables?

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#739]
### Desired behaviour

See https://github.com/ICGC-TCGA-PanCancer/pcawg-consensus-calling-tool/blob/master/consensus-calling.cwl and see how `dbs_dir` is defined in inputs before use while `output_file_name` is not. 
Regardless of whether this is valid CWL or not, we'll probably have to address this case for commands like `dockstore tool convert entry2json --entry quay.io/pancancer/pcawg-consensus-caller:latest > Dockstore.json` which list necessary parameters

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.2
DockstoreApi - 1.2.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-484)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-484

**Comment by denis-yuen** [comment]
Or just see how https://github.com/common-workflow-language/cwltool/issues/398 plays out

**Comment by melainalegaspi** [comment]
Closing until someone asks for it
