### ISSUE TITLE
Finalize JSON+LD for Tools and Workflows

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#750]
### Desired behaviour

This ticket covers adding more free-form attributes from JSON-LD metadata. This is more free-form since every tool and workflow can add metadata from different schemas.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-486)
┆Issue Type: Story
┆Sprint: Seabright Sprint 9 Ice Boat
┆Issue Number: DOCK-486

**Comment by agduncan94** [comment]
Adding JSON-LD helps with automated FAIR assessments https://fairshake.cloud/documentation/jsonschema/

**Comment by coverbeck** [comment]
I think this overlaps with #341 . Whoever tackles this or that one should consider the other.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

There is some overlap in tickets, but let's consider this done when there is a merged PR that sets the JSON-LD for tools and workflows. At this point, the exact schema/context/type is not defined, but it should be as part of the PR. Possibly have more than one.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

This ticket does overlap with the work Shreya was doing. I have assigned PR https://github.com/dockstore/dockstore-ui2/pull/667 ( https://github.com/dockstore/dockstore-ui2/pull/667|smart-link )  to Emily; finishing up the PR should wrap up this ticket.

**Comment by denis-yuen** [comment]
PR merged, reviewed as part of https://github.com/dockstore/dockstore/issues/341 
Open new issues for further improvements
