### ISSUE TITLE
Location relative paths don't work for file provisioning

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#906]
### Expected behaviour
If the location in the parameter file contains a local relative path, Dockstore should convert it to absolute

### Actual behaviour
If the location in the parameter file contains a local relative path, Dockstore doesn't seem to be able to convert it to absolute

### Steps to reproduce the behaviour 
Run the knoweng synapse submit workflow

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-503)
┆Issue Type: Bug
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-503

**Comment by denis-yuen** [comment]
If I understand correctly, to be clear, `location` is a CWL keyword. 
The workaround currently is to use `path` rather than `location`.
