### ISSUE TITLE
Starring entries should be hooked into a notification system

### ISSUE THREAD

**Issue by keiranmraine** [dockstore/dockstore#910]
## Feature Request 

If you start a tool do you get notifications of new releases and additions to the discussion threads?
I know it affects ranking.

### Desired behaviour

More a query than a request but the above would be good.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-504)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-504
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@keiranmraine 
So right now, it accomplishes two things. 
1) As mentioned, it affects the default sort for browsing 
2) It also provides for a "bookmarks"-like view under your profile -> starred

Notifications of new releases and additions to the discussion threads would be a great idea as well!

Implementer: see also #818

**Comment by denis-yuen** [comment]
For now, let's just make sure there's an easy to find FAQ entry for this

**Comment by agduncan94** [comment]
@denis-yuen would it make most sense in the FAQ or in the user tutorial section?

**Comment by denis-yuen** [comment]
I'm thinking a brief mention in user tutorial and a link to a longer explanation of side-effects in the FAQ, but I don't feel strongly about it.

**Comment by agduncan94** [comment]
Added docs in https://github.com/ga4gh/dockstore/pull/1279

**Comment by denis-yuen** [comment]
See also #1646
