### ISSUE TITLE
Home page for dock store for users who are not signed in could show a quick overview of Dockstore

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#925]
Idea: Similar to Github's [home page](https://github.com) (when not signed on) or Jupyter Notebook's [home page](http://jupyter.org), we could give a nice quick overview with pretty diagrams about Dockstore. This would only show to users who are not logged on.

This format seems to be fairly popular for online tools/websites.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-505)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-505
┆Epic: Home Page Changes

**Comment by agduncan94** [comment]
We would need to figure out what to show for logged in users. Perhaps a dashboard like github showing updates/the user's tools and workflows.

**Comment by denis-yuen** [comment]
Yeah
Throwing some ideas into the air, 
New json or descriptors added to their organizations or starred tools. 
Comments on their tools or starred.

**Comment by denis-yuen** [comment]
Now a thing
