### ISSUE TITLE
When viewing starred users, there should be a link to go to a user's Dockstore page

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#938]
When looking at the starred users page for a tool or workflow, we list the users along with their github username. Should we have these usernames as links to the corresponding github account page?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-506)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-506
┆sprint: SEAB 82- Karen
┆taskType: Story

**Comment by denis-yuen** [comment]
Alternatively, maybe their Dockstore profile page or a search for their author name?

**Comment by agduncan94** [comment]
I think the profile page makes the most sense, though we will have to figure out how we want to design that.

**Comment by denis-yuen** [comment]
Should do both, the more the better I think in terms of trust

**Comment by eileenzhh** [comment]
It seems like the starred user lists already works by linking the username to the dockstore user-page, no work needed :)
