### ISSUE TITLE
Ensure default is set before publishing

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#970]
From our discussion, it seems that a tool/workflow with no default set will use the latest tag to get entry information such as description. But a Quay.io tool isn't guaranteed to have a latest tag, and a git workflow doesn't necessarily have a latest branch. Forcing users to set default for an entry before publishing seems to make sense, as they can have better control over entry specific information, such as description.

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

  for Tools

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-510)
┆epic: Automated sync of Dockstore and GitHub apps  for Tools
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-510
┆sprint: Seabright Sprint 77- Eelektrik
┆taskType: Story

**Comment by garyluu** [comment]
Coincidentically saw this while trying to publish my github app tool
