### ISSUE TITLE
Refresh should be more intelligent about missing tokens

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#978]
## Bug Report
This contains 2 parts.

### Expected behaviour
1. Before actually refreshing, check which tools (Quay.io, GitLab, or DockerHub) the user currently has.  Make sure they have the tokens for it (exception being DockerHub) by throwing an error.  Special case: If the user has no tools, throw an error saying they need a Quay.io token.
2. During the actual refreshing, gather up all the errors and then return them all at once.

### Actual behaviour
No errors are returned

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-511)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-511
┆Sprint: Sprint 68- Smoothbound shark
┆Issue Type: Bug

**Comment by denis-yuen** [comment]
Also, refresh can be more intelligent. Skipping branches/tags seen before with this version of Dockstore (but allowing an override in case of corrupted data or temporary outages?) 
See also #1780

**Comment by garyluu** [comment]
Looks like 1. doesn't really apply anymore because of the removal of the refresh all endpoint

**Comment by garyluu** [comment]
Assuming 2. is for ​/users​/{userId}​/containers​/{organization}​/refresh
