### ISSUE TITLE
Tooltester Self Signed Certificate

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#988]
### Desired behaviour
Self-signed certificate for the jenkins master server

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-512)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-512

**Comment by denis-yuen** [comment]
Still applicable

**Comment by denis-yuen** [comment]
SEAB ticket if anything
