### ISSUE TITLE
There should be an option to cancel edit mode when on the info tab of a tool/workflow

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#991]
On the tool/workflow info tab, when a user is editing a path, they should be able to cancel. Currently to cancel you have to refresh.

We also need to be sure that the editing state is not preserved when we select another tool/workflow.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-514)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-514

**Comment by denis-yuen** [comment]
Seems to already exist
